import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a30_n = {
    0: "El Verdadero Enfrentamiento de Hermanitas: Siscalipse",
    4: "Lo que Kirino nos muestra triunfante es--",
    7: "«Siscaly» -- El título oficial es Shin Imouto Taisen Siscalypse (El Verdadero Enfrentamiento de Hermanitas: Siscalipse)",
    8: "Aunque parece un juego de aventuras, en realidad es un juego donde entrenas a tu «hermanita» y la enfrentas contra otras en línea.",
    9: "Y además, la chica que pierde en la batalla tendrá su disfraz destrozado de manera vergonzosa...",
    10: "Kirino adora ese juego.",
    23: "Kirino y Kuroneko... Parece que ambas están «muy MUY interesadas» en el premio del torneo.",
    24: "Aunque esas dos normalmente están en malos términos, esta vez parece que comparten un objetivo común.",
    25: "...¿Eh? ¡¿Lo que acaba de pasar rápidamente?!",
    26: "¡?! Y dentro de mi cabeza la palabra clave «Torneo del Juego Siscaly» está atascada y se niega a soltarse...",
    27: "Es lo mismo que con la «Conversación a Dueto»; siento como si estuviera jugando un juego.",
    28: "Soy un estudiante de tercer año de preparatoria, ¡no un chuuni! Gracias a ellos, mi pacífica vida ordinaria se corrompió con excentricidades irracionales...",
    29: "De acuerdo, el nombre exacto de este sistema será: Sistema O.R.E. (Order.Record.Effect)",
    34: "Ah... Un apoyo impresionante...",
    35: "«Los cuatro buscaremos la victoria a toda costa»...",
    36: "¿Por qué incluso yo tengo que...? ¡Espera, un momento?!",
    37: "Hay algo en la parte superior izquierda que me molesta... ¿Es esa la habilidad del sistema O.R.E?",
    38: "Con el poder todopoderoso de manipular y controlar todo a mi alcance... ¿Es este el nuevo poder con el que fui bendecido?",
    39: "Bueno, dejaré de lado estos delirios chuuni. Si quiero unirme al torneo, solo tendré que seleccionarlo.",
    85: "Sin embargo...",
    86: "Con esas tres encerradas en el mismo cuarto, no puedo pensar que terminará sin que algo malo ocurra.",
    87: "Especialmente Kirino y Kuroneko. Cuando se trata de victoria o derrota, cualquier error y se lanzarán a la yugular.",
    91: "Esa es nuestra Saori. Hábilmente las reunió.",
    95: "...Si son ellas, estará bien.",
    99: "No me importa perder, pero ellas quedarían MUY devastadas.",
    100: "No quiero defraudarlas participando en el torneo, pero no hay una buena razón para rechazar...",
}
a30_s = {
    1: ("Aunque God Eater es súper interesante, no los llamé hoy solo para jugar multijugador.", "Kirino"),
    2: ("Oh, ¿eso crees? Entonces, ¿cuál es tu razón para llamarnos? Por favor, explícate.", "Kuroneko"),
    3: ("¡Tadah!", "Kirino"),
    5: ("¡Ohoh, Kiririn-shi! ¡«Siscaly», ¿no es así?!", "Saori"),
    6: ("¡Sí!", "Kirino"),
    11: ("¿Qué hay con «Siscaly»? ¿Quieres que todos jueguen entre sí?", "Kyousuke"),
    12: ("Ejeje, es un poco diferente...", "Kirino"),
    13: ("Mira, mira-", "Kirino"),
    14: ("¿Un 【torneo de Siscaly】?", "Kyousuke"),
    15: ("¡Sí! ¡Es un torneo para reunir a todos los jugadores del país con confianza en sus habilidades y decidir quién es el usuario de hermanitas más fuerte!", "Kirino"),
    16: ("¡Es un torneo hecho solo para mí!", "Kirino"),
    17: ("¿Cómo podría NO participar en eso?", "Kirino"),
    18: ("¡Estamos aquí hoy para practicar para este torneo!", "Kirino"),
    19: ("Si hablas de ese torneo, yo también tengo algo de conocimiento.", "Saori"),
    20: ("Se dice que el ganador recibirá un premio de parte de los organizadores.", "Saori"),
    21: ("*trago*", "Kirino"),
    22: ("Mmf-hmm...", "Kuroneko"),
    30: ("Dicho esto...", "Kirino"),
    31: ("Los cuatro buscaremos la victoria a toda costa.", "Kirino"),
    32: ("Así que al final sí puedes hacer una buena propuesta.", "Kuroneko"),
    33: ("¡Kiririn-shi, es una buena idea!", "Saori"),
    40: ("¡¿Lo que significa que yo también tendré que participar?!", "Kyousuke"),
    41: ("¿No es obvio? ¿Qué dices?", "Kirino"),
    42: ("Eso significa que si por casualidad gano el torneo, también tendría derecho a recibir el 【premio del torneo】, ¿no?", "Kyousuke"),
    43: ("¿Eh? ¿También te interesan los productos de Siscaly?", "Kirino"),
    44: ("Aha, ya veo. ¿También despertaste al «moe de las hermanitas»?", "Kirino"),
    45: ("...Por supuesto que no.", "Kyousuke"),
    46: ("¿Dijiste algo?", "Kirino"),
    47: ("Nada. Todos se unen al torneo de Siscaly. Eso es un proyecto divertido.", "Kyousuke"),
    48: ("Jeje, ¿no es así?", "Kirino"),
    49: ("Sin embargo...", "Kyousuke"),
    50: ("Lo siento, pero pasaré.", "Kyousuke"),
    51: ("¿Eh? ¿Qué estás diciendo?", "Kirino"),
    52: ("Todos se unen al torneo por los premios, ¿verdad?", "Kyousuke"),
    53: ("Obviamente.", "Kirino"),
    54: ("Pero si un principiante como yo participara, no sería más que una carga.", "Kyousuke"),
    55: ("No hay necesidad de reducir a propósito sus posibilidades de ganar.", "Kyousuke"),
    56: ("Eso no será un problema si te sometes a un entrenamiento especial.", "Kirino"),
    57: ("Los oponentes son jugadores con mucha experiencia, ¿verdad? No creo que un entrenamiento de última hora lo logre.", "Kyousuke"),
    58: ("Incluso si mejoro en el juego, siento que sería una falta de respeto para quienes realmente aman Siscaly.", "Kyousuke"),
    59: ("...¿Qué quieres decir?", "Kirino"),
    60: ("Hmm... Por ejemplo.", "Kyousuke"),
    61: ("Si alguien a quien no le gustan las hermanitas en absoluto completara rápidamente un juego de hermanitas desgarrador y dijera que es un juego de mierda, ¿cómo te", "Kyousuke"),
    62: ("sentirías?", "Kyousuke"),
    63: ("...Ah.", "Kirino"),
    64: ("¿Ves? Así es como son las cosas.", "Kyousuke"),
    65: ("No soy fan de Siscaly, y si participara en el torneo de Siscaly y ganara, sería una falta de respeto hacia los verdaderos fans de Siscaly.", "Kyousuke"),
    66: ("P-Pero...", "Kirino"),
    67: ("Kiririn-shi, lo que dijo Kyousuke-shi es justificable.", "Saori"),
    68: ("Pero, el torneo requiere equipos de dos personas... ahora somos uno de más...", "Kirino"),
    69: ("Si ese es el caso, ¿qué tal si conseguimos un miembro de las redes sociales?", "Saori"),
    70: ("Por supuesto, sería más feliz si tú también participaras, Kyousuke-shi...", "Saori"),
    71: ("¿No vas a venir?", "Kuroneko"),
    72: ("...Sí, no voy.", "Kyousuke"),
    73: ("Gnnnnnn...", "Kirino"),
    74: ("...Ya veo. Este tipo no va a participar.", "Kirino"),
    75: ("Lo siento, Kirino. Aunque te tomaste la molestia de invitarme.", "Kyousuke"),
    76: ("...Hmph.", "Kirino"),
    77: ("No es gran cosa. Además, ¿no sería más fácil con una persona menos en el entrenamiento especial?", "Kirino"),
    78: ("Ya veo. Kiririn-shi quería participar en el torneo junto con Kyousuke-shi.", "Saori"),
    79: ("¿Eh? No te equivoques. Nadie dijo tal cosa.", "Kirino"),
    80: ("¿Ya veo, ya veo? ¡No poder jugar conmigo te pone tan triste!", "Kyousuke"),
    81: ("¡Qué asco! ¡Ni de broma!", "Kirino"),
    82: ("¡No seas tímida!", "Kyousuke"),
    83: ("¡Cállate! ¡Todos los que no participen en el torneo, salgan del cuarto de inmediato!", "Kirino"),
    84: ("Sí, sí...", "Kyousuke"),
    88: ("¡Bueno, si perdemos el tiempo discutiendo, nuestras posibilidades de ganar disminuirán!", "Saori"),
    89: ("¡Es hora de practicar! ¡Nuestro entrenamiento de Siscaly comienza de inmediato!", "Saori"),
    90: ("Entendido...", "Kirino"),
    92: ("Déjanos a tu hermanita; Senpai solo necesita esperar noticias de la victoria.", "Kuroneko"),
    93: ("Te arrepentirás para siempre de no participar, pero espera con ansias escuchar nuestras hazañas.", "Kuroneko"),
    94: ("Sí, las esperaré con ansias.", "Kyousuke"),
    96: ("Saori, Kuroneko. Por favor, cuiden de Kirino.", "Kyousuke"),
    97: ("¡A-Apurate y sal!", "Kirino"),
    98: ("Con mis habilidades actuales, ¿no terminaré avergonzándome frente a los demás?", "Kyousuke"),
}

a32_n = {
    0: "El Verdadero Enfrentamiento de Hermanitas: Siscalipse",
    28: "No digas eso sobre ti misma.",
    46: "Esa mocosa...",
}
a32_s = {
    1: ("...¿Qué acabas de decir?", "Kirino"),
    2: ("Nada, de verdad...", "Kyousuke"),
    3: ("Oye, tú. ¿Entiendes la posición en la que estás ahora mismo?", "Kirino"),
    4: ("¿Mi posición?", "Kyousuke"),
    5: ("Te lo diré una vez más ya que no parece que lo entiendas.", "Kirino"),
    6: ("Todo lo que necesitas hacer es escuchar lo que diga. ¿Está claro?", "Kirino"),
    7: ("¡Sí, entendido!", "Kyousuke"),
    8: ("¡¿Creías que diría eso?!", "Kyousuke"),
    9: ("Tu pronunciación apesta, está a nivel de un fracasado.", "Kirino"),
    10: ("¡Fracasado es una palabra tabú para alguien que se examina este año!", "Kyousuke"),
    11: ("Hah...", "Kirino"),
    12: ("Esta discusión es una pérdida de tiempo.", "Kirino"),
    13: ("U-ugh... Tú...", "Kyousuke"),
    14: ("¿Qué pasa? ¿Tienes algo que decir?", "Kirino"),
    15: ("No realmente...", "Kyousuke"),
    16: ("Ah, ¿de verdad? Qué decepcionante...", "Kirino"),
    17: ("Quiero decir, gracias a mí, podrás unirte al torneo...", "Kirino"),
    18: ("Podrías mostrar un poco de gratitud.", "Kirino"),
    19: ("No, no recuerdo haber dicho que participaría.", "Kyousuke"),
    20: ("¿Eh? Aunque organicé esto para que tú, sin amigos, pudieras tener interacciones sociales.", "Kirino"),
    21: ("¡Las tengo! ¡Definitivamente tengo amigos!", "Kyousuke"),
    22: ("¡Y deja esa cara de «Mentira, estoy súper sorprendido»! ¡Incluso mis sentimientos pueden herirse!", "Kyousuke"),
    23: ("Además, ¿hay algún beneficio para mí al participar en este torneo?", "Kyousuke"),
    24: ("Si ganas, seré feliz. Si tu linda hermanita es feliz, tú también serás feliz!", "Kirino"),
    25: ("...A veces dices cosas terribles.", "Kyousuke"),
    26: ("¿Q-Qué... estás diciendo?", "Kyousuke"),
    27: ("¿No eres feliz? Estar junto a una chica tan linda. Es una oportunidad bastante rara.", "Kirino"),
    29: ("De todos modos, vas a unirte al torneo del juego Siscaly.", "Kirino"),
    30: ("Tendrás que poder ganar al menos 30 rondas consecutivas antes del torneo. Esa es la norma.", "Kirino"),
    31: ("¡¿30 rondas consecutivas?! ¡Imposible! ¡Totaalmente imposible!!", "Kyousuke"),
    32: ("¿Por qué te rindes antes de empezar?", "Kirino"),
    33: ("No importa lo que digas, ¡imposible es imposible!", "Kyousuke"),
    34: ("¡Por eso! ¡Tienes que practicar!", "Kirino"),
    35: ("Incluso si somos fuertes, harás más daño que bien si nos arrastras.", "Kirino"),
    36: ("¡Excluyéndome a mí, de las otras tres, tú apestas más!", "Kirino"),
    37: ("...Creo que es imposible... Tu petición es simplemente demasiado irreal...", "Kyousuke"),
    38: ("No digas que no puedes.", "Kirino"),
    39: ("Por cierto, tendré mis exámenes este año y no tendré tiempo para esto, ¿me entiendes?", "Kyousuke"),
    40: ("Entonces solo haz tiempo. ¿No quieres jugar conmigo?", "Kirino"),
    41: ("Además, esto es inevitable.", "Kirino"),
    42: ("¿I-Inevitable?", "Kyousuke"),
    43: ("¡Ha sido decidido desde que naciste en este mundo!", "Kirino"),
    44: ("¡¿Ya está decidido?! ¡¿No tengo derecho a oponerme?!", "Kyousuke"),
    45: ("Por supuesto que no.", "Kirino"),
    47: ("De todos modos, cuento contigo.", "Kirino"),
    48: ("...Ggh...", "Kyousuke"),
    49: ("Bueno, eso concluye esto.", "Kirino"),
    50: ("¡Detente ahí mismo!", "Kyousuke"),
    51: ("Tsk, ¿qué pasa? ¿Por qué no lo dejas ya?", "Kirino"),
    52: ("Como - ya - dije...", "Kyousuke"),
    53: ("Si nos arrastraras, te...", "Kirino"),
    54: ("¿Te...?", "Kyousuke"),
    55: ("...Lo sabes, ¿verdad?", "Kirino"),
    56: ("¿Muerte? ¿Es la muerte?", "Kyousuke"),
    57: ("Ya está decidido por el destino que participarás.", "Kirino"),
}

data = {
    "000scriptAKYO_0030A.obj": build(a30_n, a30_s),
    "000scriptAKYO_0032T.obj": build(a32_n, a32_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))