import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0106_n = {
    0: "Ruta de Kuroneko · Desmayo En Medio Del Esfuerzo",
    6: "Así que está inconsciente...",
    7: "Así que seguramente no podrá reaccionar ante nada de lo que yo diga...",
    11: "...Realmente debería estar sosteniendo su mano en este momento...",
    12: "Sin embargo, la estoy cargando ahora mismo... Así que sopórtalo por un momento.",
    15: "...Pero, bueno...",
    16: "Hablando con honestidad, ¿no está demasiado liviana?",
    17: "Sus hombros, sus piernas, todos son tan delgados... Como si se rompieran si aplicara un poco de fuerza...",
    18: "Su peso... ciertamente es menos de la mitad del mío. Su cuerpo finalmente sucumbió a la fatiga después de trabajar tan duro.",
    19: "¡...Le haré entrar en razón cuando despierte!",
    23: "Qué... así que solo está teniendo un sueño...",
}
a0106_s = {
    1: ("¡Te estoy llevando a la enfermería ahora mismo!", "Kyousuke"),
    2: ("...Ah...", "Kuroneko"),
    3: ("...Senpai...", "Kuroneko"),
    4: ("¡¿Kuroneko?! Oye, ¿estás bien?", "Kyousuke"),
    5: ("Nnn... Senpai... Senpai...", "Kuroneko"),
    8: ("Está bien... Estoy justo aquí...", "Kyousuke"),
    9: ("Ah...", "Kuroneko"),
    10: ("Ah... Mm...", "Kuroneko"),
    13: ("Puedes sostener mi mano el tiempo que quieras cuando lleguemos a la enfermería...", "Kyousuke"),
    14: ("...Agh...", "Kuroneko"),
    20: ("¿Senpai...? ¿Estás... ahí...?", "Kuroneko"),
    21: ("...¿Kuroneko? ¿Estás despierta?", "Kyousuke"),
    22: ("Ahh... Aah...", "Kuroneko"),
    24: ("Sí, estoy aquí... así que solo relájate y descansa.", "Kyousuke"),
    25: ("...Nnn...", "Kuroneko"),
}

a0107_n = {
    0: "Ruta de Kuroneko · Exceso De Trabajo, Falta De Sueño Y Ansiedad",
    5: "Parece que Kuroneko... no va a despertar en el corto plazo.",
    7: "Además, esta es la primera vez... que estoy tan cerca del rostro de Kuroneko...",
    8: "Nunca habíamos estado tan cerca por la distancia entre nosotros.",
    9: "Sus mejillas están un poco rojas... Pero parece que se ha calmado... Eso es realmente genial...",
    10: "Últimamente ha estado de mal humor con frecuencia...",
}
a0107_s = {
    1: ("Aunque solo puedo realizar un examen médico simple aquí, esto es solo un caso simple de exceso de trabajo y falta de sueño.", "Doctor"),
    2: ("Uf... Me alegra escuchar eso...", "Kyousuke"),
    3: ("Bueno entonces, me iré por un tiempo, avísame cuando ella recupere la conciencia, ¿de acuerdo?", "Doctor"),
    4: ("Eso es lo que dijo el doctor, Kuroneko.", "Kyousuke"),
    6: ("Despierta pronto, tengo que regañarte sí o sí.", "Kyousuke"),
    11: ("Jeje... Será genial si su humor mejora cuando despierte.", "Kyousuke"),
    12: ("Nnn...", "Kuroneko"),
    13: ("Kuroneko, ¿estás despierta?", "Kyousuke"),
    14: ("Este lugar es...", "Kuroneko"),
    15: ("La enfermería. ¿No lo recuerdas? Te desmayaste de repente.", "Kyousuke"),
    16: ("...Sí lo recuerdo, bastante claramente.", "Kuroneko"),
    17: ("Dios... Pero, ya que estás inesperadamente llena de vigor, me siento bastante aliviado.", "Kyousuke"),
    18: ("Además, ¿no es solo falta de sueño y exceso de trabajo? No tienes que preocuparte tanto.", "Kuroneko"),
    19: ("Aunque no sea algo grave, si te desmayas, ¿no sería todo en vano?", "Kyousuke"),
    20: ("Cierto... Inicialmente pensé que podría continuar así... Soy realmente inútil.", "Kuroneko"),
    21: ("¡Tú...! Por Dios, no puedo contigo... No escucharás aunque te lo diga de nuevo, ¿verdad?", "Kyousuke"),
    22: ("Por supuesto. No estoy obligada a escucharte.", "Kuroneko"),
    23: ("Sí sí... Bueno, lo diré de nuevo solo por decirlo.", "Kyousuke"),
    24: ("En resumen, deja de exigirte de más... No puedo salir siempre a detenerte.", "Kyousuke"),
    25: ("...En cuanto a lo que pasó esta vez, siento que eres tú quien me hizo enojar sin razón en primer lugar...?", "Kuroneko"),
    26: ("Sí sí... Es mi culpa... Tómalo como culpa mía entonces.", "Kyousuke"),
    27: ("Pero sabes, deberías tener más cuidado ya que ya te desmayaste una vez. Será un problema si no tienes suerte.", "Kyousuke"),
    28: ("Está bien que me hagas preocupar. Después de todo, soy yo quien se preocupa por ti por voluntad propia.", "Kyousuke"),
    29: ("Sin embargo, si estás haciendo preocupar a los demás... deberías parar.", "Kyousuke"),
    30: ("Es mejor evitar poner a todos... tristes.", "Kyousuke"),
    31: ("...Tienes razón... Es algo que tampoco deseo ver.", "Kuroneko"),
    32: ("Sí, ¿en serio? Me alegra que estés dispuesta a escuchar.", "Kyousuke"),
    33: ("Bueno entonces... iré a buscar al doctor.", "Kyousuke"),
    34: ("......Espera.", "Kuroneko"),
    35: ("¿? ¿Qué pasa?", "Kyousuke"),
}

a0108_n = {
    0: "Ruta de Kuroneko · Exceso De Trabajo, Falta De Sueño Y Ansiedad",
    66: "Esto no está funcionando... Supongo que realmente no puedo detenerla...",
}
a0108_s = {
    1: ("...Tengo una pregunta para ti.", "Kuroneko"),
    2: ("...¿Qué es?", "Kyousuke"),
    3: ("...¿Por qué...? ¿Por qué te preocupas tanto por mí?", "Kuroneko"),
    4: ("¿Por qué preguntas?", "Kyousuke"),
    5: ("¿Acaso esto no es... un problema de otros para ti después de todo?", "Kuroneko"),
    6: ("¡Por supuesto que me preocupo!", "Kyousuke"),
    7: ("¿Cuántas veces te he dicho que estoy preocupado por ti?", "Kyousuke"),
    8: ("...Eso es solo que eres un entrometido.", "Kuroneko"),
    9: ("Aunque sea entrometido para ti, estoy realmente preocupado por ti. Tan preocupado que ni siquiera sé qué decir...", "Kyousuke"),
    10: ("Dios mío... esto realmente no es una respuesta.", "Kuroneko"),
    11: ("Aunque no puede contarse como una respuesta... se puede decir que es muy tu manera de hacer las cosas.", "Kuroneko"),
    12: ("...Decir «un problema de otros»... Eres realmente...", "Kyousuke"),
    13: ("¿Qué...?", "Kuroneko"),
    14: ("Si realmente piensas así, hasta yo me decepcionaré.", "Kyousuke"),
    15: ("¿En serio...", "Kuroneko"),
    16: ("Bueno, no quieres decir lo que dices en serio, eso lo sé.", "Kyousuke"),
    17: ("Jeh... Por Dios, ¿qué es lo que realmente sabes de mí?", "Kuroneko"),
    18: ("Aunque eres muy obstinada, sí te preocupas por tus amigos. Lo sé bien. Por eso sé que no estás hablando en serio.", "Kyousuke"),
    19: ("Me sorprendes... Decir que entiendes a los demás con solo eso...", "Kuroneko"),
    20: ("Diré algo honesto...", "Kuroneko"),
    21: ("Tienes mi más sincero agradecimiento por preocuparte por mí...", "Kuroneko"),
    22: ("Ya veo...", "Kyousuke"),
    23: ("Pero no entiendo tus sentimientos.", "Kuroneko"),
    24: ("¿Mis... sentimientos?", "Kyousuke"),
    25: ("Sí. ¿Qué estabas pensando realmente cuando intentabas detenerme? ¿Y cuál es el origen de ese pensamiento? ¿Qué ganas al detenerme?", "Kuroneko"),
    26: ("¿No lo entiendes?", "Kyousuke"),
    27: ("Sí. No entiendo lo que sea que estés haciendo.", "Kuroneko"),
    28: ("Tú... Realmente estás siendo una tonta aquí.", "Kyousuke"),
    29: ("...Es verdad. Quizás ambos somos tontos, tú y yo. Demasiado tontos para ser salvados.", "Kuroneko"),
    30: ("Oye, ¿incluso yo?", "Kyousuke"),
    31: ("¿No es algo dado?", "Kuroneko"),
    32: ("Entonces admites que tú también eres una tonta.", "Kyousuke"),
    33: ("Al menos no tengo la intención de fingir ser una persona sabia. En cualquier caso...", "Kuroneko"),
    34: ("...Está bien, aunque no lo entiendas. No pensé que lo entenderías.", "Kyousuke"),
    35: ("...Ya veo. No... molestar a la gente, eso es algo bueno.", "Kuroneko"),
    36: ("Sin embargo, no te exijas de más.", "Kyousuke"),
    37: ("Eso...lo rechazo.", "Kuroneko"),
    38: ("¿Por qué?", "Kyousuke"),
    39: ("Porque soy una creadora.", "Kuroneko"),
    40: ("...¿Eh? ¿Qué significa eso...?", "Kyousuke"),
    41: ("No puedes crear un producto excelente si no experimentas las penurias de un creador. No soy una genio, así que estoy destinada a caminar por este camino espinoso.", "Kuroneko"),
    42: ("No sé de qué estás hablando... ¿Cómo llegamos a este tema?", "Kyousuke"),
    43: ("Las creaciones suelen ir acompañadas de enormes penurias...", "Kuroneko"),
    44: ("Es como caminar en la oscuridad, no existe tal cosa como una respuesta definitiva. Aunque algunos caminos son de hecho mejores que otros, siempre están cerca de nosotros.", "Kuroneko"),
    45: ("Y buscarlos continuamente es nuestro propósito, como creadores.", "Kuroneko"),
    46: ("Aun así, seguro que no tienes que exigirte hasta ese punto, ¿verdad?", "Kyousuke"),
    47: ("No, eso es necesario. No lo entenderás ya que no eres un creador.", "Kuroneko"),
    48: ("Guh... No puedo decir nada si lo pones así...", "Kyousuke"),
    49: ("No estabas tan agotada cuando trabajabas en ese juego la vez pasada...", "Kyousuke"),
    50: ("El presente y el pasado, son completamente diferentes.", "Kuroneko"),
    51: ("...Esto es ser demasiado duro contigo misma...", "Kyousuke"),
    52: ("Debe hacerse para este nivel de trabajo, hay muchos otros que darían su vida por sus obras también.", "Kuroneko"),
    53: ("No me matará si me fuerzo hasta este grado, ¿verdad?", "Kuroneko"),
    54: ("Aunque sea así...", "Kyousuke"),
    55: ("Está bien así. Porque esto es lo que he deseado.", "Kuroneko"),
    56: ("Definitivamente crearé una buena obra cuando experimente tales penurias...", "Kuroneko"),
    57: ("Eso es lo que creo firmemente...", "Kuroneko"),
    58: ("¿No es una suposición errónea? Solo porque estás pasando por tiempos difíciles, ¿estás usando esa razón para consolarte?", "Kyousuke"),
    59: ("Quién sabe. Sin embargo, es verdad que muchos creadores han caminado por el mismo camino.", "Kuroneko"),
    60: ("Y así, yo también caminaré por este camino.", "Kuroneko"),
    61: ("¡¿Qué es eso?! ¿¡Creación o lo que sea, hay solo sufrimiento en crear?!", "Kyousuke"),
    62: ("No, no solo siento dolor. También hay muchos tipos de alegría que estoy experimentando, por eso soy capaz de soportar este sufrimiento.", "Kuroneko"),
    63: ("¿Soportar...? ¿Estás entrenando para ser monje?", "Kyousuke"),
    64: ("Supongo... Esto podría incluso acercarse a eso.", "Kuroneko"),
    65: ("Es solo sufrimiento por diferentes objetivos. Ellos se dedican a los Dioses, y yo me dedico a mis obras maestras. Esa es la única diferencia.", "Kuroneko"),
    67: ("Oye... Solo un poco, lo que sea... ¿hay algo en lo que pueda ayudar?", "Kyousuke"),
    68: ("Si lo pones así... con más razón no puedo dejarte sola...", "Kyousuke"),
    69: ("...Creo que no hay nada.", "Kuroneko"),
    70: ("Así que este dolor será solo mío. Esta es mi creación, por eso, este dolor es algo que solo me pertenece a mí...", "Kuroneko"),
    71: ("¿Por qué te guardas todo eso para ti?", "Kyousuke"),
    72: ("Puedo tener el sentido de orgullo precisamente porque hay ese sentido de penuria. Porque eso es lo que produje.", "Kuroneko"),
    73: ("¿¡No puedes hacer otra cosa para ese sentido de orgullo!?", "Kyousuke"),
    74: ("Quiero una prueba. Una prueba absoluta para mi obra trascendental.", "Kuroneko"),
    75: ("...¿Realmente piensas así?", "Kyousuke"),
    76: ("Estás poniendo esa cara de nuevo... Hablo en serio.", "Kuroneko"),
    77: ("....¿Hablas en serio?", "Kyousuke"),
    78: ("Jeh... Obviamente. No importa cuánto te preocupes por mí, es inútil. ¿Finalmente lo entendiste?", "Kuroneko"),
    79: ("Nuestra clase es codiciosa. Hasta el punto que la gente común lo considera locura.", "Kuroneko"),
    80: ("¿Por eso no te detendrás?", "Kyousuke"),
    81: ("Sí, exactamente.", "Kuroneko"),
}

a0109_n = {
    0: "Ruta de Kuroneko · Creencia Y Orgullo",
    35: "Está bien así como está ahora. Mis preocupaciones no serán en vano siempre y cuando pueda ayudarla un poco.",
    36: "Si va a ser imprudente otra vez, la detendré antes de que se desmaye.",
    53: "Y con eso, comenzó la sesión de consejería de vida de Kuroneko.",
    54: "Realmente no pensé que la situación se desarrollaría de esta manera.",
    59: "Esta es la primera vez que veo a una Kuroneko tan honesta y dócil... Quiero decir...",
    67: "Por Dios, dimos un gran rodeo... Sin embargo, este rodeo... ¿parece tener algún mérito?",
}
a0109_s = {
    1: ("Esta es mi propia decisión.", "Kuroneko"),
    2: ("Es algo que he decidido terminar, con mi espíritu, mi creencia y mi orgullo en juego.", "Kuroneko"),
    3: ("Así que, por favor, no digas más.", "Kuroneko"),
    4: ("...Pero sabes, ¿no es esto un poco diferente ya que la gente se preocupa por ti?", "Kyousuke"),
    5: ("Imagina desmayarte y ser enviada al hospital. Kirino, Saori y los miembros del club estarían preocupadísimos por ti.", "Kyousuke"),
    6: ("Si no tienes cuidado, las actividades del club podrían muy bien suspenderse por eso.", "Kyousuke"),
    7: ("...¿Y? ¿No te lo he dicho antes? No estoy obligada a escuchar tus palabras.", "Kuroneko"),
    8: ("...Eres como una hermanita para mí.", "Kyousuke"),
    9: ("¿No es natural que yo, un hermano, me preocupe por ti?", "Kyousuke"),
    10: ("...Ya veo.", "Kuroneko"),
    11: ("Kirino lo ha dicho antes. Eres una gata indómita, así que es necesario ser dominante.", "Kyousuke"),
    12: ("Jeh, eso es algo que diría una chica que no sabe nada...", "Kuroneko"),
    13: ("¿Y qué con eso? ¿No es mejor que te alejes antes de que te arañe?", "Kuroneko"),
    14: ("Es verdad, dolió. Que me arañaras la última vez.", "Kyousuke"),
    15: ("Sí, es verdad. Eres demasiado problemático, así que tuve que sacar las garras.", "Kuroneko"),
    16: ("Pero, a pesar de todo ese dolor...", "Kyousuke"),
    17: ("Me tranquiliza un millón de veces más que verte caer.", "Kyousuke"),
    18: ("Qué-...", "Kuroneko"),
    19: ("En comparación con eso, tus garras son solo un mero juguete.", "Kyousuke"),
    20: ("¡Me he vuelto fuerte! ¡No seré ahuyentado por tus garras!", "Kyousuke"),
    21: ("Por eso usaré cualquier método para detenerte la próxima vez que vuelvas a ser imprudente. ¡Espero que estés preparada!", "Kyousuke"),
    22: ("*suspiro*", "Kuroneko"),
    23: ("Por Dios... eres tan...", "Kuroneko"),
    24: ("Eso es. Los mortales de piel gruesa de este mundo viven sin ningún sentido de vergüenza...", "Kuroneko"),
    25: ("Oye tú...", "Kyousuke"),
    26: ("Supongo que la próxima vez no te arañaré, sino que te morderé...?", "Kuroneko"),
    27: ("Estoy bastante feliz si prefieres morderme. Al menos tu cara estará más cerca de mí.", "Kyousuke"),
    28: ("Estás más allá de toda esperanza...", "Kuroneko"),
    29: ("Está bien preocuparse por los demás, pero ¿qué tal considerar tu 【Propio Futuro】 por un momento?", "Kuroneko"),
    30: ("Entonces no dejes que me preocupe demasiado por ti.", "Kyousuke"),
    31: ("¿Pero no es eso solo que estás tomando las cosas en tus propias manos?", "Kuroneko"),
    32: ("Bueno, supongo que es verdad.", "Kyousuke"),
    33: ("Eso es todo. Eso es todo lo que quería decir.", "Kyousuke"),
    34: ("Me voy entonces.", "Kyousuke"),
    37: ("Ah...", "Kuroneko"),
    38: ("...¿Hmm?", "Kyousuke"),
    39: ("...E-Espera.", "Kuroneko"),
    40: ("¿Qué pasa?", "Kyousuke"),
    41: ("...Um...", "Kuroneko"),
    42: ("¿Hmm? ¿Qué pasa?", "Kyousuke"),
    43: ("El... oráculo de hace un momento...", "Kuroneko"),
    44: ("Oye, ¿qué te pasa, Kuroneko? ¿De qué oráculo hablas?", "Kyousuke"),
    45: ("Me gustaría tener una sesión de consejería de vida.", "Kuroneko"),
    46: ("Jeh... Jejeje.", "Kyousuke"),
    47: ("Deja de reírte. Hablo en serio.", "Kuroneko"),
    48: ("Aquí también hablo en serio. ¿Consejería de vida, dices?", "Kyousuke"),
    49: ("Nunca esperé eso de ti.", "Kyousuke"),
    50: ("Lo escuché hace tiempo de ella. Lo dijo con un sentido de orgullo también. Estoy segura de que escucharás lo que tenga que decir si lo pongo de esta manera, ¿no?", "Kuroneko"),
    51: ("Así que... ¿podrías escuchar mis problemas?", "Kuroneko"),
    52: ("¡Por supuesto, adelante!", "Kyousuke"),
    55: ("...He estado dibujando el manuscrito del evento, todo por mí misma.", "Kuroneko"),
    56: ("Solo quiero confirmar hasta dónde puedo llegar por mi cuenta ahora mismo...", "Kuroneko"),
    57: ("Pero parece que no puedo terminar a tiempo para la fecha límite si esto continúa.", "Kuroneko"),
    58: ("Por eso... ¿podrías ayudarme?", "Kuroneko"),
    60: ("Jeje, ¿no es lo mismo que la sugerencia que te di antes?", "Kyousuke"),
    61: ("...Cierto. Solo por ahora, lo admitiré. Estaba siendo obstinada antes.", "Kuroneko"),
    62: ("¿Está bien así? ...¿Y? ¿Lo aceptarás?", "Kuroneko"),
    63: ("Por supuesto que sí.", "Kyousuke"),
    64: ("Ya que lo has puesto así, te ayudaré sin importar qué.", "Kyousuke"),
    65: ("Ya veo... Entonces, a partir de mañana, contaré contigo.", "Kuroneko"),
    66: ("Sí, por favor.", "Kyousuke"),
}

a0110_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko",
    1: "¡Finalmente, comenzaré a trabajar como asistente de Kuroneko desde hoy!",
    2: "Bueno, es bueno que me haya preparado antes de llegar, sin embargo...",
    4: "Hmm...",
    5: "Estoy seguro de que es un lugar al que he ido muchas veces antes...",
    6: "¿Hmm? ¿Podría ser que vamos a comenzar a trabajar ahí?",
    7: "¿O vamos a algún otro lugar una vez que nos encontremos?",
    8: "No, no parece correcto... Deberíamos ir a algún lugar... cómo decirlo...",
    9: "Cierto, cierto. Debería ser un lugar donde podamos trabajar.",
    10: "¿Dónde podría ser...",
    11: "Todavía son vacaciones de verano, así que creo que cualquier lugar debería estar bien...",
    12: "Supongo que esperaré aquí.",
    13: "Kuroneko seguramente vendrá.",
    15: "Vine con ánimos, pero... cuando la otra parte no está aquí, me pone un poco nervioso.",
    16: "Pero aún así, es un poco temprano para la hora acordada.",
    17: "Si espero aquí, debería estar bien...",
    18: "Bueno, por eso vine pero...",
    20: "Bueno, si espero un poco, vendrá seguro...",
    21: "No viene en absoluto...",
    22: "Me siento... inquieto de repente...",
    23: "¿Es este realmente el punto de encuentro?",
    24: "De algún modo, tengo un mal presentimiento...",
    25: "¿Podría ser que me equivoqué?",
    26: "Si fuera a mirar en otros lugares, en cuanto al tiempo, sería mi última oportunidad de ir ahora...",
    27: "Gah, esto es problemático.",
    28: "¡Estoy esperando aquí! ¡Estoy seguro de que es aquí! ¡Probablemente es Kuroneko quien llega tarde!",
    29: "---fue lo que pensé, pero...",
    30: "Ella todavía no ha venido.",
    31: "¿Eh? ¿Entonces realmente me equivoqué?",
    36: "¿Así que ya está aquí? ...Maldición, así que llegué tarde...",
    58: "Ustedes dos seguramente se pelearían. ¿Qué tal otros lugares...",
    60: "Aun así... ¿Qué pasaría si su condición física empeora...",
    61: "El salón de clases tiene aire acondicionado, pero no podemos encenderlo como queramos...",
    62: "¿No hay otros lugares más frescos...?",
}
a0110_s = {
    3: ("El punto de encuentro debería estar por aquí, supongo?", "Kyousuke"),
    14: ("Kuroneko todavía no ha llegado...", "Kyousuke"),
    19: ("Kuroneko todavía no ha llegado...", "Kyousuke"),
    32: ("Es de Kuroneko...", "Kyousuke"),
    33: ("¿Cuánto tiempo más me harás esperar? Solo eres un criado y ¿tienes ese descaro?", "Kuroneko"),
    34: ("...Estoy esperando en el salón de clases.", "Kuroneko"),
    35: ("...Lo siento.", "Kyousuke"),
    37: ("Vaya, eres sorprendentemente rápido.", "Kuroneko"),
    38: ("Esa es mi línea. En realidad pensé en venir más temprano.", "Kyousuke"),
    39: ("Soy yo quien te invitó aquí, ¿recuerdas? Es un hecho que llegaré antes.", "Kuroneko"),
    40: ("Maldición, pensé en llegar antes que tú, y luego esperarte un poco...", "Kyousuke"),
    41: ("Oh, tu intención es admirable.", "Kuroneko"),
    42: ("Decidí pasar mis vacaciones de verano por tu bien. Por eso quería mostrarte mi determinación.", "Kyousuke"),
    43: ("...¿En serio.", "Kuroneko"),
    44: ("Bueno entonces... entonces no me retrases y da lo mejor de ti.", "Kuroneko"),
    45: ("Sí, déjamelo a mí.", "Kyousuke"),
    46: ("Bueno entonces, permíteme explicarte las áreas que debes tener en cuenta...", "Kuroneko"),
    47: ("Sí... Espera, sobre eso.", "Kyousuke"),
    48: ("¿Qué pasa?", "Kuroneko"),
    49: ("¿No hace un poco de calor aquí? ¿Estás bien?", "Kyousuke"),
    50: ("Estoy bien. Ya estoy acostumbrada a este calor.", "Kuroneko"),
    51: ("Pero, ¿no te desmayaste hace no mucho? ¿Qué pasaría si ocurriera de nuevo...", "Kyousuke"),
    52: ("Eso fue solo falta de sueño, ahora estoy bien... Aún así, no te sentirás aliviado aunque lo diga, ¿verdad?", "Kuroneko"),
    53: ("Sí, por supuesto.", "Kyousuke"),
    54: ("Pero no hay otro lugar adecuado. ¿Conoces otros buenos lugares además de este?", "Kuroneko"),
    55: ("...¿Qué tal mi casa?", "Kyousuke"),
    56: ("¿Pero con tu hermana por ahí?", "Kuroneko"),
    57: ("Ah...", "Kyousuke"),
    59: ("¿Ningún lugar, verdad? Un lugar donde podamos hablar libremente y no gastar dinero es extremadamente valioso.", "Kuroneko"),
    63: ("Todavía hay un lugar posible... aunque.", "Kyousuke"),
    64: ("Te escucho.", "Kuroneko"),
    65: ("¿Qué tal tu casa?", "Kyousuke"),
    66: ("............", "Kuroneko"),
    67: ("Y aquí estaba yo preguntándome qué ibas a sugerir tan de repente... no se puede hacer.", "Kuroneko"),
    68: ("¿Por qué? ¿Hay algún problema?", "Kyousuke"),
    69: ("Estoy segura de que hay un problema. ¿Por qué debes venir absolutamente a mi casa?", "Kuroneko"),
    70: ("Porque no dejaré que trabajes en este salón caluroso.", "Kyousuke"),
    71: ("¿Además de eso?", "Kuroneko"),
    72: ("¿Esta razón no es suficiente? Aparte de tu salud, ¿qué otra razón debería haber?", "Kyousuke"),
    73: ("P-Por Dios... ¿No puedes hablar con un poco más de reserva?", "Kuroneko"),
    74: ("No soy muy bueno con eso.", "Kyousuke"),
    75: ("¿Tienes segundas intenciones para querer ir a mi casa?", "Kuroneko"),
    76: ("¿¿Segundas intenciones?", "Kyousuke"),
    77: ("E-Eso sería...", "Kuroneko"),
    78: ("Lo he dicho muchas veces. Solo me preocupa tu salud.", "Kyousuke"),
    79: ("¿Qué tal si me desmayo frente a ti? Realmente me asustó esa vez...", "Kyousuke"),
    80: ("...Senpai.", "Kuroneko"),
    81: ("Por eso, trabajaremos en tu casa.", "Kyousuke"),
    82: ("...Está bien.", "Kuroneko"),
    83: ("También quiero echar un vistazo a tu habitación.", "Kyousuke"),
    84: ("...Y acabas de arruinarlo.", "Kuroneko"),
}

data = {
    "000scriptCKUR_0106G.obj": build(a0106_n, a0106_s),
    "000scriptCKUR_0107A.obj": build(a0107_n, a0107_s),
    "000scriptCKUR_0108T.obj": build(a0108_n, a0108_s),
    "000scriptCKUR_0109A.obj": build(a0109_n, a0109_s),
    "000scriptCKUR_0110A.obj": build(a0110_n, a0110_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
