import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

n = {
    254: "Ambas se quedaron en silencio, sin responder.",
    255: "Kuroneko ni siquiera me miró.",
    256: "Si va a ser así, no podré preguntar qué pasó.",
    277: "Después de intercambiar miradas, ambas tenían expresiones preocupadas en sus caras.",
    278: "Pero, parece que finalmente me van a decir.",
    293: "Mientras Saori hablaba, sacó su teléfono móvil.",
    294: "Después de presionar unos botones, me lo pasó. Parece que quiere que mire la pantalla.",
    295: "Mirando bien la pantalla, parece que está mostrando un correo.",
    301: "«Si sigues juntándote con Kirino Kousaka, entonces algo malo le pasará a ella.»",
    302: "«Si te importa ella, entonces corta todas las relaciones con Kirino Kousaka.»",
    310: "Saori bajó la cabeza, mientras Kuroneko cruzaba los brazos con arrogancia a su lado.",
    311: "Aunque se siente como de costumbre, puedo ver que sus expresiones son diferentes de lo normal.",
    318: "Aunque parece estar enojada, en realidad está preocupada por Kirino.",
    319: "Si no lo estuviera, no habría venido aquí a hablar conmigo.",
    327: "Qué demonios es esto...",
    328: "¿Qué significa esto?",
    329: "¿Qué le está pasando a Kirino?",
    330: "¿Podría ser... un acosador?",
    343: "Para no dejar que las dos se preocupen, tengo que resolver nuestros asuntos por mí mismo.",
    344: "Para hacer eso, necesito encontrar la causa.",
    345: "...Aunque soy reacio a hacer esto, tengo que empezar preguntándole a Kirino.",
    351: "Ya que me dejó entrar, entré obedientemente y me senté en el cojín de gato.",
    352: "Al ver esto, Kirino respiró con enojo con los brazos cruzados.",
    370: "Aunque Kuroneko no lo dijo directamente...",
}
s = {
    253: (".........", "Saori"),
    257: ("A-Además de eso, Kyousuke-shi, el próximo nuevo lanzamiento-", "Saori"),
    258: ("Hablaremos de eso después.", "Kyousuke"),
    259: ("O-Okay.", "Saori"),
    260: ("Oye, ¿qué pasó? Dímelo.", "Kyousuke"),
    261: ("Bueno... eso...", "Saori"),
    262: ("¿No puedes decirlo? ¿Ella hizo algo?", "Kyousuke"),
    263: ("¿Por qué pensarías eso...?", "Kuroneko"),
    264: ("Porque causa más problemas que otra cosa. Especialmente cuando está junta contigo.", "Kyousuke"),
    265: ("Heh... ese es un juicio acertado, Nii-san.", "Kuroneko"),
    266: ("Ahí lo tienen, el hermano de Kiririn-shi.", "Saori"),
    267: ("Ahora no es el momento para esto. ¿Qué pasó realmente?", "Kyousuke"),
    268: (".........", "Kuroneko"),
    269: (".........", "Saori"),
    270: ("Si hizo algo malo, haré que se disculpe, y después de eso, por favor llévense bien...", "Kyousuke"),
    271: ("...No es eso.", "Kuroneko"),
    272: ("¿Eh?", "Kyousuke"),
    273: ("Dije... que no es eso.", "Kuroneko"),
    274: ("Ku-Kuroneko-shi...", "Saori"),
    275: ("Solo se volvería problemático si permanecemos en silencio. Así que solo deberíamos decirlo.", "Kuroneko"),
    276: ("E-Eso, eso es cierto.", "Saori"),
    279: ("Esa mujer no hizo nada...", "Kuroneko"),
    280: ("Eh...", "Kyousuke"),
    281: ("Sin embargo, no podemos estar juntas.", "Kuroneko"),
    282: ("¿Qué pasó? No entiendo nada.", "Kyousuke"),
    283: ("Kiririn-shi realmente no hizo nada, y realmente no pasó nada.", "Saori"),
    284: ("E-Entonces, ¿por qué ustedes...", "Kyousuke"),
    285: ("Si nos juntamos, esa mujer se meterá en problemas.", "Kuroneko"),
    286: ("Es así.", "Saori"),
    287: ("...¿así cómo?", "Kyousuke"),
    288: ("Hmph... ¿aún quieres interferir a pesar de conocer mi verdadera fuerza? ¿O tienes otro objetivo en mente...?", "Kuroneko"),
    289: ("Kuroneko-shi, si continúas, ya no será una explicación.", "Saori"),
    290: ("Eso es cierto. Entonces explicaré simplemente.", "Kuroneko"),
    291: ("Kyousuke-shi, por favor mira esto.", "Saori"),
    292: ("¿Qué?", "Kyousuke"),
    296: ("¿Puedo leerlo?", "Kyousuke"),
    297: ("Sí.", "Saori"),
    298: (".........", "Kyousuke"),
    299: ("Por cierto, el remitente es desconocido. El teléfono móvil de Kuroneko-shi también recibió el mismo correo.", "Saori"),
    300: ("Esto es...", "Kyousuke"),
    303: ("¿Q-Qué es esto...", "Kyousuke"),
    304: ("Una amenaza por correo...", "Saori"),
    305: ("No sé cómo esa persona consiguió nuestras direcciones de correo, pero esto es definitivamente malicioso.", "Kuroneko"),
    306: ("Entonces por eso ustedes cancelaron la cita...", "Kyousuke"),
    307: ("Tengo que disculparme por no presentarme a la cita sin explicar. Pero después de recibir un correo así, no me es posible ir.", "Saori"),
    308: ("Eso es cierto... y tampoco es posible explicar la situación.", "Kyousuke"),
    309: ("Lo siento mucho...", "Saori"),
    312: ("No es asunto mío si algo malo le pasa a ella.", "Kuroneko"),
    313: ("Sin embargo, si algo malo realmente le pasa a ella, no se sentirá bien.", "Kuroneko"),
    314: ("Perdón por hacerte preocupar.", "Kyousuke"),
    315: ("¿Cómo podría preocuparme por esa mujer?", "Kuroneko"),
    316: ("Entendido. Gracias.", "Kyousuke"),
    317: ("No tengo idea de por qué me agradeciste.", "Kuroneko"),
    320: ("Pero llegando a eso, ¿qué pasa con el correo...", "Kyousuke"),
    321: ("Nosotras tampoco lo entendemos en absoluto.", "Saori"),
    322: ("Y tampoco sabemos cómo se filtraron nuestras direcciones de correo.", "Kuroneko"),
    323: ("¿De verdad no saben quién es el remitente?", "Kyousuke"),
    324: ("No lo sé. Es difícil de rastrear ya que el correo fue enviado desde una sub-dirección.", "Saori"),
    325: ("Parece un asunto problemático.", "Kuroneko"),
    326: ("Sinceramente...", "Saori"),
    331: ("De todos modos, con esta situación, no podemos contactar a Kiririn-shi...", "Saori"),
    332: ("Bueno, tampoco es que me mantenga en contacto con esa mujer de todos modos.", "Kuroneko"),
    333: ("Perdón a ambas.", "Kyousuke"),
    334: ("Está bien. Mientras no hagamos nada, no debería haber problemas.", "Saori"),
    335: ("Deberías preocuparte más por tu hermana.", "Kuroneko"),
    336: ("Es cierto.", "Kyousuke"),
    337: ("Por favor, cuida de Kiririn-shi. Aunque es bastante triste no poder reunirse por un tiempo.", "Saori"),
    338: ("Está bien, ¿no? Podemos no encontrarnos con esa mujer.", "Kuroneko"),
    339: ("Cuando todo esto esté resuelto, reunámonos todos.", "Kyousuke"),
    340: ("Sí.", "Saori"),
    341: ("Hmph... solo si esa mujer quiere reunirse.", "Kuroneko"),
    342: ("Está bien, lo entiendo.", "Kyousuke"),
    346: ("Oye, Kirino.", "Kyousuke"),
    347: ("...¿Qué es?", "Kirino"),
    348: ("Quiero hablar contigo.", "Kyousuke"),
    349: ("¿Es así. Entra.", "Kirino"),
    350: ("Está bien.", "Kyousuke"),
    353: ("...¿Entonces? ¿Qué es?", "Kirino"),
    354: ("Me reuní con Kuroneko y Saori.", "Kyousuke"),
    355: ("...! ¡H-Hmph! ¿Y qué?", "Kirino"),
    356: ("Les pregunté sobre lo que pasó antes.", "Kyousuke"),
    357: ("No importa, ¿verdad? ¡Esa gente!", "Kirino"),
    358: ("¿De verdad piensas así?", "Kyousuke"),
    359: ("N-Nada de tu-", "Kirino"),
    360: ("¡Mal! Escucha con atención. Les pregunté por qué no aparecieron en la cita entonces.", "Kyousuke"),
    361: ("P-Por qué... era así?", "Kirino"),
    362: ("Ambas recibieron correos amenazantes.", "Kyousuke"),
    363: ("...¿Eh?!", "Kirino"),
    364: ("«Si sigues juntándote con Kirino Kousaka, entonces algo malo le pasará a ella.»", "Kyousuke"),
    365: ("Q-Qué es esto...", "Kirino"),
    366: ("Porque te trataban como una amiga importante, por eso no se reunieron contigo, ni siquiera contactándote.", "Kyousuke"),
    367: ("Por eso, en ese momento, ambas...", "Kirino"),
    368: ("Sip. No te dejaron plantada sin razón.", "Kyousuke"),
    369: ("Saori y Kuroneko se disculparon.", "Kyousuke"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
entry = current.get("000scriptIYAN_0000E.obj", {})
entry.update(build(n, s))
current["000scriptIYAN_0000E.obj"] = entry
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptIYAN_0000E.obj (part B)")