import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0009_n = {
    0: "Ruta de Saori · Un Correo Lleno De Amor",
    4: "La imagen adjunta al correo me dejó completamente sin palabras.",
    9: "Honestamente, todo lo que puedo decir es que es dudoso.",
    10: "Al menos quítate los lentes.",
    11: "Es lo que pensé... Hasta que la línea que siguió mató cualquier humor que hubiera.",
    13: "En la imagen, Saori se veía como si estuviera totalmente despreocupada...",
    14: "Pero definitivamente tiene algo en mente.",
    15: "No entiendo del todo lo que pasó hace un momento... Es una suposición completa de mi parte pero... Tarde o temprano, descubriré cuáles son sus problemas.",
    17: "Justo así, me fui a casa, sosteniendo una gran cantidad de artículos otaku.",
}
a0009_s = {
    1: ("¿Oh? ¿Correo?", "Kyousuke"),
    2: ("¿De Saori? Eh, ¿qué es...", "Kyousuke"),
    3: ("¿Q-Qué es esto?", "Kyousuke"),
    5: ("Saludos - Mi amado Kyousuke-shi.", "Saori"),
    6: ("Para agradecerte por hoy, aquí hay una foto 'linda' de mí misma (`・ω・´)", "Saori"),
    7: ("'Linda', huh...", "Kyousuke"),
    8: ("Con esos lentes giratorios 'Hechos en China'...", "Kyousuke"),
    12: ("Muchas gracias por aceptar todas mis peticiones egoístas. Atentamente.", "Saori"),
    16: ("Bueno, hora de ir a casa.", "Kyousuke"),
}

a0010_n = {
    0: "Ruta de Saori · Un Correo De Agradecimiento",
    1: "El día después de mi intercambio con Saori.",
    2: "Recibí un correo que decía, «Estoy realmente agradecida por ayer».",
    8: "¿No puede usar emoticones como lo haría una chica normal de preparatoria?",
    9: "Bueno, lo que sea, sigamos.",
    15: "¿Qué es esta prosa extraña? ¿Qué está tratando de decirme?",
    21: "¿Se escapó de la sala...?",
    22: "¿Eso significa... que se desmayó y la enviaron al hospital?!",
    23: "¿Y si envió este correo, eso significa que está fuera de la sala!",
    30: "Oh... Esta voz elegante... Esa Saori... La usa ocasionalmente en el teléfono... Pero no importa cuántas veces la escuche, todavía no me acostumbro...",
    42: "Así es como leí el correo de Saori...",
    43: "«Me preocupé tanto por los artículos que están contigo que me desmayé. Por favor, devuélvemelos después de todo.»",
    44: "...Entonces, no tengo más remedio que ir, ¿verdad?",
    52: "¿Hmm? ¿Se rió...?",
    53: "¿Qué es esto? Está de mejor ánimo de lo que pensé.",
    58: "¿Podría ser que su espíritu empeoró porque se separó de sus artículos otaku?",
    59: "No no, no puede ser eso.",
    60: "Es lo que pensé... Pero esto es Saori...",
    61: "Miré la mochila que traje.",
    62: "Dentro de ella estaban los artículos otaku que Saori me confió.",
    63: "Saori me los pasó ya que solo podía pedírmelo a mí.",
    106: "Mientras veía a Saori reír alegremente, pensé...",
    107: "No importa quién, ¡los amigos son geniales!",
}
a0010_s = {
    3: ("¿Correo? ...De Saori.", "Kyousuke"),
    4: ("Ya que es sobre ayer, debe ser sobre los artículos?", "Kyousuke"),
    5: ("Veamos qué dice...", "Kyousuke"),
    6: ("Gracias por ayer. ＠ω＠ノシ", "Saori"),
    7: ("¡Un correo que me está apagando por completo desde el principio!", "Kyousuke"),
    10: ("Después de eso, volé hacia el cielo.", "Saori"),
    11: ("El mensaje de ella también está volando.", "Kyousuke"),
    12: ("La sensación de ligereza, y los pies sin tocar el suelo... ¿La conoces?", "Saori"),
    13: ("Esa sensación también es similar a la de una madre que perdió a su hijo.", "Saori"),
    14: ("Sí, como yo, que me separé de mis tesoros...", "Saori"),
    16: ("Cuando volví en mí, estaba mirando un techo desconocido.", "Saori"),
    17: ("Solo escuché más tarde que me había desmayado en la plataforma del tren.", "Saori"),
    18: ("Por eso, algunos trenes tuvieron que detenerse...", "Saori"),
    19: ("¿Tuviste algún problema en el camino a casa?", "Saori"),
    20: ("Como estaba preocupada por eso, me escapé de la sala para enviar este mensaje.", "Saori"),
    24: ("Contesta, contesta...", "Kyousuke"),
    25: ("¿No sirve de nada...?", "Kyousuke"),
    26: ("¡Oh! ¡Se conectó!", "Kyousuke"),
    27: ("Hola, ¿Saori?", "Kyousuke"),
    28: ("Kyousuke-shi...", "Saori"),
    29: ("¿Has visto mi correo?", "Saori"),
    31: ("Ese correo fue un error, así que por favor olvídalo...", "Saori"),
    32: ("¿En qué hospital estás ahora?", "Kyousuke"),
    33: ("¿No escucharás, verdad?", "Saori"),
    34: ("Por supuesto.", "Kyousuke"),
    35: ("*suspiro*...", "Saori"),
    36: ("Hospital Universitario de Yokohama.", "Saori"),
    37: ("Hospital Universitario de la Ciudad de Yokohama, ¿verdad?", "Kyousuke"),
    38: ("Espera, ¡voy para allá!", "Kyousuke"),
    39: ("¡¿Eh?! ¡Pero! Aquí es...", "Saori"),
    40: ("Si una madre se separa de su hijo...", "Kyousuke"),
    41: ("¡Entonces déjalos que se encuentren!", "Kyousuke"),
    45: ("¡¡Saori!!!!", "Kyousuke"),
    46: ("...Realmente viniste, Kyousuke-shi.", "Saori"),
    47: ("Sip, ¿tienes algún problema con eso?", "Kyousuke"),
    48: ("No. Solo me siento feliz por ello.", "Saori"),
    49: ("Sin embargo, no puedo estar de acuerdo con que alces la voz en el hospital.", "Saori"),
    50: ("Ugh... Tienes razón...", "Kyousuke"),
    51: ("Bueno... Esta es una habitación privada, así que no molestaremos a otras personas.", "Saori"),
    54: ("De todos modos, ¿por qué te hospitalizaron?", "Kyousuke"),
    55: ("Escribiste que te desmayaste en la plataforma del tren en el correo. ¿Te golpeaste la cabeza o algo?", "Kyousuke"),
    56: ("No, simplemente me mareé por el exceso de trabajo.", "Saori"),
    57: ("¿Mareada por exceso de trabajo?", "Kyousuke"),
    64: ("......", "Kyousuke"),
    65: ("Kyousuke-shi, eso es...", "Saori"),
    66: ("Ah, nada... Esto es...", "Kyousuke"),
    67: ("¡Es solo algo que traje por error!", "Kyousuke"),
    68: ("Por lo tanto, por favor no le prestes atención en lo más mínimo, ¡no te preocupes!", "Kyousuke"),
    69: ("Kyousuke-shi...", "Saori"),
    70: ("Muchas gracias por hacer especialmente el camino hasta aquí. Pero, 【estoy completamente bien ahora】.", "Saori"),
    71: ("¿En serio?", "Kyousuke"),
    72: ("Sí, ¡ver tu cara es suficiente para hacerme sentir mejor!", "Saori"),
    73: ("Saori... Esos artículos...", "Kyousuke"),
    74: ("Debería devolvértelos después de todo.", "Kyousuke"),
    75: ("¿Por qué?", "Saori"),
    76: ("¿Por qué preguntas...", "Kyousuke"),
    77: ("¿Porque son importantes para ti? ¿Porque en realidad no querías separarte de ellos?", "Kyousuke"),
    78: ("Eso no tiene relación con la situación actual.", "Saori"),
    79: ("Además, quiero que los guardes por todos los medios.", "Saori"),
    80: ("Oye, Saori.", "Kyousuke"),
    81: ("Algo realmente pasó.", "Kyousuke"),
    82: ("Simplemente estoy agotada. El Comiket de Verano está por comenzar, así que tengo las manos llenas.", "Saori"),
    83: ("¡Pero estoy bien ahora!", "Saori"),
    84: ("Ya veo. Eso es bueno, entonces.", "Kyousuke"),
    85: ("...Kyousuke-shi.", "Saori"),
    86: ("¿Qué pasa?", "Kyousuke"),
    87: ("Tengo una petición.", "Saori"),
    88: ("¿Podrías mantener esta hospitalización en secreto para Kiririn-shi y Kuroneko-shi?", "Saori"),
    89: ("¿Huh? ¿Por qué?", "Kyousuke"),
    90: ("Querrían venir a visitarte si supieran que estás hospitalizada.", "Kyousuke"),
    91: ("Es por eso que preferiría que te quedaras callado al respecto.", "Saori"),
    92: ("Me siento muy mal porque te he causado problemas como resultado.", "Saori"),
    93: ("Y no puedo dejar que esas dos se preocupen por mí también...", "Saori"),
    94: ("Entiendo tus sentimientos, pero ¿estás realmente bien con eso?", "Kyousuke"),
    95: ("No hubo ningún problema en el examen médico.", "Saori"),
    96: ("¿Podrías mantener esto en secreto entre nosotros dos?", "Saori"),
    97: ("Bueno, si lo pones así...", "Kyousuke"),
    98: ("Estoy en deuda contigo, Kyousuke-shi.", "Saori"),
    99: ("Mis más profundas disculpas por todos los problemas que te causé.", "Saori"),
    100: ("Está bien. ¿'Problemas'? No actúes tan reservada.", "Kyousuke"),
    101: ("Pero...", "Saori"),
    102: ("¡Eso no es un 'problema' para mí! Tal vez si fuéramos desconocidos...", "Kyousuke"),
    103: ("Somos amigos, ¿verdad?", "Kyousuke"),
    104: ("...jeje.", "Saori"),
    105: ("¡Jajajaja, ciertamente lo somos!", "Saori"),
}

a0015_n = {
    0: "Ruta de Saori · Investigando",
    1: "El día después de la visita al hospital de Saori. Hoy es el Día del Mar, así que es feriado escolar.",
    2: "No tengo nada en particular que hacer, así que pasé el tiempo en internet.",
    4: "De algún modo, estaba navegando un sitio de subastas, y como siempre, los subasteros libraban una batalla feroz.",
    5: "Este modelo de plástico es también uno de los que Saori me pasó.",
    8: "Pensemos en esto lógicamente...",
    9: "Si deja de contactarlos repentinamente después de ser hospitalizada, ¿no se volverían sospechosos?",
    14: "¡Quiero golpearla...!",
    15: "Pero me contendré por ahora. Tendré que actuar humildemente por ahora.",
    33: "...¿No es eso raro?",
    34: "Incluso si son amigos, es un artículo raro. No es algo que puedas dar como regalo.",
    35: "¿Tiene esto algo que ver con que me haya pasado los artículos otaku?",
    44: "Últimamente, le ha estado yendo bien en la escuela.",
    50: "¿¡Aplastar dónde!?",
    51: "En realidad, no pregunté eso.",
    53: "Dejémoslo así después de todo.",
    54: "Ahora mismo, no creo que pueda obtener una respuesta directa de ella.",
    63: "Eso es de hecho algo importante que quieres que un chico guarde.",
    64: "Todavía no lo entiendo, pero ¿no es esta respuesta un poco equivocada?",
    81: "Cuando ella afirma fuertemente que está bien... Significa que quiere que te preocupes por ella...",
    88: "Se siente como la estela de una tormenta.",
}
a0015_s = {
    3: ("Oh, esta figura... Se apreció enormemente desde su lanzamiento.", "Kyousuke"),
    6: ("Hablando de eso, aunque Saori pidió mantener a Kirino y Kuroneko en la oscuridad...", "Kyousuke"),
    7: ("¿Se puso en contacto con ellas?", "Kyousuke"),
    10: ("...¿Debería intentar preguntarles?", "Kyousuke"),
    11: ("¿Qué pasa con Saori?", "Kirino"),
    12: ("Bueno, ¿dijo o hizo Saori algo extraño últimamente?", "Kyousuke"),
    13: ("¿Huh? ¿Es esa la actitud que deberías tener al pedirle algo a alguien?", "Kirino"),
    16: ("Últimamente, ¿habrías notado algo extraño en Saori?", "Kyousuke"),
    17: ("Hmm... Hablando de eso...", "Kirino"),
    18: ("Después del Torneo Siscaly, de repente recibí un dato de Avatar Item de ella.", "Kirino"),
    19: ("¿Avatar Item?", "Kyousuke"),
    20: ("Para decirlo simplemente, te permite adjuntar algo a tu personaje.", "Kirino"),
    21: ("Cosas como armas, armaduras y cosas como trajes especiales...", "Kirino"),
    22: ("Oh. ¿Es algo genial?", "Kyousuke"),
    23: ("Hay una variedad de Avatar Items buenos y malos.", "Kirino"),
    24: ("Hay algunos que puedes conseguir solo jugando.", "Kirino"),
    25: ("Por supuesto, hay algunos que son exclusivos de torneos y eventos.", "Kirino"),
    26: ("Lo que recibí fue algo que solo obtienes ganando 300 batallas en línea.", "Kirino"),
    27: ("¿No es bastante raro?", "Kyousuke"),
    28: ("Podrías decir que sí.", "Kirino"),
    29: ("Saori dijo «ya no lo necesito», así que lo recibí con gratitud.", "Kirino"),
    30: ("¿Le diste algo?", "Kyousuke"),
    31: ("...No.", "Kirino"),
    32: ("También dije «¿hagamos un intercambio?», pero ella no quería nada...", "Kirino"),
    36: ("Aparte de eso, no he notado nada...", "Kirino"),
    37: ("Entonces, ¿Kuroneko mencionó algo?", "Kyousuke"),
    38: ("¿Huh? ¿Por qué crees que sé algo sobre ella?", "Kirino"),
    39: ("E-Es cierto!", "Kyousuke"),
    40: ("Si sabes eso, entonces no hagas preguntas raras.", "Kirino"),
    41: ("S-Sí...", "Kyousuke"),
    42: ("Bueno, si algo pasara, ella me lo diría.", "Kirino"),
    43: ("Después de todo, somos sus únicas amigas.", "Kirino"),
    45: ("Entonces, ¿era todo?", "Kirino"),
    46: ("Ah, todavía tengo una pregunta más.", "Kyousuke"),
    47: ("¿Qué es?", "Kirino"),
    48: ("...Bueno, viniendo de ti, probablemente sea una pregunta sin sentido.", "Kirino"),
    49: ("Si lo es, te aplastaré con mi pie.", "Kirino"),
    52: ("Vamos, haz tu pregunta ya. No tengo tanto tiempo libre.", "Kirino"),
    55: ("¿Y bien? Dilo ya.", "Kirino"),
    56: ("Lo siento. Después de todo, no es nada.", "Kyousuke"),
    57: ("...Kay. Me voy entonces.", "Kirino"),
    58: ("No tienes que ser fría solo porque no pregunté.", "Kyousuke"),
    59: ("¿Qué significa cuando una chica quiere que un chico guarde algo importante para ella?", "Kyousuke"),
    60: ("¿Ni siquiera sabes eso? ¿No es obvio?", "Kirino"),
    61: ("【Promesa Sobre El Futuro】, cosas así, ¿verdad?", "Kirino"),
    62: ("¿Promesa sobre el futuro?", "Kyousuke"),
    65: ("No es algo así...", "Kyousuke"),
    66: ("Tan irritante...", "Kirino"),
    67: ("Si eso está mal, entonces ¿por qué no vas a buscar la respuesta tú mismo?", "Kirino"),
    68: ("Oye, ¿eres un idiota? ¿Quieres morir?", "Kirino"),
    69: ("¿No has estado navegando demasiado por la red...?", "Kyousuke"),
    70: ("Cuando una chica dice que está bien, ¿qué significa?", "Kyousuke"),
    71: ("¿Huh? ¿Qué es eso, qué quieres decir?", "Kirino"),
    72: ("Como, cuando dice «ahora estoy bien».", "Kyousuke"),
    73: ("Si dice «estoy bien», significa «No te involucres más»", "Kirino"),
    74: ("¿En serio?", "Kyousuke"),
    75: ("Te estás involucrando más de lo necesario y ella piensa, «Qué molesto»", "Kirino"),
    76: ("Realmente no quiero escuchar esto...", "Kyousuke"),
    77: ("Sé considerado para evitar fastidiar a la otra parte.", "Kirino"),
    78: ("O eso...", "Kirino"),
    79: ("Tal vez es lo contrario y ella quiere que te preocupes por ella.", "Kirino"),
    80: ("¿Lo contrario?", "Kyousuke"),
    82: ("Hm... Lo siento. No lo entiendo en absoluto.", "Kyousuke"),
    83: ("¡Los hombres que no entienden el corazón de una doncella deberían ser exterminados!", "Kirino"),
    84: ("¡Me vas a hacer llorar!", "Kyousuke"),
    85: ("Sí sí, estoy ocupada a diferencia de ti.", "Kirino"),
    86: ("Si todavía tienes preguntas, ¿tal vez podrías postrarte y preguntarle a la persona involucrada?", "Kirino"),
    87: ("*suspiro*...", "Kyousuke"),
    89: ("Bueno, gracias a Kirino, aprendí algo.", "Kyousuke"),
    90: ("De alguna manera u otra, sus palabras son convincentes.", "Kyousuke"),
    91: ("Saori está de hecho escondiendo algo.", "Kyousuke"),
}

a0020_n = {
    0: "Ruta de Saori · Recuperación Completa",
    1: "Después de volver a casa de la escuela esa noche, recibí un correo en mi teléfono.",
    3: "¿Es de Saori? Veamos...",
    4: "Eh... ¿Dice que la darán de alta mañana?",
    5: "¡Es genial que no fuera algo malo!",
    21: "Kirino no está feliz por esto...",
    22: "Pero supongo que no puede sentirse bien por haber sido mantenida en la oscuridad sobre la hospitalización de su amiga.",
    30: "Se ha puesto completamente de mal humor... Aunque usualmente es arrogante, puede ser sorprendentemente delicada.",
    31: "Aquí es donde el Hermano Mayor entrará y la animará.",
    32: "Este es el momento en el que debería provocarla, y ya que es orgullosa, ¡definitivamente morderá el anzuelo!",
    40: "¿Podría ser que Kirino...",
    41: "¿está súper enojada por el hecho de que la mantuvieron en la oscuridad sobre la hospitalización de Saori?",
    44: "Mientras la llamo mientras se va, Kirino ni siquiera mira hacia atrás.",
}
a0020_s = {
    2: ("Título: Perdón por hacerte preocupar.", "Kyousuke"),
    6: ("¿Por qué estás todo sonriente, mirando tu correo?", "Kirino"),
    7: ("¡¿Uwah?! ¡No mires!", "Kyousuke"),
    8: ("No hay manera de que tengas novia, así que probablemente es un correo de esa negra o algo, ¿verdad?", "Kirino"),
    9: ("¡Déjame ver de qué se trata♪", "Kirino"),
    10: ("¡Oye! ¡No espíes!", "Kyousuke"),
    11: ("...¿Huh?", "Kirino"),
    12: ("Ah...", "Kyousuke"),
    13: ("...¿Qué es esto?", "Kirino"),
    14: ("¿Saori fue hospitalizada?", "Kirino"),
    15: ("¿Además, lo sabías y te quedaste callado hasta ahora?", "Kirino"),
    16: ("E-Es solo algo de mareo. No es algo grande.", "Kyousuke"),
    17: ("Y-Ya veo...", "Kirino"),
    18: ("¡Pero no tuve ningún trabajo de modelaje, así que podría haberla visitado si me hubieras dicho...!", "Kirino"),
    19: ("Mira, cálmate. Ella solo no quería hacerte preocupar.", "Kyousuke"),
    20: ("N-No tiene nada que ver contigo...", "Kirino"),
    23: ("¡No te enojes tanto! Saori tenía sus propias circunstancias...", "Kyousuke"),
    24: ("...No me importa ella!", "Kirino"),
    25: ("...¿Huh?", "Kyousuke"),
    26: ("¿Qué es eso? ¿No te importa? ¿No son amigas?", "Kyousuke"),
    27: ("Amigas... ¿Y qué?", "Kirino"),
    28: ("Tal vez ella no piensa eso.", "Kirino"),
    29: ("...Después de todo, ella no me dijo que fue hospitalizada.", "Kirino"),
    33: ("Bueno entonces, la ayudaré yo mismo.", "Kyousuke"),
    34: ("Porque soy su amigo.", "Kyousuke"),
    35: ("......", "Kirino"),
    36: ("...【Haz lo que quieras】.", "Kirino"),
    37: ("Ah... ¿Qué?", "Kyousuke"),
    38: ("¿Te vas? ¿No vas a ayudarme?", "Kyousuke"),
    39: ("Vas a ayudarla tú mismo, ¿verdad? ¡Entonces no tiene nada que ver conmigo!", "Kirino"),
    42: ("¿Qué quieres decir con «haz lo que quieras»?", "Kyousuke"),
    43: ("¿¡No eres amiga de Saori?!", "Kyousuke"),
    45: ("Ah, así que es así. Lo entiendo, lo entiendo.", "Kyousuke"),
    46: ("Si es así, haré lo que quiera como sugeriste.", "Kyousuke"),
    47: ("...*suspiro* Vamos, no me hagas preocupar... Dios...", "Kirino"),
    48: ("¿Kirino? ¿Dijiste algo?", "Kyousuke"),
    49: ("...Nada.", "Kirino"),
}

a0023_n = {
    0: "Ruta de Saori · Arte Ninja: Capa De Invisibilidad",
    1: "Fui directo a casa desde la escuela, e inmediatamente llamé a Saori.",
    2: "Pensé en felicitarla por salir del hospital y preguntar casualmente sobre ese Avatar Item que le dio a Kirino.",
    12: "Por cierto, este «¡No estoy preguntando eso!» es una respuesta a mi «tengo algo que preguntarte». Sobre las medidas de Saori, yo... sí quiero escucharlas.",
    15: "...",
    16: "......*suspiro*",
    17: ".........Hmm.",
    29: "Intentemos llamar a su celular.",
    30: "Como era de esperarse, su teléfono está apagado y no puedo comunicarme...",
    31: "*suspiro*... ¿Por qué no puede simplemente ser directa conmigo...",
    35: "Kirino levantó la vista por encima de la revista que estaba leyendo, y me miró fijamente hacia aquí.",
    39: "Kirino continuó refunfuñando sobre Saori, aunque no pregunté ni una sola cosa.",
    40: "Aunque Kirino dijo «Haz lo que quieras» de una manera irresponsable, probablemente esté preocupada por Saori a su manera.",
    50: "Parece que todavía guarda rencor por lo que dije hace dos días.",
    51: "Bueno, así, ella continuará acercándose a Saori, así que está bien dejarlo así.",
    54: "No sé por qué, pero acaricié la cabeza de Kirino.",
    55: "Si tuviera que dar una razón para esto, probablemente es por ser un hermano mayor.",
    62: "¡Solo toqué tu cabeza un poco! ¡No tienes que enojarte tanto!",
    63: "¡Solo estoy tratando de ser tu hermano mayor por una vez!",
    67: "Kirino puso la revista sobre la mesa, y salió de la sala de estar.",
    68: "...Pero, mientras pasaba a mi lado...",
    72: "Rechazando el toque de su hermano, pero todavía preocupándose por no poder contactar a su amiga...",
    73: "Ah... Ella realmente no es linda.",
    74: "...Pero es mi hermana, así que no se puede evitar.",
}
a0023_s = {
    3: ("¡Cortando la llamada en ese momento, ella realmente no sabe leer el ambiente!", "Kyousuke"),
    4: ("Estoy marcando de nuevo de inmediato; ¡toma esto, Bajeena!", "Kyousuke"),
    5: ("El número que marcaste no está disponible actualmente...", "Speakers"),
    6: ("...No puedo comunicarme.", "Kyousuke"),
    7: ("Si ese es el caso, ¡probaré con el chat en línea!", "Kyousuke"),
    8: ("Uh... «¡Saori! Tengo algo que preguntarte.»", "Kyousuke"),
    9: ("Veamos aquí...", "Kyousuke"),
    10: ("¿Ah? ¿Ya no conoces mis 3 medidas? ＠ω＠;", "Kyousuke"),
    11: ("¡No estoy preguntando eso!", "Kyousuke"),
    13: ("«No es eso.»", "Kyousuke"),
    14: ("«¿No tienes algunos problemas en este momento?»", "Kyousuke"),
    18: ("A diferencia de mí, que soy inexperto escribiendo, Saori usualmente puede responder de inmediato, es raro que le tome tanto tiempo.", "Kyousuke"),
    19: ("Oh, ¡respondió!", "Kyousuke"),
    20: ("«¡Mis más profundas disculpas, Kyousuke-san!»", "Kyousuke"),
    21: ("«¡Surgió algo urgente, así que tendrás que disculparme!»", "Kyousuke"),
    22: ("...Espera, ¡oye!", "Kyousuke"),
    23: ("Se desconectó... espera, ¡acaba de esquivarme!", "Kyousuke"),
    24: ("Pero, espera.", "Kyousuke"),
    25: ("Si iba a irse cuando pregunté, entonces ¿por qué pasó tanto tiempo en la primera respuesta?", "Kyousuke"),
    26: ("¿Acaso tenía algo que confesar?", "Kyousuke"),
    27: ("También es inusual que se desconecte antes de esperar una respuesta.", "Kyousuke"),
    28: ("¿Podría ser que algo pasó en su casa?", "Kyousuke"),
    32: ("...¿Cómo está ella?", "Kirino"),
    33: ("¿Quién?", "Kyousuke"),
    34: ("Estoy hablando de ella. Esa de los lentes giratorios.", "Kirino"),
    36: ("Es solo que me quedé atascada en una de las peleas de Siscaly.", "Kirino"),
    37: ("No me gusta preguntarle a esa negra, e intenté enviar un correo a la enorme...", "Kirino"),
    38: ("No recibí una respuesta y no pude hacer ninguna llamada... ¿Quién se cree que es?", "Kirino"),
    41: ("Yo también intenté llamarla y chatear con ella en línea, pero no funcionó.", "Kyousuke"),
    42: ("Ella sin duda está escondiendo algo.", "Kyousuke"),
    43: ("¿Hmm? Pero intentaste varias maneras.", "Kirino"),
    44: ("Incluso 【la cara tranquila de Buda solo dura hasta la tercera vez】, ¿así que tal vez lo intentes de nuevo?", "Kirino"),
    45: ("¿Intentar de nuevo...? ¿Por qué no me ayudas?", "Kyousuke"),
    46: ("Es algo que quieres hacer tú mismo, ¿verdad? ...No tiene nada que ver conmigo.", "Kirino"),
    47: ("...A pesar de que también estás preocupada por ella.", "Kyousuke"),
    48: ("¿Dijiste algo?", "Kirino"),
    49: ("No, ¡nada!", "Kyousuke"),
    52: ("Así que te informaré una vez que obtenga resultados.", "Kyousuke"),
    53: ("Espera aquí como una buena niña.", "Kyousuke"),
    56: ("Está bien... Lo entiendo...", "Kirino"),
    57: ("......¿Eh?", "Kirino"),
    58: ("¿Qué pasa?", "Kyousuke"),
    59: ("¿Q-Q-Q...", "Kirino"),
    60: ("¿¡Q-Por qué estás acariciando la cabeza de alguien así?!", "Kirino"),
    61: ("¡¿Ouch?!", "Kyousuke"),
    64: ("¡Ah Dios! ¡Me desordenaste el cabello!", "Kirino"),
    65: ("¿¡Realmente necesitas odiarlo tanto?!", "Kyousuke"),
    66: ("Hmph...", "Kirino"),
    69: ("Oye...", "Kirino"),
    70: ("¿Hmm?", "Kyousuke"),
    71: ("Si algo pasa de nuevo... dímelo...", "Kirino"),
    75: ("..Incluso la cara tranquila de Buda solo dura hasta la tercera vez, eh.", "Kyousuke"),
    76: ("También se dice que a la tercera va la vencida, así que tal vez lo intente de nuevo mañana.", "Kyousuke"),
}

data = {
    "000scriptDSAO_0009G.obj": build(a0009_n, a0009_s),
    "000scriptDSAO_0010A.obj": build(a0010_n, a0010_s),
    "000scriptDSAO_0015A.obj": build(a0015_n, a0015_s),
    "000scriptDSAO_0020A.obj": build(a0020_n, a0020_s),
    "000scriptDSAO_0023A.obj": build(a0023_n, a0023_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
