import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a145_n = {
    0: "Comienzo del recorrido turístico",
    21: "Manami sacó un «manual del viaje escolar» gastado.",
    28: "Con su manera de hablar, me incomoda que me haga pensar que fue hace 20 años.",
    30: "Oh sí, el profesor titular dijo algo sobre eso.",
    32: "¿Quién está en él...?",
    33: "Recuerdo que estoy en el mismo grupo que Manami...",
    34: "Probablemente incluye a Akagi también... ¿Cuántos más debería haber?",
    38: "Entonces es obra de Akagi...",
    39: "Probablemente desconfía de mi relación con Manami.",
    40: "Por eso actuó con tacto.",
    41: "...Qué metiche.",
    42: "¿Un correo? Miré la pantalla---",
    44: "El nombre «Kirino» se iluminó.",
    45: "Qué querrá ahora.",
    50: "Le respondí con calma y eché un vistazo al correo.",
    61: "Ya que el tiempo es limitado, no podemos ir a tantos lugares...",
    71: "Alrededor nuestro, nuestro viaje escolar formó una fila. La gente en la moda del «Recorrido por Lugares de Poder» estaba atascando el lugar.",
    74: "Y así le advertí, pero...",
    76: "El que estaba a punto de caerse era, de hecho, yo.",
    77: "La ola de gente empujó mi espalda y-",
    80: "Antes de que pudiera darme cuenta, Manami estaba atrapada entre mis brazos.",
    85: "Un desarrollo típico de galge.",
    86: "En este tipo de situación... No podría separarme aunque quisiera.",
    89: "Siento algo empujando contra mi codo...",
    92: "N-No puede ser... ¿Puede leer mi mente...?",
    95: "Tratando desesperadamente de cambiar el tema.",
    98: "Había una atmósfera incómoda entre nosotros...",
    105: "Entonces dejamos Kiyomizu-dera.",
    106: "Cambiando de opinión de repente... No puedo entenderla.",
    109: "Tratando de no ser confundido con un pervertido y de no mancillar la dignidad de mi hermana, respondo vagamente.",
    111: "Manami empezó a mirar a su alrededor sin rumbo.",
    113: "En la dirección que Manami señaló había un póster que decía «¡¡Edición Limitada!! Meruru Edición Regional, solo en Shinkyougoku!»",
    114: "Entonces de verdad existe.",
    119: "Partimos a Shinkyougoku para comprar esos recuerdos de «Meruru Edición Regional».",
    123: "Esa chica, más le vale estar agradecida conmigo...",
    124: "Mientras mi cartera se volvía más ligera, mi cuerpo se inclinaba pesadamente bajo los recuerdos de Meruru y un agotamiento sin fondo.",
    127: "Siento que hay otros lugares a los que debo ir...",
    128: "No puedo recordarlo, o tal vez no quiero...",
    129: "Simplemente no podía recordar dónde.",
    130: "...Pero, ¿qué pensaría Manami de mí si mencionara esto?",
    143: "Por varias razones. No puedo explicarlo en detalle.",
    151: "Eso era... Antes de que siquiera me diera cuenta, la relación entre Manami y Ayase se ha vuelto bastante buena.",
    152: "Esto es problemático.",
    167: "...No puede ser.",
    170: "No puede ser, ¿lo grabó...?",
    171: "Estaba tan sacudido que empecé a tener sudor frío.",
    172: "Rayos...",
    173: "Esto es realmente malo esta vez, ¡hay una posibilidad de que todo lo que le dije a Ayase haya sido grabado...!",
    178: "Ciertamente, Ayase es muy linda y es mi tipo... Pero no es que la considere un interés amoroso.",
    179: "¿Supongo...?",
    181: "...Logré salir de eso engañando, y me dirigí a Gion.",
    184: "Aunque Manami parece ser conocedora de Kioto, no ha oído de una compañía llamada «Heian Animation»",
    188: "Como dijo, Manami caminó hacia el mostrador.",
    189: "Esa chica es realmente entusiasta.",
    190: "Después de hablar un rato en el mostrador, Manami regresó...",
    199: "Con la cara de Saori apareciendo en mi mente, medito por un rato...",
    203: "Levanté mi «Figura de Plástico de Robot Modelo Edición Limitada de Kioto» que compré en la sucursal de Mate en Kioto y asentí con confianza.",
    204: "A mi lado está por supuesto Manami.",
    214: "Es cierto, Saori es, para mí... una amiga importante.",
    217: "La figura de una lolita gótica negra vino a mi mente.",
    218: "K-Kuroneko... ¿Qué dijo otra vez?",
    219: "Creo que es una maldición o algo...",
    230: "No importa cuán noble sea este símbolo, todo lo que puedo ver en él es la «☆» de «Stardust ☆ Witch Meruru».",
    231: "Es como si sus maldiciones me estuvieran royendo...",
    241: "Logré repeler la indagación de Manami pero...",
    242: "Mi mente está en un desorden.",
    245: "En ese momento, fui «maldito» por el beso de Kuroneko.",
    246: "Una maldición tan fuerte que todavía está entrelazada alrededor de mi corazón, erosionándolo.",
    247: "Quizás Abe no Seimei habría podido deshacer esta maldición.",
    248: "Mirando fijamente el pentagrama que acabo de comprar... Lo puse casualmente en mi bolsillo.",
    249: "El sonrojo en mi cara, sin embargo, no desapareció tan fácilmente.",
    254: "Manami dijo mientras señalaba el famoso autobús turístico que da la vuelta a Kioto.",
    257: "He tomado una decisión. Hoy pasaré mi tiempo haciendo turismo con Manami.",
}
a145_s = {
    1: ("...¿Estás de verdad bien...?", "Manami"),
    2: ("¿No confías en mí?", "Kyousuke"),
    3: ("N-No es eso lo que quiero decir...", "Manami"),
    4: ("Abuelito, estoy realmente preocupada, ¿sabes?", "Manami"),
    5: ("Abuelita, eres tú quien me preocupa mucho.", "Kyousuke"),
    6: ("Trata de no mezclarte con el grupo de otra escuela y terminar perdida por favor, ¿sí?", "Kyousuke"),
    7: ("¿Eeeh? ¡No haría algo así! Dios...", "Manami"),
    8: ("No hay problema. Estás conmigo de todos modos.", "Kyousuke"),
    9: ("¿Eh? ¿K-Kyou-chan?", "Manami"),
    10: ("Contaré contigo si algo me pasara, Manami.", "Kyousuke"),
    11: ("N-Nada debería pasar en primer lugar～", "Manami"),
    12: ("Jaja, solo bromeo.", "Kyousuke"),
    13: ("Dios... Tonto Kyou-chan.", "Manami"),
    14: ("Bueno entonces, ¿vamos?", "Manami"),
    15: ("¿A dónde?", "Kyousuke"),
    16: ("¿No leíste el manual del viaje escolar?", "Manami"),
    17: ("Ah, es cierto. Me lo pasaste justo ayer.", "Kyousuke"),
    18: ("No lo leíste...", "Manami"),
    19: ("Está bien ya que tú lo leíste.", "Kyousuke"),
    20: ("Sí, te guiaré. De verdad esperaba esto... ¡Mira!", "Manami"),
    22: ("¿Hace cuántos años conseguiste eso?", "Kyousuke"),
    23: ("Este año.", "Manami"),
    24: ("Lo has leído demasiadas veces.", "Kyousuke"),
    25: ("He estado esperando esto... Jejeje.", "Manami"),
    26: ("¿Cuántos años han pasado desde que fuimos a un viaje juntos?", "Manami"),
    27: ("Desde el viaje de la secundaria, así que unos 3 años.", "Kyousuke"),
    29: ("Ahora es tiempo libre para los grupos individuales.", "Manami"),
    31: ("...Entonces, ¿quiénes son los miembros de mi grupo?", "Kyousuke"),
    35: ("Los demás ya se fueron.", "Manami"),
    36: ("¿Por qué?", "Kyousuke"),
    37: ("Mientras no haya problema en reunirnos al final del día, Akagi-kun sugiere que cada uno vaya por su lado.", "Manami"),
    43: ("...Qué raro.", "Kyousuke"),
    46: ("¿Qué pasa, Kyou-chan?", "Manami"),
    47: ("Un correo de mi hermana.", "Kyousuke"),
    48: ("Oh, jeje... Pareces contento.", "Manami"),
    49: ("Por supuesto que no.", "Kyousuke"),
    51: ("Compra el juego completo de 【Meruru Edición Regional】.", "Kirino"),
    52: ("¿【Meruru Edición Regional】?", "Kyousuke"),
    53: ("¿Qué dijo Kirino-chan?", "Manami"),
    54: ("Me dijo que trajera recuerdos locales.", "Kyousuke"),
    55: ("Tch... En serio, no me escribas por ese tipo de cosas inútiles.", "Kyousuke"),
    56: ("...Jijiji.", "Manami"),
    57: ("...? ¿De qué te ríes?", "Kyousuke"),
    58: ("Nada～", "Manami"),
    59: ("¿Por dónde empezaremos el recorrido?", "Manami"),
    60: ("Bueno entonces, ¿a dónde deberíamos ir?", "Kyousuke"),
    62: ("Ya que vinimos a Kioto,", "Kyousuke"),
    63: ("Kiyomizu-dera es un hecho, ¿verdad?", "Kyousuke"),
    64: ("Gracias.", "Manami"),
    65: ("¿Eh?", "Kyousuke"),
    66: ("Recordaste a dónde quería ir.", "Manami"),
    67: ("...Je.", "Kyousuke"),
    68: ("'Kay, vamos.", "Kyousuke"),
    69: ("Siento seriamente que estamos en Kioto, ¿no?", "Manami"),
    70: ("Sí. Está lleno... Ni siquiera podemos movernos.", "Kyousuke"),
    72: ("S-Si no me equivoco... la cascada del matrimonio es por aquí....", "Manami"),
    73: ("Oye, no entres en pánico y te caigas, ¿okay?", "Kyousuke"),
    75: ("¿Eh?", "Manami"),
    78: ("...U-, wah", "Kyousuke"),
    79: ("...¿Eh?", "Manami"),
    81: ("......", "Kyousuke"),
    82: ("......", "Manami"),
    83: ("¡P-Perdón!", "Kyousuke"),
    84: ("No... No hay problema...", "Manami"),
    87: (".........", "Kyousuke"),
    88: (".........", "Manami"),
    90: ("*tragar saliva*", "Kyousuke"),
    91: ("Kyou-chan...", "Manami"),
    93: ("Puedo decirlo si veo tu cara.", "Manami"),
    94: ("¡D-De todos modos, movámonos!", "Kyousuke"),
    96: ("Estaba realmente lleno...", "Kyousuke"),
    97: ("Ciertamente lo estaba...", "Manami"),
    99: ("P-Parece que no podemos llegar a la cascada del matrimonio.", "Kyousuke"),
    100: ("Sí, no se puede evitar...", "Manami"),
    101: ("¿Estás segura? Querías probarlo, ¿no?", "Kyousuke"),
    102: ("Está bien, de verdad.", "Manami"),
    103: ("¿De verdad?", "Kyousuke"),
    104: ("Sí. Vamos, Kyou-chan.", "Manami"),
    107: ("¿Sabes algo sobre Meruru Edición Regional?", "Kyousuke"),
    108: ("¿Meruru Edición Regional?", "Manami"),
    110: ("Entonces es así. Busquémosla entonces. Hmm... ¿Probablemente lo sabremos si preguntamos en la tienda de recuerdos?", "Manami"),
    112: ("¡Kyou-chan, mira por allá!", "Manami"),
    115: ("Shinkyougoku entonces. Kyou-chan, vamos allá primero, ¿de acuerdo?", "Manami"),
    116: ("Sí... Lo siento un poco. Seguro que hay otros lugares a los que quieres ir, ¿verdad?", "Kyousuke"),
    117: ("Bueno entonces, caminemos por Shinkyougoku después de comprar el recuerdo para Kirino-chan.", "Manami"),
    118: ("Correcto, hagamos eso.", "Kyousuke"),
    120: ("¿R-Realmente necesitas comprar tantos..?", "Manami"),
    121: ("Sí... Pidió el juego completo...", "Kyousuke"),
    122: ("Pero... ¿tantos como los muchos santuarios populares de Tokio?", "Manami"),
    125: ("...Hmm.", "Kyousuke"),
    126: ("¿Todavía estás dudando...? Hay mucho tiempo, así que tómate tu tiempo.", "Manami"),
    131: ("De todos modos, ¿conoces una tienda de renombre que venda papeles absorbentes de aceite?", "Kyousuke"),
    132: ("¿Eh?", "Manami"),
    133: ("Parece que es realmente bueno y alguien me pidió comprar algunos como recuerdos.", "Kyousuke"),
    134: ("Si es así, ¿no debería estar en el área de Gion?", "Manami"),
    135: ("Oh, de verdad sabes mucho.", "Kyousuke"),
    136: ("Ehehe, lo estaba esperando, así que he investigado muchas cosas...", "Manami"),
    137: ("¿Vas a comprar eso para Kirino-chan?", "Manami"),
    138: ("No, es un recuerdo para Ayase.", "Kyousuke"),
    139: ("Oooh～", "Manami"),
    140: ("¿Q-Qué pasa?", "Kyousuke"),
    141: ("Ayase-chan estaba bastante enojada con Kyou-chan antes... ¿Se reconciliaron ustedes dos?", "Manami"),
    142: ("Esa chica siempre está enojada conmigo.", "Kyousuke"),
    144: ("Bueno, ¿podría ser...", "Manami"),
    145: ("...que esparciste libros ero frente a Ayase-chan,", "Manami"),
    146: ("Le dijiste que es la prueba de tu amor con Kirino mientras presumías esos libros frente a ella,", "Manami"),
    147: ("Abrazaste a Kirino-chan y gritaste «¡amo a mi hermanita!»?", "Manami"),
    148: ("¡-Por qué sabes eso?!", "Kyousuke"),
    149: ("Lo escuché de ella.", "Manami"),
    150: ("Ugh.", "Kyousuke"),
    153: ("Incluso sobre Kyou-chan tratando de hacer que Ayase-chan usara ese vestido obsceno.", "Manami"),
    154: ("También cuando hiciste cosas obscenas a un personaje de juego que se parecía justo a Ayase-chan.", "Manami"),
    155: ("Incluso instigando a Ayase-chan a decir algunas líneas vergonzosas.", "Manami"),
    156: ("He escuchado todo de ella.", "Manami"),
    157: ("Jajaja, qué estás diciendo, Manami.", "Kyousuke"),
    158: ("¿No es obvio que es todo un malentendido de su parte?", "Kyousuke"),
    159: ("¿Eh...? ¿De verdad?", "Manami"),
    160: ("Por supuesto.", "Kyousuke"),
    161: ("P-Pero...", "Manami"),
    162: ("Mira esos ojos... ¿No me crees?", "Kyousuke"),
    163: ("Hmm... Sin embargo, cuando considero la «voz de Kyou-chan».", "Manami"),
    164: ("¿Qué quieres decir con «voz»?", "Kyousuke"),
    165: ("La voz que está grabada en el teléfono móvil de Ayase-chan.", "Manami"),
    166: ("¿Qué... dijiste...?", "Kyousuke"),
    168: ("Prepárate, escucha con cuidado, yo...", "Kyousuke"),
    169: ("amo a mi hermanitáaaaaaa-", "Kyousuke"),
    174: ("De todos modos, ¿Kyou-chan? Te estás comportando demasiado infantil con Ayase-chan.", "Manami"),
    175: ("¿Eh?", "Kyousuke"),
    176: ("Si estás interesado en Ayase-chan, necesitas actuar apropiadamente como debería un senpai.", "Manami"),
    177: ("...¡N-No es así!", "Kyousuke"),
    180: ("¡B-Basta de eso. Apúrate, vamos.", "Kyousuke"),
    182: ("Oh sí, ¿has oído de una compañía llamada «Heian Animation»?", "Kyousuke"),
    183: ("¿Qué es eso?", "Manami"),
    185: ("¿Quieres ir allí?", "Manami"),
    186: ("No es que quiera pero...", "Kyousuke"),
    187: ("¡Entendido! ¡Iré a preguntar en el mostrador!", "Manami"),
    191: ("Esa compañía está aparentemente en el distrito de Kioto.", "Manami"),
    192: ("Oh.", "Kyousuke"),
    193: ("Pero, parece que está cerrada por hoy.", "Manami"),
    194: ("Cerrada... No se puede evitar entonces.", "Kyousuke"),
    195: ("Perdón.", "Manami"),
    196: ("No hay necesidad de que te disculpes.", "Kyousuke"),
    197: ("Vayamos a otro lugar.", "Kyousuke"),
    198: ("¿A dónde?", "Manami"),
    200: ("Vayamos a la sucursal de Animate en Kioto.", "Kyousuke"),
    201: ("Eeeeeh.", "Manami"),
    202: ("Esto debería funcionar.", "Kyousuke"),
    205: ("¿Así que te gustan los modelos de plástico?", "Manami"),
    206: ("No, es un recuerdo. Hay... alguien a quien le gusta este tipo de cosas.", "Kyousuke"),
    207: ("¿Es alguien que conozco?", "Manami"),
    208: ("¿No has conocido a esa persona?", "Kyousuke"),
    209: ("Es como Kuroneko, una amiga mutua de Kirino y mía. Nos conocimos hace un año.", "Kyousuke"),
    210: ("Eh, ¿son cercanos?", "Manami"),
    211: ("¡Sí!", "Kyousuke"),
    212: ("Es cierto. Cuando estabas comprando los recuerdos, parecías realmente feliz.", "Manami"),
    213: ("Jeje, sí.", "Kyousuke"),
    215: ("M-Maldición... si tan solo conociera mejor Kioto...", "Kyousuke"),
    216: ("Supongo que no hay remedio, parecías ocupado.", "Manami"),
    220: ("Hmmm, ¿sabes sobre Abe no Seimei?", "Kyousuke"),
    221: ("Por supuesto que sé sobre él.", "Manami"),
    222: ("Abe no Seimei es el exorcista que protegió Kioto durante el período Heian.", "Manami"),
    223: ("¿E-Exorcista?", "Kyousuke"),
    224: ("Los registros ahora muestran que el sacerdote Shinto tenía poderes inmensos.", "Manami"),
    225: ("Usó este poder para exterminar a los demonios que anidaban alrededor y dentro de Kioto.", "Manami"),
    226: ("¡Vamos y echemos un vistazo al Santuario Seimei!", "Manami"),
    227: ("Este es el Santuario Seimei.", "Manami"),
    228: ("¿Hm? He visto a menudo esas marcas aquí y allá...", "Kyousuke"),
    229: ("Se llama pentagrama. Es un sello que usó Abe no Seimei.", "Manami"),
    232: ("Disculpe, ¿podría darme este pentagrama?", "Kyousuke"),
    233: ("¿Es un recuerdo para Kuroneko-san?", "Manami"),
    234: ("Es correcto. Me envió un correo pidiéndolo.", "Kyousuke"),
    235: ("Parece que Kuroneko-san y Kyou-chan se llevan bastante bien.", "Manami"),
    236: ("¿E-Es así?", "Kyousuke"),
    237: ("Sí, ¿podría ser que... ustedes dos están saliendo?", "Manami"),
    238: ("No no, no lo estamos.", "Kyousuke"),
    239: ("¿De veeerdad? Fufufu... sospechoso～", "Manami"),
    240: ("¡No es así!", "Kyousuke"),
    243: ("...«Una maldición»...", "Kuroneko"),
    244: ("No «disiparé» mi maldición hasta que mi deseo se cumpla.", "Kuroneko"),
    250: ("......", "Kyousuke"),
    251: ("¿No hay ningún lugar al que quieras ir?", "Manami"),
    252: ("Bueno, no.", "Kyousuke"),
    253: ("Okay. ¡Entonces montemos eso!", "Manami"),
    255: ("Hoy, te guiaré por Kioto todo el día.", "Manami"),
    256: ("--Sí, te lo dejo a ti.", "Kyousuke"),
}

data = {
    "000scriptAKYO_0145A.obj": build(a145_n, a145_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))