import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

T = "Ruta de Kanako"

n = {
    0: T,
    1: "Después de eso...",
    2: "Justo como ella declaró, Kanako me llamaba de vez en cuando.",
    7: "Está sudando muchísimo... ¿Es un asunto tan serio?",
    16: "Me está preguntando una pregunta tan difícil...",
    17: "Esa Ayase... Así que está continuando la «Operación Superar La Otakufobia» por su cuenta... Qué perseverancia.",
    22: "Lo siento, Kirino. Fui yo.",
    23: "Pero Ayase ya jugó SisxSis una vez, así que creo que debería estar bien prestárselo, ¿verdad?",
    31: "...¿Esta vez quiere que le compre ropa?",
    37: "Ah, esta vez, podría quedar enredado con una mujer realmente problemática.",
    40: "¡Esto es para proteger tu secreto!",
    43: "¿Debería simplemente decirle «estoy de prisa»? ¡Maldición...!",
    59: "Le compré ropa, la invité en el arcade...",
    68: "A la que amas no soy yo, sino mi billetera, ¿verdad?",
    82: "Mientras lo decía, me pasó un folleto.",
    89: "...Qué dato tan inesperado.",
    100: "En ese momento, Kanako no parecía una mocosa joven,",
    101: "sino una mujer mucho más mayor, con aspecto de adulta.",
    106: "Kanako desvió sus ojos de mí y miró hacia algún lugar a lo lejos.",
    114: "...Eso es peligroso.",
    122: "Yo soy, de hecho, el que está «saliendo» con ella ahora mismo, después de todo...",
    124: "Sí. Suena como lo que mi padre también me diría a mí.",
    129: "Kanako se alejó de mí y miró el sol poniente mientras extendía sus brazos.",
    136: "Ella se está refiriendo a...",
    137: "...la apasionada escena del beso en una calle durante una puesta de sol.",
    142: "¡Deja de bromear! ¡Como si pudiera hacer eso!",
    160: "¿Qué le pasa...",
    161: "Esto no está bien. Le dije que revelara lo que quisiera, pero... ¿Qué debo hacer?",
    162: "Después de eso, no supe nada de Kanako, y pasaron varios días sin incidentes.",
}
s = {
    3: ("Oye... Tengo algo que consultarte.", "Kirino"),
    4: ("Oh, ha pasado un tiempo desde que escuché eso.", "Kyousuke"),
    5: ("No te burles de mí.", "Kirino"),
    6: ("Perdón. Entonces, ¿qué es?", "Kyousuke"),
    8: ("...Ayase me pidió que le prestara «SisxSis».", "Kirino"),
    9: ("Pfft.", "Kyousuke"),
    10: ("...¿Hablas en serio?", "Kyousuke"),
    11: ("...Sí.", "Kirino"),
    12: ("...............", "Kyousuke"),
    13: ("...............", "Kirino"),
    14: ("...Oye, ¿qué crees que debería hacer?", "Kirino"),
    15: ("...Erm...", "Kyousuke"),
    18: ("¿L-Prestárselo?", "Kyousuke"),
    19: ("¡¿No es eso imposible?! En primer lugar, ¿cómo se enteró de SisxSis?", "Kirino"),
    20: ("...No fue porque se lo dijiste tú, ¿verdad?", "Kirino"),
    21: ("¿Cómo sería posible?", "Kyousuke"),
    24: ("Para estar seguros, ¿qué tal prestarle la versión para todas las edades?", "Kyousuke"),
    25: ("...Me pregunto si estará bien.", "Kirino"),
    26: ("Bueno...", "Kyousuke"),
    27: ("Perdón, una llamada... Hola.", "Kyousuke"),
    28: ("¿Kyousuke? Soy yo, soy yo.", "Kanako"),
    29: ("Tú.", "Kyousuke"),
    30: ("Ven conmigo a comprar por un rato...", "Kanako"),
    32: ("...¿Cuándo?", "Kyousuke"),
    33: ("¿Huh～? ¿No es obvio que me refiero a ahora mismo?", "Kanako"),
    34: ("¿Ahora...? Oye, puede que yo también tenga mis propios planes, ¿sabes?", "Kyousuke"),
    35: ("Ah, es～ así～. Kyousuke Manager-san, Kanako está muy herida.", "Kanako"),
    36: ("¡Está bien, está bien, está bien, está bien! ¡Allá voy!", "Kyousuke"),
    38: ("Perdón Kirino, tengo que salir.", "Kyousuke"),
    39: ("¡¿Huh?! ¡¿Todavía no hemos terminado nuestra conversación?!", "Kirino"),
    41: ("Está bien si es Ayase. Confía en tu mejor amiga.", "Kyousuke"),
    42: ("¡No digas cosas tan irresponsables!", "Kirino"),
    44: ("¡Me voy, Kirino!", "Kyousuke"),
    45: ("¡Espera...!", "Kirino"),
    46: ("...*pant pant pant*...", "Kyousuke"),
    47: ("Eres realmente lento. ¿Cuántos años planeabas hacerme esperar?", "Kanako"),
    48: ("Pensé que me regañarías así; por eso corrí hasta aquí, ¿sabes? Ni siquiera me tomé 10 minutos.", "Kyousuke"),
    49: ("Eso no servirá. De ahora en adelante, cuando Kanako te llame, tienes que estar aquí en 5 minutos. ¿Entendido?", "Kanako"),
    50: ("¡Chica de corazón negro!", "Kyousuke"),
    51: ("Jejeje. Bueno, vamos～♪", "Kanako"),
    52: ("...¿Por qué estás entrelazando tu brazo con el mío?", "Kyousuke"),
    53: ("Es una recompensa, una recompensa para Host-kun. Jeje, ¿no eres feliz?", "Kanako"),
    54: ("...No realmente.", "Kyousuke"),
    55: ("No hay necesidad de fingir.", "Kanako"),
    56: ("No lo estoy.", "Kyousuke"),
    57: ("Ya es hora de que volvamos. Ah, estoy un poco cansada.", "Kanako"),
    58: ("...Después de jugar tanto, eso es de esperarse.", "Kyousuke"),
    60: ("Eres una mujer que requiere mucho mantenimiento, ¿no?", "Kyousuke"),
    61: ("¡Gracias por hoy! Salgamos de nuevo la próxima vez.", "Kanako"),
    62: ("...Preferiría que no hubiera una próxima vez, aunque.", "Kyousuke"),
    63: ("No digas palabras tan frías～", "Kanako"),
    64: ("Oye, oye, Kyousuke♪", "Kanako"),
    65: ("¿Hmm?", "Kyousuke"),
    66: ("Te amo①", "Kanako"),
    67: ("Sí, sí, yo también.", "Kyousuke"),
    69: ("Yo.", "Kanako"),
    70: ("Yo. Entonces... ¿por qué me llamaste esta mañana?", "Kyousuke"),
    71: ("Vamos a ver una película.", "Kanako"),
    72: ("*suspiro*...", "Kyousuke"),
    73: ("Oye, ¿qué es esa actitud?", "Kanako"),
    74: ("¿No puedes mostrar un poco más de felicidad cuando una chica tan linda te invita a salir?", "Kanako"),
    75: ("Sabes... esto se siente como una cita, ¿no?", "Kyousuke"),
    76: ("......", "Kanako"),
    77: ("¿H-Huh?! Qué asco, ¿qué estás diciendo?", "Kanako"),
    78: ("Bueno, es cierto que he estado saliendo contigo mucho últimamente.", "Kanako"),
    79: ("Pero eres solo el anfitrión designado de Kanako... No lo olvides, ¿de acuerdo?", "Kanako"),
    80: ("...Sí, señora.", "Kyousuke"),
    81: ("Qué bueno que lo entiendas. Entonces, ¿vamos a ver esta película hoy?", "Kanako"),
    83: ("...Una película romántica, eh.", "Kyousuke"),
    84: ("Y-Yo quiero ver esa. ¿Tienes alguna queja?", "Kanako"),
    85: ("Nop, nada en absoluto. No tengo ninguna queja, Kanako-sama. Hasta que lleguemos al cine, ¿entrelazamos los brazos como la última vez?", "Kyousuke"),
    86: ("¡Q-Qué te crees, lolicon. Fue una recompensa para ti la última vez; no esperes ese servicio cada vez!", "Kanako"),
    87: ("¡Ah... Eso fue interesante! ¿No fue genial? Oye, oye, ¿no fue así?", "Kanako"),
    88: ("...Sí que te gustan este tipo de películas románticas súper cliché.", "Kyousuke"),
    90: ("¿E-Eso es malo?", "Kanako"),
    91: ("Nop, está bien, ¿no?", "Kyousuke"),
    92: ("Creo que es normal que a las chicas les guste el romance.", "Kyousuke"),
    93: ("...Cállate.", "Kanako"),
    94: ("Ese tipo de desarrollo no es posible en la realidad. Ese tipo de pareja tampoco existe.", "Kanako"),
    95: ("Hasta los idiotas entienden eso. Es todo ficticio y falso. Pero...", "Kanako"),
    96: ("Esa es la parte buena de esto.", "Kanako"),
    97: ("...Je.", "Kyousuke"),
    98: ("Tanto el chico como la chica son buenas personas, se aman mucho y se quedan juntos hasta el final.", "Kanako"),
    99: ("Incluso si es ficción, eso está bien.", "Kanako"),
    102: ("¿Tienes novio?", "Kyousuke"),
    103: ("...¿Por qué preguntas? ¿Estás interesado?", "Kanako"),
    104: ("Algo así.", "Kyousuke"),
    105: ("...Hmm...", "Kanako"),
    107: ("No tengo.", "Kanako"),
    108: ("...¿Eh?", "Kyousuke"),
    109: ("...¿Por qué estás tan sorprendido?", "Kanako"),
    110: ("Pensé que tendrías mucha experiencia en relaciones. He escuchado muchas historias sobre ti de Kirino.", "Kyousuke"),
    111: ("Ah, cosas como chicos que me mantienen y me tratan?", "Kanako"),
    112: ("Sip.", "Kyousuke"),
    113: ("Esos chicos no son mis novios. Solo estoy saliendo con ellos.", "Kanako"),
    115: ("Por eso, nunca he tenido novio.", "Kanako"),
    116: ("Hmm.", "Kyousuke"),
    117: ("...¿Estás aliviado?", "Kanako"),
    118: ("¿Por qué lo estaría?", "Kyousuke"),
    119: ("Jejeje.", "Kanako"),
    120: ("Ahem... No deberías hacer ese tipo de cosas. Es peligroso estar a solas con chicos que no conoces...", "Kyousuke"),
    121: ("Espera... ¿Eso no me incluye a mí?", "Kyousuke"),
    123: ("Gyahaha, hablas como un anciano.", "Kanako"),
    125: ("Ya he dejado de hacer eso.", "Kanako"),
    126: ("¿Eh?", "Kyousuke"),
    127: ("...Después de todo, ahora tengo un anfitrión obediente.", "Kanako"),
    128: ("...Qué bueno saberlo.", "Kyousuke"),
    130: ("Ah... Eso fue divertido.", "Kanako"),
    131: ("Es lindo... Kanako también desea experimentar ese tipo de cosas.", "Kanako"),
    132: ("¿Ese tipo de cosas?", "Kyousuke"),
    133: ("Un beso.", "Kanako"),
    134: ("Guh.", "Kyousuke"),
    135: ("Hay mucha gente aquí, justo como la escena de la película, ¿verdad?", "Kanako"),
    138: ("...¿Quieres intentarlo?", "Kanako"),
    139: ("¡Como si!", "Kyousuke"),
    140: ("Está bien. Vamos, es solo un beso. ¿De acuerdo?", "Kanako"),
    141: ("¡No lo haré!", "Kyousuke"),
    143: ("En realidad quieres hacerlo, ¿no? Esta es probablemente la última oportunidad en tu vida para hacerlo, ¿sabes?", "Kanako"),
    144: ("No lo haré.", "Kyousuke"),
    145: ("...Tch, simplemente no puedes seguir el juego...", "Kanako"),
    146: ("...Bueno entonces, es una orden.", "Kanako"),
    147: ("...¿Q-Qué?", "Kyousuke"),
    148: ("Si no me besas, revelaré tu secreto.", "Kanako"),
    149: ("Tú...", "Kyousuke"),
    150: ("...Haz lo que quieras.", "Kyousuke"),
    151: ("¿Eh, eh?", "Kanako"),
    152: ("Adelante, revélalo si quieres. Hazme el ridículo si quieres. No voy a seguirle el juego.", "Kyousuke"),
    153: ("No hagas este tipo de cosas a personas a las que realmente no quieres.", "Kyousuke"),
    154: ("¿Qué...", "Kanako"),
    155: ("¡Tú...!", "Kanako"),
    156: ("¿Qué es?", "Kyousuke"),
    157: ("¡¿Estás estúpido!! ¡Ya no me importas!!", "Kanako"),
    158: ("¡¡Será mejor que lo recuerdes!!", "Kanako"),
    159: ("Ah, ¡oye!", "Kyousuke"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
current["000scriptKIFK_0001A.obj"] = build(n, s)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptKIFK_0001A.obj")