import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0090_n = {
    0: "Ruta de Kuroneko · Encuentro Después De La Escuela",
    1: "¡E-Esta vez debo...! Me hicieron pasar un mal rato durante el descanso del almuerzo pero esto...!",
    2: "¡Definitivamente lo resolveré esta vez, Kuroneko!",
    3: "Es inútil ir a su salón después de todo. En ese caso...",
    13: "Los zapatos de Kuroneko todavía están por aquí...",
    14: "¡Victoria! De esta manera, definitivamente vendrá aquí!",
    15: "Todo lo que tengo que hacer es esperar aquí.",
}
a0090_s = {
    4: ("¡El salón del club!", "Kyousuke"),
    5: ("Hmm...", "Kyousuke"),
    6: ("Así que no vino... Kuroneko...", "Kyousuke"),
    7: ("Maldición... si llega a esto...", "Kyousuke"),
    8: ("Disculpe, ¿Gokou vino a las actividades del club recientemente?", "Kyousuke"),
    9: ("No... No ha estado apareciendo en el 【Salón del Club】 últimamente...", "Student"),
    10: ("Ya veo...", "Kyousuke"),
    11: ("Siempre se va a casa inmediatamente después de la escuela, así que probablemente ya debería estar en los 【Casilleros de Zapatos】...", "Student"),
    12: ("¡Gracias!", "Kyousuke"),
    16: ("Hola, te estaba esperando.", "Kyousuke"),
    17: ("......Adiós.", "Kuroneko"),
    18: ("¡Oye, espérate!", "Kyousuke"),
    19: ("Kuh...", "Kuroneko"),
    20: ("Bueno entonces...", "Kyousuke"),
}

a0093_n = {
    0: "Ruta de Kuroneko · Encuentro Después De La Escuela",
    79: "No te dejaré escapar más...",
}
a0093_s = {
    1: ("...¿Qué es?", "Kuroneko"),
    2: ("Tengo algo que hablar contigo.", "Kyousuke"),
    3: ("Parece que has reunido algo de entusiasmo... pero sigue siendo inútil sin importar cuántas veces lo digas.", "Kuroneko"),
    4: ("No sé si será inútil o no. Vamos, acompáñame un rato.", "Kyousuke"),
    5: ("Desafortunadamente, no tengo tiempo para hablar contigo.", "Kuroneko"),
    6: ("Puede que no tengas cosas de qué hablar, pero yo tengo cosas que necesito decirte.", "Kyousuke"),
    7: ("...Estás siendo bastante enérgico.", "Kuroneko"),
    8: ("¿No es inútil si no lo hago con la tú actual?", "Kyousuke"),
    9: ("¿Entonces estás tratando de torcer mi voluntad a la fuerza?", "Kuroneko"),
    10: ("Nada de eso, solo que no escucharás si no hablo más enérgicamente.", "Kyousuke"),
    11: ("Después de todo, ya he tenido algo de experiencia antes.", "Kyousuke"),
    12: ("...Ya veo. Sin embargo...", "Kuroneko"),
    13: ("Entonces por favor intenta hacer algo de tiempo...", "Kyousuke"),
    14: ("¿Bajando el perfil esta vez? ¿Crees que agachar la cabeza y rogar funcionará?", "Kuroneko"),
    15: ("Es inútil, tu orgullo no vale nada si te rebajas así.", "Kuroneko"),
    16: ("Es verdad que mi orgullo no vale nada, rebajándome a esto. Conozco muy bien mi propia inutilidad.", "Kyousuke"),
    17: ("¡Pero por favor! ¡Escucha lo que tengo que decir!", "Kyousuke"),
    18: ("...No, no tengo nada que decirte.", "Kuroneko"),
    19: ("En cualquier caso, no interfieras.", "Kuroneko"),
    20: ("¿Interferir...? Solo voy a hablar contigo de camino a casa...", "Kyousuke"),
    21: ("Ciertamente es una pérdida de tiempo estar forzada a quedarme aquí. Está bien, iré al salón del club en su lugar.", "Kuroneko"),
    22: ("...¿No planeabas irte a casa?", "Kyousuke"),
    23: ("...Solo recordé que tenía algo que hacer.", "Kuroneko"),
    24: ("Entonces te acompañaré.", "Kyousuke"),
    25: ("...Sabes que esto estará obstaculizando mi meta, ¿no?", "Kuroneko"),
    26: ("Yo también soy miembro del club. No hay problema, ¿verdad?", "Kyousuke"),
    27: ("...Ciertamente, de hecho eres miembro también. Sin embargo, ¿sabes que los miembros de papel solo obstaculizan a los demás miembros del club?", "Kuroneko"),
    28: ("¿N-No debería haber ningún problema si me mantengo callado, verdad?", "Kyousuke"),
    29: ("Solo serás una molestia visual si te quedas ahí, senpai.", "Kuroneko"),
    30: ("Y-Yo no tienes que decirlo así...", "Kyousuke"),
    31: ("¿Entonces simplemente no quieres estar conmigo?", "Kyousuke"),
    32: ("Parece que lo percibiste bastante bien. Eso es exactamente lo que siento.", "Kuroneko"),
    33: ("...¿De verdad soy un obstáculo tan grande para ti?", "Kyousuke"),
    34: ("Absolutamente. ¿Qué quieres que diga esta vez para rechazarte?", "Kuroneko"),
    35: ("...Cualquier cosa servirá, solo dilo.", "Kyousuke"),
    36: ("De acuerdo, entonces lo diré.", "Kuroneko"),
    37: ("Eres un obstáculo.", "Kuroneko"),
    38: ("Lo diré tantas veces como sea necesario. Para ser completamente honesta, estás siendo una molestia.", "Kuroneko"),
    39: ("Reflexiona sobre cómo tus propias acciones pueden causar problemas a los demás.", "Kuroneko"),
    40: ("¿Cuántos rechazos tomará para que ese cerebro de bajo CI lo entienda?", "Kuroneko"),
    41: ("¡¿Eh?! ¡¿Eh?!", "Kyousuke"),
    42: ("...Estás siendo bastante dura.", "Kyousuke"),
    43: ("Eso es porque ya lo has hecho.", "Kuroneko"),
    44: ("¡No lo entiendo! ¡Solo estoy preocupado por ti!", "Kyousuke"),
    45: ("¡¿Por qué me estás rechazando?!", "Kyousuke"),
    46: ("¡A mí! ¡No solo a mí, también a Kirino! ¡A todos!", "Kyousuke"),
    47: ("......No lo entenderías incluso si lo dijera.", "Kuroneko"),
    48: ("¡No lo sabrías!", "Kyousuke"),
    49: ("Cállate. Grábate estas palabras en el cráneo. Deja de seguirme por ahí.", "Kuroneko"),
    50: ("No digas algo así... ¿No se preocuparía naturalmente la gente por alguien que conoce si de repente actuara de forma extraña?", "Kyousuke"),
    51: ("......¿Es así?", "Kuroneko"),
    52: ("Sí, ¿no te preocuparías también tú si alguien que conoces actuara de forma extraña?", "Kyousuke"),
    53: ("Depende de la persona. Yo hago una distinción entre amigos y meros conocidos.", "Kuroneko"),
    54: ("No creo que seamos completos desconocidos, ¿verdad?", "Kyousuke"),
    55: ("Eres una amiga que sale con nosotros, e incluso vino a mi casa a jugar, ¿no?", "Kyousuke"),
    56: ("...Aunque eso sea verdad...", "Kuroneko"),
    57: ("...Me estoy preocupando más cuanto más lo pones así.", "Kyousuke"),
    58: ("Es inútil preocuparse, solo acéptalo si la persona en cuestión lo dice.", "Kuroneko"),
    59: ("¡Por eso dije que me estoy preocupando más cuando actúas así!", "Kyousuke"),
    60: ("*suspiro*... ¿Sabes lo que significa «No es asunto tuyo»?", "Kuroneko"),
    61: ("...¿Es así como es ahora mismo?", "Kyousuke"),
    62: ("Sí, exactamente.", "Kuroneko"),
    63: ("*suspiro*... Senpai, ¿no lo entiendes aunque ya he dicho esto?", "Kuroneko"),
    64: ("Sí, no lo entiendo. No sé qué decir para que lo entiendas.", "Kyousuke"),
    65: ("Entonces déjame decirte, desearía que te rindieras.", "Kuroneko"),
    66: ("Fastidiar no es una forma de expresar preocupación, ¿lo entiendes?", "Kuroneko"),
    67: ("Eso es lo que haré si creo que es necesario...", "Kyousuke"),
    68: ("Pero, por lo que parece, no hay más opción que fastidiarte sin fin.", "Kyousuke"),
    69: ("Por eso...", "Kyousuke"),
    70: ("....Ya lo entiendo, esta es la última vez, así que déjame acompañarte.", "Kyousuke"),
    71: ("¿La última vez? ¿De qué estás hablando? Para empezar, todavía no ha pasado nada...", "Kuroneko"),
    72: ("¿De verdad lo entiendes?", "Kuroneko"),
    73: ("...No, no lo entiendo en absoluto.", "Kyousuke"),
    74: ("Oh en serio, entonces lo pondré de manera más clara, ya que es tedioso.", "Kuroneko"),
    75: ("Así que es mejor que lo dejes.", "Kuroneko"),
    76: ("...¿Tedioso, dices...? Es un revés incluso para mí cuando dices eso.", "Kyousuke"),
    77: ("Entonces lo diré unas cuantas veces más, es tedioso.", "Kuroneko"),
    78: ("Entonces, como último esfuerzo siendo la persona tediosa, te fastidiaré todo el camino.", "Kyousuke"),
    80: ("¿Qué-", "Kuroneko"),
}

a0095_s = {
    0: "Ruta de Kuroneko · Encuentro Después De La Escuela",
    1: ("Suéltame al instante, de lo contrario gritaré.", "Kuroneko"),
    2: ("¿Qué soy yo, un pervertido?", "Kyousuke"),
    3: ("¿No es ese el caso? Es porque estás tratando de arrastrarme contra mi voluntad.", "Kuroneko"),
    4: ("Eso es porque no estás siendo honesta.", "Kyousuke"),
    5: ("¿Cuántas veces tengo que decir para que entiendas que no tengo el tiempo libre para hablar contigo?", "Kuroneko"),
    6: ("...De todos modos, solo sígueme.", "Kyousuke"),
}

a0098_n = {
    0: "Ruta de Kuroneko · Encuentro Después De La Escuela",
    1: "...Parece que no hay nadie más en el salón del club.",
    2: "No habrá nadie que interfiera si habláramos adentro.",
}
a0098_s = {
    3: ("Por Dios... ¿qué planeas hacer al traerme aquí?", "Kuroneko"),
    4: ("No planeo hacer nada... Solo tengo algo que preguntarte, Kuroneko.", "Kyousuke"),
}

a0100_n = {
    0: "Ruta de Kuroneko · Encuentro Después De La Escuela",
}
a0100_s = {
    1: ("¿Qué demonios querías preguntarme?", "Kuroneko"),
    2: ("Estoy seguro de que lo sabes, ya que te tomaste el tiempo de escucharme después de todo.", "Kyousuke"),
    3: ("¿No es eso de por sí dado?", "Kuroneko"),
    4: ("Seguro que eres directa, ¿no?", "Kyousuke"),
    5: ("Ya que te estoy acompañando en un recado tan insensato, solo ahorrame el sarcasmo.", "Kuroneko"),
    6: ("Dios... como sea, iré directo al grano.", "Kyousuke"),
    7: ("Te preguntaré una vez más. Dime los problemas que estás teniendo.", "Kyousuke"),
    8: ("No es como si necesitara decirte nada.", "Kuroneko"),
    9: ("¿Por qué sigues diciendo eso? ¡Estoy preocupado por ti!", "Kyousuke"),
    10: ("Qué persona tan problemática... Ciertamente sería lamentable si te lo dijera.", "Kuroneko"),
    11: ("¿Por qué es lamentable? ¿Quién lo lamentará?", "Kyousuke"),
    12: ("Seré yo. Lamento haber mencionado esto en primer lugar.", "Kuroneko"),
    13: ("...Hmm, parece que estás siendo filosófica aquí...", "Kyousuke"),
    14: ("¿En serio? Se supone que mi habla y conducta son fáciles de entender, ¿no es así?", "Kuroneko"),
    15: ("¿Qué estás diciendo?", "Kyousuke"),
    16: ("...He elegido la respuesta más adecuada para hacerte sentir satisfecho.", "Kuroneko"),
    17: ("¿No estás tratando muy duro de sonar sofisticada?", "Kyousuke"),
    18: ("Hmm... podría ser el caso. Pero no importa de todos modos, ya que no lo entenderías.", "Kuroneko"),
    19: ("Entonces, ¿no te rendirás ya?", "Kuroneko"),
    20: ("No. Solo estoy empezando.", "Kyousuke"),
    21: ("...*suspiro*, ya entiendo tu entusiasmo.", "Kuroneko"),
    22: ("Entonces por fin entiendes.", "Kyousuke"),
    23: ("Sí, es simplemente pasión imprudente.", "Kuroneko"),
    24: ("¡Estoy totalmente en serio! ¡No estoy siendo imprudente!", "Kyousuke"),
    25: ("Si no conservas tu compostura, es lo mismo. Dije que entendí tu entusiasmo, ¿no es así?", "Kuroneko"),
    26: ("Sin embargo, esto no tiene nada que ver contigo.", "Kuroneko"),
    27: ("¿Cómo puede no tener nada que ver conmigo si está pasando a mi alrededor?", "Kyousuke"),
    28: ("Un buen argumento.", "Kuroneko"),
    29: ("Pero si terminas involucrándote en todo, ¿no estarías hasta el cuello de trabajo?", "Kuroneko"),
    30: ("Por supuesto, hay prioridades que necesito manejar, por eso estoy tratando contigo primero.", "Kyousuke"),
    31: ("No puede no tener nada que ver conmigo si te concierne a ti.", "Kyousuke"),
    32: ("...¿Es por tu amabilidad?", "Kuroneko"),
    33: ("¿Eh? ¿Qué dijiste? No pude escucharlo bien...", "Kyousuke"),
    34: ("...No importa. De todos modos, debería agradecerte ya que estás haciendo esto por mi bien.", "Kuroneko"),
    35: ("Ya veo... entonces, dime...", "Kyousuke"),
    36: ("Pero, no quiero.", "Kuroneko"),
    37: ("¿Por qué es eso?", "Kyousuke"),
    38: ("...No lo digas tan fríamente.", "Kyousuke"),
    39: ("Lo digo en serio cuando digo que no tiene nada que ver contigo. ¿No es por tu arrogancia que estás sintiendo la frialdad de mis palabras?", "Kuroneko"),
    40: ("¿Por qué piensas eso?", "Kyousuke"),
    41: ("¿Porque solo estás forzando tus propios sentimientos sobre los demás?", "Kuroneko"),
    42: ("¿Cómo no voy a preocuparme si empiezas a hablar de algo así?", "Kyousuke"),
    43: ("Además, es solo una pérdida de tiempo si continuáramos con este tema filosófico.", "Kuroneko"),
    44: ("Cambiemos de tema.", "Kuroneko"),
    45: ("Ciertamente te causará problemas si te lo dijera.", "Kuroneko"),
    46: ("...¿Por qué me causaría problemas?", "Kyousuke"),
    47: ("Porque te lastimaría a ti también.", "Kuroneko"),
    48: ("Si ese es el caso, ¿no me causaría dolor también el no decirme nada?", "Kyousuke"),
    49: ("¿No estás solo metiéndote en problemas sin pensar?", "Kuroneko"),
    50: ("No es así, pero es realmente problemático.", "Kuroneko"),
    51: ("Si es problemático o no no depende de ti decidirlo, me toca a mí decidirlo.", "Kyousuke"),
    52: ("...Cierto, lo que has dicho es correcto.", "Kuroneko"),
    53: ("Pero ya que lo sabes, ¿por qué no puedes entender que tampoco deseo causarte daño?", "Kuroneko"),
    54: ("E-Eso es...", "Kyousuke"),
    55: ("Has planteado un montón de teorías unilaterales, pero esas son más como pensamientos irracionales que teorías.", "Kuroneko"),
    56: ("P-Pero... ¿no es lo que realmente importa cómo uno piensa, y no cómo uno se expresa?", "Kyousuke"),
    57: ("Protesta innecesaria... eso es lo que mejor te describe.", "Kuroneko"),
    58: ("Por Dios... no te rindes, ¿verdad? Sin embargo, esa es exactamente la razón por la que no te lo digo.", "Kuroneko"),
    59: ("...Estorbando... no lo pensé de esa manera.", "Kyousuke"),
    60: ("Hmph, sabía que dirías eso.", "Kuroneko"),
    61: ("Por eso te estás involucrando en varias situaciones sin darte cuenta de que estás perdiendo algo.", "Kuroneko"),
    62: ("¿Perdiendo algo, y qué es eso?", "Kyousuke"),
    63: ("De hecho eres una buena persona por no darte cuenta.", "Kuroneko"),
    64: ("Así es, senpai es una buena persona, así que si hablo, seguramente...", "Kuroneko"),
    65: ("No, incluso puedo decir que definitivamente. Definitivamente te involucrarás.", "Kuroneko"),
    66: ("¿Estás diciendo que no debería?", "Kyousuke"),
    67: ("Sí, si no entiendes la necesidad de ser reservado, entonces eres verdaderamente un hombre egoísta.", "Kuroneko"),
    68: ("Sí, eso es porque soy obstinadamente amable.", "Kyousuke"),
    69: ("Me llaman amable porque persevero en mis acciones. ¡Por eso tu conveniencia es irrelevante!", "Kyousuke"),
    70: ("¿Qué-", "Kuroneko"),
    71: ("....Sí, así es, por eso te estoy pidiendo que me dejes involucrarme esta vez también.", "Kyousuke"),
    72: ("...Hmph. ¿Cuántos suspiros tengo que dar? Honestamente, eres tan...", "Kuroneko"),
    73: ("¿No puedo ser una buena persona?", "Kyousuke"),
    74: ("Hay momentos en los que una buena persona sería una mala, sin embargo...", "Kuroneko"),
    75: ("¿Sin embargo? ¿No eres igual?", "Kyousuke"),
    76: ("Exactamente, desearía que esta persona pudiera darse cuenta rápidamente de que sus buenas intenciones son solo un obstáculo.", "Kuroneko"),
    77: ("No lo entiendo...", "Kyousuke"),
    78: ("Qué cabeza dura... No, por eso no necesito a esta buena persona.", "Kuroneko"),
    79: ("Vaya, cómo desearía poder terminar rápidamente este tormento con una persona así.", "Kuroneko"),
    80: ("No sé exactamente qué problema tienes, pero puedo sentir más o menos cuánto no quieres contármelo.", "Kyousuke"),
    81: ("Pero no me convenzo fácilmente. Es lo mismo sin importar cómo me sujetes.", "Kyousuke"),
    82: ("¡Esto no es sobre otros, sino sobre ti! ¡¿Cómo podría tratarlo como si fuera un extraño?!", "Kyousuke"),
    83: ("Desearía que pudieras decírmelo incluso si te sintieras irritada.", "Kyousuke"),
    84: ("¿Podrías por favor dejar de buscar excusas para rechazarme?", "Kyousuke"),
    85: ("Aunque no sé qué más decir para pedírtelo, pero por favor, Kuroneko... ¿De acuerdo?", "Kyousuke"),
}

data = {
    "000scriptCKUR_0090A.obj": build(a0090_n, a0090_s),
    "000scriptCKUR_0093T.obj": build(a0093_n, a0093_s),
    "000scriptCKUR_0095A.obj": build({0: a0095_s[0]}, {k: v for k, v in a0095_s.items() if k != 0}),
    "000scriptCKUR_0098A.obj": build(a0098_n, a0098_s),
    "000scriptCKUR_0100T.obj": build(a0100_n, a0100_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
