import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

T = "if · Mi Amigo Akagi"

n = {
    0: T,
    1: "El día después de que regresamos sanos y salvos del viaje escolar",
    2: "Mientras el sentimiento del viaje no se había desvanecido por completo todavía, las clases de ese día se manejaron impecablemente.",
    3: "Y luego, después de que terminó la escuela...",
    28: "Uheh... Está hirviendo aquí dentro...",
    29: "En realidad hace más calor aquí que afuera debido a la multitud densa y apretada de cuerpos calientes...",
    30: "Pero... incluso así.",
    42: "Akagi dio una sonrisa deslumbrante mientras decía eso.",
    43: "A cambio, di una sonrisa amarga.",
    65: "Increíble. En serio eres el modelo de un hermano mayor entrenado.",
    66: "Sabía que este tipo era un siscon que adoraba a su hermana, pero no pensé que fuera tan hardcore.",
    67: "Definitivamente no quiero seguir su ejemplo, aunque.",
    70: "¿Fue mi imaginación, o las miradas de las chicas que nos habían estado mirando desde antes se estaban calentando de una manera inquietante?",
    71: "Cómo decirlo... Sus ojos eran como los de rapaces dirigidos a su presa...",
    72: "No me siento seguro de que pueda llegar a casa con vida si me desvío y me pierdo aquí...",
    79: "Mientras hablaba bruscamente, Akagi me miró con una expresión preocupada.",
    80: "Es realmente importante tener un amigo cercano.",
    81: "Es mucho más confiable que su brutal hermanita, y es el mejor amigo que podría tener.",
    85: "Al escuchar esas voces femeninas desde algún lugar, todas mis funciones corporales se detuvieron temporalmente.",
    90: "Por supuesto que no.",
    91: "Mis oídos definitivamente lo habían captado.",
    92: "Las chicas estaban hablando de nosotros... no, eso no era todo.",
    93: "Las mujeres que nos rodeaban nos miraban intermitentemente, y podía decir que nos estaban usando como víctimas de sus terribles delirios.",
    96: "Esto es malo, esto es malo, Akagi...",
    97: "¡A este ritmo, vamos a terminar como comida para las rapaces...!",
    100: "No sé si Akagi entendió lo que estaba pasando, pero parecía haber sentido el peligro.",
    101: "Nos miramos a los ojos y asentimos.",
    102: "Y entonces, la mano de Akagi agarró firmemente la mía...",
    104: "Podía sentir la fuerte determinación de Akagi a través de su mano.",
    105: "Nos abrimos paso entre la multitud y tratamos de escapar.",
    106: "Sin embargo, los participantes del Comiket que nos rodeaban, como anticipando algo, bloquearon nuestro camino con indiferencia.",
    111: "...Perdón, Akagi.",
    112: "Como para pisotear la determinación de Akagi, fui succionado hacia el centro de este sofocante crisol de multitud.",
    114: "...Escuché la voz de Akagi varias veces a través de una membrana delgada.",
    115: "Una presión violenta pesaba sobre mi cuerpo, y ni siquiera podía respirar.",
    116: "Tengo que responder al grito de Akagi. Tengo que responder.",
    117: "Sin embargo, me derrumbé en el piso del salón del Comiket mientras abría desesperadamente mi boca como un pez dorado asfixiándose.",
    118: "...Escuché la voz de Akagi varias veces a través de una membrana delgada.",
    119: "Una presión violenta pesaba sobre mi cuerpo, y ni siquiera podía respirar.",
    120: "Tengo que responder al grito de Akagi. Tengo que responder.",
    121: "Sin embargo, estaba a punto de derrumbarme en el piso del salón del Comiket mientras abría desesperadamente mi boca como un pez dorado asfixiándose--",
    123: "...Justo antes de perder el conocimiento, la mano de Akagi me agarró.",
    124: "Después de eso, de alguna manera logró arrastrarme hasta un espacio abierto.",
    128: "Hundiéndome en el piso, contemplé las olas de personas a nuestro alrededor.",
    129: "Esto... era malo.",
    130: "No podía ver ni un solo espacio entre el flujo ininterrumpido de rapaces.",
    135: "Akagi me hizo levantarme a la fuerza.",
    136: "Luego fui arrastrado una vez más al mar humano...!",
    142: "¡Estoy agotado! ...Pero no tenía ni una mínima cantidad de la energía necesaria para decir eso.",
    143: "Había pasado algún tiempo desde que fuimos tragados por ese mar humano antes.",
    144: "Aunque había logrado ser salvado por Akagi y creía que escaparíamos en ese punto, Akagi había reanudado triunfalmente sus compras.",
    151: "Te respeto seriamente.",
    152: "Si tuviera ese tipo de hermanita, podría matarme.",
    155: "Había acumulado un sudor de sensación desagradable debido a algo más que solo el calor.",
    156: "Quiero darme un baño rápido y refrescarme... tanto en cuerpo como en mente.",
    162: "¿El calor del verano te hace no querer bañarte? ¡Qué tontería!",
    163: "Porque el verano es caluroso, te sumerges en agua caliente y te quitas el sudor, disfrutando del verano. Es decir, este es el máximo",
    164: "placer!",
    165: "Del mismo modo, comer ramen a mitad del verano también es con estilo.",
    166: "Además, ¡lo tenemos reservado para nosotros! ¡Esto es lo mejor!",
    175: "Akagi masajeó mi cuerpo alegremente.",
    176: "Su habilidad en ello no era mala.",
    177: "Si está dudando entre ir a la universidad o conseguir un trabajo en el futuro, debería abrir un salón de masajes.",
    195: "Sin tiempo para detenerlo, Akagi se levantó frente a mí...",
    196: "Y, algo convenientemente, empezó a actuar aturdido.",
    206: "Sostuve el cuerpo de Akagi y lo puse de pie.",
    207: "Su cuerpo estaba caliente como lava.",
    211: "Mientras levantaba mi pie para salir del baño...",
    212: "...Mi pierna resbaló, hundiéndome en el baño.",
    213: "Intenté levantarme inmediatamente, pero no podía ponerme de pie bien mientras sostenía el cuerpo de Akagi.",
    214: "...Esto es malo! ¡Espera, Akagi?!",
    215: "La escena que apenas entró en mi campo de visión fue la de Akagi habiendo desmayado y perdido completamente la conciencia.",
    217: "Llamé desesperadamente para llamar la atención de Akagi.",
    218: "Pero estaba en el baño, así que solo agua de 42 grados entró en mi boca.",
    219: "Mientras sentía el peso de Akagi con todo mi cuerpo, mi mente se quedó en blanco...!",
    220: "...Después de eso, de alguna manera fui rescatado por el encargado del baño.",
    221: "Si no se hubiera dado cuenta... quién sabe qué habría pasado...",
    224: "Después de que nos permitieron descansar un rato, nos compramos leche de café en lugar de agradecimiento.",
    225: "Aunque me bañé, me siento aún más cansado.",
    226: "Después, Akagi parecía tener otro lugar al que quería ir, pero decidí declinar e irme a casa.",
    228: "Me sentí tan agotado como era posible.",
    229: "Sentí que apenas tenía la fuerza para estar de pie. Si esto fuera un juego, mi HP estaría en la zona amarilla, y mi MP estaría completamente vacío.",
    236: "Akagi me estaba mirando con una cara inusualmente seria.",
    237: "Ya sea porque mi corazón no era honesto o sentía algún tipo de motivo oculto de Akagi, realmente no podía aceptar sus palabras de frente.",
    253: "¿Supongamos que todas las dificultades de hoy fueran por el bien de Kirino?",
    254: "...Solo pensar en ello parecía aumentar repentinamente mi agotamiento.",
    255: "¿Por qué Akagi piensa que su propia hermanita es tan linda?",
    256: "No lo entendía en absoluto.",
    257: "Pero, bueno... No estaba mal pasar el rato juntos solo nosotros dos.",
    276: "La forma en que Akagi me suplicaba desesperadamente me hizo sentir tanto asco, como extrañamente en paz.",
    277: "Bueno... Lo que le dije antes no era una mentira.",
    278: "...No está tan mal, salir así juntos nosotros dos de vez en cuando.",
    285: "No me molesté en intentar replicar a esa declaración de «la chica más linda del mundo, Sena-chan».",
    286: "Sé muy bien cómo eres un idiota que adora a su hermanita sin rival.",
    294: "Dios... Retiro inmediatamente lo que dije hace un momento.",
    295: "--No está tan mal, salir así juntos nosotros dos de vez en cuando.--",
    296: "¡Eso es algo que no debe decirse en presencia de esta hermanita fujoshi!",
}
s = {
    4: ("Oye, Kousaka. Estás libre durante las vacaciones de verano, ¿verdad?", "Akagi"),
    5: ("Al menos pregunta «¿Tienes planes?»", "Kyousuke"),
    6: ("¿Huh? ¿Entonces has hecho planes con Tamura-san?", "Akagi"),
    7: (".........No.", "Kyousuke"),
    8: ("¿Verdad? Entonces está bien, así que acompáñame por un rato.", "Akagi"),
    9: ("¿Acompañarte... a qué?", "Kyousuke"),
    10: ("¡No te estoy pidiendo nada como ir a levantar mujeres en la piscina o en un espectáculo de fuegos artificiales!", "Akagi"),
    11: ("No pregunté nada de eso. Más bien, de verdad parece que lo pensaste un poco.", "Kyousuke"),
    12: ("¡Hah! Eres tan estúpido, Kousaka-kun. ¡Como si un tipo guapo como yo se sintiera encaprichado por las mujeres!", "Akagi"),
    13: ("¿Puedo golpearte?", "Kyousuke"),
    14: ("Kousaka. Solo deberías levantar el puño cuando sea por la mujer que es importante para ti.", "Akagi"),
    15: ("Basándome solo en esa línea, eres sin duda un hombre excelente.", "Kyousuke"),
    16: ("¿Entonces? ¿Qué quieres conmigo?", "Kyousuke"),
    17: ("¡Qué amable de tu parte preguntar, mi amigo sincero!", "Akagi"),
    18: ("El lugar al que voy es...", "Akagi"),
    19: ("......¿Es?", "Kyousuke"),
    20: ("¡¡El Tokyo Big Sight......!!", "Akagi"),
    21: (".........*suspiro*", "Kyousuke"),
    22: ("¿Qué te pasa, Kousaka? Sigues suspirando.", "Akagi"),
    23: ("¿Por qué estoy participando en el Comiket de Verano en medio de este maldito calor, con un bastardo como tú?", "Kyousuke"),
    24: ("......¿Porque te invité?", "Akagi"),
    25: ("Bueno, eso es cierto.", "Kyousuke"),
    26: ("De todos modos, apurémonos y entremos. Me estoy secando con este calor aquí afuera...", "Akagi"),
    27: ("Mis pensamientos exactamente. Preferiría no secarme al sol junto contigo tampoco.", "Kyousuke"),
    31: ("¿No es bastante alto el porcentaje de mujeres hacia donde nos dirigimos?", "Kyousuke"),
    32: ("¿Qué estás diciendo, Kousaka? No hay distinción entre hombres y mujeres en este mundo, ¿verdad?", "Akagi"),
    33: ("Los hombres aman a las mujeres, las mujeres aman a los hombres... Ese es el reciclaje de la vida.", "Akagi"),
    34: ("Es ciclo, ciclo. No lo mezcles con reciclaje.", "Kyousuke"),
    35: ("¡Hmph! ¡De todos modos!", "Akagi"),
    36: ("El lugar hacia donde nos dirigimos es la zona para mujeres separadas de esas éticas y moralidades.", "Akagi"),
    37: ("......¿Para mujeres?", "Kyousuke"),
    38: ("Bueno, incluso si digo para mujeres, también hay varias cosas para chicas jóvenes, pero a lo que apuntamos es al lugar de las fujoshi--en otras palabras, BL.", "Akagi"),
    39: ("Por cierto, «BL» no es una abreviatura de tocino y lechuga, ¿sabes? Significa romance entre hombres, Boy's Love.", "Akagi"),
    40: ("...Gracias por darme la explicación más innecesaria de mi vida.", "Kyousuke"),
    41: ("¡Seguro! ¡De nada!", "Akagi"),
    44: ("No pongas una cara tan cansada.", "Akagi"),
    45: ("Oye, piensa con cuidado. ¿Cuál es nuestro género?", "Kyousuke"),
    46: ("¡Masculino!", "Akagi"),
    47: ("Bien hecho. Entonces, aquí hay un problema. Si dos amigos varones cercanos se lanzaran a una multitud de mujeres para comprar bienes BL...", "Kyousuke"),
    48: ("Ahora bien, ¿qué pasará?", "Kyousuke"),
    49: ("Bueno, naturalmente...", "Akagi"),
    50: ("¡Terminarán como víctimas de los delirios de las fujoshi!", "Akagi"),
    51: ("¿Nos vamos a casa inmediatamente?", "Kyousuke"),
    52: ("No podemos, Kousaka. Incluso para mí, es tan doloroso que quiero suicidarme, ¿sabes?", "Akagi"),
    53: ("¡¿Eso?! ¡¿Te duele tanto?! ¡¿Entonces por qué viniste aquí?!", "Kyousuke"),
    54: ("No hay remedio, ¿sabes? Después de todo, mi linda hermanita me pidió «¡Hazlo pase lo que pase!»", "Akagi"),
    55: ("¡¿Escucharás lo que tu hermana diga pase lo que pase?!", "Kyousuke"),
    56: ("Bueno, si llega tan lejos como a «pase lo que pase», sí.", "Akagi"),
    57: ("Cierto, eres refrescantemente asqueroso.", "Kyousuke"),
    58: ("¡¿Quééééééééééééé?!!", "Akagi"),
    59: ("Dices eso cuando ni siquiera conoces a mi hermanita! ¡No sería una exageración decir que mi hermanita es el último ángel que descendió a este", "Akagi"),
    60: ("mundo!", "Akagi"),
    61: ("Si fuera un ángel real, no haría que su hermano mayor le comprara bienes BL.", "Kyousuke"),
    62: ("......", "Akagi"),
    63: ("Oye, Kousaka, ¿sabes?", "Akagi"),
    64: ("Los ángeles reales no tienen alas.", "Akagi"),
    68: ("Oye, te lo ruego, Kousaka. Piensa en ello como ponerme en deuda contigo, ¡y acompáñame hasta el final!", "Akagi"),
    69: ("Lo entiendo, lo entiendo. Yo tampoco querría ser abandonado solo en un lugar así.", "Kyousuke"),
    73: ("¡Kousaka, cuidado!", "Akagi"),
    74: ("¡¿Eh?! ¡¿Uooh?!!", "Kyousuke"),
    75: ("¡Idiota! ¡Mira bien por dónde caminas!", "Akagi"),
    76: ("Hay un flujo violento de gente por aquí por el servicio de colas o algo así.", "Akagi"),
    77: ("M-Mi culpa. Estaba atrapado en mis pensamientos...", "Kyousuke"),
    78: ("...Dios. Ese es el tipo de chico que eres. No sirves sin mí a tu alrededor.", "Akagi"),
    82: ("Fui salvado gracias a ti. Gra--", "Kyousuke"),
    83: ("Oye, ¿eso es...", "Mujer A"),
    84: ("Sí. Es definitivamente eso, ¿verdad?", "Mujer B"),
    86: ("............", "Kyousuke"),
    87: ("¿Qué pasa? De repente te pusiste rígido.", "Akagi"),
    88: ("...Puedo sentir miradas dirigidas hacia nosotros.", "Kyousuke"),
    89: ("¿No estás siendo demasiado cohibido?", "Akagi"),
    94: ("¡Kyaaaaaaaaaaaaaaah!!", "Ambos"),
    95: ("¡Uoh, ¿qué fue eso?!", "Akagi"),
    98: ("Akagi, vámonos por un rato. Tengo un mal presentimiento.", "Kyousuke"),
    99: ("S-Sí...", "Akagi"),
    103: ("¡Vamos, Kousaka!", "Akagi"),
    107: ("¡Kuh! ¡P-Perpón! ¡P-Paso por aquí!", "Kyousuke"),
    108: ("¡Kousaka, no te aplastes!", "Akagi"),
    109: ("Sí... ¡Waah!", "Kyousuke"),
    110: ("¡¡Kousaka!!", "Akagi"),
    113: ("¡Kousaka! ¡Kousaka! ¡Kousaka...!!!!!", "Akagi"),
    122: ("¡Kousaka, agárrate!", "Akagi"),
    125: ("Haa... haa... haa... ¡M-Me salvaste...!", "Kyousuke"),
    126: ("¿Qué estabas haciendo, Kousaka?", "Akagi"),
    127: ("Perdón... Akagi.", "Kyousuke"),
    131: ("Akagi, esperaré aquí, así que tú sigue adelante--", "Kyousuke"),
    132: ("¡Muy bien, vamos a retomar el desafío!", "Akagi"),
    133: ("No, ya estoy...", "Kyousuke"),
    134: ("¿Qué estás diciendo? ¡Vamos!", "Akagi"),
    137: ("¡Oh, vaya, qué gran captura!", "Akagi"),
    138: ("Gracias a ti, Kousaka, pudimos ir a todos los círculos marcados. ¡Con esto, mi hermanita debería revisar su opinión sobre mí!", "Akagi"),
    139: ("¡Gracias, Kousaka!", "Akagi"),
    140: (".........", "Kyousuke"),
    141: ("¿Huh? ¿Kousaka? ¿Qué te pasa? ¿Has perdido peso?", "Akagi"),
    145: ("En realidad, ¿por qué no recibiste daño? ¿Tienes realmente un interés en 'eso'?", "Kyousuke"),
    146: ("Los delirios de los que las fujoshi hablaban tan explosivamente... ¡¿No me dirás que no los escuchaste, ¿verdad?!", "Kyousuke"),
    147: ("Bueno, ¿sabes? Es como... ¿que estoy un poco acostumbrado?", "Akagi"),
    148: ("Acostumbrado, dices... ¿te has acostumbrado a eso?", "Kyousuke"),
    149: ("Bueno, sí...", "Akagi"),
    150: ("Después de todo, tengo una hermanita que lo hace cien veces peor que eso en casa.", "Akagi"),
    153: ("Así es como es. Aunque me siento asqueado por haber sudado tanto.", "Akagi"),
    154: ("Sí, yo también.", "Kyousuke"),
    157: ("Entonces, tengo una propuesta.", "Akagi"),
    158: ("¿Ah? ¿Qué es?", "Kyousuke"),
    159: ("¿Qué tal si vamos a un baño público ahora?", "Akagi"),
    160: ("Haaaaaaaaaaaah...", "Kyousuke"),
    161: ("¡Kuuuuuuh! ¡El agua caliente se está hundiendo en mi cuerpo cansado...!", "Kyousuke"),
    167: ("Ah... ¡Hurra por los japoneses...!", "Kyousuke"),
    168: ("Buh. Suenas como un anciano.", "Akagi"),
    169: ("¿Aah?", "Kyousuke"),
    170: ("¿De quién crees que es la culpa de que esté así de cansado?", "Kyousuke"),
    171: ("Sí, sí. Es mi culpa.", "Akagi"),
    172: ("Aquí, te daré un masaje como compensación.", "Akagi"),
    173: ("¡Nuah?! ¿Q-Qué estás haciendo de repente?", "Kyousuke"),
    174: ("¡Vamos, vamos! En realidad soy bueno en este tipo de cosas.", "Akagi"),
    178: ("Aun así.", "Akagi"),
    179: ("Hmm, ¿qué?", "Kyousuke"),
    180: ("Habría sido bueno si 【exploramos la posada】 en la que nos hospedamos durante el viaje escolar. Ese es mi único arrepentimiento.", "Akagi"),
    181: ("¿Qué es eso?", "Kyousuke"),
    182: ("¿Pero no es que ese tipo de cosas te hacen latir el corazón?", "Akagi"),
    183: ("Habría sido bueno si hiciéramos recuerdos de por vida como espiar el baño de las chicas o los dormitorios de las chicas. ¿Verdad?", "Akagi"),
    184: ("Sí, sí, tú haz eso.", "Kyousuke"),
    185: ("Bueno, poder socializar contigo desnudo así no está tan mal tampoco... ¡Ahí vamos!", "Akagi"),
    186: ("¡Ooooooooooooooh...!", "Kyousuke"),
    187: ("Fuu... ¿qué tal eso?", "Akagi"),
    188: ("Ah, ¡es el paraíso! Gracias.", "Kyousuke"),
    189: ("Ah... Puede que me esté mareando.", "Akagi"),
    190: ("Perdón. Me salgo primero.", "Akagi"),
    191: ("Sí... Me quedaré remojando aquí un poco más.", "Kyousuke"),
    192: ("Asegúrate de no excederte, anciano.", "Akagi"),
    193: ("Hah, lo mismo digo.", "Kyousuke"),
    194: ("Oomph... Ah...", "Akagi"),
    197: ("¡Akagi, Akagi?! ¿Estás bien, Akagi......!!", "Kyousuke"),
    198: ("Perdón, Kousaka... Me estoy sintiendo realmente mareado...", "Akagi"),
    199: ("Solo espera, te llevaré a un lugar fresco de inmediato...", "Kyousuke"),
    200: ("No... está bien.", "Akagi"),
    201: ("¡¿Huh?! ¡¿Qué estás diciendo?!", "Kyousuke"),
    202: ("Tú... tienes que salir de aquí rápido... si no, terminarás como yo...", "Akagi"),
    203: ("¡Idiota! ¡Como si pudiera dejarte atrás!", "Kyousuke"),
    204: ("...Kousaka.", "Akagi"),
    205: ("Vamos, apóyate en mi hombro.", "Kyousuke"),
    208: ("...Perdón.", "Akagi"),
    209: ("Si tienes energía para hablar, entonces estás bien.", "Kyousuke"),
    210: ("...Jaja.", "Akagi"),
    216: ("*glub, glub, glub, glub, glub*", "Kyousuke"),
    222: ("...Estoy vivo... Estoy vivo...!", "Kyousuke"),
    223: ("Hah, hah... qué alivio, Kousaka.", "Akagi"),
    227: ("......", "Kyousuke"),
    230: ("Oye, Kousaka...", "Akagi"),
    231: ("Me niego.", "Kyousuke"),
    232: ("¡¿Por qué?! ¡Todavía no he dicho nada!", "Akagi"),
    233: ("Basándome en el patrón hasta ahora, puedo decir aproximadamente que no es nada bueno.", "Kyousuke"),
    234: ("No digas eso. Solo quiero agradecerte por todas las molestias que pasaste conmigo hoy.", "Akagi"),
    235: ("......¿Qué es eso?", "Kyousuke"),
    238: ("Gracias... por hoy.", "Akagi"),
    239: ("Sí, sí. Me debes una grande por esto.", "Kyousuke"),
    240: ("No digas eso. Estoy agradecido. En serio.", "Akagi"),
    241: ("...Eso es asqueroso.", "Kyousuke"),
    242: ("Si no hubieras venido, me habría ahogado en ese mar humano en el Comiket y luego en el baño también.", "Akagi"),
    243: ("Solo sigues activando banderas de ahogamiento.", "Kyousuke"),
    244: ("Jaja. Eso es cierto. Pero...", "Akagi"),
    245: ("¿Hmm?", "Kyousuke"),
    246: ("Es gracias a ti que pude regresar con vida de ese abismo de muerte.", "Akagi"),
    247: ("...Kousaka, gracias.", "Akagi"),
    248: ("S-Sí... espera, ¿no era por tu hermanita? Pasamos bastantes desgracias por eso...", "Kyousuke"),
    249: ("¿Qué estás diciendo? No pasamos tantas desgracias.", "Akagi"),
    250: ("Sí, sí. Aquí hay un siscon extremo.", "Kyousuke"),
    251: ("Tú también tienes una hermanita, ¿no? ¿No entiendes mis sentimientos?", "Akagi"),
    252: ("¡No lo entiendo en absoluto!", "Kyousuke"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
entry = current.get("000scriptLAKA_0000.obj", {})
entry.update(build(n, s))
current["000scriptLAKA_0000.obj"] = entry
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptLAKA_0000.obj (part 1)")