import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a45_n = {
    0: "El Viaje Escolar La Próxima Semana",
    2: "Esto está mal... ¿Fui un poco demasiado brusco?",
    3: "Probablemente sería mejor que dijera algo aquí.",
    21: "Ahora que lo pienso...",
    22: "Por el incidente del torneo de Siscaly, lo olvidé por completo. De hecho voy a Kioto de viaje escolar...",
    24: "¿Esta chica podría de verdad leer mi mente?",
    29: "Ciertamente es una elección de chicas...",
    33: "¿Entonces no puedo tocar ese tema? Manami también es una chica después de todo.",
    41: "He olvidado claramente este viaje escolar, no puedo responder bien a eso.",
    42: "Bueno, si tuviera que dar una respuesta...",
    47: "¿Lo cual significa que ella también recorrerá ese gran camino y buscará a su destino?",
    48: "Destino... lo cual significa esperar conocer a un buen tipo, ¿supongo?",
    49: "¿Lo cual significa...? Un tipo que no sea yo...",
    50: "Gnn...",
    58: "Apunto a la misma universidad que ella.",
    59: "Hay dos razones para eso.",
    60: "Primero. Porque me siento tranquilo cuando estoy con Manami, claro y simple.",
    61: "La segunda es que si estoy con la señorita Chica Común Manami, podré caminar por el camino de la vida común, y ese es mi deseo más preciado.",
    62: "Cuando hablo de lo común, siento que he estado en el total opuesto de tener una vida común últimamente. En serio.",
    66: "Gracias a eso, también tengo ganas del viaje escolar de la próxima semana.",
    87: "Una vida escolar común y ordinaria.",
    88: "Las cosas que persigo están ahí dentro.",
    89: "No voy al extranjero después de todo. Es solo un viaje escolar muy llano y común. Manami y yo tenemos ganas de eso.",
    90: "¿Preguntas «por qué»?",
    91: "Porque si fuera al viaje escolar, podría liberarme de la temida orientación de vida.",
    92: "Solo disfrutar de la vida escolar de vez en cuando, no está tan mal.",
}
a45_s = {
    1: ("Uuu... Kyou-chan a veces es malo.", "Manami"),
    4: ("Oye, Manami...", "Kyousuke"),
    5: ("Pero no me disgusta un Kyou-chan malo.", "Manami"),
    6: ("No importa lo malo que sea, Kyou-chan es Kyou-chan.", "Manami"),
    7: ("No digas cosas tan vergonzosas...", "Kyousuke"),
    8: ("Ehehe～～", "Manami"),
    9: ("Perdón, perdón. Como eres tú, pensé en molestarte un poco.", "Kyousuke"),
    10: ("¿Si soy yo?", "Manami"),
    11: ("¡Sí! Solo contigo.", "Kyousuke"),
    12: ("Dios... Kyou-chan...", "Manami"),
    13: ("Pero está bien. No importa cómo te comportes, Kyou-chan siempre será Kyou-chan.", "Manami"),
    14: ("Pff, ¿qué es eso?", "Kyousuke"),
    15: ("Por cierto, Kyou-chan.", "Manami"),
    16: ("¿Hm?", "Kyousuke"),
    17: ("Tengo muchas ganas del «viaje escolar» de la próxima semana.", "Manami"),
    18: ("¿Viaje... escolar?", "Kyousuke"),
    19: ("¿Oh? Kyou-chan, ¿será que...", "Manami"),
    20: ("¿Olvidaste por completo el viaje escolar?", "Manami"),
    23: ("Aahh... Lo olvidaste...", "Manami"),
    25: ("Justo me acordé de eso.", "Kyousuke"),
    26: ("¡Será divertido!", "Manami"),
    27: ("Sí, tengo ganas.", "Kyousuke"),
    28: ("Quiero ir a la «Cascada de Kiyomizu-dera» cuando lleguemos a Kioto.", "Manami"),
    30: ("¿Tienes a alguien con quien quieras casarte?", "Kyousuke"),
    31: ("¡¿K-Kyou-chan?! ¡¿Qué estás diciendo?!", "Manami"),
    32: ("N-Nada... Está bien si no quieres hablar de eso.", "Kyousuke"),
    34: ("T-También está el «santuario Kitano Tenman-gu»! ¡Con el dios del saber!", "Manami"),
    35: ("Ah, eso también me interesa.", "Kyousuke"),
    36: ("Si es el dios del saber, puedo rezar por una mejor nota.", "Kyousuke"),
    37: ("Kyou-chan es candidato a examen después de todo.", "Manami"),
    38: ("«Después de todo» es innecesario.", "Kyousuke"),
    39: ("Kyou-chan, ¿hay algún lugar que te interese?", "Manami"),
    40: ("Hmm...", "Kyousuke"),
    43: ("¿Cascada del matrimonio? ¿Qué es eso?", "Kyousuke"),
    44: ("Es una cascada llamada Otowa, ¡se dice que conocerás a tu destinado solo con beber su agua!", "Manami"),
    45: ("No me imagino a alguien haciendo eso solo para encontrar a su destino.", "Kyousuke"),
    46: ("Las chicas comunes ciertamente lo harán.", "Manami"),
    51: ("Kitano Tenman-gu... ¿Qué es eso?", "Kyousuke"),
    52: ("Es el templo de Sugawara no Michizane. Está en Kioto, distrito de Kamigyou, y el mercado de pulgas de Tenjin se realiza cada 25 del mes.", "Manami"),
    53: ("Pero no estaremos ahí en el momento correcto, así que no podremos ver «Tenjin».", "Manami"),
    54: ("¿Memorizaste todo?", "Kyousuke"),
    55: ("Es porque tengo ganas. He leído la guía tantas veces.", "Manami"),
    56: ("Ah, sí. Como Michizane es el dios de la sabiduría, visitemos el santuario juntos.", "Manami"),
    57: ("Sí.", "Kyousuke"),
    63: ("Como era de esperar de ti, Manami, estás perfectamente preparada para el viaje escolar.", "Kyousuke"),
    64: ("Fufufu... Prepararse de antemano también es parte de la diversión de un viaje.", "Manami"),
    65: ("Hah... Muy tu estilo...", "Kyousuke"),
    67: ("¡¿Ehhhh?! ¿Nada?", "Manami"),
    68: ("Bueno, hasta ahora olvidé por completo este viaje escolar.", "Kyousuke"),
    69: ("No llegará tan de repente...", "Kyousuke"),
    70: ("Aunque tenía tantas ganas, eres cruel...", "Manami"),
    71: ("Sí, sí. Perdón.", "Kyousuke"),
    72: ("Dios...", "Manami"),
    73: ("Ah, Kyou-chan. Hay algo que quiero preguntarte...", "Manami"),
    74: ("No me preguntes nada sobre Kioto.", "Kyousuke"),
    75: ("No es sobre eso. Bueno... ¿Los chicos se duermen de inmediato al apagar las luces?", "Manami"),
    76: ("Usualmente es el caso. Además, ¿hay algo más que hacer?", "Kyousuke"),
    77: ("Las chicas probablemente... hablen de chicos o algo así.", "Manami"),
    78: ("Hmm, ¿no está bien eso?", "Kyousuke"),
    79: ("¡D-Discutirán sobre los chicos que les gustan! ¿No te interesa?", "Manami"),
    80: ("No.", "Kyousuke"),
    81: ("¿E-Entonces los chicos... no hablan de eso?", "Manami"),
    82: ("No lo hacen, supongo. En mi caso, me voy a la cama de inmediato.", "Kyousuke"),
    83: ("Y-Ya veo...", "Manami"),
    84: ("No somos niños de primaria; no hay nada por lo que hacer alboroto, ¿cierto?", "Kyousuke"),
    85: ("Dios, Kyou-chan suena como un anciano.", "Manami"),
    86: ("No quiero oír eso de ti.", "Kyousuke"),
}

a47_n = {
    0: "La Angustia Detrás De La Pared",
    1: "Esa noche---",
    2: "Mientras todos dormían, entrada la noche...",
    5: "La voz es demasiado fuerte. De ninguna manera puedo dormirme...",
    7: "Claramente excedió los límites de hablar consigo misma... Grrrr...",
    9: "Ah... Probablemente está practicando «Siscaly» en línea con Kuroneko...",
    12: "¡Incluso peleando en la red...!",
    14: "Tengo muy mal presentimiento... ¿Debería fingir estar dormido?",
    19: "...¡¿Qué iba a hacerle a su hermano dormido?!",
    25: "Esperaba que esto pasara...",
    26: "El monitor en la habitación de Kirino muestra Siscaly.",
    27: "La victoria decisiva de las dos -- el personaje que usa Kuroneko.",
    33: "Así que Kuroneko la aplastó y no pudo soportarlo, así que está desahogando su enojo tratando de sacar a Kuroneko del torneo...",
    40: "Parece que las palabras de Kuroneko la hirieron profundamente, sus ojos se están llenando de lágrimas...",
    41: "¿Qué le hizo a Kirino? Definitivamente está yendo demasiado lejos...",
    44: "Así que esto es lo que le dices a un «hermano cariñoso que anima a su hermana»...",
    45: "No, está bien. En realidad no me importa.",
    48: "No importa lo mala que sea nuestra relación, un hermano mayor sigue siendo un hermano mayor.",
    49: "Al menos, sé lo que piensa mi hermana con solo mirar su cara.",
    57: "Kirino no es el tipo de hermana que diría «quiero unirme al torneo con mis amigos». Lo sé perfectamente.",
    58: "No puede aceptar este tipo de situación, pero tampoco puede resolver el problema ella sola.",
    59: "Hacer algo para resolver esto, ¿es el trabajo de un hermano mayor?",
}
a47_s = {
    3: ("Kuh... ¡Encadenándome con un mixup 50/50...! ¡¿Cómo puede hacer eso!", "Kirino"),
    4: ("Nnnh... Ruidosa...", "Kyousuke"),
    6: ("¡Tú! ¡Tú! ¡Túuu!", "Kirino"),
    8: ("¡Esa chica maliciosa!", "Kirino"),
    10: ("¡¿Hah?!", "Kirino"),
    11: ("¡¿Quién te crees que eres?!", "Kirino"),
    13: ("¡¿Quién se cree que es?! ¡In-fu-riante!", "Kirino"),
    15: ("¡Oye!", "Kirino"),
    16: ("......ZZZZZZ", "Kyousuke"),
    17: ("...Tch, está dormido. En ese caso...", "Kirino"),
    18: ("Entiendo... Ya me levanto, ya me levanto...", "Kyousuke"),
    20: ("¡Es tan infuriante!", "Kirino"),
    21: ("...¿Q-Qué es?", "Kyousuke"),
    22: ("Quiero echar a la de negro de nuestro grupo.", "Kirino"),
    23: ("¡¿Qué?!", "Kyousuke"),
    24: ("Ven a mi habitación un momento.", "Kirino"),
    28: ("No puedo negar que esta chica tiene un tiempo de reacción excepcional y la habilidad de leer con precisión a su oponente.", "Kirino"),
    29: ("¡Con esas habilidades, es obvio que cualquiera perdería contra ella!", "Kirino"),
    30: ("Y además... tú...", "Kirino"),
    31: ("De todos modos, ¡me saca de quicio!", "Kirino"),
    32: ("Hah...", "Kyousuke"),
    34: ("No seas tan impulsiva. Si Kuroneko es tan hábil, esa es aún más razón para no echarla.", "Kyousuke"),
    35: ("Pero, en verdad dijo de mí: «¿Ceder tantos frames, es que tu cerebro está tapado por toda esa moda?»", "Kirino"),
    36: ("¡Y además...!", "Kirino"),
    37: ("¿Qué?", "Kyousuke"),
    38: ("¡N-Nada...!", "Kirino"),
    39: ("Hmm... No sé qué está pasando, pero estoy seguro de que es un asunto de otro nivel completamente.", "Kyousuke"),
    42: ("¡Tranquila, Kirino! ¡Eres fuerte! ¡Debes tener algo de confianza!", "Kyousuke"),
    43: ("...Cállate.", "Kirino"),
    46: ("De todos modos, voy a echar a la de negro...", "Kirino"),
    47: ("Sin embargo, si dices eso, terminarás arrepintiéndote, ¿cierto?", "Kyousuke"),
    50: ("Bueno, yo...", "Kirino"),
    51: ("...Conozco su habilidad en los juegos. Me molesta, pero si no participa en el torneo, será problemático y además...", "Kirino"),
    52: ("¿Además...? ¿Qué?", "Kyousuke"),
    53: ("...Se lo dije...", "Kirino"),
    54: ("¿Dijiste qué?", "Kyousuke"),
    55: ("Te echo del torneo...", "Kirino"),
    56: ("Ouch...", "Kyousuke"),
    60: ("De todos modos, debes hacer algo para 【aumentar nuestras posibilidades de victoria】...", "Kirino"),
    61: ("Ya que aceptamos el desafío, quiero ganar, sin importar lo que cueste.", "Kirino"),
    62: ("Entonces, solo con disculparse estaría bien.", "Kyousuke"),
    63: ("¿Yo? ¿No es ella la culpable?", "Kirino"),
    64: ("¿A quién le importa quién tiene razón... En una pelea, ambos lados tienen sus responsabilidades; nadie tiene toda la razón.", "Kyousuke"),
    65: ("Tú... Haz algo.", "Kirino"),
}

a48_n = {
    0: "Sesión de Orientación de Vida",
    4: "¡Guh...! ¿¡Entonces el único propósito de mi existencia es cumplir las órdenes de orientación de vida de mi hermana?!",
    7: "Mi hermana simplemente no puede ser honesta.",
    8: "Bueno, cubrir a su hermana es el deber de un hermano.",
    9: "Para ser honesto, es realmente problemático... Dios, qué fastidio.",
    17: "¡De acuerdo!",
    18: "¡Me apoderé hábilmente de la iniciativa de la conversación!",
    19: "Tengo que decir algo para hacer dudar a Kuroneko, aunque sea solo una palabra. ¡Si hay oportunidad, la tomaré!",
    21: "Dije eso con voz baja por si Kirino pegara su oído a la pared para escuchar nuestra conversación.",
    25: "¿No lo escuchó?",
    30: "¡¿Aún no es suficiente?!",
    42: "¿Por qué cambió de opinión tan de repente...?",
    43: "De todos modos, esta difícil misión ahora está completa.",
    46: "Bien, ahora está dudando...",
    47: "Estoy a una palabra de persuadirla.",
    48: "Si lo hago bien, esta misión de élite estará completa.",
    49: "Sin embargo, mi hermana me tiene hasta a mí trabajando tan duro para ella...",
    75: "En resumen, Kuroneko ideó una estrategia muy compleja para ganar el torneo que implica que me empareje con ella y se la contó a Kirino.",
    76: "Y con esa clase de charla coercitiva, provocó la ira de Kirino como siempre... Eso es probablemente.",
    79: "¿Actuando como si no supiera? Dios, no está siendo sincera.",
    85: "...¿Por qué cambió de opinión tan de repente?",
    94: "Silencio, Kuroneko reflexionó por un rato...",
    109: "De todos modos... puedo considerar esta misión completa... ¿supongo?",
}
a48_s = {
    1: ("Entiendo tus sentimientos, pero ya es tarde en la noche.", "Kyousuke"),
    2: ("Hablaremos de eso mañana, ¿está bien? Durmamos por ahora.", "Kyousuke"),
    3: ("Es tu deber hacer algo ahora mismo.", "Kirino"),
    5: ("¡Entiendo! Llamaré a Kuroneko, ¿eso sirve?", "Kyousuke"),
    6: ("Qué bien que lo entiendes...", "Kirino"),
    10: ("Okay, mi celular está en mi habitación, así que volveré para hacer la llamada.", "Kyousuke"),
    11: ("Bueno, ¿contestará Kuroneko...", "Kyousuke"),
    12: ("¿Qué?", "Kuroneko"),
    13: ("¿Eres Kuroneko? Así que oye...", "Kyousuke"),
    14: ("Hmph, si es para rogarme que me una al torneo, es inútil decir nada.", "Kuroneko"),
    15: ("¿Oh, en serio?", "Kyousuke"),
    16: ("¿Qué quieres decir con eso?", "Kuroneko"),
    20: ("¿Sabes que sus habilidades son realmente malas? Si una jugadora experta como tú no se une, no tiene sentido que participemos en este torneo!", "Kyousuke"),
    22: ("...Oh, vaya, no escuché bien eso, ¿podrías repetirlo una vez más?", "Kuroneko"),
    23: ("Co-mo di-je... Kirino es realmente mala--", "Kyousuke"),
    24: ("No eso, lo que dijiste después.", "Kuroneko"),
    26: ("Si una jugadora experta como tú no se une--", "Kyousuke"),
    27: ("No entiendo, ¿se me considera una experta comparada con...?", "Kuroneko"),
    28: ("Eso sería Kirino...", "Kyousuke"),
    29: ("Es un hecho que tu hermana juega mal. ¿Qué más?", "Kuroneko"),
    31: ("Y también... er... ¿todos? Correcto, eso es. Los meros humanos nunca podrían ganarte.", "Kyousuke"),
    32: ("...Hmph. Parece que pudiste sentir una parte de mis verdaderos poderes.", "Kuroneko"),
    33: ("De todos modos, no tengo nada más que decir sobre este asunto.", "Kuroneko"),
    34: ("¡Espera! Quiero verte parti--", "Kyousuke"),
    35: ("Colgó...", "Kyousuke"),
    36: ("¡¿Kuroneko?!", "Kyousuke"),
    37: ("«Quiero verte parti--» ¿y después?", "Kuroneko"),
    38: ("Bueno... Quiero decir, «quiero verte participar».", "Kyousuke"),
    39: ("Ya veo... No hay de otra entonces.", "Kuroneko"),
    40: ("¡Entonces!", "Kyousuke"),
    41: ("Ya que me lo pediste así... Concederé tu petición.", "Kuroneko"),
    44: ("Eso es correcto, incluso Kirino reconoce tus habilidades en el fondo.", "Kyousuke"),
    45: ("............", "Kuroneko"),
    50: ("Te necesitamos absolutamente para aumentar nuestras posibilidades de victoria.", "Kyousuke"),
    51: ("No tenemos oportunidad sin ti, ¿lo sabes, cierto?", "Kyousuke"),
    52: ("¿Posibilidades de victoria? ¿Qué dices medio dormido?", "Kuroneko"),
    53: ("¿Eh?", "Kyousuke"),
    54: ("La palabra «derrota» no existe en las batallas en las que participo. El concepto de suerte no significa nada para mí.", "Kuroneko"),
    55: ("...¿En otras palabras?", "Kyousuke"),
    56: ("Si Senpai y yo nos uniéramos, cuando llegue ese día, los cielos de Akihabara se oscurecerán con mi vórtice oscuro.", "Kuroneko"),
    57: ("¿Qué es eso...?", "Kyousuke"),
    58: ("El objetivo de este torneo es la victoria total, eso es todo.", "Kuroneko"),
    59: ("Ah, eso es correcto.", "Kyousuke"),
    60: ("Para ganar, solo me conviene apoyarte a ti, que no tienes mucha experiencia con el juego.", "Kuroneko"),
    61: ("Además, si esa presumida de la moda y Saori estuvieran en un grupo, su fuerza sería más estable, ¿no crees?", "Kuroneko"),
    62: ("Hmph... Cuando le expliqué eso, se enfureció y terminó la conversación.", "Kuroneko"),
    63: ("Ah, ya veo... ¡Espera! ¡¿Me emparejaré contigo?!", "Kyousuke"),
    64: ("¡¿En serio?! ¡¿No terminaré solo arrastrándote hacia abajo?!", "Kyousuke"),
    65: ("Sin embargo, esta es la mejor combinación.", "Kuroneko"),
    66: ("¡Pero...!", "Kyousuke"),
    67: ("Y la palabra derrota no existe en mi diccionario, creo que ya lo dije antes.", "Kuroneko"),
    68: ("¡Siempre hay un «si»!", "Kyousuke"),
    69: ("...¿Q-Qué pasa?", "Kyousuke"),
    70: ("¿No quieres emparejarte conmigo?", "Kuroneko"),
    71: ("No es el caso...", "Kyousuke"),
    72: ("¿Es así? Entonces todo está bien.", "Kuroneko"),
    73: ("De todos modos, entiendes mi plan, ¿cierto?", "Kuroneko"),
    74: ("Ah, ah... Entiendo lo esencial.", "Kyousuke"),
    77: ("También estás dando lo mejor de ti por Kirino.", "Kyousuke"),
    78: ("...¿De qué estás hablando?", "Kuroneko"),
    80: ("Para el torneo... Cuento contigo, Senpai.", "Kuroneko"),
    81: ("¿Eh? ¿Esto significa...? ¿Kuroneko, estás dispuesta a unirte al torneo?", "Kyousuke"),
    82: ("...Hmph.", "Kuroneko"),
    83: ("¡Oye! ¡No me cuelgues! ¡Oye, oyeey!", "Kyousuke"),
    84: ("...¿Por qué cambió de opinión tan de repente?", "Kyousuke"),
    86: ("Hmph. ¿Pensaste que le prestaría mi mano a un mero ser humano?", "Kuroneko"),
    87: ("No digas eso. No eres del tipo que huye sin pelear, ¿cierto?", "Kyousuke"),
    88: ("¿Yo... huyendo?", "Kuroneko"),
    89: ("Por supuesto, eso no es lo que pienso, pero ¿y Kirino?", "Kyousuke"),
    90: ("............", "Kuroneko"),
    91: ("¡Difundirá por la comunidad que desertaste frente al enemigo! Lo sé de sobra. ¡Ella es así!", "Kyousuke"),
    92: ("En efecto... Con esa chica, es muy probable.", "Kuroneko"),
    93: ("¿Negarás todo caso por caso?", "Kyousuke"),
    95: ("No hay de otra... Te costará caro.", "Kuroneko"),
    96: ("¡Entonces!", "Kyousuke"),
    97: ("Hmph. Entiendo. Concederé tu petición.", "Kuroneko"),
    98: ("¡Ya veo! ¡Gracias!", "Kyousuke"),
    99: ("Haciendo eso por tu hermana, te estás volviendo bueno en esto.", "Kuroneko"),
    100: ("Bueno, parece que se volvió un hábito.", "Kyousuke"),
    101: ("Pero esta vez, cosecharás lo que siembras.", "Kuroneko"),
    102: ("¿Por qué? ¿Hice algo?", "Kyousuke"),
    103: ("¿Tu hermana te dijo por qué estábamos peleando?", "Kuroneko"),
    104: ("¿Kirino estaba enojada porque la redujiste a cenizas en el juego?", "Kyousuke"),
    105: ("No solo eso.", "Kuroneko"),
    106: ("¿Eh? Entonces, ¿por qué estaban peleando?", "Kyousuke"),
    107: ("Quién sabe. Piénsalo tú mismo.", "Kuroneko"),
    108: ("¡Oye! ...¿Qué fue eso al final?", "Kyousuke"),
}

a51_n = {
    0: "El Día del Torneo de Juegos",
    1: "De algún modo llegamos al día del torneo...",
    2: "Como siempre, Kirino, Kuroneko, Saori y yo salimos hacia Akihabara como grupo.",
    6: "Todos están de mal humor, ¿qué es esta atmósfera sombría?",
    7: "¿No quedó eso resuelto hace unos días?",
    8: "¿No es hora de que se les pase el mal genio?",
    18: "Estas dos... ¿No conocen otras formas de comunicarse?",
    21: "Justo frente a mí señalándome--",
    36: "Phew... Parece que la situación se ha calmado.",
    40: "Incluso si fuera por el premio raro, la gente normalmente no llegaría tan lejos, ¿cierto?",
    41: "Probablemente no lo entendería aunque pasara toda una vida pensándolo.",
    51: "En un aparte, los equipos son «Kirino y Saori» y «Kuroneko y yo».",
    52: "Kirino y Kuroneko ciertamente pelearían si estuvieran en el mismo grupo, así que este arreglo parece obvio.",
    54: "Mirando hacia donde señaló Saori, una persona de apariencia oficial caminó hacia la multitud.",
    60: "Creo que «Siscaly» tiene suficientes entusiastas...",
    65: "Aunque, bueno... no creo que sea una mala idea...",
    66: "De algún modo, siento que he sido envuelto por la atmósfera del lugar y mi emoción está subiendo gradualmente.",
    73: "E-Estas chicas realmente están metidas en esto...",
    74: "¡De acuerdo, yo también tengo que dar lo mejor de mí!",
    75: "¡No puedo dejar que el tiempo pasado en el entrenamiento especial se desperdicie!",
    80: "Y así comenzó la competencia--",
    81: "El grupo de Kirino y Saori avanzó sin problemas. En cuanto a nuestra pareja, aunque tuve problemas a veces, gracias a Kuroneko, pudimos avanzar también.",
    82: "Sin embargo--",
    83: "Incluso considerando su tiempo de reacción trascendental, parece imposible pelear con una compañera tan incompetente.",
    88: "Y así, avanzamos a las semifinales.",
    89: "Y entonces, aquí--",
    92: "Esto es-- una situación inesperada...",
    93: "¡Nuestros oponentes para las semifinales terminaron siendo Kirino y Saori!",
    94: "¿Qué deberíamos hacer? ¿No tenemos más opción que pelear entre nosotros...",
    97: "Dejándome de lado, dejar que ganen podría hacer más fácil ganar las finales...",
    98: "Pero si nos ponemos fáciles en la batalla...",
    99: "¿La orgullosa Kuroneko permitirá ese plan?",
    100: "¿O será mejor que tengamos un combate serio...?",
}
a51_s = {
    3: ("Por cierto, ustedes...", "Kyousuke"),
    4: ("............", "Kirino"),
    5: ("............", "Kuroneko"),
    9: ("Oye, tú...", "Kuroneko"),
    10: ("¿Eh? ¿Q-Qué pasa?", "Kirino"),
    11: ("Estoy honrando este torneo con mi presencia a regañadientes. ¿No tienes nada que decirme?", "Kuroneko"),
    12: ("¡¿H-Huh?!", "Kirino"),
    13: ("Exijo tanto gratitud como una disculpa.", "Kuroneko"),
    14: ("¿Por qué debo hacer algo así?", "Kirino"),
    15: ("¿No es obvio? ¿Por qué eres tan terca?", "Kuroneko"),
    16: ("¿Será que no pudiste soportarlo porque te robé a tu hermano?", "Kuroneko"),
    17: ("¡¿Q-Qué estás diciendo?! ¡Imposible!", "Kirino"),
    19: ("Jajaja, ¡las dos están realmente emocionadas! ¡Nosotros tampoco perderemos, Kyousuke-shi!", "Saori"),
    20: ("No... Además, ¿cómo es esto emocionado?", "Kyousuke"),
    22: ("¿No podrías decidir las cosas por tu cuenta?", "Kirino"),
    23: ("En serio, esta chica cargada de chuunibyou es un verdadero dolor.", "Kirino"),
    24: ("Jeje. Los que me han dicho eso ya no existen en este mundo.", "Kuroneko"),
    25: ("Dime, ¿no es hora de que te des cuenta de lo miserable que es tu existencia?", "Kirino"),
    26: ("¿Y quién es la que siempre pierde en Siscaly contra esa existencia miserable?", "Kuroneko"),
    27: ("Hng... ¡Si no fuera por mí, tampoco podrías unirte a este torneo!", "Kirino"),
    28: ("Además, ¿siquiera tienes amigos con quienes formar equipo?", "Kirino"),
    29: ("E-Eso es...", "Kuroneko"),
    30: ("¡Aquí estamos!", "Saori"),
    31: ("¡¿No estamos los cuatro reunidos aquí como compañeros con un propósito común?!", "Saori"),
    32: ("Pfft, cierto...", "Kyousuke"),
    33: ("¿No es ahora el momento de unir nuestras fuerzas? ¡El objetivo es capturar el premio raro!", "Saori"),
    34: ("Hmph...", "Kirino"),
    35: ("...Supongo que no hay de otra.", "Kuroneko"),
    37: ("De todos modos, parece que hay mucha gente.", "Kirino"),
    38: ("Bueno, mientras haya premios, los coleccionistas definitivamente vendrán.", "Kuroneko"),
    39: ("Hoh... Mucha gente tiene tiempo libre.", "Kyousuke"),
    42: ("No solo vendrán coleccionistas, sino que me temo que expertos como Kuroneko-shi también se reunirán aquí.", "Saori"),
    43: ("Como recordatorio, Siscaly es una batalla por equipos de 2 contra 2, ¡por eso el trabajo en equipo es tan importante!", "Saori"),
    44: ("...Je, esa es solo la perspectiva de un mero humano.", "Kuroneko"),
    45: ("¡Kyousuke-shi también debería reunir algo de entusiasmo!", "Saori"),
    46: ("...S-Sí.", "Kyousuke"),
    47: ("¡Debes ganar!", "Kirino"),
    48: ("¿Debo...? Bueno, intentaré dar lo mejor...", "Kyousuke"),
    49: ("Asegúrate de no arrastrarme hacia abajo. Ten cuidado.", "Kuroneko"),
    50: ("...Sí～", "Kyousuke"),
    53: ("Oh, parece que está por comenzar.", "Saori"),
    55: ("Parece que el organizador no sirve. ¿Un aficionado?", "Kirino"),
    56: ("En torneos de esta escala, los organizadores normalmente son así.", "Kuroneko"),
    57: ("Los organizadores profesionales tienden a manejar torneos de juegos más grandes.", "Kuroneko"),
    58: ("¿Entonces hay torneos de juegos más grandes?", "Kyousuke"),
    59: ("Por supuesto. Para juegos de pelea famosos como «Siscaly», incluso hay torneos impulsados por entusiastas.", "Kuroneko"),
    61: ("También hay muchos torneos de juegos de cartas.", "Saori"),
    62: ("¿Entonces existen esas cosas? Increíble...", "Kyousuke"),
    63: ("¿Oh? ¿Kyousuke-shi quiere unirse a esta comunidad de ahora en adelante?", "Saori"),
    64: ("...Je, un poco.", "Kyousuke"),
    67: ("Esta competencia es un torneo de eliminación simple.", "Saori"),
    68: ("Lo cual significa, es el fin si perdemos aquí.", "Kirino"),
    69: ("...Hmph...", "Kuroneko"),
    70: ("Con eso, todos, ¡hagamos nuestro mejor esfuerzo!", "Saori"),
    71: ("Definitivamente ganaremos.", "Kirino"),
    72: ("Bueno, ya que estoy aquí, la palabra derrota es irrelevante.", "Kuroneko"),
    76: ("¡Debemos conseguir ese premio raro sin importar qué--!", "Kirino"),
    77: ("¡Oh---!", "Kirino"),
    78: ("¡Oh---!", "Saori"),
    79: ("---Je.", "Kuroneko"),
    84: ("Perdón, Kuroneko... Siempre te estoy arrastrando hacia abajo.", "Kyousuke"),
    85: ("Ya que estás emparejado conmigo, significa que montamos el mismo Wyvern.", "Kuroneko"),
    86: ("¿No es «mismo barco»? Pero cuento contigo.", "Kyousuke"),
    87: ("...Sí, te protegeré, Senpai.", "Kuroneko"),
    90: ("¿Oh?", "Kyousuke"),
    91: ("¿Eh?", "Kirino"),
    95: ("¿Qué deberíamos hacer, Kuroneko?", "Kyousuke"),
    96: ("Incluso si me lo preguntas...", "Kuroneko"),
}

data = {
    "000scriptAKYO_0045A.obj": build(a45_n, a45_s),
    "000scriptAKYO_0047A.obj": build(a47_n, a47_s),
    "000scriptAKYO_0048A.obj": build(a48_n, a48_s),
    "000scriptAKYO_0051A.obj": build(a51_n, a51_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))