import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a134_n = {
    0: "El Kyoto de Mañana",
    1: "El día después del torneo de Siscaly.",
    2: "Aproveché la oportunidad para dar un paseo durante el atardecer para tomar un descanso de estudiar.",
    11: "Rayos... ¡Lo olvidé por completo!",
    12: "Había el torneo de Siscaly, así que olvidé lo pronto que era...",
    13: "¡S-Soy un idiota!",
    16: "Exactamente eso es... Todo sobre este viaje escolar había desaparecido por completo de mi mente, incluyendo la preparación.",
    30: "Me di la vuelta, y allí estaba--",
    33: "Aragaki Ayase. Amiga cercana de Kirino, así como su colega de modelaje.",
    34: "En otras palabras, su amiga «oficial».",
    35: "Aparte de mi hermana, Ayase es la persona más bonita que he conocido hasta ahora.",
    36: "Honestamente, en cuanto a apariencias, es totalmente mi tipo pero...",
    39: "¿Y qué hay con ese «otra vez»? ¡No ha habido ni una sola vez en la que haya planeado algo obsceno contra ella desde que nació!",
    42: "Eso es correcto. Por varias razones, Ayase cree firmemente que soy un pervertido.",
    43: "Debido a muchas razones complicadas que se entrelazan, resolver ese malentendido es imposible.",
    44: "Así que para mí, Ayase es una persona problemática en muchos aspectos.",
    48: "Así que por favor no presiones tu botón de alarma personal todavía.",
    63: "Guh... Esa Manami, no le dijiste nada raro a Ayase, ¿verdad?",
    67: "...Aunque me lo busqué yo mismo, no puedo superarlo...",
}
a134_s = {
    3: ("Ah, ¿hola?", "Kyousuke"),
    4: ("Kyou-chan, ¿estás libre ahora mismo?", "Manami"),
    5: ("Sí.", "Kyousuke"),
    6: ("...¿Entonces? ¿Qué pasa?", "Kyousuke"),
    7: ("Quiero decirte que saldré temprano mañana.", "Manami"),
    8: ("¿Eh? ¿Hay algo mañana?", "Kyousuke"),
    9: ("¿Por qué...? ¡Mañana es el viaje escolar!", "Manami"),
    10: ("¡AH!", "Kyousuke"),
    14: ("Kyou-chan, ¿estás bien?", "Manami"),
    15: ("No me vas a decir que «no has preparado nada», ¿verdad?", "Manami"),
    17: ("C-Cómo debería decir esto...", "Kyousuke"),
    18: ("¿Qué pasa? Tu voz está un poco temblorosa.", "Manami"),
    19: ("Oh... cómo decirlo, estoy en problemas.", "Kyousuke"),
    20: ("Ya sentí que algo no andaba bien cuando vi que dejaste tu manual del viaje escolar en la escuela...", "Manami"),
    21: ("¡Ehh! ¡¿En serio?!", "Kyousuke"),
    22: ("Por lo que se oye, Kyou-chan, ¿no revisaste el contenido?", "Manami"),
    23: ("¡No lo hice! ¡¿Había algo importante?!", "Kyousuke"),
    24: ("Hay una etiqueta en él que se usa para la actividad grupal de ese mismo día.", "Manami"),
    25: ("¡Esto está mal--! ¡¿Debería colarme en la escuela ahora mismo?!", "Kyousuke"),
    26: ("N-No es necesario que hagas eso. Tomé el manual de Kyou-chan conmigo como precaución.", "Manami"),
    27: ("¡Como se espera de Manami! ¡Esa es mi amiga de la infancia! ¡Voy a tu casa ahora mismo!!", "Kyousuke"),
    28: ("Oh, ¿no es ese Onii-san?", "???"),
    29: ("Esa voz... ¿podría ser...", "Kyousuke"),
    31: ("A-Ayase...", "Kyousuke"),
    32: ("Buenos días, Onii-san. ¿Por qué tienes tanta prisa?", "Ayase"),
    37: ("¿Podría ser... que estás tramando cosas obscenas contra Kirino otra vez...", "Ayase"),
    38: ("¿Es esa la única explicación que pudiste idear para mi carrera...?", "Kyousuke"),
    40: ("Viendo al pervertido Onii-san sin aliento corriendo así, cualquiera estaría de acuerdo.", "Ayase"),
    41: ("¡Ugh...!", "Kyousuke"),
    45: ("El destino ciertamente es irónico...", "Kyousuke"),
    46: ("¿Hmm? ¿Dijiste algo?", "Ayase"),
    47: ("No, nada.", "Kyousuke"),
    49: ("Dejando eso de lado, ¿no tenías prisa?", "Ayase"),
    50: ("Ah, ahora que lo mencionas...", "Kyousuke"),
    51: ("Sin embargo, es raro que inicies una conversación conmigo, así que más vale...", "Kyousuke"),
    52: ("Solo vi a Onii-san y te saludé.", "Ayase"),
    53: ("No había una razón particular, así que me retiraré ahora.", "Ayase"),
    54: ("Y allí se va...", "Kyousuke"),
    55: ("Dios mío, mi corazón se conmueve cada vez que hace esa cara angelical. Es de verdad una diablesa...", "Kyousuke"),
    56: ("Espera, no debería estar pensando en estas cosas ahora. ¡Necesito apresurarme a la casa de Manami!", "Kyousuke"),
    57: ("Oh, ¿Onii-san?", "Ayase"),
    58: ("¡Oye, Ayase! ¡Perdón, tengo prisa ahora mismo!", "Kyousuke"),
    59: ("Ah. ¿Podría ser que oíste algo sobre el viaje escolar de Onee-san?", "Ayase"),
    60: ("¿Eh? ¿Por qué sabría Ayase sobre esto?", "Kyousuke"),
    61: ("Escuché sobre el viaje escolar mientras hablaba por teléfono con Onee-san ayer.", "Ayase"),
    62: ("Onii-san no es lo suficientemente serio, así que Onee-san estaba preocupada.", "Ayase"),
    64: ("Ahh, solo escuché sobre el viaje escolar de Onee-san y nada más, así que no te preocupes.", "Ayase"),
    65: ("Además, mi evaluación de Onii-san ya está en el fondo, así que no bajará más.", "Ayase"),
    66: ("Ajaja...", "Kyousuke"),
    68: ("Vamos, vamos, no te quedes ahí parado haciendo pucheros. ¿Qué tal si te apuras?", "Ayase"),
    69: ("Onee-san te está esperando, ¿no?", "Ayase"),
    70: ("¡E-Eso es correcto!", "Kyousuke"),
    71: ("¡Nos vemos, Ayase!", "Kyousuke"),
    72: ("Sí, nos vemos la próxima vez.", "Ayase"),
}

a135_n = {
    0: "Tiene que ser mentira",
    2: "De hecho le devolví el saludo tranquilamente... ¡No debería estar haciendo eso ahora mismo!",
}
a135_s = {
    1: ("Ah, ¡Kyou-chan! ¡Por aquí!", "Manami"),
    3: ("Geh, jah... jah...", "Kyousuke"),
    4: ("Oh, Kyou-chan está muy sudado.", "Manami"),
    5: ("La mitad es sudor frío.", "Kyousuke"),
    6: ("¿Huh?", "Manami"),
    7: ("Ja, ja... Oye, es mentira, ¿verdad? Todavía hay tiempo antes del viaje escolar, ¿verdad?", "Kyousuke"),
}

a136_n = {
    0: "Tiene que ser mentira",
    2: "*tragar saliva*",
    13: "¡Estoy seriamente arruinado! ¡No he preparado nada!",
}
a136_s = {
    1: ("Sabes, esto no es una broma ni nada...", "Manami"),
    3: ("El viaje escolar es mañana.", "Manami"),
    4: ("¡Estás mintiendo! ¡Debes estar mintiendo, Manami!", "Kyousuke"),
    5: ("Ojalá lo fuera... pero esta es la verdad.", "Manami"),
    6: ("Mañana... Es mañana...", "Kyousuke"),
    7: ("¿No... posiblemente lo olvidaste, verdad? ¡Después de todo es un gran evento!", "Manami"),
    8: ("......", "Kyousuke"),
    9: ("Debes estar bromeando.... ¿De verdad lo olvidaste?", "Manami"),
    10: ("¡C-Cómo podría!", "Kyousuke"),
    11: ("¡Y-Yo no lo olvidaría, por supuesto!", "Kyousuke"),
    12: ("¡P-Por supuesto! Ah, me alivio.", "Manami"),
    14: ("...No puede ser. ¿Mañana empieza el viaje escolar?", "Kyousuke"),
    15: ("Ehh... ¿Podría ser que de verdad lo olvidaste?", "Manami"),
    16: ("Cómo decirlo... Exacto.", "Kyousuke"),
    17: ("¡¿Eh?! ¡Estaba de veeerdad emocionada por esto!", "Manami"),
    18: ("¡Manami, perdón! ¡Me voy a preparar para mañana!", "Kyousuke"),
    19: ("Mira este manual con cuidado; no te equivoques.", "Manami"),
    20: ("¡Okay!", "Kyousuke"),
    21: ("¡Es fácil olvidar tu copia del seguro o tu cargador del teléfono!", "Manami"),
    22: ("¡Sí!", "Kyousuke"),
    23: ("¡Ah, y los plátanos no están incluidos en los bocadillos!", "Manami"),
    24: ("¡Plátanos también! ¡Pero este no es el momento de preparar plátanos!", "Kyousuke"),
    25: ("Eso es cierto. Perdón, yo también estoy nerviosa...", "Manami"),
    26: ("......", "Kyousuke"),
    27: ("¿Me estás escuchando, Kyou-chan? No Hay Plátanos En Los--", "Manami"),
    28: ("¡Bocadillos! ¡Correcto! ¡Entonces iré a comprar unos plátan--", "Kyousuke"),
    29: ("Geh, ¡este no es el momento de hacer eso! ¡Cálmate!", "Kyousuke"),
    30: ("Sin embargo, es posible olvidar llevar cosas importantes al empacar apurado, así que ten cuidado.", "Manami"),
    31: ("Le pasa a todos.", "Manami"),
    32: ("Como olvidar llevar tu ropa interior durante el viaje de la secundaria...", "Manami"),
    33: ("Oh, así que fuiste sin ropa interior esa vez.", "Kyousuke"),
    34: ("Sí. ¡Eso fue difícil!", "Manami"),
    35: ("¡¿Y cómo terminó así?! ¡Mi hermano! ¡Fue mi hermano!", "Manami"),
    36: ("Qué, entonces fue Rock, qué tonto.", "Kyousuke"),
    37: ("¿Crees que eres mejor que él?", "Manami"),
    38: ("?", "Kyousuke"),
    39: ("Dios. De todos modos, llámame si no entiendes algo.", "Manami"),
    40: ("Estoy deseando ir contigo, Kyou-chan, así que haré mi mejor esfuerzo para ayudar.", "Manami"),
    41: ("¡Así que no olvides nada! Si terminas olvidando, yo--", "Manami"),
    42: ("¿me lo prestas?", "Kyousuke"),
    43: ("No lo haré.", "Manami"),
    44: ("Kyou-chan, ¿estás en tus cabales?", "Manami"),
    45: ("No estoy bien en absoluto. Estoy súper estresado.", "Kyousuke"),
    46: ("Dios, tómalo en serio.", "Manami"),
    47: ("De todos modos, cuando tengamos problemas, ayudémonos mutuamente.", "Manami"),
    48: ("¿Estás de verdad bien? ¿Necesitas mi ayuda?", "Manami"),
    49: ("¡Estoy bien! ¡No, en serio!", "Kyousuke"),
    50: ("De todos modos, si no entiendes algo, llámame.", "Manami"),
    51: ("Estoy deseando ir contigo, Kyou-chan, así que haré mi mejor esfuerzo para ayudar.", "Manami"),
    52: ("......", "Kyousuke"),
    53: ("¡Kyou-chan! ¡Está bien! ¡Vuelve a este mundo!", "Manami"),
    54: ("¿Hm? ¡Ah! ¡Perdón! Me quedé en blanco por un momento.", "Kyousuke"),
    55: ("Estoy realmente preocupada por ti.", "Manami"),
}

a137_n = {
    0: "La Rapsodia de la Víspera de la Partida",
    14: "¡Finalmente siento la urgencia de esta situación!",
    25: "¿Cuándo me perdí en primer lugar?",
    33: "Debe haber decidido que le trajera recuerdos en el momento en que escuchó la palabra «Kioto».",
    35: "Qué descarada hermana podrías pensar. Pero no habríamos tenido una conversación de hermanos tan normal hace un año.",
    36: "...Si lo piensas, probablemente le traería al menos un recuerdo de todos modos.",
    38: "Kirino sacó su teléfono móvil, escribiendo algo.",
    40: "Lo dijo mientras presionaba el botón de enviar en su teléfono y me lanzó una sonrisa en mi dirección.",
    41: "¿Qué es esa sonrisa...? Me dio un escalofrío en la espalda...",
    45: "DE Kuroneko.",
    50: "DE Saori.",
    54: "DE Ayase.",
    58: "Y recibí un último mensaje.",
    60: "DE Kirino.",
    65: "Qué chica sinvergüenza...",
    68: "Q-Qué comentario cruel...",
    69: "Además, ¡qué onda con ella! ¡Quedándose en mi habitación la víspera del viaje escolar cuando estoy muy ocupado!",
    71: "¡Estoy mirando porque me estás obstruyendo!",
    73: "¿Huh? ¿Qué está diciendo esta idiota?",
}
a137_s = {
    1: ("¡B-Bueno! ¡Se resolverá por sí solo!", "Kyousuke"),
    2: ("Kyou-chan, ¿estás de verdad bien?", "Manami"),
    3: ("Estoy cada vez más preocupada por Kyou-chan después de esto...", "Manami"),
    4: ("¡No te preocupes por eso! ¿Okay?", "Kyousuke"),
    5: ("Si Kyou-chan lo dice...", "Manami"),
    6: ("Pero no hagas nada imprudente, ¿entendido?", "Manami"),
    7: ("Te preocupas demasiado.", "Kyousuke"),
    8: ("Aunque lo digas...", "Manami"),
    9: ("¡Está bien...! ¿Alguna vez te he mentido?", "Kyousuke"),
    10: ("T-Tienes razón...", "Manami"),
    11: ("Sin embargo, ¡no hagas nada imprudente! ¡Siéntete libre de confiar en mí si algo pasa!", "Manami"),
    12: ("Sí, gracias, Manami.", "Kyousuke"),
    13: ("¡Esto es realmente malo! ¡No he preparado nada!", "Kyousuke"),
    15: ("Además, ¿qué necesito llevar? O espera, ¿por cuántos días?", "Kyousuke"),
    16: ("...¿Qué estás haciendo?", "Kirino"),
    17: ("¡¿No puedes verlo?! ¡Preparándome para mañana!", "Kyousuke"),
    18: ("Entonces... Tomaste una decisión...", "Kirino"),
    19: ("¿Tomar una decisión?", "Kyousuke"),
    20: ("¿No te estás yendo de casa?", "Kirino"),
    21: ("¡¿Estás estúpida?! ¡Por supuesto que no!", "Kyousuke"),
    22: ("¿Eh? ¿No es eso?", "Kirino"),
    23: ("¡¿Qué es eso de esa expresión «qué inesperado»?!", "Kyousuke"),
    24: ("¿No ibas en un viaje para encontrarte a ti mismo?", "Kirino"),
    26: ("Lamento decepcionarte, pero es solo un viaje escolar.", "Kyousuke"),
    27: ("Ohh.", "Kirino"),
    28: ("Sí, fufufu... Desde mañana, estaré lejos de ti en Kioto. Haaa, me siento lleno de energía.", "Kyousuke"),
    29: ("Yatsuhashi crudo.", "Kirino"),
    30: ("¿Huh?", "Kyousuke"),
    31: ("Trae algunos recuerdos para tu súper linda hermanita.", "Kirino"),
    32: ("......", "Kyousuke"),
    34: ("Está bien. Yatsuhashi crudo, entonces.", "Kyousuke"),
    37: ("Oye, ¿qué estás haciendo?", "Kyousuke"),
    39: ("Está bien, mensaje enviado.", "Kirino"),
    42: ("Jejeje... De hecho olvidaste un gran evento como el viaje escolar. Has superado a esa traficante de modas; no puedo evitar sentir lástima por ti.", "Kuroneko"),
    43: ("¿Usaré el poder de 【Abe no Seimei】 para eliminar la maldición dentro de tu sangre?", "Kuroneko"),
    44: ("PD ---- Tráeme artículos de pentagrama cuando regreses.", "Kuroneko"),
    46: ("¡Asegúrate de visitar la compañía de anime 【Heian Animation】 que está ubicada en Kioto!", "Saori"),
    47: ("¡HeiAni cargará con la existencia de la industria del anime en el futuro!", "Saori"),
    48: ("¡Por favor entra y explórala en mi lugar!", "Saori"),
    49: ("¡Por cierto! Escuché que también venden artículos originales.", "Saori"),
    51: ("¿Cómo te va en este clima caluroso y húmedo?", "Ayase"),
    52: ("Hablando de eso, aparentemente hay una tienda de renombre que vende increíbles 【Papeles Absorbentes de Aceite】.", "Ayase"),
    53: ("Me gustaría probar usarlos antes del trabajo.", "Ayase"),
    55: ("Todas son peticiones de recuerdos...", "Kyousuke"),
    56: ("¡Es imposible comprarlos todos!", "Kyousuke"),
    57: ("...¿Huh?", "Kyousuke"),
    59: ("De todos modos, primero será el yatsuhashi crudo. Te enviaré otro mensaje si pienso en más. Si olvidas, estás muerto.", "Kirino"),
    61: ("¿Y-Yo? ¿Esta frase «te enviaré otro si pienso en más»...?", "Kyousuke"),
    62: ("Lo entiendes al leerlo, ¿verdad?", "Kirino"),
    63: ("¡Lo entiendo! ¡Significa que quieres más!", "Kyousuke"),
    64: ("Exactamente.", "Kirino"),
    66: ("Entiendo... Te los compraré, así que no molestes mis preparativos.", "Kyousuke"),
    67: ("De todos modos, ¿por qué te preparas la noche justo antes del viaje escolar? ¿Estás estúpido?", "Kirino"),
    70: ("Je, ¿qué estás mirando?", "Kirino"),
    72: ("¡Ajá! ¿Podría ser que te sientes solo porque vas a estar separado de mí?", "Kirino"),
    74: ("Digo, vas a morir de soledad cuando yo no esté～", "Kirino"),
    75: ("Ah, escalofriante, escalofriante. Eres un siscon escalofriante～", "Kirino"),
    76: ("Esta chica... ¿No puede apurarse e ir a otro lugar...?", "Kyousuke"),
}

a138_n = {
    0: "La Rapsodia de la Víspera de la Partida",
    27: "¡Qué persistente!",
    36: "Es inútil... Mis palabras no le llegan en absoluto.",
    44: "Estoy demasiado cansado para replicar más...",
    46: "Lo que digas, gran S.",
}
a138_s = {
    1: ("Correcto, esto es para ti.", "Kirino"),
    2: ("Q-¿Qué es esto? Está algo ennegrecido con tinta.", "Kyousuke"),
    3: ("Es una lista de recuerdos, los quiero todos. Si olvidas cualquiera de ellos...", "Kirino"),
    4: ("¡T-Tantos!", "Kyousuke"),
    5: ("Quieres decir «tan pocos». ¿Hay algo con lo que estés infeliz?", "Kirino"),
    6: ("¡Por supuesto que lo hay! ¡¿Por qué tengo que comprar tantas cosas?!", "Kyousuke"),
    7: ("V-Veré qué puedo hacer al respecto... cuando llegue el momento.", "Kyousuke"),
    8: ("¿«Veré»? ¿Qué quieres decir?", "Kirino"),
    9: ("Sabes, ya te di un margen al extender tu fecha límite para completar «SisSis», ¿no?", "Kirino"),
    10: ("¡Esas son dos cosas diferentes!", "Kyousuke"),
    11: ("Huu. ¿Estás diciendo que no hay forma de lograr ambas?", "Kirino"),
    12: ("¡Exactamente eso es lo que quiero decir!", "Kyousuke"),
    13: ("¿Por qué necesito traer tantos recuerdos?", "Kyousuke"),
    14: ("No, traer recuerdos está bien, ¡pero al menos pide apropiadamente!", "Kyousuke"),
    15: ("Cómpramelos.", "Kirino"),
    16: ("Sabes...", "Kyousuke"),
    17: ("No tienes ningún derecho a objetar.", "Kirino"),
    18: (".........", "Kyousuke"),
    19: ("Tomaré eso como un acuerdo.", "Kirino"),
    20: ("Bueno, es un hecho escuchar la petición de la linda, sexy y brillante yo, ¿verdad?", "Kirino"),
    21: ("¡No es conveniente para mí, sabes!", "Kyousuke"),
    22: ("Este es un viaje escolar, así que tengo tiempo libre limitado.", "Kyousuke"),
    23: ("¡Es improbable que pueda comprarlos todos ya que son tantos!", "Kyousuke"),
    24: ("Te las arreglarás de alguna manera; no tiene nada que ver conmigo.", "Kirino"),
    25: ("Haré lo que pueda, así que aguanta.", "Kyousuke"),
    26: ("Prométemelo.", "Kirino"),
    28: (".........", "Kyousuke"),
    29: ("¿Por qué me miras fijamente? Asqueroso.", "Kirino"),
    30: ("¡Estoy estupefacto! ¡Impactado!", "Kyousuke"),
    31: ("De todos modos, es una promesa.", "Kirino"),
    32: ("No soy demasiado irrazonable. Entiendo completamente que te sientes inferior a la perfecta yo, pero no hay necesidad de estar así.", "Kirino"),
    33: ("¡¿Cómo eres perfecta?!", "Kyousuke"),
    34: ("Bueno, de todos modos te lo dejo a ti. Por favor, encárgate de ello.", "Kirino"),
    35: ("...Entiendo.", "Kyousuke"),
    37: ("De todos modos, cuento contigo.", "Kirino"),
    38: ("Sí sí, estoy siendo contado.", "Kyousuke"),
    39: ("¿Estupefacto?", "Kirino"),
    40: ("Ah, ¿mi increíbleza te tomó por sorpresa?", "Kirino"),
    41: ("¡¿Cómo cambió así de lo que estábamos hablando?!", "Kyousuke"),
    42: ("Tu voz fuerte es prueba suficiente. Bien, cuento contigo. Gracias. Eso es todo.", "Kirino"),
    43: ("Huh... Maldición, no tengo opción...", "Kyousuke"),
    45: ("¡Entonces, ¿por qué solo estás mirando fijamente?!", "Kirino"),
    47: ("Lo entiendo; el silencio es consentimiento.", "Kirino"),
    48: ("¡Ent～～～～iendo! ¡Maldición...!", "Kyousuke"),
}

data = {
    "000scriptAKYO_0134A.obj": build(a134_n, a134_s),
    "000scriptAKYO_0135A.obj": build(a135_n, a135_s),
    "000scriptAKYO_0136T.obj": build(a136_n, a136_s),
    "000scriptAKYO_0137A.obj": build(a137_n, a137_s),
    "000scriptAKYO_0138T.obj": build(a138_n, a138_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))