import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0120_s = {
    1: ("Así que esta es la casa de Kuroneko...", "Kyousuke"),
    2: ("¿De verdad te alegra tanto?", "Kuroneko"),
    3: ("Después de todo, es mi primera vez aquí... Kirino y Saori nunca han estado aquí, ¿verdad?", "Kyousuke"),
    4: ("Es verdad. Sin embargo, ¿es algo de lo que presumir?", "Kuroneko"),
    5: ("Hmm. Pero, eso... cómo decirlo...", "Kyousuke"),
    6: ("Es como si nuestra relación hubiera mejorado, supongo?", "Kyousuke"),
    7: ("Razonamiento falaz de una niña... Solo es que no tuve la oportunidad, eso es todo. No te engañes pensando que solo te invitaré a ti.", "Kuroneko"),
    8: ("Sí, sí. Lo sé... Tch.", "Kyousuke"),
    9: ("Mi casa no es tan grande, pero entra, por favor.", "Kuroneko"),
    10: ("A-Ah...", "Kyousuke"),
    11: ("...¿Q-Qué es esa cara llena de anticipación?", "Kuroneko"),
    12: ("No me veo así. Solo estoy nervioso.", "Kyousuke"),
    13: ("No hay nada de qué estar nervioso. Después de todo, no hay nadie en casa.", "Kuroneko"),
    14: ("¿E-Es así...", "Kyousuke"),
    15: ("...¿P-Por qué estás tan decaído?", "Kuroneko"),
    16: ("¿Tus hermanitas no están en casa?", "Kyousuke"),
    17: ("*suspiro*", "Kuroneko"),
    18: ("Qué bueno que he preparado algunas contramedidas...", "Kuroneko"),
}
a0120_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko",
}

a0125_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko",
}
a0125_s = {
    1: ("Por Dios, eres un caso perdido.", "Kuroneko"),
    2: ("¿Eh? ¿P-Por qué!?", "Kyousuke"),
    3: ("Pensaste en maneras de persuadir a alguien, pero ¿ese es tu verdadero objetivo?", "Kuroneko"),
    4: ("He sido menospreciada.", "Kuroneko"),
    5: ("...¿Huh?", "Kyousuke"),
    6: ("De ninguna manera permitiría que una persona como tú conozca a mis hermanas de repente.", "Kuroneko"),
    7: ("Solo hice una pregunta simple, ¿si tus hermanas están o no por aquí?", "Kyousuke"),
    8: ("Eso parece ser el caso en la superficie, sin embargo...", "Kuroneko"),
    9: ("...Oye, ¿por qué eres tan cauteloso?", "Kyousuke"),
    10: ("¿No es algo esperable?", "Kuroneko"),
    11: ("Por tu forma de hablar hace un momento, ya te has delatado bastante claramente.", "Kuroneko"),
    12: ("¿Qué he delatado?", "Kyousuke"),
    13: ("...Eres un auténtico siscon.", "Kuroneko"),
    14: ("¡No lo soy! Una persona con una hermana real, hay un 100% de probabilidad de que no sea un siscon!", "Kyousuke"),
    15: ("¿Vaya? ¿Eso significa que solo excluyes a tu propia hermana?", "Kuroneko"),
    16: ("No es eso. Todos los personajes relacionados con hermanitas están excluidos.", "Kyousuke"),
    17: ("Sabes que no estás siendo nada persuasivo usando personajes de juegos como ejemplo, ¿verdad?", "Kuroneko"),
    18: ("...Eres desesperanzadora si realmente lo dices en serio.", "Kyousuke"),
    19: ("Estoy medio bromeando.", "Kuroneko"),
    20: ("¡¿No todo?!", "Kyousuke"),
    21: ("La mitad va en serio.", "Kuroneko"),
    22: ("...¿Realmente parezco un siscon?", "Kyousuke"),
    23: ("Sí, lo pareces.", "Kuroneko"),
    24: ("Por eso no deseo que conozcas a mis hermanas.", "Kuroneko"),
    25: ("Eso significa...", "Kyousuke"),
    26: ("...¿Tus hermanas son realmente tan lindas?", "Kyousuke"),
    27: ("...Te desprecio.", "Kuroneko"),
    28: ("Lo lamento muchísimo.", "Kyousuke"),
    29: ("Como hermana mayor, estoy obligada a cuidar de mis hermanas. Por eso permití que mis hermanas salieran.", "Kuroneko"),
    30: ("¿En serio... Te llaman 'onee-chan' correctamente, ¿verdad?", "Kyousuke"),
    31: ("Por supuesto.", "Kuroneko"),
    32: ("Entonces, ¿cómo podría permitir que un pervertido como tú se acerque a mis hermanitas?", "Kuroneko"),
    33: ("No me tomes por alguna persona peligrosa.", "Kyousuke"),
    34: ("¿Acaso no estamos charlando bastante bien ahora mismo?", "Kyousuke"),
    35: ("...Lo siento por eso. Pero no se puede evitar.", "Kuroneko"),
    36: ("¿Qué no se puede evitar?", "Kyousuke"),
    37: ("Estás confirmado como una persona peligrosa. La prueba de esto ya salió a la luz. Por favor, ríndete.", "Kuroneko"),
    38: ("Guh...", "Kyousuke"),
    39: ("...Sin embargo.", "Kuroneko"),
    40: ("...Así que me tratan como un pervertido.", "Kyousuke"),
    41: ("Sí, desafortunadamente.", "Kuroneko"),
    42: ("...¿Realmente soy tan poco confiable?", "Kyousuke"),
    43: ("Si se relaciona con este asunto, no eres nada confiable.", "Kuroneko"),
    44: ("Para empezar, ¿viniste realmente aquí solo para ver a mis hermanas? ¿Y qué hay del propósito original?", "Kuroneko"),
    45: ("¡Ah! Pero... sí. Estoy aquí para ayudar...", "Kyousuke"),
    46: ("Es bueno que lo sepas. Mira, es hora de comenzar a trabajar.", "Kuroneko"),
    47: ("Ah... E-Eso, es verdad...", "Kyousuke"),
    48: ("Hmph... Buen chico. Olvídate de mis hermanitas. ¿Entendido?", "Kuroneko"),
    49: ("Además, ese no es el objetivo de hoy, ¿verdad?", "Kuroneko"),
    50: ("...En efecto, no lo es.", "Kyousuke"),
    51: ("No lo pierdas de vista de nuevo.", "Kuroneko"),
    52: ("Guh... Sí. Lo lamento muchísimo.", "Kyousuke"),
    53: ("H-Hmph... Te ves decaído después de que dije que no había nadie en casa.", "Kuroneko"),
    54: ("...¿No deseas estar a solas conmigo, solo nosotros dos?", "Kuroneko"),
    55: ("N-Nada de eso.", "Kyousuke"),
    56: ("...¿E-Es así. Qué bien.", "Kuroneko"),
}

a0130_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko",
    2: "Podría estar imaginándolo, pero Kuroneko parece estar mirándome con frialdad.",
    3: "¿Se supone que debo decir algo aquí...?",
    7: "....De algún modo, parece que su buen humor ha regresado.",
    18: "Y así, comenzó mi conferencia de principiante total sobre ser asistente de doujin.",
    59: "He estado viendo a Kuroneko en la escuela, pero ahora puedo ver su obstinación cuando se trata de la creación...",
    60: "Quizás sea algo que planea mostrarle a Kirino... Aprendí mucho hoy.",
    66: "He visto este momento de presión mientras trabajabas antes, una vez. ¿Podría ser que sea así cuando estás realmente ocupada?",
    79: "Ah, ya veo. Kirino seguramente estaría celosa cuando vea que le quité a su querida Kuroneko.",
}
a0130_s = {
    1: ("Hmph...", "Kuroneko"),
    4: ("*suspiro*... Estoy decepcionada de ti, pero enojarme contigo ahora no tiene sentido.", "Kuroneko"),
    5: ("No quiero perder tiempo. Te explicaré los detalles de esta tarea.", "Kuroneko"),
    6: ("S-Sí, te lo dejo a ti.", "Kyousuke"),
    8: ("Kuroneko, lo siento. Solo vine a ayudarte.", "Kyousuke"),
    9: ("Así que por favor anímate un poco, ¿de acuerdo?", "Kyousuke"),
    10: ("Eres realmente desesperanzador...", "Kuroneko"),
    11: ("Pero está bien. Solo estamos perdiendo tiempo si charláramos aquí, así que olvidémonos de lo que acaba de pasar.", "Kuroneko"),
    12: ("Bueno entonces, ya que dijiste que vas a ayudar, apurémonos y hagamos algo de trabajo.", "Kuroneko"),
    13: ("Sin embargo, no hay nada en lo que tú, un completo novato, puedas ayudar.", "Kuroneko"),
    14: ("...¿Eh, en serio?", "Kyousuke"),
    15: ("¿Cuánto sabes sobre la creación de manga?", "Kuroneko"),
    16: ("Honestamente, casi nada en absoluto.", "Kyousuke"),
    17: ("Ya veo... Si es así, empezaré desde lo básico.", "Kuroneko"),
    19: ("Hay tres fases durante la creación de manga si la dividimos de manera correspondiente.", "Kuroneko"),
    20: ("Primero, la trama. Esto se refiere a crear un tipo de historia, sea cual sea el género o la categoría. Es lo mismo para una novela y una película también.", "Kuroneko"),
    21: ("Incluso lo mismo va para el manga. Solo necesitamos escribir el esquema de la historia. Incluso entre profesionales, hay personas que solo trabajan en", "Kuroneko"),
    22: ("esto para sacar a la luz obras originales.", "Kuroneko"),
    23: ("Lo siguiente es el storyboard. A partir de esta fase, es algo que solo tiene el manga. En términos más simples, significa dibujar un boceto aproximado.", "Kuroneko"),
    24: ("Decidir el diseño de los paneles y las posiciones de los personajes, por ejemplo. También hay personas que solo trabajan específicamente en esta fase de la creación.", "Kuroneko"),
    25: ("Bueno, aunque dije bastante, no importa si no lo entiendes. Estas cosas no tienen relación con el trabajo de un asistente.", "Kuroneko"),
    26: ("¿En serio...", "Kyousuke"),
    27: ("Sin embargo, esto es esencial para el proceso de crear un manga. Por eso se requiere que lo sepas.", "Kuroneko"),
    28: ("Finalmente, la última fase es el manuscrito. Tu trabajo, es hacer el toque final en él.", "Kuroneko"),
    29: ("Incluso para ti, creo que deberías saber al menos qué significa 'rellenar los colores', ¿verdad?", "Kuroneko"),
    30: ("Sí. ¿Eso significa entintar, verdad? Para el cabello y la ropa...", "Kyousuke"),
    31: ("Eso es. Básicamente, ese es el trabajo que harás.", "Kuroneko"),
    32: ("Sin embargo, nunca usé un lápiz para dibujar antes... ¿está bien?", "Kyousuke"),
    33: ("Jeje... Si esto fuera el pasado, ciertamente sería un gran problema.", "Kuroneko"),
    34: ("Pero hoy en día, es posible usar la computadora para dibujar manga. Incluso con tu falta de habilidad, completar esto no será un problema.", "Kuroneko"),
    35: ("¿E-Es así... Increíble...", "Kyousuke"),
    36: ("Hablando de eso, contaré contigo para las cosas que puedas hacer.", "Kuroneko"),
    37: ("Primero debes entender lo básico de usarla. Deberíamos poder completar eso hoy si todo sale según lo planeado.", "Kuroneko"),
    38: ("¿Huh? ¿Está bien haciendo solo eso?", "Kyousuke"),
    39: ("En comparación con fallar de inmediato al trabajar en tareas imposibles, es mejor dominar lo básico y evitar errores. ¿Entiendes?", "Kuroneko"),
    40: ("E-Es verdad...", "Kyousuke"),
    41: ("Dicho esto, hay dos tipos de errores que uno puede cometer al trabajar en la computadora.", "Kuroneko"),
    42: ("Borrar los archivos equivocados, así como sobrescribir la copia de respaldo original. Esos son los dos.", "Kuroneko"),
    43: ("Lo entiendo. Aunque son errores simples, sería muy problemático si ocurrieran.", "Kyousuke"),
    44: ("Es verdad. Además, todo tipo de errores aparecerán si uno no está acostumbrado.", "Kuroneko"),
    45: ("Para evitar eso, uno debe tener el hábito de hacer respaldos con frecuencia. Por eso, antes de que hagas cualquier otra cosa, por favor acostúmbrate a ello.", "Kuroneko"),
    46: ("...Entendido.", "Kyousuke"),
    47: ("Pero... aunque dije que te iba a ayudar... ¿No te estorbaría?", "Kyousuke"),
    48: ("Está dentro de mis cálculos que habrá algunos accidentes, así que tranquilo.", "Kuroneko"),
    49: ("Trabajar solo y trabajar con alguien son dos cosas completamente diferentes...", "Kuroneko"),
    50: ("...¿Kuroneko?", "Kyousuke"),
    51: ("La soledad corroe el espíritu... Pero si alguien logra acercar a alguien, entonces juntos, ¡su poder crece exponencialmente!", "Kuroneko"),
    52: ("¡Este poder excede los límites de este mundo y se convierte en una leyenda! Deberías ser consciente de ello también, las muchas leyendas nacidas de corazones conectados...", "Kuroneko"),
    53: ("O-Oye～, Kuroneko～. Vuelve en sí～.", "Kyousuke"),
    54: ("Qué lástima, parece que no pudiste comprender eso.", "Kuroneko"),
    55: ("S-Sí, lo siento por eso.", "Kyousuke"),
    56: ("Jeh, está bien. Últimamente también he estado aprendiendo mucho. Todo tipo de cosas después de unirme al club...", "Kuroneko"),
    57: ("¿Ah en serio... todo tipo de cosas, eh.", "Kyousuke"),
    58: ("Sí, todo tipo.", "Kuroneko"),
    61: ("Por cierto, ¿qué vas a hacer si yo usara tu computadora?", "Kyousuke"),
    62: ("Por supuesto haré trabajo que no requiera computadora. Cosas como la trama y el storyboard se pueden hacer en papel.", "Kuroneko"),
    63: ("Pero, cuando esas estén hechas...", "Kyousuke"),
    64: ("Veamos... Supongo que te despediré cuando lleguemos a ese punto?", "Kuroneko"),
    65: ("Oye oye, no tiene sentido si no estoy ayudando cuando estás ocupada.", "Kyousuke"),
    67: ("Ah, supongo que no hay remedio. En ese caso...", "Kyousuke"),
    68: ("¿Estás pensando en pedirle prestada a tu hermana?", "Kuroneko"),
    69: ("...¿Cómo lo supiste?", "Kyousuke"),
    70: ("Puedo ver a través de tu línea de pensamiento fácilmente.", "Kuroneko"),
    71: ("¿En serio.", "Kyousuke"),
    72: ("Te advertiré primero, será mejor que no reveles demasiada información a esa mujer.", "Kuroneko"),
    73: ("¿Revelar qué información?", "Kyousuke"),
    74: ("Sobre que vienes a mi casa.", "Kuroneko"),
    75: ("¿Hay algún problema en contarle eso a Kirino?", "Kyousuke"),
    76: ("...Eres realmente un idiota, senpai.", "Kuroneko"),
    77: ("Oye, ¿qué quieres decir con eso?", "Kyousuke"),
    78: ("De todos modos, no es no. Si le contaras a tu hermana sobre esta 'ceremonia' en curso que estamos realizando, te enviaré por el camino al infierno.", "Kuroneko"),
    80: ("...Lo entiendo. Pensaré en una buena razón para pedirle prestada una laptop a Kirino.", "Kyousuke"),
    81: ("¿Cuáles son las posibilidades de éxito?", "Kuroneko"),
    82: ("Déjamelo a mí. Tengo un plan secreto.", "Kyousuke"),
}

a0135_n = {
    0: "Ruta de Kuroneko · Adquisición De Suministros Necesarios",
}
a0135_s = {
    1: ("¿Qué pasa?", "Kirino"),
    2: ("¿Podrías prestarme tu laptop?", "Kyousuke"),
    3: ("¿Por qué? ¿No tienes una computadora de escritorio? La que te dio Saori.", "Kirino"),
    4: ("Aunque es verdad...", "Kyousuke"),
    5: ("Deberías poder entender mis sentimientos como entusiasta del 'hermanita-moe'. Quiero jugar juegos de hermanitas en la laptop de mi hermana.", "Kyousuke"),
    6: (".........", "Kirino"),
    7: ("(´·ω·｀) ¿Hah?", "Kirino"),
    8: ("¡Oye! ¿¡Por qué cerraste la puerta?!", "Kyousuke"),
    9: ("Qué asco. ( ﾟÅﾟ;)", "Kirino"),
    10: ("¿Eh? Es raro... Mi plan secreto ha...", "Kyousuke"),
    11: ("¡Lo siento! ¡Solo te mentí! ¡Por favor abre la puerta! ¡Dame otra oportunidad!", "Kyousuke"),
    12: ("¡¿Qué?! ¡Eres realmente molesto!", "Kirino"),
    13: ("¡Necesito tu laptop para ayudar a Kuroneko! Aunque no puedo decirte por qué -- ¡Por favor, prémestamela!", "Kyousuke"),
    14: ("......", "Kirino"),
    15: ("Espera un momento.", "Kirino"),
    16: ("Aquí tienes.", "Kirino"),
    17: ("O-Oh... Gracias.", "Kyousuke"),
    18: ("...Aunque no sé qué estás haciendo...", "Kirino"),
    19: ("Tch, lo que sea. Me voy.", "Kirino"),
    20: ("Kirino... Puedo entender tus sentimientos sin que me lo digas.", "Kyousuke"),
}

a0140_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko 2",
    24: "Toqué la mano de Kuroneko...",
    25: "...Espera, ¿por qué su cara está tan roja?",
    29: "Cómo decirlo...",
    30: "Es bastante incómodo para ambos trabajar en silencio...",
}
a0140_s = {
    1: ("Bueno entonces, puedo hacer mi primer debut espectacular como su asistente.", "Kyousuke"),
    2: ("Oye～", "Kyousuke"),
    3: ("V-Voy...", "Kuroneko"),
    4: ("Y-Yo.", "Kyousuke"),
    5: ("...Bienvenido.", "Kuroneko"),
    6: ("Entra, por favor. Aunque es un poco urgente, tengo algo que pedirte.", "Kuroneko"),
    7: ("Ah, lo siento. Parece que hice algo raro aquí...", "Kyousuke"),
    8: ("Si cometiste un error, solo presiona Ctrl y Z juntos para deshacerlo.", "Kuroneko"),
    9: ("Oh, ya veo. ¡Gracias!", "Kyousuke"),
    10: ("...Te advertiré primero.", "Kuroneko"),
    11: ("Es fácil fallar al principio, así que como precaución, por favor no sobrescribas ni borres accidentalmente el archivo original.", "Kuroneko"),
    12: ("...Lo siento. Sobrescribí accidentalmente...", "Kyousuke"),
    13: ("Ah... Esto ya no se puede usar.", "Kuroneko"),
    14: ("He respaldado cada archivo de este lado.", "Kuroneko"),
    15: ("Tendrás que empezar desde cero desde aquí si cometes otro error... Ese es tu castigo por el error.", "Kuroneko"),
    16: ("Realmente... lo siento. Solo te estoy dando problemas.", "Kyousuke"),
    17: ("No te preocupes por eso. Ya lo dije, ¿verdad? Tu error está dentro de mis cálculos. No tengo muchas expectativas de ti desde el principio.", "Kuroneko"),
    18: ("Además, yo...", "Kuroneko"),
    19: ("¿'Yo'...?", "Kyousuke"),
    20: ("Ah... La tableta gráfica...", "Kuroneko"),
    21: ("Está bien, yo la agarro.", "Kyousuke"),
    22: ("Y-Yo puedo agarrarla yo misma...", "Kuroneko"),
    23: ("...Oh.", "Kyousuke"),
    26: ("Oye, ¿estás bien? ¿Tienes fiebre...", "Kyousuke"),
    27: ("...N-Nada. Vuelve a tu trabajo.", "Kuroneko"),
    28: ("S-Sí...", "Kyousuke"),
}

data = {
    "000scriptCKUR_0120A.obj": build(a0120_n, a0120_s),
    "000scriptCKUR_0125T.obj": build(a0125_n, a0125_s),
    "000scriptCKUR_0130A.obj": build(a0130_n, a0130_s),
    "000scriptCKUR_0135A.obj": build(a0135_n, a0135_s),
    "000scriptCKUR_0140A.obj": build(a0140_n, a0140_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
