import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0088_n = {
    0: "Ruta de Saori · Un Punto Muerto",
    7: "Llamarte a ti misma una flor con esos lentes giratorios es demasiado...",
    21: "¿Eh? ¿Eh? ¿Ehh?",
    22: "Esta sensación suave... ¿podría ser...?",
    31: "Saori mostró una sonrisa de corazón.",
    32: "Reflejándose en la luz del atardecer, el rostro de Saori brilló hermosamente.",
    33: "Sin estar preparado, mi corazón dio un salto... Pero oye, eso no es justo...",
}
a0088_s = {
    1: ("De todos modos, aguanta. Ve a por ello, ¿de acuerdo?", "Kyousuke"),
    2: ("...Estoy agradecida por todo.", "Saori"),
    3: ("Dije que está bien. No te preocupes por eso.", "Kyousuke"),
    4: ("Mmm... ¡por favor no me acaricies de repente! ¡Eso hace cosquillas!", "Saori"),
    5: ("Ah, lo siento.", "Kyousuke"),
    6: ("Acariciar a una joven flor como yo como si fuera un cachorrito... ¡Realmente no entiendes el corazón de una doncella!", "Saori"),
    8: ("...Justo ahora, pensaste algo grosero, ¿verdad?", "Saori"),
    9: ("¿Eh? Uhh...", "Kyousuke"),
    10: ("¡No sirve de nada fingir ser inocente!", "Saori"),
    11: ("¡Lo sé porque leí tu mente!", "Saori"),
    12: ("¡¿En serio!?", "Kyousuke"),
    13: ("Solo bromeaba.", "Saori"),
    14: ("¡¡Tú!!", "Kyousuke"),
    15: ("Pero-", "Saori"),
    16: ("Incluso yo puedo hacer cosas femeninas.", "Saori"),
    17: ("Si puedes, entonces ¿por qué no lo h-", "Kyousuke"),
    18: ("¿Huh...?", "Kyousuke"),
    19: ("Je... ¿Qué te parece, Kyousuke-shi?", "Saori"),
    20: ("Solo... como muestra de mi gratitud...", "Saori"),
    23: ("Fufufu...", "Saori"),
    24: ("¿E-Eso fue...?", "Kyousuke"),
    25: ("No tienes que estar tan nervioso, ¿verdad? O...", "Saori"),
    26: ("...¿Te estaba... molestando?", "Saori"),
    27: ("Por supuesto... que no.", "Kyousuke"),
    28: ("Es solo que... me sorprendió un poco.", "Kyousuke"),
    29: ("Ah... ¿Es así...?", "Saori"),
    30: ("...Qué alivio, que no me aborreces.", "Saori"),
    34: ("Entonces, con eso, por favor espera un poco por las buenas noticias.", "Saori"),
    35: ("Volveré con seguridad con algunas buenas noticias.", "Saori"),
    36: ("Sí... Lo espero, Saori.", "Kyousuke"),
    37: ("¡Entendido!", "Saori"),
}

a0090_n = {
    0: "Ruta de Saori · Festín Juntos En El Comiket",
    1: "Unos días después...",
    2: "Saori probablemente está ocupada, no he podido contactarla desde entonces.",
    3: "Sin embargo, no me preocupaba mi teléfono en silencio como antes.",
    4: "Porque Saori ya ha decidido firmemente avanzar con sus sentimientos...",
    5: "Y así, hoy es el primer día del Comiket de Verano.",
    6: "Kuroneko estaba participando como círculo, y Kirino y yo vinimos a su puesto para pasar el rato-",
    7: "Quiero decir, vinimos a mirar alrededor, sin planes de comprar nada pero...",
    18: "Kirino y Kuroneko, como siempre, están en eso otra vez...",
    19: "Se controlan cuando hay clientes, pero antes de que te des cuenta, vuelven a insultarse entre ellas...",
    20: "Eh, es como su forma de comunicación. No es una pelea seria.",
    22: "...Estoy tan aburrido.",
    23: "Con Kirino y Kuroneko entrando en su propio mundo, me dejan sin nada que hacer...",
    24: "Si tan solo hubiera algo que hiciera latir mi corazón.",
    25: "Por ejemplo... una vendedora con traje de maid enamorándose de mí a primera vista, y confesándome...",
    26: "Una belleza en cosplay enamorándose de mí a primera vista, y confesándome...",
    27: "Cuando lo pienso... eso es todo lo que se me ocurre... imposible.",
    28: "Enamorarse a primera vista es solo una leyenda urbana.",
    32: "Ha aparecido una belleza----(ﾟ∀ﾟ)----!!!!",
    33: "¡Y es dulce y linda! Oh no, es seriamente de mi tipo!",
    34: "Oye oye, ¿quién dijo que enamorarse a primera vista es una leyenda urbana?",
    35: "¡Si esto no es amor a primera vista, entonces ¿qué es este latido en mi pecho!",
    36: "Espera, ¿huh...?",
    37: "¿Por qué esta persona sabe mi nombre?",
    50: "Saori habló sobre los últimos días con una gran sonrisa en su rostro.",
    51: "Primero, Saori enfrentándose a sus padres.",
    52: "Sus padres recibieron un gran impacto después de aprender sobre sus verdaderos sentimientos.",
    53: "Parece que Saori siempre ha sido enseñada a ser disciplinada y concienzuda por sus padres.",
    54: "Una Saori desinteresada y bien educada. Esta misma persona, por primera vez, diciendo lo que sentía, realmente tocó profundamente a sus padres.",
    60: "Hm. Él realmente es digno de ser hijo del CEO de una gran empresa, teniendo un corazón tan grande.",
    65: "¡No me mires fijamente! ¡Eres demasiado deslumbrante para que te mire!",
    78: "Saori bajó los hombros y solo me miró fijamente.",
    79: "Solo por curiosidad, miré detrás de mí. Por supuesto, no había nadie allí.",
    80: "...Espera... no querrás decir...",
    88: "Dije eso. Definitivamente dije que me casaría con Saori.",
    89: "Pero pensé que era lo único que podía decir para animarla...",
    93: "¿No hay problemas...?",
    94: "Pero, esto es como... una propuesta...",
    95: "Siento...",
    101: "¡Parpadeando de una manera adorable así...! Así, justo así-",
    102: "Incluso aunque es más grande que yo, es irresistiblemente linda.",
    103: "...Espera, ser linda no tiene nada que ver con ser grande.",
    123: "-Entonces Saori hizo una cara ω y dio una sonrisa alegre.",
}
a0090_s = {
    8: ("Como dije, ¡no hay razón para que tu libro narcisista se venda!", "Kirino"),
    9: ("Y, ¿qué es con este libro de referencia masivo?", "Kirino"),
    10: ("¿Por qué es necesario leer un libro de referencia de 500 páginas para un doujinshi? ¿Estás menospreciando a los clientes?", "Kirino"),
    11: ("...No tengo interés en personas ignorantes que no pueden entender el vocabulario de este libro.", "Kuroneko"),
    12: ("Así como la gente elige libros, los libros eligen a la gente.", "Kuroneko"),
    13: ("Por supuesto, nadie elegiría a una perra como tú, sin embargo.", "Kuroneko"),
    14: ("¿Huh? ¡Eres totalmente molesta!", "Kirino"),
    15: ("Esas palabras prueban mi punto.", "Kuroneko"),
    16: ("Bueno, ya que hemos llegado a esto, solo pondré una maldición sobre ti como respuesta.", "Kuroneko"),
    17: ("Huh...", "Kyousuke"),
    21: ("Pero aun así-", "Kyousuke"),
    29: ("¡Kyousuke-san!", "???"),
    30: ("...¿Huh?", "Kyousuke"),
    31: ("Ufufufu...", "???"),
    38: ("Espera, ¡eres Saori!", "Kyousuke"),
    39: ("Fufufu, como siempre, tus reacciones son maravillosas.", "Saori"),
    40: ("Debido a eso, mis esfuerzos hasta ahora han valido la pena.", "Saori"),
    41: ("Como siempre... no has cambiado nada.", "Kyousuke"),
    42: ("¿Qué estás diciendo?", "Saori"),
    43: ("No importa cómo me vea, sigo siendo yo.", "Saori"),
    44: ("¡Pfft! Bueno, supongo que tienes razón.", "Kyousuke"),
    45: ("Entonces... ¿por qué estás aquí hoy?", "Kyousuke"),
    46: ("Oh, cierto. ¡Casi me olvido de eso!", "Saori"),
    47: ("Pensé que podría verte si viniera aquí...", "Saori"),
    48: ("¿Así que eso significa?", "Kyousuke"),
    49: ("Sí, he traído buenas noticias.", "Saori"),
    55: ("Se disculparon diciendo, «No queríamos forzar a nuestra hija hacia un futuro no deseado».", "Saori"),
    56: ("Ya veo... entonces ¿qué hay del compromiso y de tu prometido?", "Kyousuke"),
    57: ("Mi padre lo canceló.", "Saori"),
    58: ("En un momento, quería que la boda se adelantara, pero...", "Saori"),
    59: ("Sin ocultarlo, expliqué mi razón, y él lo entendió.", "Saori"),
    61: ("Realmente, es un poco increíble que lo hayan aceptado.", "Kyousuke"),
    62: ("Sí. Les dije que la razón por la que pude decirles cómo me sentía fue gracias al apoyo de una persona llamada Kyousuke.", "Saori"),
    63: ("¿Y-Yo?", "Kyousuke"),
    64: ("¿Quién más podría ser?", "Saori"),
    66: ("Y tengo una cosa más que discutir contigo...", "Saori"),
    67: ("¿Qué?", "Kyousuke"),
    68: ("Esta ceremonia de boda fue cancelada, pero...", "Saori"),
    69: ("Hay otro candidato para prometido...", "Saori"),
    70: ("...¿Lo dices en serio?", "Kyousuke"),
    71: ("Sí, lo digo.", "Saori"),
    72: ("Pero, si la otra parte está dispuesta, yo estoy...", "Saori"),
    73: ("¿Quién es este otro candidato a prometido...", "Kyousuke"),
    74: ("*suspiro*...", "Saori"),
    75: ("Tu único punto malo es esa horrible cabeza dura.", "Saori"),
    76: ("¿Huh? ¿Qué significa eso?", "Kyousuke"),
    77: ("¿He dicho esto y todavía no lo entiendes?", "Saori"),
    81: ("...¿En serio?", "Kyousuke"),
    82: ("Sí.", "Saori"),
    83: ("Se supone que... soy yo?", "Kyousuke"),
    84: ("Sí.", "Saori"),
    85: ("Les dije a mis padres sobre cuando me confesaste, diciendo «¡Me casaré contigo!»", "Saori"),
    86: ("Por eso me dejaron cancelar el compromiso.", "Saori"),
    87: ("Uhh, ahh...", "Kyousuke"),
    90: ("O, ¿estabas mintiendo entonces?", "Saori"),
    91: ("¡¿Por supuesto que no!? ¡Siempre hablo en serio!!", "Kyousuke"),
    92: ("Entonces no habrá ningún problema, ¿verdad?", "Saori"),
    96: ("Con estas dos veces, he usado la determinación de toda mi vida.", "Saori"),
    97: ("Por eso, ¿asumirás la responsabilidad?", "Saori"),
    98: ("U-Umm...", "Kyousuke"),
    99: ("...¿No?", "Saori"),
    100: ("Urgh...", "Kyousuke"),
    104: ("Um... ¿estás realmente bien conmigo?", "Kyousuke"),
    105: ("...¿Qué estás diciendo?", "Saori"),
    106: ("No lo quiero... a menos que sea contigo.", "Saori"),
    107: ("Oye ustedes dos, ¿qué están haciendo?", "Kirino"),
    108: ("Se ven bastante íntimos... no nos están ocultando ningún secreto, ¿verdad?", "Kuroneko"),
    109: ("¿Qué deberíamos hacer, Saori?", "Kyousuke"),
    110: ("Lo descubrirán pronto de todos modos. Además...", "Saori"),
    111: ("No puedo ocultar algo a mis dos preciosas amigas.", "Saori"),
    112: ("¡Pfft! ¿Es así?", "Kyousuke"),
    113: ("Kiririn-san, Kuroneko-san, por favor escuchen.", "Saori"),
    114: ("Me comprometeré con Kyousuke-san.", "Saori"),
    115: ("Je, comprometida.", "Kirino"),
    116: ("Oh, eso es un evento auspicioso...", "Kuroneko"),
    117: ("Espera, ¿¡comprometida!?", "Kirino"),
    118: ("E-Espera... ¿Cuál es el significado de esto...?", "Kuroneko"),
    119: ("No hay más significado, es lo que es...", "Kyousuke"),
    120: ("N-No lo entiendo, ¡no puedo aceptar esto!", "Kirino"),
    121: ("¿Podrías decirme las circunstancias exactas?", "Kuroneko"),
    122: ("¡Por supuesto! ¡Te lo explicaré claramente!", "Saori"),
}

a0100_n = {
    0: "Ruta de Saori · Amigas Sin Lentes Giratorios",
    1: "Después de eso, pasaron algunos días.",
    2: "Hoy es el primer día del Comiket.",
    3: "Kirino y yo fuimos a jugar por el espacio del círculo de Kuroneko...",
    4: "O más bien, fuimos a mirar la mercancía de Kuroneko.",
    5: "Saori estaba... no allí.",
    6: "Cediendo a la petición de su prometido, renunció a ser una otaku.",
    7: "La comunidad de «Otaku Girls Unite!» que Saori creó ya no existe.",
    8: "O estaba a punto de desaparecer, cuando Kirino y Kuroneko fueron confiadas para dirigirla.",
    9: "Por supuesto, su prometido aparentemente había hecho que cortara lazos con Kirino, Kuroneko, y yo.",
    10: "O así parecía.",
    21: "Bueno...",
    22: "Incluso aunque ha sido así mucho últimamente, hemos estado manteniendo contacto.",
    23: "Incluso si nos separamos, nuestros corazones están conectados.",
    24: "¿No es eso lo que significa ser amigas?",
    25: "...Todavía no puedo aceptar realmente esto, sin embargo...",
}
a0100_s = {
    11: ("¡Oh sí! La negra trajo esos libros que no se venden nada otra vez. Ya es hora de que aprenda, ¿verdad?", "Kirino"),
    12: ("¿Podrías no estar tan celosa de que estos libros son demasiado buenos para su comprensión?", "Kuroneko"),
    13: ("Bueno, no es como si hubiera esperado que lo entendieras.", "Kuroneko"),
    14: ("¿Huh? De todos modos, no quiero entender esos libros basura...", "Kirino"),
    15: ("Fufufu... ¿Realmente crees que esas palabras funcionarán conmigo?", "Kuroneko"),
    16: ("Deberías bañarte en las llamas de mediados de verano del purgatorio y quemar tu alma.", "Kuroneko"),
    17: ("Espera, ¿puedes escuchar, Saori? Esa negra está enviando ondas de radio desde su cabeza otra vez.", "Kirino"),
    18: ("...Dame el teléfono. Tengo algo que quiero decir...", "Kuroneko"),
    19: ("¿Por qué no usas esa telepatía tuya?", "Kirino"),
    20: ("No hables de la telepatía como un dispositivo de conversación. Es una inducción de almas solo dada a los elegidos.", "Kuroneko"),
}

a0102_n = {
    0: "Ruta de Saori · El Final",
    1: "Después de eso, nunca volví a ver a Saori.",
    2: "¡Qué pena! ¡Este es el final de El Cuento De Kyousuke!",
}

a0105_n = {
    0: "Ruta de Saori · El Final",
    1: "Después de eso, Saori y yo intentamos tomar el lugar de su prometido.",
    2: "Al final, fui tratado como una persona sospechosa, y todo terminó con la policía siendo llamada.",
    3: "El ingenio rápido de Saori terminó salvándome, pero cuando llegué a casa, mi padre no estaba nada complacido.",
    4: "Desde ese día, no he podido contactar a Saori...",
    5: "¡Qué pena! ¡Este es el final de El Cuento De Kyousuke!",
}

a0110_n = {
    0: "Ruta de Saori · La Conclusión Al Final Del Alboroto",
    1: "Y así, los días y los meses pasaron a la deriva...",
    2: "Desde entonces, me comporté como el modelo mismo de un otaku galante para ganarme el favor de los padres de Saori.",
    3: "Antes de que nos diéramos cuenta, decían cosas como, «¡Su futuro se ve brillante, este es un guardián!»",
    4: "Y entonces hoy, a pesar de que Saori y yo todavía estamos en la preparatoria, finalmente estábamos en nuestra hermosa ceremonia de matrimonio.",
    9: "¡Estás siendo bastante dura con tus padres, ¿no lo crees?!",
    10: "«Por el bien de mis padres...» ¿¡A dónde fue la ejemplar Saori?!",
    11: "Bueno, en su caso, no retener nada sobre sus padres puede ser algo bueno.",
    27: "Saori, luciendo avergonzada, se movió inquieta mientras miraba hacia abajo.",
    28: "Cuando un hombre ve a una chica comportándose así...",
    29: "Lo hace enamorarse de ella. O... lo hace querer molestarla...",
    39: "Y así, Saori y yo nos casamos.",
    40: "...¿Qué hay de la diferencia de altura?",
    41: "...Mentiría si dijera que no me importa...",
    42: "Pero, no lo suficiente como para preocuparme, porque...",
    43: "¡Mi esposa es la más linda del mundo entero!",
}
a0110_s = {
    5: ("Estás nervioso, ¿verdad, Kyousuke-san?", "Saori"),
    6: ("¡Por supuesto! Es un matrimonio después de todo, un matrimonio.", "Kyousuke"),
    7: ("Oh no, no es algo por lo que alterarse.", "Saori"),
    8: ("Esto es solo para silenciar a mis padres quejosos. Podrías llamarlo jugar a las fantasías.", "Saori"),
    12: ("Es una ceremonia meramente por apariencias, porque todavía no has sido registrado en nuestro registro familiar...", "Saori"),
    13: ("Entonces, no tenses tanto tus hombros.", "Saori"),
    14: ("*suspiro*... Qué suerte tienes, no estás nada nerviosa.", "Kyousuke"),
    15: ("Pero... yo estoy nerviosa...", "Saori"),
    16: ("¿Huh?", "Kyousuke"),
    17: ("No hay manera de que no lo estuviera...", "Saori"),
    18: ("Creo que he experimentado algunas cosas más que la mayoría de la gente.", "Saori"),
    19: ("Pero usar un vestido de novia y ser una novia... es mi primera vez.", "Saori"),
    20: ("Saori...", "Kyousuke"),
    21: ("Kyousuke-san, simplemente sigues tomando todas mis primeras veces...", "Saori"),
    22: ("...No digas algo tan fácil de malinterpretar.", "Kyousuke"),
    23: ("Fue un cumplido.①", "Saori"),
    24: ("Oh, tú...", "Kyousuke"),
    25: ("Pero, hablando honestamente...", "Saori"),
    26: ("Este tipo de latido en mi corazón es un primero en mi vida...", "Saori"),
    30: ("Jaja, ¿tomé otra de tus primeras veces, huh?", "Kyousuke"),
    31: ("¿Eh...? ¡A-Ah!", "Saori"),
    32: ("...Dijiste que parara, y sin embargo aquí estás diciéndome lo mismo.", "Saori"),
    33: ("De ahora en adelante, tenemos que ser considerados el uno con el otro.", "Saori"),
    34: ("No te preocupes.", "Kyousuke"),
    35: ("Puede que todavía no sea confiable, pero...", "Kyousuke"),
    36: ("¡Asumiré la responsabilidad y te haré feliz!", "Kyousuke"),
    37: (".........", "Saori"),
    38: ("...¡Sí!", "Saori"),
}

data = {
    "000scriptDSAO_0088G.obj": build(a0088_n, a0088_s),
    "000scriptDSAO_0090E.obj": build(a0090_n, a0090_s),
    "000scriptDSAO_0100E.obj": build(a0100_n, a0100_s),
    "000scriptDSAO_0102E.obj": build(a0102_n, {}),
    "000scriptDSAO_0105E.obj": build(a0105_n, {}),
    "000scriptDSAO_0110E.obj": build(a0110_n, a0110_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
