import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0024_n = {
    0: "Ruta de Saori · La Familiar De Kuroneko",
    6: "Hmm... Esa persona de allá es...",
    11: "Tal como dijo Manami, Kuroneko llevaba bolsas en ambas manos.",
    12: "Puedo ver varios libros tan gruesos como diccionarios metidos dentro.",
    13: "Se ve difícil para Kuroneko cargar todo eso.",
    33: "El Comiket de Verano es esa cosa, ¿verdad? El festival otaku.",
    34: "Dejando eso de lado.",
    35: "Si mal no recuerdo, esto del Comiket de Verano se celebra durante el periodo del Festival de los Faroles.",
    40: "¡Ah, pasé eso por alto!",
    41: "Pero, ahora entiendo más o menos lo que Kuroneko quiere decir.",
    42: "Básicamente, algo como «¡Que comience la Hora Del Apuro!»",
    43: "Incluso la usualmente tranquila y serena Kuroneko está nerviosa en este momento.",
    44: "Por ello, ni siquiera puede dedicar tiempo para charlar.",
    56: "Primero dejé a Manami, que me esperaba para volver a casa, y luego fui al lugar de reunión indicado por Kuroneko.",
    58: "Es verano. Pleno verano. Básicamente, la temporada de emancipación.",
    59: "Parejas liberadas de la etiqueta social se lanzan una sobre otra en público sin reservas.",
    60: "Esa pareja compartiendo conos de helado allá...",
    61: "Y esta pareja entrelazando los brazos aquí a pesar del calor infernal... Ohhohh, ¡está haciendo calor aquí!",
    64: "Encontré a una chica que se parecía a Saori cerca de la fuente.",
    65: "Parecida... Porque su espalda está de cara a mí.",
    66: "Bueno, no puedo creer que una chica tan alta como esa estuviera toda sola, así que probablemente sea Saori.",
    68: "Intenté llamarla.",
    69: "Pero, mi voz se perdió en el ruido. Parecía que no llegó a Saori.",
    70: "Saori miró alrededor del área con inquietud, buscando a Kuroneko.",
    74: "Llamar no funcionó, enviar correos tampoco.",
    75: "Incluso la cara tranquila de Buda solo dura hasta la tercera vez.",
    76: "¡Es imposible que una reunión directa falle!",
    78: "Dije eso mientras le daba una palmada en el hombro a Saori.",
    84: "Saori, mostrando habilidades de sprint increíbles, se deslizó entre los plebeyos y se dirigió hacia la salida del parque.",
    85: "Su figura se hizo gradualmente más y más pequeña...",
    86: "Sin poder hacer nada, solo pude ver su espalda mientras se alejaba.",
    89: "La vi alejarse y decidí volver a casa.",
    90: "Por alguna razón.",
    91: "Tenía el presentimiento de que nunca volvería a ver a Saori si la dejaba escapar ahora.",
    104: "¡Definitivamente no soy uno de esos «Ojos Malignos»!",
    106: "En el caluroso mes de agosto, Kirino, Kuroneko y Saori fueron allá; encontrándose con Ayase por casualidad y exponiendo el lado otaku de Kirino... Fue un",
    107: "tiempo horrible.",
}
a0024_s = {
    1: ("Las vacaciones de verano comienzan mañana, así que todos se van temprano.", "Manami"),
    2: ("Bueno, no hay nadie a quien le guste quedarse el día de la ceremonia de clausura.", "Kyousuke"),
    3: ("Oh. Es cierto.", "Manami"),
    4: ("Entonces, ¿nos vamos a casa también?", "Manami"),
    5: ("Ah, está bien.", "Kyousuke"),
    7: ("¡Kuroneko!", "Kyousuke"),
    8: ("...oh, Kousaka-senpai, Tamura-senpai. Encantada de conocerlos.", "Kuroneko"),
    9: ("Buenas tardes, Gokou-san.", "Manami"),
    10: ("Parece que llevas muchas cosas, pero ¿estás bien? ¿Te ayudo?", "Manami"),
    14: ("No hay necesidad de preocuparse.", "Kuroneko"),
    15: ("Solo los Moradores de las Tinieblas pueden manejar esto...", "Kuroneko"),
    16: ("¿Moradores de las Tinieblas?", "Manami"),
    17: ("¡N-Nada!", "Kyousuke"),
    18: ("Solo me estoy mareando un poco por el calor, ¿verdad, Kuroneko?", "Kyousuke"),
    19: ("...Es inútil hablar con humanos.", "Kuroneko"),
    20: ("¡Ah-Ah-Ah!", "Kyousuke"),
    21: ("¡Manami! Tengo algo que discutir con Kuroneko, así que ¿podrías ir adelante primero?", "Kyousuke"),
    22: ("Está bien. Entendido, Kyou-chan.", "Manami"),
    23: ("...Tú.", "Kyousuke"),
    24: ("No saques tu ojo maligno frente a Manami.", "Kyousuke"),
    25: ("...¿Eso es todo? Entonces, te dejaré atrás.", "Kuroneko"),
    26: ("¡Oye! No hay necesidad de tanta prisa.", "Kyousuke"),
    27: ("Desafortunadamente, estoy ocupada, a diferencia de ti.", "Kuroneko"),
    28: ("También tengo una reunión con Saori más tarde.", "Kuroneko"),
    29: ("¿Una reunión con Saori?", "Kyousuke"),
    30: ("Sí. Necesito absolutamente materiales para mis nuevas publicaciones que saldrán durante el Comiket de Verano. Este equipaje es una parte de dichos materiales.", "Kuroneko"),
    31: ("Así que organicé una reunión con Saori para pedirle prestados algunos folletos de información.", "Kuroneko"),
    32: ("¿Nuevas publicaciones del Comiket de Verano?", "Kyousuke"),
    36: ("No estoy familiarizado con eso, así que podría estar equivocado.", "Kyousuke"),
    37: ("¿Podrás terminar a tiempo si solo empiezas a pedir prestado ahora?", "Kyousuke"),
    38: ("...Hmph.", "Kuroneko"),
    39: ("Por eso dije que estoy ocupada.", "Kuroneko"),
    45: ("Sabes, sobre esos folletos de información...", "Kyousuke"),
    46: ("¿Qué tal si voy a buscarlos por ti?", "Kyousuke"),
    47: ("¿El senpai lo hará?", "Kuroneko"),
    48: ("Estás ocupada con el manuscrito, ¿verdad? De todos modos, estoy libre.", "Kyousuke"),
    49: ("También tengo algo que preguntarle a Saori, ¿ves.", "Kyousuke"),
    50: ("Si consigo los folletos por ti, puedes trabajar en el manuscrito mientras tanto.", "Kyousuke"),
    51: ("...Es verdad que nuestros intereses coinciden.", "Kuroneko"),
    52: ("Sip.", "Kyousuke"),
    53: (".........", "Kuroneko"),
    54: ("Entendido. Por favor, ayúdame con esta transacción.", "Kuroneko"),
    55: ("Por todos los medios, ten cuidado de no verte afectado por el calor del verano.", "Kuroneko"),
    57: ("Aunque sé eso...", "Kyousuke"),
    62: ("¡Son tan envidiables...! ¡Maldición!", "Kyousuke"),
    63: ("Oh... ¿es esa Saori?", "Kyousuke"),
    67: ("¡Oye!", "Kyousuke"),
    71: ("¡Saoriii! ¡Oyeeyy!", "Kyousuke"),
    72: ("¿Kyou-Kyousuke-shi?!", "Saori"),
    73: ("¡Yo! ¡No nos veíamos desde el hospital!", "Kyousuke"),
    77: ("¡Incluso la cara tranquila de Buda solo dura hasta la tercera vez, Saori! ¡Tendrás que decirme qué te preocupa hoy!", "Kyousuke"),
    79: ("Kyousuke-shi...", "Saori"),
    80: ("Estoy muy contenta por este encuentro, pero...", "Saori"),
    81: ("Ya que estoy comprometida con una reunión con Kuroneko-shi, por lo tanto... ¡DORON!", "Saori"),
    82: ("¡Oye! ¡Espera!", "Kyousuke"),
    83: ("¡Nadie esperará cuando se lo pidan!", "Saori"),
    88: ("¡Huir al ver la cara de alguien es la desgracia de un amigo!", "Kyousuke"),
    92: ("¡Saori, espera! ¡No huyas!", "Kyousuke"),
    93: ("¡Aw!!", "Saori"),
    94: ("¡Ay ay ay!!", "Saori"),
    95: ("¡Kyousuke-shi! ¡Duele!", "Saori"),
    96: ("¿Huh? ¿A-Ah, lo siento!", "Kyousuke"),
    97: ("En serio... Agarrarme el brazo de repente...", "Saori"),
    98: ("¿No es el trato de Kyousuke-shi hacia las damas un poco violento?", "Saori"),
    99: ("¡Te dije que lo siento! Pero...", "Kyousuke"),
    100: ("Pero si te perdía de vista aquí, tenía el presentimiento de que no podría verte de nuevo...", "Kyousuke"),
    101: ("Kyousuke-shi...", "Saori"),
    102: ("Así que Kyousuke-shi finalmente contrajo la misma enfermedad que Kuroneko...", "Saori"),
    103: ("¡NO!", "Kyousuke"),
    105: ("¡Ja Ja Ja! Bueno, dejando las bromas de lado...", "Saori"),
}

a0025_n = {
    0: "Ruta de Saori · Contacto En El Parque",
    4: "Se parece a Saori, pero no es Saori!",
    5: "¡Porque no hay lentes giratorios!!",
    7: "Espera, cálmate, Kyousuke.",
    8: "Aunque no lleva los lentes giratorios, tiene la altura, la ropa y la sensación de Saori...?",
    16: "No puedo simplemente soltar:",
    17: "«¡Saori sin lentes es tan hermosa que mi corazón no pudo soportarlo!»",
    18: "...justo en frente de la persona misma.",
}
a0025_s = {
    1: ("¿Sí?", "Saori"),
    2: ("¡Ooooooooooooooh?!", "Kyousuke"),
    3: ("¿P-Puedo saber quién es esta persona?!!", "Kyousuke"),
    6: ("E-Eh, em...", "Saori"),
    9: ("¡¿Podría ser que... eres el doppelganger de Saori?!", "Kyousuke"),
    10: ("Kyo-Kyousuke-san, por favor cálmate. Yo soy... Saori.", "Saori"),
    11: ("*jadeo*", "Kyousuke"),
    12: ("Oh, entonces es Saori.", "Kyousuke"),
    13: ("¡Qué grosero! ¿Qué es esto!", "Saori"),
    14: ("¿Estás diciendo que yo sin los lentes soy una falsa?", "Saori"),
    15: ("No, no es eso... Solo que ha pasado mucho tiempo desde que vi tu rostro real.", "Kyousuke"),
    19: ("Bueno, dejando eso de lado, lo que quiero preguntar es...", "Saori"),
}

a0026_n = {
    0: "Ruta de Saori · Contacto En El Parque",
    2: "Esa es una pregunta terrible.",
    87: "¡Oh! Eso fue peligroso. ¡Casi caigo en el ritmo de Saori!",
    88: "Yendo de aquí para allá, esta persona es realmente buena manipulando la dirección de la conversación.",
    89: "Si no tengo cuidado, el tema podría cambiarse por completo sin que me dé cuenta...",
    90: "¡Tendré que concentrarme y estar atento!",
}
a0026_s = {
    1: ("¿Por qué demonios estás aquí, Kyousuke-shi?", "Saori"),
    3: ("Vine a recoger los materiales en nombre de Kuroneko, que está ocupada con el manuscrito.", "Kyousuke"),
    4: ("Dios mío...", "Saori"),
    5: ("¿Vas por la ruta de Kuroneko-shi esta vez?", "Saori"),
    6: ("¡No lo llames ruta!", "Kyousuke"),
    7: ("¡Y no mezcles la realidad con los juegos!", "Kyousuke"),
    8: ("¡Jajaja! Eso es solo una broma ligera♪", "Saori"),
    9: ("Hoy no haré réplicas innecesarias.", "Kyousuke"),
    10: ("Oh, hoy estás bastante estricto.", "Saori"),
    11: ("Pero sigue siendo divertido ver un lado diferente de Kyousuke-shi.", "Saori"),
    12: ("De todos modos, aquí están los materiales en cuestión.", "Saori"),
    13: ("O-Oh. Gracias.", "Kyousuke"),
    14: ("¿Confirmas la recepción?", "Saori"),
    15: ("Te los pasé, ¿verdad? ¿Está completo el trabajo?", "Saori"),
    16: ("Supongo que sí.", "Kyousuke"),
    17: ("Bueno entonces, ¡eso es todo por mí!", "Saori"),
    18: ("¡¡No huyas!!", "Kyousuke"),
    19: ("¡Jajajajaja! Después de todo no me dejarás escapar tan fácilmente.", "Saori"),
    20: ("Compórtate ya que entiendes eso. El clima ya está bastante caluroso, y no quiero calentar más las cosas.", "Kyousuke"),
    21: ("¡No digas eso; cuanto más cálido, mejor!!", "Saori"),
    22: ("¡Rechazo esa idea!", "Kyousuke"),
    23: ("Bueno, bueno, Kyousuke-shi, cálmate un poco, ¿quieres?", "Saori"),
    24: ("¿De quién crees que es la culpa?", "Kyousuke"),
    25: ("¿Mía?", "Saori"),
    26: ("¡¿Así que lo sabías después de todo?! ¡Chica malvada!", "Kyousuke"),
    27: ("Jeje, cuando reaccionas así, puedo hacer de boke.", "Saori"),
    28: ("Sí, sí... De todos modos, suéltalo. Revela lo que estás ocultando.", "Kyousuke"),
    29: ("Eh, ¿oh...? S-Sí.", "Kyousuke"),
    30: ("¿Hmm???", "Saori"),
    31: ("Ahora. Kyousuke-shi, ¿es realmente todo lo que querías de mí?", "Saori"),
    32: ("Pensé que me ibas a interrogar, por eso me preparé para ello.", "Saori"),
    33: ("Oye, Saori. ¿Por qué estás esquivando mis preguntas?", "Kyousuke"),
    34: ("No he estado esquivando tus preguntas, Kyousuke-shi.", "Saori"),
    35: ("Es solo que tus reacciones son interesantes...", "Saori"),
    36: ("Sin darme cuenta empecé a hacerlo①", "Saori"),
    37: ("Aún estás tratando de esquivar.", "Kyousuke"),
    38: ("Ahora, ahora, ¡no tienes que enojarte!", "Saori"),
    39: ("Aquí están los materiales que querías... ¡Bueno entonces!", "Saori"),
    40: ("S-Sí... Gracias.", "Kyousuke"),
    41: ("...¿Eh?", "Saori"),
    42: ("¿Por qué el «¿eh?»?", "Kyousuke"),
    43: ("Bueno... Hm...", "Saori"),
    44: ("Me sorprende que no preguntaras nada más.", "Saori"),
    45: ("Huh, ¿hablarás de ello?", "Kyousuke"),
    46: ("No hay nada que decir sobre eso; ¿no tienes otro tema del que hablar?", "Saori"),
    47: ("Mentir no te ayuda.", "Kyousuke"),
    48: ("No, ¡estoy siendo seria!", "Saori"),
    49: ("Hay algo realmente, ¿verdad? ¡Lo sé!", "Kyousuke"),
    50: ("¡Tengo todos los artículos otaku como evidencia! Así que, ¡dilo! Te sentirás mejor si lo dices.", "Kyousuke"),
    51: ("Kyo-Kyousuke-shi, estás demasiado cerca...", "Saori"),
    52: ("Kuh... Este interrogatorio persistente; ¡es como si me estuvieran interrogando!", "Saori"),
    53: ("¿En serio...?", "Kyousuke"),
    54: ("Finalmente entiendes. Dios mío...", "Saori"),
    55: ("Mira, Saori...", "Kyousuke"),
    56: ("¡NO! ¡Continúa desde donde lo dejamos!", "Kyousuke"),
    57: ("Em... Desde donde lo dejamos...", "Saori"),
    58: ("Ahora, ¿estaba diciendo algo?", "Saori"),
    59: ("...Tú. ¿De verdad quieres que lo diga?", "Kyousuke"),
    60: ("¡Jeje! ¡Esto es el llamado «presagio»!", "Saori"),
    61: ("Al hacer muchas preguntas detalladas, a veces puede abrirse una nueva ruta...?", "Saori"),
    62: ("¡Oh...! ¡Entonces todo saldrá como se desea!", "Kyousuke"),
    63: ("Pero, ¿no estás en la ruta de Kuroneko-shi ahora mismo?", "Saori"),
    64: ("¡Policía, soy inocente!", "Saori"),
    65: ("¡Entendido! ¡Lo entiendo!", "Kyousuke"),
    66: ("¡Kyousuke-shi...!", "Saori"),
    67: ("Saori, me equivoqué.", "Kyousuke"),
    68: ("En momentos así, los procedimientos son importantes.", "Kyousuke"),
    69: ("¿Procedimientos... dices?", "Saori"),
    70: ("Los procedimientos en este caso particular son...", "Kyousuke"),
    71: ("¡Vamos a comer algo de Katsudon por ahora!", "Kyousuke"),
    72: ("Kyousuke-shi...", "Saori"),
    73: ("Es algo doloroso de decir pero, hay regulaciones contra traer comida a una sala de interrogatorios.", "Saori"),
    74: ("¿¡En serio?!", "Kyousuke"),
    75: ("Sería problemático si el sospechoso comenzara a amotinarse en medio del interrogatorio.", "Saori"),
    76: ("E incluso si permitieran la comida, todos los gastos de entrega serían para el sospechoso...", "Saori"),
    77: ("¡No puedes reproducir una escena dramática de lágrimas en la realidad!", "Saori"),
    78: ("¿¡QUÉÉÉÉÉ?!", "Kyousuke"),
    79: ("O espera, ¿no estás tratando de hacerme hablar rápido?", "Kyousuke"),
    80: ("¡Soy inocente!", "Saori"),
    81: ("Eso...", "Kyousuke"),
    82: ("«¡Objeción!» ¿Es esta una réplica aceptable...?", "Kyousuke"),
    83: ("......", "Saori"),
    84: ("Salirte del personaje de repente es juego sucio, Kyousuke-shi.", "Saori"),
    85: ("Fue mi culpa.", "Kyousuke"),
    86: ("Uu... Es vergonzoso que mi broma fallara así...", "Saori"),
    91: ("Oye Saori, por favor escúchame con atención.", "Kyousuke"),
    92: ("Sí sí, ¿qué es?", "Saori"),
    93: ("¡La semana pasada! ¡Qué! ¿Te pasó?", "Kyousuke"),
    94: ("¿Nada en absoluto?", "Saori"),
    95: ("No digas una mentira tan descarada. Entonces, ¿por qué me pasaste esos artículos?", "Kyousuke"),
    96: ("Para hacer la historia corta...", "Saori"),
    97: ("¿Porque esos artículos reconocieron a Kyousuke-shi como su dueño...?", "Saori"),
    98: ("No, eso no es posible...", "Kyousuke"),
    99: ("¿En serio?", "Kyousuke"),
    100: ("En serio.", "Saori"),
    101: ("¿Realmente en serio?", "Kyousuke"),
    102: ("Realmente en serio, ¡no pasó nada!", "Saori"),
    103: ("Kyousuke-shi, hay una cosa que me gustaría preguntar pero...", "Saori"),
    104: ("¿Por qué te esfuerzas tanto por mí?", "Kyousuke"),
    105: ("...Oye, solo estoy preocupado, sabes...", "Kyousuke"),
    106: ("Gracias por eso, pero...", "Saori"),
    107: ("...estás escondiendo algo, ¿verdad?", "Kyousuke"),
    108: ("Manteniéndolo en secreto, y tratando de manejarlo tú misma.", "Kyousuke"),
    109: ("Me pregunto...", "Saori"),
    110: ("No, eso es. ¡Eso definitivamente es!", "Kyousuke"),
    111: ("Eres una persona muy confiable, así que no eres del tipo que simplemente revela sus propios problemas, ¿verdad?", "Kyousuke"),
    112: ("Por eso sería extraño decirlo, pero...", "Kyousuke"),
    113: ("Estás diferente de lo usual. Puedo decirlo claramente.", "Kyousuke"),
    114: ("...Kyousuke-shi.", "Saori"),
    115: ("Solo tengo una cosa que decirte.", "Saori"),
    116: ("¿Qué es?", "Kyousuke"),
    117: ("No hay ruta de harem con Kuroneko-shi y yo, ¿lo sabes?", "Saori"),
    118: ("¡No estoy apuntando a eso!", "Kyousuke"),
    119: ("Entonces, una ruta de harem con Kiririn-shi, Kuroneko-shi y yo...", "Saori"),
    120: ("Espera un momento. ¿Por qué incluiste a Kirino?", "Kyousuke"),
    121: ("No hay razón especial.", "Saori"),
    122: ("Solo estaba pensando si eso te haría feliz...", "Saori"),
    123: ("¡Es una pesadilla cuando uno de los personajes objetivo es una hermana!", "Kyousuke"),
    124: ("¡Solo estoy puramente preocupado por ti!", "Kyousuke"),
    125: ("...¿Puramente preocupado por mí...?", "Saori"),
    126: ("Sí, eso es.", "Kyousuke"),
    127: ("Pero...", "Saori"),
    128: ("Ya veo... no hay uno...", "Kyousuke"),
    129: ("¡Caramba! ¡¿Qué me estás haciendo decir?!", "Kyousuke"),
    130: ("Jeh... ¡La cara real de Kyousuke-shi...! ¡CAPTURADA!", "Saori"),
    131: ("¡¡T-TÚ!!", "Kyousuke"),
    132: ("¡Deja de cambiar el tema así! ¡Estoy preocupado por ti...", "Kyousuke"),
}

a0029_n = {
    0: "Ruta de Saori · Kyousuke-shi Es Sospechoso",
    12: "Entrevista de matrimonio...",
    13: "Así es. Fuimos a Akihabara después del torneo de Siscaly, y lo soltó sin querer.",
    14: "Esta entrevista de matrimonio, ¿es lo que tenía a Saori ansiosa últimamente?",
    15: "¿Pero qué dijo en ese momento?",
    16: "Se rió como si fuera una broma, ¿verdad?",
    17: "Siento que debería decir algo, pero no puedo pensar en nada apropiado para decir...",
    18: "Saori puede parecer enorme, pero en realidad es más joven que yo.",
    19: "A pesar de eso, vislumbré un mundo que me es desconocido.",
    20: "Seguramente, debe sentirse desanimada.",
    24: "En ese caso, no pongas una sonrisa tan triste...",
    40: "Tuve un pequeño presentimiento sobre esto, pero nunca esperé que incluso Saori terminara pidiendo una consulta de vida...",
    51: "Eso es eso, ¿verdad? ¿El tesoro único en su tipo?",
    52: "Aunque soy un hombre, esas cualidades están haciendo que mi corazón lata más rápido.",
    53: "¿Entonces no correría una mujer directo hacia ello?",
    60: "El honor de los padres, huh...",
    61: "No es un mundo que me sea familiar; para Saori, es un asunto de familia.",
    73: "Si están comprometidos, entonces es un problema entre los dos.",
    74: "No importa cuánto confíe en mí, soy un extraño. No es bueno entrometerme.",
    75: "Esto debería ser un asunto de mutuo acuerdo.",
    87: "Hablando de eso, cuando Saori rechazó mis regalos, se veía realmente abatida.",
    88: "...Seguramente a partir de entonces, sería imposible conseguir más figuras...",
    89: "¿Es eso un resultado de la entrevista de matrimonio?",
    90: "¿Saori llegó a una especie de resolución?",
    100: "Eso es eso, ¿verdad? ¿El tesoro único en su tipo?",
    101: "Aunque soy un hombre, esas cualidades están haciendo que mi corazón lata más rápido.",
    102: "¿Entonces no correría una mujer directo hacia ello?",
    109: "Saori cayó en silencio con un suspiro de dolor.",
    110: "Aquí es donde llegué a una posibilidad.",
    111: "¿Debido a la aparición de su pretendiente matrimonial, Saori lamenta el hecho de que no podrá casarse con quien realmente ama?",
    112: "¿Y por eso, se negó obstinadamente a confiarme esas circunstancias privadas?",
    138: "«Sí», dices... ¿Eso está realmente bien para ti?",
}
a0029_s = {
    1: ("¿Podría ser, Kyousuke-shi...", "Saori"),
    2: ("¿Que me estás dudando?", "Saori"),
    3: ("N-No es tal cosa. Solo estoy preocupado por ti.", "Kyousuke"),
    4: ("¿De verdad piensas que te he estado llamando y esperando en los chats por mera curiosidad...?", "Kyousuke"),
    5: ("¿Reemplazando a alguien en su cita, presentándome en su lugar en el lugar de encuentro?", "Kyousuke"),
    6: ("Sí.", "Saori"),
    7: ("¡¿Una respuesta instantánea?!", "Kyousuke"),
    8: ("No dije que sea malo hacerlo por mera curiosidad. Me siento extremadamente honrada por eso.", "Saori"),
    9: ("Entonces, ¿por qué no me hablas?", "Kyousuke"),
    10: ("¿Aún recuerdas lo que te dije en el maid café en aquel entonces?", "Saori"),
    11: ("Tenía que ir a una entrevista de matrimonio, y...", "Saori"),
    21: ("En ese momento, ¿no dijiste que era solo una «experiencia de vida»?", "Kyousuke"),
    22: ("Pensé que solo sería una experiencia de vida.", "Saori"),
    23: ("Aun así, debería haberlo dicho.", "Saori"),
    25: ("¿Quieres decir que esa entrevista de matrimonio es algo serio...?", "Kyousuke"),
    26: ("Muy, muy seria.", "Saori"),
    27: ("Pero, solo fue una entrevista de matrimonio, ¿verdad?", "Kyousuke"),
    28: ("No es como si tuvieras que sentar cabeza; si terminas rechazándola, se resolverá...", "Kyousuke"),
    29: ("............", "Saori"),
    30: ("Eh, ¿qué pasa con ese silencio?", "Kyousuke"),
    31: ("En realidad...", "Saori"),
    32: ("Tengo que mantener el honor de mis padres, así que... me... voy a comprometer.", "Saori"),
    33: ("...............¿Estás hablando en serio?", "Kyousuke"),
    34: ("Lo digo en serio.", "Saori"),
    35: ("P-Pero, ¿nada está finalizado todavía...?", "Kyousuke"),
    36: ("...Incluso las reservas para la sala de ceremonias ya se han hecho.", "Saori"),
    37: ("¿En serio...?", "Kyousuke"),
    38: ("Kyousuke-shi... Es realmente difícil de decir, pero...", "Saori"),
    39: ("Me gustaría tener esta Consulta de Vida por una vez.", "Saori"),
    41: ("Está bien. Tendrás que explicar esto primero.", "Kyousuke"),
    42: ("En realidad, mi prometido dijo que quería que dejara mi hobby otaku.", "Saori"),
    43: ("Yo también estoy un poco molesta por eso.", "Saori"),
    44: ("Ya veo...", "Kyousuke"),
    45: ("Pero tu familia es bastante adinerada, ¿no?", "Kyousuke"),
    46: ("¿No podrías simplemente rechazar la petición de dejar tu hobby?", "Kyousuke"),
    47: ("La persona de esta entrevista de matrimonio es el hijo de una familia dueña de una gran empresa que cotiza en bolsa.", "Saori"),
    48: ("Le va muy bien en su carrera, es muy educado, y su discurso suena inteligente y encantador...", "Saori"),
    49: ("Además, su ingreso anual futuro sería de decenas de millones.", "Saori"),
    50: ("Guau... ¡Eso no puede ser real...!", "Kyousuke"),
    54: ("Pero él tiene casi 40.", "Saori"),
    55: ("¡Eso es lo que lo descarta todo!", "Kyousuke"),
    56: ("La edad no importa en el amor...", "Saori"),
    57: ("Eso puede ser cierto, pero...", "Kyousuke"),
    58: ("Pero esto es una entrevista de matrimonio, ¿verdad? Cualquier afecto y amor ni siquiera han comenzado.", "Kyousuke"),
    59: ("Aun así, tengo que aceptar por el honor de mis padres.", "Saori"),
    62: ("Me dijo que me deshiciera de todos mis artículos otaku, pero...", "Saori"),
    63: ("De ninguna manera, no pude soportar tirar los tesoros llenos de recuerdos.", "Saori"),
    64: ("¿Por eso, le pasaste esos artículos a Kirino y a mí?", "Kyousuke"),
    65: ("Sí...", "Saori"),
    66: ("Si es Kyousuke-shi y Kiririn-shi, pensé que podría confiarles mis recuerdos.", "Saori"),
    67: ("Sin embargo, realmente lamento haberles causado problemas a ambos.", "Saori"),
    68: ("No, lo hiciste porque confías en nosotros, ¿verdad?", "Kyousuke"),
    69: ("Entonces no se considera una molestia.", "Kyousuke"),
    70: ("...Estoy muy agradecida.", "Saori"),
    71: ("Pero, con respecto al compromiso...", "Kyousuke"),
    72: ("Lo siento, pero no puedo decir nada al respecto.", "Kyousuke"),
    76: ("Pero, incluso después de casarse, rechazar por completo el hobby de tu compañero de vida es algo que no puedo aceptar.", "Kyousuke"),
    77: ("¿Kyousuke-shi...?", "Saori"),
    78: ("Es matrimonio... ¿verdad?", "Kyousuke"),
    79: ("Es completamente diferente de una cita casual.", "Kyousuke"),
    80: ("¿Planeas vivir el resto de tu vida como lo dicte tu esposo?", "Kyousuke"),
    81: ("Eso es...", "Saori"),
    82: ("¡Eso es algo que definitivamente no quiero...!", "Saori"),
    83: ("Entonces está decidido. No debería ser yo quien guarde tus tesoros.", "Kyousuke"),
    84: ("¡Deberías hacer que tu prometido entienda tu hobby otaku!", "Kyousuke"),
    85: ("¿Hmm? Parece que tienes algo que decir?", "Saori"),
    86: ("Bueno, tengo una montaña llena de ellos.", "Kyousuke"),
    91: ("Dijiste, un futuro que nunca se te concederá...", "Kyousuke"),
    92: ("¿Te referías a esto?", "Kyousuke"),
    93: ("Sí, me refería.", "Saori"),
    94: ("Me dijeron que dejara mi hobby otaku por mi pretendiente matrimonial.", "Saori"),
    95: ("Como pensé...", "Kyousuke"),
    96: ("La persona de esta entrevista de matrimonio es el hijo de una familia dueña de una gran empresa que cotiza en bolsa.", "Saori"),
    97: ("Le va muy bien en su carrera, es muy educado, y su discurso suena inteligente y encantador...", "Saori"),
    98: ("Además, su ingreso anual futuro sería de decenas de millones.", "Saori"),
    99: ("Guau... ¡Eso no puede ser real...!", "Kyousuke"),
    103: ("Pero él tiene casi 40.", "Saori"),
    104: ("¡Eso es lo que lo descarta todo!", "Kyousuke"),
    105: ("La edad no importa en el amor...", "Saori"),
    106: ("Eso puede ser cierto, pero...", "Kyousuke"),
    107: ("Pero esto es una entrevista de matrimonio, ¿verdad? Cualquier afecto y amor ni siquiera han comenzado.", "Kyousuke"),
    108: ("Aun así, tengo que aceptar por el honor de mis padres.", "Saori"),
    113: ("¡Bueno, ese tipo de broma es interesante de vez en cuando!", "Saori"),
    114: ("¡Maldición! ¡Eso es como un Romeo y Julieta moderno!", "Kyousuke"),
    115: ("......¿Huh?", "Saori"),
    116: ("Em, ¿Kyousuke-shi...? Es una pregunta abrupta, pero...", "Saori"),
    117: ("Escuchando la conversación, ¿de dónde sacaste ese Romeo y Julieta?", "Saori"),
    118: ("No, no tienes que decir nada, lo entiendo.", "Kyousuke"),
    119: ("Déjalo por mí por ahora. Solo tienes que fallar la entrevista de matrimonio, ¿verdad?", "Kyousuke"),
    120: ("¡Kyou-Kyousuke-shi! ¡Tu voz es demasiado alta!", "Saori"),
    121: ("¿Crees que puedo quedarme callado sobre esto?!", "Kyousuke"),
    122: ("¿Te gusta este pretendiente matrimonial? ¡¿Lo amas?!", "Kyousuke"),
    123: ("Eso es...", "Saori"),
    124: ("Está bien, está decidido. Ahora guíame a la casa de este tipo.", "Kyousuke"),
    125: ("¿Eeeh?!", "Saori"),
    126: ("Pero, Saori. Es matrimonio, ¿verdad?", "Kyousuke"),
    127: ("No es solo salir con alguien.", "Kyousuke"),
    128: ("Esto... es deliberado.", "Saori"),
    129: ("¿Quieres decir que pretendes vivir el resto de tu vida como una criada escuchando las órdenes de su amo?", "Kyousuke"),
    130: ("¿Vas a mentir sobre tus sentimientos y arruinar tu vida por el bien de tus padres?", "Kyousuke"),
    131: ("¿Estás bien con una vida así?!", "Kyousuke"),
    132: ("Yo... ¡No puedo aceptar esas condiciones!", "Saori"),
    133: ("¡Entonces está decidido!", "Kyousuke"),
    134: ("Al final, no puedo aceptar tu tesoro.", "Kyousuke"),
    135: ("¡Él tendrá que entender tu hobby otaku!", "Kyousuke"),
    136: ("¿Planeas vivir el resto de tu vida sellando tu hobby otaku?!", "Kyousuke"),
    137: ("Sí...", "Saori"),
    139: ("¿Puedes realmente renunciar a tu forma de vida tan fácilmente?", "Kyousuke"),
    140: ("¿Es suficiente la aparición de un pretendiente matrimonial para que tires tu hobby otaku?", "Kyousuke"),
    141: ("¿Está bien tirar el detonante detrás del encuentro de Kirino y Kuroneko?!", "Kyousuke"),
    142: ("...", "Saori"),
    143: ("No te limites a seguir en silencio con la cabeza baja.", "Kyousuke"),
    144: ("Pero...", "Saori"),
    145: ("¿No entiendes después de esto?", "Kyousuke"),
    146: ("En ese caso, lo diré directamente.", "Kyousuke"),
    147: ("¡¿EEEH?!", "Saori"),
    148: ("Llévame a la casa de ese pretendiente matrimonial. Ahora mismo.", "Kyousuke"),
    149: ("¡Kyousuke-shi! ¡Esto es demasiado imprudente!", "Saori"),
    150: ("¡Shhh! ¡Hoy, tomé una decisión!", "Kyousuke"),
    151: ("Listos, ¡VAMOS!!", "Kyousuke"),
    152: ("¡QUEEEEEEÉÉ-EEEH", "Saori"),
}

a0030_n = {
    0: "Ruta de Saori · Una Idea Brillante",
    6: "Entonces, ¿por qué estás mirando hacia otro lado?",
    13: "Espera, ¿de repente puso su boca cerca de mi oído...?",
    14: "¡Ah...! ¡E-Eso es...!",
    16: "M-Mi oído se está volviendo cosquilloso...",
    18: "¿Y-Y esta sensación...?",
    20: "¿Esta sensación suave en mi brazo es...?",
    22: "E-Esto es malo... Completamente perforado a través de mi corazón...",
    29: "¡No hagas estas cosas peligrosas! Y págales los sentimientos a los jóvenes que lo malinterpretaron!",
}
a0030_s = {
    1: ("Hacer que entienda mi hobby otaku...", "Saori"),
    2: ("No había pensado en eso antes, pero ¿tienes un plan en mente?", "Saori"),
    3: ("No, no tengo ni idea.", "Kyousuke"),
    4: ("............", "Saori"),
    5: ("Me gusta esa faceta honesta tuya, Kyousuke-shi.", "Saori"),
    7: ("Hmm... hacer que entienda, hacer que entienda, hacer que entienda...", "Saori"),
    8: ("Oh, ohhh, ¿ohhhhhh?!", "Saori"),
    9: ("¿Qué pasa?", "Kyousuke"),
    10: ("Una gran idea de repente destelló en mi mente.", "Saori"),
    11: ("Muy bien, escuchémosla.", "Kyousuke"),
    12: ("¡Entendido!", "Saori"),
    15: ("Primero, necesitaré pedir prestada tu ayuda...", "Saori"),
    17: ("Después, sobre la cosa de Kyousuke-shi, usaré mi buena apariencia...", "Saori"),
    19: ("Y usando estos labios que son puros como un capullo de flor humedecido con el rocío de la mañana...", "Saori"),
    21: ("Y curvando estos dedos largos y esbeltos alrededor...", "Saori"),
    23: ("Besando el cuerpo caliente y excitado...", "Saori"),
    24: ("...Espera, ¿qué clase de cosas estás diciendo?", "Kyousuke"),
    25: ("¿Qué clase...", "Saori"),
    26: ("Estoy inventando un escenario para mostrar mi alma otaku, donde beso mi colección una por una...", "Saori"),
    27: ("¿Hay algún problema?", "Saori"),
    28: ("¡Pensé que estabas leyendo una historia erótica!", "Kyousuke"),
    30: ("De todos modos, ¡lo rechazo! ¡No aceptado!", "Kyousuke"),
    31: ("¿Es así...", "Saori"),
    32: ("En mi opinión, iba por el camino correcto...", "Saori"),
    33: ("Si lo exageras, solo disgustarás a alguien que no sabe nada de otaku.", "Kyousuke"),
    34: ("En lugar de eso, haz algo más apropiado.", "Kyousuke"),
}

data = {
    "000scriptDSAO_0024A.obj": build(a0024_n, a0024_s),
    "000scriptDSAO_0025G.obj": build(a0025_n, a0025_s),
    "000scriptDSAO_0026T.obj": build(a0026_n, a0026_s),
    "000scriptDSAO_0029A.obj": build(a0029_n, a0029_s),
    "000scriptDSAO_0030G.obj": build(a0030_n, a0030_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
