import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a139_n = {
    0: "Sumergido en Expectativas",
    3: "Aunque dije eso, ¿debería realmente continuar de esa manera?",
    4: "¡Pero! No soy yo el culpable.",
    5: "Mantente firme, como debería hacer un hermano mayor.",
    15: "¿Qué pasa con esa chica...",
    16: "Finalmente estoy libre.",
    18: "Aunque siento ganas de tomar un descanso, el tiempo corre.",
    19: "¿Eh? ¿Tiempo?",
    21: "¡Digo, no he preparado nada para el viaje escolar...!",
    23: "Empaqué apropiadamente mis cosas en mi bolsa mientras murmuraba algunos insultos.",
}
a139_s = {
    1: ("...¿Qué es esa actitud? Me estás fastidiando.", "Kirino"),
    2: ("Vamos... Estás siendo demasiado dura con tu propio hermano.", "Kyousuke"),
    6: ("Hmph... Bueno, lo pasaré por alto esta vez.", "Kirino"),
    7: ("Compraré los recuerdos, así que espera obedientemente hasta entonces, ¿okay?", "Kyousuke"),
    8: ("N-No me trates como a una niña...", "Kirino"),
    9: ("Dios, de todos modos...", "Kirino"),
    10: ("¡Trae recuerdos!", "Kirino"),
    11: ("Entendido.", "Kyousuke"),
    12: ("Absolutamente debes hacerlo.", "Kirino"),
    13: ("Dije que entendido.", "Kyousuke"),
    14: ("Te enviaré un correo mañana. Responde de inmediato.", "Kirino"),
    17: ("Ahh, estoy tan cansado.", "Kyousuke"),
    20: ("¡Geeeh! ¡Ya es tan tarde!", "Kyousuke"),
    22: ("Rayos, ¡todo es porque Kirino me interrumpió...!", "Kyousuke"),
    24: ("Whoa... Esto está mal.", "Kyousuke"),
    25: ("Con esto... Voy a tener que quedarme despierto toda la noche... Jajaja...", "Kyousuke"),
}

a140_n = {
    0: "Llegada ★ Ciudad de Kioto",
    2: "Con un fuerte bostezo, entré a la ciudad de Kioto.",
    3: "La antigua capital, Kioto...",
    4: "El sol de esta ciudad alguna vez próspera me picó en mis ojos privados de sueño.",
    6: "Tengo tanto sueño, oh tierra de Kioto.",
    7: "Incluso dentro del tren bala en movimiento, a pesar del insistente pedido de Manami de jugar cartas, simplemente holgazaneé.",
    17: "Parece que no lo entendió... Qué lenta.",
    18: "Al revés está bien, ¡pero es completamente poco masculino que un chico use el hombro de una chica!",
    22: "Como siempre, ella vio a través de mí.",
    23: "Eso es correcto. Ya estoy tan cansado en el primer día del viaje.",
    24: "Todo es por mi hermana que mis preparativos para el viaje tomaron más tiempo.",
    25: "Ya estaba cerca del amanecer cuando me quedé dormido.",
    26: "Aunque estoy en Kioto... parece que no puedo escapar de la maldición de mi hermana.",
    27: "Entrecerré los ojos hacia la vieja ciudad bajo el sol ardiente.",
    29: "-y dejé escapar otro gran bostezo.",
}
a140_s = {
    1: ("*bostezo*", "Kyousuke"),
    5: ("...Sueño...", "Kyousuke"),
    8: ("Kyou-chan... ¿Estás bien?", "Manami"),
    9: ("Sí.", "Kyousuke"),
    10: ("Tu cara se ve horrible.", "Manami"),
    11: ("Oh, ¿en serio...", "Kyousuke"),
    12: ("Tienes unas ojeras serias ahí...", "Manami"),
    13: ("Solo falta de sueño... Bueno, no debería ser un problema ya que dormí en el tren bala, así que no te preocupes.", "Kyousuke"),
    14: ("Estoy preocupada... Cierto, ¿qué tal si te presto mi hombro?", "Manami"),
    15: ("¿Puedes hacer algo tan vergonzoso?", "Kyousuke"),
    16: ("¿Eh?", "Manami"),
    19: ("De todos modos, está bien... *bostezo*...", "Kyousuke"),
    20: ("Estoy segura de que empacaste apurado anoche, ¿verdad? Así fue como te quedaste sin dormir.", "Manami"),
    21: ("Algo así.", "Kyousuke"),
    28: ("*bostezo*", "Kyousuke"),
}

a143_n = {
    0: "Llegada ★ Ciudad de Kioto",
    6: "Por supuesto, habría podido dormir profundamente si usara el regazo de Manami...",
    30: "Bueno, no indagaré más...",
    36: "Ugh... Ella se preocupaba por mí y terminé diciendo algo cruel...",
    43: "Aunque, más que eso, la sonrisa de Manami levantó mucho mi ánimo.",
}
a143_s = {
    1: ("¿Estás bien, Kyou-chan?", "Manami"),
    2: ("Estoy bien... Bien... *bostezo*", "Kyousuke"),
    3: ("Entonces de verdad no dormiste mucho anoche, ¿verdad? Te habría prestado mi regazo como almohada en el tren bala si lo hubieras pedido.", "Manami"),
    4: ("No, mejor no hagas eso.", "Kyousuke"),
    5: ("Pero el viaje escolar está por empezar y tienes sueño...", "Manami"),
    7: ("Además, está escrito en la guía que Kioto es terriblemente caluroso durante el verano.", "Manami"),
    8: (".........", "Kyousuke"),
    9: ("...¿Kyou-chan?", "Manami"),
    10: ("...ZZZZZ", "Kyousuke"),
    11: ("¡Kyou-chan! ¡¿Puedes dormir incluso de pie?!", "Manami"),
    12: ("¡Uwoh! ¡Nada bien, nada bien!", "Kyousuke"),
    13: ("Mira, el sol es intenso. ¡Si te sientes mal en el camino, dímelo!", "Manami"),
    14: ("Sí, gracias.", "Kyousuke"),
    15: ("Traje un poco de dulce de roca, ayuda con la fatiga～", "Manami"),
    16: ("¡Más conocimiento de abuela!", "Kyousuke"),
    17: ("...Es realmente asombroso que sepas esas cosas.", "Kyousuke"),
    18: ("¿Eh? ¿Eh? ¿Es así?", "Manami"),
    19: ("...¿Huh? ¿Qué es eso?", "Kyousuke"),
    20: ("¿Lo dudas? ¡Es verdad! ¡Mi abuela me lo dijo!", "Manami"),
    21: ("Además, traje bolsitas de té para usar en el baño de esta noche.", "Manami"),
    22: ("¿Para qué las trajiste?", "Kyousuke"),
    23: ("¿No sabes? El té rojo tiene componentes humectantes; es genial para la piel que ha sido sobreexpuesta a la luz solar.", "Manami"),
    24: ("Sobre eso... ¿tienes la intención de usarlo en un baño público?", "Kyousuke"),
    25: ("...Es cierto...", "Manami"),
    26: ("Supongo que no puedo usar bolsitas de té cuando todos están aquí～", "Manami"),
    27: ("¡Ese no es el punto! ¡Es el espacio! ¡El baño es demasiado grande!", "Kyousuke"),
    28: ("...¿Usar bolsitas de té en el baño? No lo entiendo.", "Kyousuke"),
    29: ("Ehehe. Estoy bastante bien preparada, ¿no?", "Manami"),
    31: ("De todos modos, no me concierne.", "Kyousuke"),
    32: ("Entonces, Kyou-chan debería usar una bolsita de té.", "Manami"),
    33: ("No tienes que contenerte. No te preocupes por mí～", "Manami"),
    34: ("No hay forma de que tome esto.", "Kyousuke"),
    35: ("«Esto»... Solo quiero que te mejores...", "Manami"),
    37: ("¡E-Entendido! ¡Ya tengo!", "Kyousuke"),
    38: ("¡Ya estoy bien!", "Kyousuke"),
    39: ("¿De verdad?", "Manami"),
    40: ("Sí, en serio. Disfrutemos Kioto.", "Kyousuke"),
    41: ("S-Sin embargo...", "Kyousuke"),
    42: ("No necesitas contenerte～", "Manami"),
    44: ("Quiero que Kyou-chan mejore～", "Manami"),
    45: ("Gracias.", "Kyousuke"),
    46: ("¿Te sientes mejor?", "Manami"),
    47: ("Supongo que sí.", "Kyousuke"),
    48: ("¡Ya estoy bien!", "Kyousuke"),
    49: ("¿De verdad?", "Manami"),
    50: ("Sí, de verdad. Disfrutemos este viaje a Kioto.", "Kyousuke"),
    51: ("¿De verdad? No me estás mintiendo, ¿verdad?", "Manami"),
    52: ("¡No estoy mintiendo!", "Kyousuke"),
    53: ("De todos modos, estoy muy preocupada por Kyou-chan～", "Manami"),
    54: ("¡L-Lo entiendo! ¡Lo entiendo!", "Kyousuke"),
    55: ("¡Ya estoy bien!", "Kyousuke"),
    56: ("¿De verdad?", "Manami"),
    57: ("Sí, de verdad. Así que disfrutemos nuestro viaje.", "Kyousuke"),
    58: ("S-Sí...", "Kyousuke"),
    59: ("Sin embargo, no te ves nada bien...", "Manami"),
    60: ("No tienes que forzarte, ¿sabes?", "Manami"),
    61: ("No estoy... forzándome... a mí mismo... en absoluto.", "Kyousuke"),
    62: ("...Bueno, divirtámonos un poco.", "Kyousuke"),
    63: ("Ah, sí...", "Manami"),
}

a160_n = {
    0: "En la posada",
    2: "Con eso, el primer día del viaje escolar llega a su fin.",
    3: "Finalmente llegamos al hotel en la calle 3.",
    10: "Este tipo es Akagi Kouhei. Es mi compañero de clase y tiene una hermana menor en primer año de nuestra escuela.",
    11: "Así que también es un «hermano mayor».",
    13: "Llevé el equipaje a la habitación y fui al lobby a tomar un descanso.",
}
a160_s = {
    1: ("Finalmente llegamos. ¿Así que esta es la posada donde nos alojamos?", "Kyousuke"),
    4: ("Ah... Estoy agotado. Me duele la cintura después de caminar tanto.", "Kyousuke"),
    5: ("¿Estás bien, Abuelito? Esto es solo el primer día～", "Manami"),
    6: ("Eres ruidosa.", "Kyousuke"),
    7: ("Ah, ambos finalmente regresaron.", "???"),
    8: ("Akagi, tú...", "Kyousuke"),
    9: ("Oh, no tienes que agradecerme.", "Akagi"),
    12: ("Todos nuestros miembros se han reunido ahora, así que entremos a la posada.", "Akagi"),
    14: ("Phew... Estoy mucho más relajado sin mi hermana...", "Kyousuke"),
    15: ("Oye, Kousaka. Todavía hay tiempo antes de que la cena esté lista, ¿quieres echar un vistazo a la posada?", "Akagi"),
    16: ("¡Déjame tomar un descanso primero!", "Kyousuke"),
    17: ("Hey hey, ¡la juventud se va antes de que puedas decirlo!", "Akagi"),
    18: ("Además, hay recuerdos que mi hermana me pidió conseguir.", "Akagi"),
    19: ("¡Ah, yo también!", "Kyousuke"),
    20: ("Tú también, eh.", "Akagi"),
    21: ("Es raro que vengamos aquí, ¿así que vamos a las tiendas juntos?", "Akagi"),
    22: ("No hay problema.", "Kyousuke"),
    23: ("...Recuerdo que Kirino quería un poco de yatsuhashi crudo... y...", "Kyousuke"),
    24: ("Está bien, vamos.", "Kyousuke"),
}

a170_n = {
    0: "Comprando los Regalos, y...",
    3: "Akagi y yo teníamos ambas manos llenas con bolsas de recuerdos.",
    6: "Bien dicho para alguien que es 100 veces más popular.",
    9: "De repente se volvió agresivo. Este bastardo siscon...",
    17: "Un leve aroma de champú flotó desde el cabello de Manami...",
    19: "M-Mi corazón no se saltó un latido ni nada...",
    25: "Regresé aquí justo después de comer...",
    26: "Además, ¿de qué quiere hablar Manami?",
    27: "Algo me pasó por la mente pensando en ello. .",
    28: "«En la noche del viaje»",
    29: "«Un hombre soltero siendo llamado»",
    30: "«por su amiga de la infancia recién salida del baño»",
    31: "¡El baño no tiene nada que ver!",
    32: "¡Está mal! ¡No puedo quitarme la figura de Manami de la cabeza!",
    33: "¡Pero estamos cómodos con nuestros lazos actuales!",
    34: "Ese tipo de cosas...",
    35: "Eso es....",
    38: "¿P-Por qué estoy temblando? ¡Cálmate!",
}
a170_s = {
    1: ("Kousaka, de verdad compraste muchos recuerdos.", "Akagi"),
    2: ("Tú también; no hagas comentarios sobre los demás.", "Kyousuke"),
    4: ("Estos son regalos para mi hermana y sus amigas.", "Kyousuke"),
    5: ("¡Je! ¡Ciertamente eres 【popular】!", "Akagi"),
    7: ("De todos modos, también le compré un regalo a tu hermana.", "Kyousuke"),
    8: ("¿Huh? ¿Qué es eso, Kousaka? ¡No me digas que estás apuntando a mi hermana?!", "Akagi"),
    10: ("Como senpai en el mismo club que ella, al menos tengo que comprarle un recuerdo.", "Kyousuke"),
    11: ("¿Es así? Entonces está bien.", "Akagi"),
    12: ("...Me da escalofríos solo pensar en ti como mi cuñado.", "Akagi"),
    13: ("Igual.", "Kyousuke"),
    14: ("Ah, ¡Kyou-chan!", "Manami"),
    15: ("Oh, Manami, entonces ya te bañaste...", "Kyousuke"),
    16: ("Sí.", "Manami"),
    18: (".........", "Kyousuke"),
    20: ("Cierto, cierto. Tengo algunas cosas de qué hablarte luego; ¿está bien?", "Manami"),
    21: ("...¿Cosas?", "Kyousuke"),
    22: ("Sí. Después de la cena.", "Manami"),
    23: ("S-Sí... Okay...", "Kyousuke"),
    24: ("Te estaré esperando aquí.", "Manami"),
    36: ("Entonces viniste primero, Kyou-chan.", "Manami"),
    37: ("¡Ah! ¡Sí! ¡Es cierto! ¡Hace un momento!", "Kyousuke"),
    39: ("¿Puedes echar un vistazo a esto?", "Manami"),
    40: ("¿Huh? ¿No es esto un amuleto protector...?", "Kyousuke"),
    41: ("Sí. Lo compré en el lugar al que fuimos juntos.", "Manami"),
    42: ("¿Y-Y esto es...?", "Kyousuke"),
    43: ("Deseo darte esto, Kyou-chan.", "Manami"),
    44: ("¿Para mí?", "Kyousuke"),
    45: ("Kyou-chan no parece cuidadoso; puede ser peligroso, ¿sabes?", "Manami"),
    46: ("Estoy bastante preocupada por ti.", "Manami"),
    47: ("Tonta...", "Kyousuke"),
    48: ("¡Incluso si no te preocupas por mí, puedo cuidarme solo!", "Kyousuke"),
    49: ("¿De verdad?", "Manami"),
    50: ("Sí. Me he estado llevando bien con Kirino últimamente también.", "Kyousuke"),
    51: ("Así que quédate tranquila, solo sé la misma de siempre.", "Kyousuke"),
    52: ("...Bueno, gracias por preocuparte de todos modos.", "Kyousuke"),
    53: ("Ehehe, de nada.", "Manami"),
}

a183_n = {
    0: "La Sonrisa de Manami",
    6: "Has estado acomodándote a mi horario; ¿qué tan santurrón eres?",
    11: "Pero, probablemente ha estado esperando hoy.",
    12: "Viendo cómo gastó su guía...",
    13: "¿Qué soy yo comparado con ella?",
    14: "¿Qué puedo hacer por ella?",
    24: "Manami sacó su teléfono celular, acercó su cara a la mía-- Hmf, está demasiado cerca...",
    26: "--Y así, me tomé una foto conmemorativa con Manami.",
    27: "Sin decoración, barata, solo una foto de nuestras caras...",
    28: "Pero aun así, después de ver a Manami tan feliz por ello, me alegra que la hayamos tomado.",
    29: "De verdad, este tipo de cosas «normales» son las que combinan con mi personaje.",
    30: "...N-No. No puedo pensar en nada en absoluto...",
}
a183_s = {
    1: ("Hoy fue divertido～", "Manami"),
    2: ("¿Estás feliz así nomás?", "Kyousuke"),
    3: ("Sí, por supuesto. Muchas gracias, Kyou-chan.", "Manami"),
    4: ("Yo debería ser quien te agradezca.", "Kyousuke"),
    5: ("De verdad me divertí. Así que al menos puedo expresar mi gratitud～", "Manami"),
    7: ("No sé por qué, pero le he tomado cariño a Kioto.", "Manami"),
    8: ("Kioto de verdad te sienta bien.", "Kyousuke"),
    9: ("¿Te refieres a como una geisha aprendiz?", "Manami"),
    10: ("Digo que eres como una anciana.", "Kyousuke"),
    15: ("¿Debería invitarte? Para agradecerte por hoy.", "Kyousuke"),
    16: ("Eh, ¿estás seguro?", "Manami"),
    17: ("Sí, cualquier cosa está bien.", "Kyousuke"),
    18: ("Hmm, entonces....", "Manami"),
    19: ("Tomémonos una foto juntos.", "Manami"),
    20: ("Oye... ¿Estás bien con solo eso?", "Kyousuke"),
    21: ("Sí.", "Manami"),
    22: ("Ya veo. Entendido, tomémosla.", "Kyousuke"),
    23: ("¡Yay! Entonces...", "Manami"),
    25: ("Okay, ¡digamos Cheese!", "Manami"),
    31: ("...P-Perdón por llamarte tan tarde.", "Manami"),
    32: ("No, no es nada...", "Kyousuke"),
    33: ("Necesitaremos despertarnos temprano mañana, así que me voy a la cama.", "Manami"),
    34: ("S-Sí.", "Kyousuke"),
    35: ("¡N-Nos vemos entonces! Buenas noches, Kyou-chan.", "Manami"),
}

a200_n = {
    0: "Carga Cada Vez Mayor",
    1: "...Pasé el segundo y tercer día haciendo las mismas actividades turísticas.",
    2: "La única diferencia era que los recuerdos se iban acumulando día a día.",
    4: "Cuando vuelva a Chiba... significa un estilo de vida con una hermana ruidosa...",
    5: "Regresar a mi vida escolar usual significa días ocupados esperándome con Kuroneko.",
    6: "Cuando regrese, tendré que escuchar las interminables conferencias otaku de Saori otra vez.",
    7: "Una vez que regrese a Chiba, finalmente puedo ver a la amiga de mi hermanita - ¡Lovely My Angel Ayase-tan!",
    8: "Bueno, solo una cosa--",
    10: "Con su cabeza apoyada en mi hombro, Manami murmuraba en su sueño...",
    11: "El tiempo pasado con Manami en este viaje muy bien podría ser irremplazable...",
}
a200_s = {
    3: ("¿Podré... llevar todo eso de vuelta a casa...?", "Kyousuke"),
    9: ("...Kyou-chan...", "Manami"),
    12: ("Así fue como pensé que las cosas irían.", "Kyousuke"),
}

data = {
    "000scriptAKYO_0139A.obj": build(a139_n, a139_s),
    "000scriptAKYO_0140A.obj": build(a140_n, a140_s),
    "000scriptAKYO_0143T.obj": build(a143_n, a143_s),
    "000scriptAKYO_0160A.obj": build(a160_n, a160_s),
    "000scriptAKYO_0170A.obj": build(a170_n, a170_s),
    "000scriptAKYO_0183A.obj": build(a183_n, a183_s),
    "000scriptAKYO_0200A.obj": build(a200_n, a200_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))