import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0050_n = {
    0: "Ruta de Kuroneko · Las Palabras De Las Gafas Remolino",
    11: "No es de extrañar que Kirino no lo entienda, nunca se unió a un círculo para participar antes...",
    23: "Dada la personalidad de Saori, debe ser duro para ella si no puede hacer nada cuando algo le pasa a sus amigas... Comparado con otros, ella",
    24: "realmente valora a sus amigas.",
    25: "Yo mismo, odio cuando todo lo que puedo hacer es mostrar preocupación... Y aun así...",
    26: "No obstante, no puedo pedirle que haga más...",
    37: "Cierto, esa cosa que Kirino mencionó, más vale que también le pregunte a Saori sobre eso.",
    48: "¿Qué pasa con su risa extraña?",
    64: "Como se esperaba de Saori.",
    66: "Esto podría ser una oportunidad para hablar con Kuroneko.",
}
a0050_s = {
    1: ("Bueno entonces, primero que nada...", "Kyousuke"),
    2: ("¡Cuento contigo, Saori!", "Kyousuke"),
    3: ("Así que es sobre la situación de Kuroneko-shi...", "Saori"),
    4: ("Sí, ¿sabes algo al respecto?", "Kyousuke"),
    5: ("Veamos... Escuché que está ocupada trabajando en su manuscrito para el próximo Comiket de Verano.", "Saori"),
    6: ("Y por eso no habrá contacto por un tiempo.", "Saori"),
    7: ("Ya veo, trabajando en su manuscrito para el Comiket de Verano, huh.", "Kyousuke"),
    8: ("Cada año, muchos participantes de círculos pierden el sueño solo para terminar su trabajo a tiempo para este evento.", "Saori"),
    9: ("Seguramente, es la etapa final de los preparativos.", "Saori"),
    10: ("Ya veo...", "Kyousuke"),
    12: ("Sin embargo, después de escucharte, parece que ese no es el caso.", "Saori"),
    13: ("¿Tú también lo piensas?", "Kyousuke"),
    14: ("Sin embargo, eso es casi todo lo que puedo decir por ahora.", "Saori"),
    15: ("También me gustaría ayudar a Kuroneko-shi con su empresa, pero...", "Saori"),
    16: ("Yo también, estoy muy ocupada. Por favor acepta mis más profundas disculpas...", "Saori"),
    17: ("¿Tú también tienes algo que te preocupa?", "Kyousuke"),
    18: ("¡N-No! E-Es solo los llamados 'asuntos familiares'.", "Saori"),
    19: ("Ya veo... entonces, ¿hay algo con lo que pueda ayudar?", "Kyousuke"),
    20: ("Está bien. Por favor ayuda a Kuroneko-shi en su lugar.", "Saori"),
    21: ("Entendido, déjamelo a mí.", "Kyousuke"),
    22: ("Te estoy agradecida, Kyousuke-shi.", "Saori"),
    27: ("No te preocupes por eso. Tienes que ponerte a ti primero.", "Kyousuke"),
    28: ("Me aligera un poco el ánimo escucharte decir eso.", "Saori"),
    29: ("Ahora que lo pienso, ¿no está Kiririn-shi relacionada con este asunto?", "Saori"),
    30: ("Se sentía mal por ser ignorada por Kuroneko.", "Kyousuke"),
    31: ("Para ser honesto, le pedí consejo a Kirino antes de venir contigo.", "Kyousuke"),
    32: ("Prepostero, tú pidiéndole consejo a Kiririn-shi?", "Saori"),
    33: ("Sí, le pregunté si estaba siendo demasiado considerado y ahora Kuroneko piensa que soy asqueroso o algo así.", "Kyousuke"),
    34: ("Pero, por lo que dijo, a Kuroneko no le importa eso en absoluto. Por eso me ordenó resolverlo yo mismo.", "Kyousuke"),
    35: ("Ya veo, ya veo. Lo entiendo.", "Saori"),
    36: ("Entonces, solo hay una conclusión.", "Saori"),
    38: ("Dime, ¿sabes algo sobre Kuroneko y alguna meta importante que pueda tener?", "Kyousuke"),
    39: ("¡Bueno! No realmente...", "Saori"),
    40: ("Ya veo, pensé que sería así...", "Kyousuke"),
    41: ("Kyousuke-shi... ¿Quién te habló sobre esta 'meta importante'?", "Saori"),
    42: ("Fue Kirino...", "Kyousuke"),
    43: ("Ya veo, ya veo. Así que así es.", "Saori"),
    44: ("¿Qué pasa? ¿Sabes algo al respecto?", "Kyousuke"),
    45: ("En absoluto. Solo que, ¿esas palabras se te quedaron en la mente?", "Saori"),
    46: ("S-Sí... bueno, algo así.", "Kyousuke"),
    47: ("Huhuhu...", "Saori"),
    49: ("Estas maduras células cerebrales mías me están diciendo que sería mejor dejar que manejes esta situación tú mismo.", "Saori"),
    50: ("¿Eh?", "Kyousuke"),
    51: ("Visto que no puedo participar en esto, todo lo que puedo hacer es hacer conjeturas a ciegas.", "Saori"),
    52: ("Oh, bueno, supongo que sí...", "Kyousuke"),
    53: ("Entonces quédate como estás y ve a por todas con estilo!", "Saori"),
    54: ("...Estoy segura de que Kuroneko-shi se alegrará si das un paso adelante.", "Saori"),
    55: ("No lo entiendo.", "Kyousuke"),
    56: ("Lo dejaremos aquí por ahora. Hablemos de otra cosa.", "Saori"),
    57: ("Pero en cuanto a Kuroneko...", "Kyousuke"),
    58: ("Ya, ya, quizás estés de acuerdo después de escuchar.", "Saori"),
    59: ("Aunque es verdad que tengo cosas que hacer, le prometí a Kuroneko-shi reunirme con ella mañana.", "Saori"),
    60: ("¿Oh? ¿Para qué?", "Kyousuke"),
    61: ("Vamos a comprar materiales de arte para preparar los doujinshi que se venderán en el Comiket.", "Saori"),
    62: ("«Sería problemático si te quedaras sin ellos más tarde, así que ¿qué tal si vamos juntas?» es lo que le dije.", "Saori"),
    63: ("Ahah...", "Kyousuke"),
    65: ("En ese caso, permíteme ir con ustedes.", "Kyousuke"),
    67: ("Jejeje, pensé que dirías eso.", "Saori"),
    68: ("Entonces...", "Kyousuke"),
    69: ("Sí, nos encantaría que vinieras. ¿Nos vemos en Akihabara mañana entonces?", "Saori"),
    70: ("¡Sí! ¡Muchas gracias!", "Kyousuke"),
    71: ("No lo menciones, crearé la oportunidad para que ustedes dos hablen, así que cuando eso pase...", "Saori"),
    72: ("¡No necesitas decir más! ¡Intentaré sacarle el mayor provecho!", "Kyousuke"),
    73: ("Debes dar lo mejor de ti, Kyousuke-shi, ¡buena fortuna para ti!", "Saori"),
    74: ("...De acuerdo. ¡Mañana es el enfrentamiento!", "Kyousuke"),
}

a0053_n = {
    0: "Ruta de Kuroneko · El Ruido De La Ciudad Cibernética",
    7: "Uwah... claramente se está poniendo nerviosa ahora que estoy aquí...",
    8: "Esto es de esperarse, ya que a la que le dijo «quédate lejos» está ahora justo frente a ella.",
    12: "Oye oye, ¿no está esto volviéndose un poco demasiado obvio?",
    39: "...¿Qué tipo de lengua alienígena están hablando?",
    40: "No puedo seguir su conversación en absoluto...",
    41: "Si esto continúa, parece que no podré cumplir mi objetivo de hablar con Kuroneko... ¿Qué debería hacer?",
    53: "Entonces, ¿está de mal humor después de todo...?",
    54: "Hmm, no puedo descifrarla...",
    59: "Saori... eres tan confiable como siempre.",
    60: "¡No desperdiciaré esta oportunidad que me diste!",
    61: "Ahora es momento de intentar hablar con Kuroneko...",
    72: "N-No puedo continuar la conversación! Mierda... ¿qué debería hacer?",
}
a0053_s = {
    1: ("Bueno, llegué a Akihabara, pero... ¿dónde están?", "Kyousuke"),
    2: ("¡Oh! ¿No es ese Kyousuke-shi?", "Saori"),
    3: ("Oh... ¡Ahh! ¡Q-Qué coincidencia, jajaja!", "Kyousuke"),
    4: ("...¿Huh?", "Kuroneko"),
    5: ("Hola.", "Kyousuke"),
    6: ("¿P-Por qué...", "Kuroneko"),
    9: ("...¿Por qué está senpai aquí, me pregunto?", "Kuroneko"),
    10: ("Ah, en realidad...", "Kyousuke"),
    11: ("¡Qué coincidencia! ¡Esto debe ser un extraño golpe del destino!", "Saori"),
    13: ("Kyousuke-shi, si tienes tiempo, ¿te gustaría acompañarnos a ambas de compras?", "Saori"),
    14: ("Claro, me parece bien, pero...", "Kyousuke"),
    15: ("Eso es genial. ¿Qué tal tú, Kuroneko-shi?", "Saori"),
    16: ("Nos encontramos por coincidencia... E-Entonces no hay más remedio.", "Kuroneko"),
    17: ("¡Así es como debería ser!", "Saori"),
    18: ("...Vamos, no podemos estar perdiendo el tiempo aquí.", "Kuroneko"),
    19: ("¡Entendido!", "Saori"),
    20: ("¡Bueno entonces, vamos!", "Saori"),
    21: ("Aun así, no pensé que aceptaría tan fácilmente.", "Kyousuke"),
    22: ("Huhuhu, estoy segura de que Kuroneko-shi también está secretamente encantada.", "Saori"),
    23: ("¿En serio? No lo creería, a juzgar por su actitud anterior.", "Kyousuke"),
    24: ("No vi nada que indicara lo contrario.", "Saori"),
    25: ("Creo que deberías conseguir un par de gafas nuevas, Saori.", "Kyousuke"),
    26: ("...Aquí estamos.", "Kuroneko"),
    27: ("¿Este lugar vende cosas como materiales de arte?", "Kyousuke"),
    28: ("Qué ignorante, solo cállate y síguenos.", "Kuroneko"),
    29: ("¿No es esta una tienda que trata con electrónica y juegos?", "Kyousuke"),
    30: ("¡Es la mejor tienda en Akiba para herramientas de dibujo digital!", "Saori"),
    31: ("Ah, ya veo...", "Kyousuke"),
    32: ("Voy a entrar.", "Kuroneko"),
    33: ("¡De acuerdo!", "Saori"),
    34: ("¡Ah, espérenme!", "Kyousuke"),
    35: ("Oh, la forma de este lápiz de tableta es bastante única.", "Saori"),
    36: ("Está diseñado pensando en la ergonomía. Incluso si lo usas por un rato, tus manos no se cansarán.", "Kuroneko"),
    37: ("Ya veo, esto se ve como que sería muy útil durante los momentos de trabajo intenso.", "Saori"),
    38: ("Sí. Sin embargo, debes prestar atención al desgaste de la punta del lápiz. Por eso es mejor comprar repuestos también.", "Kuroneko"),
    42: ("Si tienes un presupuesto extra, es mejor comprar también una lámina transparente de protección para la pantalla, para que los trazos del lápiz salgan más bonitos.", "Kuroneko"),
    43: ("Hoho, ya veo. Eso es bastante impresionante. Me enfoco más en los dibujos a mano que en los digitales, así que no sabía mucho sobre eso.", "Saori"),
    44: ("Tengo un profundo respeto por tu vasto conocimiento, ¿no crees, Kyousuke-shi?", "Saori"),
    45: ("¡¿Eh?! Ah, sí, eso es cierto. Es asombroso que sepas tanto.", "Kyousuke"),
    46: ("...Esto es todo meramente conocimiento común.", "Kuroneko"),
    47: ("Ese no es el caso. Eres muy conocedora del uso de herramientas específicas.", "Kyousuke"),
    48: ("Lo que significa que las usas mucho en casa, ¿no?", "Kyousuke"),
    49: ("No, las pruebo en lugares como estos hasta dominarlas.", "Kuroneko"),
    50: ("Y-Ya veo.", "Kyousuke"),
    51: ("Para obtener los mejores resultados, es natural probarlas a fondo.", "Kuroneko"),
    52: ("S-Supongo que sí...", "Kyousuke"),
    55: ("Bueno entonces... Siento que hemos visto suficiente de todo aquí. Es hora de pagar los artículos.", "Saori"),
    56: ("Dime, ya que la caja registradora está un poco concurrida, ¿podrían ustedes dos esperar afuera por un momento?", "Saori"),
    57: ("Entiendo, te lo dejo a ti.", "Kuroneko"),
    58: ("¡Muy agradecida! ¡Bueno entonces!", "Saori"),
    62: ("Vamos.", "Kuroneko"),
    63: ("Ah, sí.", "Kyousuke"),
    64: ("Akihabara está bastante concurrida hoy.", "Kyousuke"),
    65: ("Así es.", "Kuroneko"),
    66: ("Se siente un poco cansado esperar por Saori, sin embargo.", "Kyousuke"),
    67: ("Así es.", "Kuroneko"),
    68: ("Además, parece que Saori aún no viene...", "Kyousuke"),
    69: ("Así es.", "Kuroneko"),
    70: ("......", "Kyousuke"),
    71: ("......", "Kuroneko"),
    73: ("...Mentiste, ¿no?", "Kuroneko"),
    74: ("...¿Eh?", "Kyousuke"),
}

a0055_n = {
    0: "Ruta de Kuroneko · El Ruido De La Ciudad Cibernética",
    14: "Eso es... ¡¿qué tipo de diferencia hace eso?!",
    18: "Por Dios... Hah... Realmente no lo entiendo...",
    42: "...Kirino está contando conmigo, así que no puedo rendirme tan fácilmente.",
    51: "Si Kuroneko no dice nada, no hay manera de que esta conversación continúe... *suspiro*...",
    54: "En resumen, por lo que entiendo actualmente...",
    55: "Kirino tenía razón. Kuroneko no parece odiarme.",
    56: "Pero ¿por qué me evita? Intentaré investigar esto.",
    70: "¿Por qué se siente como si su humor se hubiera vuelto agrio de repente?",
    79: "Entonces... ¿estás completamente bien?",
}
a0055_s = {
    1: ("¿M-Mentí sobre qué?", "Kyousuke"),
    2: ("Sobre aparecer en nuestro punto de encuentro por coincidencia.", "Kuroneko"),
    3: ("...Oh bueno. Entonces lo viste.", "Kyousuke"),
    4: ("Por supuesto, ¿pensaste que no me daría cuenta?", "Kuroneko"),
    5: ("...No, es tal como dijiste, Kuroneko. Esa excusa fue tan mala que me descubrieron al instante.", "Kyousuke"),
    6: ("¿Por qué viniste hoy?", "Kuroneko"),
    7: ("Porque siento que me has estado evitando.", "Kyousuke"),
    8: ("¿Yo? ¿Evitándote?", "Kuroneko"),
    9: ("¿Eh? ¿Por qué lo dijiste en forma de pregunta? ¿No me has estado evitando?", "Kyousuke"),
    10: ("Senpai, no te estoy evitando ni nada parecido.", "Kuroneko"),
    11: ("¿Entonces mi experiencia de ayer fue una ilusión?", "Kyousuke"),
    12: ("No te estoy evitando, solo estoy...", "Kuroneko"),
    13: ("Solo estoy... rechazándote, eso es todo.", "Kuroneko"),
    15: ("...¿Estoy equivocado?", "Kyousuke"),
    16: ("No... En absoluto.", "Kuroneko"),
    17: ("¿Por qué respondiste como si fuera tan difícil?", "Kyousuke"),
    19: ("En fin, si continuamos la conversación así terminaremos dando vueltas en círculos.", "Kyousuke"),
    20: ("Aclararé esto antes de que Saori regrese.", "Kyousuke"),
    21: ("¿Qué es?", "Kuroneko"),
    22: ("¿Por qué... dijiste «No te involucres conmigo»?", "Kyousuke"),
    23: ("Eso, no necesitas saberlo. Todo lo que tienes que hacer es seguir fielmente la misión que te he encomendado.", "Kuroneko"),
    24: ("¿Lo que significa mantenerme callado y hacer lo que me dicen?", "Kyousuke"),
    25: ("Exacto, no te involucres más conmigo... solo tenlo presente.", "Kuroneko"),
    26: ("¿Cómo puedo... No... no importa.", "Kyousuke"),
    27: ("...¿Por qué te detuviste a mitad de camino?", "Kuroneko"),
    28: ("No cambiarás de opinión incluso si te sigo fastidiando, ¿no?", "Kyousuke"),
    29: ("Lo que básicamente significa, que tu corazón está titubeando.", "Kuroneko"),
    30: ("No es eso... No es eso en absoluto... es solo que...", "Kyousuke"),
    31: ("Hmph... parece que te sobreestimé.", "Kuroneko"),
    32: ("No involucrarme contigo... cierto.", "Kyousuke"),
    33: ("Así es.", "Kuroneko"),
    34: ("Hm? Bueno... estaba pensando que eso parecería un poco solitario...", "Kyousuke"),
    35: ("Hay... algo que te preocupa, ¿no?", "Kyousuke"),
    36: ("Pero no hay nada que pueda hacer para ayudar. Me siento inútil como senpai.", "Kyousuke"),
    37: ("......", "Kuroneko"),
    38: ("......¿Así que planeas rendirte?", "Kuroneko"),
    39: ("¿Huh? ¿Qué estás diciendo? ¿No es eso lo que me dijiste? Todo lo que estoy haciendo es respetar tus deseos.", "Kyousuke"),
    40: ("Incluso después de todo eso, ¿por qué suenas tan molesta por ello?", "Kyousuke"),
    41: ("......", "Kuroneko"),
    43: ("......", "Kuroneko"),
    44: ("D-Di algo.", "Kyousuke"),
    45: ("......", "Kuroneko"),
    46: ("............", "Kuroneko"),
    47: ("¡Gaaah! ¡Di algo, no soporto este silencio más!", "Kyousuke"),
    48: ("¿O simplemente me detestas, y no quieres hablarme?", "Kyousuke"),
    49: ("No... No es eso...", "Kuroneko"),
    50: ("*suspiro*... Me rindo. ¿Qué debería hacer con esto...", "Kyousuke"),
    52: ("...Lo siento, no sé qué debería decir en este punto.", "Kuroneko"),
    53: ("Pero, yo... um...", "Kuroneko"),
    57: ("Solo que... yo... um...", "Kuroneko"),
    58: ("...Lo escuché de Saori.", "Kyousuke"),
    59: ("¿Van bien tus preparativos para el Comiket?", "Kyousuke"),
    60: ("...¿Eh?", "Kuroneko"),
    61: ("Me enteré de eso. ¿Los preparativos para el Comiket ya entraron en la fase de trabajo intenso?", "Kyousuke"),
    62: ("...Está bien, ha estado yendo sin problemas.", "Kuroneko"),
    63: ("¿En serio? ¿No estás teniendo ningún problema en absoluto?", "Kyousuke"),
    64: ("Realmente está bien, si hubiera problemas no estaría aquí comprando cosas a un ritmo tranquilo.", "Kuroneko"),
    65: ("Me alegra escucharlo. Pero los doujinshi recientes son realmente impresionantes. Usar este tipo de herramientas digitales para hacerlos...", "Kyousuke"),
    66: ("Hmm... Ya veo, entonces me alegra escucharlo.", "Kyousuke"),
    67: ("......", "Kuroneko"),
    68: ("¿Oh? ¿Qué pasa, te has callado de repente.", "Kyousuke"),
    69: ("...No, no es nada.", "Kuroneko"),
    71: ("Umm... ¿qué tal esto?", "Kyousuke"),
    72: ("...En realidad, no importa, no es nada.", "Kuroneko"),
    73: ("¿Oh en serio...? Olvídalo, no responderás a mi pregunta aunque siga preguntando.", "Kyousuke"),
    74: ("......Así es.", "Kuroneko"),
    75: ("Ya sé. Está bien, es la fase de trabajo intenso para preparar el Comiket, ¿no? Lo escuché de Saori.", "Kyousuke"),
    76: ("...No hay tal cosa.", "Kuroneko"),
    77: ("¿En serio? ¿No la hay?", "Kyousuke"),
    78: ("Realmente está todo bien. Con estas circunstancias, no puedes llamarlo infierno.", "Kuroneko"),
    80: ("Los preparativos para el Comiket van bien. Mientras venga a reponer lo que necesito aquí.", "Kuroneko"),
    81: ("Te refieres a ese lápiz de tableta y a eso ergo-cosa.", "Kyousuke"),
    82: ("......Jeh.", "Kuroneko"),
    83: ("¿Eh, dije algo extraño?", "Kyousuke"),
    84: ("Es mejor recordar con precisión las cosas necesarias a tu alrededor, senpai.", "Kuroneko"),
    85: ("Se llama ergonomía.", "Kuroneko"),
}

a0058_n = {
    0: "Ruta de Kuroneko · El Ruido De La Ciudad Cibernética",
    4: "Guh... Restregándome la sal en la herida...!",
    5: "Aun así, ya no hay vuelta atrás...",
    7: "Oh... S-Salvado...",
    13: "Phew... parece que de alguna manera logré esquivar esa pregunta...",
    25: "¿Oh? ¿No parece que el ambiente ahora está bastante bien?",
    26: "Probablemente podría reconciliarme con Kuroneko si esto continúa...",
    42: "...Me abrí paso entre la multitud persiguiendo a Kuroneko.",
    43: "Pero, terminé perdiéndola...",
}
a0058_s = {
    1: ("Recupérate. ¿No acabo de hablar de esas?", "Kuroneko"),
    2: ("Eres un estudiante preparándose para los exámenes de ingreso y aun así, tu memoria es sorprendentemente mala.", "Kuroneko"),
    3: ("...Además, ¿de verdad tienes tiempo para preocuparte por mí? ¿No necesitas estudiar?", "Kuroneko"),
    6: ("...Bueno, supongo que es inevitable que estés preocupado después de decir eso.", "Kuroneko"),
    8: ("Pero, de verdad eres impresionante. No solo sobre juegos y manga, sino que también sabes de terminología específica.", "Kyousuke"),
    9: ("¿Terminología específica...? ¿Te refieres a la ergonomía?", "Kuroneko"),
    10: ("Tch tch. No te hagas una idea equivocada, Kuroneko. Ahora mismo, mi cabeza está llena de vocabulario en inglés.", "Kyousuke"),
    11: ("Esa es la única razón por la que no recordé esa palabra antes.", "Kyousuke"),
    12: ("Hmph... Bueno, eso está bien entonces.", "Kuroneko"),
    14: ("Pero aun así, poder pronunciar esas palabras difíciles tan impecablemente, seguro que eres increíble.", "Kyousuke"),
    15: ("¿Te refieres a la ergonomía?", "Kuroneko"),
    16: ("Sí sí, esa. ¡Seguro que eres conocedora!", "Kyousuke"),
    17: ("Para poder sacar obras incluso mejores, uno debe tener el conocimiento y también mejores herramientas.", "Kuroneko"),
    18: ("¿No dijiste que querías elegir ese lápiz lo que sea?", "Kyousuke"),
    19: ("Todavía no he llegado a un nivel tan alto.", "Kuroneko"),
    20: ("Por eso quieres esa ergo-cosa.", "Kyousuke"),
    21: ("Así es, por ejemplo, si alguien ejerce demasiada presión al trazar una línea, terminará torcida.", "Kuroneko"),
    22: ("Si haces eso usando un lápiz ergonómico, es más fácil corregir ese tipo de error.", "Kuroneko"),
    23: ("Así que hasta necesitas saber ese tipo de cosas... Impresionante...", "Kyousuke"),
    24: ("...Eso no es verdad.", "Kuroneko"),
    27: ("Al final, las obras creativas no son solo imágenes y palabras.", "Kuroneko"),
    28: ("Para evitar que ocurran problemas inesperados, se debe desfragmentar, optimizar y hacer chequeos frecuentes de errores en el disco duro.", "Kuroneko"),
    29: ("Deshacerse de programas y archivos sin usar mientras se eliminan virus y spyware.", "Kuroneko"),
    30: ("Actualizar el SO así como los drivers, terminales, memorias USB, servidores y demás también deberían respaldarse al menos tres veces.", "Kuroneko"),
    31: ("Aunque no hay una conexión directa con el proceso de creación, aún puede tener un gran impacto.", "Kuroneko"),
    32: ("También hay...", "Kuroneko"),
    33: ("Y-Ya entiendo, es suficiente.", "Kyousuke"),
    34: ("Ni siquiera he explicado la mitad.", "Kuroneko"),
    35: ("No, eso es... jaja. No puedo seguirte el ritmo...", "Kyousuke"),
    36: ("!!", "Kuroneko"),
    37: ("Parece que tendré que informarme sobre eso...", "Kyousuke"),
    38: ("En resumen, compremos las cosas primero. En cualquier caso, Saori es segura que lenta...", "Kyousuke"),
    39: ("Me voy a casa.", "Kuroneko"),
    40: ("¿Huh, oye, Kuroneko?!", "Kyousuke"),
    41: ("¡Espera! ¿Por qué te vas a casa tan de repente?!", "Kyousuke"),
    44: ("¡¿Qué está pasando...?!", "Kyousuke"),
    45: ("Kyousuke-shi, así que estabas aquí. ¿Dónde está Kuroneko-shi?", "Saori"),
    46: ("Bueno, realmente no sé...", "Kyousuke"),
}

a0060_n = {
    0: "Ruta de Kuroneko · El Disgusto Sin Razón",
    4: "Sin embargo, hoy intentamos hablar el uno con el otro por un rato y de eso entendí...",
    5: "Que Kuroneko definitivamente está escondiendo algo.",
    6: "¿Algo... que le está causando preocupación?",
    7: "Tanto Kirino como Saori dijeron que tampoco sabían nada.",
    8: "Kuroneko... ¿por qué no intenta buscar a alguien con quien discutirlo?",
    9: "¿No tiene a Kirino, Saori, y todos esos amigos de la escuela, mucha gente a la que puede pedir apoyo?",
    10: "A pesar de eso, se queda callada y trata de mantener las decisiones importantes para sí misma...",
    12: "Desaparecer sin ninguna explicación... Ciertamente parece algo que ella haría.",
    13: "Bueno, si lo pensó bien y llegó a esa conclusión, está bien pero...",
    15: "Ya he tenido suficiente de este tipo de cosas.",
    16: "Si te preocupa algo, al menos deberías hablar con alguien al respecto.",
    17: "Ayudaría, en todo caso, al menos te haría sentir mejor, ¿no?",
}
a0060_s = {
    1: ("Esa Kuroneko... ¿por qué se enojó de repente...?", "Kyousuke"),
    2: ("¿Fue algo que hice? Pero teníamos un buen ambiente hace un momento...", "Kyousuke"),
    3: ("Simplemente no lo entiendo.", "Kyousuke"),
    11: ("¿Está yendo a algún otro lugar sin avisarnos o algo así?", "Kyousuke"),
    14: ("Solo espero que no vaya a apresurar su decisión sin consultar a nadie, y luego venir a pedir ayuda cuando el hecho esté hecho...", "Kyousuke"),
    18: ("...Después de todo somos amigos.", "Kyousuke"),
}

data = {
    "000scriptCKUR_0050A.obj": build(a0050_n, a0050_s),
    "000scriptCKUR_0053A.obj": build(a0053_n, a0053_s),
    "000scriptCKUR_0055T.obj": build(a0055_n, a0055_s),
    "000scriptCKUR_0058A.obj": build(a0058_n, a0058_s),
    "000scriptCKUR_0060A.obj": build(a0060_n, a0060_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
