import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

n = {
    0: "if · El Capítulo Del Lirio Prohibido",
    2: "Ya no puedo aguantar más.",
    5: "...Mi vida...",
    6: "terminó \(ωoω)/",
    26: "Esto es realmente... Solo puedo dejar escapar un suspiro.",
    27: "Cómo decirlo... esto es agotador.",
    28: "Si Ayase no hubiera logrado calmar la situación cuando Kirino irrumpió de repente, habría sido una escena terrible ahora.",
    30: "Pasando el tiempo sin rumbo, escuchando las voces de Kirino y Ayase a través de la pared, de repente escuché pasos que se dirigían a la puerta principal.",
    31: "Parece que Ayase está a punto de irse.",
    32: "Pensé en despedirla, pero Kirino se enojaría, así que no importa.",
    33: "Mientras tenía pensamientos en esta línea, Kirino entró a la habitación sin siquiera tocar.",
    70: "Parece que ha pensado mucho...",
    71: "Es bueno que no haya cancelado su cita con sus amigas.",
    72: "Sería lo mejor si Kuroneko, Saori y Ayase se llevaran bien entre ellas.",
    75: "Pasaron unos días desde el día en que traje a Ayase a casa de repente y Kirino se enojó.",
    76: "Hoy es el fin de semana.",
    77: "Se supone que Kirino tiene una cita con Kuroneko y Saori.",
    79: "Pero, por alguna razón está sentada en el sofá de casa...",
    80: "Y de mal humor mientras abraza sus rodillas.",
    103: "Kirino hinchó sus mejillas en silencio mientras abrazaba sus rodillas, como si no quisiera continuar hablando.",
    104: "Parece que de verdad la dejaron plantada.",
    112: "No respondió, pero asintió en silencio como respuesta.",
    113: "Muy bien, ahora a volver a mi habitación y llamar a las dos.",
    114: "Volví a la habitación y tomé mi teléfono. Primero, intentaré llamar a Kuroneko.",
    122: "Esta vez, llamaré a Saori.",
    123: "El timbre sonó dos, tres veces, casi entrando al buzón de voz cuando finalmente contestó.",
    130: "¿No solo Kuroneko, sino incluso Saori me colgó?",
    131: "Además, justo cuando mencioné el evento de hoy.",
    133: "Algo debe haber pasado.",
    134: "Y si hay una causa detrás de esto...",
    137: "Cuando regresé a la sala, Kirino todavía estaba sentada en el sofá abrazando sus rodillas.",
    141: "Kirino me lanzó una mirada por un segundo, antes de volver a abrazar sus rodillas.",
    142: "Me senté frente a ella y la miré directamente.",
    143: "Sin embargo, Kirino no me devolvió la mirada.",
    164: "Parece que no tiene sentido preguntar más...",
    165: "El ambiente es desagradable si me quedo aquí con ella, mejor me dirijo de vuelta a mi habitación primero.",
    166: "Incluso si sigo interrogando a Kirino, nada se resolverá.",
    167: "Kuroneko y Saori no me hablarán.",
    169: "Mientras murmuro para mí mismo, pensé en Ayase.",
    170: "Ayase es la amiga cercana de Kirino, así que tal vez sepa lo que está pasando.",
    171: "Por ahora, intentaré contactarla.",
    172: "Abriendo la agenda de mi teléfono, llamé a Ayase.",
    173: "Después de varios timbres, una voz familiar llenó mis oídos.",
    186: "Bueno, debe ser lo de siempre.",
    187: "No puedo caer en esto.",
    195: "Un suspiro pesado vino del otro lado de la llamada telefónica.",
    196: "Con solo esto, puedo decir que algo pasó entre Kirino y ella.",
    205: "Aunque tenía un tono serio, incluso si es reacia, me diría lo que pasó.",
    206: "Qué diablos le habrá pasado...",
    207: "Por ahora, tengo que hablar con Ayase.",
    209: "Ayase ya está aquí mucho antes que yo.",
    210: "Mientras me acercaba, Ayase me notó y bajó la mirada.",
    214: "Nos sentamos lado a lado en el banco del parque, pero ninguno de nosotros dijo una palabra.",
    222: "Ella es excelente en clase y es el centro de ella, a diferencia de mí.",
    223: "Además, aparentemente es la líder del grupo más visible de la clase.",
    224: "Entonces, ¿cómo la excluyeron?",
}
s = {
    1: ("¡Woahhhhhhhhhhhhhhhhh!", "Ambos"),
    3: ("Sinceramente, hacer que use toda esa fuerza... Espera...", "Kirino"),
    4: ("¡T-Tú!!", "Kirino"),
    7: ("...Kirino, ¡perdón!", "Ayase"),
    8: ("¿A-Ayase...?!", "Kirino"),
    9: ("Perdón por la intrusión repentina. Aunque no habíamos acordado reunirnos, quería verte, así que vine.", "Ayase"),
    10: ("Y Onii-san me dijo que te esperara ya que estabas ocupada.", "Ayase"),
    11: ("Perdón, perdón por decir esas cosas.", "Ayase"),
    12: ("Uh, está bien. Oye, Ayase, ¿por casualidad escuchaste lo que estaba haciendo...", "Kirino"),
    13: ("Eh, ¿qué? Perdón. Estaba en una conversación profunda con Onii-san, así que no escuché nada. Sonaba bastante mal, pero como había una pared", "Ayase"),
    14: ("entre nosotros, no pude escucharlo muy bien. De verdad. Sí.", "Ayase"),
    15: ("Pero esta pared no es realmente a prueba de sonido...", "Kirino"),
    16: ("...¿Eh?", "Ayase"),
    17: ("No escuché nada.", "Ayase"),
    18: ("Ah... Está bien.", "Kirino"),
    19: ("Entonces está bien.", "Kirino"),
    20: ("Qué bien. Entonces, ¿vamos a tu habitación?", "Ayase"),
    21: ("Está bien.", "Kirino"),
    22: ("Onii-san, perdón por molestarte.", "Ayase"),
    23: ("Sí. Yo debería disculparme por hacerte esperar.", "Kyousuke"),
    24: ("Está bien.", "Ayase"),
    25: ("Ah... phew.", "Kyousuke"),
    29: ("...Eso fue malo...", "Kyousuke"),
    34: ("¡¡Oye!!!", "Kirino"),
    35: ("...Te enojas incluso sin que muestre mi cara.", "Kyousuke"),
    36: ("¿Por qué la trajiste por tu cuenta?", "Kirino"),
    37: ("No entiendo lo que quieres decir.", "Kyousuke"),
    38: ("¡Es sobre Ayase! ¡¡Ayase!!", "Kirino"),
    39: ("¿Huh? ¿Hay algún problema? Son amigas cercanas.", "Kyousuke"),
    40: ("E-Eso puede ser cierto pero... ¡tengo mis razones!", "Kirino"),
    41: ("¿Qué razones?", "Kyousuke"),
    42: ("¡Justo ahora, justo ahora... Ayase vio todo!!", "Kirino"),
    43: ("No importa si lo ve. Tu verdadera naturaleza ya está expuesta.", "Kyousuke"),
    44: ("Pero Ayase... es diferente.", "Kirino"),
    45: ("¿No es otaku?", "Kyousuke"),
    46: ("Sí. ¡Estaba tratando de que no se enterara!", "Kirino"),
    47: ("Ah, así que es eso... mi culpa.", "Kyousuke"),
    48: ("¡Es toda tu culpa! ¿¡No deberías haberme informado de antemano?!", "Kirino"),
    49: ("¡Lo entiendo! ¡Lo siento!!", "Kyousuke"),
    50: ("A Ayase no pareció importarle, pero ¡argh! ¡Esto me está haciendo enojar! ¡Es toda tu culpa!!", "Kirino"),
    51: ("L-Lo dije, ¡lo entiendo! ¡Seré más cuidadoso la próxima vez!!", "Kyousuke"),
    52: (".........", "Kirino"),
    53: ("¿Qué pasa? ¿Por qué te preocupa tanto eso...?", "Kyousuke"),
    54: ("Voy a salir con Kuroneko y Saori este fin de semana... pero probablemente sea mejor cancelarlo.", "Kirino"),
    55: ("¿Por qué lo harías? Ayase simplemente vino...", "Kyousuke"),
    56: ("Porque Ayase se enteró de alguna manera mientras hablábamos.", "Kirino"),
    57: ("Estás sobre-pensando.", "Kyousuke"),
    58: ("El ánimo se ha arruinado... definitivamente.", "Kirino"),
    59: ("Te preocupas rápido... Aun así, no es bueno cancelar citas con tus otras amigas.", "Kyousuke"),
    60: ("Eso es cierto pero...", "Kirino"),
    61: ("A Ayase no le importó, así que solo mantén esa cita.", "Kyousuke"),
    62: ("Está bien...", "Kirino"),
    63: ("Kuroneko y Saori han estado esperando pasar el rato contigo.", "Kyousuke"),
    64: ("S-Supongo que no hay remedio! ¡Esas dos solas no pueden poner las cosas en marcha.", "Kirino"),
    65: ("Entonces quieres decirlo así. Bueno, da igual.", "Kyousuke"),
    66: ("¿Debería reunirme con Ayase en otro momento?", "Kirino"),
    67: ("Sí. Estará bien si haces arreglos adecuados con ambas partes.", "Kyousuke"),
    68: ("Ah, cierto. Entonces haré una cita con Ayase.", "Kirino"),
    69: ("Sí, sí.", "Kyousuke"),
    73: (".........", "Kirino"),
    74: (".........", "Kyousuke"),
    78: (".........", "Kirino"),
    81: ("Oye. ¿Qué estás haciendo?", "Kyousuke"),
    82: ("¡Cállate! ¡Vete!", "Kirino"),
    83: ("¿Qué te pasa, quieres hablar?", "Kyousuke"),
    84: ("¿Por qué preguntas? No tiene nada que ver contigo.", "Kirino"),
    85: ("Eso no es cierto.", "Kyousuke"),
    86: ("¡Esto no tiene nada que ver contigo!", "Kirino"),
    87: ("¿No tenías una cita con Kuroneko y Saori?", "Kyousuke"),
    88: (".........", "Kirino"),
    89: ("¿Por qué sigues en casa?", "Kyousuke"),
    90: ("¡Dije que no tiene nada que ver contigo!", "Kirino"),
    91: ("¿En serio pensaste que aceptaría eso? Ellas también son mis amigas.", "Kyousuke"),
    92: (".........", "Kirino"),
    93: ("¿Qué pasó?", "Kyousuke"),
    94: ("...No actúes como un hermano.", "Kirino"),
    95: ("Perdón, pero soy más que un hermano. También soy un amigo.", "Kyousuke"),
    96: ("...me dejaron.", "Kirino"),
    97: ("¿Huh?", "Kyousuke"),
    98: ("Me dejaron plantada.", "Kirino"),
    99: ("¿Huh?? ¿Te dejaron plantada? ¡Eso es realmente extraño!", "Kyousuke"),
    100: ("Es verdad. No vinieron a nuestro punto de encuentro, y no contestaron mis llamadas...", "Kirino"),
    101: ("Oye oye, esto no puede ser verdad...", "Kyousuke"),
    102: (".........", "Kirino"),
    105: ("¿Cuando llamaste, no contestaron?", "Kyousuke"),
    106: ("...Sí.", "Kirino"),
    107: ("Entendido. Intentaré llamarlas.", "Kyousuke"),
    108: (".........", "Kirino"),
    109: ("No es desde tu número, así que tal vez contesten.", "Kyousuke"),
    110: ("Espera, dejé mi teléfono en mi habitación. Espera aquí un momento. Voy a hacer la llamada.", "Kyousuke"),
    111: (".........", "Kirino"),
    115: (".........", "Kuroneko"),
    116: ("Hola, ¿eres Kuroneko?", "Kyousuke"),
    117: (".........", "Kuroneko"),
    118: ("Sabes, la cita de hoy con Kirino...", "Kyousuke"),
    119: ("......", "Kuroneko"),
    120: ("H-Hola... ¿Qué demonios pasó...", "Kyousuke"),
    121: ("Si es Saori...", "Kyousuke"),
    124: ("...Kyousuke-shi.", "Saori"),
    125: ("¡Finalmente, finalmente contestaste!", "Kyousuke"),
    126: (".........", "Saori"),
    127: ("Oye, Saori. Sobre hoy...", "Kyousuke"),
    128: (".........", "Saori"),
    129: ("¡Eh! ¡Es-Espera un momento?!", "Kyousuke"),
    132: (".........", "Kyousuke"),
    135: ("Solo puede ser esa persona.", "Kyousuke"),
    136: ("Por ahora, iré a hablar con ella...", "Kyousuke"),
    138: (".........", "Kirino"),
    139: ("Hice las llamadas.", "Kyousuke"),
    140: ("......!", "Kirino"),
    144: ("Llamé tanto a Kuroneko como a Saori.", "Kyousuke"),
    145: ("¿Y...", "Kirino"),
    146: ("Pregunté sobre hoy.", "Kyousuke"),
    147: (".........", "Kirino"),
    148: ("Pero colgaron sin decir una palabra.", "Kyousuke"),
    149: ("Eh...", "Kirino"),
    150: ("¿Hiciste algo?", "Kyousuke"),
    151: ("¡¿Q-Qué quieres decir! ¿¡Estás diciendo que es mi culpa?!", "Kirino"),
    152: ("¿No es un poco extremo que cuelguen sin decir nada?", "Kyousuke"),
    153: ("¡No lo sé! ¡No hice nada!!", "Kirino"),
    154: ("¿De verdad? ¿Las ofendiste mientras chateaban?", "Kyousuke"),
    155: ("Es normal que esa negra se enoje, ¿no?", "Kirino"),
    156: ("Bueno, eso es cierto...", "Kyousuke"),
    157: ("¿Por qué es mi culpa? ¡Yo soy la que fue plantada!", "Kirino"),
    158: ("Incluso Saori tampoco dijo una palabra...", "Kyousuke"),
    159: ("¡No lo sé! ¡No hice nada!", "Kirino"),
    160: (".........", "Kyousuke"),
    161: ("¡Sospechar de tu hermana, eres increíble!", "Kirino"),
    162: ("Huh...", "Kyousuke"),
    163: ("¡Definitivamente no es mi culpa!", "Kirino"),
    168: ("...¿Qué está pasando...", "Kyousuke"),
    174: ("Sí, hola.", "Ayase"),
    175: ("Ah, Ayase. Soy yo, Kyousuke.", "Kyousuke"),
    176: ("Onii-san, ¿qué pasa?", "Ayase"),
    177: ("Bueno, tengo algo sobre Kirino que preguntarte.", "Kyousuke"),
    178: ("¿Kirino...?", "Ayase"),
    179: ("No no, no sospeches de mí. Recientemente, se ha estado comportando de manera extraña.", "Kyousuke"),
    180: ("¿Es... así?", "Ayase"),
    181: ("Sí. Por eso pensé que debería preguntarte.", "Kyousuke"),
    182: ("Entonces es así. Pensé que definitivamente era...", "Ayase"),
    183: ("¿Qué quieres decir con definitivamente?", "Kyousuke"),
    184: ("Nada.", "Ayase"),
    185: ("¿Es así...", "Kyousuke"),
    188: ("Bueno, es sobre Kirino...", "Kyousuke"),
    189: ("Um, ¿Kirino está actualmente en casa?", "Ayase"),
    190: ("Sí, lo está.", "Kyousuke"),
    191: (".........", "Ayase"),
    192: ("¿Hay algo que sea difícil de decir para ti?", "Kyousuke"),
    193: ("Sí.", "Ayase"),
    194: (".........", "Kyousuke"),
    197: ("Entiendo, vamos a otro lugar.", "Kyousuke"),
    198: ("Entonces, ¿podrías venir al parque?", "Ayase"),
    199: ("¿El parque cercano?", "Kyousuke"),
    200: ("Sí, ahí.", "Ayase"),
    201: ("Entendido. Estaré ahí enseguida.", "Kyousuke"),
    202: ("Por favor, hazlo. Nos vemos.", "Ayase"),
    203: ("Sí, nos vemos.", "Kyousuke"),
    204: (".........", "Kyousuke"),
    208: ("Oh...", "Kyousuke"),
    211: ("Gracias por venir especialmente hasta aquí, Onii-san.", "Ayase"),
    212: ("Está bien. Sentémonos primero.", "Kyousuke"),
    213: ("Está bien.", "Ayase"),
    215: ("Oye, sobre Kirino...", "Ayase"),
    216: ("Cierto.", "Kyousuke"),
    217: ("En realidad... recientemente, la están aislando en la escuela...", "Ayase"),
    218: ("¿Huh? ¿Están excluyendo a Kirino?", "Kyousuke"),
    219: ("Sí, así es. Aunque no sé por qué.", "Ayase"),
    220: ("Debes estar bromeando. ¿Cómo la excluirían?", "Kyousuke"),
    221: ("Yo también encuentro eso extraño...", "Ayase"),
    225: ("Pasara lo que pasara, no tengo idea.", "Ayase"),
    226: ("Ya veo...", "Kyousuke"),
    227: ("Aun así, creo en Kirino.", "Ayase"),
    228: ("¡Ayase...!", "Kyousuke"),
    229: ("Pase lo que pase, creeré en Kirino y la protegeré.", "Ayase"),
    230: ("Gracias, Ayase. ¿Puedo confiarte a Kirino durante el horario escolar?", "Kyousuke"),
    231: ("Sí. ¡Déjamelo a mí!", "Ayase"),
    232: ("Kirino definitivamente estará bien si tú estás con ella.", "Kyousuke"),
    233: ("Estoy orgullosa de poder escuchar eso de Onii-san.", "Ayase"),
    234: ("No es nada. Por favor, cuida de Kirino.", "Kyousuke"),
    235: ("Lo haré.", "Ayase"),
    243: (".........", "Kuroneko"),
    244: (".........", "Saori"),
    248: ("¡Está bien! No tiene sentido quedarse en silencio, así que iré directo al grano.", "Kyousuke"),
    249: (".........", "Kuroneko"),
    250: ("¿Qué... es?", "Saori"),
    251: ("¿Qué pasó entre Kirino y ustedes?", "Kyousuke"),
    252: (".........", "Kuroneko"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
entry = current.get("000scriptIYAN_0000E.obj", {})
entry.update(build(n, s))
current["000scriptIYAN_0000E.obj"] = entry
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptIYAN_0000E.obj (part A)")