import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

T = "if · Un Capítulo De Rock"

n = {
    0: T,
    5: "La persona que está detrás de mí cuando me doy la vuelta es el hermano menor de Manami, Rock.",
    6: "Qué puntualidad tan perfecta.",
    7: "O quizás... ¿la peor puntualidad...?",
    19: "Seguramente... Esa discusión de antes puede haber sido un shock para ella.",
    24: "Como era de esperar de los estudiantes de secundaria. Deber, responsabilidad... mientras uses palabras serias, se las tragarán y creerán cualquier cosa. Pero esta es",
    25: "la segunda vez y todavía no se da cuenta. ¿Es estúpido o qué?",
    26: "De todos modos, jugaré mis cartas bien.",
    33: "Entonces, al día siguiente-",
    34: "Esperé a Rock en el camino de vuelta a casa después de la escuela.",
    42: "Después de poner tranquilamente mi mochila en el suelo, puse mi palma frente a los ojos de ese corte de pelo cepillo.",
    43: "Luego agarré su frente y la apreté.",
    49: "Convencido por los ojos llorosos de Rock, solté su cabeza.",
    50: "Al hacerlo, Rock se frotó dolorosamente la cabeza y me miró fijamente.",
    65: "Antes de darme cuenta, solté mi firme agarre de la cabeza de cepillo de Rock y consideré lo que dijo.",
    72: "¿Qué demonios está pasando?",
    73: "Entonces, al día siguiente, Manami no fue a la escuela para la ceremonia de clausura.",
    74: "Se le dijo al maestro de aula que era «Asuntos Familiares».",
    75: "Manami no respondió ninguna de mis llamadas... Cuando finalmente pude reunirme con ella, nos acercábamos a la mitad de las vacaciones de verano.",
    81: "Sí, la Manami que no había visto por un tiempo había cambiado totalmente su apariencia a la de una idol.",
    82: "Sin embargo, no es como si hubiera hecho algo artificial como cirugía plástica... Tenía un rostro naturalmente refinado como si hubiera usado tratamientos de belleza.",
    83: "Pero sobre todo, su silueta corporal cambió visiblemente. Su cintura ahora es perfecta.",
    84: "En comparación con antes, su pecho ahora es más prominente.",
    85: "Francamente hablando, es una belleza.",
    100: "Este Rock tiene el aspecto del vocalista de una banda de heavy metal; francamente, es increíblemente genial.",
    113: "L-La Manami que conozco... no puede ser tan rockera...",
}
s = {
    1: ("Yo... de repente recordé que tengo algo que hacer, así que me voy.", "Manami"),
    2: ("¿Huh? Oye, ¿Manami?", "Kyousuke"),
    3: ("Adiós adiós, Kyou-chan～", "Manami"),
    4: ("¡Ah, es el Bro!", "???"),
    8: ("Oh Rock, eres tú.", "Kyousuke"),
    9: ("¿Qué es eso de «eres tú»?", "Rock"),
    10: ("Exactamente lo que significa.", "Kyousuke"),
    11: ("¿Qué pasa, Bro! Pareces un poco decaído. ¿Pasó algo?", "Rock"),
    12: ("¡Deberías celebrar el fin de la escuela! ¡Ah! ¡Es cierto; qué tal patear una lata en el camino a casa como solíamos hacer! Bro!", "Rock"),
    13: ("Seguro que eres animado... Este nivel de estupidez es bastante digno de elogio.", "Kyousuke"),
    14: ("¿D-De verdad? Me haces sonrojar... Jeje.", "Rock"),
    15: ("Déjalo. No te estoy elogiando realmente. Eso es algo que Manami diría...", "Kyousuke"),
    16: ("Ah, ¿dónde está ella, por cierto? ¿No volvieron juntos?", "Rock"),
    17: ("Nah, dijo que tiene algo que hacer y se fue a otro lugar.", "Kyousuke"),
    18: ("Oh, ¿sí?", "Rock"),
    20: ("Rock.", "Kyousuke"),
    21: ("¿Qué pasa, Bro?", "Rock"),
    22: ("Tengo una tarea importante para ti.", "Kyousuke"),
    23: ("¡¿D-DDe verdad!? ¿Algo interesante?!", "Rock"),
    27: ("Hoy, cuando llegues a casa, ¿revisarás la condición de Manami?", "Kyousuke"),
    28: ("¿Revisar su condición?", "Rock"),
    29: ("Así es. Hay algo que me preocupa... Cuando ella está fuera de mi vista, eres el único en quien puedo confiar. ¿Puedes hacerlo?", "Kyousuke"),
    30: ("¡Cuenta conmigo, Bro! Después de todo, ¡Bro se va a convertir en mi verdadero hermano muy pronto!", "Rock"),
    31: ("Como dije, es más complejo que eso. De todos modos, ¡cuento contigo!", "Kyousuke"),
    32: ("¡Recibido!", "Rock"),
    35: ("Manami faltó a la escuela...", "Kyousuke"),
    36: ("Así que algo malo sí pasó...?", "Kyousuke"),
    37: ("¡Bro!", "Rock"),
    38: ("Oye, Rock, ¿cómo fue?", "Kyousuke"),
    39: ("Ah, mierda, ayer vi ese programa de música en la TV que me gusta, «Okyou de DIVE», así que lo olvidé por completo.", "Rock"),
    40: ("Oh, ya veo, no hay remedio entonces. Rock, ven aquí un segundo.", "Kyousuke"),
    41: ("¿Hm? ¿Para qué?", "Rock"),
    44: ("¡Duele, Bro! ¡Duele! ¡Duele, auche!", "Rock"),
    45: ("Ah, perdón. No pude controlar mi fuerza con una cabeza tan agarrable.", "Kyousuke"),
    46: ("¡Eso es muy cruel, Bro!", "Rock"),
    47: ("¡Siempre tuviste una cabeza tan bien formada!", "Kyousuke"),
    48: ("¡Incluso si me elogias mientras me aprietas la cabeza, no estaré feliz!", "Rock"),
    51: ("E-Era una broma, Bro. La verdad es que sí revisé la condición de Hermana Mayor.", "Rock"),
    52: ("Oh. Deberías haberlo dicho antes.", "Kyousuke"),
    53: ("Pero verás...", "Rock"),
    54: ("¿Hm? ¿Qué pasa? ¿Es algo difícil de decir?", "Kyousuke"),
    55: ("B-Bueno, podrías decir que sí...", "Rock"),
    56: ("Está bien. Solo dímelo directamente.", "Kyousuke"),
    57: ("Parece que Hermana Mayor se va al extranjero de alguna manera...", "Rock"),
    58: ("¿Qué? ¿Van a cerrar la tienda y abrir una nueva en algún país extranjero?", "Kyousuke"),
    59: ("No, no tenemos planes para eso. Más bien, no hay manera de que pudiéramos.", "Rock"),
    60: ("¡Entonces no digas bromas!", "Kyousuke"),
    61: ("¡Duele! ¡Duele, Bro! ¡Por favor, deja de hacer llaves de cabeza!", "Rock"),
    62: ("Ahah, perdón. Lo hice sin pensar.", "Kyousuke"),
    63: ("¡Eso no fue una broma!", "Rock"),
    64: ("...¿En serio?", "Kyousuke"),
    66: ("Escuché a Mamá y Papá hablar de eso ayer. Bro, ¿pasó algo entre tú y Hermana Mayor?", "Rock"),
    67: ("No, nada especial...", "Kyousuke"),
    68: ("Ya veo. Hermana Mayor parecía bien. ¿Quizás no le importan las relaciones a distancia?", "Rock"),
    69: ("¿E-Estaba bien? ¿No estaba deprimida?", "Kyousuke"),
    70: ("Sí, de alguna manera parecía que había tomado una decisión.", "Rock"),
    71: ("¿Tomado una decisión...?", "Kyousuke"),
    76: ("¿T-Tú...?! ¿Manami...?", "Kyousuke"),
    77: ("Sí. Ha pasado un tiempo, Kyou-chan.", "Manami"),
    78: ("Quiero decir, este estilo... Cómo decirlo...", "Kyousuke"),
    79: ("¿Qué pasa con eso?", "Manami"),
    80: ("¡¿No te has vuelto increíblemente linda?!", "Kyousuke"),
    86: ("Por lo que me dijo Kyou-chan, tuve una revelación.", "Manami"),
    87: ("El «yo» actual está mal. Pero volver al «yo» anterior parecía imposible, así que... ¡decidí audazmente apuntar a mi sueño de la infancia!", "Manami"),
    88: ("¡¿Un sueño?! ¿Tenías algo así?", "Kyousuke"),
    89: ("¡Sí! ¿No lo sabías? ¡Mi sueño era convertirme en una idol que cante y baile en la TV, y convertirme en la estrella de la sala de estar de cada hogar!", "Manami"),
    90: ("Esas expresiones... «cantar y bailar», «sala de estar»... apestan a anciana, ¡¿así que realmente ES Manami?!", "Kyousuke"),
    91: ("...No es el momento adecuado para decir eso. E-Entonces... ¿Qué pasa con lo de las citas...", "Kyousuke"),
    92: ("Sí... ¿Terminemos con eso ya?", "Manami"),
    93: ("¡¿Quééé?! ¡¿Manami me rechazó?!", "Kyousuke"),
    94: ("Voy a dejar la escuela y apuntar a mi sueño, así que vine a despedirme.", "Manami"),
    95: ("¿Uh...?", "Kyousuke"),
    96: ("Gracias, Kyou-chan. Gracias a ti, pude encontrar mi propio camino. ¡Esté atento a mí en el futuro!", "Manami"),
    97: ("S-Sí...", "Kyousuke"),
    98: ("¡Broo!", "Rock"),
    99: ("Rock... ¿Y-Tú también?!", "Kyousuke"),
    101: ("Ah, por ahora, planeamos hacer nuestro debut como dúo. Rock toca el shamisen, yo canto.", "Manami"),
    102: ("¡¿Quééééé?!", "Kyousuke"),
    103: ("¡Bastardo! ¡Rock! ¡Sabías esto!", "Kyousuke"),
    104: ("Ah, el cabello es una farsa aunque; ¡planeo hacerlo aún más increíble cuando mi cabello real crezca!", "Rock"),
    105: ("¡¡No pregunté por eso!!", "Kyousuke"),
    106: ("¡Ouchouchouchouch!! Perdón Bro, ¡me rindo! ¡Mis articulaciones no se doblan de esa manera, Bro!", "Rock"),
    107: ("¡Empieza a hablar!", "Kyousuke"),
    108: ("B-Bueno, Hermana Mayor dijo que tuvo una revelación con tu consejo, así que está apuntando a su sueño, y yo también estoy apuntando a ese sueño con ella.", "Rock"),
    109: ("Por eso usamos la primera mitad de las vacaciones de verano para prepararnos.", "Rock"),
    110: ("Ya hemos firmado un contrato con la agencia de Ayase-chan; vamos a hacer nuestro debut el próximo mes.", "Manami"),
    111: ("Ustedes dos...", "Kyousuke"),
    112: ("¡Kyou-chan/Bro, gracias por todo!", "Ambos"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
current["000scriptJROC_0000E.obj"] = build(n, s)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptJROC_0000E.obj")