import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0000_n = {
    0: "Ruta de Saori · Encuentro En Akihabara",
    1: "Dos días después de que terminara el viaje escolar.",
    2: "Fui a Akihabara en mi día libre para darle a Saori unos souvenirs.",
    5: "Lo único que se me ocurría, naturalmente, era algo relacionado con el otaku.",
    6: "Por ejemplo, cosas como, «Este modelo es limitado a uno por persona, así que me gustaría que vinieras conmigo!».",
    7: "O tal vez, «¡Compré una figura de tamaño real, ayúdame a cargarla!»",
    8: "Tiene que ser algo así.",
    13: "¿Qué está planeando? ¿Va a ir a la guerra con esas cosas enormes?",
    19: "Cuando ella da esta sonrisa felina...",
    20: "Definitivamente significa que vamos a ir ahí...",
    24: "La mochila de Saori se ve bastante pesada. Me pregunto qué habrá dentro.",
    25: "...Oh, sí...",
    26: "Oh, cierto, ¡los souvenirs...! Debería dárselos...",
    27: "Eso fue lo que pensé, pero estas cosas que está cargando...",
    28: "Con solo mirarlo, parecía que pesa al menos 2 o 3 kilos...",
    29: "Todavía tenemos lugares a dónde ir. Tal vez debería esperar hasta que nos separemos.",
    44: "¿Qué    estás    diciendo    !?",
    51: "Parece que no es porque no le guste el souvenir...",
    52: "Pero si ese es el caso, no tengo idea de qué está pasando.",
    53: "«Nunca se hará realidad» si lo acepta... ¿qué hay con eso?",
    59: "Saori revolvió su mochila y sacó algo...",
    69: "Maldición... Esta persona se está divirtiendo a mi costa...",
    70: "...Eché un vistazo a otro objeto sobre la mesa.",
    71: "Cada uno de ellos son ediciones limitadas o descatalogados; básicamente son artículos de colección.",
    72: "Esta figura es tan difícil de conseguir que solo la encuentras en subastas...",
    73: "¿¡Y este juego está firmado por la actriz de voz...!?",
    74: "Aparte de eso, hay dos sables de luz sobresaliendo de su mochila...",
    75: "Es como si el par de hojas blancas se extendieran hacia los cielos...",
    76: "...No, espera. He visto esto en algún lugar...",
    77: "¿Qué? ¿No es parte de los premios de trofeo de esa competencia?",
    78: "No, no, eso era solo por los sables.",
    79: "Aun así, no tengo idea de cuáles son las intenciones de Saori, soltando todos estos artículos de colección...",
}
a0000_s = {
    3: ("Me dijo por teléfono que también tenía algo de qué hablar.", "Kyousuke"),
    4: ("¿Qué podría querer hablarme?", "Kyousuke"),
    9: ("¡Oye-! ¿¡Kyousuke-shi～!", "???"),
    10: ("Ah, ¡mis más sinceras disculpas! Los preparativos me tomaron más tiempo del que pensé.", "Saori"),
    11: ("Está bien, acabo de llegar...", "Kyousuke"),
    12: ("...Espera, ¿qué pasa con esas bolsas?", "Kyousuke"),
    14: ("Aquí, dame algunas de esas bolsas, se ven pesadas.", "Kyousuke"),
    15: ("¡No te preocupes, lo tengo bajo control!", "Saori"),
    16: ("Dicho eso, ¿partimos hacia un café o algo así en lugar de quedarnos parados ociosamente?", "Saori"),
    17: ("¿Por café te refieres a...", "Kyousuke"),
    18: ("Jejeje...", "Saori"),
    21: ("...¡Un café de sirvientas, por supuesto!", "Saori"),
    22: ("Bienvenido, Amo y Amante.", "Maid"),
    23: ("Uf... Aquí... vamos...", "Saori"),
    30: ("Aquí tienes, tus souvenirs. Aunque no pude conseguir lo que querías...", "Kyousuke"),
    31: ("¿Qué tal esto! ¡Modelo de robot regional de edición limitada disponible solo en Kioto!", "Kyousuke"),
    32: ("Ah... No está mal...", "Saori"),
    33: ("Este modelo de hecho hace que mi corazón salte! Está rebosante de un aura de la vieja capital, pero...", "Saori"),
    34: ("¿Oh? ¿No te gusta?", "Kyousuke"),
    35: ("¡Para nada! No es eso.", "Saori"),
    36: ("Entonces, ¿qué es?", "Kyousuke"),
    37: ("Estoy más que agradecida por tu buena voluntad, pero no estoy en condiciones de aceptarlo en el momento presente.", "Saori"),
    38: ("¿En el momento presente? Ah, ¿porque vas a ir de compras después, así que aumentará indebidamente tu carga total?", "Kyousuke"),
    39: ("Está bien. Lo guardaré yo hasta que termines de comprar.", "Kyousuke"),
    40: ("No, no es eso...", "Saori"),
    41: ("¿Qué es? Solo dímelo.", "Kyousuke"),
    42: ("...", "Saori"),
    43: ("Si lo acepto, podría 【nunca hacerse realidad】.", "Saori"),
    45: ("¿Qué significa eso siquiera?", "Kyousuke"),
    46: ("Si no te gusta el regalo... deberías decirlo, si fue porque no conseguí lo que pediste.", "Kyousuke"),
    47: ("¡No, eso está lejos de ser el caso!", "Saori"),
    48: ("Tengo el más profundo agradecimiento por tu regalo.", "Saori"),
    49: ("Pero, por ahora no me es posible aceptarlo...", "Saori"),
    50: ("Hmm...", "Kyousuke"),
    54: ("Esto no puede contarse como compensación...", "Saori"),
    55: ("Como reemplazo...", "Saori"),
    56: ("¿¡Qué!? ¡No coloques esas bolsas en la mesa de repente!", "Kyousuke"),
    57: ("Bueno, me ha estado rondando la cabeza desde el principio, pero ¿qué hay dentro?", "Kyousuke"),
    58: ("¡Nada especial! Es solo mi insignificante regalo.", "Saori"),
    60: ("¡E-Esto es...!?", "Kyousuke"),
    61: ("Es como ves, ¡mi humilde colección!", "Saori"),
    62: ("Todos ellos bienes raros y premium...", "Saori"),
    63: ("...Puede que no sea mucho, pero supongo que Kyousuke-shi estaría interesado en ello.", "Saori"),
    64: ("Este desarrollo es demasiado repentino, y no puedo entenderlo. ¿Puedes explicar qué está pasando desde el principio?", "Kyousuke"),
    65: ("Bueno, es así y asá, etcétera...", "Saori"),
    66: ("Ya veo, así que por eso es así y asá...", "Kyousuke"),
    67: ("...Tsk, ¡esto no es un manga o un juego, cómo lo sabría!", "Kyousuke"),
    68: ("¡Jajaja!", "Saori"),
    80: ("¿No es este el premio del torneo de antes? Lo repartimos entre nosotros.", "Kyousuke"),
    81: ("¡Eso es! Una de las mejores piezas de mi colección, llena de recuerdos de ese día.", "Saori"),
    82: ("¿No son todas estas las cosas que más aprecias?", "Kyousuke"),
    83: ("Sí, ciertamente.", "Saori"),
    84: ("No lo digas tan a la ligera.", "Kyousuke"),
    85: ("Si es tan importante, entonces guárdalo apropiadamente, y no se lo des a otros.", "Kyousuke"),
    86: ("...¡Kyousuke-shi!", "Saori"),
    87: ("¿Q-Qué pasa, poniéndote seria de repente...", "Kyousuke"),
    88: ("Es precisamente porque estas son 【cosas realmente valiosas】, que me gustaría que las tuvieras.", "Saori"),
    89: ("...¿Huh?", "Kyousuke"),
    90: ("Espera, no lo entiendo en absoluto.", "Kyousuke"),
    91: ("Bien bien, de todos modos...", "Saori"),
}

a0003_n = {
    0: "Ruta de Saori · Encuentro En Akihabara",
    11: "Lo que dijo Saori tiene algo de sentido.",
    12: "Durante los eventos en los galge, si has dado los regalos correctos a tu objetivo determina si llegarás al final verdadero.",
    27: "Por supuesto que no.",
    39: "¡De repente se está convirtiendo en un desarrollo peligroso!",
    40: "Y hablar de seppuku en estos tiempos...",
    44: "En este maldito periodo pacífico, este tipo de discurso carece de persuasión...",
    50: "¡Qué persona tan agotadora...!",
}
a0003_s = {
    1: ("Bien bien, no hay necesidad de contenerse, a-a-acéptalo!", "Saori"),
    2: ("¡Por favor acepta esta ofrenda!", "Saori"),
    3: ("¡Esto no tiene ningún sentido!", "Kyousuke"),
    4: ("¡¿Hoho!?", "Saori"),
    5: ("¿Honestamente todavía no logras captar el significado de por qué te estoy entregando este regalo...", "Saori"),
    6: ("¡¿Eres una idiota?!", "Kyousuke"),
    7: ("¿¿Kyousuke-shi realmente está diciendo tal cosa?", "Saori"),
    8: ("Eso es exactamente lo que he estado diciendo.", "Kyousuke"),
    9: ("Entonces, mientras esto sea presuntuoso, permíteme incluir una explicación.", "Saori"),
    10: ("Cumpleaños, aniversarios, ceremonias, celebraciones, etc... Es común dar regalos durante tales eventos.", "Saori"),
    13: ("Pero, creo que...", "Saori"),
    14: ("¡Querer dar un regalo de corazón no requiere ninguna razón!", "Saori"),
    15: ("!!", "Kyousuke"),
    16: ("¿Eh, ah...", "Kyousuke"),
    17: ("Fufu.", "Saori"),
    18: ("Parece que Kyousuke-shi está sin palabras bajo la presión de mi impacto.", "Saori"),
    19: ("¡Solo me sorprendí porque es demasiado repentino!", "Kyousuke"),
    20: ("Es solo una broma, ¿verdad? Puedo notar que es un plan para sacar una risa de mi reacción.", "Kyousuke"),
    21: ("¿Qué estás diciendo, Kyousuke-shi! Estoy siendo muy seria, ¿sabes?", "Saori"),
    22: ("En cualquier caso, no lo aceptaré. Absoluta, absolutamente no!", "Kyousuke"),
    23: ("No digas tal cosa...", "Saori"),
    24: ("Estas cosas son semejantes a mi alma... Por todos los medios, quiero que las aceptes!", "Saori"),
    25: ("¡¿Cómo puedo aceptar tu alma!?", "Kyousuke"),
    26: ("Ku... ¡¿no está funcionando incluso después de decir tanto!?", "Saori"),
    28: ("Por favor, aprecia adecuadamente esas cosas tan importantes, ¿de acuerdo?", "Kyousuke"),
    29: ("Uuu... Estoy agradecida de que entiendas el valor de mi alma.", "Saori"),
    30: ("¡Pero es precisamente por eso que quiero que la tengas!", "Saori"),
    31: ("¿Eh...? Um... bueno...", "Kyousuke"),
    32: ("Deja de dudar y solo acéptalo...", "Saori"),
    33: ("¡Vamos... acéptalo rápido y te sentirás mucho mejor!", "Saori"),
    34: ("¡¿Por qué suenas como un policía presionando a un sospechoso para que confiese!?", "Kyousuke"),
    35: ("Si no lo aceptas...", "Saori"),
    36: ("¡Entonces estaré resuelta a cometer seppuku!", "Saori"),
    37: ("¡¿Se-Seppuku!? ¡Espera! ¡Por favor dime la razón primero!", "Kyousuke"),
    38: ("¡Oh! ¡Por fin estás dispuesto a escucharme?", "Saori"),
    41: ("Estoy completamente seria al respecto.", "Saori"),
    42: ("Para probar eso...", "Saori"),
    43: ("El seppuku es un poco exagerado, ¿no...", "Kyousuke"),
    45: ("Cuando era solo una niña, dominé el arte del seppuku.", "Saori"),
    46: ("¡Empezando desde el apéndice, hacer una incisión lateral a la derecha del abdomen!", "Saori"),
    47: ("¡Te cortarás el apéndice! ¿¡Preferirías morir?!", "Kyousuke"),
    48: ("Bueno, es solo una broma.", "Saori"),
    49: ("¡¿Una broma!?", "Kyousuke"),
    51: ("¡Ah! ¡He engañado a un inocente ciudadano otra vez...!", "Saori"),
    52: ("¡Asistente de suicidio! ¡Ven, asistente de suicidio!", "Saori"),
    53: ("¡R-R-R-Relájate, Saori!", "Kyousuke"),
    54: ("El asistente de la tienda está a punto de llamar a la policía.", "Kyousuke"),
    55: ("Si Kyousuke-shi lo hubiera aceptado de antemano, entonces todo estaría resuelto.", "Saori"),
    56: ("Estoy a tu cuidado, Kyousuke-shi.", "Saori"),
    57: ("No estoy seguro de qué decir...", "Kyousuke"),
    58: ("Oh vamos, es triste si no juegas con la broma.", "Saori"),
    59: ("¡¿Toda esa apendicitis era una broma?!", "Kyousuke"),
    60: ("¡Eso es, Kyousuke-shi! ¡Ahora sí estás listo!", "Saori"),
    61: ("...¡Ugh!", "Kyousuke"),
    62: ("¡No estoy jugando!", "Kyousuke"),
    63: ("¡Huh! ¡No no no!", "Saori"),
    64: ("Si digo que lo haré, honestamente lo haré, ¿sabes...?", "Saori"),
    65: ("¡Deja de gritar sobre cometer seppuku!", "Kyousuke"),
    66: ("¡Tch!", "Saori"),
    67: ("¿Q-Qué...?", "Kyousuke"),
    68: ("Muy bien, si no me dejas cortarlo, lo picaré.", "Saori"),
    69: ("¿Huuuh?", "Kyousuke"),
    70: ("De paso, tengo algunos consejos geniales.", "Saori"),
    71: ("Hay una carnicería que vende sándwiches impresionantes cerca de Manseibashi.", "Saori"),
    72: ("Ya que vinimos a Akihabara, ¡probémoslo!", "Saori"),
    73: ("¿No dices nada? ¿No puedes decir nada?", "Saori"),
    74: ("Oye... Kyousuke-shi...", "Saori"),
    75: ("Si no lo aceptas rápido, me rebanaré las entrañas de verdad...?", "Saori"),
    76: ("No jugaré con tu estafa del «me voy a cortar».", "Kyousuke"),
    77: ("¿Todavía no captas mi seriedad...? ¡Kuh!", "Saori"),
}

a0005_n = {
    0: "Ruta de Saori · Es Demasiado Raro",
    4: "Honestamente, no puedo seguirle el ritmo en absoluto.",
    5: "Pero, ¿es realmente buena idea aclarar las cosas?",
    6: "No, un hombre sabio se mantiene alejado del peligro. Vigilaré su reacción.",
    7: "De todos modos",
    12: "Habiendo dicho todo eso, entendí algo.",
    13: "Las acciones de Saori eran demasiado misteriosas...",
    14: "¿Qué es esto! ¿De repente querer que tome estos artículos otaku...? ¿verdad?",
    15: "Bueno entonces, ¿qué debería hacer?",
    16: "Parece que es imposible persuadirla en su condición actual...",
    50: "Tch... No estamos haciendo ningún progreso con esta discusión.",
    51: "¡Ahora que hemos llegado a esto...!",
    65: "Con su dedo índice presionando sus labios, me sonrió.",
    66: "Ese gesto es moe incluso cuando lo hace una chica usando unos enormes lentes giratorios.",
}
a0005_s = {
    1: ("Hmm...", "Kyousuke"),
    2: ("Kyousuke-shi, ¿qué parece estar preocupándote?", "Saori"),
    3: ("No es una preocupación... cómo decirlo...", "Kyousuke"),
    8: ("Estoy realmente contento de que te sientas así, sí, pero...", "Kyousuke"),
    9: ("¿¿De verdad?!", "Saori"),
    10: ("¡Si lo encuentras aceptable, entonces yo también me regocijaré!", "Saori"),
    11: ("¡Espera! Todavía no he aceptado, ¿verdad?", "Kyousuke"),
    17: ("Err, bueno... no sé qué debería decir, pero...", "Kyousuke"),
    18: ("¿Pero?", "Saori"),
    19: ("¡Tengo una cosa que decir!", "Kyousuke"),
    20: ("¡Imposible! ¡Algo que es imposible es imposible!!", "Kyousuke"),
    21: ("¡¿Qué-!? ¡¿Kyousuke-shi!!?", "Saori"),
    22: ("Huff, huff, huff...", "Kyousuke"),
    23: ("¡No ha podido seguirme hasta ahora...!", "Kyousuke"),
    24: ("Kyou-su-ke-shi-", "Saori"),
    25: ("¡¿AAAHHHHH!?", "Kyousuke"),
    26: ("¿De dónde saliste! ¿Eres un monstruo?!", "Kyousuke"),
    27: ("Hmph... ¿subestimaste la probabilidad de un encuentro casual conmigo?", "Saori"),
    28: ("¿Eres un monstruo? ¿Como los monstruos que aparecen en un RPG?", "Kyousuke"),
    29: ("Bien bien, dejemos la broma ahí...", "Saori"),
    30: ("...¿Aun así quieres que lo tome después de todo?", "Kyousuke"),
    31: ("¡Eso es precisamente correcto!", "Saori"),
    32: ("¡Por favor! ¡No puedo confiarle este asunto a nadie más que a ti!", "Saori"),
    33: ("Hmm...", "Kyousuke"),
    34: ("Pero, sabes...", "Kyousuke"),
    35: ("Pero si es realmente tan importante, no deberías simplemente deshacerte de ello.", "Kyousuke"),
    36: ("Entendería si ya no lo necesitaras, pero tu colección es como tu vida, ¿verdad?", "Kyousuke"),
    37: ("No hay razón para que me lo des.", "Kyousuke"),
    38: ("Si pudieras aceptar esta colección como si fuera yo misma y tratarla con gran cuidado...", "Saori"),
    39: ("Sí, piensa en ello como yo, salúdalo todos los días, báñense juntos todos los días...", "Saori"),
    40: ("¡También habría muchos problemas con eso!", "Kyousuke"),
    41: ("¡Jajaja, al contrario, eso sería bienvenido!", "Saori"),
    42: ("¡Incluso si es solo una broma, elige algo menos cuestionable! Tus bromas apestan a acoso sexual de viejo.", "Kyousuke"),
    43: ("¡De todos modos! No habría ningún problema si solo lo aceptaras!", "Saori"),
    44: ("Aquí, aquí, ¡tómalo ya!", "Saori"),
    45: ("No es como si fuera el caramelo dorado de Echigoya, ¿por qué tomaría tal cosa!", "Kyousuke"),
    46: ("¡Tómalo-por-favor!", "Saori"),
    47: ("¡No lo NECESITO!", "Kyousuke"),
    48: ("¡Ah------! ¡¿Por qué-----! ¡El amo está siendo irrazonable!", "Saori"),
    49: ("¡O-Oye! ¡No hagas ruidos raros en público!", "Kyousuke"),
    52: ("Wow, ¿de dónde salió ese Gundam de tamaño real?", "Kyousuke"),
    53: ("¿¡Qué!? ¿Dónde? ¿Dónde está?", "Saori"),
    54: ("¡Ahora o nunca!", "Kyousuke"),
    55: ("Vuelve otra vez, amo☆", "Maid"),
    56: ("¡M-Maldición! ¡Fue un ardid!", "Saori"),
    57: ("¡Kyousuke-shi! ¡Espérame!", "Saori"),
    58: ("Huff, huff, huff...", "Kyousuke"),
    59: ("Huyendo hasta aquí, ni siquiera Saori podrá perseguirme.", "Kyousuke"),
    60: ("Oh bueno, no parece del tipo atlético.", "Kyousuke"),
    61: ("¡No puedes vender al por mayor a un mayorista, Kyousuke-shi!", "Saori"),
    62: ("¡¿Sa-Saori!?", "Kyousuke"),
    63: ("¿¡De dónde saliste siquiera!?", "Kyousuke"),
    64: ("Eso es un secreto comercial①.", "Saori"),
    67: ("Kyousuke-shi, ¿no puedes aceptarlo sin importar qué?", "Saori"),
    68: ("Como he dicho, ¿no se supone que son cosas importantes para ti?", "Kyousuke"),
    69: ("¿Y por qué tuviste que elegirme a mí? ¿No podrían haber sido Kirino o Kuroneko?", "Kyousuke"),
    70: ("Le di a Kiririn-shi una figura por buena voluntad en el pasado, y terminó añadiéndole decoraciones...", "Saori"),
    71: ("Tristemente, me temo que lo mismo podría volver a pasar...", "Saori"),
    72: ("En cuanto a Kuroneko-shi, dice que no hay espacio en su habitación para guardarlo.", "Saori"),
    73: ("Ya veo...", "Kyousuke"),
    74: ("Por eso, tengo la intención de que lo aceptes sin importar qué.", "Saori"),
    75: ("Hmm....", "Kyousuke"),
    76: ("Está bien. Si vas a llegar tan lejos, lo tomaré.", "Kyousuke"),
    77: ("¡¿D-De verdad?!", "Saori"),
    78: ("Sí. Sin embargo, tengo una condición.", "Kyousuke"),
    79: ("Ya que son tus cosas, solo las guardaré por ti. Cuando las necesites de vuelta, puedes venir a buscarlas cuando quieras.", "Kyousuke"),
    80: ("¡A-Agradecimiento dichoso!", "Saori"),
    81: ("Sí, aceptaré tu pasión y tu alma.", "Kyousuke"),
    82: ("¡Jeje! ¡Estoy en deuda contigo!", "Saori"),
    83: ("Ah...", "Kyousuke"),
    84: ("¡No he pagado mi parte del café de sirvientas...!", "Kyousuke"),
    85: ("Me encargué de eso por ti, así que tranquilo.", "Saori"),
    86: ("¿En serio? Lo siento por eso.", "Kyousuke"),
    87: ("¿Es suficiente esta cantidad?", "Kyousuke"),
    88: ("Está bien. Me ayudaste mucho hoy, así que no te preocupes por el dinero.", "Saori"),
    89: ("A cambio, por favor cuida bien de los artículos.", "Saori"),
    90: ("Muy bien, entendido.", "Kyousuke"),
    91: ("Entonces, Kyousuke-shi, nos vemos.", "Saori"),
}

a0007_n = {
    0: "Ruta de Saori · Es Demasiado Raro",
    19: "Una Saori tímida y ligeramente avergonzada... ¿¡N-No es linda!? ¡Mi corazón saltó un latido ahí!",
    20: "Haciéndose la humilde así... ¡Ella tiene un lado lindo!",
    29: "Eso es. No importa cuánto parezca una otaku, sigue siendo una chica delicada de corazón.",
    30: "Como chico, tengo que comportarme como un caballero.",
}
a0007_s = {
    1: ("Oye... ¿Pasó algo?", "Kyousuke"),
    2: ("¿A qué te refieres con 'algo'...?", "Saori"),
    3: ("No respondas una pregunta con otra pregunta. Yo soy el que hace las preguntas aquí.", "Kyousuke"),
    4: ("¿Eh, eso significa...", "Saori"),
    5: ("¿Acabo de levantar una bandera con Kyousuke-shi?", "Saori"),
    6: ("No, eso no pasó.", "Kyousuke"),
    7: ("Ugh... Completamente negado...", "Saori"),
    8: ("Parece que soy una existencia totalmente irrelevante a los ojos de Kyousuke-shi.", "Saori"),
    9: ("Y-Yo no dije eso...", "Kyousuke"),
    10: ("De hecho, pregunté «¿qué pasó?» precisamente porque estaba preocupado.", "Kyousuke"),
    11: ("Eso significa que, tú realmente... sobre mí...", "Saori"),
    12: ("Guardando silencio... Así que eso significa...", "Saori"),
    13: ("¿Apruebas y aceptas?", "Saori"),
    14: ("No no, solo estaba sorprendido y sin palabras.", "Kyousuke"),
    15: ("¡Jajaja! ¡No hay necesidad de ser tímido!", "Saori"),
    16: ("Además...", "Saori"),
    17: ("No me importaría lo más mínimo...", "Saori"),
    18: ("¿Eh...?", "Kyousuke"),
    21: ("Sin embargo, lo siento terriblemente, Kyousuke-shi... No puedo estar involucrada en un affaire en este momento.", "Saori"),
    22: ("¿Eh? ¿De qué estás hablando?", "Kyousuke"),
    23: ("Bueno, sobre la bandera.", "Saori"),
    24: ("Como dije, una falta de etiqueta como levantar una bandera contigo sería...", "Kyousuke"),
    25: ("Ah... pero, si Kyousuke-shi insistes tanto...", "Saori"),
    26: ("Me abstendré respetuosamente de hacer eso.", "Kyousuke"),
    27: ("¡¿Rechazada cortésmente?!", "Saori"),
    28: ("No, no puedo causar un malentendido así a una chica ni siquiera como broma.", "Kyousuke"),
    31: ("Como era de esperarse de Kyousuke-shi... Seguro que sabes cómo tratar a una dama.", "Saori"),
    32: ("Teniendo una hermana así, cualquier otra chica parecería un ángel.", "Kyousuke"),
    33: ("Básicamente, soy como un ángel para Kyousuke-shi.", "Saori"),
    34: ("Era solo un ejemplo.", "Kyousuke"),
    35: ("¡Jajaja! ¡Solo bromeaba!", "Saori"),
    36: ("............", "Kyousuke"),
    37: ("E-Espera, Kyousuke-shi.", "Saori"),
    38: ("¡Di algo sobre mi comentario!", "Saori"),
    39: ("¿Eh? Ah, ah, lo siento.", "Kyousuke"),
    40: ("Escuché algo que no pude entender, así que mi cerebro se congeló.", "Kyousuke"),
    41: ("¡¿Hasta el punto de un colapso mental?!", "Saori"),
    42: ("Aunque, realmente rebosas masculinidad cuando afirmas las cosas.", "Saori"),
    43: ("Aah... ¡Si solo pudiera ser tan valiente como tú!", "Saori"),
    44: ("¡No, no creo que debas seguir mi ejemplo!", "Kyousuke"),
    45: ("Aunque estés vestida así, sigues siendo una chica apropiada.", "Kyousuke"),
    46: ("¿E-Es así?", "Saori"),
    47: ("Pero incluso las chicas pueden fallar en gestionar las banderas. Especialmente...", "Saori"),
    48: ("...las banderas de amistad son difíciles de gestionar.", "Saori"),
    49: ("¿Hm? ¿Qué dijiste?", "Kyousuke"),
    50: ("Nada en absoluto.", "Saori"),
    51: ("Lo que sea, solo respóndeme. ¿Qué te pasa?", "Kyousuke"),
    52: ("¿Lo que sea...?", "Saori"),
    53: ("Eso es lo que acabas de decir, ¿verdad?", "Saori"),
    54: ("S-Sí, ¿y qué?", "Kyousuke"),
    55: ("¿Entonces me estás diciendo «no hay necesidad de que seas valiente»?", "Saori"),
    56: ("Guhh... no es lo que quise decir.", "Kyousuke"),
    57: ("De todos modos, responde mi pregunta primero. Dime con honestidad; ¿qué pasó?", "Kyousuke"),
    58: ("Kyousuke-shi aferrándose a mí y cuestionándome con obstinación...", "Saori"),
    59: ("¿¿Podría ser... algún tipo de conspiración?!", "Saori"),
    60: ("Ah, ¡me rindo! ¡Agitaré la bandera!", "Kyousuke"),
    61: ("¡Jajaja! ¿No estás levantando la bandera blanca un poco demasiado temprano?", "Saori"),
    62: ("Pero no importa cuántas veces preguntes, mi respuesta será «Nada».", "Saori"),
    63: ("......¿Huh?", "Kyousuke"),
    64: ("¡Jejeje! ¡Kyousuke-shi está realmente actuando su edad!", "Saori"),
    65: ("Los chicos en su adolescencia están de hecho muy interesados en el género opuesto.", "Saori"),
    66: ("Yo... mentiría si dijera lo contrario... ¡Pero!", "Kyousuke"),
    67: ("¡No quiero escuchar sobre esas cosas en absoluto ahora!", "Kyousuke"),
    68: ("¡Lo entiendo!", "Saori"),
    69: ("Lo que quieres saber es si tengo novio o no, ¿verdad?", "Saori"),
    70: ("¡NOOOOOOOOO!!!!!!!!!!!", "Kyousuke"),
    71: ("Kyousuke-shi, tengo un consejo para ti.", "Saori"),
    72: ("¿Q-Qué es...?", "Kyousuke"),
    73: ("Cuando estás cortejando a una chica que te gusta, ser demasiado persistente hará que le caigas mal en cambio.", "Saori"),
}

a0008_n = {
    0: "Ruta de Saori · Determinación Hacia Un Futuro Amargo",
    4: "Ah... ¿Quizás fui un poco demasiado lejos?",
    5: "Pero aun así, ¿cómo puedo aceptar esos artículos cuando ni siquiera sé qué está pasando?",
    6: "Maldición, ¡¿qué se supone que debo hacer?!",
    11: "No estoy haciendo ningún progreso...",
    12: "Mientras más intento descubrir la verdad, más siento que estoy atrapado en un profundo pantano.",
    13: "¿A ella no le importa el contenido de esa mochila?",
    14: "¿Qué piensa Saori de los artículos otaku ahora mismo?",
    15: "¿Quizás ya no necesita estos artículos otaku...?",
    16: "No, no... ¡Eso es imposible!",
    17: "Cuando pasó los artículos, la tristeza se elevó en sus ojos, eso no se me escapó.",
}
a0008_s = {
    1: ("Aun así, Kyousuke-shi...", "Saori"),
    2: ("No tienes que hacer un gran espectáculo sobre que te desagrada.", "Saori"),
    3: ("Incluso yo me sentiré un poco herida.", "Saori"),
    7: ("Lo siento, fui un poco demasiado lejos.", "Kyousuke"),
    8: ("Si te sientes mal por eso...", "Saori"),
    9: ("¡Entonces no hay problema si aceptas esos artículos!", "Saori"),
    10: ("Nonono, sí hay un problema.", "Kyousuke"),
    18: ("De todos modos, no puedo tomar tus cosas.", "Kyousuke"),
    19: ("Si ese es el caso, entonces tómalo como un caso en el que te lo presto por ahora.", "Saori"),
    20: ("Oficialmente sigue siendo mi cosa. ¿No tienes problema con eso así?", "Saori"),
    21: ("¿Huh? ¿UOH?!", "Kyousuke"),
    22: ("¡Hazme este favor, Kyousuke-shi!", "Saori"),
    23: ("...Hombre, no hay remedio...", "Kyousuke"),
    24: ("Muy bien, lo cuidaré por ti.", "Kyousuke"),
    25: ("¡JaJa! ¡Agradecimiento dichoso!", "Saori"),
    26: ("Entonces, por favor cuídalo por mí por un tiempo.", "Saori"),
    27: ("¿No es esto algo realmente importante para ti... hasta el punto de que lo llamarías tu alma?", "Kyousuke"),
    28: ("Describirlo como mi alma... Estás exagerando otra vez.", "Saori"),
    29: ("No lo estoy. Esta es tu manera de vivir, tu identidad.", "Kyousuke"),
    30: ("Pasarlo tan fácilmente a otra persona, no sé cuáles son tus segundas intenciones.", "Kyousuke"),
    31: ("No tengo tal cosa. Solo quiero que lo sostengas.", "Saori"),
    32: ("¿No puede ser Kirino o Kuroneko?", "Kyousuke"),
    33: ("Le di a Kiririn-shi una figura por buena voluntad en el pasado, y terminó añadiéndole decoraciones...", "Saori"),
    34: ("Tristemente, me temo que lo mismo podría volver a pasar...", "Saori"),
    35: ("En cuanto a Kuroneko-shi, dice que no hay espacio en su habitación para guardarlo.", "Saori"),
    36: ("Ya veo...", "Kyousuke"),
    37: ("Por eso, tengo la intención de que lo aceptes sin importar qué.", "Saori"),
    38: ("Hmm...", "Kyousuke"),
    39: ("Está bien. Si vas a llegar tan lejos, lo tomaré.", "Kyousuke"),
    40: ("¡¿D-De verdad?!", "Saori"),
    41: ("Sí. Sin embargo, tengo una condición.", "Kyousuke"),
    42: ("Ya que son tus cosas, solo las guardaré por ti. Cuando las necesites de vuelta, puedes venir a buscarlas cuando quieras.", "Kyousuke"),
    43: ("¡A-Agradecimiento dichoso!", "Saori"),
    44: ("Sí, aceptaré tu pasión y tu alma.", "Kyousuke"),
    45: ("¡Jeje! ¡Estoy en deuda contigo!", "Saori"),
    46: ("Ah...", "Kyousuke"),
    47: ("¡No he pagado mi parte del café de sirvientas...!", "Kyousuke"),
    48: ("Me encargué de eso por ti, así que tranquilo.", "Saori"),
    49: ("¿En serio? Lo siento por eso.", "Kyousuke"),
    50: ("¿Es suficiente esta cantidad?", "Kyousuke"),
    51: ("Está bien. Me ayudaste mucho hoy, así que no te preocupes por el dinero.", "Saori"),
    52: ("A cambio, por favor cuida bien de los artículos.", "Saori"),
    53: ("Sip, entendido.", "Kyousuke"),
    54: ("Entonces, Kyousuke-shi, nos vemos.", "Saori"),
}

data = {
    "000scriptDSAO_0000A.obj": build(a0000_n, a0000_s),
    "000scriptDSAO_0003T.obj": build(a0003_n, a0003_s),
    "000scriptDSAO_0005A.obj": build(a0005_n, a0005_s),
    "000scriptDSAO_0007T.obj": build(a0007_n, a0007_s),
    "000scriptDSAO_0008A.obj": build(a0008_n, a0008_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
