import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

T = "Ruta de Kanako"

n = {
    0: T,
    1: "Me empujé el flequillo y me recogí el cabello.",
    4: "Para ser honesto, había asistido a un evento de Meruru como su manager antes.",
    24: "Esta chica... no ha cambiado en nada.",
    29: "Aunque eso es una mentira.",
    36: "Y así...",
    39: "Kanako se mostró en ese magnífico escenario ante todos nosotros.",
    40: "Incluso yo, que no tenía prácticamente ningún interés en un evento de Meruru, me emocioné.",
    42: "Después de que el Comiket de Verano terminara pacíficamente, regresé a mi vida diaria normal.",
    43: "Todavía queda medio mes de vacaciones de verano. Ahora bien, ¿cómo pasaré el tiempo...",
    46: "¿Kanako, eh?",
    48: "Ayase vino a recoger a Kirino temprano en la mañana y se fue a algún lugar con ella.",
    52: "¿Qué asuntos tendrá conmigo?",
    53: "Incliné la cabeza perplejo, pero entonces...",
    56: "¡E-Esta chica...!",
    58: "¡Estoy expuesto...!",
    59: "¿Cómo pasó? Pensé que funcionaría bien ya que esta mocosa es tan estúpida...",
    64: "¿Cómo respondo?",
    65: "La verdad es que Ayase me pidió que fingiera ser un manager.",
    66: "Si le digo la verdad, el hobby de Kirino también quedaría expuesto.",
    67: "Maldición, soy un tonto. ¡¿Por qué le dije mi verdadera identidad en aquel entonces?!",
    70: "...Tiene una mirada de traviesa en el rostro.",
    74: "Gracias a mi egoísta hermana, ya sé más o menos lo que estás tratando de decir.",
    78: "¿Por qué me estás hablando tan casualmente de repente... Espera, ha sido así desde que nos conocimos.",
    80: "No tuve más remedio que aceptar las exigencias de esta mocosa de mal genio.",
    95: "Hablando como una adulta cuando todavía es una niña.",
    98: "\"Señorita\", jaja.",
    108: "No entiendo nada a esta mocosa.",
    115: "...Eso es impresionante. Terminó todo lo que ordenó.",
    116: "...Pero, mi billetera...",
    132: "En serio... Esto se está volviendo realmente problemático.",
}
s = {
    2: ("¿Aah---?!", "Kanako"),
    3: ("¡Manager!", "Kanako"),
    5: ("Finalmente lo recordaste.", "Kyousuke"),
    6: ("¡Recuerdo, recuerdo!", "Kanako"),
    7: ("Pero, ¿huh? Manager, ¿no te despidieron después de que la oficina se enterara de que estabas acosando sexualmente a Kanako?", "Kanako"),
    8: ("¡¿Quién te contó una mentira tan irrespetuosa?!", "Kyousuke"),
    9: ("Ayase.", "Kanako"),
    10: ("A-Ayase～～～～～", "Kyousuke"),
    11: ("...N-No tuve mucha opción. No pude pensar en buenas excusas.", "Ayase"),
    12: ("Aun así...", "Kyousuke"),
    13: ("Sabes...", "Kanako"),
    14: ("¿Por qué no lo discutiste con Kanako en aquel entonces?", "Kanako"),
    15: ("¿Eh?", "Kyousuke"),
    16: ("Entonces pude haberle dicho a todos que el Manager no me acosó sexualmente. Eres tan tonto.", "Kanako"),
    17: ("Tú...", "Kyousuke"),
    18: ("...Es cierto que tocar el trasero de la futura super-idol Kanakana-chan es un crimen digno de muerte, pero no creo que debas ser despedido.", "Kanako"),
    19: ("Oye, deja de hablar como si realmente te hubiera acosado sexualmente.", "Kyousuke"),
    20: ("Soy inocente.", "Kyousuke"),
    21: ("Pero, el trasero de Kanako.", "Kanako"),
    22: ("No lo toqué.", "Kyousuke"),
    23: ("¿De verdad? Bueno, no importa.", "Kanako"),
    25: ("Bueno... De todos modos.", "Kanako"),
    26: ("¿Viniste a ver la actuación en el escenario de Kanako?", "Kanako"),
    27: ("Sí, lo hice.", "Kyousuke"),
    28: ("Después de todo soy tu fan número uno.", "Kyousuke"),
    30: ("...Hmm. ¿No eres leal?", "Kanako"),
    31: ("Bueno entonces, ¿qué tal si te consigo un asiento del personal?", "Kanako"),
    32: ("Oh, ¿está bien eso?", "Kyousuke"),
    33: ("¡Por supuesto! Déjamelo a mí.", "Kanako"),
    34: ("Jeje, ¡anima la actuación en vivo de Kanako!", "Kanako"),
    35: ("¡Está bien! ¡Haz tu mejor esfuerzo!", "Kyousuke"),
    37: ("¡¡Está comenzando la Estrella de Polvo ☆ Bruja Meruru～～♪", "Kanako"),
    38: ("¡Uhyoo! ¡¡Kanakana-chan!! ¡¡Está aaaaaaaquí!!", "Otaku"),
    41: ("Dios... Estoy completamente rodeado de kohais talentosos aquí.", "Kyousuke"),
    44: ("Sí...", "Kyousuke"),
    45: ("Yo.", "Kanako"),
    47: ("Bienvenida. Kirino no está en casa ahora mismo.", "Kyousuke"),
    49: ("Ehehe, eso lo sé.", "Kanako"),
    50: ("Verás, no vine a encontrarme con Kirino hoy, sino con el Onii-san de Kirino.", "Kanako"),
    51: ("¿Eh? ¿Conmigo?", "Kyousuke"),
    54: ("Nos volvemos a encontrar～. ¡Manager-san♪", "Kanako"),
    55: ("¿Geh...?", "Kyousuke"),
    57: ("Jaja, así que es eso, justo como pensé.", "Kanako"),
    60: ("Oye... ¿Qué... es todo esto? Jeje.", "Kanako"),
    61: ("H-Hay... muchas razones detrás de esto.", "Kyousuke"),
    62: ("¿Por qué el hermano de Kirino y mi manager son la misma persona?", "Kanako"),
    63: ("Guh...", "Kyousuke"),
    68: ("Hmm, así que hay alguna razón detrás de esto.", "Kanako"),
    69: ("Jeje, no estoy realmente interesada en las circunstancias del Manager detrás de esto～, así que podría simplemente olvidar todo al respecto～", "Kanako"),
    71: ("Pero... ¿No deberías hacer algo a cambio?", "Kanako"),
    72: ("...Entiendo. ¿Qué quieres que haga?", "Kyousuke"),
    73: ("Eres perspicaz, ¿no?", "Kanako"),
    75: ("Primero, dime tu nombre.", "Kanako"),
    76: ("Kyousuke. Kousaka Kyousuke.", "Kyousuke"),
    77: ("Entonces, Kyousuke. Vamos a comer. Tú pagas, por supuesto.", "Kanako"),
    79: ("Sí, sí. Entendido.", "Kyousuke"),
    81: ("Veamos... Kanako quiere un set de hamburguesa, un parfait de frutas, dango de arroz...", "Kanako"),
    82: ("¡Eso es suficiente! Eso es demasiado, gordita.", "Kyousuke"),
    83: ("¡¿Huh?! ¡¿Qué fue lo que dijiste?!", "Kanako"),
    84: ("Es una cantidad ridícula para ordenar. ¿No tienes nada de moderación? Por eso tu estómago está tan fofo.", "Kyousuke"),
    85: ("...¡No me digas fofa!", "Kanako"),
    86: ("Oye, ¿te das cuenta... de qué tipo de posición estás?", "Kanako"),
    87: ("Lo hago. Por eso te estoy invitando a comer así. Sé agradecida.", "Kyousuke"),
    88: ("No es eso...", "Kanako"),
    89: ("¿Qué es?", "Kyousuke"),
    90: ("No fue fácil para Kanako engañarte, así que... quiero que seas más... ¿cómo lo digo?", "Kanako"),
    91: ("Quiero que me atiendas apropiadamente como un anfitrión.", "Kanako"),
    92: ("Esa es una petición bastante grande.", "Kyousuke"),
    93: ("Eres la primera persona que conozco, aparte de mi hermana, tan directa al expresar sus deseos.", "Kyousuke"),
    94: ("Bueno, Kanako quiere un chico que escuche todo lo que ella diga.", "Kanako"),
    96: ("Ya que estás acompañando a una dama, por favor cuida tus palabras.", "Kanako"),
    97: ("Pfft.", "Kyousuke"),
    99: ("¡¿Q-Qué te da risa!", "Kanako"),
    100: ("No, no, no me estoy riendo. No me estoy riendo en absoluto.", "Kyousuke"),
    101: ("¡Mentiroso! ¡Definitivamente te reíste! ¡Ves! ¡Todavía estás riéndote!!", "Kanako"),
    102: ("Jaja, Kanako-sama es tan linda.", "Kyousuke"),
    103: ("¡N-No me trates como a una niña!", "Kanako"),
    104: ("Te estoy tratando como mi ama. Después de todo, soy el anfitrión designado de Kanako-sama.", "Kyousuke"),
    105: ("¡¿Qué clase de anfitrión tiene esa actitud?!", "Kanako"),
    106: ("Maldición～, ¿qué te pasa? Ya sea un manager o un anfitrión ahora, sigo siendo de un estatus más alto que tú, ¿no?!", "Kanako"),
    107: ("Por eso estoy siguiendo tus órdenes. ¿De qué estás tan insatisfecha?", "Kyousuke"),
    109: ("Grr...", "Kanako"),
    110: ("Ah, Dios, ¡ahora estoy enojada! ¡Quiero una soda de helado adicional y cheesecake!", "Kanako"),
    111: ("...Eso no es 'enojo', sino 'hambre', ¿no?", "Kyousuke"),
    112: ("¡Prepárate! ¡Voy a vaciar tu billetera!", "Kanako"),
    113: ("...*suspiro*", "Kyousuke"),
    114: ("Phew～, estoy llena.", "Kanako"),
    117: ("Gracias por la comida♪ Kyousuke-san①", "Kanako"),
    118: ("...Comiste como un fantasma hambriento.", "Kyousuke"),
    119: ("¡¿Es algo que se le dice a una chica?!", "Kanako"),
    120: ("Solo me preocupo por si estás bien.", "Kyousuke"),
    121: ("Hmph, esto es nada.", "Kanako"),
    122: ("Y así engordarás más.", "Kyousuke"),
    123: ("¿Ah?", "Kanako"),
    124: ("Nada.", "Kyousuke"),
    125: ("Hmph... Oye, Kyousuke.", "Kanako"),
    126: ("¿Hmm? ¿Qué es?", "Kyousuke"),
    127: ("De ahora en adelante, te llamaré de vez en cuando. ¿Entiendes?", "Kanako"),
    128: ("¿Huh? ¿No acabo de invitarte?", "Kyousuke"),
    129: ("Oh, ya veo. Hmm... así que puedes decir eso～", "Kanako"),
    130: ("De alguna manera, la boca de Kanako se está volviendo floja～", "Kanako"),
    131: ("¡Lo entiendo! ¡Lo entiendo, maldición!", "Kyousuke"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
current["000scriptKIFK_0000A.obj"] = build(n, s)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptKIFK_0000A.obj")