import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0175_n = {
    0: "Ruta de Kuroneko · La Prueba De Dios",
    21: "...Es verdad, no lo he considerado antes... Solo estoy pensando que ser trabajador ciertamente nos llevará a algún lugar...",
    49: "...Maldición. ¿No hay algo que pueda hacer?",
    50: "......No sirve. No puedo pensar en nada que pueda hacer...",
    72: "Esta chica... ¿todavía está preocupada por eso?",
    73: "No, eso no es correcto... Solo se está entregando a la desesperación...",
}
a0175_s = {
    1: ("...¿Por qué no estás diciendo nada?", "Kuroneko"),
    2: ("No me digas que planeas quedarte en silencio...", "Kuroneko"),
    3: ("¿Soy alguien cuya existencia es trivial para ti?", "Kuroneko"),
    4: ("...Solo no sé cómo decirlo. No es que no seas importante ni nada.", "Kyousuke"),
    5: ("Así que eso es lo que mi existencia significa para ti.", "Kuroneko"),
    6: ("Alguien sobre quien no puedes encontrar una respuesta. Eso es todo.", "Kuroneko"),
    7: ("...N-Nada de eso.", "Kyousuke"),
    8: ("Si es así, ¿por qué no puedes encontrar una respuesta?", "Kuroneko"),
    9: ("E-Eso es...", "Kyousuke"),
    10: ("¿Cómo podrías ser trivial para mí...", "Kyousuke"),
    11: ("...Hmph. Digas lo que digas.", "Kuroneko"),
    12: ("Olvídalo, aunque solo lo digas para complacerme... Estoy un poco feliz.", "Kuroneko"),
    13: ("¿En serio...", "Kyousuke"),
    14: ("...Sin embargo, si ese es el caso, ¿por qué te quedas en silencio?", "Kuroneko"),
    15: ("Es porque no sé cómo decirlo.", "Kyousuke"),
    16: ("Ah en serio. Así que has tropezado con esta situación cuando eres incapaz de dar una respuesta.", "Kuroneko"),
    17: ("Eres de verdad un tipo amable indefenso...", "Kuroneko"),
    18: ("Nunca pensando en ti mismo, siempre saltando a la acción... Por eso siempre irrumpes sin considerar primero lo que otros podrían pensar o en qué", "Kuroneko"),
    19: ("tipo de situación están.", "Kuroneko"),
    20: ("Incluso intentas entrometerte en cosas que están más allá de tu habilidad.", "Kuroneko"),
    22: ("Kuh...", "Kyousuke"),
    23: ("......Jeh. Parece que di en el clavo.", "Kuroneko"),
    24: ("No ha terminado todavía, ¿verdad? ¿No debe haber todavía algo que podamos hacer?", "Kyousuke"),
    25: ("¿No es muy temprano todavía para rendirse? ¿Por qué puedes decir eso tan fácilmente?", "Kyousuke"),
    26: ("...Es como dices. Mientras no nos rindamos, debe haber una manera. La gente suele decir eso.", "Kuroneko"),
    27: ("¿Verdad?", "Kyousuke"),
    28: ("Aunque eso es el balbuceo de una persona ignorante que no entiende nada de la situación...", "Kuroneko"),
    29: ("Eso es... Ciertamente, no soy tan conocedor como tú...", "Kyousuke"),
    30: ("Sin embargo, por esa razón déjame decir esto. ¡Mientras no perdamos la esperanza, nos las arreglaremos de algún modo!", "Kyousuke"),
    31: ("Por Dios... Realmente necesito aprender un poco de tu motivación inquebrantable.", "Kuroneko"),
    32: ("Sin embargo...", "Kuroneko"),
    33: ("Aun así, un horario así es imposible desde el principio.", "Kuroneko"),
    34: ("Fue muy estricto desde el inicio, y aun así un novato como tú quiere unirse...", "Kuroneko"),
    35: ("Parece ser así. Sean cuales sean los dioses malvados que existan, todos me están llamando a rendirme.", "Kuroneko"),
    36: ("...No es imposible. Todavía hay algo que podemos hacer, ¿verdad?", "Kyousuke"),
    37: ("¿Qué más podemos hacer? Intenta decirlo.", "Kuroneko"),
    38: ("C-Como dije, yo pagaré por--", "Kyousuke"),
    39: ("...Y te estoy diciendo que eso es una molestia.", "Kuroneko"),
    40: ("Es un callejón sin salida. No tenemos ninguna solución. Somos como ratas acorraladas.", "Kuroneko"),
    41: ("Hay un dicho que dice 'Una rata acorralada morderá al gato'. Incluso si somos nosotros...", "Kyousuke"),
    42: ("Somos diferentes de una rata... Es inútil luchar más.", "Kuroneko"),
    43: ("¿C-Cómo puedes decirlo así...", "Kyousuke"),
    44: ("¿Porque esa es la verdad? No hay otra solución...", "Kuroneko"),
    45: ("Estoy segura de que en el fondo de tu corazón ya te has rendido, ¿verdad?", "Kuroneko"),
    46: ("...No es así como me siento.", "Kyousuke"),
    47: ("Cierto. Estaba segura de que dirías eso.", "Kuroneko"),
    48: ("Sin embargo, no lo necesito. No me importa si tu entrometimiento es por buena voluntad o por amabilidad, no necesito nada de eso.", "Kuroneko"),
    51: ("...Maldición.", "Kyousuke"),
    52: ("Eso es. Ni siquiera nosotros podemos levantarnos del borde de la muerte ya.", "Kuroneko"),
    53: ("Es una lástima... Un Final Malo.", "Kuroneko"),
    54: ("A veces, la buena voluntad de las personas puede salir mal. Eso es exactamente lo que pasó aquí.", "Kuroneko"),
    55: ("...¿Qué hice para que saliera mal...?", "Kyousuke"),
    56: ("Te lo dije, ¿no? Esta es mi creación, si no estoy contenta con ella, no tiene sentido hacerla.", "Kuroneko"),
    57: ("No quiero continuar si debo recibir la caridad de otras personas.", "Kuroneko"),
    58: ("...¿Caridad...? No quise decir algo así...", "Kyousuke"),
    59: ("Pero al final se volvió así.", "Kuroneko"),
    60: ("E-Estás equivocada.", "Kyousuke"),
    61: ("No importa cuáles fueron tus intenciones, la situación es así. Yo no soy capaz de hacer nada y tú quieres resolverlo, obviamente.", "Kuroneko"),
    62: ("Pero, mi orgullo no permitirá algo así.", "Kuroneko"),
    63: ("Estoy realmente agradecida por tu ayuda. Sin embargo...", "Kuroneko"),
    64: ("Este juego de fingir se acabó aquí.", "Kuroneko"),
    65: ("...¿Qué es eso?", "Kyousuke"),
    66: ("No pidas recompensas si vamos a mantener buenas relaciones. ¿Qué diferencia hay entre esto y el juego de fingir de un niño?", "Kuroneko"),
    67: ("¿Por qué estás siendo tan masoquista?", "Kyousuke"),
    68: ("...El que fue incapaz de responder fuiste tú, ¿no?", "Kuroneko"),
    69: ("Eso...", "Kyousuke"),
    70: ("Por eso, lo que nos une ya no existe.", "Kuroneko"),
    71: ("Hmph... Para ser más específicos, ¿no es esto lo mismo que actuar como hermanos?", "Kuroneko"),
    74: ("...Solo falta un poco más para que terminemos, ¿verdad? Piensa en ello de nuevo...", "Kyousuke"),
    75: ("Eso no es lo que realmente piensas, ¿verdad? Parece que solo te estás lastimando a ti misma...", "Kyousuke"),
    76: ("......", "Kuroneko"),
    77: ("¿Actuar...? ¿Qué es eso?", "Kyousuke"),
    78: ("¿Pero no es ese el caso?", "Kuroneko"),
    79: ("¡No lo es! Te dije que no es así. ¡No puedes dejar que este incidente te haga perder de vista quién eres!", "Kyousuke"),
    80: ("Terminemos esto ya.", "Kuroneko"),
    81: ("¿Terminar...? ¿Terminar qué?", "Kyousuke"),
    82: ("............Todo.", "Kuroneko"),
    83: ("Todo el trabajo del manuscrito que estábamos haciendo hasta ahora, y también este falso-drama...", "Kuroneko"),
    84: ("¡¿Qué es eso!? ¿Esa era la magnitud de tu pasión?", "Kyousuke"),
    85: ("¿Era algo tan barato como para dejarlo pasar usando la palabra 'drama'?", "Kyousuke"),
    86: ("¡¿Y aun así lo llamas falso!? ¡¿Todo lo que estabas haciendo hasta ahora era falso!?", "Kyousuke"),
    87: ("Es algo tuyo, y solo tuyo, ¿verdad? ¡Lo llamaste tu propio trabajo, verdad!?", "Kyousuke"),
    88: ("......", "Kuroneko"),
    89: ("¿No es esta una de esas penurias de producción que tenías que atravesar!?", "Kyousuke"),
    90: ("¿Parezco herida? Solo estoy declarando un hecho.", "Kuroneko"),
    91: ("Si no estamos actuando como hermanos, entonces supongo que estamos imitando la amistad? Suena como un drama juvenil infantil de televisión...?", "Kuroneko"),
    92: ("...No... No es eso, ¿sabes? Necesitas calmarte un poco. Deja de bromear sobre esto.", "Kyousuke"),
    93: ("...Jeje. Tienes razón... En efecto, fue solo una tontería hace un momento.", "Kuroneko"),
    94: ("...Sin embargo, este problema es toda la realidad.", "Kuroneko"),
    95: ("...Pero si no te rindes, todavía puedes arreglártelas de algún modo, ¿no es así?", "Kyousuke"),
    96: ("...Eso es. Ese es mi deseo... Pero hay situaciones en las que simplemente no puedes hacer nada.", "Kuroneko"),
    97: ("...Urgh, ¡basta! ¡Cuando alguien está tratando de decir algo constructivo, lo apagas de inmediato!", "Kyousuke"),
    98: ("Solo eres mi kohai, así que no te creas mucho. Cállate y acepta la buena voluntad de tu senpai.", "Kyousuke"),
    99: ("Jeh... Ahora ni siquiera puedes formar palabras decentes, ¿qué pasa ahora? ¿Te estás enojando conmigo?", "Kuroneko"),
    100: ("Es verdad que esas palabras son las que describen nuestra relación... Pero, ¿no dirás que te involucraste conmigo por ese tipo de palabras?", "Kuroneko"),
    101: ("Mi única kohai eres solo tú.", "Kyousuke"),
    102: ("¡Eres demasiado ruidosa! ¡Despierta y escúchame!", "Kyousuke"),
    103: ("No. Es inútil continuar más.", "Kuroneko"),
    104: ("¡Eres mi kohai importante!", "Kyousuke"),
    105: ("Jeh. ¿Senpai y kohai? ¿No soy solo una de las muchas kohais que tienes?", "Kuroneko"),
    106: ("¡Eso no es verdad! ¡Eres mi única kohai!", "Kyousuke"),
    107: ("...¿Eh?", "Kuroneko"),
    108: ("¡Esto no tiene nada que ver con otras personas! Estoy realmente preocupado por ti, preocupándome por tus problemas, entrometiéndome en tus asuntos, todo solo para", "Kyousuke"),
    109: ("verte sonreír!", "Kyousuke"),
    110: ("Eso es, a lo mucho, la tableta se rompió. Pero es un problema que yo, como estudiante de preparatoria, no puedo resolver.", "Kuroneko"),
    111: ("No tengo el dinero, es absurdo pedir prestado a otras personas... Es fatal. No puedo hacer nada en absoluto. Es jaque mate.", "Kuroneko"),
    112: ("Fatal, dices....", "Kyousuke"),
    113: ("No hay manera de evitarlo.", "Kuroneko"),
    114: ("¿Qué estás hablando como si supieras todo? Escucha lo que tu senpai tiene que decirte a veces.", "Kyousuke"),
    115: ("Hmph... Ni siquiera puedes decir cosas decentes ahora, ¿así que estás apelando desde esa posición?", "Kuroneko"),
    116: ("Es verdad que esas palabras son las que describen nuestra relación... Pero, ¿no dirás que te involucraste conmigo por ese tipo de", "Kuroneko"),
    117: ("palabras?", "Kuroneko"),
    118: ("¡Mi única kohai eres solo tú!", "Kyousuke"),
    119: ("Qué... Y-Tienes muchas otras kohais, ¿no?", "Kuroneko"),
    120: ("Sí, es verdad. Pero la única kohai importante para mí eres solo tú.", "Kyousuke"),
}

a0178_n = {
    0: "Ruta de Kuroneko · Kyousuke Fuera De Control",
    4: "Lo hago. En efecto, voy a dar exámenes pronto.",
    5: "Me han llenado las orejas sobre lo importante que es este tiempo de verano.",
    6: "Pero sabes... ¡no puedo estudiar todo el tiempo! Lo que es realmente importante es...",
    7: "No es que tome los estudios a la ligera. Entiendo lo importante que es estudiar.",
    8: "Pero aparte de eso, hay otras cosas más importantes, ¿verdad? ¡¿No es algo que todos ustedes siempre me muestran!?",
    9: "...Simplemente no puedo encontrar una manera de responder a esto.",
    10: "En ese caso, seré fiel a mí mismo...",
    11: "Me reí de Kuroneko una vez antes... Pero eso es realmente todo lo que tengo...",
    14: "Es natural preocuparse...",
    15: "Ya tomé la iniciativa. Elegí escuchar a otros hablar de ti, y elegí hablarte.",
    16: "¡Ya es demasiado tarde para que yo me detenga!",
    17: "Además, sobre todo...",
    18: "Sí, por eso... correcto...",
    56: "Al verla tan preocupada por algo tan estúpido... No pude evitar reír.",
}
a0178_s = {
    1: ("...¿Qué tontería es esa?!", "Kuroneko"),
    2: ("¿No tienes otras cosas que hacer? ¿Realmente entiendes quién eres?", "Kuroneko"),
    3: ("¡Estás a punto de pasar exámenes! ¿Entiendes siquiera lo importante que es tu tiempo de verano?", "Kuroneko"),
    12: ("...Esas son dos cosas diferentes!", "Kyousuke"),
    13: ("¿Qué?", "Kuroneko"),
    19: ("Esto es lo que quiero hacer.", "Kyousuke"),
    20: ("¿Q-Qué tontería es esta? ¿Vas a dejar que un impulso emocional arruine toda tu vida?", "Kuroneko"),
    21: ("Como estudiante que va a dar exámenes, deberías estar enfocado en estudiar. Así se supone que son los estudiantes.", "Kuroneko"),
    22: ("Desafortunadamente, más que estudiar...", "Kyousuke"),
    23: ("Es verdad que voy a dar exámenes pronto.", "Kyousuke"),
    24: ("La educación es ciertamente importante. Solo les traeré problemas a mis padres si fallo, y también destruirá mi sueño de tener una 'vida normal'.", "Kyousuke"),
    25: ("Sin embargo...", "Kyousuke"),
    26: ("¡Pero por encima de eso, hay algo mucho más importante justo en frente de mí!", "Kyousuke"),
    27: ("¿Cómo podría abandonarte cuando tienes problemas?", "Kyousuke"),
    28: ("¡Yo misma te dije que me dejaras en paz! ¿Y planeas continuar haciendo lo que te plazca?", "Kuroneko"),
    29: ("¡Claro que sí! ¡No estoy haciendo esto solo por ti, sino también por mí!", "Kyousuke"),
    30: ("¡Decidí ayudarte hasta que haya logrado mi meta! ¡Y también se lo prometí a todos! ¡Kirino, Saori... Y sobre todo, a mí mismo!", "Kyousuke"),
    31: ("No me voy a rendir en la mitad de esto.", "Kyousuke"),
    32: ("¿Tu meta? ¡Como si tuvieras una!", "Kuroneko"),
    33: ("Sí, la tengo. Finalmente me di cuenta de que tengo una meta muy importante.", "Kyousuke"),
    34: ("¿Por qué no me cuentas más sobre eso entonces? ¿De qué has estado hablando hasta ahora?", "Kuroneko"),
    35: ("Sí, escucha bien. Mi meta es...", "Kyousuke"),
    36: ("¡Proteger este mundo! ¡Este mundo contigo en él! ¡Con Kirino y Saori a mi lado, quiero proteger este mundo contigo en él!", "Kyousuke"),
    37: ("¡Deja de tontear! Para ti, yo no soy nada...! ¡Solo una kohai... Una mera amiga!", "Kuroneko"),
    38: ("¡Esto no tiene nada que ver con ser una kohai, una amiga o una hermanita! ¡Deja de aferrarte a esas palabras!", "Kyousuke"),
    39: ("¡Lo importante es lo que hay dentro! Las palabras no son suficientes, ¡tenemos que ir más profundo! ¡Es una cuestión de sentimientos!", "Kyousuke"),
    40: ("Quiero ayudarte... ¿No es suficiente eso? Por encima de todo, yo...", "Kyousuke"),
    41: ("¡Creo que estar a tu lado es más importante!", "Kyousuke"),
    42: ("Creo que sería peligroso dejarte sola en tu estado actual.", "Kyousuke"),
    43: ("Hah...", "Kuroneko"),
    44: ("Considera el significado de tus palabras... Ya no eres un niño.", "Kuroneko"),
    45: ("¿Todavía recuerdas lo que dijiste antes? Estoy segura de que esa cabeza gruesa tuya no contiene ningún recuerdo de ello.", "Kuroneko"),
    46: ("¡Las palabras de alguien como tú no podrán llegar a mi alma!", "Kuroneko"),
    47: ("Vete a casa... Y usa ese cerebro inútil tuyo para reflexionar sobre mis palabras. Si es que logras recordarlas.", "Kuroneko"),
    48: ("¡Espera! ¿Qué es exactamente lo que estás diciendo?", "Kyousuke"),
    49: ("¿He dicho algo que te haya herido!?", "Kyousuke"),
    50: ("Lo hiciste en el pasado. De vuelta del torneo de juegos. Claramente dijiste 'no puedo seguir tu ritmo'.", "Kuroneko"),
    51: ("...¿'No puedo seguir tu ritmo'...? ¿Durante el torneo de juegos?", "Kyousuke"),
    52: ("...Ah.", "Kyousuke"),
    53: ("¿Q-Qué es esa voz despreocupada?! Yo...", "Kuroneko"),
    54: ("Tú... ¿siempre estuviste preocupada por eso? ¿Por eso me has estado evitando?", "Kyousuke"),
    55: ("Y-Yo no... De todos modos, esta es una buena oportunidad, solo quiero mejorar en las relaciones interpersonales.", "Kuroneko"),
    57: ("En serio... ¡Esto es exactamente por lo que es peligroso que estés sin mí cerca!", "Kyousuke"),
    58: ("¿Q-Qué estás diciendo...", "Kuroneko"),
    59: ("¿No pudiste simplemente preguntármelo en ese entonces?", "Kyousuke"),
    60: ("Para empezar, ¿realmente no confías en mí lo suficiente como para pensar que diría esas palabras con ese significado en mente?", "Kyousuke"),
    61: ("Eso es...", "Kuroneko"),
    62: ("Bueno, dejando eso de lado.", "Kyousuke"),
    63: ("En realidad, hay muchas cosas en las que no puedo seguir tu ritmo. Eso es porque no soy un otaku. Tampoco puedo dibujar manga.", "Kyousuke"),
    64: ("Pero eso es solo una faceta de tus pasatiempos. Nunca pensé que no podría seguir tu ritmo en aspectos más importantes y básicos de ti misma.", "Kyousuke"),
    65: ("Entonces, ¿ahora entiendes?", "Kyousuke"),
    66: ("Por Dios...", "Kuroneko"),
    67: ("Jeh, es ridículo, ¿no? Todo pasó por mi malentendido...", "Kuroneko"),
    68: ("En realidad estoy bastante avergonzada...", "Kuroneko"),
    69: ("Sin embargo...", "Kuroneko"),
    70: ("¿Hmm?", "Kyousuke"),
    71: ("Gracias a esto, llegué a entender y notar muchas cosas... Así que esto en realidad no es algo malo.", "Kuroneko"),
}

a0179_n = {
    0: "Ruta de Kuroneko · La Frase Decisiva",
    22: "Tus ojos me están diciendo que responda rápido... sin embargo.",
    31: "Solo di que quieres que lo diga directamente, aunque ella es definitivamente más linda así.",
    32: "Quizás no debería presionar demasiado a esa chica tímida o se enojará.",
    35: "Ciertamente no tengo que decirlo directamente, ¿verdad?",
}
a0179_s = {
    1: ("En cualquier caso...", "Kuroneko"),
    2: ("Aunque hemos llegado tan lejos, no has dicho la frase decisiva.", "Kuroneko"),
    3: ("Veo que eres realmente incompetente... pero es realmente lamentable que te menosprecie, ¿verdad? Porque todavía hay una maldición sobre ti.", "Kuroneko"),
    4: ("¿Una maldición...? ¿Qué es eso? No recuerdo nada así.", "Kyousuke"),
    5: ("Por supuesto que la hay. Desde tu manera de pensar, y tus labios, lleva la maldición de la 'verdadera incompetencia'.", "Kuroneko"),
    6: ("Simplemente no puedes notar 'eso'... y además, no lo dirás aunque esté mal.", "Kuroneko"),
    7: ("Por Dios, es realmente una molestia. Si no estuviera ahí, estoy segura de que la conversación terminaría en este instante.", "Kuroneko"),
    8: ("No... Es por esa maldición, que soy capaz de estar aquí.", "Kuroneko"),
    9: ("¿Kuroneko? ¿Qué estás diciendo?", "Kyousuke"),
    10: ("Jeje... Estoy diciendo, permíteme liberarte de esa maldición.", "Kuroneko"),
    11: ("Como estaba diciendo, ¿qué maldición...", "Kyousuke"),
    12: ("¡Hmm...!", "Kyousuke"),
    13: ("Este es un ritual para romper la maldición. Y ahora haré una nueva.", "Kuroneko"),
    14: ("Mi maldición ha sido enviada para sobrescribir tu maldición actual.", "Kuroneko"),
    15: ("Y ahora, la maldición de la incompetencia que estaba sobre ti desaparecerá lentamente.", "Kuroneko"),
    16: ("Y mi maldición será, la maldición ceremonial. Te haré oficialmente mi compañero.", "Kuroneko"),
    17: ("Es diferente de antes, no simplemente un contrato de compañeros... es más fuerte y más profundo en significado, un contrato que ata las almas de dos personas.", "Kuroneko"),
    18: ("¿Qué tal? Estoy a punto de poner en marcha este mismo contrato sobre ti ahora.", "Kuroneko"),
    19: ("¿Cuál es tu... respuesta?", "Kuroneko"),
    20: ("Ahh... He despertado. Incluso yo, lo entiendo ahora.", "Kyousuke"),
    21: ("Como estaba diciendo, te estoy preguntando, ¿cuál es tu respuesta?", "Kuroneko"),
    23: ("¿No puedes usar términos más simples para dejarlo claro?", "Kyousuke"),
    24: ("Siento que si ese fuera el caso, lo habría notado antes...", "Kyousuke"),
    25: ("...¿No te lo dije antes?", "Kuroneko"),
    26: ("Mi personalidad está retorcida. Además de eso, ¿qué tal apurarte y responder mi pregunta?", "Kuroneko"),
    27: ("¿Quién fue el que dijo antes, que ambas de nuestras personalidades están retorcidas?", "Kyousuke"),
    28: ("Como estaba diciendo, ¿cuánto tiempo más planeas tomarme el pelo?", "Kuroneko"),
    29: ("Jeje... Además, estoy seguro de que sabes lo que voy a decir en respuesta, ¿no?", "Kyousuke"),
    30: ("...Es un hecho necesario que ambos lados deben aceptar el contrato, incluso cuando haces un trato con el diablo, no es unilateral...", "Kuroneko"),
    33: ("...Lo entiendo. Te responderé.", "Kyousuke"),
    34: ("Mi respuesta es...", "Kyousuke"),
}

a0180_n = {
    0: "Ruta de Kuroneko · Tiempo De Presión Y Experiencia De Vida",
    1: "Cada día fue un día emocionante después de eso.",
    2: "Después de esa discusión, fui a comprar una tableta nueva y me tomó bastante tiempo.",
    3: "La tableta era inesperadamente cara... Ciertamente no pude comprarla en el acto.",
    4: "Al final, retiré mis ahorros y la compré. Aunque Kuroneko la aceptó de mala gana... esto sigue siendo la manera de un hombre.",
    5: "Y después de volver al trabajo... experimenté el «Tiempo de Presión» por primera vez.",
    6: "El tiempo de presión realmente cambia a una persona, eso es evidente justo en frente de mí...",
    9: "Después de murmurarle al monitor, las manos de Kuroneko se movieron a una velocidad aterradora.",
    15: "Eso es en realidad bastante aterrador...",
    18: "Kuroneko no va a descansar. Aunque estoy más concentrado que antes, ya estoy llegando a mis límites.",
    19: "Ku-Kuroneko-san, esto se está poniendo realmente difícil...",
    22: "Incluso si pasa del límite, el trabajo todavía continúa...",
    23: "Ahh, esto no es lo que hacen los humanos... Sin embargo, por eso esto está siendo llamado la 'escena de la carnicería'.",
    24: "Después de todo, los 'creadores' no son seres humanos ordinarios...",
    25: "Sin saberlo, mientras la fecha límite se acerca, el impulso aumenta junto con ella. Claramente sentí que ella era diferente de mí.",
    26: "Bueno, estoy al lado de Kuroneko, así que superé esto con perseverancia.",
    27: "Aunque eso fue lo que pensé...",
    28: "Finalmente estamos de vuelta a casa después de terminar todo.",
    34: "Impresión offset - En pocas palabras, hay dos maneras de imprimir doujin. O usas papel barato para hacer un libro ordinario, o agregas algo de dinero para hacerlo todo",
    35: "brillante.",
    36: "Darle autenticidad a tu libro poniéndole dinero es para lo que sirve el offset. Fuente: Kuroneko-sensei sobre Producción de Doujin.",
}
a0180_s = {
    7: ("Las dificultades solo van hacia aquellos que se enfrentan a los obstáculos. Los que no lo hacen solo serán corderos que siguen al destino. Entonces, ¿qué hay del", "Kuroneko"),
    8: ("desafiante? ¿Cederá o lo superará?", "Kuroneko"),
    10: ("¿Ku-Kuroneko...?", "Kyousuke"),
    11: ("No me hables o afectará mi concentración.", "Kuroneko"),
    12: ("P-Pero... ¿estás bien?", "Kyousuke"),
    13: ("Mejor que nunca. Si me concentro de verdad, me vuelvo así. No hay nada raro en ello, así que solo continúa con tu trabajo.", "Kuroneko"),
    14: ("Y-Ya veo. Lo entiendo...", "Kyousuke"),
    16: ("La desesperación solo viene para aquellos que se rinden. Arrastrándose en el suelo mientras suplican perdón frente a Dios. ¿Puede escalarse cualquier muro mientras no te", "Kuroneko"),
    17: ("rindas? ¿Llegarán siempre las oraciones al cielo?", "Kuroneko"),
    20: ("Para luchar hacia adelante por este conocimiento, sin rendirte incluso si tus pies dejan de moverse. Solo aquellos con la determinación de continuar sin importar qué serán", "Kuroneko"),
    21: ("permitidos para llegar a este plano...", "Kuroneko"),
    29: ("Aun así, no pensé que la llevarías personalmente a la imprenta...", "Kyousuke"),
    30: ("Normalmente solo necesitas enviar los datos y listo.", "Kuroneko"),
    31: ("Aunque ya que planeamos impresión offset, no tiene sentido no ir ahí directamente. La textura del papel es algo que necesitas sentir de verdad.", "Kuroneko"),
    32: ("Sí, los datos solos no servirán para algo así.", "Kyousuke"),
    33: ("Sí, la impresión es uno de los placeres de crear un libro.", "Kuroneko"),
    37: ("Ya veo... Pero con esto, hemos terminado todo, ¿verdad?", "Kyousuke"),
    38: ("Sí, hemos enviado el guion para su publicación. Todo lo que tenemos que hacer ahora es esperar. Bueno, en realidad son los libros quienes nos estarán esperando ese día.", "Kuroneko"),
    39: ("¿En serio? Así que se acabó por el momento, bien hecho.", "Kyousuke"),
    40: ("Sí... Bien hecho. Gracias a ti, soy capaz de terminar a tiempo.", "Kuroneko"),
    41: ("Jeje... No sé si te estaba ayudando o solo te estaba frenando...", "Kyousuke"),
    42: ("Hmph, ¿lo dudas? ¿Cuál de los dos fue?", "Kuroneko"),
    43: ("Oye oye, ¿no se supone que debes decir algo como 'Es porque estás aquí, por eso seguí adelante'?", "Kyousuke"),
    44: ("...N-No te creas mucho. Para empezar, ¿no fue tu obstinación la que interrumpió mi impulso?", "Kuroneko"),
    45: ("Qué-, ¿me estás echando la culpa a mí? Además de eso, ¿no es la razón real tus propios malentendidos?", "Kyousuke"),
    46: ("*risa*", "Kuroneko"),
    47: ("*risa*", "Kyousuke"),
    48: ("Parémonos aquí. No es elegante seguir discutiendo bajo una ocasión tan formal.", "Kuroneko"),
    49: ("¿Qué quieres decir con una ocasión formal?", "Kyousuke"),
    50: ("¿No es obvio? Es el día en que ambos completamos el manuscrito.", "Kuroneko"),
}

a0190_n = {
    0: "Ruta de Kuroneko · El Sueño De Un Día De Verano: Una Realidad",
    1: "Y así, en el día del Comiket---",
    12: "Kuroneko completó su manga, hoy... Por fin las rutinas diarias de los miembros de siempre han vuelto.",
    13: "En retrospectiva, ¿han estado realmente peleando hasta ahora? Es lo que he estado preguntándome.",
    14: "Por lo que parece, realmente se siente como la escena de siempre.",
    15: "...Bueno, he trabajado tan duro solo por el bien de ver esta escena.",
    21: "Aunque eso es lo que está diciendo... Por su expresión, pude adivinar aproximadamente lo que Kuroneko acaba de decir.",
    22: "Para la tímida Kuroneko, de hecho no es fácil repetir lo que acaba de decir.",
    26: "Esa frase que dijo Kuroneko fue...",
}
a0190_s = {
    2: ("Hola～, estamos vendiendo un doujin nuevo～, sin embargo, el contenido está lleno de divagaciones de una chuunibyou así que es bastante lamentable～", "Kirino"),
    3: ("Ah, sin embargo, los dibujos todavía están a un nivel visible～?", "Kirino"),
    4: ("Si eso te parece aceptable, entonces por favor ven y compra～. Esta gata estará realmente feliz si lo haces～", "Kirino"),
    5: ("Tú... ¿Estás aquí para humillarme o para ayudar a promocionar mis artículos?", "Kuroneko"),
    6: ("¿Oh? No te estoy humillando. Estoy ayudándote seriamente a promocionar tus artículos.", "Kirino"),
    7: ("Solo espero que nadie sea estafado al comprar, así que solo estoy explicando en detalle lo que van a comprar.", "Kirino"),
    8: ("¿Eh? Usando la calumnia para promocionar las cosas que vendo, felicitaciones por tener ese cerebro. ¿Es esto lo que llaman esnobismo de tendencias?", "Kuroneko"),
    9: ("Pensar que querrías vender un manga así. Por esto es que las chuunibyous son dolorosas de soportar.", "Kirino"),
    10: ("Simplemente no maduran mentalmente en absoluto.", "Kirino"),
    11: ("Ya, ya, ambas... Hoy es un día tan encantador, sé que ambas están en buenos términos, pero tengan un límite con la pelea de enamorados...", "Saori"),
    16: ("Por cierto, tengo algo que tengo que decirte.", "Kuroneko"),
    17: ("¿Huh, qué es?", "Kyousuke"),
    18: (".........", "Kuroneko"),
    19: ("...¿Ah? L-Lo siento, no te escuché bien... ¿podrías decirlo una vez más?", "Kyousuke"),
    20: ("¿Una vez más? No bromees conmigo. Acabas de perder la oportunidad que solo llega una vez en la vida.", "Kuroneko"),
    23: ("Escucharé con más cuidado la próxima vez. Sigamos trabajando duro de ahora en adelante.", "Kyousuke"),
    24: ("...Haz lo que quieras. Te lo diré de nuevo cuando tenga ganas.", "Kuroneko"),
    25: ("Sí, cuento contigo.", "Kyousuke"),
    27: ("---Gracias---", "Kuroneko"),
}

data = {
    "000scriptCKUR_0175T.obj": build(a0175_n, a0175_s),
    "000scriptCKUR_0178A.obj": build(a0178_n, a0178_s),
    "000scriptCKUR_0179G.obj": build(a0179_n, a0179_s),
    "000scriptCKUR_0180A.obj": build(a0180_n, a0180_s),
    "000scriptCKUR_0190E.obj": build(a0190_n, a0190_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
