import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a115_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo Esté Feliz De Ir A Una Cita Con Mi Hermanita",
    3: "*suspiro*... Así que al final, todo fue en vano.",
    6: "Ahora que mi plan de recrear las escenas de la novela de Kirino «Imouto City» ha fallado, solo queda una cosa...",
    7: "Era el único método que no quería usar en absoluto si era posible, pero...",
}
a115_s = {
    1: ("D-De todos modos, ¿todavía no has recordado nada?", "Kyousuke"),
    2: ("Eres tan persistente. No sigas preguntándome eso.", "Kirino"),
    4: ("Entonces, ¿qué vas a hacer? No me digas que va a terminar así nomás?", "Kirino"),
    5: ("Hmm...", "Kyousuke"),
    8: ("...Todavía me queda un último recurso.", "Kyousuke"),
    9: ("¿Huh? ¿Un último recurso? ¿Qué es eso?", "Kirino"),
    10: ("...Por ahora, vayamos a casa primero.", "Kyousuke"),
}

a120_n = {
    0: "Ruta de Kirino · No Hay Más Opción Que Usar Mi Último Recurso Con Mi Hermanita",
    1: "Bien, ya pasaron las 9 p.m.",
    2: "Después de volver a casa, inmediatamente cené, me bañé y me preparé por completo.",
    3: "El ambiente en la habitación de Kirino está inusualmente tenso, mientras mi hermanita y yo estamos actualmente frente a frente.",
    8: "Esta chica... ¿Está imaginando algo inútil otra vez?",
    10: "Ah, me preguntaba por qué había un bate de béisbol en la esquina de la habitación, así que ese era su propósito previsto.",
    12: "...¿Realmente está bien, Kyousuke?",
    13: "Seré golpeado hasta quedar hecho pulpa por el bate de béisbol si fallara una vez más, ¿sabes? Esto no es para reírse, ¿sabes?",
    14: "Tch... Tengo que prepararme para lo peor aquí.",
    15: "Hagámoslo. Este es mi último recurso...",
    19: "Agh! ¡No soy responsable de lo que pase!",
    28: "Así que incluso esto no es suficiente...",
    29: "Así es. Escuchar la petición de otra persona no funcionará con Kirino, que solo sabe cómo explotar a otras personas.",
    30: "Aunque ella siempre me pide cosas, ni siquiera escuchará una petición mía ni por una vez...",
    31: "No... Espera.",
    32: "Si pedir no es bueno, ¿qué tal hacer algo que Kirino me pidió que hiciera?",
    33: "Antes de perder sus recuerdos, Kirino me dijo que completara «SisXSis» lo antes posible.",
    34: "Entonces, a la inversa, ¿no puedo hacer que Kirino lo juegue...?",
    35: "Maldición, realmente no quería usar esto, pero...",
    36: "El «verdadero» último recurso está en mi bolso aquí.",
    37: "El juego de hermanitas recomendado por Kirino, «SisXSis».",
    38: "...Es cierto que si Kirino juega esto, podría recuperar sus recuerdos.",
    39: "Pero si esto falla, yo...",
    56: "Además, ¡no repitas exactamente lo mismo que te dije hace un año!",
    68: "Maldición, realmente no quería usar esto, pero...",
    69: "El «verdadero» último recurso está en mi bolso aquí.",
    70: "El juego de hermanitas recomendado por Kirino, «SisXSis».",
    71: "...Es cierto que si Kirino juega esto, podría recuperar sus recuerdos.",
    72: "Pero si esto falla, yo...",
}
a120_s = {
    4: ("Oye, ¿no es hora de que me muestres ese último recurso tuyo?", "Kirino"),
    5: ("Deberías haberlo revelado mucho antes si tuvieras tal cosa en primer lugar.", "Kirino"),
    6: ("...Como si pudiera hacer algo tan vergonzoso una segunda vez.", "Kyousuke"),
    7: ("¿A-Algo... vergonzoso?", "Kirino"),
    9: ("S-Si haces algo pervertido otra vez, te romperé la cabeza.", "Kirino"),
    11: ("E-Estará bien... Creo... Probablemente...", "Kyousuke"),
    16: ("Ah, por cierto, ese bate de béisbol es de metal.", "Kirino"),
    17: ("¡¿Entonces por qué está disfrazado para parecer que es de madera?!", "Kyousuke"),
    18: ("¿Qué? Sácalo rápido.", "Kirino"),
    20: ("¡Realmente lamento todo lo que ha pasado hasta ahora! ¡Por favor recupera tus recuerdos!", "Kyousuke"),
    21: ("......", "Kirino"),
    22: ("......¿Kirino?", "Kyousuke"),
    23: ("...Umm...No... entiendo lo que quieres decir... ¿Qué estás haciendo?", "Kirino"),
    24: ("¡E-El arte secreto final que hace que cumplas mi deseo a cambio de mi honor y orgullo como hombre, la técnica de «Rogar-de-rodillas»!", "Kyousuke"),
    25: ("...¿Por qué no te mueres mejor?", "Kirino"),
    26: ("Para empezar, tu ruego ni siquiera tiene el valor de un pañuelo de bolsillo.", "Kirino"),
    27: ("Mi orgullo no tiene precio según el significado de mi nombre, sin embargo.", "Kyousuke"),
    40: ("¡Maldición, lo haré!", "Kyousuke"),
    41: ("¡Contempla, este es mi último recurso--!", "Kyousuke"),
    42: ("¡Contempla, este es mi último recurso--!", "Kyousuke"),
    43: ("¡Espera, ¿no es ese un juego otaku?! No importa cuánto me muestres este tipo de cosas, yo...", "Kirino"),
    44: ("No es solo un juego otaku. Este «SisXSis» es un juego que tu yo obsesionada con las hermanitas llamó divino, ¡un juego R-18 de hermanita menor!", "Kyousuke"),
    45: ("...Haré que lo juegues conmigo.", "Kyousuke"),
    46: ("¡¿*jadeo*?!", "Kirino"),
    47: ("¡Espera, no agarres el bate! ¡Escúchame!", "Kyousuke"),
    48: ("¡I-Idiota! ¡Si me golpeas con el bate moriré, ¿sabes?!", "Kyousuke"),
    49: ("¡Por eso lo tenía conmigo!", "Kirino"),
    50: ("P-Pervertido... Antes de que me atrapes, yo te atraparé a ti...", "Kirino"),
    51: ("¡No, ¿qué clase de lógica de supervivencia es esa?!", "Kyousuke"),
    52: ("¡Cállate! ¡Idiota! ¡Pervertido!", "Kirino"),
    53: ("¡T-Te dije, no? Era algo realmente vergonzoso que no quería hacer sin importar qué!", "Kyousuke"),
    54: ("¡¿No es eso obvio?! Para empezar, jugar un juego de hermanitas con tu hermanita... N-No hay manera.", "Kirino"),
    55: ("N-No hay más remedio, ¿verdad? No quedan otras maneras excepto esta.", "Kyousuke"),
    57: ("E-Esto es.", "Kyousuke"),
    58: ("¿Huh? ¿Un reproductor de música?", "Kirino"),
    59: ("Sí, hay una canción denpa en él.", "Kyousuke"),
    60: ("¿Huh? ¿Qué estás diciendo a estas alturas? Ya he escuchado eso muchas veces.", "Kirino"),
    61: ("No, hay algo llamado el efecto subliminal, ¿verdad? Los resultados podrían ser diferentes si lo repitieras muchas veces.", "Kyousuke"),
    62: ("Tan persistente.", "Kirino"),
    63: ("¡Por favor! ¡Te lo ruego! ¡Por favor, Kirino-san!", "Kyousuke"),
    64: ("¡N-No quiero! No te acerques aquí.", "Kirino"),
    65: ("¡Te lo ruego de verdad!", "Kyousuke"),
    66: ("T-Te mataré si te acercas más.", "Kirino"),
    67: ("...Así que, no funcionó al final.", "Kyousuke"),
    73: ("¡Maldición, lo haré!", "Kyousuke"),
    74: ("¡Contempla, este es mi último recurso--!", "Kyousuke"),
}

a123_n = {
    0: "Ruta de Kirino · No Hay Más Opción Que Usar Mi Último Recurso Con Mi Hermanita",
    2: "E-Esta mocosa, en realidad dijo algo que crearía un malentendido serio si nuestros padres lo escucharan.",
    7: "¡Ah, Dios! Este desarrollo es el mismo que pasó al principio...",
    33: "Gah, me cortó mi frase de golpe seguro así nomás...!",
}
a123_s = {
    1: ("¡¿Q-Qué estás tratando de mostrarme?! ¡A-Apúrate y guárdalo!", "Kirino"),
    3: ("No es realmente algo que tengas que rechazar hasta ese punto, ¿verdad? Ahora entonces, apurémonos y juguemos «SisXSis».", "Kyousuke"),
    4: ("¡Y-Ya te dije que no me mostraras eso! ¡¡Pervertido!!", "Kirino"),
    5: ("¿Quién es el pervertido? Esto es algo que te gustaba mucho en el pasado.", "Kyousuke"),
    6: ("¡No hay manera de que eso sea posible! ¿Estás loco?", "Kirino"),
    8: ("...Perdón, Kirino. No tienes el derecho a decir que no.", "Kyousuke"),
    9: ("¡¿Por qué estás tan confiado esta vez?!", "Kirino"),
    10: ("Es como lo que dice esa estudiante de primaria con cerebro de adulta. Solo hay una verdad.", "Kyousuke"),
    11: ("No importa cuánto lo niegues, el pasado no puede cambiarse. ¡Amabas «SisXSis» tanto que era como si adoraras a un dios!", "Kyousuke"),
    12: ("¡Mentiras! ¡Mentiras, mentiras, mentiras! Solo estás tratando de engañarme y convertirme en una pervertida como tú, ¿no?!", "Kirino"),
    13: ("¡No estoy mintiendo! ¡Todo es verdad! ¡Mírame a los ojos!", "Kyousuke"),
    14: ("No me apuntes con esos ojos de pez muerto.", "Kirino"),
    15: (".........", "Kyousuke"),
    16: ("T-Te dije que pararas...", "Kirino"),
    17: ("No me mires fijamente de esa manera significativa.", "Kirino"),
    18: ("No te miraré si dices que jugarás el juego.", "Kyousuke"),
    19: ("Guhh... Pero, todavía es demasiado...", "Kirino"),
    20: ("No, simpatizo contigo... pero es toda la verdad.", "Kyousuke"),
    21: ("Odio esa idea. No lo admitiré.", "Kirino"),
    22: ("Dijiste que no lo admitirías... En serio, desearía poder grabar esa línea que dijiste hace un momento y reproducírsela a la «tú» de hace un año.", "Kyousuke"),
    23: ("Guh... Desearía poder darle un puñetazo noqueador a mi yo del pasado...", "Kirino"),
    24: ("Escucha, este «SisXSis» fue el único regalo que me diste.", "Kyousuke"),
    25: ("Sin embargo, no lo he completado y frecuentemente me regañas para que me apure y lo termine.", "Kyousuke"),
    26: ("...Tú eres la que me dijo que lo jugara. Por eso, te estoy diciendo que hagas lo mismo ahora.", "Kyousuke"),
    27: ("Completa la «ruta de Rinko» junto conmigo.", "Kyousuke"),
    28: ("¡No. Quiero. Hacerlo!", "Kirino"),
    29: ("¡Tú eres la que me dijo «atesorarlo como si fuera yo», ¿sabes?!", "Kyousuke"),
    30: ("¡No! Esa persona podría ser yo, pero ciertamente no soy yo!", "Kirino"),
    31: ("¡No digas cosas tan egoístas! ¡¿No dijiste una vez que eres tú misma?!", "Kyousuke"),
    32: ("¡Ahh, es demasiado complicado!", "Kyousuke"),
    34: ("O-Oye, este es mi último recurso aquí. No hay otra alternativa.", "Kyousuke"),
    35: ("¿Huh? ¿Tu último recurso? Mejor esfuérzate más y encuentra otra manera.", "Kirino"),
    36: ("En cualquier caso, ¡no quiero hacer esto!!", "Kirino"),
    37: ("En cualquier caso, no lo jugaré. No es no.", "Kirino"),
    38: ("¡No digas cosas tan infantiles! ¡Eso no servirá!", "Kyousuke"),
    39: ("Entiendo eso... sin embargo...", "Kirino"),
    40: ("Mírame, Kirino.", "Kyousuke"),
    41: ("¿Alguna vez te he mentido desde que perdiste tus recuerdos? Nunca te he mentido, estoy seguro de que ya lo sabes, ¿verdad?!", "Kyousuke"),
    42: ("...Definitivamente soy tu aliado.", "Kyousuke"),
    43: ("Guh...", "Kirino"),
    44: ("...Kirino, ¿hablas en serio?", "Kyousuke"),
    45: ("Incluso así, creo que hice mi mejor esfuerzo por tu bien.", "Kyousuke"),
    46: ("Si rechazas esto, no hay nada más que pueda hacer.", "Kyousuke"),
    47: ("E-Esas palabras... no son justas...", "Kirino"),
    48: ("Ya no me importa... Honestamente estoy cansada de esto...", "Kirino"),
    49: ("Incluso si mis recuerdos no vuelven, mientras actúe apropiadamente, no debería molestarte a ti ni a esas amigas otaku, ¿verdad?", "Kirino"),
    50: ("Ese tipo de actuación... probablemente no funcionará para siempre, ¿verdad? Tarde o temprano, ¿no serás expuesta seguramente?", "Kyousuke"),
    51: ("Si eso pasa, no solo te lastimarás tú, sino también ellas.", "Kyousuke"),
    52: ("¿Por qué tienes que decir esas cosas...", "Kirino"),
}

a125_n = {
    0: "Ruta de Kirino · No Hay Más Opción Que Usar Mi Último Recurso Con Mi Hermanita",
    5: "Tch... Puedo ver claramente que estás evitando deliberadamente el tema.",
    6: "Sin embargo...",
    9: "Sé que Kirino está empezando a rendirse en recuperar sus recuerdos.",
    10: "Y si realmente hiciera eso, sus recuerdos desaparecerían para siempre. Eso es lo que siento.",
    11: "Por esa razón, no puedo rendirme aquí.",
    21: "Después de un rato, Kirino simplemente dijo eso y cerró la boca.",
    22: "1: Inesperadamente, el almuerzo de Rinko sabía mejor. 2: Por supuesto, el almuerzo de Miyabi sabía mejor.",
    23: "Esta es la primera elección en «SisXSis».",
    24: "Dato curioso, cuando jugué este juego con Kirino antes, ella se negó vehementemente a entrar en la «ruta de Rinko» por alguna razón y eligió a Miyabi en su lugar.",
    26: "...Incluso así, Kirino no ha dicho una palabra por un rato. ¿Qué le pasó?",
    35: "...¿Qué quiere decir con eso, en otras palabras?",
    40: "Tch... Esta chica. Obviamente todavía me está ridiculizando irrazonablemente.",
    47: "*suspiro*, también sé que estoy diciendo cosas realmente absurdas aquí.",
    48: "Sin embargo, me di cuenta mientras gritaba.",
    49: "La razón real por la que estoy tan desesperado aquí...",
    54: "...Esta mocosa, parece que no lo entenderá si no lo digo claramente.",
    67: "Ahh... ¿Está en su modo confrontacional perverso otra vez?",
    68: "Dios, ¿por qué esta chica cabezadura no lo entiende?",
    77: "Kirino hinchó el pecho, sin rastros de duda o debilidad en ella ya.",
    78: "Era exactamente como la hermanita totalmente impecable que yo conocía.",
    80: "Esta también es Kirino.",
    81: "Lo que puedo hacer es... simplemente vigilarla.",
    87: "Kirino... Está completamente abrumada por mi explosiva franqueza.",
    88: "...Sin embargo, ¿por qué su cara está ligeramente roja?",
    91: "¡Está bien, es hora de que empiece el partido real!",
    104: "Bueno entonces, realmente nos desviamos del tema hace un momento. Es hora de empezar el juego ya.",
    105: "Me enfrento a la pantalla del juego una vez más y suavemente empiezo a mover el mouse.",
    106: "...No presté especial atención a la mirada que se quemaba en mi espalda.",
    109: "Sentados lado a lado frente a la computadora así me recuerda al día antes de que Kirino se fuera a estudiar al extranjero.",
    110: "Kirino está frunciendo el ceño un poco, pero bueno, todo esto es para recuperar sus recuerdos. No me preocuparé por ello.",
    111: "Eso es porque, este realmente es el último recurso.",
    112: "Este «SisXSis» es el último hilo de esperanza que me conecta con los recuerdos perdidos de Kirino.",
    113: "Parece que el contenido del juego ha cambiado, las elecciones que seleccioné cuando jugué el juego la última vez están resaltadas en un color diferente.",
    114: "Solo completé el juego una vez, así que no sabía que esto pasaría.",
    115: "En otras palabras, estas elecciones resaltadas deben ser la ruta que Kirino eligió antes.",
    116: "Además, según las elecciones seleccionadas, parece que fueron de cuando persiguió a «Rinko».",
    117: "Lo que significa, podríamos entrar en la ruta de Rinko mientras sigamos fielmente estas. Eso es un poco increíble.",
    121: "Y entonces, mientras continuábamos jugando el juego, finalmente empecé a entender por qué Kirino evitaba la «ruta de Rinko».",
    122: "Y, hay algo que noté vagamente cuando jugué la «ruta de Miyabi» la última vez, y confirmé mientras jugaba ahora la «ruta de Rinko».",
    123: "Esta hermanita llamada «Rinko» es exactamente igual a Kirino.",
    124: "No, no me refiero a sus sentimientos internos. Me refiero a su actitud hacia el héroe.",
    125: "Bueno, puedo ver por qué Kirino quiere evitarla. Ya que completar la «ruta de Rinko» significa que Rinko y el héroe se enamoran el uno del otro al final.",
    126: "¡Jugar algo así con mi hermanita a mi lado va más allá de lo incómodo, es peligroso!",
    127: "¡Espera, ¿no es esa la situación actual?!",
    129: "N-No es bueno... Seguiré jugando el juego con la mente vacía de este punto en adelante.",
    130: "...Honestamente, el contenido de la historia es bastante común.",
    131: "De repente cohabitando con sus hermanitas perdidas hace mucho tiempo, el héroe no sabe cómo tratar a «Rinko».",
    132: "Al desarrollar una conexión con su otra hermanita «Miyabi», la distancia entre el héroe y «Rinko» gradualmente se vuelve más cercana.",
    133: "La relación entre ellos se vuelve íntima, incluso fugándose, pero el héroe pierde el conocimiento justo antes de eso debido a una condición crítica.",
    134: "Por otro lado, «Rinko» es traída de vuelta por sus padres y enviada al extranjero para estudiar.",
    135: "Para despedirse de su hermano mayor, va al hospital sola, pero...",
    137: "¿Q-Qué es este líquido que corre por mis mejillas...",
    138: "¡¿E-E-E-Estoy llorando? ¿Por jugar un juego bishoujo...?!",
    139: "N-No, pero... esto no puede evitarse, ¿verdad?",
    140: "Miré de vuelta a la pantalla mientras el juego entra en su clímax.",
    141: "Debido a un repentino accidente de tráfico, «Rinko» ha olvidado al héroe.",
    142: "¿Qué pasa con esto, no es esto exactamente igual a mi situación actual?",
    143: "Cuando ve al héroe luchando desesperadamente por su bien, «Rinko» se frustró por sus recuerdos perdidos.",
    144: "Así como me veo a mí mismo como el héroe, ¿Kirino también se ve a sí misma como Rinko...?",
    146: "...¿Qué es este sentimiento...? Un sentimiento inexplicable brotó desde las profundidades de mi pecho...",
    154: "¡Maldición! ¿Por qué mis lágrimas no dejan de fluir...? No puedo ver la expresión de Kirino a este paso.",
    156: "Gracias por restaurar mi cordura, querida hermana.",
    157: "Maldición, Kirino tiene razón. ¿Por qué estoy diciendo cosas tan vergonzosas calmadamente?",
    169: "Si no me equivoco, Saori lo había mencionado antes.",
    170: "Poco antes de que Kirino perdiera sus recuerdos, estaba peleando con Kuroneko sobre cierta línea de Rinko en «SisXSis».",
    172: "N-No puedo recordarlo. ¿Cómo pude olvidarlo en un momento así?",
    176: "...¿Huh?",
    177: "Esta chica, ¿qué fue lo que dijo?",
    181: "E-Espera. Todavía solo ha recordado esa línea particular de «Rinko». Podría ser una coincidencia. Esperemos su reacción.",
    191: "¡Uwoh! ¡Su humor ha dado un giro brusco para peor?!",
    199: "...Tch... Está usando su lenguaje abusivo mientras hace una cara agria...",
    200: "Es su misma cara molesta de siempre, pero ¿por qué se ve tan linda ahora?!",
    210: "Esta vez, cerró la puerta de verdad.",
    211: "Me quedé de pie ahí, atónito, mientras sostenía la laptop que me dio en una mano.",
    218: "¿Por qué estás tan eufórica al respecto...",
    219: "No... Espera, ¿no es esto...",
    220: "En resumen, ¿estás diciendo que no puedes aceptar psicológicamente los juegos bishoujo y simplemente no puedes soportar jugar un juego de hermanita moe con tu detestable hermano",
    221: "mayor, verdad?",
    222: "SisXSis. Una historia loca con un triángulo amoroso alrededor del héroe y sus dos hermanitas, la descarada pero torpe Rinko, la gentil y dócil",
    223: "Miyabi.",
    224: "El héroe actúa fríamente con ella como un extraño, volviéndose ocupado mientras trata de ayudar a «Rinko» a recuperar sus recuerdos perdidos, mientras está agotado tanto en cuerpo como en",
    225: "mente.",
    226: "Ella no puede recuperar sus recuerdos. El hermano se está desgastando cada vez más día a día también. Eso hizo que «Rinko» cayera en el autodesprecio y cerrara su",
    227: "corazón.",
}
a125_s = {
    1: ("Te lo ruego, por favor persigue a «Rinko» junto conmigo.", "Kyousuke"),
    2: ("El matiz de tus palabras ha cambiado sutilmente.", "Kirino"),
    3: ("...N-No, solo pensé que podría no gustarte cómo lo dije la primera vez.", "Kyousuke"),
    4: ("¡Ese no es el problema aquí! ¿No lo entiendes?", "Kirino"),
    7: ("Ahora no es el momento de ser exigente con los métodos.", "Kyousuke"),
    8: ("...?", "Kirino"),
    12: ("¿Q-Qué? No te importé en absoluto hasta ahora, así que ¿por qué de repente...?", "Kirino"),
    13: ("Humph, en realidad no es por tu bien.", "Kyousuke"),
    14: ("¿Eh?", "Kirino"),
    15: ("No lo malinterpretes. Tampoco es por mi bien. Simplemente te estoy haciendo compañía como tu hermano mayor hasta el final.", "Kyousuke"),
    16: ("E-Entonces, ¿por qué te entrometes así?", "Kirino"),
    17: ("...Por el bien de mi hermanita.", "Kyousuke"),
    18: ("?!", "Kirino"),
    19: ("...Por eso, juguemos «SisXSis». Kirino.", "Kyousuke"),
    20: ("Haz... Haz lo que quieras.", "Kirino"),
    25: ("Así que, esta vez, elegí a Rinko...", "Kyousuke"),
    27: ("Oye...", "Kirino"),
    28: ("¿Hm?", "Kyousuke"),
    29: ("...¿De verdad quieres tanto que recupere mis recuerdos?", "Kirino"),
    30: ("Por supuesto que sí. Si te quedas así, será desalentador para Saori, Kuroneko y también Ayase.", "Kyousuke"),
    31: ("¿Sabes cuántos problemas causaste por tus aficiones? Olvidar eso es demasiado injusto, ¿verdad?", "Kyousuke"),
    32: ("...Entiendo.", "Kirino"),
    33: ("¿Entender... qué?", "Kyousuke"),
    34: ("Que estás trabajando tan duro por el bien de mí, esas personas otaku, y también Ayase.", "Kirino"),
    36: ("Sé que no te importan esos recuerdos. Ahora mismo, los intereses otaku son simplemente asquerosos para ti, ¿verdad?", "Kyousuke"),
    37: ("...¿Y-Y qué?", "Kirino"),
    38: ("Aunque es una lástima para Saori y Kuroneko, siento que no hay más remedio. Sin embargo, no puedo aceptar que nos trates como extraños solo por eso.", "Kyousuke"),
    39: ("¿Huh? Hablar de «tratarte como un extraño» a estas alturas... Eso suena tan pretencioso.", "Kirino"),
    41: ("Cállate, estoy muy herido.", "Kyousuke"),
    42: ("Escucha bien, sin importar si has perdido tus recuerdos, o lo que sea que hayas olvidado, ese no es el problema.", "Kyousuke"),
    43: ("Tú... ¿Sabes lo que acabas de decir? ¿No quieres volverme a convertir en una otaku?", "Kirino"),
    44: ("¡¡Ya dije que no es eso!!", "Kyousuke"),
    45: ("?!", "Kirino"),
    46: ("Ah, perdón. Mi voz se alzó un poco ahí...", "Kyousuke"),
    50: ("Escucha, lo importante es... que tu afición fue la cosa que nos hizo empezar a cambiar.", "Kyousuke"),
    51: ("Por tus intereses otaku, pudiste obtener a Kuroneko y Saori como nuevas amigas.", "Kyousuke"),
    52: ("Incluso Ayase, aunque ambas tuvieron una gran pelea por ello al principio, aceptó a la «Kirino otaku» al final.", "Kyousuke"),
    53: ("...Entonces, ¿qué estás tratando de decir? ¿Por qué quieres interferir?", "Kirino"),
    55: ("Porque yo también he cambiado.", "Kyousuke"),
    56: ("¿Eh...", "Kirino"),
    57: ("Hice nuevas amistades gracias a conocer tu afición, y también me di cuenta de las cosas con las que soy malo.", "Kyousuke"),
    58: ("Y siento que incluso mi relación contigo mejoró un poco.", "Kyousuke"),
    59: ("Todos nosotros pasamos por estos cambios y los superamos mientras pasábamos tiempo contigo.", "Kyousuke"),
    60: ("Si negaras eso, ¿qué se supone que debemos hacer?", "Kyousuke"),
    61: ("Eso es... Eso es solo por la conveniencia de ustedes.", "Kirino"),
    62: ("¿Por qué no tengo más remedio que volver a convertirme en una otaku, solo para poder acomodar a todos ustedes?", "Kirino"),
    63: ("¡No hay manera de que pueda aceptar algo tan irrazonable!", "Kirino"),
    64: ("...¿Por qué estás tan obsesionado con esto... aunque siempre me ignoraste?", "Kirino"),
    65: ("¡¿Qué importan mis recuerdos o lo que sea a estas alturas?!", "Kirino"),
    66: ("¡Como si yo actuara tan desesperadamente por alguien que no me importa en absoluto!", "Kyousuke"),
    69: ("Entonces, ¿por qué estoy tratando de ayudarte a recuperar tus recuerdos hasta el punto de tener que actuar tan lastimosamente aquí?", "Kyousuke"),
    70: ("¿Cuántas veces crees que me has golpeado hasta ahora desde que perdiste tus recuerdos? Lo diré por si acaso, pero no soy tanto de un M.", "Kyousuke"),
    71: ("¡Cállate! ¡Solo estás diciendo lo que quieres! ¡Sin siquiera saber cómo me siento!", "Kirino"),
    72: ("¡También estoy inquieta y ansiosa! ¡Sé que esas amigas otaku están seriamente preocupadas por mí!", "Kirino"),
    73: ("...Lo admitiré. Estoy impaciente. Preocupada. ¡Tan inquieta que estoy al borde del llanto!", "Kirino"),
    74: ("...¿K-Kirino?", "Kyousuke"),
    75: ("Pero, no te pediré ayuda. ¡Como si lo hiciera! ¡Soy Kirino Kousaka! Por eso...", "Kirino"),
    76: ("¡Haré lo que quieras con mi propia fuerza! ¡Solo mira!", "Kirino"),
    79: ("*suspiro*... No hay más remedio entonces.", "Kyousuke"),
    82: ("¡Maldición! Solo lo diré una vez...", "Kyousuke"),
    83: ("¡Escucha bien! ¡Eres la persona más importante para mí!", "Kyousuke"),
    84: ("...¿Huh? Espera, ¿qué estás diciendo?", "Kirino"),
    85: ("¿Qué tal, ríete de mí por ser un siscon pervertido! ¡Soy un siscon hardcore! ¡No, soy un siscon de los más empedernidos! ¡¿Estás asombrada?!", "Kyousuke"),
    86: ("Uh... ¿Ah? ...¿Eh?", "Kirino"),
    89: ("L-Lo entiendo. ¡Está bien si solo juego, ¿verdad?! Sin embargo, no sé si mis recuerdos volverán o no!", "Kirino"),
    90: ("...Dios mío. ¿Qué pasó durante este año? ¿Te llevabas tan bien con la yo del pasado? Eso es imposible...", "Kirino"),
    92: ("No me ves como un hermano mayor, ¿verdad? No me importa. Soy ampliamente conocido como un fracaso de hermano mayor, después de todo.", "Kyousuke"),
    93: ("T-Te pusiste serio de repente.", "Kirino"),
    94: ("¡Aun así, sigo siendo tu hermano mayor! ¡No puedo evitar preocuparme como loco por la hermanita que tanto odio!", "Kyousuke"),
    95: ("H-Hermanita, hermanita, sigues diciendo eso... ¡No empieces a actuar como un hermano mayor solo en momentos así!", "Kirino"),
    96: ("¡Cállate! ¡Lo seguiré diciendo una y otra vez!", "Kyousuke"),
    97: ("¡Soy el hermano mayor de Kousaka Kirino! ¡Tu verdadero hermano mayor! ¡Nada más, nada menos! ¡¿Tienes algún problema con eso?!", "Kyousuke"),
    98: ("¡Y ser un hermano mayor significa que cuando veo a mi hermanita preocupada, tengo que ayudarla sin importar qué!", "Kyousuke"),
    99: ("P-Pero no estoy particularmente preocupada.", "Kirino"),
    100: ("No trates de ocultarlo. Lo entiendo. Entiendo que te estás forzando ahora mismo.", "Kyousuke"),
    101: ("...", "Kirino"),
    102: ("¿P-Por qué piensas eso...?", "Kirino"),
    103: ("Eso es obvio. Porque soy tu hermano mayor.", "Kyousuke"),
    107: ("...Mi hermano mayor no puede ser...", "Kirino"),
    108: ("...no puede ser... tan genial...", "Kirino"),
    118: ("¿Cómo está...? ¿Has recordado algo?", "Kyousuke"),
    119: ("Como si pudiera ser tan fácil. Solo que... siento que la «yo actual» elegiría esto.", "Kirino"),
    120: ("...Ya veo.", "Kyousuke"),
    128: ("......?!", "Kirino"),
    136: ("...¡¿Ah?!", "Kyousuke"),
    145: ("...*sniff*.", "Kirino"),
    147: ("...Kirino... ¿Podrías pausar por un momento?", "Kyousuke"),
    148: ("¿Eh...?", "Kirino"),
    149: ("Yo... de verdad me gusta la tú actual que está frente a mí.", "Kyousuke"),
    150: ("......?!", "Kirino"),
    151: ("Sin embargo, tus recuerdos perdidos son igual de importantes... ¡por eso no quiero rendirme en ninguno de los dos!", "Kyousuke"),
    152: ("Así que por favor... te lo ruego... por favor recuerda... tus... nuestros... preciosos... preciosos recuerdos...", "Kyousuke"),
    153: ("..........", "Kirino"),
    155: ("..................Asqueroso.", "Kirino"),
    158: ("Uh... P-Perdón... Parece que perdí la compostura por un momento ahí...", "Kyousuke"),
    159: ("Además... ¡tu hombro me ha estado tocando desde antes! ¡Pervertido! ¡¡Siscon!!", "Kirino"),
    160: ("...Estoy segura de que soltaste esa torpe confesión hace un momento porque fuiste influenciado por el juego, ¡pero no entiendes la historia de Rinko-rin en absoluto!", "Kirino"),
    161: ("...¿Eh?", "Kyousuke"),
    162: ("Escucha bien. Rinko-rin amaba a su hermano mayor desde que era una niña.", "Kirino"),
    163: ("Pero debido a un incidente, sus sentimientos hacia su hermano se volvieron complejos, y antes de que se diera cuenta, dejó de notar sus propios verdaderos sentimientos.", "Kirino"),
    164: ("Aunque Rinko-rin perdió sus recuerdos, al ver a su dedicado hermano dando todo por su bien, sus sentimientos latentes en el fondo de su corazón despertaron.", "Kirino"),
    165: ("Habiendo perdido sus recuerdos, pero recordando sus sentimientos, Rinko-rin reunió su coraje para confesarse con su hermano mayor. Esa línea fue...", "Kirino"),
    166: ("...¡O-Oye! ¡E-Espera un minuto!", "Kyousuke"),
    167: ("¿Q-Qué, estoy en una de las mejores partes!", "Kirino"),
    168: ("No, creo que probablemente conozco esa misma línea.", "Kyousuke"),
    171: ("Eso es... erm, es eso... ¡esa cosa!", "Kyousuke"),
    173: ("¡Agh, ¿por qué lo olvidaste?!!! Es obviamente «Siempre te he amado, siempre te he amado»! ¡Así que todavía no lo has jugado!", "Kirino"),
    174: ("P-Perdón...", "Kyousuke"),
    175: ("¡Siempre eres así! Aunque te lo di como regalo...", "Kirino"),
    178: ("¡K-Kirino... ¿Por qué recuerdas la frase característica de la ruta de Rinko...?!", "Kyousuke"),
    179: ("...Ah.", "Kirino"),
    180: ("No me digas... ¿volvieron tus recuerdos?", "Kyousuke"),
    182: ("Ah...Ah...Ah... Y-Y-Y-Y-Y-Yo...", "Kirino"),
    183: ("¡C-C-C-C-C-C-Cállate! ¡Sal de aquí!", "Kirino"),
    184: ("¡Guh!", "Kyousuke"),
    185: ("E-Eso duele... ¿P-Por qué me pateaste hace un momento?", "Kyousuke"),
    186: ("Imposible, imposible, imposible, imposible...", "Kirino"),
    187: ("E-Erm... ¿Kirino? ¿Estás bien?", "Kyousuke"),
    188: ("......", "Kirino"),
    189: ("E-Entonces al final, ¿volvieron tus recuerdos? ¿O no?", "Kyousuke"),
    190: ("...Cállate. Quédate callado.", "Kirino"),
    192: ("...Bueno, eso es todo.", "Kirino"),
    193: ("E-Espera... No... ¡No cierres la puerta!", "Kyousuke"),
    194: ("¡Tch!", "Kirino"),
    195: ("¿K-Kirino...?", "Kyousuke"),
    196: ("...volvieron.", "Kirino"),
    197: ("¿Eh?", "Kyousuke"),
    198: ("¡Mis recuerdos han vuelto! ¡¿Tienes algún problema con eso?!", "Kirino"),
    201: ("Genial... Genial... Kirino...", "Kyousuke"),
    202: ("¡C-Cállate! ¡¿Qué te pasa, diciendo cosas asquerosas con una cara asquerosa llorosa?!", "Kirino"),
    203: ("¿Asqueroso, dices...? N-No puedo evitarlo, mis lágrimas no paran.", "Kyousuke"),
    204: ("Ah, eres realmente molesto. Espera aquí un momento.", "Kirino"),
    205: ("...¿Eh?", "Kyousuke"),
    206: ("Aquí, toma esto.", "Kirino"),
    207: ("Umm... ¿Esto es?", "Kyousuke"),
    208: ("D-De todos modos... Solo déjame sola por el resto del día.", "Kirino"),
    209: ("¡Y mejor completa rápidamente todo «SisXSis», idiota!!", "Kirino"),
    212: ("Pff... Jeje.", "Kyousuke"),
    213: ("Jajaja... Bueno, al final, resultó así.", "Kyousuke"),
    214: ("Así es, era «Siempre te he amado, siempre te he amado».", "Kyousuke"),
    215: ("¡?! ¡Así es! ¿Qué, entonces sí lo entiendes!", "Kirino"),
    216: ("Adiós... Hermano mayor, 【siempre te he amado, siempre te he amado】.", "Rinko"),
    217: ("¡Mira! ¿Qué tal fue eso, la valiente línea de Rinko-rin?! ¡Es tan conmovedora que hace llorar a la gente... De hecho, ¿no es simplemente divina?!", "Kirino"),
}

a130_n = {
    0: "Ruta de Kirino · Es Imposible Que Mi Hermanita Me Esté Ignorando",
    2: "Como pensé, la familia Tamura es realmente agradable. Solo pasé un tiempo en su lugar sin mi hermana, y ahora mi cuerpo se siente rejuvenecido.",
    4: "En la sala de estar, Kirino estaba jugando God Eater sola.",
    5: "Es una vista que he visto todos los días antes del viaje escolar, y también una vista que nunca pude ver mientras Kirino estaba amnésica.",
    6: "Ahh, así que con eso, esta orientación de vida ha llegado a su fin, eh.",
    7: "Honestamente, el hecho de que Kirino hubiera recuperado sus recuerdos todavía se sentía como un sueño para mí, pero mirándola ahora, finalmente se siente real.",
    8: "Está bien, supongo que volveré a mi habitación sin ser notado por mi hermanita...",
    11: "Tch... Y aquí pensé que sería malo si interrumpía tu concentración jugando.",
    12: "Más bien, ya que me hiciste decirlo, ¿qué tal si también me dices «Bienvenido a casa»?",
    14: "...Sí, sí.",
    20: "...Siento que se me cayó la mandíbula.",
    21: "Kirino inmediatamente giró su cabeza, mirando hacia otro lado.",
    22: "¿Huh...? Algo se balanceó en el borde de su consola de juegos portátil...",
    24: "¿Qué es eso? Normalmente la gente no colocaría esa clase de cosa ahí, ¿verdad?",
    25: "...La Meruru de Edición Regional de Kioto...",
    28: "No puedo descifrar si ese gesto de gratitud fue solo por jugar el juego con ella antes o por ayudarla a recuperar sus recuerdos.",
    29: "De cualquier manera, las orejas de Kirino estaban rojas brillantes mientras continuaba mirando hacia otro lado de mí...",
}
a130_s = {
    1: ("Ah, ha pasado mucho tiempo desde que tuve unas vacaciones tan relajantes～.", "Kyousuke"),
    3: ("...¿Hmm?", "Kyousuke"),
    9: ("Alto ahí, ¿dónde están tus saludos?", "Kirino"),
    10: ("Ya llegué...", "Kyousuke"),
    13: ("¡Entonces, vuelve a bajar después de dejar tus bolsos! Hay algunas cosas que quiero.", "Kirino"),
    15: ("Ah, y también...", "Kirino"),
    16: ("¿Qué es?", "Kyousuke"),
    17: ("...racias.", "Kirino"),
    18: ("¿Huh?", "Kyousuke"),
    19: ("...Como dije! Bueno... Gracias.", "Kirino"),
    23: ("Pff...", "Kyousuke"),
    26: ("...¿Qué?", "Kirino"),
    27: ("No, nada.", "Kyousuke"),
}

data = {
    "000scriptBKIR_0115A.obj": build(a115_n, a115_s),
    "000scriptBKIR_0120A.obj": build(a120_n, a120_s),
    "000scriptBKIR_0123T.obj": build(a123_n, a123_s),
    "000scriptBKIR_0125A.obj": build(a125_n, a125_s),
    "000scriptBKIR_0130G.obj": build(a130_n, a130_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
