import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

T = "if · Un Cierto Misterio En Kioto"

n = {
    0: T,
    7: "¿Qué estamos haciendo dos chicos juntos...?",
    14: "Se suponía que sería una caminata corta por la posada con Akagi por un rato, pero...",
    15: "La exploración de la posada terminó bastante rápido.",
    16: "El edificio en sí no era muy grande, y tampoco tenía ningún lugar particularmente extraño.",
    17: "Por supuesto, esto era más o menos lo esperado.",
    18: "No habrá nada raro en una posada tan normal... ¿Verdad?",
    19: "Y como era de esperar-",
    31: "Miré en la dirección de dicha puerta, a la que Akagi estaba señalando.",
    32: "Cierto, estaba allí: la puerta que aún no habíamos abierto.",
    33: "...¿Pero esa puerta siquiera estaba allí antes?",
    38: "La puerta desprendía una sensación de antigüedad que jamás había experimentado con nada más antes.",
    39: "El pomo era súper viejo y oxidado, y la puerta misma parecía haberse vuelto casi negra de lo sucia que estaba.",
    40: "Extraño... Muy extraño...!",
    56: "...¿Eh? Espera... Algo parece... estar mal.",
    57: "Puedo entender lo que dice Akagi, pero lo escucho diciendo «Pupupu»...",
    58: "Y cuando miré a Akagi...",
    67: "...¿¡¿Qué clase de delirio es este?!?!",
    70: "Y así, impulsado de nuevo por Akagi, comencé a buscar en toda la habitación otra vez, pero...",
    80: "Akagi estaba a punto de cerrar la puerta, pero sus manos se detuvieron mientras miraba algo en la habitación.",
    83: "Akagi entró en la habitación y recogió esa pequeña cosa que se cayó.",
    84: "Parece que es...",
    103: "¿Qué es esto de Fushimi Inari Subterráneo?! ¡Es demasiado sospechoso!",
    104: "¡Se llama Fushimi Inari porque está en el área de Fushimi! ¡Y estamos en Sanjyou, Higashiyama ahora mismo!",
    105: "¡No creas todo lo que lees!",
    128: "Ciertamente, hay una puerta en el piso en la esquina de la habitación.",
    129: "Odio este tipo de deus-ex-machina descarado.",
    130: "Se siente como si estuviera en un juego o anime otra vez...",
    131: "No, esta escena probablemente sería demasiado cursi incluso para un juego de 8 bits.",
    140: "La puerta en el piso se abrió con el mismo sonido de antes.",
    143: "Había un tramo continuo de escaleras debajo de la puerta abierta.",
    144: "Esto es... ¡Esto es demasiado conveniente!",
    145: "¡Esto no es nada más que sospechoso!!!",
    146: "...pero fui el único que pensó así.",
    151: "Akagi empezó a bajar las escaleras sin escuchar ni una palabra de lo que dije.",
    152: "No puedo simplemente dejarlo ir solo...",
    153: "¡Argh, maldición! ¡No tengo otra opción!",
    155: "Después de bajar las escaleras, había un área con un techo muy alto.",
    156: "Akagi caminó adelante, mientras yo lo perseguía apresuradamente.",
    164: "Avanzamos firmemente.",
    165: "Antes de que nos diéramos cuenta, habíamos caminado bastante distancia, pero no hemos encontrado nada de interés.",
    166: "¿Fue realmente buena idea continuar hacia adelante...?",
    167: "Miré hacia atrás, pero las escaleras de antes ya no eran visibles.",
    168: "Lo que se arrastraba detrás de nosotros no era más que oscuridad.",
    169: "Probablemente ya hemos recorrido un buen trecho.",
    177: "¿Por qué hay una puerta de santuario bajo tierra...!?",
    183: "Con esta escena frente a mí, ya no puedo negar la existencia del Fushimi Inari Subterráneo.",
    184: "Akagi está todo emocionado, y yo también me estoy poniendo un poco emocionado...",
    187: "El sinuoso camino de puertas continuaba para siempre.",
    188: "Ya no tenía ningún sentido de la dirección; ni tenía idea de dónde estaba.",
    196: "Un pequeño santuario se alzaba más allá de las puertas.",
    197: "Pero... se ve un poco sucio e inútil.",
    198: "Pero Akagi se veía realmente seguro de que nuestros deseos podían cumplirse.",
    202: "Akagi se paró frente al pequeño santuario. Con una mirada seria en su rostro, juntó las manos e inclinó la cabeza.",
}
s = {
    1: ("¿Qué estás diciendo que encontraremos explorando?", "Kyousuke"),
    2: ("Puede que encontremos algo, o nada en absoluto.", "Akagi"),
    3: ("Sigues declarando lo increíblemente obvio.", "Kyousuke"),
    4: ("Cállate. No tenemos nada que hacer ahora mismo, así que ¿por qué no?", "Akagi"),
    5: ("Bueno, no puedo discutir contra eso. Como sea, te acompañaré.", "Kyousuke"),
    6: ("¡Muy bien! ¡Exploremos la posada entonces!", "Akagi"),
    8: ("Ahora bien, ¡empecemos desde este pasillo!", "Akagi"),
    9: ("Bueno, es estándar empezar desde una esquina.", "Kyousuke"),
    10: ("¡Así es! ¡Ya es un hecho bien establecido que las esquinas de los pasillos de los edificios guardan secretos desagradables!", "Akagi"),
    11: ("...¿Oh en serio?", "Kyousuke"),
    12: ("Vamos, ¡vayamos!", "Akagi"),
    13: ("Muy bien, muy bien...", "Kyousuke"),
    20: ("No hay nada...", "Akagi"),
    21: ("El que sugirió explorar este lugar fuiste tú, ¿no?", "Kyousuke"),
    22: ("Bueno, eso es cierto, pero es Kioto ¿no? Esperaba encontrar algo aquí...", "Akagi"),
    23: ("Es precisamente porque es Kioto, que los espíritus de los ríos tendrían problemas para aparecer aquí!", "Kyousuke"),
    24: ("Bueno, eso mató el tiempo. Aunque fue realmente improductivo.", "Kyousuke"),
    25: ("No, ¡todavía no!", "Akagi"),
    26: ("¿Todavía estás planeando algo...?", "Kyousuke"),
    27: ("No hemos recorrido todo, ¿verdad?", "Akagi"),
    28: ("¿Eso importa?", "Kyousuke"),
    29: ("¡Sí! ¡No hemos abierto esa puerta todavía, ¿verdad!", "Akagi"),
    30: ("¿Puerta?", "Kyousuke"),
    34: ("No hemos mirado allí, ¿verdad?", "Akagi"),
    35: ("Es una puerta inusualmente vieja.", "Kyousuke"),
    36: ("Sí. Extrañamente común.", "Akagi"),
    37: ("Sí...", "Kyousuke"),
    41: ("...¿De verdad la vamos a abrir?", "Kyousuke"),
    42: ("¿Huh? Qué estás diciendo, por supuesto que la abriremos.", "Akagi"),
    43: ("¿Siquiera has pensado en lo que podría pasar si la abrimos?", "Kyousuke"),
    44: ("No pasará nada. Es solo una puerta.", "Akagi"),
    45: ("Ah, cierto. Siempre fuiste así de estúpido, eh.", "Kyousuke"),
    46: ("Como sea, abramos la puerta.", "Akagi"),
    47: ("Sí.", "Kyousuke"),
    48: ("...", "Kyousuke"),
    49: ("No hay nada en esta habitación...", "Kyousuke"),
    50: ("Más bien, es solo una habitación sin luces encendidas, y no es nada diferente de una habitación normal.", "Kyousuke"),
    51: ("No hay nada aquí, ¿eh?", "Kyousuke"),
    52: ("Sí.", "Akagi"),
    53: ("...Espera, ¿qué te pasa? Habla bien.", "Kyousuke"),
    54: ("Tú también, suenas como los juegos de 8 bits de antaño.", "Akagi"),
    55: ("¡¿Huh?! ¡Pero estoy hablando bien, tú-", "Kyousuke"),
    59: ("¡T-Tú, de alguna manera te convertiste en un montón de píxeles, de repente!", "Kyousuke"),
    60: ("Jajaja. Qué extraña coincidencia. Yo te veo de la misma manera también.", "Akagi"),
    61: ("¡¿Por qué estás tan tranquilo con esto?!", "Kyousuke"),
    62: ("Ahah. Ya veo... Ahora lo entiendo.", "Akagi"),
    63: ("¿Q-Qué es?", "Kyousuke"),
    64: ("Por ventura, este es el juicio forjado sobre nuestras almas por atrevernos a perturbar un poder antiguo en Kioto.", "Akagi"),
    65: ("¡¿HUH?!", "Kyousuke"),
    66: ("¿No lo entiendes? Básicamente, este misterio se resolverá una vez que consigamos el tesoro de adentro.", "Akagi"),
    68: ("De todos modos, no podemos empezar si tú no te mueves. ¡Busquemos en esta habitación!", "Akagi"),
    69: ("¡E-Oye!", "Kyousuke"),
    71: ("¿No es esta solo una habitación normal...?", "Kyousuke"),
    72: ("Sí. Así es. ¿Qué es esto, algún truco!?", "Akagi"),
    73: ("¡Todo esto ha sido tu interpretación salvaje!", "Kyousuke"),
    74: ("Vamos a la siguiente habitación. Voy a cerrar la puerta de esta habitación.", "Akagi"),
    75: ("Sí.", "Kyousuke"),
    76: ("...¿Hm?", "Akagi"),
    77: ("¿Y ahora qué?", "Kyousuke"),
    78: ("Algo se cayó.", "Akagi"),
    79: ("¿Eh?", "Kyousuke"),
    81: ("¿Qué es eso?", "Kyousuke"),
    82: ("Quién sabe. Iré a mirar.", "Akagi"),
    85: ("¿Un folleto...? Dice «Santuario Fushimi Inari» aquí.", "Akagi"),
    86: ("Santuario Fushimi Inari, eh...", "Kyousuke"),
    87: ("Espera un segundo, esto no es exactamente Fushimi Inari, ¡¿verdad?!", "Akagi"),
    88: ("¿Entonces qué es?", "Kyousuke"),
    89: ("¡Es el Fushimi Inari Subterráneo...!", "Akagi"),
    90: ("¡¿Fushimi Inari Subterráneo?!", "Kyousuke"),
    91: ("Sí, esto se está poniendo interesante, ¿no?", "Akagi"),
    92: ("A mí me suena sospechoso.", "Kyousuke"),
    93: ("Bueno, no lo digas así. Uh... el legendario Santuario Fushimi Inari Subterráneo que puede conceder cualquier deseo...", "Akagi"),
    94: ("Todo este asunto se está volviendo más y más sospechoso...", "Kyousuke"),
    95: ("Espera. Hay más. El Santuario Fushimi Inari Subterráneo está durmiendo debajo de Kioto.", "Akagi"),
    96: ("¡¿No es eso aún más sospechoso!? Además, ¿a dónde fue toda la charla sobre el tesoro?", "Kyousuke"),
    97: ("¡El legendario Santuario Fushimi Inari Subterráneo que puede conceder cualquier deseo...!", "Akagi"),
    98: ("Oye, Akagi... ¿Estás escuchando?", "Kyousuke"),
    99: ("¡Eso es increíble! ¡Cualquier deseo puede ser concedido!", "Akagi"),
    100: ("¡Recupérate, hombre! ¡Sé realista! ¡Es demasiado bueno para ser verdad!", "Kyousuke"),
    101: ("¿Qué estás diciendo? ¡Cualquier deseo puede ser concedido, sabes!", "Akagi"),
    102: ("¡NO! ¡PARA!", "Kyousuke"),
    106: ("Está bien, ¡he decidido!", "Akagi"),
    107: ("Tengo una sensación realmente mala sobre esto...", "Kyousuke"),
    108: ("¡Voy a ir a este Fushimi Inari Subterráneo!", "Akagi"),
    109: ("Lo sabía...", "Kyousuke"),
    110: ("Por supuesto. También vienes, ¿verdad?", "Akagi"),
    111: ("¿Por qué lo haría? Es sospechoso, no importa cómo lo mire.", "Kyousuke"),
    112: ("¡¿Qué estás diciendo!? ¡Es por la emoción!", "Akagi"),
    113: ("¡No necesito ese tipo de emoción en mi vida!", "Kyousuke"),
    114: ("Cualquier deseo puede ser concedido, sabes.", "Akagi"),
    115: ("¿No suena demasiado bueno para ser verdad?", "Kyousuke"),
    116: ("¡Idiota! ¡Tienes que soñar!!", "Akagi"),
    117: ("¡¿Cómo puedo tener un sueño con un folleto así que simplemente recogiste!!", "Kyousuke"),
    118: ("¡Pero tus deseos pueden ser concedidos!", "Akagi"),
    119: ("Apuesto a que tu deseo es sobre tu relación con tu hermana de todos modos.", "Kyousuke"),
    120: ("¿Puede haber algo más?", "Akagi"),
    121: ("No respondas con una cara tan seria...", "Kyousuke"),
    122: ("Está bien, he decidido. Hagámoslo y cambiemos las leyes de Japón.", "Akagi"),
    123: ("Oye, no he dicho que iré...", "Kyousuke"),
    124: ("Oye, Kousaka, mira allí.", "Akagi"),
    125: ("¿Eh?", "Kyousuke"),
    126: ("La esquina de la habitación. La trampilla en el piso.", "Akagi"),
    127: ("¿Cómo puede haber una... espera, allí está.", "Kyousuke"),
    132: ("El Fushimi Inari Subterráneo, que descansa debajo de Kioto...", "Akagi"),
    133: ("No importa cómo lo mires, parece demasiado conveniente.", "Kyousuke"),
    134: ("Pensaremos en eso si no pasa nada.", "Akagi"),
    135: ("Oye, Akagi.", "Kyousuke"),
    136: ("Está bien, intentaré abrirla.", "Akagi"),
    137: ("¡¿Puedes ser un poco más cauteloso?!", "Kyousuke"),
    138: ("Está bien, ¡solo ayúdame!", "Akagi"),
    139: ("¡Argh en serio...!", "Kyousuke"),
    141: ("Son escaleras...", "Akagi"),
    142: ("Sí, escaleras...", "Kyousuke"),
    147: ("¡Whoa, Kousaka, es increíble! ¡Está realmente aquí! ¡El Santuario Fushimi Inari Subterráneo!", "Akagi"),
    148: ("Esto es demasiado conveniente.", "Kyousuke"),
    149: ("Está bien, ¡vamos a echar un vistazo!", "Akagi"),
    150: ("No estás escuchando en absoluto... ¡Oye! ¡¿De verdad vas a ir?! ¡¡Akagi!!", "Kyousuke"),
    154: ("¡Espera, Akagi! ¡Es peligroso ir solo!", "Kyousuke"),
    157: ("¡Akagi!", "Kyousuke"),
    158: ("Oh, viniste después de todo.", "Akagi"),
    159: ("Idiota. Es porque fuiste todo por tu cuenta.", "Kyousuke"),
    160: ("Ahí vas de nuevo. Aunque digas eso, en realidad tienes curiosidad por el Fushimi Inari Subterráneo.", "Akagi"),
    161: ("A quién le importa eso...", "Kyousuke"),
    162: ("Bueno, ya que estás aquí, ¡busquémoslo juntos!", "Akagi"),
    163: ("Sí, sí.", "Kyousuke"),
    170: ("Oye, ¿está bien seguir caminando tan lejos?", "Kyousuke"),
    171: ("No sabría nada de eso.", "Akagi"),
    172: ("Eso es cierto, pero..", "Kyousuke"),
    173: ("¿Oh?", "Akagi"),
    174: ("¿Qué es?", "Kyousuke"),
    175: ("¿Es una puerta de santuario sintoísta?", "Akagi"),
    176: ("...!", "Kyousuke"),
    178: ("Esto es, ¿no.", "Kyousuke"),
    179: ("Es la puerta del santuario de Fushimi Inari.", "Akagi"),
    180: ("No puede ser...", "Kyousuke"),
    181: ("¡Increíble! ¡¿Entonces realmente existe?!", "Akagi"),
    182: ("Lo-Lo parece.", "Kyousuke"),
    185: ("¡Muy bien! ¡Adentro vamos!", "Akagi"),
    186: ("¡Sí!", "Kyousuke"),
    189: ("¿Oh? Veo algo.", "Kyousuke"),
    190: ("Es verdad... Parece algo de un santuario.", "Akagi"),
    191: ("Parece un pequeño santuario.", "Kyousuke"),
    192: ("¡Oh-! ¡Increíble! Me alegro tanto de que hayamos venido aquí.", "Akagi"),
    193: ("¿Pero esto es lo que puede conceder deseos? Se ve destartalado.", "Kyousuke"),
    194: ("¡No digas esas cosas! Nuestros deseos pueden ser concedidos.", "Akagi"),
    195: ("Pero...", "Kyousuke"),
    199: ("¡Ahora! ¡Vamos a cumplir mis deseos!", "Akagi"),
    200: ("*suspiro*... Haz lo que quieras. Regresaremos cuando termines.", "Kyousuke"),
    201: ("Lo tengo.", "Akagi"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
current["000scriptHKYM_0000E.obj"] = build(n, s)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptHKYM_0000E.obj (part 1)")