import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

n = {
    183: "Qué presión silenciosa y terrible...",
    184: "...Estoy perdido...",
    190: "¿Q-Qué pasa con ella...? Dio una reacción tan femenina...",
    191: "Normalmente, ese era el tipo de escena donde me cubría de todo tipo de insultos y me lanzaba un gancho de derecha sin perdón...",
    192: "¡¿Por qué nos volvimos ambos incómodos ahí atrás?!",
    193: "¡Ah, maldición! ¡Ya no entiendo nada...!",
    202: "He estado actuando de manera extraña. No puedo simplemente decírselo, aunque.",
    203: "Pero, hoy, ¿no has estado tú también... actuando algo extraño?",
    220: "Bueno... debería estar bien decírselo.",
    221: "Ella se iba a enterar eventualmente de todos modos...",
    241: "Puede que haya sido mi imaginación, pero...",
    242: "La expresión de Kirino parecía solitaria mientras bajaba la cabeza.",
    245: "Esta chica.",
    246: "¿Podría haber escondido el álbum porque pensó que me sorprendería?",
    247: "......No hay manera, ¿verdad...?",
    252: "Después de decir eso, extendí mi mano para ponerla en la cabeza de Kirino por alguna razón.",
    253: "Sentí que, si hacía esto, podríamos volver a nuestra relación de hermanos incluso si no nos llevábamos bien, igual que como éramos antes.",
    254: "......",
    256: "...No sirvió.",
    257: "Cuando vi la cara sorprendida de Kirino, simplemente no pude tocarla.",
    266: "Dios, ¿quién es a esta hora...?",
    267: "Es la 1:00 de la mañana... Esto es demasiado temprano para levantarse.",
    271: "¿Por qué está Kirino aquí a esta hora...?",
    272: "No sé la razón. Pero, debe haber algo para que me despierte.",
    273: "De todos modos, escucharé lo que tiene que decir.",
    275: "Aunque mi habitación nunca ha tenido una cerradura...",
    279: "No creo que Kirino de todas las personas diga algo como «tuve un sueño de miedo, así que no puedo dormir～!», pero...",
    288: "¡N-No puedo creerlo... Kirino está preocupada por mí?!",
    297: "Me preguntaba con qué iba a responder, pero...",
    299: "Si pone esa cara, no puedo enojarme.",
    306: "Mira lo fuerte que es tu voz...",
    307: "Parece que Kirino habla en serio. Está seriamente atrapada por la idea imposible de que me iré a algún lugar.",
    317: "...Espera, ¿dormir juntos?",
    319: "Con la cara roja, Kirino se acurrucó silenciosamente contra mí.",
    320: "Err... ¿Qué es esta criatura viviente...?",
    321: "Sus hombros temblaban, y estaba muy nerviosa...",
    322: "......Linda.",
    323: "...Espera, ¡cálmate, yo! ¡Kirino es mi hermanita! ¡Es una experta en trabajar duro a su hermano mayor por la mandíbula, ¿no?!",
    335: "...Un día después de eso.",
    340: "Hablado hasta que nuestra relación se volviera así... Ah, quiere decir... hasta que descubrí el hobby otaku de Kirino.",
}
s = {
    145: ("¿Es así? Entonces, ¿puedes morir?", "Kirino"),
    152: ("*suspiro*...", "Kyousuke"),
    154: ("B-Buenos días...", "Kyousuke"),
    155: ("......Hmph.", "Kirino"),
    156: ("......*suspiro*", "Kyousuke"),
    166: ("Oye, Kirino. Esa postura tuya...", "Kyousuke"),
    167: ("Es un poco demasiado provocativa, umm...", "Kyousuke"),
    168: ("¿Hah?", "Kirino"),
    169: ("Siempre me he sentado así.", "Kirino"),
    170: ("Eso es... cierto. Ah, no importa. Perdón...", "Kyousuke"),
    172: ("¿Qué te pasa? De repente estás siendo asqueroso, ¿sabes?", "Kirino"),
    173: ("Guh, ¡cállate!", "Kyousuke"),
    174: ("...En serio, ¿qué le pasa?", "Kirino"),
    175: ("......Solo debería morir.", "Kirino"),
    176: ("Hmm... Ya es tarde.", "Kyousuke"),
    177: ("Debería ir a darme un baño pronto...", "Kyousuke"),
    178: ("Ah, dios. Ha hecho tanto calor todos los días... ¡¿Qué--?!", "Kyousuke"),
    179: ("...?!", "Kirino"),
    180: ("¡¿K-Kirino?!", "Kyousuke"),
    181: ("¡E-Esto no es lo que parece! ¡Una coincidencia... sí, es el resultado de una coincidencia!", "Kyousuke"),
    182: ("Heh...", "Kirino"),
    185: ("...Está bien.", "Kirino"),
    186: ("¿Ah...?", "Kyousuke"),
    187: ("N-No estoy particularmente enojada...", "Kirino"),
    188: ("Solo ten cuidado de ahora en adelante.", "Kirino"),
    189: ("S-Sí... Perdón, revisaré si estás dentro la próxima vez...", "Kyousuke"),
    194: (".........", "Kyousuke"),
    195: ("Umm...", "Kyousuke"),
    196: ("Esto es una pregunta abrupta, pero...", "Kyousuke"),
    197: ("¿Por qué me llamaste a tu habitación?", "Kyousuke"),
    198: ("¿Es quizás sobre otra consulta de vida?", "Kyousuke"),
    199: ("......", "Kirino"),
    200: ("Oye, no te quedes en silencio, di algo.", "Kyousuke"),
    201: ("¿No has estado actuando raro últimamente?", "Kirino"),
    204: ("Definitivamente estás escondiendo algo. ¿Qué es? Apúrate y dímelo.", "Kirino"),
    205: ("No estoy escondiendo nada.", "Kyousuke"),
    206: ("Eso es una mentira.", "Kirino"),
    207: ("No estoy mintiendo.", "Kyousuke"),
    208: ("Entonces, ¿qué pasa con tu actitud últimamente?", "Kirino"),
    209: ("Has... estado evitándome.", "Kirino"),
    210: ("S-Siempre soy así. Solo soy cauteloso de ser arrastrado al egoísmo de mi hermanita.", "Kyousuke"),
    211: ("Es diferente.", "Kirino"),
    212: ("¿Q-Qué es?", "Kyousuke"),
    213: ("...No puedo explicarlo bien, pero ¡es diferente!", "Kirino"),
    214: ("¿Justo cómo soy diferente?", "Kyousuke"),
    215: ("E-Eso es... eso es...", "Kirino"),
    216: ("Estás actuando frío y distante... como un extraño...", "Kirino"),
    217: ("E-Eso es...", "Kyousuke"),
    218: ("¡¿Qué es?! ¡Si tienes una razón, apúrate y dímelo! ¡Esto me está haciendo sentir incómoda!", "Kirino"),
    219: (".........", "Kyousuke"),
    222: ("La verdad es que no soy realmente tu hermano mayor.", "Kyousuke"),
    223: ("Tú eres la hija de Mamá y Papá, pero yo soy el hijo del hermano de Mamá.", "Kyousuke"),
    224: ("Por lo tanto, no somos parientes de sangre, y para decirlo sin rodeos... Err... ¿Es como si fuéramos completos extraños?", "Kyousuke"),
    225: ("Hmm, ¿es así?", "Kirino"),
    226: ("¡¡Qué reacción tan ligera!!!!", "Kyousuke"),
    227: ("¿No deberías estar más sorprendida? No soy tu hermano mayor, ¿sabes?", "Kyousuke"),
    228: ("Es porque... de alguna manera lo sentí.", "Kirino"),
    229: ("...¿Te diste cuenta?", "Kyousuke"),
    230: ("Eres el único sin fotos tuyas en el álbum familiar.", "Kirino"),
    231: ("Ah...", "Kyousuke"),
    232: ("¿Es quizás por eso que escondiste ese álbum?", "Kyousuke"),
    233: ("¿Esconderlo...?", "Kirino"),
    234: ("...¿Por casualidad hurgaste en mi colección?", "Kirino"),
    235: ("¿Huh...? N-No...! ¡Hay una buena razón para esto...!", "Kyousuke"),
    236: ("¡Definitivamente nunca pensé en algo malo como tratar de encontrar tu debilidad o algo así!", "Kyousuke"),
    237: ("...Basta.", "Kirino"),
    238: ("¿Heh...?", "Kyousuke"),
    239: ("Dije que basta. ¡Sal de aquí!", "Kirino"),
    240: ("S-Claro...", "Kyousuke"),
    243: ("Oye, Kirino.", "Kyousuke"),
    244: ("Cállate. No digas nada más.", "Kirino"),
    248: ("¿Qué estás mirando fijamente?", "Kirino"),
    249: ("Oye... Solo quiero decir una cosa.", "Kyousuke"),
    250: ("Entonces, ¿por qué no te apuras y lo dices?", "Kirino"),
    251: ("Incluso si no somos parientes de sangre, eres mi hermanita.", "Kyousuke"),
    255: ("S-Perpón...", "Kyousuke"),
    258: ("...Entonces, buenas noches.", "Kyousuke"),
    259: ("......", "Kirino"),
    260: ("......Idiota.", "Kirino"),
    261: ("...Espera, ¡¿qué estoy diciendo?!", "Kirino"),
    262: ("Ah... ¡Ugh...!!", "Kirino"),
    263: ("En serio... sería mejor si él no estuviera...!", "Kirino"),
    264: (".........", "Kyousuke"),
    265: ("Huh... hnn...", "Kyousuke"),
    268: ("¿Mamá?", "Kyousuke"),
    269: ("...Soy yo.", "Kirino"),
    270: ("......¿Kirino?", "Kyousuke"),
    274: ("Espera, abriré la puerta ahora.", "Kyousuke"),
    276: ("¿Qué pasa? Para que vengas tan tarde en la noche...", "Kyousuke"),
    277: ("......Nada en particular.", "Kirino"),
    278: ("«Nada en particular», dices... Oye oye.", "Kyousuke"),
    280: ("...Dijiste cosas extrañas antes, así que es tu culpa.", "Kirino"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
entry = current.get("000scriptMGIM_0000.obj", {})
entry.update(build(n, s))
current["000scriptMGIM_0000.obj"] = entry
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptMGIM_0000.obj (part B)")