import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0064_n = {
    0: "Ruta de Saori · Una Oleada De Sentimientos",
    4: "Saori me entregó sigilosamente un número de fotografías.",
    5: "Veamos, son fotos de...",
    6: "...Saori.",
    7: "Y es su versión sin lentes giratorios.",
    8: "¿Y lo que es más, cosplay completo de maid?",
    15: "¡Gah, ¿un contraataque de precisión?!",
    18: "La segunda foto.",
    19: "Muy definitivamente... un cosplay de un cierto personaje famoso de anime.",
    20: "Más que la perfección de su cosplay, seguir viendo el rostro sin obstrucciones de Saori es como un regalo para los ojos... digo, malo para el corazón.",
    21: "Esto es lo que pienso totalmente. El tipo que inventó la idea de quitarse los lentes para revelar a una chica hermosa fue una gran persona.",
    24: "Y entonces la tercera foto.",
    25: "A propósito, ¡¿qué pensaría la sociedad de un tipo que, mientras está parado frente a una chica de preparatoria, mira fijamente fotos de dicha chica de preparatoria en traje de baño?!",
    26: "¡No solo un pervertido en espera, sino un pervertido en entrenamiento, ¿verdad?!",
    27: "Alguien debería llamar a la policía por mí.",
    31: "La última foto...",
    32: "El traje de maid, el cosplay de personaje de anime, el bikini...",
    33: "El trago de mi deglución nerviosa resonó en mis oídos.",
    34: "¿Se rendiría el héroe antes del tan esperado jefe final?",
    35: "Pero, si retrocedía aquí, ¡no podría ser considerado un hombre!",
    39: "El tan esperado jefe final rompió fácilmente nuestras defensas aéreas.",
    40: "Siento como si estuviera empezando a tocar la puerta prohibida...",
}
a0064_s = {
    1: ("Kyo... Kyousuke-shi...", "Saori"),
    2: ("A-Aquí...", "Saori"),
    3: ("¿Qué es esto?", "Kyousuke"),
    9: ("¿S-Saori? ¿Qué...", "Kyousuke"),
    10: ("Uuuu, uuuu, uuuu...", "Saori"),
    11: ("Cálmate. ¡Cálmate, Saori!", "Kyousuke"),
    12: ("Si tuviera que decirlo, aunque prefiero a las chicas con lentes, ¡tu look natural es bastante increíble!", "Kyousuke"),
    13: ("¡Y ver a una dama apropiada expuesta al descubierto trae una oleada de sentimientos!", "Kyousuke"),
    14: ("Kyousuke-shi, ¡tú también necesitas calmarte!", "Saori"),
    16: ("Y parece que hay más...", "Kyousuke"),
    17: ("¡Ohhhhh?!", "Kyousuke"),
    22: ("¡Pero! Aun así, prefiero a las chicas con lentes...", "Kyousuke"),
    23: ("¡Gah!", "Kyousuke"),
    28: ("S-Saori... ¿qué es esto...", "Kyousuke"),
    29: ("Hay más...", "Saori"),
    30: ("Todavía queda una última foto...", "Saori"),
    36: ("¡Hnnnggg!", "Kyousuke"),
    37: ("¡Bu-ha-hwoooo!", "Kyousuke"),
    38: ("¡Tú! ¿¡Qué! ¿¡Esto! Huh?!", "Kyousuke"),
    41: ("Me esforcé mucho...", "Saori"),
    42: ("Y era como una famosa pro-cosplayer...", "Saori"),
    43: ("¡Mostrándome a mí misma!", "Saori"),
    44: ("¡¿No te esforzaste en la cosa equivocada?!", "Kyousuke"),
    45: ("Uuuu, uuuu, uuuu...", "Saori"),
    46: ("Si... Si dices que todo esto no fue suficiente...", "Saori"),
    47: ("Si no, entonces solo la armadura de Micro Bikini femenina podría...", "Saori"),
    48: ("¡Está bien, está bien, lo entiendo!", "Kyousuke"),
    49: ("¡Entiendo tototalmente cuánto te esforzaste!", "Kyousuke"),
    50: ("¡Pero esto no es algo que deberías hacer como una mujer que está a punto de casarse!", "Kyousuke"),
    51: ("Eso es lo que pasa...", "Saori"),
    52: ("¡¿Huh?!", "Kyousuke"),
    53: ("Si tirara mi pudor, mi nuevo yo sería verdaderamente libre...", "Saori"),
    54: ("Tomé esas fotos mientras creía eso.", "Saori"),
    55: ("Los primeros cosplays fueron tomados en preparación para el último.", "Saori"),
    56: ("Ah.. Ahaha... ¡AHAHAHAHAHA!", "Saori"),
    57: ("¡¿Saori?! ¡¡Saori!!", "Kyousuke"),
}

a0065_n = {
    0: "Ruta de Saori · Saori En Apuros",
    5: "¿Ese hombre? ¿Está hablando de su prometido?",
    6: "A juzgar por esa mirada en su rostro, estoy seguro de que tiene que estar hablando de él.",
    17: "Esto se sentía como saltarse todos los eventos de «caminemos a casa juntos» en un juego gal y de repente ir directo a la «confesión bajo el cerezo».",
    23: "Definitivamente hay algo sospechoso en él.",
    24: "Pero, ahora no es el momento de profundizar en su prometido. El problema es---",
    33: "¿Su voz está temblando...?",
    34: "¿Está asustada de algo? Es como si tuviera miedo de que yo lo niegue.",
    36: "---¿una respuesta de mí?",
    37: "¿Por qué tendría que siquiera preguntar?",
    45: "No respondió mi pregunta y se fue con prisa.",
    46: "Si quisiera alcanzarla, probablemente podría.",
    47: "Pero tiene ese aura decidida, y no pude seguirla.",
    48: "No sé qué está pasando, pero parecía que Saori había encontrado la respuesta que necesitaba.",
    49: "Todo esto saldrá bien... Eso espero.",
    50: "Pero... por alguna razón, sentí una sensación de inquietud arrastrándose dentro de mí.",
}
a0065_s = {
    1: ("H-Hey... ¡Saori! ¡Recupérate!", "Kyousuke"),
    2: (".........", "Saori"),
    3: ("Kyousuke-shi...", "Saori"),
    4: ("Ese hombre... Ese hombre...", "Saori"),
    7: ("¿Entonces hablaste con él?", "Kyousuke"),
    8: ("Sí... El otro día en la fiesta de té...", "Saori"),
    9: ("...Seguí tu consejo, y hablé con él sobre mi hobby otaku.", "Saori"),
    10: ("¿Y el resultado?", "Kyousuke"),
    11: ("Él simplemente... no entiende a los otakus...", "Saori"),
    12: ("¿¡Entonces canceló el matrimonio?!", "Kyousuke"),
    13: ("No, en lugar de eso me tuvo lástima por estar mal influenciada por los otakus.", "Saori"),
    14: ("Y decidió casarse conmigo en mi próximo cumpleaños...", "Saori"),
    15: ("¡¿QUEEEEEEEEEEEEEEEEEEE?!", "Kyousuke"),
    16: ("¿Cómo pasó eso? ¿No están saltándose un montón de pasos aquí?", "Kyousuke"),
    18: ("«Saori-san, has sido corrompida por el cáncer de la sociedad.", "Saori"),
    19: ("Pero aún eres joven, todavía puedes ser salvada.", "Saori"),
    20: ("Repararé tu mente... Y tu cuerpo.»", "Saori"),
    21: ("Y eso fue todo...", "Saori"),
    22: ("¡Eso es justo como un viejo pervertido!", "Kyousuke"),
    25: ("Saori, entonces,", "Kyousuke"),
    26: ("¿qué le dijiste después de eso?", "Kyousuke"),
    27: ("...............", "Saori"),
    28: ("Kyousuke-shi.", "Saori"),
    29: ("¿S-Sí?", "Kyousuke"),
    30: ("Siempre serás mi amigo, ¿verdad?", "Saori"),
    31: ("¿Saori?", "Kyousuke"),
    32: ("...Por favor respóndeme...", "Saori"),
    35: ("¿Puedo obtener una respuesta?", "Saori"),
    38: ("Por supuesto.", "Kyousuke"),
    39: ("Pase lo que pase, tú, Kirino, Kuroneko y yo siempre seremos amigos.", "Kyousuke"),
    40: ("....Ya veo.", "Saori"),
    41: ("...Muchas gracias. Con esto, mi mente está decidida.", "Saori"),
    42: ("¿Tu mente está decidida...? ¿En qué?", "Kyousuke"),
    43: ("Lo siento, no tengo tiempo para explicarlo...", "Saori"),
    44: ("Tengo que irme...", "Saori"),
}

a0067_n = {
    0: "Ruta de Saori · Las Palabras De Mis Padres",
    1: "Han pasado unos días desde que conocí a Saori en Akihabara.",
    2: "Desde entonces, no he estado en contacto con ella.",
    3: "No contesta su celular ni entra al chat.",
    4: "No ha estado en ningún sitio de redes sociales, y no ha contactado a Kirino ni a nadie más.",
    5: "Sin nada que hacer, pasé mis días mirando fijamente mi celular silencioso.",
    9: "¿De qué está hablando de repente? Ah, debe haber malinterpretado por qué estaba mirando mi celular.",
    12: "¿Por qué esta vieja piensa que Manami y yo estamos saliendo?",
    13: "No sé cuántas veces le dije que no tenemos ese tipo de relación.",
    14: "Claro, me gusta Manami, pero no de esa manera.",
    15: "Además, ¡tengo el derecho de decidir eso!",
    16: "«El derecho de decidir», huh...",
    24: "Ella sí que está segura...",
    27: "Exactamente como dice mi madre...",
    28: "Si fuera Kirino, este tipo de error no pasaría.",
    29: "Mi madre confía en Kirino, así que puede decir eso con total confianza.",
    33: "Una hija propia...",
    34: "Hablando de eso, ¿qué piensan los padres de Saori del compromiso...",
    36: "Esa noche...",
    37: "Intenté tener la misma conversación con mi papá que acababa de llegar a casa.",
    45: "Además, dije que alguien que era una buena persona!",
    46: "¡Mantente dentro de algunos límites de mimar a tu hija, maldito viejo!",
    47: "Lo cual nunca diría ni siquiera si me rasgaran la boca, pero...",
    54: "Lo más cercano a ti mismo, huh...",
    55: "Recordé a Saori.",
    56: "¿Quién es lo más cercano a Saori, ya que vive sola en un departamento?",
    57: "¿Quién la está apoyando? ¿Quién es su brújula?",
    58: "Creía conocer a Saori, pero...",
    59: "No tenía la más mínima idea.",
    64: "Después de poner sus ojos en su periódico, no dijo nada más.",
    65: "En mi cama, comencé a recordar lo que dijo mi papá.",
    66: "«La Miseria De Un Hijo Es responsabilidad de los padres.» «Los padres que piensan en cosas que no sean sus hijos son inútiles.»",
    67: "¿Qué hay de los padres de Saori?",
    68: "¿No piensan nada de forzar a su hija a un matrimonio que ella no quiere?",
    70: "Miro casualmente mi celular, esperando ver algún tipo de actualización.",
    71: "No hay correos nuevos, ni notificaciones.",
    72: "No había nada que pudiera hacer para resolver el problema en mi propia mente.",
}
a0067_s = {
    6: ("¿Qué pasa, teniendo un concurso de miradas con tu teléfono?", "Yoshino"),
    7: ("Realmente no...", "Kyousuke"),
    8: ("Fufu... Manami es tu vecina. Si estás preocupado, ¿por qué no vas a verla?", "Yoshino"),
    10: ("Manami y yo no somos así.", "Kyousuke"),
    11: ("Sí, sí, lo sé.", "Yoshino"),
    17: ("Oye, solo por decir...", "Kyousuke"),
    18: ("Si tu hija se fuera a casar, ¿qué pensarías?", "Kyousuke"),
    19: ("Quiero decir, casarse de una manera que no quieres.", "Kyousuke"),
    20: ("¿Huh? ¿Por qué preguntas esto tan de repente?", "Yoshino"),
    21: ("Solo déjalo fluir. Solo tengo curiosidad.", "Kyousuke"),
    22: ("Hmmm... Al menos, yo...", "Yoshino"),
    23: ("Pienso que Kirino no haría eso.", "Yoshino"),
    25: ("Tú también piensas eso, ¿verdad?", "Yoshino"),
    26: ("Sí...", "Kyousuke"),
    30: ("Bueno, voy de compras ahora.", "Yoshino"),
    31: ("Cuida la casa por mí, ¿de acuerdo?", "Yoshino"),
    32: ("Una hija propia...", "Kyousuke"),
    35: ("Hmm...", "Kyousuke"),
    38: ("Oye, solo por decir...", "Kyousuke"),
    39: ("Si hubiera esta persona realmente buena...", "Kyousuke"),
    40: ("Y porque pensaba que era por el bien de sus padres, los siguió al pie de la letra.", "Kyousuke"),
    41: ("Hasta el punto de que empieza a arruinar su propia vida...", "Kyousuke"),
    42: ("Si este fuera tu hijo, ¿qué harías?", "Kyousuke"),
    43: ("...¿Estamos hablando de Kirino?", "Daisuke"),
    44: ("Por supuesto que no. Esto es solo una pregunta hipotética.", "Kyousuke"),
    48: ("¿Hipotética, huh...", "Daisuke"),
    49: ("...【La Miseria De Un Hijo】 es responsabilidad de los padres.", "Daisuke"),
    50: ("¿Qué quieres decir?", "Kyousuke"),
    51: ("Cómo crece un niño es su propia elección.", "Daisuke"),
    52: ("Pero la brújula que los guía son sus padres.", "Daisuke"),
    53: ("Un hijo es lo más cercano a tu propia existencia que crías.", "Daisuke"),
    60: ("Pero, por eso...", "Daisuke"),
    61: ("Los padres que traen desgracia a sus hijos son resentidos por el resto de sus vidas.", "Daisuke"),
    62: ("¿Es así?", "Kyousuke"),
    63: ("Los padres que piensan en cosas que no sean sus hijos son inútiles.", "Daisuke"),
    69: ("...Tch.", "Kyousuke"),
}

a0070_n = {
    0: "Ruta de Saori · Encuentro Con Ella",
    2: "Después de atar firmemente mis zapatos, recogo los artículos otaku que había colocado a mi lado.",
    3: "Por supuesto, son los artículos otaku que Saori me dio.",
    5: "Ha pasado una semana desde la última vez que vi a Saori.",
    6: "Esta semana pasada, todavía no he tenido noticias de ella.",
    7: "Ha estado ignorando mis llamadas y mensajes.",
    8: "Esto ha tenido un efecto tan fuerte en mi delicado corazón lleno de pubertad como cuando Ayase bloqueó mi número.",
    10: "Desde entonces, siempre me pregunté en qué decidió su mente.",
    11: "Ya es hora de que lo descubra.",
    30: "Solo esta vez, estuve completamente de acuerdo con todo lo que dijo Kirino.",
    49: "¿Qué pasa con eso...",
    61: "Hey, hey, hey, hey!",
    62: "Kirino, te estás pasando demasiado.",
}
a0070_s = {
    1: ("...Muy bien.", "Kyousuke"),
    4: ("Bueno entonces, hora de ir.", "Kyousuke"),
    9: ("...Muchas gracias. Con esto, mi mente está decidida.", "Saori"),
    12: ("Está bien, me voy.", "Kyousuke"),
    13: ("¡Kyousuke-shi!", "Saori"),
    14: ("¡¿Wooooaaaah?!", "Kyousuke"),
    15: ("Espera, ¿Saori? ¿Por qué estás aquí...", "Kyousuke"),
    16: ("O más bien, justo iba a verte, pero...", "Kyousuke"),
    17: ("Lamento mucho venir aquí tan de repente.", "Saori"),
    18: ("Vine aquí para trazar la línea... He venido a despedirme.", "Saori"),
    19: ("¿Despedirte...?", "Kyousuke"),
    20: ("Estás bromeando, ¿verdad? De repente dices que te vas, esto no tiene ningún sentido.", "Kyousuke"),
    21: ("Hablo en serio. Completamente en serio.", "Saori"),
    22: ("No puedo aprobar esta seriedad.", "Kyousuke"),
    23: ("Pensé que dirías algo así.", "Saori"),
    24: ("Explicaré apropiadamente las circunstancias.", "Saori"),
    25: ("¿Podrías tú y Kiririn-shi dedicarme un poco de tiempo?", "Saori"),
    26: ("¿Huh? ¿De qué se trata todo eso?", "Kirino"),
    27: ("¿Entrevista de matrimonio? ¿Prometido? ¡No he escuchado ni una palabra de esto!", "Kirino"),
    28: ("¿Y qué pasa con ese tipo? ¿No permitir que los lentes giratorios sean otaku, diciendo «repararé tu cuerpo»?", "Kirino"),
    29: ("¡Es solo un lolicon... ¿Quién se cree que es!", "Kirino"),
    31: ("Kiririn-shi, por favor cálmate.", "Saori"),
    32: ("¡¿Cómo podría calmarme!", "Kirino"),
    33: ("Más bien, ¡¿por qué estás tan tranquila?! ¡Este es tu problema!", "Kirino"),
    34: ("...Mi mente ya está decidida.", "Saori"),
    35: ("Saori...", "Kirino"),
    36: ("...Oye Saori.", "Kyousuke"),
    37: ("Pregunté esto antes pero, ¿en qué has decidido tu mente?", "Kyousuke"),
    38: ("...Es tal como significa.", "Saori"),
    39: ("Él está atascado pensando que tú, Kiririn-shi, y Kuroneko-shi son «Malas amigas que me engañaron hacia el camino del otaku.»", "Saori"),
    40: ("Está bien si es solo yo, pero no puedo dejar que tenga ese malentendido de mis preciosas amigas.", "Saori"),
    41: ("Entonces, ¿por qué...", "Kyousuke"),
    42: ("Ese hombre tiene una voz muy influyente. Enfrentando los problemas recientes causados por el 2D en la sociedad, ha estado empujando activamente restricciones sobre el 2D.", "Saori"),
    43: ("Por supuesto, él solo no es el problema. Sin embargo, no puede escapar a la atención de la sociedad.", "Saori"),
    44: ("...Me convertí en la chispa de la situación, y no podía soportar ver a mis anime y juegos favoritos siendo culpados.", "Saori"),
    45: ("Son cosas importantes ya que unen a todos...", "Saori"),
    46: ("Saori...", "Kyousuke"),
    47: ("No quiero causar problemas a todos.", "Saori"),
    48: ("Por eso terminaré mi relación con todos para prevenir causar más problemas.", "Saori"),
    50: ("Si nuestra amistad es tan preciosa como dices, ¿terminarás esa amistad para ayudarnos?", "Kyousuke"),
    51: ("Esa es una manera horrible de evaluar la situación. ¿No entiendes lo que estás diciendo?", "Kyousuke"),
    52: ("Por supuesto. Decidí después de pensarlo bien.", "Saori"),
    53: ("Si yo no estuviera aquí, las cosas se resolverían pacíficamente. Soy la raíz de todos los problemas.", "Saori"),
    54: ("...En serio, esta conversación es molesta.", "Kirino"),
    55: ("¿Kirino? ¿Qué estás diciien-", "Kyousuke"),
    56: ("Pero es verdad, ¿no?", "Kirino"),
    57: ("Ocultaste el hecho de que tenías una entrevista de matrimonio, dejaste que la conversación se expandiera, ¿y regulaste el 2D?", "Kirino"),
    58: ("Honestamente, es extremadamente molesto.", "Kirino"),
    59: ("...Mis más sinceras disculpas.", "Saori"),
    60: ("Oh, ¿piensas que disculparte será el fin de esto?", "Kirino"),
    63: ("¡Kirino!", "Kyousuke"),
}

a0072_n = {
    0: "Ruta de Saori · Encuentro Con Ella",
    28: "¿Es que le dolió que la dejaran fuera del círculo...?",
    29: "¿Es por eso que está tan alterada?",
    61: "...¿Qué pienso sobre ellos?",
    62: "Los otakus son lo que son, les gustan los juegos y el anime...",
    63: "Nada más, nada menos...",
    87: "...¿Estás dando tu propia postura al respecto?",
    90: "Ah, es patético pero, no puedo decir nada...",
    118: "Creo que entiendo lo que está tratando de decir. Solo un poco, aunque sea.",
    124: "Ser decisivo aquí y ahora, huh...",
    128: "Maldición... ¿Cómo debería responder a esto...",
}
a0072_s = {
    1: ("¡Dije que te calmes! Te estás alterando demasiado.", "Kyousuke"),
    2: ("...¡Deja de actuar tan superior cuando no sabes nada!", "Kirino"),
    3: ("¡Al menos sé más que tú!", "Kyousuke"),
    4: ("¿Qué es eso? ¿Ella te consultó, así que te crees todo un experto?", "Kirino"),
    5: ("¡¿Por qué te enojas conmigo?!", "Kyousuke"),
    6: ("Compartes el mismo crimen. Tú tampoco me dijiste nada de esto.", "Kirino"),
    7: ("¡Oye! ¡No te pongas violenta!", "Kyousuke"),
    8: ("¡Estaban ocultándomelo, qué mezquino es eso!", "Kirino"),
    9: ("...Um... lo siento...", "Kyousuke"),
    10: ("Es demasiado tarde para disculparte.", "Kirino"),
    11: ("Entonces, te daré algo como disculpa.", "Saori"),
    12: ("¿Quizás disfrutarías de un doujinshi de tu Meruru favorita o algo así, qué tal...?", "Saori"),
    13: ("No quiero uno, así que solo deja de ocultarme cosas.", "Kirino"),
    14: ("No tienes idea de cuánto se preocupó la gente...", "Kirino"),
    15: ("......", "Saori"),
    16: ("Oye, ¿por qué no dijiste nada?", "Kirino"),
    17: ("¿Crees que soy solo una molestia?", "Kirino"),
    18: ("No hay manera de que pensara eso.", "Kyousuke"),
    19: ("Entonces, ¿por qué no querías hablarme?", "Kirino"),
    20: ("No es eso... Es solo que este es un tema delicado...", "Kyousuke"),
    21: ("¡Aun así, dímelo!", "Kirino"),
    22: ("No te enojes tanto. Saori tenía sus razones...", "Kyousuke"),
    23: ("Eso lo puedo ver solo con mirar...", "Kirino"),
    24: ("Kiririn-shi...", "Saori"),
    25: ("Entonces no deberías estar tan molesta con ella, ¿verdad?", "Kyousuke"),
    26: ("No quiero escuchar tus excusas.", "Kirino"),
    27: ("Kirino...", "Kyousuke"),
    30: ("...¿Qué quieres? Mirándome así...", "Kirino"),
    31: ("¿Es divertido excluirme?", "Kirino"),
    32: ("No te estamos excluyendo.", "Kyousuke"),
    33: ("Lo dudo.", "Kirino"),
    34: ("Ahora ni siquiera puedo confiar en ti. Bueno, no podía desde el principio, de todos modos...", "Kirino"),
    35: ("No te enojes tanto. Saori tenía sus razones...", "Kyousuke"),
    36: ("Sí, puedo ver eso...", "Kirino"),
    37: ("Kiririn-shi...", "Saori"),
    38: ("Entonces no deberías estar tan molesta con ella, ¿verdad?", "Kyousuke"),
    39: ("No quiero escuchar tus excusas.", "Kirino"),
    40: ("Tch... Tu silencio me dice que tengo razón.", "Kirino"),
    41: ("¡Y-Tú estás equivocada!", "Kyousuke"),
    42: ("¿En qué?", "Kirino"),
    43: ("Solo leí mal el momento, o más bien...", "Kyousuke"),
    44: ("De todos modos, había una razón por la que no podía decirte...", "Kyousuke"),
    45: ("Linda excusa.", "Kirino"),
    46: ("¡No es una excusa!", "Kyousuke"),
    47: ("Bueno, así es como suena...", "Kirino"),
    48: ("¿No va a rehabilitarse ella de todos modos?", "Kirino"),
    49: ("Este es tu propio hobby, ¿verdad? ¿Por qué tienes que dejarlo solo porque alguien te lo dijo?", "Kirino"),
    50: ("¡Eso es lo que le dije a Saori también!", "Kyousuke"),
    51: ("¿Puedes no interrumpir cuando la gente está hablando?", "Kirino"),
    52: ("Ugh...", "Kyousuke"),
    53: ("*ahem* Bueno...", "Kirino"),
    54: ("Suena como si te quedaras parado y escucharas como un idiota. Te felicitaré por eso, aunque...", "Kirino"),
    55: ("Entiendo lo que estás tratando de decir.", "Kyousuke"),
    56: ("Puede ser así... Saori ha estado realmente preocupada por esto.", "Kyousuke"),
    57: ("No te estaba preguntando.", "Kirino"),
    58: ("A-Ah...", "Kyousuke"),
    59: ("Oye... ¿Qué piensas sobre los otakus?", "Kirino"),
    60: ("¿Yo? Bueno...", "Kyousuke"),
    65: ("¿No vas a responder? Entonces hablaré.", "Kirino"),
    66: ("Es un estilo de vida, no solo un hobby.", "Kirino"),
    67: ("Si simplemente lo tiras, sería como hacerte desaparecer.", "Kirino"),
    68: ("Kirino...", "Kyousuke"),
    69: ("Qué... ¿no puedes decir nada?", "Kirino"),
    70: ("Bueno, Saori. ¿Qué tal tú?", "Kirino"),
    71: ("Entonces, ¿cuál es la situación?", "Kirino"),
    72: ("Eso es... Pero, Saori tiene que hacer lo que pueda...", "Kyousuke"),
    73: ("¿Lo que pueda hacer? Si falla, ¿hay algún significado?", "Kirino"),
    74: ("Luchas para ganar. ¿Por qué no entiendes eso?", "Kirino"),
    75: ("Ni siquiera sabes cuánto se está esforzando, no digas lo que te plazca.", "Kyousuke"),
    76: ("Por supuesto que no lo sé. Ustedes dos me lo han estado ocultando.", "Kirino"),
    77: ("Eso es... verdad. Pero, ¿no puedes ver con solo mirarla que ha pasado por mucho?", "Kyousuke"),
    78: ("...No.", "Kirino"),
    79: ("«No», dice... ¡Argh!", "Kyousuke"),
    80: ("...Bueno, eso es verdad.", "Kyousuke"),
    81: ("Hmmm. ¿No lo estás negando?", "Kirino"),
    82: ("No, este es el resultado de nuestro «desafío».", "Kyousuke"),
    83: ("Pero... ¡Saori aún no ha perdido! Ha estado luchando espléndidamente, y el resultado...", "Kyousuke"),
    84: ("Y el resultado es que si pierdes, todo será sin sentido.", "Kirino"),
    85: ("Ugh...", "Kyousuke"),
    86: ("...No lo aceptaré a menos que ganes.", "Kirino"),
    88: ("No puedes simplemente reiniciar como en un juego... Las competencias no se ganan tan fácilmente.", "Kirino"),
    89: ("No puedes seguir así.", "Kirino"),
    91: ("Y tú... Sigues diciendo Saori esto, Saori aquello, deja de imponerte a ella.", "Kirino"),
    92: ("Si quieres resolver esto después de escucharla, mejor muéstrame que estás al menos dispuesto a ir a la casa de su prometido y explotar.", "Kirino"),
    93: ("¿¡Por qué tengo que explotar!?", "Kyousuke"),
    94: ("Es solo un ejemplo. Muéstrame que eres así de serio.", "Kirino"),
    95: ("No tienes que explotar, puedes simplemente hundirte en la Bahía de Tokio después de atarte a un ancla.", "Kirino"),
    96: ("Solo estás tratando de matarme en tu mente, ¿verdad?", "Kyousuke"),
    97: ("Ese es mi punto, debes estar dispuesto a morir.", "Kirino"),
    98: ("...Hay lógica en lo que dices.", "Kyousuke"),
    99: ("Fui irresponsable al consultar a Saori esta vez.", "Kyousuke"),
    100: ("No... no lo fuiste.", "Saori"),
    101: ("No, el matrimonio es un problema entre dos personas. No era mi lugar intervenir.", "Kyousuke"),
    102: ("Si tenías un problema que no podías resolver, que alguien intervenga es algo por lo que agradecer.", "Kirino"),
    103: ("Si quieres que alguien intervenga, consultarías a alguien, ¿verdad?", "Kirino"),
    104: ("Si quieres ser aprobada o negada, buscas una opinión, ¿verdad?", "Kirino"),
    105: ("Que te digan que estás equivocada es mejor que ser ignorada.", "Kirino"),
    106: ("Ya veo...", "Kyousuke"),
    107: ("Eres igual que Saori.", "Kirino"),
    108: ("Solo te veo huyendo a escondidas.", "Kirino"),
    109: ("¡No estamos huyendo, simplemente no sabemos qué hacer!", "Kyousuke"),
    110: ("Al contrario, no hay a dónde huir. Estamos en un callejón sin salida aquí.", "Kyousuke"),
    111: ("Si no hay salida, ¿por qué no hacer una?", "Kirino"),
    112: ("Más fácil decirlo que hacerlo...", "Kyousuke"),
    113: ("Me usaste como ruta de escape.", "Kirino"),
    114: ("¿Huh?", "Kyousuke"),
    115: ("Porque estabas perdido con tu hobby, pensaste que nada más podía pasar y viniste a mí, ¿verdad?", "Kirino"),
    116: ("¿Dónde quedó tu determinación? ¡No me digas que no puedes hacer algo que ya has hecho!", "Kirino"),
    117: ("Kirino...", "Kyousuke"),
    119: ("Oye tú, con los lentes giratorios.", "Kirino"),
    120: ("Si has estado escuchando, ¿por qué no dices algo?", "Kirino"),
    121: ("Kiririn-shi...", "Saori"),
    122: ("Huyendo, dices...", "Kyousuke"),
    123: ("No te estaba preguntando.", "Kirino"),
    125: ("Le estaba preguntando a Saori.", "Kirino"),
    126: ("Kirino...", "Kyousuke"),
    127: ("Después de escuchar todo esto, si todavía lo estás negando... solo estás huyendo.", "Kirino"),
    129: ("Kiririn-shi, yo...", "Saori"),
    130: ("Saori, si estás enojada por las palabras de Kirino, deberías decir algo.", "Kyousuke"),
    131: ("¿Huh? Si tienes algo que decir, te escucharé.", "Kirino"),
}

data = {
    "000scriptDSAO_0064G.obj": build(a0064_n, a0064_s),
    "000scriptDSAO_0065A.obj": build(a0065_n, a0065_s),
    "000scriptDSAO_0067A.obj": build(a0067_n, a0067_s),
    "000scriptDSAO_0070A.obj": build(a0070_n, a0070_s),
    "000scriptDSAO_0072T.obj": build(a0072_n, a0072_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
