import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a37_n = {
    0: "Para Refutar Y Persuadir",
    6: "Su expresión está tan fría como siempre, pero parece que está enojada.",
    7: "Tengo ganas de animarla un poco...",
    19: "¿Qué debería decir?",
    20: "Las dos son muy tercas, así que empeorará todo si digo algo raro.",
    21: "...Hmph.",
    31: "Acabo de decir algo, pero no llegó del todo a sus oídos.",
    32: "S-Solo tengo que callarme y esperar a que pase la tormenta...",
    35: "Esto está mal. Si espero, ciertamente se derrumbará",
    36: "¿Q-Qué debería hacer? ¡Ya sé! ¡¿No es este el momento en que Saori me rescata?!",
}
a37_s = {
    1: ("Tal como lo pensé...", "Kuroneko"),
    2: ("¿Eh?", "Kyousuke"),
    3: ("Senpai realmente se pone del lado de esta chica.", "Kuroneko"),
    4: ("...¿Siscon?", "Kuroneko"),
    5: ("¿Cómo es que llegamos a esto? Muy bien, Kuroneko, escúchame.", "Kyousuke"),
    8: ("Tus habilidades son esenciales para obtener la victoria.", "Kyousuke"),
    9: ("Hmph... ¿Por qué no dijiste eso desde el principio?", "Kuroneko"),
    10: ("¿Por qué te estás poniendo tan engreída?", "Kirino"),
    11: ("Kirino, por favor, quédate callada por ahora. No compliques más las cosas.", "Kyousuke"),
    12: ("¿Hah?", "Kirino"),
    13: ("Kiririn-shi, está bien. Veamos qué tiene que decir Kyousuke-shi.", "Saori"),
    14: ("¿Eh? ...Bueno, supongo que no hay de otra. Me quedaré callada por ahora.", "Kirino"),
    15: ("Kuroneko. Lo que trato de decir es...", "Kyousuke"),
    16: ("Intentar persuadirme con palabras poco inspiradas es inútil.", "Kuroneko"),
    17: ("Poniéndose tan malhumorada...", "Kyousuke"),
    18: ("Lo que quiero decir es...", "Kyousuke"),
    22: ("De todos modos, ¡por favor, cálmense!", "Kyousuke"),
    23: ("Escuchen, ¿cuál es su objetivo? ¡Intenten considerarlo una vez más!", "Kyousuke"),
    24: ("...¿Objetivo?", "Kirino"),
    25: ("Nuestro objetivo es...", "Kyousuke"),
    26: ("¡Lograr la victoria!", "Saori"),
    27: ("¿Cierto?", "Kyousuke"),
    28: ("¡Así que ahora no es el momento de estar peleando!", "Kyousuke"),
    29: ("Si tienes algo que decir, dilo rápido.", "Kuroneko"),
    30: ("......", "Kyousuke"),
    33: ("Hmm... Tal como lo pensé, no necesitamos el poder de esta chica malvada.", "Kirino"),
    34: ("Qué coincidencia. Pues yo también me niego a unir fuerzas contigo.", "Kuroneko"),
    37: ("Una buena amistad es algo hermoso, ¿no es así, Kyousuke-shi?", "Saori"),
    38: ("Como siempre, hay algo mal con tu vista...", "Kyousuke"),
    39: ("No hay de otra; tendré que hacer algo.", "Kyousuke"),
}

a38_n = {
    0: "Para Refutar Y Persuadir",
    3: "Está completamente malhumorada.",
    4: "Intentaré usar la «Conversación de Dos» para calmarla.",
    11: "¿Qué fue eso...",
    19: "Ugh, Kuroneko se cerró por mi pésima reacción.",
    20: "Al parecer, este Uriel tendría relación con Kirino.",
    36: "Urgh, ¡esto es tan vergonzoso!",
    39: "Kuroneko... Se ve complacida...",
    42: "No estoy seguro de cómo reaccionar...",
    44: "Decepcioné a Kuroneko...",
    47: "¡Kirino apareció de repente!",
}
a38_s = {
    1: ("Oye, hagan las paces.", "Kyousuke"),
    2: ("Me niego.", "Kuroneko"),
    5: ("...Aunque pensaba que Senpai estaba de mi lado.", "Kuroneko"),
    6: ("...Pensar que se convirtió en el subordinado de Uriel... Increíble.", "Kuroneko"),
    7: ("«Uriel»... ¿Te refieres a Kirino?", "Kyousuke"),
    8: ("Sí, en efecto.", "Kuroneko"),
    9: ("Como el «Ángel Caído», este es mi archienemigo: Uriel.", "Kuroneko"),
    10: ("¿De verdad? *tragar*", "Kyousuke"),
    12: ("Uri... ¿Qué es eso?", "Kyousuke"),
    13: ("No he oído mucho al respecto; ¿te importaría explicármelo?", "Kyousuke"),
    14: ("...¿Eh?", "Kuroneko"),
    15: ("E-Emm, Uriel es, el archienemigo del ángel caído, es decir, «mi» archienemigo.", "Kuroneko"),
    16: ("T-Tu hermana es la anfitriona del espíritu que... descendió...", "Kuroneko"),
    17: ("...Olvídalo.", "Kuroneko"),
    18: ("L-Lo siento.", "Kyousuke"),
    21: ("Hm-Hmph.", "Kuroneko"),
    22: ("No tengo nada que decirle a un subordinado de Uriel.", "Kuroneko"),
    23: ("Kuroneko, no soy el subordinado de Uriel.", "Kyousuke"),
    24: ("Entonces, ¿qué eres?", "Kuroneko"),
    25: ("Soy el subordinado del ángel caído, es decir, tuyo.", "Kyousuke"),
    26: ("...¿Eh?", "Kuroneko"),
    27: ("¿E-Estás estúpido?", "Kuroneko"),
    28: ("No digas eso.", "Kyousuke"),
    29: ("Eres demasiado enredoso.", "Kuroneko"),
    30: ("Las viles palabras de un mero humano no pueden conmover mi corazón.", "Kuroneko"),
    31: ("Mientras tanto, mis poderes mágicos se liberan lentamente.", "Kuroneko"),
    32: ("El fin prometido se acerca. Pronto, todo volverá a la nada.", "Kuroneko"),
    33: ("¿Qué estás diciendo...?", "Kyousuke"),
    34: ("...¡¿Se puede evitar?!", "Kyousuke"),
    35: ("...Sí. Si lo deseas... quizá pueda suprimir el salvaje poder de la oscuridad.", "Kuroneko"),
    37: ("¡Lo deseo! ¡Haré todo lo que esté en mi poder!", "Kyousuke"),
    38: ("Kukuku... De verdad, harás todo.", "Kuroneko"),
    40: ("...Entonces, tu alma será mía por toda la eternidad.", "Kuroneko"),
    41: (".........", "Kyousuke"),
    43: ("...Me decepcionas.", "Kuroneko"),
    45: ("¡Molesto!", "Kirino"),
    46: ("¡Uwah!", "Kyousuke"),
    48: ("¡¿De qué están hablando ustedes dos?! ¡Están enfrascados en su plática insana!", "Kirino"),
    49: ("¡Es molesto solo escucharlo! ¡¿No pueden terminarlo de una vez?!", "Kirino"),
    50: ("...Oh, vaya, ¿de qué te enojas?", "Kuroneko"),
    51: ("¿Será que te disgusta que te quiten el alma de tu hermano?", "Kuroneko"),
    52: ("¿Hah? Eso es tan absurdo que no lo entiendo.", "Kirino"),
    53: ("Desafortunado. Es momento.", "Kuroneko"),
    54: ("Todo ya terminó. Todos se desvanecerán...", "Kuroneko"),
    55: ("Por favor, no te pongas de mal humor, lo siento, ¿ok?", "Kyousuke"),
    56: ("No estoy de mal humor.", "Kuroneko"),
}

a39_n = {
    0: "Posponiendo la división del equipo",
    2: "Hmmm...",
    3: "Parece que esta conversación empeoró su ánimo.",
    12: "Objeciones... hay una.",
    13: "Cuando pienso en los riesgos de unirme al torneo, me siento intimidado...",
    14: "Pero si solo me repito, no hay forma de que lo acepten.",
    15: "Entonces, no tengo más opción que el método amable.",
    20: "¡¿No tienes consideración alguna?!",
    30: "Dios, esto no lleva a ninguna parte.",
    31: "¿Qué debería decir para resolver su pelea interminable?",
    32: "O mejor dicho, ¿por qué participan juntas en el torneo si se llevan tan mal?",
    33: "Es por el premio que tienen frente a ellas...",
    38: "Jejeje... ¡Las cosas van según lo planeado por una vez!",
    45: "Phew... Ahora se portará bien.",
    63: "En los días previos a la competencia, Kirino y yo pasamos por un entrenamiento especial agotador.",
    64: "Dicho esto, el que sufría el agotamiento era yo.",
    65: "Me obligaban a jugar Siscaly constantemente cada vez que estábamos en casa.",
    66: "Lo que pasó durante este tiempo... Lo siento, pero déjenme omitirlo. ¡Brillé precisamente porque me esforcé en permanecer en silencio!",
    67: "--Entonces, el día del torneo.",
    68: "Como resultado de este entrenamiento especial, nuestra pareja aseguró una fácil victoria en la primera ronda.",
    69: "Sin embargo, el destino se burló de nosotros de nuevo... Terminamos contra el equipo Kuroneko-Saori en la segunda ronda.",
    70: "Lo intentamos con todas nuestras fuerzas, pero aún así fuimos derrotados por el excelente trabajo en equipo del equipo Kuroneko-Saori.",
    71: "Sin embargo, incluso con su poderoso ataque, el equipo Kuroneko-Saori perdió por un pelo en la final.",
    72: "Aunque Kirino estaba amargada, Kuroneko y Saori aun así consiguieron el premio de segundo lugar que ella quería.",
    73: "Bueno, creo que esos resultados estuvieron bastante bien.",
    84: "Al final, ¡es lo mismo de siempre!",
    85: "Dos grandes no pueden coexistir.",
    86: "No solo no pueden coexistir, sino que solo pueden frustrarse y pelear hasta el amargo final...",
    99: "En los días previos a la competencia, Saori y yo usamos nuestro tiempo libre para pasar por un duro entrenamiento especial.",
    100: "...Entonces, el día de la competencia.",
    101: "Durante las semifinales, Saori y yo fuimos derrotados rápidamente por el equipo perfectamente coordinado de Kirino-Kuroneko.",
    102: "Sin embargo, incluso con su poderoso ataque, el equipo Kirino-Kuroneko perdió por un pelo en la final.",
    103: "Kirino y Kuroneko estaban amargadas. Pero creo que perder fue algo bueno.",
    104: "Porque aunque perdieron, consiguieron el segundo lugar. ¡Eso es genial, deberían estar orgullosas!",
    105: "Además...",
    106: "¿Unidas a través de una derrota? Parece que su relación mejoró.",
    107: "...¡Aunque podría ser solo mi imaginación!",
}
a39_s = {
    1: ("Dios mío. Por esto los meros humanos son compañeros tan molestos.", "Kuroneko"),
    4: ("Siento haber hecho que gastaras tu energía.", "Kyousuke"),
    5: ("Hmph... Está bien si entiendes, «si».", "Kuroneko"),
    6: ("Si solo esa presumida de la moda de allá fuera tan comprensiva como tú.", "Kuroneko"),
    7: ("¿Eh? ¿Dijiste algo?", "Kirino"),
    8: ("¡Vaya, vaya! ¡Los tres deberían calmarse!", "Saori"),
    9: ("Dejemos la división de equipos por ahora y concentrémonos en practicar batallas entre nosotros, ¿qué tal?", "Saori"),
    10: ("¡Oh! ¡Esa es una buena idea!", "Kyousuke"),
    11: ("¿Alguien tiene alguna objeción?", "Saori"),
    16: ("Por eso también estoy involucrado en la preparación de este torneo de juegos.", "Kyousuke"),
    17: ("¡Y eso es todo! Gracias, Kyousuke-shi, por tu consideración.", "Saori"),
    18: ("Yo sí tengo una objeción.", "Kuroneko"),
    19: ("¡Oye!", "Kyousuke"),
    21: ("Aparte de eso, ¿no hay un asunto más urgente por resolver?", "Kuroneko"),
    22: ("¿Qué es? ¿Estás tratando de iniciar una sesión espiritual?", "Kirino"),
    23: ("Hmph... Algo así. Una ceremonia de purificación. En otras palabras, una disculpa por tus acciones.", "Kuroneko"),
    24: ("¿Una disculpa? ¿A ti? ......¿Por qué?", "Kirino"),
    25: ("¿Tienes problemas para entender las palabras que usé?", "Kuroneko"),
    26: ("He estado escuchando en silencio hasta ahora, ¿no estabas soltando tonterías?", "Kirino"),
    27: ("¿Cuándo has estado callada? Estás berreando todo el tiempo de forma molesta.", "Kuroneko"),
    28: ("¿Hah? ¿Qué es eso? No tengo idea de qué dices.", "Kirino"),
    29: ("...Ustedes dos, llevan un rato en bucle...", "Kyousuke"),
    34: ("¡Kuroneko! ¡¿No quieres el premio súper raro?!", "Kyousuke"),
    35: ("...E-Eso...", "Kuroneko"),
    36: ("De verdad lo quieres, ¿no? Tú también, Kirino.", "Kyousuke"),
    37: ("Ugh... Por supuesto.", "Kirino"),
    39: ("Si ustedes dos no pueden unirse, ¡entonces el premio terminará en manos de otra persona!", "Kyousuke"),
    40: ("¿Está bien eso para ti?", "Kyousuke"),
    41: ("......", "Both"),
    42: ("¿El disfraz de personaje súper raro, o los artículos de promoción súper raros, no los quieren?", "Kyousuke"),
    43: ("Uuu... Los quiero tanto...", "Kirino"),
    44: ("¿Cierto? Entonces cuiden su actitud.", "Kyousuke"),
    46: ("Entonces, tú serás mi pareja.", "Kirino"),
    47: ("......¿Eh?", "Kyousuke"),
    48: ("No queda mucho tiempo hasta el torneo. Vivimos en la misma casa, así que podemos entrenar eficientemente.", "Kirino"),
    49: ("Tienes un punto, pero...", "Kyousuke"),
    50: ("¿Qué? ¿Tienes alguna objeción?", "Kirino"),
    51: ("Ninguna, ¿cierto? ¡Puedes jugar con uuuna hermanita tan linda!", "Kirino"),
    52: ("...¿Dónde está esa hermanita linda?", "Kyousuke"),
    53: ("¿Tienes los ojos podridos?", "Kirino"),
    54: ("Parece que las parejas han sido decididas.", "Saori"),
    55: ("¿Eh? ¿Decididas así nomás?", "Kyousuke"),
    56: ("...Aunque creo que yo sería la más indicada para apoyarte, ya que tus habilidades son las peores.", "Kuroneko"),
    57: ("Sin embargo, si los hermanos van a emparejarse, solo me queda unirme a Saori entonces.", "Kuroneko"),
    58: ("...¿Está bien?", "Kyousuke"),
    59: ("¿No dije que sí? Te estás alargando.", "Kirino"),
    60: ("Al contrario, la derrota es inaceptable conmigo.", "Kirino"),
    61: ("¡Prepárate!", "Kirino"),
    62: ("Entendido...", "Kyousuke"),
    74: ("Ah... ¿Deberíamos dejarlo así por hoy?", "Saori"),
    75: ("Es demasiado pronto para decidir los equipos en este punto.", "Saori"),
    76: ("Tómate tu tiempo para considerar tus opciones, Kyousuke-shi.", "Saori"),
    77: ("C-Cierto...", "Kyousuke"),
    78: ("Kiririn-shi, así son las cosas.", "Saori"),
    79: ("Entonces terminemos por hoy.", "Kirino"),
    80: ("¡Nos vemos!", "Kirino"),
    81: ("...Phew.", "Kyousuke"),
    82: ("Arrepiéntete. Vamos. Rápido.", "Kuroneko"),
    83: ("Cállate, chica chuunibyou malvada.", "Kirino"),
    87: ("Ugh... Esto no tiene fin...", "Saori"),
    88: ("En ese caso, tú y yo.", "Kyousuke"),
    89: ("¿Eh?", "Saori"),
    90: ("Serás mi pareja.", "Kyousuke"),
    91: ("¿Kyousuke-shi y... yo?", "Saori"),
    92: ("Espera, ¿qué estás decidiendo tú solo?", "Kirino"),
    93: ("¡Eso! Si Saori se convierte en tu pareja, entonces mi pareja sería automáticamente esta chica, ¿no?", "Kuroneko"),
    94: ("¿No es esta una oportunidad perfecta para conocerse?", "Kyousuke"),
    95: ("Si el premio está en juego, entonces no tendrán tiempo de pelear, ¿cierto?", "Kyousuke"),
    96: ("No es que quiera pelear. Es solo que ella me arrastró...", "Kirino"),
    97: ("Yo, yo tampoco estoy interesada en discusiones sin sentido.", "Kuroneko"),
    98: ("Entonces no hay problema. Saori y yo en un equipo, Kuroneko y Kirino en el otro.", "Kyousuke"),
}

a40_n = {
    0: "Alias «Chica Común»",
    1: "De camino a casa al día siguiente...",
    6: "--Normal.",
    7: "Esa es la mejor descripción para esta amiga de la infancia con gafas.",
    8: "Esta persona se llama Tamura Manami.",
    9: "Como pueden ver, su apariencia es muy normal.",
    10: "Aunque su rostro es bastante lindo, es un poco común.",
    11: "Sería una verdadera belleza sin sus gafas! O eso me gustaría decir, pero no.",
    12: "Sus notas son decentes. No participa en ningún club; sus intereses son la cocina y la costura.",
    13: "Aunque su actitud le da muchos amigos, los cercanos con los que pasarías tiempo después de la escuela se redujeron hasta ser no muchos.",
    21: "Le conté a la chica de gafas, siempre sonriente y despistada, todo lo que pasó ayer.",
    34: "Esta es «Manami», y aun así dice cosas sin sentido con una cara engreída.",
}
a40_s = {
    2: ("...*suspiro*", "Kyousuke"),
    3: ("¿Estás bien, Kyou-chan? Has estado suspirando todo el tiempo.", "???"),
    4: ("Eres la única que me habla con tanta dulzura, Manami.", "Kyousuke"),
    5: ("Somos amigos de la infancia, así que es normal que me preocupe por ti.", "Manami"),
    14: ("¿Qué pasa? ¿Por qué estás mirando mi cara?", "Manami"),
    15: ("Solo estaba pensando que eres completamente ordinaria.", "Kyousuke"),
    16: ("Jeje, me haces sonrojar.", "Manami"),
    17: ("No, no es algo para sonrojarse... *suspiro*", "Kyousuke"),
    18: ("Kyou-chan, ¿por qué sigues suspirando hoy? Tu felicidad se agotará, ¿sabes?", "Manami"),
    19: ("Sí, sí... Oh, cierto, ¿te importa escucharme un rato?", "Kyousuke"),
    20: ("Por supuesto, si estás bien conmigo.", "Manami"),
    22: ("Hmm hmm... Ya veo.", "Manami"),
    23: ("¿Entonces Kyou-chan está dudando si ir a apoyar a Kirino al torneo?", "Manami"),
    24: ("Exacto.", "Kyousuke"),
    25: ("Ah, sí deseo apoyarlos, excepto a Kirino.", "Kyousuke"),
    26: ("Jejeje, ¿así es?", "Manami"),
    27: ("En cualquier caso, sí deseo dar mi apoyo, pero Kirino ha estado actuando huraña y enojada desde la mañana.", "Kyousuke"),
    28: ("...¿De verdad?", "Manami"),
    29: ("Es verdad, ¿por qué me dudas?", "Kyousuke"),
    30: ("¿De verdad? ¿Kirino-chan está realmente enojada?", "Manami"),
    31: ("¡Me pateó cuando nos cruzamos en el pasillo!", "Kyousuke"),
    32: ("Oh, ya veo. Entonces, creo que no está enojada.", "Manami"),
    33: ("¿Eh?", "Kyousuke"),
    35: ("¿Quieres ir a apoyarla?", "Manami"),
    36: ("...Lo consideraré.", "Kyousuke"),
    37: ("Okay.", "Manami"),
}

a43_n = {
    0: "Alias «Chica Común»",
    13: "Aunque, eso es absolutamente imposible... Nunca pensé que me diría algo así.",
    14: "¿Es este el poder de una amiga de la infancia?",
    32: "Esta chica... Volvió a decir naturalmente algunas cosas realmente vergonzosas...",
}
a43_s = {
    1: ("¿Tú... puedes entender la mente de Kirino?", "Kyousuke"),
    2: ("No puedo. Solo estoy adivinando.", "Manami"),
    3: ("Estoy segura de que Kirino-chan depende de ti.", "Manami"),
    4: ("¡¿Eh?!", "Kyousuke"),
    5: ("¿Cómo llegaste siquiera a esa conclusión?", "Kyousuke"),
    6: ("Eres un hermano mayor afortunado.", "Manami"),
    7: ("¡Ni modo! ¡Esa chica no podría estar dependiendo de mí!", "Kyousuke"),
    8: ("¡Esa chica no es una hermana tan buena!", "Kyousuke"),
    9: ("Eso no es verdad.", "Manami"),
    10: ("¡Lo es! ¡Lo sé!", "Kyousuke"),
    11: ("¿Oh, en serio?", "Kyousuke"),
    12: ("¡Seguro que sí! Así que, creo que sería mejor que Kyou-chan tenga más confianza.", "Manami"),
    15: ("Eso es porque...", "Manami"),
    16: ("¿Porque qué?", "Kyousuke"),
    17: ("Yo también dependo de Kyou-chan en algunas cosas.", "Manami"),
    18: ("¡¿Q-Qué estás diciendo?! ¡Tan de repente...!", "Kyousuke"),
    19: ("Estás avergonzado ahora～", "Manami"),
    20: ("¡N-No... no estoy avergonzado!", "Kyousuke"),
    21: ("Jeje. Estás escondiendo tu vergüenza. Kyou-chan es tan lindo.", "Manami"),
    22: ("...Ah, en serio...", "Kyousuke"),
    23: ("«Ah, en serio»... ¿Eso es todo?", "Manami"),
    24: ("¿Qué más podría decir?", "Kyousuke"),
    25: ("Dios...", "Manami"),
    26: ("Incluso yo... siempre pensé en ser de ayuda para Kyou-chan, ¿sabes?", "Manami"),
    27: ("No te molestes.", "Kyousuke"),
    28: ("Buuh... Tan cruel...", "Manami"),
    29: ("No dependeré de ti.", "Kyousuke"),
    30: ("¿Hmm? Entonces no te ayudaré a estudiar de ahora en adelante.", "Manami"),
    31: ("¡Estaba equivocado! ¡Manami, gracias por todo!", "Kyousuke"),
}

data = {
    "000scriptAKYO_0037A.obj": build(a37_n, a37_s),
    "000scriptAKYO_0038T.obj": build(a38_n, a38_s),
    "000scriptAKYO_0039A.obj": build(a39_n, a39_s),
    "000scriptAKYO_0040A.obj": build(a40_n, a40_s),
    "000scriptAKYO_0043T.obj": build(a43_n, a43_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))