import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0053_n = {
    0: "Ruta de Saori · Informe De Ejecución Del Plan",
    29: "Ya veo, ella soportó bastante por sí sola.",
    30: "Y yo me burlé de eso con mis palabras... Gah, maldición, fallé...!",
    31: "Así es... Ella lo consideró largamente, y aceptó este matrimonio.",
    32: "Probablemente le fue difícil hablar de eso conmigo, un extraño.",
}
a0053_s = {
    1: ("Saori. Entiendo cómo te sientes.", "Kyousuke"),
    2: ("¿Kyousuke-shi?", "Saori"),
    3: ("Ya que hemos llegado a esto, ya no me importan las apariencias. Haré que canceles este compromiso.", "Kyousuke"),
    4: ("¿C-C-Cancelar el compromiso?", "Saori"),
    5: ("Exactamente. ¡Eso es algo fácil de hacer!", "Kyousuke"),
    6: ("No renunciarás a ser otaku, y no tendrás que casarte.", "Kyousuke"),
    7: ("Matarás dos pájaros de un tiro.", "Kyousuke"),
    8: ("Sin embargo, no es, ¡no es algo que yo pueda hacer!", "Saori"),
    9: ("¡¿Por qué estás dudando sobre eso?!", "Kyousuke"),
    10: ("¡No decidas tú mismo si puedes hacerlo o no!", "Kyousuke"),
    11: ("Es extraño, cuando eres tú quien lo dice, siento que puedo hacerlo...", "Saori"),
    12: ("Pero... ¡Pero!", "Saori"),
    13: ("Tú lo dices, pero Saori-", "Kyousuke"),
    14: ("¡NOESNOESNOESNOES! ¡Es totalmente imposible!", "Saori"),
    15: ("¡Kyousuke-shi no se da cuenta de la gravedad de la situación!", "Saori"),
    16: ("¡No tienes que refutar eso tan frenéticamente!", "Kyousuke"),
    17: ("¡Kyousuke-shi no entiende!", "Saori"),
    18: ("El peso detrás de la cancelación de un compromiso... ¡No tienes ni la más remota idea de las implicaciones!", "Saori"),
    19: ("¿Cancelar el compromiso? Significa anular el matrimonio.", "Kyousuke"),
    20: ("No es... Eso no es, Kyousuke-shi...", "Saori"),
    21: ("No es un asunto tan simple...", "Saori"),
    22: ("Saori...", "Kyousuke"),
    23: ("No me concierne solo a mí.", "Saori"),
    24: ("Ya que implica a ambas familias, no es algo que pueda hacer por mi propia voluntad.", "Saori"),
    25: ("S-Supongo que es cierto...", "Kyousuke"),
    26: ("Incluso si no puedo decir que lo que dices no ha cruzado por mi mente...", "Saori"),
    27: ("Sin embargo, no es un mundo donde una sola chica pueda actuar egoístamente y salirse con la suya...", "Saori"),
    28: ("Por eso, considera que toda esta charla sobre cancelar el compromiso no ha pasado.", "Saori"),
    33: ("¿Kyousuke-shi? ¿Me estás escuchando?", "Saori"),
    34: ("Ah, sí... Por supuesto.", "Kyousuke"),
    35: ("Sé lo grave que es cancelar un compromiso. Implica a ambas familias después de todo.", "Kyousuke"),
    36: ("¡Oooh! ¡Como era de esperarse de Kyousuke-shi!", "Saori"),
    37: ("¡Que entiendas tanto de mí...! ¿Cómo es que no fui consciente de esto?", "Saori"),
    38: ("Me habías asustado por un momento aquí.", "Saori"),
    39: ("Pero verás, ¿podrías intentar escucharme con la mente clara?", "Kyousuke"),
    40: ("En respuesta al consejo que te di, dijiste cosas como «Es imposible» o «Es inútil», ¿verdad?", "Kyousuke"),
    41: ("¿Por qué decidiste hacerlo así desde el principio?", "Kyousuke"),
    42: ("Eso es...", "Saori"),
    43: ("Al rechazar sugerencias, no puedes seguir un consejo, ni resolver tus problemas.", "Kyousuke"),
    44: ("¿Qué es lo que quieres que diga, Saori?", "Kyousuke"),
    45: ("...", "Saori"),
    46: ("Nada pasará si sigues aplastando posibilidades. ¡Intentemos algo antes de decidir que es imposible!", "Kyousuke"),
    47: ("Pero la situación actual es...", "Saori"),
    48: ("Si tuviera que comparar esta situación con un juego de shogi, sería «Jaque Mate».", "Saori"),
    49: ("¿¡Qué es un jaque mate! Si tienes miedo de estar en un callejón sin salida, ¡dale la vuelta!", "Kyousuke"),
    50: ("S-Semejante desconsideración escandalosa por la propiedad personal!", "Saori"),
    51: ("Sin embargo, esto no es justo, ¿sabes?", "Saori"),
    52: ("¡Esta no es una situación que requiera juego limpio!", "Kyousuke"),
    53: ("Hacerlo mientras gritas, ¡no es diferente a un berrinche de niño!", "Saori"),
    54: ("¡Hgnn! ¡Eso puede ser cierto pero...!", "Kyousuke"),
    55: ("Maldición... ¿No tengo algo bajo la manga?", "Kyousuke"),
    56: ("Está bien, Kyousuke-shi. Después de todo esto, he tomado mi resolución.", "Saori"),
    57: ("Pensé demasiado en esto de forma egoísta, fue mi error presionar irrazonablemente mis preocupaciones sobre Kyousuke-shi.", "Saori"),
    58: ("¿Un error...? ¡No digas cosas así!", "Kyousuke"),
    59: ("Muchas gracias. El simple hecho de escuchar esas palabras es suficiente para apretar mi corazón por el hecho de que tengo un amigo tan bueno.", "Saori"),
    60: ("Sin embargo, todo lo que hice fue causarte problemas.", "Saori"),
    61: ("Por eso, es suficiente.", "Saori"),
    62: ("¡El que debería pensar con claridad es Kyousuke-shi!", "Saori"),
    63: ("¿Qué?", "Kyousuke"),
    64: ("¡Cuando actúas tan precipitadamente, cualquier forma de pensamiento racional desaparece!", "Saori"),
    65: ("De todos modos, ¿qué tal tomarnos un descanso para comer algo de hielo raspado? Te invito, así que-", "Saori"),
    66: ("¡Saori! ¡No te hagas la persona «agradable»!", "Kyousuke"),
    67: ("¡Qué...! ¡Es muy grosero de tu parte decir eso!", "Saori"),
    68: ("¡Cállate, maldición! ¡Ser una persona «agradable» es el primer paso para ser un don nadie!", "Kyousuke"),
    69: ("No quiero que actúes como una persona «agradable» con la que la gente solo pasa el rato por su propio beneficio.", "Kyousuke"),
    70: ("¡*risita*! ¿Qué es esa teoría desordenada?", "Saori"),
    71: ("¿Desordenada o no, quiero discutir mi creencia de que SÍ hay una posibilidad.", "Kyousuke"),
    72: ("En serio... Por eso Kyousuke-shi es...", "Saori"),
    73: ("Hielo raspado, huh...", "Kyousuke"),
    74: ("¡Son increíbles en esta temporada! Te llenas la boca con escamas de hielo-", "Saori"),
    75: ("¿Y te congelas el cerebro, y te vuelves la lengua del color del jarabe?", "Kyousuke"),
    76: ("¡Cierto cierto! ¡Te estás divirtiendo solo de pensarlo!", "Saori"),
    77: ("Entonces, démosle un cierre a esta conversación sombría, y comamos algo de hielo raspado conmigo-", "Saori"),
    78: ("No, no le daré un cierre.", "Kyousuke"),
    79: ("De todos modos, hagamos una ceremonia de despedida...", "Saori"),
    80: ("Cuando llegue el momento, me gustaría que tomaras asiento como asistente.", "Saori"),
    81: ("¡No necesito un asiento!", "Kyousuke"),
    82: ("¡¿Kyo-Kyousuke-shi?!", "Saori"),
    83: ("¡También me niego a aceptar algo como una ceremonia de despedida! Podrías hacer arreglos para tenerme un asiento, pero no lo tomaré.", "Kyousuke"),
    84: ("Te lo ruego, no digas algo como «separación» tan fácilmente...", "Kyousuke"),
    85: ("Ah...", "Saori"),
    86: ("No sé si hay una mejor manera o no, pero tengo pensamientos sobre esto.", "Kyousuke"),
    87: ("Así que por favor, escucha lo que tengo que decir.", "Kyousuke"),
    88: ("Entonces, así es como es...", "Saori"),
    89: ("¡NOOOO es así en absoluto!!!", "Kyousuke"),
    90: ("¡¿Hiiiiiiiii?! ¡Kyousuke-shi! ¡Estás muy ruidoso!", "Saori"),
    91: ("¡¿Cómo puedo aceptar eso sin gritar! Estúpido!", "Kyousuke"),
    92: ("¡Secuestrar a esta doncella pura e inocente y llamarla estúpida es muy cruel!", "Saori"),
    93: ("¡Cállate! Eres estúpida, ¡así que te llamaré estúpida!", "Kyousuke"),
}

a0055_n = {
    0: "Ruta de Saori · Informe De Ejecución Del Plan",
    4: "Se ha puesto seria...",
    5: "¿Debería intentar aligerar el ambiente un poco?",
    6: "No, finalmente logré concentrarme, no debería decir nada innecesario.",
    13: "Recordé a esos tipos que escuché en la estación.",
    14: "Cuando los escuché, al principio estaba pensando...",
    15: "«¡Qué están diciendo frente a Saori!»",
    16: "Pero ahora que lo pienso, puede haber sido una señal de Dios.",
    25: "¿Quizás fallé en expresar mi punto con la forma en que lo dije...",
    26: "Hm... Parece que las palabras que elegí no fueron las apropiadas.",
    40: "Parece que la inteligente Saori se dio cuenta.",
    41: "Para escuchar cuál era la causa de su incomodidad, tuve que intentar tres veces.",
    42: "Incluso pasé por las intromisiones de Kirino sin inmutarme.",
    47: "Regocijado por las palabras de Saori, le di una palmada en la cabeza tal como solía hacer con Kirino.",
    48: "Aunque Saori es más grande que yo.",
    53: "*tragar* Q-¿Qué está pasando...",
    54: "La forma en que lo dice...",
    55: "Un poco... me hace latir el corazón...",
}
a0055_s = {
    1: ("Si estás dispuesto a llegar tan lejos, ¿escucharé lo que tienes que decir?", "Saori"),
    2: ("Aunque te advierto, no perdonaré ninguna broma.", "Saori"),
    3: ("N-No lo haré.", "Kyousuke"),
    7: ("No tengo razón para bromear cuando mi amiga está pasando por problemas.", "Kyousuke"),
    8: ("Jaja, la forma en que me miras y dices eso, ¡me hace sentir incómoda!", "Saori"),
    9: ("Entonces, ¿cuál es el plan?", "Saori"),
    10: ("Puede que de hecho seas incapaz de cancelar el compromiso.", "Kyousuke"),
    11: ("Pero, ¿qué tal el otro lado?", "Kyousuke"),
    12: ("¿Lo que significa...?", "Saori"),
    17: ("¡Tu prometido es un normal!", "Kyousuke"),
    18: ("......¿Huh?", "Saori"),
    19: ("¡Tu prometido está igualando con un normal!", "Kyousuke"),
    20: ("¡Y en este momento, Saori no se está comportando como uno!", "Kyousuke"),
    21: ("¡Estás desemparejada con tu prometido!", "Kyousuke"),
    22: ("Em... Kyousuke-shi...", "Saori"),
    23: ("...¿No estás equivocado...?", "Saori"),
    24: ("¿E-Estoy...?", "Kyousuke"),
    27: ("Entonces, ¿qué tal esto?", "Kyousuke"),
    28: ("Eres una otaku de pies a cabeza. Haz que tu prometido entienda eso.", "Kyousuke"),
    29: ("Él no entiende a los otakus, así que no entenderá ni la mitad de lo que dices.", "Kyousuke"),
    30: ("Si haces eso, ¿no hay una posibilidad de que, a la luz de eso, tu prometido cancele el compromiso por su lado?", "Kyousuke"),
    31: ("Hm...", "Saori"),
    32: ("Ya veo. Kyousuke-shi es todo un estratega.", "Saori"),
    33: ("Pero me pregunto si saldría bien...", "Saori"),
    34: ("Entiendo cómo te sientes, si esto fallara, de hecho perderías el ánimo.", "Kyousuke"),
    35: ("Pero, incluso si yo mismo fallé dos veces, a la tercera fue la vencida.", "Kyousuke"),
    36: ("¿Fallaste?", "Saori"),
    37: ("La primera vez fue la llamada telefónica, la segunda vez fue el chat.", "Kyousuke"),
    38: ("Y a la tercera vez, tomando el lugar de Kuroneko, logré alcanzar mi objetivo al fin.", "Kyousuke"),
    39: ("Ah...", "Saori"),
    43: ("Entiendo.", "Saori"),
    44: ("Me siento un poco incómoda actuando para ser desagradable...", "Saori"),
    45: ("Pero si quiero seguir siendo quien soy, lo mantendré.", "Saori"),
    46: ("¡Bien, bien dicho Saori!", "Kyousuke"),
    49: ("¡¿K-Kyousuke-shi?!", "Saori"),
    50: ("¡Oh! ¡Lo siento! Eso fue malo de mi parte.", "Kyousuke"),
    51: ("No... Solo me sorprendió un poco...", "Saori"),
    52: ("N-No estuvo mal... ¿Supongo?", "Saori"),
    56: ("Tu compatibilidad es mala; es imposible que se queden juntos.", "Kyousuke"),
    57: ("Tu prometido puede haber dicho que entiende a los otakus.", "Kyousuke"),
    58: ("Pero no los aprueba, ¿verdad?", "Kyousuke"),
    59: ("Ughhh... De hecho... No puedo discutir con eso...", "Saori"),
}

a0058_n = {
    0: "Ruta de Saori · Informe De Ejecución Del Plan",
    114: "De algún modo no pude decir, «¿Lo decías en serio?»",
}
a0058_s = {
    1: ("Si ese es el caso, deberías decirle que ser otaku es justo quien eres.", "Kyousuke"),
    2: ("Si él tiene un problema, entonces se retirará del compromiso.", "Kyousuke"),
    3: ("¿Ser otaku es justo quien soy...?", "Saori"),
    4: ("No hay duda de que esto es quien soy, y hay personas que piensan que «solo nos gusta el anime».", "Saori"),
    5: ("Sin embargo, no sé si será tan fácil...", "Saori"),
    6: ("Por el bien de ti y de tu prometido, tienes que asegurarte de que él sepa que el que ustedes dos se junten es un error.", "Kyousuke"),
    7: ("Por el bien de mi prometido...", "Saori"),
    8: ("Sí. ¿Crees que ambos pueden ser realmente felices si basan su matrimonio en una mentira?", "Kyousuke"),
    9: ("Eso es... ciertamente correcto.", "Saori"),
    10: ("Pero, eso significaría traicionar a mis padres.", "Saori"),
    11: ("¡¿Tus padres?! ¡Este es tu problema, no el problema de tus padres!", "Kyousuke"),
    12: ("...!", "Saori"),
    13: ("¿Qué quieres hacer? ¿Qué estás pensando?", "Kyousuke"),
    14: ("¿Qué quieres hacer tú? No tus padres... ¡No sigas a ciegas lo que tus padres dicen! ¡Piensa por ti misma!", "Kyousuke"),
    15: ("Estoy siendo apoyada por mis padres.", "Saori"),
    16: ("A pesar de eso, desobedecerles... Siento que eso es solo ser egoísta.", "Saori"),
    17: ("...Realmente te importan tus padres.", "Kyousuke"),
    18: ("Sí. Mi familia es irremplazable.", "Saori"),
    19: ("Pero, ¿estás realmente bien así?", "Kyousuke"),
    20: ("No puedes avanzar así.", "Kyousuke"),
    21: ("¿No hará que las cosas sean mucho más fáciles para ti si dices lo que realmente piensas?", "Kyousuke"),
    22: ("Si no lo haces, nunca llegarás a ninguna parte.", "Kyousuke"),
    23: ("Es exactamente como dices.", "Saori"),
    24: ("Sin embargo, ¿cómo debería enfrentarlos...?", "Saori"),
    25: ("¡Puedes resolverlo ahí mismo!", "Kyousuke"),
    26: ("Si tus padres te desheredan, entonces puedes unirte a mi familia.", "Kyousuke"),
    27: ("¡¿Ky-Kyousuke-shi?!", "Saori"),
    28: ("Mi padre es un poco terco pero, si hablo con él, estoy seguro de que entenderá...", "Kyousuke"),
    29: ("¡Kirino y mi madre te recibirán con gusto!", "Kyousuke"),
    30: ("Apoyarte no es ningún problema.", "Kyousuke"),
    31: ("Ah... Eso es lo que querías decir...", "Saori"),
    32: ("Estaba segura de que estabas pensando en casarte conmigo.", "Saori"),
    33: ("¿Eh?", "Kyousuke"),
    34: ("¡Ah, nada!", "Saori"),
    35: ("Aun así... ¿tus palabras tienen algún tipo de efecto mágico adjunto?", "Saori"),
    36: ("Solo tu ánimo me ha hecho sentir mucho mejor.", "Saori"),
    37: ("Saori...", "Kyousuke"),
    38: ("«Deberías sonreír» es lo que quieres decir, ¿verdad?", "Saori"),
    39: ("¡¿Huh?! Como era de esperarse, esa broma no se usa a menudo...", "Kyousuke"),
    40: ("Fufu... Aún te queda camino por recorrer.", "Saori"),
    41: ("¡Pero sí tienes espíritu!", "Saori"),
    42: ("G-Gracias...", "Kyousuke"),
    43: ("Pero, ya que valoraste mi espíritu, ¿no tienes que valorar tu propio coraje?", "Kyousuke"),
    44: ("Pero, incluso entonces... todavía no puedo tomar una decisión.", "Saori"),
    45: ("¿Qué pasa si mis padres me odian por traicionar sus expectativas...?", "Saori"),
    46: ("Uno puede conseguir un nuevo hobby, pero uno no puede conseguir nuevos padres.", "Saori"),
    47: ("Cuando pienso en que me odien, diciendo, «No necesitamos una hija como tú»... pierdo la resolución...", "Saori"),
    48: ("¿Entonces, pasarás el resto de tu vida lamentando tus acciones?", "Kyousuke"),
    49: ("Eso es...", "Saori"),
    50: ("Dilo, Saori. Tu prometido no está aquí, ni tus padres...", "Kyousuke"),
    51: ("Ky-Kyousuke-shi...", "Saori"),
    52: ("Y-Yo... realmente no quiero...", "Saori"),
    53: ("e-este matrimonio...", "Saori"),
    54: ("...No entiendo...", "Saori"),
    55: ("Simplemente no sé qué debería estar haciendo...", "Saori"),
    56: ("¡Cálmate, Saori! Nada bueno pasará si entras en pánico.", "Kyousuke"),
    57: ("Pero...yo...yo...!", "Saori"),
    58: ("¿Es así como realmente te sientes...?", "Kyousuke"),
    59: ("...", "Saori"),
    60: ("Quiero estar con mis amigos... para siempre, si es posible...", "Saori"),
    61: ("Pero, tengo miedo de traicionar a mis padres...", "Saori"),
    62: ("Saori...", "Kyousuke"),
    63: ("Kyousuke-shi...", "Saori"),
    64: ("Bueno entonces, ¿qué tal si me secuestras?", "Saori"),
    65: ("¿Estás tratando de huir otra vez?", "Kyousuke"),
    66: ("¡Entiendo totalmente que estás sufriendo! Con amigos y familia... Puedo entender no saber cuál poner primero.", "Kyousuke"),
    67: ("Aun así, tienes que elegir. Si no lo haces, perderás una parte de ti misma.", "Kyousuke"),
    68: ("¿Estás bien con eso? ¿Estás bien negándote a ti misma, y dejándote a la deriva?", "Kyousuke"),
    69: ("Kyousuke-shi...", "Saori"),
    70: ("Y-Yo... ¿Puedo realmente elegir por mí misma?", "Saori"),
    71: ("¿Puedo convertirme en una protagonista? ¿Podría pensar y actuar por mí misma?", "Saori"),
    72: ("Por supuesto que puedes. Esto no es sobre nadie más. Esta es tu historia.", "Kyousuke"),
    73: ("...Hm, eso es verdad.", "Saori"),
    74: ("Debería tener el derecho de elegir por mí misma...", "Saori"),
    75: ("Soy yo misma... Y eso está bien, ¿verdad?", "Saori"),
    76: ("Sí, eres tú misma.", "Kyousuke"),
    77: ("Como otaku, y como dama, eres extremadamente rara pero, también eres una amiga irremplazable.", "Kyousuke"),
    78: ("...Entiendo.", "Saori"),
    79: ("Recuperaré la parte de mí que he perdido.", "Saori"),
    80: ("Lo intentaré, mediante el atractivo otaku.", "Saori"),
    81: ("Sí, adelante.", "Kyousuke"),
    82: ("¡Lo haré!", "Saori"),
    83: ("Ah...Kyousuke-shi, ¿puedo preguntarte algo?", "Saori"),
    84: ("Huh, ¿qué?", "Kyousuke"),
    85: ("Si el próximo plan sale bien, ¿podemos... juntos...", "Saori"),
    86: ("......", "Saori"),
    87: ("¿Hacer qué juntos?", "Kyousuke"),
    88: ("Uh, en realidad, no importa.", "Saori"),
    89: ("¡¿Huh, qué!? ¡No me dejes con la incógnita!!", "Kyousuke"),
    90: ("Oh... Podría ser solo un mal presagio.", "Saori"),
    91: ("Sabes, lo ves con frecuencia en las películas.", "Saori"),
    92: ("Cuando la gente dice, «Cuando la batalla termine, cásate conmigo» antes de morir en batalla.", "Saori"),
    93: ("Ah... Eso sí pasa.", "Kyousuke"),
    94: ("Por eso te lo diré cuando regrese.", "Saori"),
    95: ("Está bien. Si eso es lo que quieres.", "Kyousuke"),
    96: ("Lo espero con ansias, así que ve a por ellos.", "Kyousuke"),
    97: ("...¡Lo haré!", "Saori"),
    98: ("...¡¿Huh?!", "Kyousuke"),
    99: ("¿S-Secuestrarte? ¿Quieres decir fugarnos?", "Kyousuke"),
    100: ("De ninguna manera, entiendo tus sentimientos pero, tengo mis propios asuntos en curso...", "Kyousuke"),
    101: ("...Entonces, ¿podrías esperar un rato por la respuesta?", "Kyousuke"),
    102: ("¡Jeje!", "Saori"),
    103: ("¿Jeje?", "Kyousuke"),
    104: ("¡Jajaja! ¡Solo estaba bromeando!", "Saori"),
    105: ("¿Tú... me engañaste?", "Kyousuke"),
    106: ("¡Por favor no te enojes conmigo! Fue solo una travesura linda.", "Saori"),
    107: ("¡¿Pensé que lo decías en serio?!", "Kyousuke"),
    108: ("¿Eh...?", "Saori"),
    109: ("Si realmente lo pensabas, pensé que haría lo que pudiera...", "Kyousuke"),
    110: ("Kyousuke-shi... ¿Irías tan lejos por mí?", "Saori"),
    111: ("...Lo siento. Estaba pisoteando tus sentimientos.", "Saori"),
    112: ("Pero, ¿alguna vez he sido sentimental?", "Saori"),
    113: ("...Quieres decir...", "Kyousuke"),
    115: ("Aunque, gracias a ti, creo que mi carga se ha aligerado.", "Saori"),
    116: ("No sé qué pasará pero... Con lo que pueda hacer, daré todo de mí.", "Saori"),
    117: ("...Sí. Ve a por ello, Saori.", "Kyousuke"),
    118: ("Uhg, ¡no hay nada más que hacer que ir en un viaje para encontrarme a mí misma...!", "Saori"),
    119: ("Sin reacción de Kyousuke-shi, huh...?", "Saori"),
    120: ("Con más razón para desaparecer sin dejar rastro...", "Saori"),
    121: ("¡Espera, espera, espera! Si vas tan lejos, ¿no se pondrán tristes tus padres?", "Kyousuke"),
    122: ("Eso es eso, y esto es esto.", "Saori"),
    123: ("¡No lo hagas parecer tan simple!", "Kyousuke"),
    124: ("¡Si tienes la resolución de desaparecer, entonces úsala para atacar!", "Kyousuke"),
    125: ("Kyousuke-shi...", "Saori"),
    126: ("Ciertamente, ahora que lo dices.", "Saori"),
    127: ("¿Verdad?", "Kyousuke"),
    128: ("Huh, siento como si pudiera hacerlo.", "Saori"),
    129: ("¡Sí, ese es el espíritu!", "Kyousuke"),
    130: ("¡Ve y encuéntrate a ti misma!", "Kyousuke"),
    131: ("Muy bien. Si lo dices así.", "Saori"),
    132: ("¡Floreceré por mi propio bien!", "Saori"),
    133: ("¡Incluso si termino con un destino horrible...", "Saori"),
    134: ("¡No te vuelvas débil de mente ahora! ¡Ponte en marcha con resolución y regresa!", "Kyousuke"),
    135: ("¡Sí, señor!!", "Saori"),
}

a0060_n = {
    0: "Ruta de Saori · Aventurándome En Akiba Una Vez Más",
    1: "Tres días después de la reunión de estrategia con Saori, una vez más me encuentro entrando a la Sagrada Tierra Otaku de Akihabara.",
    2: "Pero esta vez, no estoy aquí porque tenga una cita con Saori.",
    3: "La razón esta vez: mi hermana.",
    8: "¿Quién te crees que eres?",
    16: "Ah, así que es así.",
    17: "En resumen, me estás ordenando que deje los estudios, camine ahí afuera bajo el sol ardiente, y me seque bañándome en los intensos rayos de la luz",
    18: "solar directa.",
    19: "¡Incluso yo me molestaría ante el egoísmo de Kirino, ¿sabes?!",
    20: "Hoy, como hermano, necesito tener una charla severa con Kirino.",
    25: "...¿Ven? Le hablé severamente, ¿no?",
    29: "Por ahora, hagamos nuestro camino a la tienda en la Calle Principal Chuo-dori.",
    30: "Durante los fines de semana y feriados, Akihabara se llena de multitudes bulliciosas.",
    31: "Hay mucha gente aquí también. Empiezo a refunfuñar contra los transeúntes inocentes que caminan por la calle conmigo.",
    32: "Cada uno de ellos lleva esa moda otaku fácilmente reconocible...",
    33: "¿Dónde compras esos lentes giratorios hoy en día? Incluso Manami usa lentes normales...",
    34: "...Aunque son un poco anticuados.",
    38: "El uso involuntario de la forma interrogativa se debe a que la figura de Saori es demasiado... ya sabes.",
    39: "¿Qué es eso, un cascarón vacío? ¿Estás tratando de dar una impresión de una persona sin alma?",
    40: "Los cascarones vacíos de las cigarras están más rellenos hoy en día, ¿sabes?",
    41: "Caminando tambaleante por la acera, parecía como si Saori fuera a ser derribada hacia la calzada por el hombre corpulento que apareció frente a ella.",
    42: "Esto no es solo malo; esto es realmente malo.",
}
a0060_s = {
    4: ("¡¿Quieres que te compre un juego nuevo?!", "Kyousuke"),
    5: ("Sí. No tienes nada mejor que hacer, ¿verdad?", "Kirino"),
    6: ("De todos modos, no haces nada más que respirar oxígeno y exhalar dióxido de carbono.", "Kirino"),
    7: ("Al menos sé de alguna utilidad para mí.", "Kirino"),
    9: ("Se supone que debería estar preparándome para los exámenes de ingreso, ¿sabes?", "Kyousuke"),
    10: ("Huuuh...", "Kirino"),
    11: ("¿Y entonces? ¿Cómo se relaciona eso con mi vida?", "Kirino"),
    12: ("Solo pensé en tomar un respiro e ir a Akiba por un rato.", "Kirino"),
    13: ("Si ese es el caso, ve por ti misma.", "Kyousuke"),
    14: ("De ninguna manera.", "Kirino"),
    15: ("Hace tanto calor, y realmente no quiero ir a un área popular con mucha gente.", "Kirino"),
    21: ("¿Puedo decir algo, Kirino?", "Kyousuke"),
    22: ("No soy tu chófer, ni tu hombre de mantenimiento. Soy tu---", "Kyousuke"),
    23: ("¿No vas a ir?", "Kirino"),
    24: ("¡¡Me encantaría ir!!", "Kyousuke"),
    26: ("Me pregunto si esto también es un efecto de la pulsera de Kuroneko...", "Kyousuke"),
    27: ("¿Pasará algo incluso peor después, o recibiremos una visita de la Dama Fortuna...?", "Kyousuke"),
    28: ("Lo que sea que pase, tengo que apurarme y conseguir lo que está buscando, y luego puedo refrescarme en una linda sala con aire acondicionado...", "Kyousuke"),
    35: ("Espera, ¿una chica con lentes giratorios?", "Kyousuke"),
    36: ("*suspiro*......", "Saori"),
    37: ("¿Eres tú, Saori?", "Kyousuke"),
    43: ("¡Saori! ¡Oye, Saori!", "Kyousuke"),
}

a0063_n = {
    0: "Ruta de Saori · Aventurándome En Akiba Una Vez Más",
    5: "En este momento, no puedo dejar a Saori así.",
    6: "Tengo que hacer que se calme y me escuche.",
}
a0063_s = {
    1: ("Ah, ah, ah...", "Saori"),
    2: ("¿Qué pasa? ¿Cómo fue el plan?", "Kyousuke"),
    3: ("aouaouaouaou!", "Saori"),
    4: ("¡No entiendo lo que dices!", "Kyousuke"),
    7: ("Escucha, ¿está bien? En este momento, necesitas enfriarte.", "Kyousuke"),
    8: ("En momentos así, respiras-", "Kyousuke"),
    9: ("*inhala*", "Saori"),
    10: ("Inhala.", "Kyousuke"),
    11: ("*inhala*", "Saori"),
    12: ("¡Inhala, inhala, inhala!", "Kyousuke"),
    13: ("*inhala*", "Saori"),
    14: ("¡¡¡Inhala!!!", "Kyousuke"),
    15: ("*inhala*, *tose* *tose* *tose*", "Saori"),
    16: ("¿A-Estás tratando de matarme!?", "Saori"),
    17: ("Pero oye, te calmó, ¿verdad?", "Kyousuke"),
    18: ("¿Ah...?", "Saori"),
    19: ("......", "Saori"),
    20: ("aouaouaouaouaou!", "Saori"),
    21: ("¡No vuelvas a eso!", "Kyousuke"),
    22: ("aouaouaouaou...!", "Saori"),
    23: ("¡Ya basta! ¡Si sigues así, te dejaré aquí en Akihabara!", "Kyousuke"),
    24: ("...No necesitas estar involucrado en esto.", "Kyousuke"),
    25: ("Kyousuke-shi...", "Saori"),
    26: ("Por favor. Estoy preocupado por ti.", "Kyousuke"),
    27: ("¿Podrías contarme qué pasó?", "Kyousuke"),
    28: ("Uuhg...", "Saori"),
    29: ("Ky-Kyousuke-shi...Y-Yo...", "Saori"),
    30: ("Sí. ¿Qué es?", "Kyousuke"),
    31: ("¡E-Es hora de pagar las consecuencias!", "Saori"),
    32: ("¿¡Qué pasó!? ¡Dilo! ¡Puedo ayudarte!", "Kyousuke"),
    33: ("¿Pagar las consecuencias? ¿Todavía hablas raro?", "Kyousuke"),
    34: ("U-uhg...Kyousuke-shi...", "Saori"),
    35: ("Kyousuke-shi, eres el único que se ha preocupado tanto por mí...", "Saori"),
    36: ("U-Uhg...", "Saori"),
    37: ("¿Qué dijiste...?", "Kyousuke"),
    38: ("Y-Yo...!", "Saori"),
    39: ("¿¡Saori!? ¡Te lo ruego, cálmate!", "Kyousuke"),
    40: ("U-Ugh...", "Saori"),
    41: ("Kyousuke-shi, y-yo...", "Saori"),
    42: ("Finalmente tengo que pagar las consecuencias.", "Saori"),
    43: ("Bueno, deberías pagar las consecuencias.", "Kyousuke"),
    44: ("Kyousuke-shi... Ahora es un buen momento para intervenir...", "Saori"),
    45: ("Jeje... Parece que el sueño de que bajemos juntos por la alfombra roja no va a suceder, después de todo...", "Saori"),
    46: ("Saori, mira la realidad. Nunca tuve ese sueño.", "Kyousuke"),
    47: ("La realidad...", "Saori"),
    48: ("La realidad que se supone que debería ver... La cruel, severa realidad...", "Saori"),
}

data = {
    "000scriptDSAO_0053T.obj": build(a0053_n, a0053_s),
    "000scriptDSAO_0055A.obj": build(a0055_n, a0055_s),
    "000scriptDSAO_0058T.obj": build(a0058_n, a0058_s),
    "000scriptDSAO_0060A.obj": build(a0060_n, a0060_s),
    "000scriptDSAO_0063T.obj": build(a0063_n, a0063_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
