import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0037_n = {
    0: "Ruta de Saori · Angustia Por Un Problema Difícil",
    2: "No puedo soportar la expresión preocupada en su rostro.",
    3: "Podría decir algo, pero no tengo nada bueno en mente...",
    4: "Bueno entonces, ¿qué debería hacer...",
    6: "Saori... se ve bastante preocupada, pero bueno, eso era de esperarse...",
    7: "Para Saori, tanto sus hobbies como sus padres son importantes sin medida.",
    8: "Por eso no puede aceptar la idea de tirar uno por el resto de su vida.",
    9: "Entiendo los sentimientos de Saori cuando dice que lo hace por sus padres.",
    10: "¡Pero no creo que sea del interés de Saori doblegarse ante lo que sus padres quieren!",
    11: "En momentos así, ¿qué debería decirle?",
    12: "No hay caso, nada me viene a la mente...",
    18: "E-Esto es patético...",
    19: "Quería animarla, pero en lugar de eso solo la hice preocuparse; qué patético...",
    46: "¡Anime, juegos, figuras y manga!",
    47: "¿Por qué no pensé en algo tan simple!",
}
a0037_s = {
    1: ("Pero, ¿qué puedo hacer que sea más concreto... No puedo pensar en nada.", "Saori"),
    5: ("Hmm...", "Saori"),
    13: ("¿Kyousuke-shi? ¿Pasa algo?", "Saori"),
    14: ("Has estado un poco pálido por un rato...", "Saori"),
    15: ("Quizás...", "Saori"),
    16: ("¿El calor del verano te afectó, y tus patrones de pensamiento están a punto de explotar?", "Saori"),
    17: ("N-No... Nada de eso...", "Kyousuke"),
    20: ("¡Tener que escuchar todo esto de repente debe ser bastante confuso!", "Saori"),
    21: ("¿Qué tal si lo dejamos así por hoy y hablamos mañana?", "Saori"),
    22: ("No me importa particularmente, pero...", "Kyousuke"),
    23: ("¿Estás realmente bien con eso?", "Kyousuke"),
    24: ("Estoy bien, ¡no te preocupes!", "Saori"),
    25: ("El solo poder hablar contigo así me quitó un peso de encima, y resultó divertido.", "Saori"),
    26: ("¡Estoy profundamente agradecida contigo!", "Saori"),
    27: ("Ya veo. Me alegra escuchar eso.", "Kyousuke"),
    28: ("Bueno entonces, ¡si algo pasa de nuevo, contáctame!", "Kyousuke"),
    29: ("¡Entendido!", "Saori"),
    30: ("¡No cargues con todo tú sola, de acuerdo?!", "Kyousuke"),
    31: ("¡Reconocido!", "Saori"),
    32: ("Si te rindes ahora, significa que estás renunciando a las cosas que has apreciado.", "Kyousuke"),
    33: ("Cosas que aprecio...", "Saori"),
    34: ("Sí. Cosas que has apreciado hasta ahora.", "Kyousuke"),
    35: ("Por supuesto. Tal como dijiste, estos son mis tesoros.", "Saori"),
    36: ("Esos tesoros... figuras, juegos, anime y manga...", "Kyousuke"),
    37: ("¿Es algo que puedes dejar fácilmente? Son tesoros porque no pueden ser reemplazados, ¿verdad?", "Kyousuke"),
    38: ("Si renuncias a tus hobbies otaku ahora...", "Kyousuke"),
    39: ("Será como dijiste, nunca podré darte ese recuerdo.", "Kyousuke"),
    40: ("Tendrías que pasar el resto de tu vida sin tocar manga, figuras, anime o juegos, ¿sabes?", "Kyousuke"),
    41: ("¿Podrás soportar una vida tan aburrida y monótona?", "Kyousuke"),
    42: ("............", "Kyousuke"),
    43: ("¿Qué pasa?", "Saori"),
    44: ("...Espera, ¡¡lo recuerdo!!!!", "Kyousuke"),
    45: ("¿K-Kyousuke-shi?", "Saori"),
}

a0038_n = {
    0: "Ruta de Saori · Angustia Por Un Problema Difícil",
    24: "Yo... no puedo refutar eso...",
    33: "...Sí, ser etiquetado como un hermano pervertido que engañó a su hermana, ese incidente abominable.",
    34: "Para ser precisos, ella aún no lo ha aceptado completamente, así que no puedo confiarme demasiado...",
    62: "Kirino tenía dos lados. Eso es porque sus amigas de un lado odiaban a los otakus.",
}
a0038_s = {
    1: ("Solo hazle saber que los otakus son inofensivos.", "Kyousuke"),
    2: ("¿Los otakus son inofensivos...?", "Saori"),
    3: ("Sí. Exactamente.", "Kyousuke"),
    4: ("Que los otakus no son una mala influencia...", "Kyousuke"),
    5: ("Si él entiende eso, entonces tu prometido no te dirá cosas como «Deja de ser otaku», ¿verdad?", "Kyousuke"),
    6: ("Eso puede ser cierto pero...", "Saori"),
    7: ("Sin embargo, no es tan fácil de resolver.", "Saori"),
    8: ("Oye, ¿por qué eres tan pesimista?", "Kyousuke"),
    9: ("¿Me preguntas eso?", "Saori"),
    10: ("¿H-Hay algo malo?", "Kyousuke"),
    11: ("...Kyousuke-shi, tú sabes cómo es esto.", "Saori"),
    12: ("Es verdad que no es tan fácil de resolver.", "Kyousuke"),
    13: ("Como era de esperarse de Kyousuke-shi. Entiendes bien la situación.", "Saori"),
    14: ("Por supuesto. Todavía hay cosas que incluso yo no comprendo del todo.", "Kyousuke"),
    15: ("Incluso después de hablar con ellos, algunos podrían entender mientras que otros no. Esa es la profundidad de un otaku.", "Saori"),
    16: ("Afirmo que soy una otaku.", "Saori"),
    17: ("Sin embargo, hay personas en este mundo que piensan que la subcultura del anime y el manga es una mala influencia.", "Saori"),
    18: ("Eso puede ser cierto.", "Kyousuke"),
    19: ("Pero, eso no es una razón para cambiar tu forma de vivir.", "Kyousuke"),
    20: ("¡Oh...! Eso es...", "Saori"),
    21: ("¿Qué tiene de malo decir que te gusta si eso es lo que te gusta? ¿Hay necesidad de sentir vergüenza por ello?", "Kyousuke"),
    22: ("Está bien decirlo en voz alta. Si cedes ante ellos, parecerás deprimida.", "Kyousuke"),
    23: ("No entiendo tu explicación... Hm...", "Saori"),
    25: ("¿Puedes entender eso, Kyousuke-shi?", "Saori"),
    26: ("Incluso Kyousuke-shi tuvo algunos problemas aceptando nuestra cultura al principio.", "Saori"),
    27: ("No estoy negando eso... pero...", "Kyousuke"),
    28: ("No te rindas. No te preocupes... Tengo un plan secreto.", "Kyousuke"),
    29: ("¿Plan secreto?", "Saori"),
    30: ("Sí. En realidad, esta no es la primera vez que intento que una persona normal entienda a los otakus.", "Kyousuke"),
    31: ("...¿Por ejemplo?", "Saori"),
    32: ("Una chica de secundaria que es modelo activa y a quien convencí... ¡Ayase!", "Kyousuke"),
    35: ("Una chica de secundaria... hm, eso sí suena a un hueso duro de roer.", "Saori"),
    36: ("Sin embargo, tu oponente esta vez es un hombre adulto, ¿verdad?", "Saori"),
    37: ("¿Y qué si es un adulto? ¡¿Y qué si es un hombre?!", "Kyousuke"),
    38: ("No solo a Ayase, ¡incluso logré convencer a mi terco padre de que aceptara el hobby otaku de Kirino!", "Kyousuke"),
    39: ("¿No es eso también... debido al esfuerzo implacable de Kirino todo este tiempo?", "Saori"),
    40: ("Esto es solo mi conjetura...", "Saori"),
    41: ("...Bueno, es verdad que fueron los esfuerzos de Kirino los que hicieron que nuestro padre entendiera su hobby otaku.", "Kyousuke"),
    42: ("Los adultos son diferentes de los niños; tienen pensamientos independientes y amor propio.", "Saori"),
    43: ("Con mucha experiencia de vida, uno no puede aceptar fácilmente nuevas ideas.", "Saori"),
    44: ("Entonces, ¿qué significa cuando no pueden aceptar a los otakus...?", "Kyousuke"),
    45: ("...No lo sé. Pero...", "Saori"),
    46: ("Pienso que una persona inteligente tendrá una actitud más cautelosa hacia las cosas nuevas.", "Saori"),
    47: ("...¿Entonces estás diciendo que enfrentar a una chica de secundaria es un nivel diferente?", "Kyousuke"),
    48: ("Así es.", "Saori"),
    49: ("¿Y qué?", "Kyousuke"),
    50: ("Más bien, un adulto maduro que tiene experiencia de vida podría entender mejor los intereses del otro, ¿verdad?", "Kyousuke"),
    51: ("¿Porque un adulto podría entender mejor...?", "Saori"),
    52: ("Es verdad que comparada con un hombre adulto, una chica de secundaria es como una pista de esquí plateada que nadie ha pisado.", "Kyousuke"),
    53: ("Probablemente sea el mejor momento para plantar ideas en ellos enseñándoles desde el principio.", "Kyousuke"),
    54: ("Pero, en un terreno donde muchas personas ya han patinado, ¿no sería más fácil que las plantas echen raíces!?", "Kyousuke"),
    55: ("¿¡Ah?! Ahora que lo pones así...", "Saori"),
    56: ("Además, mi terco padre solía decir que el hobby otaku de Kirino era malo y quería que lo dejara pero...", "Kyousuke"),
    57: ("Finalmente lo reconoció al final. Por eso dije que los adultos entenderán si hablas con ellos.", "Kyousuke"),
    58: ("Una estudiante de secundaria es después de todo una estudiante de secundaria. Él o ella puede cambiar fácilmente de opinión, ¿verdad?", "Saori"),
    59: ("Por ejemplo, incluso sus intenciones pueden verse fácilmente afectadas por la influencia de sus amigos, familia y alrededores.", "Saori"),
    60: ("¿No fue por el bien de su amiga cercana que la amiga de Kiririn-shi se cambió a sí misma?", "Saori"),
    61: ("Oh... Es cierto...", "Kyousuke"),
    63: ("Por eso, usar una lógica tan torpe contra adultos es...", "Saori"),
    64: ("Para ser franca, una batalla perdida... Jajaja.", "Saori"),
    65: ("¡No decidas que perdiste antes de siquiera empezar! ¿Quién te crees que eres? ¡¿Mi hermana?!", "Kyousuke"),
    66: ("¿Kyo-Kyousuke-shi...?", "Saori"),
    67: ("No decidas como si ya conocieras tu futuro.", "Kyousuke"),
    68: ("¡Ya que es tu futuro, deberías pavimentar tu propio camino!", "Kyousuke"),
    69: ("...Eso puede ser cierto...", "Saori"),
    70: ("Antes de que comience la batalla, el resultado ya se puede ver.", "Saori"),
    71: ("¡Espera! Al menos escucha lo que tengo que decir. ¿De acuerdo? ¡Justo así!", "Kyousuke"),
    72: ("N-No, no me convencerás tan fácilmente.", "Saori"),
    73: ("¿Por qué? En serio, hoy estás muy sin ánimo.", "Kyousuke"),
    74: ("No es un problema de capricho.", "Saori"),
    75: ("Es muy arriesgado hacer que una persona normal entienda a los otakus.", "Saori"),
    76: ("Además, me gustaría evitar causar problemas a mi pareja y a mis padres por decir algo extraño.", "Saori"),
    77: ("Causar problemas...", "Kyousuke"),
    78: ("De todos modos, déjame pasar esta batalla perdida... Jajaja.", "Saori"),
    79: ("¡Incluso si es una batalla perdida, hay mérito en intentarlo!", "Kyousuke"),
    80: ("Ningún general envía tropas a una batalla perdida.", "Saori"),
    81: ("Por favor entiende, Kyousuke-shi. ¡Hay una diferencia entre irrazonable e imprudente!", "Saori"),
    82: ("Es mejor si estoy sola, no quiero causar problemas a los demás.", "Saori"),
    83: ("En ese caso, al menos escucha lo que tengo que decir y dime qué te parece.", "Kyousuke"),
    84: ("Voy a contarte sobre una chica de secundaria. Sobre Ayase.", "Kyousuke"),
}

a0039_n = {
    0: "Ruta de Saori · Historia De Éxito",
    3: "Guh...",
    4: "¿Puedo decir algo que pueda recuperarme de esto?",
    13: "Si se trata de mi Amada Angel Ayase, déjamelo a mí.",
    14: "...Así que, expliqué apropiadamente lo que sucedía entre Kirino y Ayase.",
    15: "Básicamente, el incidente donde Ayase se enteró de que Kirino era otaku.",
    16: "Y que Ayase quería cortar contacto con Kirino.",
    17: "Ayase, a diferencia de Kirino, era una chica de secundaria normal.",
    18: "Probablemente no puede ver a los otakus que lujurian por figuras de chicas y se sumergen en anime de niñas pequeñas como otra cosa que repugnantes.",
    19: "Además, el asco de Ayase por los otakus está a un nivel incomparablemente alto.",
    20: "Esto es comprensible, ya que su madre trabaja como líder de la PTA, que lanza regularmente reuniones para discutir regulaciones contra los juegos y el anime.",
    21: "Recibiendo la ráfaga completa de comentaristas de TV y periodistas tercos culpando a los otakus, no es de extrañar que Ayase no tenga una simple opinión.",
    22: "El asco de Ayase se alimenta especialmente por el evento conocido como el «Incidente Siscaly».",
    23: "En ese evento, un hombre electrocutó a una mujer hasta la muerte en un intento de imitar a Siscaly después de ser influenciado por ello.",
    24: "Sin embargo, la verdad era que los medios estaban usando el incidente para echarle la culpa a los otakus.",
    25: "Por supuesto, no quiero decir que los otakus sean completamente inocentes.",
    26: "Sin embargo, el argumento de que los otakus son una influencia negativa en la sociedad no es necesariamente correcto.",
    35: "Yo también siento que solo estoy animando a ciegas.",
    36: "Sin embargo, es suficiente con que Saori esté sonriendo de nuevo.",
}
a0039_s = {
    1: ("...No es que no entienda lo que dices, pero...", "Saori"),
    2: ("Puede ser grosero, pero tu discurso carece de poder de persuasión.", "Saori"),
    5: ("Ah... Hm... Em...", "Kyousuke"),
    6: ("Bueno, de todos modos...", "Saori"),
    7: ("Sé que lo que dije fue incoherente.", "Kyousuke"),
    8: ("Pero, me gustaría que escuches. Si hay incluso una pequeña posibilidad, todavía querría intentarlo.", "Kyousuke"),
    9: ("Kyousuke-shi...", "Saori"),
    10: ("...Si ese es el caso, Kyousuke-shi.", "Saori"),
    11: ("Por favor, explica más sobre la amiga de Kiririn-shi, Ayase-shi.", "Saori"),
    12: ("...Está bien.", "Kyousuke"),
    27: ("Al explicar el malentendido, después de algunos giros y vueltas, la amistad de Ayase con Kirino volvió a la normalidad.", "Kyousuke"),
    28: ("Ya veo, ya veo...", "Saori"),
    29: ("Por eso podrías simplemente explicarle las cosas a tu prometido.", "Kyousuke"),
    30: ("Si lo pones así...", "Saori"),
    31: ("¡De algún modo siento confianza en que puedo persuadirlo!", "Saori"),
    32: ("¡Así es! ¡Tú puedes! ¡Si piensas que puedes hacerlo, puedes!!", "Kyousuke"),
    33: ("¡Adelante, adelante! ¡Si es tú, entonces puedes hacerlo! ¡Así que hazlo! ¡Nunca te rindas!!", "Kyousuke"),
    34: ("Kyousuke-shi, eres como una parodia del video MAD del Hada del Fuego.", "Saori"),
    37: ("Es tal como dices.", "Saori"),
    38: ("Si te rindes antes de empezar, entonces nunca conseguirás lo que quieres.", "Saori"),
    39: ("Sip, ¡ese es el espíritu!", "Kyousuke"),
    40: ("En realidad, se supone que me reuniré con él mañana...", "Saori"),
    41: ("Pienso que hablaré apropiadamente de ello entonces.", "Saori"),
}

a0040_n = {
    0: "Ruta de Saori · Interrogado Por Kuroneko",
    1: "...El día siguiente.",
    2: "Fui a la escuela durante las vacaciones de verano para pasarle a Kuroneko la información que obtuve de Saori.",
    14: "¡¿Eres una grabadora?!",
    17: "No es que... no pueda decírselo. Pero contarle aquí sobre la entrevista de matrimonio, es...",
    18: "Saori no quería que le contara a nadie sobre su hospitalización. Probablemente tampoco quiere que nadie sepa sobre su entrevista de matrimonio...",
    19: "Saori no quiere que Kirino o Kuroneko se preocupen, lo cual puedo entender.",
    27: "Una persona normal diría «te daré llamadas perdidas todas las noches» en su lugar.",
    44: "...¿Podría ser que acabo de pisar una mina terrestre?",
    45: "La mirada de Kuroneko me transmitió un sentimiento feroz como si dijera «Un secreto entre solo ustedes dos, qué descarado...»",
    46: "No sé si es solo una ilusión, pero siento la presencia de un demonio detrás de Kuroneko.",
    54: "...Es como si Kuroneko pudiera ver a través de mi corazón.",
    55: "¿O es esto el llamado «intuición femenina»?",
    56: "De todos modos, es bueno que haya entendido la situación.",
    58: "Asentí sin dudar. No quería despertar sospechas.",
    68: "¿Qué Ángel Caído... El diseño parece que tiene una maldición en su lugar...",
    79: "Más bien, prueba del efecto contrario.",
    87: "Puede que diga eso, pero se rió malvadamente.",
    88: "Bueno, esto es lo usual en ella, que sus acciones y pensamientos no estén alineados.",
    89: "Dice eso, pero en realidad está preocupada por Saori.",
    90: "Incluso mientras me pasaba la pulsera, su hombro temblaba torpemente.",
    101: "...¿Podría ser.",
    102: "¿Es su forma de agradecerme por conseguirle la información?",
    103: "En realidad no hay necesidad de eso; Kuroneko es muy considerada.",
}
a0040_s = {
    3: ("Aquí, las cosas que querías.", "Kyousuke"),
    4: ("...Ciertamente. La tomaré.", "Kuroneko"),
    5: ("...Así que.", "Kuroneko"),
    6: ("Mientras me usas como excusa, ¿para qué querías encontrarte con Saori?", "Kuroneko"),
    7: ("¡Pfft!!", "Kyousuke"),
    8: ("¿U-Usándote como excusa?", "Kyousuke"),
    9: ("Por favor, no te hagas el tonto.", "Kuroneko"),
    10: ("Me lo dijiste, ¿verdad?", "Kuroneko"),
    11: ("Dijiste «tenía algo que preguntarle a Saori»...", "Kuroneko"),
    12: ("¿Es, es así...?", "Kyousuke"),
    13: ("Sí. El discurso y los movimientos del senpai están cuidadosamente registrados en mi consciencia profunda, así que no puede haber errores.", "Kuroneko"),
    15: ("Saori es nuestra amiga mutua. No debería haber ningún problema en dejarme saber cosas sobre ella, ¿verdad?", "Kuroneko"),
    16: ("¿O podría ser que es algo que no se me puede decir a mí?", "Kuroneko"),
    20: ("Vamos, confiesa ya.", "Kuroneko"),
    21: ("No hay nada que confesar; realmente no es importante...", "Kyousuke"),
    22: ("Si no es importante, entonces debería estar bien decirlo.", "Kuroneko"),
    23: ("Eso es...", "Kyousuke"),
    24: ("No es bueno para tu cuerpo mantenerlo embotellado.", "Kuroneko"),
    25: ("...Veamos. Por ejemplo...", "Kuroneko"),
    26: ("Podría pedir prestado el poder de los Moradores de las Tinieblas, y enviarte maldiciones noche tras noche...", "Kuroneko"),
    28: ("Como dije, realmente no es nada importante.", "Kyousuke"),
    29: ("Quién sabe. Si eres tan terco, me pondré más sospechosa.", "Kuroneko"),
    30: ("Pero, aunque perdió la conciencia, solo se quedó en el hospital unos días antes de que la dieran de alta.", "Kyousuke"),
    31: ("...¿Perdió la conciencia?", "Kuroneko"),
    32: ("¿Qué quieres decir con perdió la conciencia?", "Kuroneko"),
    33: ("Eh...", "Kyousuke"),
    34: ("Bueno, ya ves...", "Kyousuke"),
    35: ("¡Oh sí! ¡Dije «PERDISTE»! Ya sabes, ¡como en los juegos de pelea!", "Kyousuke"),
    36: ("Fue hospitalizada, ¿verdad?", "Kuroneko"),
    37: ("¡Ooh?! ¡Si-Si te acercas tanto...", "Kyousuke"),
    38: ("¿Si me acerco tanto? ¿Qué estás diciendo?", "Kuroneko"),
    39: ("Si eso es un problema, entonces confiesa rápido.", "Kuroneko"),
    40: ("¡E-Eso es! ¡Saori fue hospitalizada!", "Kyousuke"),
    41: ("Pero la dieron de alta después de unos días; ¡no hay nada particularmente malo!", "Kyousuke"),
    42: ("Ya veo...", "Kuroneko"),
    43: ("Te lo dijo a ti mientras me mantenía a mí en la oscuridad.", "Kuroneko"),
    47: ("En realidad, es bastante complicado.", "Kyousuke"),
    48: ("¿Cómo decirlo... Es un poco difícil de decir...", "Kyousuke"),
    49: ("...¿Por qué estás tan nervioso?", "Kuroneko"),
    50: ("No es como si sospechara de la relación entre ustedes dos.", "Kuroneko"),
    51: ("Saori probablemente te dijo:", "Kuroneko"),
    52: ("«Por favor, mantén esto en secreto de Kiririn-shi y Kuroneko-shi»", "Kuroneko"),
    53: ("y estabas teniendo eso en mente, ¿verdad?", "Kuroneko"),
    57: ("...Lo tengo. Confesaré.", "Kyousuke"),
    59: ("Hmph, como era de esperarse...", "Kuroneko"),
    60: ("Admito la derrota ante tu ojo observador.", "Kyousuke"),
    61: ("¿No es obvio? Ese es el poder que solo se les da a los elegidos.", "Kuroneko"),
    62: ("Sí sí, justo así.", "Kyousuke"),
    63: ("Dejando eso de lado, tengo que devolver el favor por la información de Saori.", "Kuroneko"),
    64: ("Si te encuentras con ella, ¿podrías pasarle esta 【pulsera】?", "Kuroneko"),
    65: ("¿Qué pasa con esta pulsera ominosa...", "Kyousuke"),
    66: ("Es un amuleto. Pero, no es solo un amuleto simple.", "Kuroneko"),
    67: ("Es un amuleto con la bendición del Ángel Caído.", "Kuroneko"),
    69: ("A propósito, ¿siempre cargas con este tipo de cosas?", "Kyousuke"),
    70: ("No.", "Kuroneko"),
    71: ("Obtuve el amuleto de la suerte, pero está en una longitud de onda conflictiva conmigo.", "Kuroneko"),
    72: ("¿Qué quieres decir?", "Kyousuke"),
    73: ("Me mareo cuando lo uso, y los cuervos vuelan sobre mí...", "Kuroneko"),
    74: ("Al final, cuando se me rompió la agujeta del zapato y estaba preocupada por eso, tu hermana estaba como...", "Kuroneko"),
    75: ("«¿Eres tan pobre que no puedes conseguir una agujeta adecuada? Qué triste lolololol»", "Kuroneko"),
    76: ("Y así fue como se burló de mí.", "Kuroneko"),
    77: ("¡¿Entonces no es una pulsera maldita?!", "Kyousuke"),
    78: ("...Esto es prueba de su efectividad.", "Kuroneko"),
    80: ("Desafortunadamente, no es de la misma longitud de onda que yo.", "Kuroneko"),
    81: ("¿Entonces se desperdicia incluso si tiene algún efecto?", "Kyousuke"),
    82: ("...Pero, si un humano que es diferente a mí la toma, podrían ser capaces de conquistarla.", "Kuroneko"),
    83: ("Por eso quiero pasársela; para ver si ella puede hacerlo.", "Kuroneko"),
    84: ("Tú...", "Kyousuke"),
    85: ("solo quieres experimentar con Saori.", "Kyousuke"),
    86: ("¿Oh? Eso no es cierto... Ufufu...", "Kuroneko"),
    91: ("Bueno entonces, estoy ocupada aquí...", "Kuroneko"),
    92: ("Si te encuentras con ella, por favor pásasela.", "Kuroneko"),
    93: ("Oye, ¡espera!", "Kyousuke"),
    94: ("...¿Qué es?", "Kuroneko"),
    95: ("¿Puedo hacer una pregunta?", "Kyousuke"),
    96: ("Si no es de la misma longitud de onda, entonces ¿por qué la estabas guardando?", "Kyousuke"),
    97: ("...¿No es obvio?", "Kuroneko"),
    98: ("Estaba pensando en dártela a ti.", "Kuroneko"),
    99: ("...¿A mí? ¿Por qué?", "Kyousuke"),
    100: ("...Por favor, piénsalo tú mismo.", "Kuroneko"),
}

a0045_n = {
    0: "Ruta de Saori · Informe De Ejecución Del Plan",
    1: "Me quedé en casa hoy, dejando pasar el tiempo mientras abría y cerraba mis libros de referencia.",
    2: "...En ese punto, Saori me llamó y me pidió salir.",
    5: "Ha pasado un tiempo desde la última vez que la vi...",
    6: "Pero se ve extremadamente agotada...",
    8: "En ese momento, algunas personas pasaron a nuestro lado y dijeron...",
    11: "...Podíamos escuchar ese tipo de cosas diciéndose.",
    12: "Para Saori, que fue a una entrevista de matrimonio irrazonable, y empujada a un compromiso, esto era lo último que quería escuchar.",
    13: "Saori parecía haber escuchado la conversación anterior, y tenía una mirada deprimida en su rostro.",
    33: "Oh cierto, hay algo de Kuroneko.",
    34: "Parece que esto va a tomar algo de tiempo, ¿quizás debería entregar esto primero?",
    35: "Pero, si lo entrego ahora, rompería el flujo de la conversación...",
    36: "Y esta cosa, es excesivamente ominosa.",
    37: "Y por lo que dijo Kuroneko, no da una buena impresión.",
    38: "El diseño se siente un poco maldito; supongo que puede esperar.",
    41: "De todos modos, se la devolveré a Kuroneko. Sí, eso está bien.",
    42: "Metí la pulsera que saqué en la parte trasera de mi bolsillo trasero, y reanudé la conversación.",
    45: "Aunque es una pulsera de muy mal gusto...",
    49: "Uhh, la mirada resentida de Saori perforó mi corazón...",
    53: "Saori no pudo evitar encogerse de hombros, y tomó la pulsera de cráneo de cristal de mí.",
    60: "Riendo alegremente, Saori se puso la pulsera en el brazo.",
    68: "Mirando la espalda de Saori mientras se iba, tuve un inexplicable sentimiento de inquietud...",
    69: "En este instante, de algún modo tuve el presentimiento de que el deseo de Saori nunca se haría realidad.",
    70: "¿Podría ser esta una premonición misteriosa?",
    71: "Aunque no tengo sexto sentido...",
    72: "De todos modos, no debería haberle dado esa pulsera a Saori.",
    93: "Tomé la pulsera de Saori, y la puse en mi bolsillo trasero.",
    94: "Después de eso, Saori juntó sus manos, y bajó ligeramente la cabeza.",
    104: "Mientras Saori seguía hablando, se veía tan agotada que dolía mi corazón.",
    105: "La grande, alta, con estilo otaku, lentes giratorios Saori.",
    106: "Sin embargo, es una chica normal de preparatoria por dentro. Solo una chica frágil.",
    107: "Sobre el matrimonio, dejando el pasado de lado, se considera demasiado temprano para Japón en los tiempos actuales.",
    108: "Podría seguir siendo cierto para el «mundo refinado» en el que vive Saori, pero he estado ignorando eso.",
    109: "...Pero eso está mal. Saori está perdida por eso. Está preocupada por eso.",
    110: "Es un matrimonio, ¿no? ¿Saltando por encima de la relación de novios, hacia compañeros de vida?",
    111: "¡No es un problema que una chica de 16-17 años pueda resolver por sí sola!",
}
a0045_s = {
    3: ("Lo siento, ¿te hice esperar?", "Kyousuke"),
    4: ("No, yo también acabo de llegar.", "Saori"),
    7: ("Ya veo. Entonces está bien.", "Kyousuke"),
    9: ("No importa cuán buenos sean los términos, 【si la compatibilidad es mala, es imposible】 para una relación continuar.", "Passerby A"),
    10: ("Ellos normiefags. De todos modos, no hay nadie con quien pueda salir lol.", "Passerby B"),
    14: ("¡Kyo-Kyousuke-shi!", "Saori"),
    15: ("Si seguimos esperando aquí, estaremos molestando a las maid que están distribuyendo pañuelos.", "Saori"),
    16: ("Por lo tanto, ¿qué tal pasar el resto de nuestro tiempo en el maid café de siempre?", "Saori"),
    17: ("Entonces... ¿cómo estuvo?", "Kyousuke"),
    18: ("...No funcionó.", "Saori"),
    19: ("Argh...", "Kyousuke"),
    20: ("Repetiré sus palabras tal como las dijo...", "Saori"),
    21: ("«Entiendo lo que dices. Ser otaku no es malo.»", "Saori"),
    22: ("«Sin embargo, tampoco es una virtud.»", "Saori"),
    23: ("«No odio a los otakus. Entiendo que hay algunos puntos buenos sobre el anime y los juegos.»", "Saori"),
    24: ("«Sin embargo, es un hecho que mucha gente se ha sumergido demasiado profundo y se ha perdido a sí misma en el anime y los juegos.»", "Saori"),
    25: ("«No quiero que pierdas tu yo original.»", "Saori"),
    26: ("...esto es lo que dijo.", "Saori"),
    27: ("Hmm, es una opinión muy apropiada.", "Kyousuke"),
    28: ("Sí. Muy apropiada.", "Saori"),
    29: ("Sin embargo, mi yo original proviene de los hobbies otaku.", "Saori"),
    30: ("Por eso, que rechacen mis hobbies otaku se siente como que me rechacen a mí misma...", "Saori"),
    31: ("¿Entonces no sabes cómo lidiar con tu prometido?", "Kyousuke"),
    32: ("Es vergonzoso, pero es tal como dijiste.", "Saori"),
    39: ("¿Pasa algo, Kyousuke-shi?", "Saori"),
    40: ("...Nah, no es nada.", "Kyousuke"),
    43: ("En realidad, hay algo que Kuroneko me pidió que te pasara, pero...", "Kyousuke"),
    44: ("¿Podrías aceptarlo?", "Kyousuke"),
    46: ("¿Por qué Kuroneko-shi quiere darme esto?", "Saori"),
    47: ("Lo siento... Le conté a Kuroneko sobre tu hospitalización.", "Kyousuke"),
    48: ("...Ya veo.", "Saori"),
    50: ("Pero...", "Saori"),
    51: ("......?", "Kyousuke"),
    52: ("Estoy agradecida por la preocupación de Kuroneko-shi.", "Saori"),
    54: ("Fu fu... esto es...", "Saori"),
    55: ("Este diseño es como la encarnación del hobby de Kuroneko.", "Saori"),
    56: ("Pienso lo mismo.", "Kyousuke"),
    57: ("Sin embargo, he escuchado que los amuletos que están deliberadamente modelados para ser ominosos aún pueden ahuyentar el mal.", "Saori"),
    58: ("¿Es así?", "Kyousuke"),
    59: ("Pero si esto aplica a esta cosa, no puedo decirlo.", "Saori"),
    61: ("También te doy las gracias.", "Saori"),
    62: ("Sí, no es nada.", "Kyousuke"),
    63: ("Aparte de eso, vayamos al punto principal.", "Kyousuke"),
    64: ("¡Sí señor, señor!", "Saori"),
    65: ("Bueno entonces, Kyousuke-shi.", "Saori"),
    66: ("¡Hasta la próxima!", "Saori"),
    67: ("S-Sí.", "Kyousuke"),
    73: ("L-Lo siento, ¡Saori! ¿Podrías devolverme esa pulsera, después de todo?", "Kyousuke"),
    74: ("¿Eh? ¿Por qué?", "Saori"),
    75: ("En realidad, parece que esta pulsera estaba destinada para mí.", "Kyousuke"),
    76: ("¿Para ti?", "Saori"),
    77: ("Sip. Si te la pones, ocurrirán muchas cosas malas.", "Kyousuke"),
    78: ("Según Kuroneko, aunque esta pulsera no encajaba con su longitud de onda, sí tiene un efecto.", "Kyousuke"),
    79: ("Dijo que Saori podría ser capaz de hacer algo con ella, así que te la pasó.", "Kyousuke"),
    80: ("Hmm...", "Saori"),
    81: ("¿Básicamente esta pulsera tiene una historia problemática?", "Saori"),
    82: ("Así es.", "Kyousuke"),
    83: ("Podría o no tener un efecto tal como dice Kuroneko...", "Kyousuke"),
    84: ("Pero si tuviera un efecto negativo, me sentiría mal.", "Kyousuke"),
    85: ("Ya veo. Como dijiste, tiene sentido.", "Saori"),
    86: ("Sin embargo, no puedo dejar que las buenas intenciones de Kuroneko-shi se desperdicien...", "Saori"),
    87: ("Entonces, la guardaré junto con tus artículos otaku.", "Kyousuke"),
    88: ("Después de que resuelvas tu problema, puedes recuperarla.", "Kyousuke"),
    89: ("Si la dueña puede desterrar la mala suerte, entonces esta pulsera maldita no podrá ejercer su efecto.", "Kyousuke"),
    90: ("Bueno, eso es verdad.", "Saori"),
    91: ("Entonces hagamos como dices, puedes guardar la pulsera por mí.", "Saori"),
    92: ("¡Está bien!", "Kyousuke"),
    95: ("Que Kyousuke-shi sea protegido por Dios...", "Saori"),
    96: ("...Por favor, no bromees con eso.", "Kyousuke"),
    97: ("Sin embargo, aprendí algo de esto.", "Saori"),
    98: ("Hay una brecha insalvable entre él y yo.", "Saori"),
    99: ("Saori...", "Kyousuke"),
    100: ("Él es una buena persona. Pero...", "Saori"),
    101: ("Los hobbies otaku son mi... identidad propia.", "Saori"),
    102: ("Por eso, no aceptar eso...", "Saori"),
    103: ("No puedo considerar el matrimonio con él.", "Saori"),
}

data = {
    "000scriptDSAO_0037A.obj": build(a0037_n, a0037_s),
    "000scriptDSAO_0038T.obj": build(a0038_n, a0038_s),
    "000scriptDSAO_0039A.obj": build(a0039_n, a0039_s),
    "000scriptDSAO_0040A.obj": build(a0040_n, a0040_s),
    "000scriptDSAO_0045A.obj": build(a0045_n, a0045_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
