import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0101_n = {
    0: "Ruta de Kuroneko · El Sueño De Un Día De Verano",
    3: "Por cómo se ven las cosas, ¿debería intentarlo de nuevo?",
    4: "¿Qué debería decir de todos modos...? ¿O debería simplemente monitorear la situación en silencio...",
    8: "Maldición... Quedarme callado tuvo el efecto contrario...",
    17: "Guh... Qué embarazoso escucharla repetirlo así...",
    18: "Bueno, ya que llegué tan lejos, sería un error tratar de esquivar el tema...",
    69: "Aunque su manera de expresarlo es única, en resumen, ¿no es todavía sobre eso?",
    70: "«No te acerques a mí». ¿No es eso lo que estás tratando de decir, Kuroneko?",
    73: "...Ah, no puedo soportarlo... No puedo soportarlo en absoluto.",
    77: "...No esperaba ser rechazado tan directamente.",
    78: "Justo cuando pensé que Kuroneko me escucharía si presionaba con fuerza...",
}
a0101_s = {
    1: ("Bueno entonces... ¿Qué debería hacer?", "Kuroneko"),
    2: ("No estoy obligada a escuchar nada de lo que digas.", "Kuroneko"),
    5: ("...¿Sin palabras?", "Kuroneko"),
    6: ("Después de venir hasta aquí, ¿te has quedado sin palabras? Eres tan inútil...", "Kuroneko"),
    7: ("¡N-No, no es nada de eso....!", "Kyousuke"),
    9: ("Sé que estoy siendo extenso, pero por favor.", "Kyousuke"),
    10: ("«Estoy escondiendo algo» está escrito en toda tu cara. ¿No se siente raro que no quieras que me preocupe por esto?", "Kyousuke"),
    11: ("......Oh bueno, probablemente podría ser por mi culpa que estés haciendo tanto.", "Kuroneko"),
    12: ("¿Entonces quieres escucharlo, sin importar qué?", "Kuroneko"),
    13: ("Sin importar qué.", "Kyousuke"),
    14: ("...Ya veo.", "Kuroneko"),
    15: ("Sí, así es.", "Kyousuke"),
    16: ("Entonces... ¿soy considerada una de tus 【amigas importantes】?", "Kuroneko"),
    19: ("S-Sí... Podrías decir eso.", "Kyousuke"),
    20: ("Jeh, ¿es así...", "Kuroneko"),
    21: ("Está bien entonces, te daré una recompensa. Ya que respondiste tan honestamente.", "Kuroneko"),
    22: ("¿Por qué me estás mirando con desprecio? Espera, ¿una recompensa...?", "Kyousuke"),
    23: ("Sí...", "Kuroneko"),
    24: ("Te responderé.", "Kuroneko"),
    25: ("Eres una persona tan desesperanzadora, ¿no...?", "Kuroneko"),
    26: ("*suspiro* Qué patético... Está bien entonces...", "Kuroneko"),
    27: ("No hay manera de evitarlo, así que escucha bien.", "Kuroneko"),
    28: ("¿E-En serio...", "Kyousuke"),
    29: ("Gracias.", "Kyousuke"),
    30: ("...Supongo que has escuchado de Saori? Sobre mi círculo participando en el próximo Comiket de Verano.", "Kuroneko"),
    31: ("Sí, he escuchado sobre eso.", "Kyousuke"),
    32: ("Ese pedazo de manuscrito no ha estado avanzando tan fluidamente como planeé.", "Kuroneko"),
    33: ("Así que ahora estoy quedándome atrás y tratando de remontar... Eso es todo.", "Kuroneko"),
    34: ("...¿Eso es todo?", "Kyousuke"),
    35: ("Sí. Eso es todo.", "Kuroneko"),
    36: ("...¿En serio?", "Kyousuke"),
    37: ("...Seguro que eres persistente.", "Kuroneko"),
    38: ("Hmm... ¡Entonces déjamelo a mí! Yo voy a--", "Kyousuke"),
    39: ("No lo necesito.", "Kuroneko"),
    40: ("¡¿Ni siquiera he dicho nada todavía?!", "Kyousuke"),
    41: ("Ibas a decir «¡Permíteme ayudar!» de todos modos, ¿no?", "Kuroneko"),
    42: ("...¿Puedes leer mi mente?", "Kyousuke"),
    43: ("¿Sabes lo que significa un «favor no deseado»? Eso es lo que eres ahora mismo.", "Kuroneko"),
    44: ("¿Puedes por favor no malinterpretar? Solo te lo estoy diciendo porque estás siendo persistente y no tengo la menor intención de dejar que participes.", "Kuroneko"),
    45: ("...Así que por favor no hagas más cosas innecesarias.", "Kuroneko"),
    46: ("¿Cosas innecesarias...? Solo quiero ayudarte...", "Kyousuke"),
    47: ("¿No te lo he dicho antes? Es mejor mantenerse alejado de los obstáculos. Todos estos son obstáculos en la producción de obras.", "Kuroneko"),
    48: ("¿De verdad estoy siendo un obstáculo?", "Kyousuke"),
    49: ("Así es. Es problemático si dejara que un aficionado participe.", "Kuroneko"),
    50: ("¿Ahora lo entiendes? ¿Siquiera puedes dibujar manga?", "Kuroneko"),
    51: ("...Es verdad que no puedo, pero también sé esto.", "Kyousuke"),
    52: ("¿Oh?", "Kuroneko"),
    53: ("Se requiere un «asistente» cuando se trata de manga, ¿no?", "Kyousuke"),
    54: ("Además, hay muchas otras cosas que hacer... En las que incluso un aficionado podría ayudar.", "Kyousuke"),
    55: ("Oh, qué sorpresa... Senpai realmente sabe sobre estas cosas.", "Kuroneko"),
    56: ("Porque te conozco desde hace suficiente tiempo, por eso sé solo esto.", "Kyousuke"),
    57: ("...Hmph, de acuerdo.", "Kuroneko"),
    58: ("Todo esto es solo una fachada de todos modos.", "Kuroneko"),
    59: ("¿Una fachada?", "Kyousuke"),
    60: ("Te informaré de la verdad.", "Kuroneko"),
    61: ("Seguramente te dolerá... Pero querrías escucharlo de todos modos, ¿no? Por lo tanto...", "Kuroneko"),
    62: ("...¿Estás preparado?", "Kuroneko"),
    63: ("Sí, cuando sea.", "Kyousuke"),
    64: ("Jeje, tienes algo de agallas... Bueno entonces, permíteme decirte.", "Kuroneko"),
    65: ("Para mí, crear es el acto de tomar un fragmento de mi mente y recrearlo, sublimarlo.", "Kuroneko"),
    66: ("No es exagerado decir que creé algo nuevo.", "Kuroneko"),
    67: ("Por eso no permitiré que nadie invada este dominio.", "Kuroneko"),
    68: ("Especialmente alguien como tú, que ni siquiera sabe dónde está parado. Nunca.", "Kuroneko"),
    71: ("Debería haberlo dicho antes, si uno pisa el dominio, se le impondrá un castigo.", "Kuroneko"),
    72: ("Tu castigo es mi rechazo. ¿Puedes soportar este castigo?", "Kuroneko"),
    74: ("...Lo siento.", "Kyousuke"),
    75: ("Hmph... Me alegra que lo entiendas.", "Kuroneko"),
    76: ("Maldición... Seguro que soy inútil.", "Kyousuke"),
    79: ("¡¿Y yo pensaba que nuestra relación se arreglaría...!", "Kyousuke"),
}

a0102_n = {
    0: "Ruta de Kuroneko · Esfuerzos Completamente Ignorados",
    1: "Esta es la primera vez que me siento así... es realmente insoportable ser completamente ignorado por alguien.",
    5: "Por Dios... Es algo deprimente cuando considero la posibilidad de que esto podría durar para siempre...",
    6: "Sé que estoy defraudando a Saori que está contando conmigo... Pero después de que ella me dijo eso, ¿qué se supone que debo hacer?",
    7: "Manami también me sobreestimó... Si esos son los deseos de la persona en cuestión, ¡no hay nada que pueda hacer!",
    8: "También he defraudado a Kirino... Pero, estoy seguro de que estarás bien.",
    9: "Tu amistad con Kuroneko no se romperá por algo así...",
    10: "Pero, en cuanto a mí...",
    24: "Si Kuroneko está siendo presionada, me gustaría apoyarla. Incluso ahora ese sentimiento no ha cambiado.",
    25: "Pero... si la persona en cuestión no desea ayuda, ¿qué pasaría si la ayudara?",
    26: "Todavía no puedo encontrar una respuesta a eso...",
    27: "...Así es... Si le preguntara a Akagi, que no está realmente relacionado con Kuroneko... ¿Sería eso bueno?",
    28: "No, debería parar.... No es como si tuviera algo de qué hablar tranquilamente....",
    29: "Y, también... Esto es algo de lo que debo obtener la respuesta por mí mismo.",
    30: "Por eso...",
    48: "¿Hermanita...? Kuroneko no es mi hermana...",
    49: "Lo que me recuerda, la propia Kuroneko dijo algo similar antes...",
    50: "Lo pensé... Si fueras mi hermana, ¿resultaría así?",
    52: "Kuroneko sería como ella...",
    54: "...¿Algo así?",
}
a0102_s = {
    2: ("Y-Yo...", "Kyousuke"),
    3: (".........", "Kuroneko"),
    4: ("Completamente ignorado... huh.", "Kyousuke"),
    11: ("...*suspiro*", "Kyousuke"),
    12: ("Dime, escuché esto de mi hermana hoy.", "Akagi"),
    13: ("Sí...", "Kyousuke"),
    14: ("Esa chica... parece que está en muy mal estado...", "Akagi"),
    15: ("...¿Mal estado?", "Kyousuke"),
    16: ("Parece que está constantemente empujando sus límites.", "Akagi"),
    17: ("Y continúa conduciéndose, alcanzando sus límites... un círculo vicioso.", "Akagi"),
    18: ("Suena como el peor patrón.", "Kyousuke"),
    19: ("Sí, una espléndida ruta hacia la autodestrucción.", "Akagi"),
    20: ("El senpai del club quería detenerla... pero parece que no escucha en absoluto, ¿no?", "Akagi"),
    21: ("La habría detenido antes si fuera tan simple.", "Kyousuke"),
    22: ("...Es verdad.", "Akagi"),
    23: ("Oh en serio...", "Kyousuke"),
    31: ("Oye, ¿Akagi...?", "Kyousuke"),
    32: ("¿Hmm? ¿Qué es?", "Akagi"),
    33: ("Esto es solo teóricamente hablando, ¿de acuerdo?", "Kyousuke"),
    34: ("¿Hmm? Sí.", "Akagi"),
    35: ("¿Qué pasaría si, a simple vista pudieras decir que tu hermana está tratando de forzarse...", "Kyousuke"),
    36: ("...Y te pelearas con su amiga, diciendo que todo era por el bien de la producción...", "Kyousuke"),
    37: ("Es doloroso de ver, así que querías detenerla, pero te dijeron que no te metieras a cambio...", "Kyousuke"),
    38: ("En ese punto... ¿qué harías?", "Kyousuke"),
    39: ("¡Mi hermana nunca diría algo así!", "Akagi"),
    40: ("...Gracias por reaccionar exactamente como esperaba.", "Kyousuke"),
    41: ("No te preguntaré de nuevo.", "Kyousuke"),
    42: ("Oye oye, ¿dije algo extraño hace un momento?", "Akagi"),
    43: ("Estoy colgando-", "Kyousuke"),
    44: ("¡E-Espera! Oye, Kousaka.", "Akagi"),
    45: ("Si mi hermana está siendo imprudente, ¿no sería más o menos lo mismo para cualquiera, haciendo lo que haría un hermano mayor?", "Akagi"),
    46: ("...¿Eh? Bueno... supongo que sí.", "Kyousuke"),
    47: ("Esa chica... Es 【como una hermanita】 para ti, ¿no?", "Akagi"),
    51: ("¿Por qué me estás mirando fijamente? Asqueroso.", "Kirino"),
    53: ("¿Qué estás mirando? Asqueroso.", "Kuroneko"),
    55: ("Eso sería... bastante desagradable.", "Kyousuke"),
    56: ("¿En serio? ¿Pero no es ella tu 【linda kohai】?", "Akagi"),
    57: ("Dime, Akagi, ahora estoy realmente preocupado por ti.", "Kyousuke"),
    58: ("¿Por qué 'linda kohai' equivale a 'hermanita'?", "Kyousuke"),
    59: ("¿Huh? ¿Por qué?", "Akagi"),
    60: ("Entonces déjame preguntarte otra vez, Akagi, ¿por qué ves a las personas por las que te preocupas y que son más jóvenes que tú como hermanitas?", "Kyousuke"),
    61: ("Seguro que estás siendo irrespetuoso... ¡Yo solo tengo una sola hermana!", "Akagi"),
    62: ("¡Eso lo sé!", "Kyousuke"),
    63: ("Estoy colgando.", "Kyousuke"),
    64: ("De acuerdo, no lo entiendo muy bien, pero buena suerte de todos modos.", "Akagi"),
    65: ("...Pero, ¿qué planeas hacer?", "Akagi"),
    66: ("Quién sabe...", "Kyousuke"),
    67: ("Supongo que intentaré pensarlo un poco más. Nos vemos.", "Kyousuke"),
    68: ("Tienen la intención de prohibirle entrar al salón del club... Aunque dudo que exigirse de más en algún lugar donde la gente no pueda monitorearla sea cualquier", "Akagi"),
    69: ("mejor.", "Akagi"),
}

a0103_n = {
    0: "Ruta de Kuroneko · La Perspectiva De La Hermanita",
    4: "Pero hace un momento estabas mirando fijamente hacia aquí.",
    5: "Ah, no... estabas mirando hacia aquí porque yo estaba hablando de Kuroneko. Eso es natural.",
    9: "En otras palabras, quiere decir «no puedo evitar preocuparme por ella».",
    10: "Pobre Kirino, parece que ya no puede soportarlo más, aunque no lo dirá.",
    11: "Una amiga cercana que no está aquí, de repente.",
    12: "Bueno, no es como si pudiera decir algo sobre otras personas.",
    13: "Eso es exactamente por lo que no hizo un gran escándalo, sino que se mantiene callada al respecto.",
    14: "El dolor de que una «vida diaria normal» sea destruida, conozco muy bien ese sentimiento.",
    15: "No es solo Kirino. Incluso yo encuentro bastante doloroso no poder ver a Kuroneko como de costumbre.",
    16: "En cuanto a lo que dijo Kuroneko, «nuestro mundo» está a punto de derrumbarse.",
    17: "Pero si yo no pisara el mundo de Kuroneko, entonces también destruiría nuestras vidas diarias -- Nuestro mundo.",
    18: "Pisar el mundo de Kuroneko, supongo que significa hacer todo lo posible por volver las cosas a como eran. Estoy seguro de que eso es.",
    19: "...Bueno, no sé si sea posible volver a como antes incluso si intervengo.",
    20: "--¿Tengo ese tipo de derecho?",
    21: "Ella se muestra algo reacia, ¿así que puedo siquiera poner un pie en sus problemas?",
    28: "¿Qué le pasa a Kirino...?",
    29: "Sin embargo, a menos que pise su mundo, mi mundo seguramente cambiará si esto continúa...",
    35: "Si Kuroneko fuera mi hermanita...",
    43: "Parece que no es muy diferente de lo que está pasando ahora...",
    49: "Sip, una reacción de acuerdo a mis expectativas.",
    63: "Así fue como te hice frente antes.",
    64: "Aunque todavía me pregunto si esa fue la elección correcta.",
    68: "Murmuré un agradecimiento, con dos significados.",
}
a0103_s = {
    1: ("...¿Hm?", "Kyousuke"),
    2: ("¿Qué pasa, algo anda mal?", "Kyousuke"),
    3: ("...No es nada, nada en absoluto.", "Kirino"),
    6: ("Debes estar preocupada por ella.", "Kyousuke"),
    7: ("¿Q-Quién estaría preocupada por ella?", "Kirino"),
    8: ("No me aburriré incluso si ella no está.", "Kirino"),
    22: (".....Eres un idiota.", "Kirino"),
    23: ("¿Huh?", "Kyousuke"),
    24: ("...No es nada.", "Kirino"),
    25: ("Pero además de eso, ve y haz algo ya.", "Kirino"),
    26: ("Eso lo sé.", "Kyousuke"),
    27: ("Si lo entiendes, entonces ponte en marcha como siempre....", "Kirino"),
    30: ("Dios... ¿Cuánto tiempo vas a estar nervioso?", "Kirino"),
    31: ("...Jeje.", "Kyousuke"),
    32: ("¿Q-Qué? Riendo de repente así...", "Kirino"),
    33: ("Tú y Kuroneko seguro que tienen algunas similitudes.", "Kyousuke"),
    34: ("¿Huh?", "Kirino"),
    36: ("¡Eres una hermana mayor excéntrica! ¡Apúrate y supera tu chuunibyou!", "Kirino"),
    37: ("Incluso si somos familia, es embarazoso solo mirarte, ¿no lo entiendes?", "Kirino"),
    38: ("...Qué ruidoso.", "Kuroneko"),
    39: ("Ya es hora de que te vuelvas más madura, y más tolerante con los intereses de los demás, ¿no?", "Kuroneko"),
    40: ("Solo con mirarte divagando por ahí, me siento tan asqueada que me dan náuseas.", "Kuroneko"),
    41: ("Aun así, ¿no me lo guardo para mí? Deberías aprender de mí.", "Kuroneko"),
    42: ("¡¿Pero no lo dijiste al final?!", "Kirino"),
    44: ("¿Por qué te estás riendo para ti mismo?", "Kirino"),
    45: ("Bueno, ¿debería decir que ambas son similares en carácter, o que ambas no están siendo honestas...", "Kyousuke"),
    46: ("Estaba pensando que quizás ustedes dos realmente son hermanas después de todo.", "Kyousuke"),
    47: ("¿No puedes dejar de decir cosas tan estúpidas?", "Kirino"),
    48: ("¿Cómo podría compararse esa aspirante a novelista delirante con una normal como yo?", "Kirino"),
    50: ("Estúpida, eso no es importante. Lo importante es la naturaleza verdadera de una persona. ¡Lo que son!", "Kyousuke"),
    51: ("¿Q-Quién está diciendo que somos hermanas?! Una chuuni delirante como ella... como mi hermanita...!", "Kirino"),
    52: ("Hm... Supongo que podría funcionar en realidad...", "Kirino"),
    53: ("¡¿Acabas de mezclar el 2D y el 3D?!", "Kyousuke"),
    54: ("¿Eh?", "Kirino"),
    55: ("Mientras sea algo relacionado con hermanitas, todo te sirve... Además, Kuroneko debería ser tu hermana mayor ya que es mayor que tú.", "Kyousuke"),
    56: ("B-Bueno... supongo.", "Kirino"),
    57: ("Mira lo emocionada que estás, ¿no quieres tener una hermanita?", "Kyousuke"),
    58: ("Tch... eres ruidoso.", "Kirino"),
    59: ("Si tienes tiempo para hacer chistes estúpidos, deberías estar lidiando con ella ahora mismo.", "Kirino"),
    60: ("...Lo sé.", "Kyousuke"),
    61: ("Ella es como una 【gata indómita】, alguien necesita detenerla a la fuerza. ¿No es esa tu especialidad?", "Kirino"),
    62: ("Sí...", "Kyousuke"),
    65: ("Si lo entiendes, entonces ve e inténtalo?", "Kirino"),
    66: ("Porque ella definitivamente está esperando.", "Kirino"),
    67: ("...Gracias.", "Kyousuke"),
}

a0104_n = {
    0: "Ruta de Kuroneko · La Conversación Con Papá",
    5: "¿Q-Qué se cree que está preguntando?!",
    7: "¿Está hablando de Kuroneko...!?",
    9: "Mi Mamá es tan bocona... Y además, su malentendido la llevó a contarle a Papá...",
    14: "Aunque este malentendido no es realmente genial, no parece malo discutir esto con Papá.",
    19: "Parece que sí.",
    32: "...No quiero tener esta situación dos veces.",
    37: "Como dije, eso es solo un malentendido...",
}
a0104_s = {
    1: ("Kyousuke.", "Daisuke"),
    2: ("¿Huh?", "Kyousuke"),
    3: ("¿Has... conseguido una novia?", "Daisuke"),
    4: ("¡¿Huh?!", "Kyousuke"),
    6: ("Escuché de tu madre. Has estado trayendo a tu novia a casa últimamente.", "Daisuke"),
    8: ("N-No, eso es, uh... Solo la estoy ayudando a hacer un juego...", "Kyousuke"),
    10: ("También escuché que no ha estado aquí últimamente.", "Daisuke"),
    11: ("Urk...", "Kyousuke"),
    12: ("¿Ustedes dos se pelearon?", "Daisuke"),
    13: ("Se... podría decir eso.", "Kyousuke"),
    15: ("No tengo la menor idea de lo que ella está pensando, así que estoy en un pequeño aprieto.", "Kyousuke"),
    16: ("Ya veo", "Daisuke"),
    17: (".........", "Daisuke"),
    18: ("Eres como yo, socialmente torpe.", "Daisuke"),
    20: ("*tose*... Cruzar caminos el uno con el otro es algo que le puede pasar a cualquiera.", "Daisuke"),
    21: ("Además, esto fácilmente se convertirá en la causa de choques y peleas.", "Daisuke"),
    22: ("Aunque nunca los he visto a ti y a Mamá peleando...", "Kyousuke"),
    23: ("Eso es solo porque no te dejamos verlo.", "Daisuke"),
    24: ("Soy como lo que dijiste antes. Incluso ahora, hay momentos en los que no entiendo de qué está hablando tu madre.", "Daisuke"),
    25: ("No saber de qué está enojada la otra persona. No saber de qué está descontenta. No saber qué está... pensando.", "Daisuke"),
    26: ("Cuanto más te preocupas por la otra parte, más fácil es que tus acciones y palabras la lastimen.", "Daisuke"),
    27: ("En situaciones así... ¿qué debería hacer?", "Kyousuke"),
    28: ("Es difícil de decir, no hay una respuesta estándar para eso. Todo lo que puedes hacer es pensarlo seriamente, y tomar la acción que creas que es la mejor.", "Daisuke"),
    29: ("Kyousuke, no pienses en «tener éxito». Es imposible para nosotros.", "Daisuke"),
    30: ("¿Imposible?", "Kyousuke"),
    31: ("Sí. Sin embargo, incluso tú tienes tu propia manera de hacer las cosas, así que permíteme verla en algún momento.", "Daisuke"),
    33: ("Incluso el inútil puede hacer algo si le pone esfuerzo.", "Daisuke"),
    34: ("Lo entiendo, lo intentaré, Papá.", "Kyousuke"),
    35: ("Ya veo.", "Daisuke"),
    36: ("Si ustedes dos se reconcilian, preséntala ante nosotros. Estoy deseándolo.", "Daisuke"),
}

a0105_n = {
    0: "Ruta de Kuroneko · La Conversación Con Papá",
    1: "Reforcé mi determinación de enfrentar a Kuroneko una vez más.",
    2: "Porque he recibido el aliento de muchas personas.",
    3: "Trabajaré duro a mi manera incluso si me rechaza de nuevo. Me hice esa promesa a mí mismo.",
    87: "Maldición... ¿No hay nada que pueda decir...",
    88: "Verla alejarse, sin poder hacer nada, es frustrante... ¿Me quedo aquí apretando los dientes...",
}
a0105_s = {
    4: ("Hola. Parece que no has avanzado mucho.", "Kyousuke"),
    5: ("¿Qué quieres? Seguro que tienes mucho tiempo libre si puedes venir al salón de los de primer año durante el verano.", "Kuroneko"),
    6: ("No es porque tenga tiempo libre. Estoy aquí porque tengo algo que hacer.", "Kyousuke"),
    7: ("¿Es algo que requiera específicamente que estés aquí?", "Kuroneko"),
    8: ("Lo es.", "Kyousuke"),
    9: ("Eres... inesperadamente obstinada.", "Kyousuke"),
    10: ("¿Obstinada? ¿De qué diablos estás hablando?", "Kuroneko"),
    11: ("Estoy seguro de que lo sabes, ¿no? Si estás siendo tan imprudente... estoy seguro de que estás a punto de llegar a tu límite, ¿no?", "Kyousuke"),
    12: ("Jeh, en absoluto... Solo estoy haciendo lo que es necesario para lograr lo que quiero.", "Kuroneko"),
    13: ("Qué obstinada.", "Kyousuke"),
    14: ("Jeje, esto es algo que cualquiera podría hacer si quisiera.", "Kuroneko"),
    15: ("Hacer tu mejor esfuerzo para alcanzar tu meta, ¿cómo está eso mal?", "Kuroneko"),
    16: ("¡La gente no se agota hasta el cansancio así!", "Kyousuke"),
    17: ("Mírate, te estás tambaleando visiblemente...", "Kyousuke"),
    18: ("Oye, déjame ayudar...", "Kyousuke"),
    19: ("No es necesario.", "Kuroneko"),
    20: ("...Tch, al menos déjame terminar lo que tengo que decir.", "Kyousuke"),
    21: ("Mi respuesta será la misma sin importar cuántas veces lo digas. ¿Por qué no te esfuerzas un poco en aprender eso?", "Kuroneko"),
    22: ("...No me estás mirando desde el principio.", "Kyousuke"),
    23: ("Es inútil no importa lo que digas, no tengo intención de escucharte.", "Kuroneko"),
    24: ("¿Así que cualquier cosa que diga es inútil?", "Kyousuke"),
    25: ("Sí, así es. Así que déjame en paz.", "Kuroneko"),
    26: ("Por favor no me detengas más, es solo un poco más así que...", "Kuroneko"),
    27: ("¿No es algo dado que tengo que detenerte?", "Kyousuke"),
    28: ("¿Crees que te permitiré seguir siendo imprudente en tu estado actual?", "Kyousuke"),
    29: ("Por eso he dicho, eres un obstáculo.", "Kuroneko"),
    30: ("Si preocuparme por ti es ser un obstáculo, entonces seguiré siendo un obstáculo tantas veces como quiera.", "Kyousuke"),
    31: ("Aceptaré tus amables intenciones ya que lo has puesto así. Lo aprecio. Por eso...", "Kuroneko"),
    32: ("...¿Entiendes que todo terminará en el momento en que te derrumbes por «un poco más»?", "Kyousuke"),
    33: ("Por supuesto. Sin embargo, esta vez es solo... que mi habilidad todavía no es suficiente.", "Kuroneko"),
    34: ("Es una lástima no poder terminar algo. Tengo algo de arrepentimiento... Pero es mi deseo caminar por este camino de sacrificio.", "Kuroneko"),
    35: ("...¿Qué clase de deseo es ese?", "Kyousuke"),
    36: ("...Como esperaba, parece que nuestras opiniones difieren.", "Kuroneko"),
    37: ("¿No es hora de que me dejes ir? Esta cantidad de tiempo es muy importante para mí ahora mismo.", "Kuroneko"),
    38: ("¿Pero no has escuchado nada de lo que he dicho?", "Kyousuke"),
    39: ("Es inútil sin importar lo que digas. ¿No lo entiendes? Ambos no tenemos intención de ceder.", "Kuroneko"),
    40: ("Por supuesto, estoy aquí solo para detenerte.", "Kyousuke"),
    41: ("¿En serio? Sin embargo, no me rendiré, sin importar lo que digas.", "Kuroneko"),
    42: ("Así que por favor deja de perder el tiempo. El tiempo que te asigné se acabó.", "Kuroneko"),
    43: ("...¿Qué significa eso?", "Kyousuke"),
    44: ("Significa exactamente lo que acabo de decir. Por lo menos, no deberíamos encontrarnos hasta... que el manuscrito esté terminado.", "Kuroneko"),
    45: ("Solo me causarás problemas cuando me busques.", "Kuroneko"),
    46: ("¿Quieres decir... que ni siquiera vendrás a la escuela?", "Kyousuke"),
    47: ("Sí. El trabajo se puede hacer en casa.", "Kuroneko"),
    48: ("¡¿Eres una idiota?!", "Kyousuke"),
    49: ("¿Ir tan lejos para evitarme... y que ni siquiera pueda preocuparme por ti, es eso lo que estás diciendo?", "Kyousuke"),
    50: ("...Es como has dicho. Tener esa intención es suficiente.", "Kuroneko"),
    51: ("Así que, por favor no interfieras innecesariamente.", "Kuroneko"),
    52: ("...¿Qué pasa si digo que no? ¿Si digo que no voy a permitir esto e incluso te detengo a la fuerza?", "Kyousuke"),
    53: ("Eso es solo repetir lo que hemos dicho hoy. Es improductivo. Es inútil, ríndete.", "Kuroneko"),
    54: ("Seguiré deteniéndote hasta que lo hagas.", "Kyousuke"),
    55: ("No me detendré. ...No, me daré a fondo para compensar el tiempo perdido.", "Kuroneko"),
    56: ("Tch... Eso es injusto... ¿Cómo se supone que responda a lo que has dicho...?", "Kyousuke"),
    57: ("No tienes que hacerlo. Ya he dicho esto antes, ¿no?", "Kuroneko"),
    58: ("Solo hay una cosa que quiero que hagas ahora mismo.", "Kuroneko"),
    59: ("...¿Y esa sería?", "Kyousuke"),
    60: ("...Que me ignores.", "Kuroneko"),
    61: ("Eso otra vez...", "Kyousuke"),
    62: ("¿Qué tal? Si de verdad estás preocupado por mí, ¿puedes hacerme este pequeño favor?", "Kuroneko"),
    63: ("¿Qué quieres decir con ignorarte?", "Kyousuke"),
    64: ("Es simple. No me hables incluso si nos encontramos, será como si no nos conociéramos. Tratarme como una completa desconocida servirá.", "Kuroneko"),
    65: ("¿Como una completa desconocida, cómo es eso siquiera posible...", "Kyousuke"),
    66: ("Estoy demasiado preocupado por ti, ¿por qué no lo entiendes?", "Kyousuke"),
    67: ("...Senpai, simplemente ríndete conmigo ya...", "Kuroneko"),
    68: ("¿Qué, oye!", "Kyousuke"),
    69: ("¿Es ese... tu verdadero deseo?", "Kyousuke"),
    70: ("Sí, así es.", "Kuroneko"),
    71: ("¿Estás totalmente.... de acuerdo con eso?", "Kyousuke"),
    72: ("Obviamente. Yo misma lo estoy deseando.", "Kuroneko"),
    73: ("...Maldición... ¿No hay alguna manera de detenerte?", "Kyousuke"),
    74: ("...Obviamente. No me detendrías tú. Bueno, eso es eso...", "Kuroneko"),
    75: ("Así que, terminará aquí. Lo diré una última vez.", "Kuroneko"),
    76: ("Déjame en paz.", "Kuroneko"),
    77: ("...¿Hasta cuándo?", "Kyousuke"),
    78: ("Veamos... hasta que el manuscrito esté terminado.", "Kuroneko"),
    79: ("Por lo menos, tendremos que encontrarnos después de que empiecen las clases, ¿no?", "Kuroneko"),
    80: ("Así que, antes de que el manuscrito esté completo, somos completos desconocidos. No me hables incluso si nos encontramos, ¿de acuerdo?", "Kuroneko"),
    81: ("Estoy segura de que puedes soportarlo si es este tipo de nivel, ¿no?", "Kuroneko"),
    82: ("....¿Lo dices en serio?", "Kyousuke"),
    83: ("Sí, por supuesto.", "Kuroneko"),
    84: ("Incluso si es tal como dijiste....cuando eso termine, ¿podemos volver a nuestra antigua relación? ¿Vas a... volver a como antes?", "Kyousuke"),
    85: ("Las relaciones de las personas son algo que cambia continuamente, ¿no?", "Kuroneko"),
    86: ("Por eso ahora me despido de ti.", "Kuroneko"),
    89: ("...ah.", "Kuroneko"),
    90: ("¡Ah! ¡Oye! ¡Kuroneko, Kuroneko!?", "Kyousuke"),
    91: ("¡Maldición! ¡A-A la enfermería!", "Kyousuke"),
}

data = {
    "000scriptCKUR_0101A.obj": build(a0101_n, a0101_s),
    "000scriptCKUR_0102A.obj": build(a0102_n, a0102_s),
    "000scriptCKUR_0103A.obj": build(a0103_n, a0103_s),
    "000scriptCKUR_0104A.obj": build(a0104_n, a0104_s),
    "000scriptCKUR_0105T.obj": build(a0105_n, a0105_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
