import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

n = {
    0: "if · El Capítulo De Las Circunstancias Entre Hermano Y Hermana",
    1: "Tomando una respiración profunda, primero miré fijamente el Espacio Oscuro que Kirino había escondido.",
    2: "Incluyendo DVDs, figuras, paquetes de juegos y folletos, era la imagen misma de un montón de mercancía otaku.",
    5: "Levanté el álbum de entre la enorme pila de mercancía otaku, colocado allí como para esconderlo.",
    6: "Este tipo de cosa destacaba demasiado entre las otras ilustraciones de anime bishoujo.",
    7: "...¿Por qué hay un álbum en un lugar así?",
    8: "Entonces Kirino trató de esconder sus fotos vergonzosas de cuando era pequeña en un lugar así......",
    10: "Aunque es llamada una hermanita perfecta tanto en apariencia como en intelecto, si es de cuando era una niña pequeña...",
    11: "¿No es solo natural que tenga fotos de mojando la cama y llorando?",
    14: "......Diré esto solo por si acaso.",
    15: "Solo quería saber la debilidad de mi maldita y engreída hermanita, y nunca querría ver una «Kirino mojando la cama», ¿okay?",
    16: "¡No malentiendan ese punto, todos ustedes buenos chicos y chicas!",
    20: "Estaba lleno de ese tipo de cosas...",
    21: "Las fotos de Kirino creciendo que vi en el álbum eran todas de momentos profundamente emotivos...",
    22: "Kirino llorando en el día de deportes... Kirino yendo a un viaje y quedándose dormida después de cansarse... Kirino haciendo una señal de paz con Papá y Mamá en la foto...",
    23: "La Kirino en estas fotos cambiaba constantemente su expresión exactamente de la misma manera en que lo hace ahora.",
    24: "Odio admitirlo, pero... creo que Kirino era increíblemente linda cuando era pequeña. En serio.",
    25: "Llámenme un hermano mayor idiota, pero no puedo evitar pensar eso.",
    26: "No, no, todos se sienten así sobre los niños, ¿verdad? Especialmente cuando se trata de la propia familia, los miras bajo una luz favorable.",
    28: "Dejé escapar un suspiro naturalmente mientras miraba una foto de mi hermanita sonriendo inocentemente.",
    29: "No quiero negar su yo actual, pero solo desearía... que me respetara un poco más como su hermano mayor.",
    30: "Al menos, desearía que dejara de tratarme como un extraño, mirándome fijamente como si no pensara que somos familia.",
    32: "Seguí y seguí pasando las páginas, pero...",
    34: "Así es, este álbum ignoró espléndida y completamente mi existencia.",
    35: "Contenía a Kirino de principio a fin. Así como a Papá y Mamá en algunos lugares.",
    36: "No pude encontrar ni una sola foto conmigo, su hijo y hermano mayor de Kirino, en ella.",
    37: "Como si tales fotos hubieran sido sacadas intencionalmente...",
    40: "Pero, cuando la reviso...",
    41: "Solo hay fotos de eventos de los que no tengo memoria...",
    42: "¿Cuándo fuimos a este viaje? No puedo recordarlo en absoluto...",
    46: "Solo hay fotos de ella misma en ese álbum que tiene...",
    47: "Estoy seguro de que al lado de ese, también hay un «álbum solo de Kyousuke» en algún lugar.",
    48: "Después de eso, Kirino terminó su llamada telefónica y volvió a la habitación, pero...",
    49: "Por alguna razón, dijo «En realidad, eso es suficiente por hoy», y revocó la consulta de vida ella misma.",
    50: "Al final, terminó sin que yo descubriera lo que Kirino estaba tratando de decirme.",
    51: "Y entonces, a la mañana siguiente...",
    62: "¿Realmente hice eso como ella dijo...?",
    63: "...No sirve. No puedo recordarlo en absoluto.",
    67: "Preguntarle a Mamá no sirvió. Probablemente no me estaba escuchando en serio...",
    68: "...Bueno, solo hay una persona más a quien puedo preguntar.",
    74: "Realmente no lo entiendo en absoluto.",
    77: "¡¿Una respuesta instantánea?! Como esperaba, ¡me rompe el corazón!!",
    84: "¿Qué es esto? Esto se siente tan inútil como hablar con una pared de ladrillos.",
    85: "Como si estuviera tratando de esconder el secreto de mi nacimiento...",
    86: "...Espera, ¿¡qué estoy diciendo?! Algo como un «secreto de nacimiento», ¿¡no es eso desdibujar demasiado la línea con el mundo 2D?!",
    87: "Soy un estudiante masculino de secundaria extremadamente normal... ¿No es así, Kousaka Kyousuke?",
    94: "Lo que Papá me dijo después fue algo que me costó creer de inmediato...",
    98: "Un shock que se sentía como un martillo de hierro golpeando mi cabeza golpeó todo mi cuerpo.",
    103: "Diciendo eso, Papá se alejó de mí.",
    104: "Honestamente, lo agradecí.",
    105: "Incluso si de repente me dicen «¡Tú no eres nuestro hijo!», no se siente real, ¿sabes?",
    106: "Probablemente hay varias circunstancias detrás de esto, pero no tengo la confianza de que podría entenderlo si me lo explicara ahora.",
    122: "Todavía no he entendido y aceptado todo.",
    123: "Aun así, mi Mamá y mi Papá no pueden ser nadie más que estos dos para mí.",
    124: "Si fuera más joven, podría sentirme un poco más confundido, aunque.",
    125: "El yo actual piensa esto.",
    126: "Si soy feliz ahora mismo, ¡eso es suficiente!",
    127: "...Pensé eso, pero...",
    140: "La lengua malvada de Kirino era algo normal. Debería haber salido de la habitación con indiferencia hace un momento.",
    141: "Aun así, estar a solas con Kirino en la misma habitación me hacía sentir incómodo, y últimamente me encerraba en mi habitación para evitar encontrarme con ella cara a cara tanto como",
    142: "fuera posible.",
    143: "No, ¿sobre qué estoy dudando? Debería simplemente actuar como siempre, ¡como de costumbre!",
    144: "¡Por ahora, Kirino todavía piensa en mí como su hermano mayor!",
    146: "......No, quizás no.",
    147: "Aun así.",
    148: "Incluso si no me trata como su hermano mayor y no somos parientes de sangre, esa maldita y descarada estudiante de secundaria es mi hermanita.",
    149: "Si interactúo con ella de la misma manera en que lo he hecho hasta ahora, no habrá problemas.",
    150: "...Entiendo esto en mi cabeza.",
    151: "Pero, si lo pensaba bien, la relación entre ella y yo es la de completos extraños viviendo en la misma casa.",
    153: "Una vez que lo pensé, se negó a desaparecer y permaneció atascado en mi cabeza.",
    157: "El intercambio de esta mañana entre yo y Kirino también fue incómodo.",
    158: "Bueno, desde el principio, la actitud de Kirino hacia mí siempre ha sido como la de entrar en contacto con una oruga peluda, ¿sabes? No mucha",
    159: "diferencia en cómo me trataban de antes.",
    160: "Más bien... Lo que es diferente es que me siento más consciente a su alrededor.",
    161: "Le lancé una mirada de reojo.",
    162: "Kirino tenía sus piernas dobladas sobre la silla en la que estaba sentada, y estaba sentada en una postura que exponía libremente sus muslos blancos.",
    163: "Esta había sido una escena sin importancia que veía todos los días hasta hace poco.",
    164: "Sin embargo, solo por cambiar mi punto de vista, se había convertido en una escena que realmente me preocupaba sobre dónde mirar.",
    165: "Era como mirar los muslos de una completa extraña...",
    171: "No puedo soportar hablar más con Kirino. Me retiraré de vuelta a mi habitación...",
}
s = {
    3: ("Hmm... ¿Qué es esto?", "Kyousuke"),
    4: ("Es bastante viejo, pero... ¿un álbum de fotos?", "Kyousuke"),
    9: ("Kukuku...", "Kyousuke"),
    12: ("Jejeje...", "Kyousuke"),
    13: ("¡He conseguido la debilidad de Kousaka Kirino!", "Kyousuke"),
    17: ("Lo siguiente es...", "Kyousuke"),
    18: ("...No hay ninguna.", "Kyousuke"),
    19: ("......", "Kyousuke"),
    27: ("¿Por qué no pudo crecer así?", "Kyousuke"),
    31: ("......Aun así.", "Kyousuke"),
    33: ("Este álbum... no tiene nada más que fotos de Papá, Mamá y Kirino.", "Kyousuke"),
    38: ("B-Bueno, ¡después de todo Mamá y Papá favorecen a Kirino! No es como que no tener fotos mías...", "Kyousuke"),
    39: ("No es como que... me haga sentir solo.", "Kyousuke"),
    43: (".........", "Kyousuke"),
    44: ("Ah, ¡preocuparme así no me queda nada bien!", "Kyousuke"),
    45: ("...Supongo que le preguntaré a Mamá directamente mañana.", "Kyousuke"),
    52: ("Oye, Mamá. Hay algo que me gustaría preguntarte...", "Kyousuke"),
    53: ("¿No tienes fotos de mí de cuando era pequeño?", "Kyousuke"),
    54: ("¿Qué? Eso es bastante repentino.", "Yoshino"),
    55: ("No es realmente importante, pero estaba en mi mente, así que solo quería preguntar.", "Kyousuke"),
    56: ("No hay fotos tuyas, Kyousuke.", "Yoshino"),
    57: ("Eh, ¿no hay? ¿Ni siquiera una?", "Kyousuke"),
    58: ("Es porque nunca quisiste que te tomaran fotos.", "Yoshino"),
    59: ("......¿Es así?", "Kyousuke"),
    60: ("Así es. Cada vez que una cámara se apuntaba hacia ti, ¡siempre huías!", "Yoshino"),
    61: ("¿Hmm?", "Kyousuke"),
    64: ("En ese aspecto, aunque, Kirino siempre quería que le tomaran fotos, así que hay muchas fotos de ella...", "Yoshino"),
    65: ("Ahora que lo pienso, eso podría haber sido una señal de su potencial como modelo.", "Yoshino"),
    66: ("Sí, sí, qué padre consentidor eres.", "Kyousuke"),
    69: ("Oye, Papá. ¿Cómo era yo cuando era pequeño?", "Kyousuke"),
    70: ("¿Por qué preguntas eso ahora?", "Daisuke"),
    71: ("Estaba en mi mente.", "Kyousuke"),
    72: ("Eras un niño muy normal. Un niño extremadamente ordinario e inofensivo.", "Daisuke"),
    73: ("Heh...", "Kyousuke"),
    75: ("Eso no es lo que quise decir. ¿No parecía un «niño que reía mucho» o un «niño de mente rápida»?", "Kyousuke"),
    76: ("No.", "Daisuke"),
    78: ("Oye, oye, no recuerdo muy bien mi niñez...", "Kyousuke"),
    79: ("En serio quiero saber cómo era yo en ese entonces.", "Kyousuke"),
    80: ("......Ya veo.", "Daisuke"),
    81: ("¿«Ya veo»? ¿Eso es todo lo que tienes que decir?", "Kyousuke"),
    82: ("¿Te molesta?", "Daisuke"),
    83: ("Quiero saber porque me molesta.", "Kyousuke"),
    88: ("......Hmm.", "Daisuke"),
    89: ("De cualquier manera, pensé que te lo diría algún día.", "Daisuke"),
    90: ("...¿Sobre qué?", "Kyousuke"),
    91: ("Sobre ti, Kyousuke. Querías preguntar sobre ti, ¿verdad?", "Daisuke"),
    92: ("S-Sí...", "Kyousuke"),
    93: ("Tú eres...", "Daisuke"),
    95: ("Entonces, ¿no soy realmente tu hijo?", "Kyousuke"),
    96: ("......Así es.", "Daisuke"),
    97: ("Eres el hijo del hermano de tu madre.", "Daisuke"),
    99: ("...Pero, por ciertas razones, tomamos custodia de ti.", "Daisuke"),
    100: ("Ya veo...", "Kyousuke"),
    101: ("¿Entonces esa es la razón por la que mis recuerdos de cuando era pequeño son borrosos?", "Kyousuke"),
    102: ("...Terminemos aquí por hoy. No hay necesidad de que aprendas todo de una vez.", "Daisuke"),
    107: ("Querido... ¿Le dijiste a Kyousuke?", "Yoshino"),
    108: ("Pensé que era un buen momento para decírselo.", "Daisuke"),
    109: ("Ya veo...", "Yoshino"),
    110: ("Oye, Kyousuke. ¿Escucharás?", "Yoshino"),
    111: ("Es verdad que no eres nuestro hijo biológico. Pero...", "Yoshino"),
    112: ("Entiendo incluso si no lo dices.", "Kyousuke"),
    113: ("Tanto tú como Papá piensan en mí como su hijo de verdad......... ¿Verdad?", "Kyousuke"),
    114: ("Kyousuke...", "Yoshino"),
    115: ("Bueno, es impactante, ¿sabes? Que de repente me digan que no soy un hijo de esta familia.", "Kyousuke"),
    116: ("Incluso ahora no puedo ordenar la situación. Incluso siento que esto podría ser un sueño.", "Kyousuke"),
    117: ("Aun así, el hecho de que ustedes dos me hayan criado hasta ahora no cambiará en absoluto, así que...", "Kyousuke"),
    118: ("Estoy realmente agradecido con ustedes dos por haberme criado hasta hoy.", "Kyousuke"),
    119: ("...Hijo idiota. No es «hasta hoy».", "Daisuke"),
    120: ("Serás nuestro problemático hijo «siempre, de ahora en adelante también».", "Daisuke"),
    121: ("......¡Sí!", "Kyousuke"),
    128: ("Ah, qué calor... Tengo que tomar un poco de té de cebada...", "Kyousuke"),
    129: ("*glup*, *glup*, *glup*...", "Kyousuke"),
    130: ("*jadeo*...! Esto es realmente como debería ser el verano...!", "Kyousuke"),
    131: ("Ah...", "Kyousuke"),
    132: ("...¿Qué?", "Kirino"),
    133: ("No, no es nada.", "Kyousuke"),
    134: ("¿Es así? Entonces, ¿puedes morir?", "Kirino"),
    135: ("¡¿Por qué?! ¡¿Tengo que morir si no hago nada?!", "Kyousuke"),
    136: ("¿Crees que tienes algún valor en vivir?", "Kirino"),
    137: ("Ah, sí, sí. Soy yo el que está mal por estar aquí, ¿verdad? ¡Dios...!", "Kyousuke"),
    138: ("¡Haaaaaaaah...!", "Kyousuke"),
    139: ("¡Insooooportaabbleeeeeee!", "Kyousuke"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
entry = current.get("000scriptMGIM_0000.obj", {})
entry.update(build(n, s))
current["000scriptMGIM_0000.obj"] = entry
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptMGIM_0000.obj (part A)")