import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a106_n = {
    0: "Ruta de Kirino · Es Imposible Que Las Amigas De Mi Hermanita No Ayuden",
    2: "Es un mal hábito mío decir cosas impactantes cuando me dejo llevar por el momento.",
    3: "Además, sigo sin tener idea incluso después de devanarme los sesos durante toda la noche. Soy realmente lastimoso.",
    5: "Ni sus artículos otaku ni el tiempo que pasó con sus amigas pudieron restaurar sus recuerdos.",
    6: "¿Qué más puedo hacer?",
    8: "Si ella misma se rindiera también, sus recuerdos podrían desaparecer para siempre.",
    10: "No importa cuán trivial sea, realmente me gustaría algo de ayuda ahora mismo...",
    14: "...*suspiro*, no soy yo mismo.",
    15: "He estado privado de sueño recientemente por pensar demasiado. Pensaré en una solución después de dormir un poco.",
    17: "Ellas son diferentes de Ayase, ambas son las amigas otaku de Kirino...",
    18: "Si son ellas, estoy seguro de que darán una mano para que Kirino recupere sus aficiones otaku!",
    19: "Bueno, Kirino no recuerda a ninguna de las dos ahora mismo, y no pudo recordar nada después de mirar la sala de chat y las fotografías.",
    20: "Pero si se reunieran personalmente, ¡tal vez las cosas resulten diferente!",
    22: "Ya que he decidido eso, mejor contacto a Saori de inmediato.",
    24: "Es cierto que hay una posibilidad de que Kirino recupere sus recuerdos si hablara con las dos directamente.",
    25: "Pero, ¿está bien darles preocupaciones innecesarias solo por el bien de recuperar los recuerdos de Kirino?",
    26: "Además, la Kirino actual ni siquiera oculta su disgusto por los otakus, como se vio en su comportamiento anterior.",
    27: "Si la Kirino actual se reuniera con ellas, ¿qué haría si se encuentra con otakus tan descarados como ellas...?",
    29: "...¿Realmente está bien dejarlas reunirse?",
    30: "Sin embargo, no puedo simplemente dejarlo así, y no puedo pensar en ninguna otra idea mejor, eso es seguro.",
    31: "Además, ellas son las amigas cercanas de Kirino.",
    32: "¿Las palabras y actitud mezquinas de Kirino destruirán su amistad?",
    33: "Es cierto que son amigas cercanas.",
    34: "Pero, incluso si son amigas, no, porque son amigas, hay cosas que querrías ocultarles sin importar qué, ¿verdad?",
    35: "La manera en que Kirino oculta su afición otaku de las personas de su escuela es un ejemplo de eso.",
    36: "No es solo porque tiene miedo de ser excluida por sus amigas.",
    37: "Si se lo contara, terminaría lastimando a ambas partes, y por eso se mantiene callada al respecto.",
    38: "Entonces, ¿en quién debería apoyarse Kirino?",
    39: "No tenía amigas con quienes discutir sus aficiones otaku y tampoco podía consultar a nuestros padres.",
    40: "En esos momentos, la única en quien Kirino puede apoyarse es....",
    42: "Al final, cuidar de la hermanita es el trabajo del hermano mayor. Esto no tiene nada que ver con amor o amistad, es una obligación.",
    43: "Lo sabía desde hace un año, ¿no?",
    44: "Wow. Cuando me di cuenta de eso, me calmé de repente.",
    46: "Debe haber algo que pueda hacer como hermano mayor.",
    48: "Cierto, ¿no son también amigas valiosas? Es solo natural ayudarse mutuamente cuando se está en apuros.",
    49: "Ahora que he decidido eso, debería contactar primero a Saori.",
    55: "Saori es de hecho una persona asombrosa. O tiene buenas habilidades de adivinación, o es realmente observadora de las cosas que pasan a su alrededor.",
    56: "...No, no es solo eso.",
    57: "Probablemente ha estado constantemente preocupada por Kirino desde ese día en la sala de chat.",
    58: "Como pensé, hice bien en apoyarme en Saori.",
}
a106_s = {
    1: ("*suspiro*... Dije que hay «otras maneras», pero en realidad, no tengo ninguna idea en absoluto.", "Kyousuke"),
    4: ("Sin embargo, no hay más remedio...", "Kyousuke"),
    7: ("Si esto continúa, Kirino bien podría rendirse. Incluso en las mejores circunstancias, no hay pistas sobre cómo volverla a la normalidad.", "Kyousuke"),
    9: ("¿Hay algo... que aún no haya probado?", "Kyousuke"),
    11: ("No... un método tan vago no funcionará.", "Kyousuke"),
    12: ("Cualquier idea pretenciosa que se me ocurra en mi estado impaciente actual ciertamente no tendrá éxito.", "Kyousuke"),
    13: ("...Así es. Últimamente, me he estado excediendo demasiado.", "Kyousuke"),
    16: ("¡Así es! ¿Qué tal pedir ayuda a sus amigas otaku -- Kuroneko y Saori!", "Kyousuke"),
    21: ("Así es, es mejor hacer algo que no hacer nada.", "Kyousuke"),
    23: ("...Pero... ¿es esta realmente la única manera?", "Kyousuke"),
    28: ("No hay manera de que puedan salir adelante con el ambiente entre ellas de antes. No hay duda sobre ello.", "Kyousuke"),
    41: ("...Solo yo, ¿verdad?", "Kyousuke"),
    45: ("Solo un poco más, pensemos en ello solo un poco más.", "Kyousuke"),
    47: ("Tch... ¿Para qué estoy dudando?", "Kyousuke"),
    50: ("Hola. Soy Saori. ¡Ha pasado mucho tiempo, Kyousuke-shi!", "Saori"),
    51: ("Perdón por haberte llamado de repente. ¿Estás libre ahora mismo?", "Kyousuke"),
    52: ("Jaja, no necesitas ser tan formal entre nosotros, Kyousuke-shi. ¿Supongo que me llamas por el asunto del recuerdo de Kioto?", "Saori"),
    53: ("A-Aah, perdón, no es sobre eso... En realidad, tengo un favor que pedirte.", "Kyousuke"),
    54: ("...Por casualidad, ¿es sobre Kiririn-shi?", "Saori"),
}

a107_n = {
    0: "Ruta de Kirino · Es Imposible Que Las Amigas De Mi Hermanita No Ayuden",
    1: "Después de la escuela, llevé inmediatamente a Kirino a la estación de Akihabara.",
    2: "No estoy seguro si llegamos temprano, pero Saori y Kuroneko no se ven por ningún lado.",
    4: "Esta chica, está mirando alrededor como si fuera su primera vez aquí.",
    5: "Ahora que lo pienso... este también fue el lugar donde conocimos a Kuroneko y Saori por primera vez.",
    6: "Ooh, de alguna manera se siente que las cosas irán bien...",
    8: "...O no.",
    9: "¿Todo saldrá bien como está?",
    11: "En realidad, solo una minoría de otakus viste de esa manera. Pero como es raro, verlo deja un impacto muy fuerte.",
    18: "Bueno, es normal sorprenderse.",
    19: "Yo también escupí el agua que estaba bebiendo cuando nos conocimos por primera vez...",
    23: "Lo cual me recuerda, la casa de Saori está bastante lejos.",
    24: "Y aun así, aceptó reunirse una vez que la contacté. Realmente no soy rival para ella.",
    25: "Pero... la persona importante aquí, Kirino, estaba así, ¿eh?",
    29: "Esta Kirino... en realidad está mirando a Saori y Kuroneko como si fueran una especie rara.",
    43: "¡¿Uwah?! Sin demora, Kirino había entrado en su modo disgustado causado por la manera de hablar de Kuroneko!",
    48: "¿Qué pasa con esto...? Según este intercambio de argumentos, ¿no es lo mismo que antes...?",
    62: "O-Oye... no puede estar bromeando con lo que acaba de decir.",
    63: "Los ánimos de Saori están obviamente por los suelos, y los ojos de Kuroneko también están un poco húmedos.",
    66: "Tch... Esta chica, ¿sigue siendo obstinada?",
    67: "D-De todos modos, será malo a este paso si no hago seguimiento y revierto la situación!",
    71: "¿Q-Qué pasa? ¿Qué es ese extraño intercambio de miradas...? Más bien, ¿p-por qué sonrieron las dos tan de repente?",
    84: "¡¿Ooooooh?! Reconozco este ambiente.",
    85: "Terremotos, truenos, incendios, hermanitas, antes de cualquier desastre natural como esos, todo se detendrá así, y luego...",
    92: "T-Tú... acabas de pisar completamente una mina terrestre para Kuroneko.",
    93: "Incluso si tu propio libro fuera publicado, eso es demasiado...",
    96: "Es cierto que le mostré a Kirino la novela que Kuroneko escribió. Sin embargo, no le dije si era una novela profesional o una historia doujin amateur.",
    97: "Incluso si lo explicara, Kirino no lo habría entendido ya que no tiene conocimiento otaku.",
    106: "Kirino y Kuroneko empezaron una pelea de enamoradas.",
    107: "Este es un espectáculo bastante común, pero ha pasado mucho tiempo desde entonces, así que yo solo...",
    110: "¡Estas son lágrimas acumuladas por fatiga y estrés!",
    111: "Maldita sea, esa Saori... Sonrió traviesamente como si hubiera visto a través de todo...",
    112: "¿Eh...? ¿Visto a través de todo?",
    115: "Entonces no pongas una cara de «:3» y empieces a silbar.",
    121: "Sí, lo entiendo. Para la Kirino actual, esa frase está prohibida ya que niega su existencia.",
    122: "Sin embargo, no pude contenerlo.",
    127: "Grité mientras mis emociones se desbordaban.",
    128: "La cara de Kirino se puso pálida y no se movió como si el tiempo se hubiera detenido.",
    129: "Hmph, ya no me importa.",
    134: "Las dos estaban confundidas, mirando de Kirino a mí, pero eventualmente empezaron a caminar detrás de mí.",
    135: "Por un instante, vi a Kirino con sus ojos bajos en la esquina de mi visión. Sin embargo, no tengo la intención de detenerme.",
    136: "Al final, Kirino no vino a la cafetería de sirvientas.",
    139: "Maldición, ¿no es esto exactamente lo mismo que hace tres días?",
    140: "En otras palabras, no hay vuelta atrás de la catástrofe aquí debido a su personalidad deshonesta, ¿verdad?",
    141: "Dios mío, ¿qué debería hacer ahora?",
    142: "De alguna manera, necesito hacerles saber que lo que acaba de decir no son sus verdaderos sentimientos.",
    154: "Oooh, eso es Kuroneko para ti. Ha estado investigando cómo señalar las fallas de Kirino durante este último año.",
    166: "Kirino... No puedes ocultar tu sonrisa, como siempre.",
    167: "Sin embargo... Así es. Incluso si olvidara sus intereses otaku, Kirino sigue siendo Kirino. Mi hermanita.",
}
a107_s = {
    3: ("Jeh～, así que esto es Akihabara.", "Kirino"),
    7: ("Uwah, hay tantas personas como tú en grupos～", "Kirino"),
    10: ("¡Uwah! ¿No se está pasando esa persona? Ya pasó de moda cargar una mochila, y hay algo parecido a una vara sobresaliendo de ella...", "Kirino"),
    12: ("Sí, incluso yo creo que es demasiado...", "Kyousuke"),
    13: ("¡Kiririn-shi! ¡Kyousuke-shi! ¡Por aquí!", "Saori"),
    14: ("¡Espera, ¿Saori?!", "Kyousuke"),
    15: ("O-Oye... ¿No me digas que son el dúo del que me hablabas..?", "Kirino"),
    16: ("...Sí, la grande es Saori, y la negra es Kuroneko. Son tus amigas.", "Kyousuke"),
    17: ("Ick...", "Kirino"),
    20: ("Bueno, bueno, Kyousuke-shi. La situación esta vez parece bastante seria, ¿no es así?", "Saori"),
    21: ("Sí, ahora no puedo evitar pensar que naciste bajo la estrella de la calamidad.", "Kuroneko"),
    22: ("Perdón por eso, ustedes dos. Por hacerlas venir especialmente hasta aquí.", "Kyousuke"),
    26: ("...Cierto, esto es un sueño... Un mal sueño...", "Kirino"),
    27: ("Oye Kirino, vuelve a la realidad.", "Kyousuke"),
    28: ("...Uhh.", "Kirino"),
    30: ("D-Dime, Saori... Ahora mismo, Kirino...", "Kyousuke"),
    31: ("Jajaja, no tienes que terminar de decirlo, lo entiendo completamente, Kyousuke-shi.", "Saori"),
    32: ("...Saori.", "Kyousuke"),
    33: ("Bueno entonces, primero me presentaré ante Kiririn-shi. Soy Saori Bageena. ¿Sería mejor si digo «Mucho gusto»?", "Saori"),
    34: ("Y esta persona es...", "Saori"),
    35: ("Hmph, no es necesario dar mi nombre. Estoy segura de que ha escuchado mi nombre hace un momento.", "Kuroneko"),
    36: ("...", "Kirino"),
    37: ("N-No digas eso, estoy seguro de que entiendes lo que está pasando con Kirino por lo de Saori, ¿verdad?", "Kyousuke"),
    38: ("...No hay más remedio si «Nii-san» lo pone de esta manera.", "Kuroneko"),
    39: ("¿Nii-san～?", "Kirino"),
    40: ("¡O-Oye! ¡Tú, eso fue a propósito, ¿no?!", "Kyousuke"),
    41: ("Mi nombre es Kuroneko. Deberías grabar mi nombre en tu pequeña alma, para nunca volver a olvidarlo.", "Kuroneko"),
    42: ("¿Huh?", "Kirino"),
    44: ("Oye tú. ¿Podrías parar la tontería que has estado soltando desde el principio?", "Kirino"),
    45: ("Hmph... Al menos su boca sigue igual.", "Kuroneko"),
    46: ("En ese caso, ¿podrías también dejar de presumir ese notable estilo de fashionista tuyo? Akiba es el lugar equivocado para eso, eres una monstruosidad.", "Kuroneko"),
    47: ("¡¿Q-Qué estás diciendo?! ¡Esto es lo más moderno de este año...!", "Kirino"),
    49: ("Ya, ya, ustedes dos. Este no es el lugar para tener una pelea de enamorados. ¿Qué tal si vamos de inmediato a la cafetería de sirvientas que frecuentamos?", "Saori"),
    50: ("V-Vamos, Saori también lo dijo, así que ten un poco de autocontrol aquí, ¿de acuerdo? Apurémonos a la cafetería de sirvientas.", "Kyousuke"),
    51: ("......", "Kuroneko"),
    52: ("No... voy...", "Kirino"),
    53: ("O-Oye Kirino, ¿qué estás diciendo? ¡Todos se reunieron aquí solo por el bien de recuperar tus recuerdos, no hay significado si no estás presente!", "Kyousuke"),
    54: ("Pero ¿no es una cafetería de sirvientas un lugar donde los otakus asquerosos van y se reúnen para ver a las meseras vestidas con trajes de sirvienta?", "Kirino"),
    55: ("¿Cómo podría ir... a un lugar así?", "Kirino"),
    56: ("Kiririn-shi...", "Saori"),
    57: ("No importa si no deseas venir. ¿Vamos, «Nii-san»?", "Kuroneko"),
    58: ("¡No decidas eso por tu cuenta! ¡No quiero caminar junto con otakus tan asquerosos!", "Kirino"),
    59: ("Y también, lo diré ahora ya que hay una oportunidad, pero ¿saben ustedes dos lo prominentes que son?", "Kirino"),
    60: ("Para dejarlo claro, no creo que seamos amigas. Es una mala broma, ¿verdad?", "Kirino"),
    61: ("--?!", "Kyousuke"),
    64: ("Oye, para, Kirino. Estas dos están aquí hoy por tu bien.", "Kyousuke"),
    65: ("No es como si se los hubiera pedido. Más bien, ¿podrías avisarme con anticipación si vamos a reunirnos con gente así?", "Kirino"),
    68: ("D-Dime, Saori. Kirino está actualmente...", "Kyousuke"),
    69: ("...Entiendo, Kyousuke-shi.", "Saori"),
    70: ("¿Entiendes... qué exactamente?", "Kyousuke"),
    72: ("¿Q-Qué es tan gracioso?", "Kirino"),
    73: ("¿Gracioso? Cierto, todo sobre ti es simplemente risible.", "Kuroneko"),
    74: ("...¿Huh?", "Kirino"),
    75: ("¿Dijiste que has perdido tus recuerdos? Si vas a mentir, necesitarás inventar algo mejor que eso.", "Kuroneko"),
    76: ("Eres como una niña que se vendaría su propia muñeca sin razón. Solo quieres que los demás te hagan sentir especial, y se preocupen por ti. Por eso", "Kuroneko"),
    77: ("inventaste esta clase de escenario para tu propia terquedad, ¿verdad?", "Kuroneko"),
    78: ("Jaja, una espléndida Chuunibyou.", "Saori"),
    79: ("¡¿Qué están diciendo las dos?! Hablo en serio...", "Kirino"),
    80: ("No necesitas sentirte avergonzada, Kiririn-shi. Es algo que cualquiera puede tener, igual que el sarampión.", "Saori"),
    81: ("Sí, conozco tus sentimientos como la palma de mi mano. No puede ser solo «cualquiera», ¿verdad?", "Kuroneko"),
    82: ("Solo hay una persona de la que deseas que se vuelva y te mire... Ese debe ser tu hermano mayor al que amas demasiado, ¿verdad?", "Kuroneko"),
    83: ("¡¿Q-Qué...?!", "Kirino"),
    86: ("¡¿Q-Q-Q-Q-Q-Quién amaría a este tipo de chico?! ¡Tú, chica Chuunibyou de Jakigan-----------!", "Kirino"),
    87: ("¡C-C-C-C-Cóntrólate, Kirino----!", "Kyousuke"),
    88: ("¡Suéltame! ¡La voy a matar!", "Kirino"),
    89: ("O-Oye, ¡no digas algo tan peligroso frente a la estación! O-Oye, ¡no te resistas! ¡No me des codazos!", "Kyousuke"),
    90: ("¡Soltando tonterías justo cuando decido escuchar por un rato, ¿quién es una Chuunibyou?! ¡¿Quién es una niña?!", "Kirino"),
    91: ("¡Todo eso te describe claramente a ti! ¡Aunque eres una maldita escritora de medio pelo que solo puede escribir novelas Jakigan autocomplacientes!", "Kirino"),
    94: ("...Espera, oye. ¿Cómo supiste sobre la ambición de Kuroneko de ser novelista?", "Kyousuke"),
    95: ("¿Eh? Ah...", "Kirino"),
    98: ("Lo que significa...", "Kyousuke"),
    99: ("¿M-Mis... recuerdos... han vuelto...?", "Kirino"),
    100: ("E-E-E-E...", "Kyousuke"),
    101: ("¡Éxito-------!", "Kyousuke"),
    102: ("¡N-No abraces mi cabeza! Ahhh, basta, ¡suéltame!", "Kirino"),
    103: ("¿Oh cielos? ¿Entonces de verdad perdiste tus recuerdos? Realmente pensé que tenías sarampión.", "Kuroneko"),
    104: ("Un escenario como la pérdida de memoria es algo que solo humanos de mente superficial podrían haber inventado.", "Kuroneko"),
    105: ("¡C-Como dije, no me pongas junto con tu tontería de Jakigan!", "Kirino"),
    108: ("¿Eh, Kyousuke-shi? ¿Estás llorando?", "Saori"),
    109: ("¡C-Cállate!", "Kyousuke"),
    113: ("...Por casualidad, ¿estaban las dos poniendo un acto solo para enojar a Kirino...?", "Kyousuke"),
    114: ("¿Eh, realmente no sé de qué estás hablando...", "Saori"),
    116: ("Oye, ¿hablas en serio?", "Kyousuke"),
    117: ("¡E-Entonces, ¿cómo más podría haberlo dicho!", "Kirino"),
    118: ("...", "Kyousuke"),
    119: ("...La que está diciendo esto no es la verdadera Kirino.", "Kyousuke"),
    120: ("¿Huh? ¿Qué pasa con eso de la verdadera yo?", "Kirino"),
    123: ("Mi hermanita es alguien con una personalidad descarada y extremadamente irritante, les dice tranquilamente a las personas que mueran, pero...", "Kyousuke"),
    124: ("...Incluso así, no es una persona que lastime a sus amigas.", "Kyousuke"),
    125: ("...?!", "Kirino"),
    126: ("Por eso... la tú actual no es mi hermanita. Incluso si Papá o Mamá te reconocen, yo no te reconoceré.", "Kyousuke"),
    130: ("Kuroneko, Saori. Realmente lamento haberles pedido que me acompañaran hoy. Les invito en la cafetería de sirvientas.", "Kyousuke"),
    131: ("Kyousuke-shi...", "Saori"),
    132: ("¿Está bien esto?", "Kuroneko"),
    133: ("...No hay problema, vamos.", "Kyousuke"),
    137: ("¿Así es como la actual... cómo se siente realmente la «nueva tú»?", "Kyousuke"),
    138: ("¿T-Tienes algún problema con ello?", "Kirino"),
    143: ("...Por supuesto que tenemos un problema con ello. ¿Qué piensas de nosotras exactamente?", "Kuroneko"),
    144: ("¡¿Kuroneko?!", "Kyousuke"),
    145: ("¿Qué? ¿No dije que pienso en ustedes como otakus asquerosos?", "Kirino"),
    146: ("¿Asqueroso...? Huh. Entonces, me pregunto si podrías explicar qué parte es «asquerosa»?", "Kuroneko"),
    147: ("¿H-Huh? ¿Qué estás diciendo? ¡Diré que es asqueroso si siento que lo es!", "Kirino"),
    148: ("Ya veo. Defines todo fuera de tu sentido estético como «asqueroso». Es una opinión muy parecida a la de un troll sin cerebro en internet.", "Kuroneko"),
    149: ("¡¿Qué-?!", "Kirino"),
    150: ("Por esa definición, tu apariencia es «asquerosa» ante mis ojos. Rápidamente desvístete o simplemente sal de mi vista, ¿por qué no lo haces?", "Kuroneko"),
    151: ("¡T-Tú... eres la que debería hablar! ¡¿Quítate ese vestido negro sensual ahora mismo?! ¡Me hace sentir calor hasta el punto de morir solo con mirarte!", "Kirino"),
    152: ("Hmph, dijiste lo mismo la primera vez que nos conocimos. No solo tu vocabulario, hasta tu pensamiento es deficiente.", "Kuroneko"),
    153: ("¡¡Gggmmmmnnnnnggghhh!!", "Kirino"),
    155: ("...Sin embargo, no me disgusta esa parte de ti.", "Kuroneko"),
    156: ("...¿Eh...?", "Kirino"),
    157: ("Es bastante estimulante pelear contigo, y sobre todo es muy divertido verte explotar.", "Kuroneko"),
    158: ("Qu-Qué... Qué...", "Kirino"),
    159: ("Kuroneko... Tú...", "Kyousuke"),
    160: ("Parece que tu verdadera naturaleza no ha cambiado a pesar de perder tus recuerdos... Muy bien. Te reconoceré.", "Kuroneko"),
    161: ("...Es tal como ella dijo. Lo entendí después de mirar a las dos discutiendo.", "Saori"),
    162: ("La tú que no reconoce a los otakus sigue siendo tú. Solo has roto el caparazón conocido como tu yo y te has cambiado a ti misma...", "Kuroneko"),
    163: ("Kiririn-shi no cambió en absoluto. Sigue siendo nuestra amiga.", "Saori"),
    164: ("Ustedes dos...", "Kirino"),
    165: ("Tch... No estoy feliz de ser reconocida por otakus.", "Kirino"),
}

a109_n = {
    0: "Ruta de Kirino · Es Imposible Que Mi Hermanita Tenga Interés En El Comiket Ahora",
    2: "Colgando la llamada con Saori, guardé mi celular en el bolsillo.",
    3: "Hoy iremos al Comiket como se planeó anteriormente. La llamada era sobre pedirle a Kirino que viniera.",
    4: "Pero...",
    6: "Kirino se sentó en el sofá, leyendo su revista de moda con una mirada en blanco.",
    7: "Ha estado así desde ese incidente.",
    8: "Cuando nos encontramos en casa, no solo no nos hablamos, ni siquiera nos miramos las caras.",
    9: "Nuestra relación podría estar mucho peor que hace un año.",
    10: "Es claro que escuchó la conversación en el teléfono, sin embargo, trata de ignorarlo a propósito...",
    11: "Perdón... Saori, creo que es inútil invitarla en este estado.",
    12: "...¿Hmm? Siento que estoy siendo observado por alguien...?",
    14: "...Justo ahora... Por un momento, ¿los ojos de Kirino se encontraron con los míos?",
    15: "Por casualidad, ¿quiere ir al Comiket? ...Eso no puede ser.",
    16: "Pero ahora, podría ser por una falta de juicio de mi parte, pero Kirino parece tener una mirada solitaria en su cara.",
    17: "...Puede que haya cometido un error en algún lugar.",
    18: "Tales pensamientos cruzan por mi mente mientras estoy en la puerta principal.",
    19: "Pero, ya que la Kirino actual niega su amistad con Saori y Kuroneko, es imposible para mí reconocerla.",
    20: "Aun así, mi corazón todavía desea que nosotros los hermanos podamos divertirnos juntos con Saori y Kuroneko una vez más. Estoy seguro de que ella piensa lo mismo.",
    21: "Así que, Kirino. Algún día cuando tus recuerdos hayan vuelto, vamos al Comiket juntos otra vez.",
    22: "Mientras murmuraba tales pensamientos en mi mente, salí de la casa.",
}
a109_s = {
    1: ("Sí, entendido. Bueno entonces, te llamaré una vez que esté ahí.", "Kyousuke"),
    5: ("...", "Kirino"),
    13: ("...?!", "Kirino"),
}

a110_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo Esté Feliz De Ir A Una Cita Con Mi Hermanita",
    1: "Hoy es la ceremonia de clausura de la escuela.",
    2: "Las tan esperadas vacaciones de verano están aquí, después de un semestre de nada más que problemas.",
    3: "¡Oh! ¡Adiós a los días de restricciones y autocontrol! ¡Hola a los días de libertad e indulgencia!",
    4: "Y así, lo primero que hace mi yo animado es...",
    6: "Junto con mi hermanita amnésica, fuimos al punto caliente líder de Tokio, el distrito de Dogenzaka en Shibuya.",
    7: "*suspiro*... Soy un gran preocupón.",
    14: "Fuimos de la calle principal a los callejones más pequeños, donde las tiendas circundantes consisten en clubes y hoteles de apariencia dudosa a ambos lados, y el",
    15: "ambiente empezó a volverse sospechoso.",
    16: "En todo este mundo, la única persona que caminaría por estas calles sórdidas con su hermanita, no una, sino dos veces, soy yo.",
    39: "Estoy seguro de que incluso la Kirino actual entendería esos sentimientos.",
    40: "...Eso es porque, esta persona aquí es, sin duda, Kirino.",
}
a110_s = {
    5: ("Tch, ¿por qué debo ir a Shibuya contigo el primer día de las vacaciones de verano?", "Kirino"),
    8: ("No hay más remedio. Se tarda mucho en llegar aquí, y hoy es tu único día libre del trabajo donde tienes suficiente tiempo.", "Kyousuke"),
    9: ("En realidad, solo quieres mirar alrededor de Shibuya, ¿verdad?", "Kirino"),
    10: ("Y como es vergonzoso venir aquí solo, engañaste a tu hermanita para que viniera contigo. Realmente no tienes amigos, ¿verdad?", "Kirino"),
    11: ("No lo pongas como si yo fuera un pervertido solitario.", "Kyousuke"),
    12: ("Pero entonces, ¿para qué vinimos aquí? No puedes ser un chico guapo sin importar la ropa que uses, así que deberías simplemente rendirte en eso.", "Kirino"),
    13: ("...Ya me rendí en eso desde el momento en que nací. Ahora, solo deja de hablar y sígueme.", "Kyousuke"),
    17: ("Oye, ¿a dónde me llevas? Esta área es...", "Kirino"),
    18: ("Aquí estamos. Espérame.", "Kyousuke"),
    19: ("¿Eh? ¿Qué necesitas en una tienda de conveniencia...", "Kirino"),
    20: ("...Algunas cosas.", "Kyousuke"),
    21: ("Oye, perdón por hacerte esperar. Es bastante pesado.", "Kyousuke"),
    22: ("¿Huh? ¿Por qué compraste un cubo de agua...? Incluso si tienes sed, todavía hay un límite, ¿verdad?", "Kirino"),
    23: ("¿Esto? Hay... una razón para ello.", "Kyousuke"),
    24: ("...¿Eh?", "Kirino"),
    25: ("¡Idi... ¿Qué estás haciendo!?", "Kirino"),
    26: ("C-Cállate... Tú hiciste esto en el pasado también.", "Kyousuke"),
    27: ("¿Y-Yo...?", "Kirino"),
    28: ("Así es. Fue en la noche de la víspera de Navidad, justo en este lugar.", "Kyousuke"),
    29: ("¡¿C-Cómo pude haber hecho un acto tan tonto?! Definitivamente me resfriaría si hiciera eso durante el invierno.", "Kirino"),
    30: ("Ah, así es. ¿No te enviaron al hospital porque pescaste un espléndido resfriado?", "Kyousuke"),
    31: ("¡¿Qué-?!", "Kirino"),
    32: ("Todo fue para recolectar datos para tu novela. Mira, este libro...", "Kyousuke"),
    33: ("Este es el libro que dijiste que fue escrito por mí...", "Kirino"),
    34: ("Hay una escena en este libro donde el protagonista se reunió con Shiori-chan que estaba aprisionada por un trozo de escombros en medio de un fuerte aguacero.", "Kyousuke"),
    35: ("Dijiste que querías sentir cómo se sentía el protagonista entonces.", "Kyousuke"),
    36: ("...¡¿Qué-?!", "Kirino"),
    37: ("Honestamente, no entiendo completamente por qué irías tan lejos solo para escribir una novela.", "Kyousuke"),
    38: ("Sin embargo, así de seria estabas sobre escribir tu novela en ese momento.", "Kyousuke"),
}

a113_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo Esté Feliz De Ir A Una Cita Con Mi Hermanita - G",
    3: "Si estoy así de frío incluso durante el verano, entiendo por qué Kirino enfermó después de lo que hizo en esa noche de invierno.",
    4: "Más bien, Kirino tiene suerte de no haberse congelado hasta la muerte.",
}
a113_s = {
    1: ("...¿Realmente... hice eso?", "Kirino"),
    2: ("Sí. Ah～, hace frío.", "Kyousuke"),
    5: ("......", "Kirino"),
    6: ("¿Cómo está? ¿Recuerdas algo?", "Kyousuke"),
    7: ("No sé... ¿Recolecté algún otro dato?", "Kirino"),
    8: ("Sí, me ordenaste que me atropellara un auto en el cruce peatonal, luego te compré un accesorio de 30,000 yenes de una tienda departamental...", "Kyousuke"),
    9: ("Y por último, entramos juntos a ese hotel de ahí...¡¿*atragantado*?!", "Kyousuke"),
    10: ("T-Tú... ¿qué estás haciendo de repente...", "Kyousuke"),
    11: ("¡P-Pervertido! ¡Siscon! ¡Escoria humana!", "Kirino"),
    12: ("¿Q-Q-Qué hotel...? ¡No hables de tus propias ilusiones pervertidas con tu hermanita!", "Kirino"),
    13: ("No, no es una ilusión, es la escena donde el protagonista y un tipo llamado Toshi desarrollan una conexión entre sí en la novela...", "Kyousuke"),
    14: ("¡---?! ¡Eres lo peor!", "Kirino"),
    15: ("¡¿Otra falla-----?!", "Kyousuke"),
    16: ("¡Guwah!", "Kyousuke"),
    17: ("Siempre eres tan imprudente... ¡De verdad eres un idiota...!", "Kirino"),
}

data = {
    "000scriptBKIR_0106A.obj": build(a106_n, a106_s),
    "000scriptBKIR_0107A.obj": build(a107_n, a107_s),
    "000scriptBKIR_0109E.obj": build(a109_n, a109_s),
    "000scriptBKIR_0110A.obj": build(a110_n, a110_s),
    "000scriptBKIR_0113G.obj": build(a113_n, a113_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
