import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a54_n = {
    0: "Caminando De Puntillas",
    1: "Al final, ambos lados decidieron no ceder y tener un combate real.",
    2: "Porque Kuroneko---",
    4: "...es lo que dijo.",
    5: "Incluso si dijo eso, su habilidad es obviamente superior a la nuestra...",
    6: "Porque ellos no me tienen a mí.",
    7: "La habilidad virtuosa de Kuroneko puede estar cubriéndome, aún me falta toda habilidad de juego.",
    8: "Esto ciertamente será una batalla dura.",
    9: "Y conocen perfectamente el alcance de mis habilidades...",
    10: "Probablemente las dos se aliarán contra mí.",
    14: "Ya que conocemos las fortalezas de cada uno, es un hecho que centrarán sus ataques en mí.",
    15: "Por otro lado, ¿no podemos también predecir sus movimientos?",
    17: "Y así comenzó la gran batalla entre los cuatro--",
    18: "Cuando comenzó el combate, Kirino y Saori centraron sus ataques en mí como se predijo.",
    20: "A-Aunque lo sabía, su embestida es más feroz de lo que pensaba...",
    21: "Puede que no pueda durar los 60 segundos completos...",
    24: "¡E-Estas chicas...!",
    25: "¡Ya que normalmente se llevan bien, pueden cooperar...!",
    32: "Kuroneko me da consejos precisos mientras sigue de cerca a los personajes de Saori y Kirino.",
    33: "Kuroneko... Es increíble...",
    34: "Es como si controlara ambos personajes al mismo tiempo.",
    35: "Pero en realidad, todavía soy yo quien tiene que controlar el mío.",
    36: "Estamos casi a tiempo...",
    41: "Kirino introduce un comando complicado en su control, y en ese preciso momento--",
    47: "¡Los milagros realmente ocurren!",
    50: "«¡¡GANASTE!!» parpadea en la pantalla.",
    53: "Kirino miró en blanco la pantalla con los ojos atónitos.",
    54: "No, tampoco esperaba realmente ganar.",
    57: "El plan de Kuroneko tuvo éxito.",
    63: "Sea como sea, los milagros no ocurren tan seguido. Sobre todo, nos enfrentaremos a poderosos oponentes que pudieron llegar a las finales.",
    64: "Pero, bueno--",
}
a54_s = {
    3: ("No importa quién sea el oponente, lo que debemos hacer no cambia.", "Kuroneko"),
    11: ("...? Espera...", "Kyousuke"),
    12: ("¿Qué pasa?", "Kuroneko"),
    13: ("Se me acaba de ocurrir algo...", "Kyousuke"),
    16: ("Kuroneko... Creo que podríamos posiblemente ganar esta batalla.", "Kyousuke"),
    19: ("¡Ughh! ¡Mierda!", "Kyousuke"),
    22: ("¡Vamos!", "Kirino"),
    23: ("¡Kyousuke-shi! ¡Nadie va a encontrar tu cadáver!", "Saori"),
    26: ("...¡Ugh!!", "Kyousuke"),
    27: ("Mueve la palanca para escapar.", "Kuroneko"),
    28: ("¡O-Ok!", "Kyousuke"),
    29: ("¡Kyousuke-shi, no te lo permitiré!", "Saori"),
    30: ("Defiéndete.", "Kuroneko"),
    31: ("¡¿A-Así?!", "Kyousuke"),
    37: ("¡Guah!!", "Kyousuke"),
    38: ("¡Está acorralado!", "Kirino"),
    39: ("¡N-No puedo escapar!", "Kyousuke"),
    40: ("¡¡Este combate es nuestro!!", "Kirino"),
    42: ("...Hmph.", "Kuroneko"),
    43: ("¡?!", "Kirino"),
    44: ("Estaba esperando esto.", "Kuroneko"),
    45: ("...¿Eh??", "Kirino"),
    46: ("Solo un minuto. ¿Tuviste una pesadilla?", "Kuroneko"),
    48: ("¡No puede ser! ¡¿Hablas en serio?!", "Kirino"),
    49: ("No puede ser, esto es bastante...", "Saori"),
    51: ("¿G-Ganamos...?", "Kyousuke"),
    52: ("Es tal como lo ves.", "Kuroneko"),
    55: ("Sabía que tu hermana usaría esta técnica como golpe final.", "Kuroneko"),
    56: ("Quería ganar usando su técnica más llamativa frente al gran público. Así es el camino de esa chica que busca atención.", "Kuroneko"),
    58: ("Vaya vaya, ciertamente fue un juego reñido.", "Saori"),
    59: ("Será mejor que ganen esto.", "Kirino"),
    60: ("Oye oye, Kirino, no nos presiones.", "Kyousuke"),
    61: ("Nada de eso, ¡una victoria completa! No aceptaré nada menos.", "Kirino"),
    62: ("Entendido.", "Kyousuke"),
    65: ("¡Después de llegar tan lejos, no tenemos más opción que hacerlo!", "Kyousuke"),
}

a56_n = {
    0: "Caminando De Puntillas",
    37: "Ella... lo hizo para calmarme...",
    41: "N-No puedo negarlo.",
}
a56_s = {
    1: ("¿Tienes un momento?", "Kuroneko"),
    2: ("¿Hmm? ¿Qué pasa? Justo cuando por fin estaba en el ánimo.", "Kyousuke"),
    3: ("«No tenemos más opción que hacerlo»... es lo que dijiste hace un momento, ¿cierto?", "Kuroneko"),
    4: ("¡Sí! ¿Hay algo malo en eso?", "Kyousuke"),
    5: ("Pero tus piernas están temblando.", "Kuroneko"),
    6: ("¡Gah! E-Esta es la emoción previa a la batalla!", "Kyousuke"),
    7: ("¿Será que piensas que no podemos ganar?", "Kuroneko"),
    8: ("Je, ¡no voy a acobardarme después de llegar tan lejos!", "Kyousuke"),
    9: ("Eso es lo que espero.", "Kuroneko"),
    10: ("Eso es una exageración...", "Kyousuke"),
    11: ("Hm... Simplemente medí tu confianza.", "Kuroneko"),
    12: ("De todos modos, ¿soy una carga?", "Kyousuke"),
    13: ("Sí.", "Kuroneko"),
    14: ("¡Eso es demasiado directo! ¡Sé un poco más delicada!", "Kyousuke"),
    15: ("No hay necesidad de eso, sabe que creo en ti.", "Kuroneko"),
    16: ("Jaja. Bueno, supongo que es verdad.", "Kyousuke"),
    17: ("Eres ciertamente una carga, pero eso es todo.", "Kuroneko"),
    18: ("¿Hm? ¿Qué quieres decir con eso?", "Kyousuke"),
    19: ("Este nivel de desventaja es perfecto.", "Kuroneko"),
    20: ("¡No digas que soy una desventaja!", "Kyousuke"),
    21: ("...Desventaja.", "Kuroneko"),
    22: ("¡No digas que soy una desventaja!", "Kyousuke"),
    23: ("¡No soy para nada así--!", "Kyousuke"),
    24: ("...Además, parece que estás bastante segura.", "Kyousuke"),
    25: ("En un combate, el que piensa en la derrota antes de que empiece va a perder.", "Kuroneko"),
    26: ("...Kuroneko.", "Kyousuke"),
    27: ("Si te falta confianza, escóndete detrás de mí.", "Kuroneko"),
    28: ("O-Okay...", "Kyousuke"),
    29: ("Entonces 'estabas' pensando en la derrota.", "Kuroneko"),
    30: ("¡No te burles de mí!", "Kyousuke"),
    31: ("¡Yo también puedo hacer cosas cuando es necesario!", "Kyousuke"),
    32: ("Eso espero.", "Kuroneko"),
    33: ("¡No me tomes por tonto! ¡He pasado por entrenamiento después de todo!", "Kyousuke"),
    34: ("¡No puedo perder cuando hemos llegado tan lejos!", "Kyousuke"),
    35: ("...Je, sin darte cuenta tus piernas dejaron de temblar.", "Kuroneko"),
    36: ("¿Eh?", "Kyousuke"),
    38: ("...¿Puedes hacerlo?", "Kuroneko"),
    39: ("Ah, sí... No hay problema. ¡Vamos, Kuroneko!", "Kyousuke"),
    40: ("...Sí.", "Kuroneko"),
    42: ("Lo diré ahora.", "Kuroneko"),
    43: ("¿Q-Qué es?", "Kyousuke"),
    44: ("En el campo de batalla, no hay «buen esfuerzo», solo ganadores y perdedores.", "Kuroneko"),
    45: ("No es «tengo que ganar» o «quiero ganar». Es «gano». ¿Entiendes?", "Kuroneko"),
    46: ("S-Sí...", "Kyousuke"),
    47: ("Puedo pelear cubriéndote; aún así ganaremos.", "Kuroneko"),
    48: ("¿D-D-de dónde sale esta confianza?", "Kyousuke"),
    49: ("Siento lástima por tu falta de confianza.", "Kuroneko"),
    50: ("Ugh...", "Kyousuke"),
    51: ("Por eso, esa hermana tuya siempre sale con la suya.", "Kuroneko"),
    52: ("......", "Kyousuke"),
    53: ("Qué lamentable.", "Kuroneko"),
    54: ("¡Cállate! ¡Me estás haciendo perder más confianza!", "Kyousuke"),
    55: ("Entonces, ¿vamos?", "Kuroneko"),
    56: ("¡S-Sí!", "Kyousuke"),
}

a58_n = {
    0: "Creer En La Victoria",
    3: "¿Hmm? ¿Será que ella...",
    4: "No solo me lo está diciendo a mí, ¿será que lo dice para aliviar su propio estrés?",
    5: "Es comprensible. Incluso para Kuroneko, no hay forma de no estar nerviosa una vez que llegas tan lejos.",
    6: "Le demostraré que yo también puedo ser confiable.",
    13: "Kuroneko es muy confiable una vez que se pone así.",
    26: "Escuché esa línea antes.",
    27: "Llevas la responsabilidad de ganar después de derrotar a tus anteriores enemigos.",
    28: "Esta chica... Siempre ha sido así.",
    35: "Para una chica que no suele ser honesta, ¡llegó tan lejos!",
    39: "¡Nuestro objetivo no es nada más que la victoria!",
}
a58_s = {
    1: ("Mientras des todo de ti, no perderemos.", "Kuroneko"),
    2: ("Sin embargo, no olvides que un solo momento de negligencia puede ser fatal.", "Kuroneko"),
    7: ("Gracias, Kuroneko.", "Kyousuke"),
    8: ("¿Por qué expresas tu gratitud...?", "Kuroneko"),
    9: ("Está bien si no sabes por qué.", "Kyousuke"),
    10: ("De todos modos, gracias.", "Kyousuke"),
    11: ("¡Kuroneko, de algún modo me estoy emocionando de repente!", "Kyousuke"),
    12: ("Por favor, no digas lo obvio.", "Kuroneko"),
    14: ("¡Perdón por hacerlos esperar a ambos!", "Saori"),
    15: ("¿Qué pasa, Saori?", "Kyousuke"),
    16: ("Por lo que se ve, ¡los oponentes que enfrentarán en las finales están firmemente rankeados en el top 10 nacional!", "Saori"),
    17: ("¡¿Q-Qué dijiste?!", "Kyousuke"),
    18: ("En otras palabras, digo que tus oponentes son dos personas al nivel de Kuroneko.", "Saori"),
    19: ("¿S-Serio...?", "Kyousuke"),
    20: ("¿Cómo es posible ganarle a tales oponentes...?", "Kyousuke"),
    21: ("¡Espíritu de lucha!", "Kirino"),
    22: ("...¿Espíritu de lucha?", "Kyousuke"),
    23: ("Eso es correcto. ¡Gana con tu espíritu de lucha!", "Kirino"),
    24: ("¡Ya que nos vencieron, definitivamente tienen que ganar!", "Kirino"),
    25: ("¡?!", "Kyousuke"),
    29: ("Gracias, Kirino. Gracias a ti, hicimos un avance. ¿No es así, Kuroneko?", "Kyousuke"),
    30: ("«Perder no es una opción, por lo tanto debemos ganar». Esa lógica irrazonable es muy tuya.", "Kuroneko"),
    31: ("Pero... no me desagrada particularmente.", "Kuroneko"),
    32: ("No es que lo esté haciendo por ustedes dos...", "Kirino"),
    33: ("Solo estoy animándolos; ¡me enojaré si pierden!", "Kirino"),
    34: ("Kirino...", "Kyousuke"),
    36: ("¡Con esto, solo podemos lograr una victoria completa!", "Kyousuke"),
    37: ("No tienes que decírmelo. Simplemente disfruta mi hermosa masacre desde tu asiento VIP.", "Kuroneko"),
    38: ("¡Okay! ¡Vamos con nuestro espíritu de lucha!", "Kyousuke"),
}

a61_n = {
    0: "Después Del Torneo",
    1: "Aunque estábamos entusiasmados y animados para las finales, lamentablemente perdimos.",
    2: "Estábamos demasiado avergonzados para enfrentar a Kirino... Incluso Kuroneko se mordió los labios por la frustración.",
    11: "Kirino levantó un papel de color con la firma de la seiyuu.",
    14: "Saori sostenía un artbook de edición limitada de Siscaly y parecía muy feliz.",
    15: "Aunque no logramos la victoria completa... esto, bueno, es suficiente.",
    16: "Mirando a mi hermana eufórica y a sus amigas, mi corazón se estaba calentando.",
}
a61_s = {
    3: ("Apestan.", "Kirino"),
    4: ("Lo siento...", "Kyousuke"),
    5: ("No pondré excusas, así que adelante, regáñame.", "Kuroneko"),
    6: ("Oh, bueno.", "Kirino"),
    7: ("...¿Eh?", "Kuroneko"),
    8: ("Para ustedes dos... No estuvo mal.", "Kirino"),
    9: ("¿Qué acabas de decir...?", "Kuroneko"),
    10: ("¡N-Nada! Además de eso, ¡mira esto! ¡El premio del subcampeón!", "Kirino"),
    12: ("Jeje... ¡Realmente quería esto!", "Kirino"),
    13: ("Aunque nos perdimos la victoria, el premio del segundo lugar también es espléndido.", "Saori"),
    17: ("...Oye.", "Kirino"),
    18: ("¿Hmm? ¿Qué pasa?", "Kyousuke"),
    19: ("......Gracias.", "Kirino"),
    20: ("...Sí.", "Kyousuke"),
}

a62_n = {
    0: "La Habilidad de Kuroneko",
    4: "Sin embargo... La pareja fue realmente mala.",
    5: "La «pareja» en cuestión es obviamente su compañera de equipo...",
    8: "En las finales también, Kuroneko estaba prácticamente ilesa.",
    9: "No llegaría a su nivel ni aunque practicara toda mi vida.",
    10: "Y no es que fuera tan lejos para dominar solo un juego de todos modos.",
    17: "¿Nada...? Entonces ¿por qué pone esa cara?",
    18: "Está un poco agitada...",
    19: "Tengo que hacer algo para evitar a dónde va esta conversación.",
    20: "Un tema que podría redirigir la conversación sería...",
    26: "No lo entiendo. ¿Alma? ¿Fusionada con tu cuerpo? ¿Qué es eso?",
    35: "Caminando junto a Kuroneko...",
    36: "Kirino jugaba con su teléfono mientras refunfuñaba.",
    37: "Y justo al lado estaba Saori consolando a Kirino con una sonrisa burlona.",
    55: "Me quedo sin palabras.",
    59: "Ella debe estar realmente amargada por esta derrota...",
    60: "Porque tiene tanto orgullo...",
    66: "Esto es difícil... No sé qué decir.",
}
a62_s = {
    1: ("Vaya, vaya... Pero sabes...", "Saori"),
    2: ("Kuroneko-shi fue de verdad asombrosa.", "Saori"),
    3: ("Los espectadores incluso la aplaudieron algunas veces.", "Saori"),
    6: ("No es particularmente tu culpa.", "Kuroneko"),
    7: ("No, me siento muy mal por eso.", "Kyousuke"),
    11: ("Como pensé, no puedo seguirte el ritmo.", "Kyousuke"),
    12: ("...¿Eh?", "Kuroneko"),
    13: ("¿Hmm? ¿Qué pasa?", "Kyousuke"),
    14: ("......", "Kuroneko"),
    15: ("...¿Kuroneko?", "Kyousuke"),
    16: ("No es nada.", "Kuroneko"),
    21: ("T-Todavía, ¡me alegro por ti! Ese premio exclusivo es bastante raro, ¿no?", "Kyousuke"),
    22: ("...Si lo quieres, puedo dártelo.", "Kuroneko"),
    23: ("Oye oye, ¿de verdad estás bien con eso? Lo querías, ¿cierto?", "Kyousuke"),
    24: ("Tu alma atada ya se ha fusionado con mi cuerpo.", "Kuroneko"),
    25: ("¿Eh?", "Kyousuke"),
    27: ("¿Qué pasa? ¿No lo aceptas?", "Kuroneko"),
    28: ("No, no. No puedo aceptarlo. Aunque estés decepcionada por el resultado, aun así lo ganaste.", "Kyousuke"),
    29: ("¿Es así?", "Kuroneko"),
    30: ("Además, se convertiría en de Kirino si lo tomara.", "Kyousuke"),
    31: ("...¿Porque eres un siscon?", "Kuroneko"),
    32: ("Obviamente no.", "Kyousuke"),
    33: ("...Je, entonces solo acéptalo con gracia.", "Kuroneko"),
    34: ("No, es tuyo.", "Kyousuke"),
    38: ("Sabes...", "Kyousuke"),
    39: ("¿Hay algo más?", "Kuroneko"),
    40: ("Al final, ¿por qué participaste en el torneo? Estabas claramente peleando con Kirino antes.", "Kyousuke"),
    41: ("...En efecto, me pregunto por qué.", "Kuroneko"),
    42: ("¿Te preguntas por qué...? Tú...", "Kyousuke"),
    43: ("Por improbable que sea, podría ser que despertaste mi interés.", "Kuroneko"),
    44: ("Sentí que participar en este torneo contigo podría ser bastante interesante...", "Kuroneko"),
    45: ("Eso... Quieres decir--", "Kyousuke"),
    46: ("¿Y tú? ¿Por qué participaste en este torneo?", "Kuroneko"),
    47: ("¿Eh? Porque sin mí, no habrían podido formar dos equipos.", "Kyousuke"),
    48: ("No me refiero a eso, estos artículos claramente no tienen significado para ti... Para empezar, tampoco estabas muy interesado en esto, ¿cierto?", "Kuroneko"),
    49: ("Bueno, sí, pero estaban contando conmigo.", "Kyousuke"),
    50: ("...Dios mío. ¿Debería llamarte de buen corazón o simplemente idiota?", "Kuroneko"),
    51: ("¿Qué quieres decir con eso?", "Kyousuke"),
    52: ("Eres realmente un siscon al final.", "Kuroneko"),
    53: ("¡Gah!! ¡¿Todavía estás diciendo eso?! ¡Te dije que no lo soy!", "Kyousuke"),
    54: ("Jeje, es una broma, solo una broma.", "Kuroneko"),
    56: ("¿Qué pasa, Kuroneko?", "Kyousuke"),
    57: ("Nada...", "Kuroneko"),
    58: ("Nada, dices...", "Kyousuke"),
    61: ("Lo siento, terminé arrastrándote hacia abajo...", "Kyousuke"),
    62: ("Mi poder mágico simplemente no fue suficiente.", "Kuroneko"),
    63: ("Incluso si dices eso...", "Kyousuke"),
    64: ("Por favor, solo detente. Escuchar tus disculpas es una deshonra innecesaria.", "Kuroneko"),
    65: ("Ya veo...", "Kyousuke"),
    67: ("Lo siento.", "Kyousuke"),
    68: ("...Eres persistente.", "Kuroneko"),
    69: ("Gracias.", "Kyousuke"),
    70: (".....Je.", "Kuroneko"),
    71: ("...Yo también, me he divertido mucho.", "Kuroneko"),
    72: ("Gracias... Senpai.", "Kuroneko"),
}

data = {
    "000scriptAKYO_0054A.obj": build(a54_n, a54_s),
    "000scriptAKYO_0056T.obj": build(a56_n, a56_s),
    "000scriptAKYO_0058A.obj": build(a58_n, a58_s),
    "000scriptAKYO_0061A.obj": build(a61_n, a61_s),
    "000scriptAKYO_0062A.obj": build(a62_n, a62_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))