import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

T = "Ruta de Kanako"

n = {
    0: T,
    1: "La siguiente orden de Kanako fue...",
    2: "Que me convirtiera en su manager otra vez y la ayudara en su actuación en el escenario.",
    3: "Por cierto, Kanako se está cambiando de ropa ahora mismo.",
    4: "...En serio, esto se está volviendo bastante raro.",
    5: "¿Por qué estoy en un lugar así, esperando que «la amiga de mi hermana» termine de cambiarse...",
    6: "Me aburrí de esperar, así que empecé a hablar con Kanako mientras se cambiaba de ropa.",
    26: "¿Por qué se está enojando?",
    29: "Hmmm～",
    37: "Kanako se acercó lentamente para presumir todo su cuerpo.",
    39: "¿Cómo pudo hacer algo así vistiendo ropa tan erótica?",
    40: "Por eso dije que es una mocosa.",
    42: "En su caso, no hay nada de sentido de erotismo, pero...",
    43: "Si alguien viera esta escena, seguramente habría un enorme malentendido.",
    56: "Intercambiamos choques de palmas emocionados.",
    88: "...¿Cómo es posible...? Definitivamente no se supone que sea un lolicon!",
    89: "¡Maldición! ¡¿Pero por qué mi corazón late más rápido cuando Kanako se acerca...?!",
    96: "¿Qué es este extraño silencio...",
    125: "Por la súbita confesión, mi cerebro, sin dar ni un giro, llegó al punto de ebullición.",
    126: "Las sinceras palabras que se derramaron de la boca de Kanako hicieron que mi corazón se derritiera.",
    137: "...Parece que después de todo me he convertido en un maldito lolicon serio.",
    138: "Mientras miro el rostro tímido y completamente rojo de Kanako,",
    139: "no puedo evitar pensar...",
    140: "......La amiga de mi hermanita no puede ser tan linda.",
}
s = {
    7: ("Oye.", "Kyousuke"),
    8: ("¿Qué es?", "Kanako"),
    9: ("¿Por qué me llamaste?", "Kyousuke"),
    10: ("Deberías saber bien que soy completamente inútil.", "Kyousuke"),
    11: ("Eso no es verdad.", "Kanako"),
    12: ("¿Oh?", "Kyousuke"),
    13: ("Cuando no estabas aquí, hice algunas actuaciones, pero.", "Kanako"),
    14: ("...Es mejor cuando estás aquí.", "Kanako"),
    15: ("...Gracias.", "Kyousuke"),
    16: ("Hablando de eso, esta es la segunda vez este mes que haces una actuación de Meruru.", "Kyousuke"),
    17: ("Sip, una nueva serie está comenzando o algo.", "Kanako"),
    18: ("¿Oh?", "Kyousuke"),
    19: ("¿Bridget está aquí contigo?", "Kyousuke"),
    20: ("Está aquí, en la sala de espera de al lado.", "Kanako"),
    21: ("¿Por qué hay salas de espera separadas?", "Kyousuke"),
    22: ("No sé.", "Kanako"),
    23: ("Hmm... ¿No es extraño? Ustedes dos siempre estaban juntas hasta ahora.", "Kyousuke"),
    24: ("...Eres tan ruidoso. No importa, ¿no?", "Kanako"),
    25: ("¿Quieres conocer a Bridget tanto? Después de todo, eres un lolicon.", "Kanako"),
    27: ("Está bien, terminé.", "Kanako"),
    28: ("¡Tadah! ¿Cómo está?", "Kanako"),
    30: ("Eres la persona más adecuada para ese atuendo en todo el mundo.", "Kyousuke"),
    31: ("Más o menos～. Jeje... No me elogies tanto～, me daré vergüenza.", "Kanako"),
    32: ("Aunque Meruru es una estudiante de primaria.", "Kyousuke"),
    33: ("Oye.", "Kanako"),
    34: ("A pesar de cómo se ve, ¡en realidad he crecido!", "Kanako"),
    35: ("¿Dónde has crecido?", "Kyousuke"),
    36: ("¿Qué...? M-Mira cuidadosamente, aquí.", "Kanako"),
    38: ("Mira.", "Kanako"),
    41: ("Mira.", "Kanako"),
    44: ("Deja esto ya... ¿Oh?", "Kyousuke"),
    45: ("...Y-Tú.", "Kyousuke"),
    46: ("¿?", "Kanako"),
    47: ("Tus senos han crecido, ¿no?", "Kyousuke"),
    48: ("¿Eh? ¡¿En serio?!", "Kanako"),
    49: ("Sí, solo un poquito.", "Kyousuke"),
    50: ("¡¡Yaaaaaaaaaaaay!!", "Kanako"),
    51: ("¡¡El poder de la leche es INCREÍBLE!! ¡Sí, sí...!", "Kanako"),
    52: ("Aquí es donde comienza el estirón de crecimiento de Kanako... Jaja♪ Solo observen chicos, jejeje.", "Kanako"),
    53: ("¿No es genial?", "Kyousuke"),
    54: ("¡Sí!", "Kanako"),
    55: ("¡Oye!", "Ambos"),
    57: ("Estoy tan feliz... Jaja♪ Bueno, aunque todavía es... pequeño...", "Kanako"),
    58: ("¡¿Ah?!", "Kanako"),
    59: ("～～～～～～", "Kanako"),
    60: ("¡¿A-dónde estás mirando, maldito?!", "Kanako"),
    61: ("Tus senos.", "Kyousuke"),
    62: ("¡No lo digas tan bruscamente! ¡Lolicon!", "Kanako"),
    63: ("¿A quién estás acusando de ser lolicon?", "Kyousuke"),
    64: ("No tengo ningún interés en chicas planas.", "Kyousuke"),
    65: ("...Qué-", "Kanako"),
    66: ("...¿Acabas de decir eso?", "Kanako"),
    67: ("¿Y qué si lo dije?", "Kyousuke"),
    68: ("Hmm～～～", "Kanako"),
    69: ("¿Q-Qué es?", "Kyousuke"),
    70: ("Bueno entonces, confirmaré si es verdad o no.", "Kanako"),
    71: ("Préstame tu mano.", "Kanako"),
    72: ("¿Huh?", "Kyousuke"),
    73: ("Solo hazlo.", "Kanako"),
    74: ("E-Oye.", "Kyousuke"),
    75: ("¿Qué...", "Kyousuke"),
    76: ("¿D-Dónde me estás haciendo tocar, tú......?!", "Kyousuke"),
    77: ("Jeje, te sacudiste, ¿no?", "Kanako"),
    78: ("...gah... tú... haciendo esto...", "Kyousuke"),
    79: ("No tienes ningún interés en una chica loli como yo, ¿verdad?", "Kanako"),
    80: ("¿O eres realmente un lolicon?", "Kanako"),
    81: ("¡N-No lo soy!", "Kyousuke"),
    82: ("Entonces no hay problema.", "Kanako"),
    83: ("Ufufu①", "Kanako"),
    84: ("N-No te acerques.", "Kyousuke"),
    85: ("¿Eh～? ¿Por qué～?", "Kanako"),
    86: ("Oye... Kyousuke... ¿Me odias?", "Kanako"),
    87: ("...?! N-No me molestes.", "Kyousuke"),
    90: ("Estás demasiado cerca... demasiado cerca...!!", "Kyousuke"),
    91: ("Quiero estar cerca.", "Kanako"),
    92: ("...Tu cara está roja, ¿sabes?", "Kanako"),
    93: ("Y-Tú también...", "Kyousuke"),
    94: ("..................", "Kanako"),
    95: ("..................", "Kyousuke"),
    97: ("...*gulp*", "Kyousuke"),
    98: ("Pfft.", "Kanako"),
    99: ("¡Kyahahahaha!", "Kanako"),
    100: ("...¿Eh?", "Kyousuke"),
    101: ("¿Qué es esa cara? ¿Te lo tomaste en serio?", "Kanako"),
    102: ("Poniéndote así de nervioso, eres tan lindo♪ ¿Eres realmente un lolicon después de todo?", "Kanako"),
    103: ("¡¿Guh...?!", "Kyousuke"),
    104: ("¡Y-Tú...! ¡Tú...! ¡Ya basta...!", "Kyousuke"),
    105: ("¡?!", "Ambos"),
    106: ("Kanakana-chan, ya es hora de subir al escenario... Eh...", "Bridget"),
    107: ("¡¿Eeeeeeeeh?!", "Bridget"),
    108: ("Estoy ocupada en este momento, así que espérame un poco.", "Kanako"),
    109: ("B-Bridget-chan... No es lo que parece; ¡hay una explicación para esto...?!", "Kyousuke"),
    110: ("¡S-Lo siento!!!", "Bridget"),
    111: ("..................", "Kanako"),
    112: ("..................", "Kyousuke"),
    113: ("¡Oye! ¡Levántate! Si no la perseguimos, ¡definitivamente habrá un malentendido!", "Kyousuke"),
    114: ("No importa, déjala malinterpretar.", "Kanako"),
    115: ("¿Huh?", "Kyousuke"),
    116: ("Mejor aún, ¿qué tal hacerlo de verdad?", "Kanako"),
    117: ("...Ups, lo hice.", "Kanako"),
    118: ("T-Tú... tú...", "Kyousuke"),
    119: ("...Sabes...", "Kanako"),
    120: ("...Las cosas que pasaron antes, lo que acaba de pasar... Puede que hayas pensado que te estaba molestando todo el tiempo.", "Kanako"),
    121: ("Porque soy una idiota.", "Kanako"),
    122: ("No puedo hacer ese tipo de cosas.", "Kanako"),
    123: ("Todo fue real.", "Kanako"),
    124: ("...Te amo, Kyousuke.", "Kanako"),
    127: ("...¿Recuerdas cuando nos conocimos?", "Kanako"),
    128: ("...Se sintió como el peor encuentro posible.", "Kyousuke"),
    129: ("Jeje... Eso es verdad.", "Kanako"),
    130: ("Dijiste cosas terribles como que soy común, y que parecía que sería jefe de sección en una pequeña empresa en diez años.", "Kyousuke"),
    131: ("Todavía siento lo mismo ahora.", "Kanako"),
    132: ("¿Entonces?", "Kyousuke"),
    133: ("...No hay remedio.", "Kanako"),
    134: ("Cómo resultó así... Realmente no lo sé.", "Kanako"),
    135: ("Porque te amo.", "Kanako"),
    136: ("----", "Kyousuke"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
current["000scriptKIFK_0003E.obj"] = build(n, s)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptKIFK_0003E.obj")