import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

n = {
    371: "Bueno, hagámoslo así.",
    378: "Kirino sacó su teléfono en silencio y luego me lo pasó.",
    379: "Miré la pantalla de su teléfono decorado y brillante.",
    380: "Había un correo similar al que Saori me mostró.",
    381: "«Si sigues juntándote con tus amigas, ellas se encontrarán en peligro.»",
    382: "«Si te importan tus amigas, deja de reunirte con ellas.»",
    396: "Bueno, no entiendo esta situación.",
    397: "Cómo debería manejar este problema...",
    398: "Después de conocer la situación del correo, los correos amenazantes continuaron atormentando a Kirino.",
    399: "Cambiar las direcciones de correo no funcionó.",
    400: "Usar sub-direcciones tampoco funcionó.",
    401: "Es completamente desconcertante cómo se filtran las direcciones de correo.",
    402: "Los correos amenazantes fluían persistentemente.",
    404: "El flujo continuo de correos amenazantes está empezando a quebrar a Kirino.",
    405: "Me parece que estos correos amenazantes no se detendrán pronto.",
    406: "Aunque normalmente tiene su teléfono a su lado, ahora ni siquiera quiere estar cerca de él.",
    412: "Tomo el teléfono que suena de sus manos y miro la pantalla.",
    413: "Dice «Tienes un correo».",
    414: "Al ver eso, mis cejas se levantan naturalmente.",
    427: "...Esto pasa cada vez que llega otro correo.",
    428: "Cada vez que llega un correo nuevo, cambia su dirección e inmediatamente les dice a sus amigas.",
    429: "Pero nada se resolverá si seguimos repitiendo lo mismo.",
    433: "Por ese correo, Kirino no se ha estado reuniendo con sus amigas.",
    434: "Tiene miedo de que sus amigas corran la misma suerte.",
    435: "Ha estado soportando esto por su cuenta.",
    436: "Apenas escucha mis palabras.",
    441: "Me llevé un susto después de abrir la puerta.",
    442: "¿Por qué? Porque Ayase vino.",
    454: "Seguí a Ayase hasta la sala, y ahí Ayase vio a Kirino con una expresión asustada en su cara.",
    468: "Ayase se acercó a la asustada Kirino y la abrazó suavemente.",
    469: "Kirino se calmó un poco de su estado de desorden.",
    470: "Pero fue solo por un momento.",
    473: "Intentando pacificar a Kirino, Ayase la sostuvo fuerte y le frotó la espalda.",
}
s = {
    372: (".........", "Kirino"),
    373: ("Dime, ¿sabes algo sobre esto? ¿Alguna idea de por qué se envió este tipo de correo?", "Kyousuke"),
    374: ("¡No sabría nada sobre esto! ¡Yo también quiero saber la razón detrás de esto!", "Kirino"),
    375: ("¿Te pasó algo... a ti también?", "Kyousuke"),
    376: ("Yo también recibí... un correo similar...", "Kirino"),
    377: ("¡¿Qué dijiste?!", "Kyousuke"),
    383: ("¿El remitente es desconocido?", "Kyousuke"),
    384: ("Sí. ¿La negra y Saori recibieron lo mismo?", "Kirino"),
    385: ("Sip. Con exactamente el mismo contenido.", "Kyousuke"),
    386: ("¡¿Qué demonios está pasando...!", "Kirino"),
    387: ("Esto va demasiado lejos, incluso para una broma.", "Kyousuke"),
    388: ("...Puede que no sea solo una broma.", "Kirino"),
    389: ("¿Por qué dices eso?", "Kyousuke"),
    390: ("Incluso cuando cambio las direcciones de correo varias veces, recibo una copia cada hora.", "Kirino"),
    391: ("¿Huh...?", "Kyousuke"),
    392: ("¡Ya no lo entiendo! ¡No importa cuánto cambie mi dirección, igual llega!", "Kirino"),
    393: ("No solo eso, después de cambiar las direcciones, no son días, sino horas antes de que llegue de nuevo!", "Kirino"),
    394: ("Oye oye, ¿qué es esto?", "Kyousuke"),
    395: ("¡No lo entiendo! ¡¿Por qué estoy recibiendo este tipo de cosas?!", "Kirino"),
    403: ("Ya basta... ¿qué es? ¿Qué está pasando...", "Kirino"),
    407: ("...¡Hii!", "Kirino"),
    408: ("¿Otro correo?", "Kyousuke"),
    409: ("N-No lo quiero... el timbre da miedo...", "Kirino"),
    410: ("Le echaré un vistazo. ¿Está bien?", "Kyousuke"),
    411: ("S-Sí...", "Kirino"),
    415: ("También cambiaste de dirección hace un momento...", "Kyousuke"),
    416: ("Dios... ¿qué es? ¿Qué, qué es? ¡¿Qué?!", "Kirino"),
    417: ("Cálmate. Lo borraré por ti.", "Kyousuke"),
    418: ("¡Solo lo cambié! ¡Solo se lo dije a mis amigas! ¡¿Cómo?!", "Kirino"),
    419: ("¡Cálmate! ¡Está todo bien!", "Kyousuke"),
    420: ("¡¿Cómo puedo calmarme?! ¡No puedo calmarme en absoluto! ¡No lo entiendo! ¡¿Qué es?! ¡¿Qué puede ser!!", "Kirino"),
    421: (".........", "Kyousuke"),
    422: ("Tengo que cambiar la dirección... si no, él lo sabrá. Debo cambiarla rápido.", "Kirino"),
    423: ("Oye, Kirino.", "Kyousuke"),
    424: ("Esta vez, tengo que cambiarla a algo que nadie sepa. Una larga y complicada que nadie pudiera saber...", "Kirino"),
    425: ("*suspiro*...", "Kyousuke"),
    426: ("Con números y letras y símbolos... ¡y aún más larga...!", "Kirino"),
    430: ("Esta vez, definitivamente... él, jejeje...", "Kirino"),
    431: ("Kirino, ¿estás bien?", "Kyousuke"),
    432: ("Sí, pero ¿y si vuelve a llegar... No. No llegará. No llegará... Esta vez seguro.", "Kirino"),
    437: ("¡¡Eep!!!", "Kirino"),
    438: ("Está bien. Parece que alguien está aquí.", "Kyousuke"),
    439: ("¡T-Tú abre la puerta!", "Kirino"),
    440: ("Entendido.", "Kyousuke"),
    443: ("Perdón por molestarte, Onii-san.", "Ayase"),
    444: ("A-Ayase...", "Kyousuke"),
    445: ("Erm, ¿está Kirino?", "Ayase"),
    446: ("Sí, pero ¿qué pasa?", "Kyousuke"),
    447: ("Kirino sigue cambiando su dirección de correo recientemente, así que me preocupé...", "Ayase"),
    448: ("Ah, es eso. Les hace saber a sus amigas cada vez que cambia su dirección de correo.", "Kyousuke"),
    449: ("Lo ha estado cambiando con demasiada frecuencia, así que me preocupé. Además, recibí un correo hace un momento...", "Ayase"),
    450: ("Ah...", "Kyousuke"),
    451: ("Kirino está, ¿verdad? Entonces, entraré.", "Ayase"),
    452: ("Entiendo. Está en la sala.", "Kyousuke"),
    453: ("¡Está bien! Con permiso.", "Ayase"),
    455: ("¿P-Por qué está... Ayase aquí...?", "Kirino"),
    456: ("Porque estoy preocupada por ti... enviando correos sobre cambiar de dirección todos los días.", "Ayase"),
    457: ("N-No puedes. Ayase, ¡no puedes venir!", "Kirino"),
    458: ("...¿Kirino?", "Ayase"),
    459: ("No puedes juntarte conmigo.", "Kirino"),
    460: ("¿Por qué dices esas cosas?", "Ayase"),
    461: ("Porque si te juntas conmigo, te pasarán cosas malas. Y si algo malo te pasa por mi culpa...", "Kirino"),
    462: ("¿Quién dijo esas cosas? Es imposible que algo malo me pase si me junto contigo.", "Ayase"),
    463: ("P-Porque... todos los días los correos... incluso después de cambiar las direcciones...", "Kirino"),
    464: ("Por eso envías esos correos cada día...", "Ayase"),
    465: ("¡Por eso no puedes quedarte! ¡Ayase, vete! ¡Nunca más puedes venir!", "Kirino"),
    466: ("...Kirino, no te preocupes.", "Ayase"),
    467: ("A-Ayase...", "Kirino"),
    471: ("¡No puedes! ¡No puedes, Ayase! ¡Definitivamente no!!", "Kirino"),
    472: ("¡Está bien! Está bien, Kirino.", "Ayase"),
    474: ("Ayase... P-Por qué...?", "Kirino"),
    475: ("Pase lo que pase, no te traicionaré. Siempre te protegeré.", "Ayase"),
    476: ("A-Ayase...", "Kirino"),
    477: ("Así que cálmate. No tienes que preocuparte.", "Ayase"),
    478: ("Ayase... Ayase...", "Kirino"),
    479: ("Poder no depender de nadie, debe sentirse inquietante... Perdón, debería haber venido antes.", "Ayase"),
    480: ("A-Ayase...", "Kirino"),
    481: ("Ya está bien. Estoy contigo. Porque me gustas mucho.", "Ayase"),
    482: ("¡Ayase...! *sollozo*, *sollozosollozo*, yo... yo...! Tenía miedo... Tenía miedo todo este tiempo.", "Kirino"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
entry = current.get("000scriptIYAN_0000E.obj", {})
entry.update(build(n, s))
current["000scriptIYAN_0000E.obj"] = entry
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptIYAN_0000E.obj (part C)")