import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0035_n = {
    0: "Ruta de Kuroneko · El Sartén Y El Pescado",
    7: "SÍ pasó algo.",
    17: "Pero aun así... ¿No está siendo antinaturalmente rara? Esta chica...",
    19: "¿Q-Qué está diciendo? Esta chica...",
    25: "¿Qué está pasando? ¿No parece Kuroneko extraña?",
    26: "Entonces, ¿qué debería hacer...?",
    88: "De alguna manera me estoy sintiendo bastante deprimido.",
    89: "Incluso estoy sorprendido conmigo mismo, por qué... me siento... tan triste?",
}
a0035_s = {
    1: ("Compré el recuerdo que pediste de Kioto.", "Kyousuke"),
    2: ("Ya veo. Pero ya no lo necesito.", "Kuroneko"),
    3: ("¿Huh? ¿Qué es eso, qué quieres decir?", "Kyousuke"),
    4: ("Cambié de opinión y no hay otra razón.", "Kuroneko"),
    5: ("E-Es-Espera... ¿Pasó algo mientras estaba en Kioto?", "Kyousuke"),
    6: ("No realmente.", "Kuroneko"),
    8: ("...De todos modos, volvamos a casa juntos.", "Kyousuke"),
    9: ("¿Juntos... contigo...?", "Kuroneko"),
    10: ("¿No podemos?", "Kyousuke"),
    11: ("...Hmph, ¿es necesario hacer algo así?", "Kuroneko"),
    12: ("No hay ninguna razón para que yo vuelva a casa contigo.", "Kuroneko"),
    13: ("¿No podemos volver a casa juntos sin una razón?", "Kyousuke"),
    14: ("...Sí, eso es correcto. Toda acción debe tener un objetivo válido que la acompañe.", "Kuroneko"),
    15: ("Las acciones sin rumbo, son tan inútiles como hojas muertas flotando en el agua.", "Kuroneko"),
    16: ("Huh...", "Kyousuke"),
    18: ("...¿Huh?", "Kyousuke"),
    20: ("¿No me escuchaste?", "Kuroneko"),
    21: ("Entonces lo repetiré, no hay ninguna razón para que yo vaya a casa contigo.", "Kuroneko"),
    22: ("¿Y-Yo no tienes que decirlo tan bruscamente...?", "Kyousuke"),
    23: ("Hmm... Simplemente deseo que lo entiendas...", "Kuroneko"),
    24: ("No puedo estar en tu presencia.", "Kuroneko"),
    27: ("Lo siento, pero no tengo tiempo para jugar ahora mismo.", "Kuroneko"),
    28: ("Adiós entonces, senpai.", "Kuroneko"),
    29: ("Kuroneko, ¿puedo preguntarte algo?", "Kyousuke"),
    30: ("¿Qué sería?", "Kuroneko"),
    31: ("Uh, es solo una teoría...", "Kyousuke"),
    32: ("...¿Qué?", "Kuroneko"),
    33: ("¿P-Podría ser que tienes a alguien que te interesa?", "Kyousuke"),
    34: ("¡¿P-Por qué habría de ser ese el caso?!", "Kuroneko"),
    35: ("Y-Ya veo... Por fin puedo relajarme un poco...", "Kyousuke"),
    36: ("¿P-Por qué dijiste algo tan confuso de repente...", "Kuroneko"),
    37: ("Eso sonó realmente frío... Me voy a sentir solo...", "Kyousuke"),
    38: ("¿No es ese tu problema? Yo tengo mis propios asuntos que atender.", "Kuroneko"),
    39: ("Eh, ¿qué tipo de asunto?", "Kyousuke"),
    40: ("...No necesito decírtelo.", "Kuroneko"),
    41: ("Además, eso de estar solo es una mentira, ¿no es así? Senpai ya tiene a Belphegor... no, a Tamura-senpai.", "Kuroneko"),
    42: ("¿Por qué mencionaste a Manami aquí? Ella no tiene nada que ver con esto.", "Kyousuke"),
    43: ("Además, es verdad que me sentiré solo si no estás cerca.", "Kyousuke"),
    44: ("......Ya veo.", "Kuroneko"),
    45: ("...Senpai, aprovecharé la ocasión para dejárselo claro.", "Kuroneko"),
    46: ("Oh, ¿qué es?", "Kyousuke"),
    47: ("...No te involucres más conmigo.", "Kuroneko"),
    48: ("¿Qué es eso, probando un chiste nuevo?", "Kyousuke"),
    49: ("Si eso es lo que piensas, eres realmente una persona despreocupada.", "Kuroneko"),
    50: ("¡Eso es porque quería que fuera un chiste! Porque...", "Kyousuke"),
    51: ("¿Porque... qué?", "Kuroneko"),
    52: ("¿No me sentiré solo si no es ese el caso?", "Kyousuke"),
    53: ("......", "Kuroneko"),
    54: ("...Incluso si me miras así, eso no cambiará mi decisión.", "Kuroneko"),
    55: ("¿Qué se supone que significa eso? No lo entiendo.", "Kyousuke"),
    56: ("No importa si no lo entiendes, solo quería decirte eso.", "Kuroneko"),
    57: ("Tienes que darme una razón, ¿sabes.", "Kyousuke"),
    58: ("No necesito dar una, es inútil incluso si lo hago.", "Kuroneko"),
    59: ("¿Por qué es inútil? ¿Cómo lo sabrías si no lo dices en voz alta?", "Kyousuke"),
    60: ("El resultado será mejor para ambos de esa manera...", "Kuroneko"),
    61: ("¿N-No hay cosas que deberías hacer?", "Kuroneko"),
    62: ("¿C-Cosas que debería hacer...?", "Kyousuke"),
    63: ("Por Dios... ¿No está senpai preparándose para sus exámenes?", "Kuroneko"),
    64: ("...Ah...", "Kyousuke"),
    65: ("¿Ahora lo entiendes? Ambos tenemos cosas que debemos hacer. Así que es por nuestro mutuo bien el hacerlo.", "Kuroneko"),
    66: ("¿Crees que aceptaré eso así nomás? ¡Explícate apropiadamente!", "Kyousuke"),
    67: ("No presumas que puedes hacer que la gente te diga todo lo que quieres.", "Kuroneko"),
    68: ("Hay muchas cosas que la gente no puede decirle a otros.", "Kuroneko"),
    69: ("Aun así...", "Kyousuke"),
    70: ("No lo entiendo en absoluto...", "Kyousuke"),
    71: ("Sí, eso está perfectamente bien. También pensé que no lo entenderías.", "Kuroneko"),
    72: ("¿Qué es eso...", "Kyousuke"),
    73: ("Inútil significa inútil.", "Kuroneko"),
    74: ("Ahora mismo, tu voluntad no es nada más que un obstáculo para mi alma. Por eso tengo que distanciarme de ti.", "Kuroneko"),
    75: ("¿Qué es eso...", "Kyousuke"),
    76: ("Es como dije.", "Kuroneko"),
    77: ("Esto marca el final de nuestra conversación.", "Kuroneko"),
    78: ("¿O-Oye? ¿Qué te pasa?", "Kyousuke"),
    79: ("No tengo necesidad ni obligación de responderte.", "Kuroneko"),
    80: ("¿De verdad tienes que decirlo así? Aunque estoy preocupado por ti...", "Kyousuke"),
    81: ("¿No puedes dejar de estar tan deprimido? Es de mal gusto.", "Kuroneko"),
    82: ("...Detente.", "Kyousuke"),
    83: ("No hay nada más que tenga que decir.", "Kuroneko"),
    84: ("Dijiste «no te involucres más conmigo» hace un rato... ¿Lo dices en serio?", "Kyousuke"),
    85: ("...Sí, lo digo.", "Kuroneko"),
    86: ("...No te involucres más conmigo.", "Kuroneko"),
    87: ("¿Qué... es eso...", "Kyousuke"),
}

a0038_n = {
    0: "Ruta de Kuroneko · La Sugerencia De Belphegor",
    20: "Una razón por la que Kuroneko me rechazaría...",
    29: "...Pero me da cosa pedirle ayuda.",
}
a0038_s = {
    1: ("...Así que Kuroneko-san se fue.", "Manami"),
    2: ("Sí, así es.", "Kyousuke"),
    3: ("Dime, Kyou-chan...", "Manami"),
    4: ("...¿No se siente como si... Kuroneko-san estuviera actuando un poco rara?", "Manami"),
    5: ("¿Cierto? ¡Definitivamente estaba actuando rara! ¿Tú también lo pensaste?", "Kyousuke"),
    6: ("S-Sí, parece que ella está... evitándote a propósito.", "Manami"),
    7: ("Así que es así...", "Kyousuke"),
    8: ("Kyou-chan, ¿has hecho algo... a Kuroneko-san?", "Manami"),
    9: ("¡No lo hice! ¡Nada en absoluto! Creo...", "Kyousuke"),
    10: ("Entonces, ¿por qué te evita así? Estoy segura de que hay una razón para ello.", "Manami"),
    11: ("Bueno...", "Kyousuke"),
    12: ("Oye, Manami... Quiero preguntarte ya que podría no haberme dado cuenta yo mismo... ¿Dije algo mal a Kuroneko hace un momento?", "Kyousuke"),
    13: ("No, nada de ese tipo.", "Manami"),
    14: ("Fuiste un senpai muy amable hace un momento.", "Manami"),
    15: ("¿E-En serio? Jeje, ¡estoy algo avergonzado!", "Kyousuke"),
    16: ("....Hmmm, en realidad, ¿quizás sí?", "Manami"),
    17: ("...¿Eh? ¿En serio?", "Kyousuke"),
    18: ("Pero eso no fue nada fuera de lo común para ti. Creo que Kuroneko-san te está evitando por alguna otra razón.", "Manami"),
    19: ("¡No me estás ayudando nada con eso!", "Kyousuke"),
    21: ("No tengo la menor idea...", "Kyousuke"),
    22: ("¿Qué debería hacer?", "Kyousuke"),
    23: ("¿Qué tal si le pides un consejo a Kirino-chan?", "Manami"),
    24: ("¡¿Huh?!", "Kyousuke"),
    25: ("¿Q-Qué tiene que ver Kirino con esto?", "Kyousuke"),
    26: ("Después de todo, ¿no se llevan muy bien Kirino-chan y Kuroneko-san?", "Manami"),
    27: ("Por eso ella podría saber la razón por la que Kuroneko-san está actuando tan rara.", "Manami"),
    28: ("Hm... Es verdad.", "Kyousuke"),
    30: ("Oye, Kyou-chan.", "Manami"),
    31: ("¿Hmm?", "Kyousuke"),
    32: ("Yo... te apoyaré, Kyou-chan.", "Manami"),
    33: ("O-Oh, gracias.", "Kyousuke"),
    34: ("¡Sí!", "Manami"),
    35: ("¡Buena suerte, «senpai»!", "Manami"),
    36: ("No puedo evitarlo cuando me llamas así.", "Kyousuke"),
}

a0040_n = {
    0: "Ruta de Kuroneko · La Consejería De Vida Al Revés",
    2: "Bueno entonces, supongo que intentaré preguntarle de inmediato.",
    3: "Ahí está.",
}
a0040_s = {
    1: ("Llegué a casa.", "Kyousuke"),
    4: ("Oye Kirino, tengo algo que me gustaría discutir contigo.", "Kyousuke"),
    5: ("¿Eh... algo que discutir?", "Kirino"),
    6: ("Sí.", "Kyousuke"),
    7: ("Si es algo raro... Bueno, no creo que sea algo así.", "Kirino"),
    8: ("Por supuesto. ¿En qué mundo existe un hermano que acosara sexualmente a su hermanita?", "Kyousuke"),
    9: ("E-Este tipo... Mírate quién habla...", "Kirino"),
    10: ("Incluso sin que lo pretendas, ha habido muchísimas veces en las que terminó siendo así.", "Kirino"),
    11: ("No tengo recuerdos de eso.", "Kyousuke"),
    12: ("Sí, sí. Entonces, ¿qué es?", "Kirino"),
    13: ("...Quiero tener una Consejería de Vida.", "Kyousuke"),
}

a0043_n = {
    0: "Ruta de Kuroneko · La Consejería De Vida Al Revés",
    24: "Sin embargo, ella tiene un punto ahí.",
    25: "¿Asqueroso...?",
}
a0043_s = {
    1: ("...¿Huh? ¿Una Consejería de Vida? ¿La quieres? ¿De mí?", "Kirino"),
    2: ("Exacto. Está bien de vez en cuando, ¿no?", "Kyousuke"),
    3: ("Hmm...", "Kirino"),
    4: ("Bueno, de acuerdo. Ve, te prestaré atención.", "Kirino"),
    5: ("Kuroneko ha estado bastante fría últimamente. Kirino, ¿podrías hacer algo?", "Kyousuke"),
    6: ("Q-Qué... Qué...", "Kirino"),
    7: ("...¡¿Los dos están saliendo?!", "Kirino"),
    8: ("¡N-No estamos--! ¡¿Qué te hace pensar eso?!", "Kyousuke"),
    9: ("¡Es por la manera engañosa en que lo dijiste!!", "Kirino"),
    10: ("...¿Huh?", "Kyousuke"),
    11: ("¡No me digas '¿Huh?'! ¡Te estoy preguntando desde cuándo empezaste a salir con ella?!", "Kirino"),
    12: ("¿Qué estás diciendo? No hay manera de que esté saliendo con Kuroneko.", "Kyousuke"),
    13: ("¡¿Qué--!", "Kirino"),
    14: ("¡Auch!", "Kyousuke"),
    15: ("¡No seas tan engañoso, idiota!", "Kirino"),
    16: ("Perdón. Pero escucha, es verdad que Kuroneko ha estado actuando fría.", "Kyousuke"),
    17: ("¿Qué quieres decir?", "Kirino"),
    18: ("Me ha estado evitando. Ni siquiera aceptó los recuerdos que traje de Kioto, e incluso me rechazó cuando ofrecí caminar a casa juntos.", "Kyousuke"),
    19: ("¡Asqueroso! ¿Es eso lo que has estado haciendo en la escuela?!", "Kirino"),
    20: ("¡¿C-Cómo es eso asqueroso?!", "Kyousuke"),
    21: ("P-Porque... comprar recuerdos, caminar a casa juntos...", "Kirino"),
    22: ("Es como si estuvieras c-coqueteándole...", "Kirino"),
    23: ("¡Has estado jugando demasiados galge!", "Kyousuke"),
    26: ("Es realmente asqueroso, hacer cosas como dar recuerdos y caminar a casa juntos...", "Kirino"),
    27: ("¿Qué es eso? ¿Tratando de activar una bandera?", "Kirino"),
    28: ("Puedo entender que tema por su propia seguridad...", "Kirino"),
    29: ("...E-Entonces, Kirino, la razón por la que Kuroneko me evita es...", "Kyousuke"),
    30: ("No me digas... ya que fui demasiado considerado con ella... la asusté...?", "Kyousuke"),
    31: ("Incorrecto.", "Kirino"),
    32: ("¿Huh? Pero acababas de decir...", "Kyousuke"),
    33: ("Eso está definitivamente mal. Estaba medio bromeando. Es verdad que eres asqueroso, pero ella no te tiene miedo.", "Kirino"),
    34: ("...Eso lo dices con bastante confianza.", "Kyousuke"),
    35: ("Por supuesto.", "Kirino"),
    36: ("E-De todos modos, creo que hay otras razones por las que te está evitando.", "Kirino"),
    37: ("¿Qué te hace decir eso?", "Kyousuke"),
    38: ("Porque es lo mismo conmigo.", "Kirino"),
    39: ("De hecho, el otro día...", "Kirino"),
}

a0045_n = {
    0: "Ruta de Kuroneko · El Día Prometido",
    5: "Mierda... La conversación de antes la puso de mal humor.",
    21: "Creo que probablemente quiso decir «tengo algo importante que hacer, así que no tengo tiempo para jugar por un tiempo».",
    22: "Desde el punto de vista de Kirino, significa que no podrá salir con ella más. Está molesta por eso.",
    26: "No te preocupes, no soy tan imprudente.",
    27: "Aun así, todo lo que entendí es que Kuroneko está ocupada con algo...",
    28: "¿Cómo se relaciona eso con que me evite?",
    34: "Ya veo, creo que ya lo entiendo casi todo.",
    35: "Kuroneko está tratando de hacer algo por su cuenta. Es solo una suposición, pero no quiere molestar a los demás y por eso se distanció.",
}
a0045_s = {
    1: ("...Espera, ¿por qué tengo que hablar contigo sobre esto?", "Kirino"),
    2: ("...¿Huh?", "Kyousuke"),
    3: ("Si crees que es tu culpa, normalmente deberías lidiar con ello tú mismo.", "Kirino"),
    4: ("Bueno, eso es verdad, pero... estoy en el límite de mis fuerzas, ¡por eso te lo pido!", "Kyousuke"),
    6: ("Bueno, hablaré ya que esta vez no hay más remedio.", "Kirino"),
    7: ("Por favor, te lo ruego, no puedo hacer nada solo.", "Kyousuke"),
    8: ("¡Necesito tu ayuda! ¡Por favor!", "Kyousuke"),
    9: ("B-Bueno... Si lo pones así, supongo que no puedo decir que no.", "Kirino"),
    10: ("El día prometido se acerca.", "Kuroneko"),
    11: ("¿Huh?", "Kirino"),
    12: ("Hasta que cumpla mi 'misión'... no tengo tiempo para jugar con mortales como tú.", "Kuroneko"),
    13: ("Ya no nos veremos hasta que todo esto termine.", "Kuroneko"),
    14: ("¿Huh? E-Espera, ¿qué estás diciendo?", "Kirino"),
    15: ("Esto es todo lo que tengo que decir.", "Kuroneko"),
    16: ("Ah, ¡espera! Espera...", "Kirino"),
    17: ("¿Qué...", "Kirino"),
    18: ("¿Qué fue eso?", "Kyousuke"),
    19: ("Yo tampoco lo entiendo.", "Kirino"),
    20: ("Bueno, lo supuse.", "Kyousuke"),
    23: ("No estás pensando en algo que me vaya a irritar, ¿verdad?", "Kirino"),
    24: ("No, nada de eso.", "Kyousuke"),
    25: ("Como habrás adivinado... Me enojaré si te atreves a decirlo.", "Kirino"),
    29: ("He estado pensando...", "Kirino"),
    30: ("Creo que tiene alguna 【Meta Importante】 en mente.", "Kirino"),
    31: ("¿Qué quieres decir con eso?", "Kyousuke"),
    32: ("No estoy segura, pero tengo la sensación de que está tratando de lograrla completamente sola.", "Kirino"),
    33: ("Hmph, ¿por qué se está esforzando tanto sola? En serio, presumiendo cuando no puede hacer nada.", "Kirino"),
    36: ("*mirando fijamente*", "Kirino"),
    37: ("¿Q-Qué...?", "Kyousuke"),
    38: ("Solo terminaríamos peleando si yo hablara con ella...", "Kirino"),
    39: ("...Tú, haz algo...", "Kirino"),
    40: ("Te escuché, ¿con eso de... la Consejería de Vida, verdad?", "Kirino"),
    41: ("Así es.", "Kyousuke"),
    42: ("Pensaré en algo, así que déjamelo a mí.", "Kyousuke"),
    43: ("...Hmph.", "Kirino"),
}

data = {
    "000scriptCKUR_0035T.obj": build(a0035_n, a0035_s),
    "000scriptCKUR_0038A.obj": build(a0038_n, a0038_s),
    "000scriptCKUR_0040A.obj": build(a0040_n, a0040_s),
    "000scriptCKUR_0043T.obj": build(a0043_n, a0043_s),
    "000scriptCKUR_0045A.obj": build(a0045_n, a0045_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
