import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a60_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo No Ayude A Mi Hermanita",
    3: "...Ella se alejó de mí sin decir palabra en el momento en que volví a casa.",
    18: "Aunque siempre se pelean, Kirino de verdad considera a esas dos como sus amigas importantes.",
    19: "Esta podría ser una oportunidad para recuperar sus recuerdos.",
}
a60_s = {
    1: ("Ya llegué～", "Kyousuke"),
    2: ("......", "Kirino"),
    4: ("Oye, Kirino. Tengo algo que decirte.", "Kyousuke"),
    5: ("¿Kirino? ¿Estás escuchando?", "Kyousuke"),
    6: ("Kirino.", "Kyousuke"),
    7: ("...Tch.", "Kirino"),
    8: ("...¿Qué? ¿No dije que no te acercaras más?", "Kirino"),
    9: ("Relájate. No voy a hacer nada extraño otra vez.", "Kyousuke"),
    10: ("¿Huh? No puedo creer eso.", "Kirino"),
    11: ("Más bien, no importa qué clase de objeto trajiste contigo esta vez, tengo absolutamente cero confianza en ti ahora.", "Kirino"),
    12: ("...No traje nada conmigo hoy. Hay algunas personas con las que quiero que hables.", "Kyousuke"),
    13: ("¿No tienes capacidad de aprendizaje? ¿Eres un tonto? Dije que no les preguntaría a Papá y Mamá sobre ello.", "Kirino"),
    14: ("No, las personas con las que quiero que hables no son nuestros padres. Tampoco necesitas reunirte con ellas directamente.", "Kyousuke"),
    15: ("Entonces, ¿quiénes son? ¿Y cómo voy a hablar con ellas?", "Kirino"),
    16: ("...Son tus amigas. Haré que hables con ellas en la sala de chat.", "Kyousuke"),
    17: ("¿Huh?", "Kirino"),
}

a63_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo No Ayude A Mi Hermanita",
    11: "Como siempre, no la entiendo en absoluto. Entonces, ¿cuál es?",
    23: "¡Entonces por qué me estás preguntando?!",
}
a63_s = {
    1: ("¿De verdad tengo que hacerlo?", "Kirino"),
    2: ("No has sido muy cooperativa desde el principio.", "Kyousuke"),
    3: ("Por supuesto. Después de todo, no me preocupa en absoluto.", "Kirino"),
    4: ("Incluso si a ti no te preocupa, a mí sí.", "Kyousuke"),
    5: ("¿Huh? Que tú estés preocupado no tiene nada que ver conmigo.", "Kirino"),
    6: ("No necesito ningún recuerdo sobre tener aficiones otaku.", "Kirino"),
    7: ("...Ah, ¿es así?", "Kyousuke"),
    8: ("E-Espera. ¿Qué pasa con esa actitud tuya? ¿No eres tú el que no está motivado?", "Kirino"),
    9: ("...No, es porque simplemente no estás dispuesta a hacerlo... Así que no sé qué hacer.", "Kyousuke"),
    10: ("N-No dije que no lo haré.", "Kirino"),
    12: ("Ahora que lo pienso... esto de la pérdida de memoria, en realidad lo inventaste todo, ¿verdad?", "Kirino"),
    13: ("¡Sí, estoy segura de que es eso!", "Kirino"),
    14: ("¡El problema es que todo es verdad!", "Kyousuke"),
    15: ("Guh... Siento que empezaré a pensar lo mismo si sigues diciendo eso...", "Kirino"),
    16: ("¡¿*jadeo*?! ¡¿Podría ser esto lavado de cerebro?!", "Kirino"),
    17: ("¡No es eso!", "Kyousuke"),
    18: ("N-No...", "Kyousuke"),
    19: ("¡Ah! ¡Acabas de tartamudear! ¿Por qué tartamudeabas en ese momento?", "Kirino"),
    20: ("¿No es hora de que pares esto?", "Kirino"),
    21: ("¡Solo estaba eligiendo cuidadosamente mis palabras y aún así reaccionas así?! ¡Todo es real!", "Kyousuke"),
    22: ("No voy a creer tus palabras, no importa lo que digas.", "Kirino"),
    24: ("Oye, ¿no te sientes terrible al tener algunos de tus recuerdos perdidos?", "Kyousuke"),
    25: ("Bueno, sí me siento así un poco.", "Kirino"),
    26: ("Sin embargo, no tengo ningún arrepentimiento si son recuerdos otaku.", "Kirino"),
    27: ("Oye Kirino. ¿Estás... diciendo eso en serio?", "Kyousuke"),
    28: ("Estoy seria, súper seria.", "Kirino"),
    29: ("......", "Kyousuke"),
    30: ("¿Q-Qué pasa con esa mirada seria...? Uwah, ¡no te pongas todo lloroso!", "Kirino"),
    31: ("Dios. Escucha, los recuerdos son importantes para formar tu carácter...", "Kyousuke"),
    32: ("No me sermonees con palabras que memorizaste al azar de ver la televisión.", "Kirino"),
    33: ("...De todos modos. ¿No es renunciar a tus recuerdos lo mismo que renunciar a parte de tu vida?", "Kyousuke"),
    34: ("¿Huh? ¿No estás exagerando demasiado?", "Kirino"),
    35: ("Oye, solo cinco minutos bastarán. Si no te gusta, puedes parar de inmediato. Así que por favor chatea con las dos.", "Kyousuke"),
    36: ("Hmph... ¿Y si digo que no quiero?", "Kirino"),
    37: ("¿Qué estás diciendo? Apúrate y siéntate frente a la computadora.", "Kyousuke"),
    38: ("¿Q-Qué se supone que es eso, una orden?", "Kirino"),
    39: ("Haré cualquier cosa por el bien de recuperar tus recuerdos.", "Kyousuke"),
    40: ("¿C-Cualquier cosa, dices...", "Kirino"),
    41: ("Tch, tienes mucha cara aunque seas un pervertido.", "Kirino"),
    42: ("...Si haces eso, me rendiré.", "Kyousuke"),
    43: ("...¿Eh?", "Kirino"),
    44: ("Admitiré que todo hasta ahora fue mi delirio.", "Kyousuke"),
    45: ("Decirles a nuestros padres, entregarme a la policía, haz lo que quieras... Pero, el hecho de que perdiste tus recuerdos es la verdad.", "Kyousuke"),
    46: ("...Tch... Tratando de engañarme otra vez...", "Kirino"),
    47: ("...Pero, pensar que dirías tanto.", "Kirino"),
    48: ("Exagerado, dices... Es algo importante para ti...", "Kyousuke"),
    49: ("Estoy cansada de escuchar tus sermones. Bien, quedas despedido～", "Kirino"),
    50: ("...Kirino.", "Kyousuke"),
    51: ("¡Eres molesto!", "Kirino"),
    52: ("¡Te lo ruego! ¡Kirino!", "Kyousuke"),
    53: (".........", "Kirino"),
    54: ("...*gulp*", "Kyousuke"),
    55: ("Ah Dios... ¡Entiendo!", "Kirino"),
}

a65_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo No Ayude A Mi Hermanita",
    2: "Mierda... Dije demasiado...",
    3: "Esta chica, parece estar de un mal humor.",
    12: "Además, si descubrieran que Kirino las olvidó por completo, se sorprenderían.",
    13: "Si es posible, me gustaría recuperar los recuerdos de Kirino antes de que se den cuenta...",
}
a65_s = {
    1: ("Dios mío...", "Kirino"),
    4: ("Umm... ¿Kirino-san?", "Kyousuke"),
    5: ("Entiendo que no quieras hacer esto. Pero compláceme aquí...¡Así!", "Kyousuke"),
    6: ("Ahh, ¡lo entiendo! ¡Estará bien si lo hago, verdad?!", "Kirino"),
    7: ("*jadeo*...*jadeo*... E-Es bueno que entiendas...", "Kyousuke"),
    8: ("Lo diré de antemano, no diré nada como que mis recuerdos han cambiado.", "Kirino"),
    9: ("Sin embargo, si hablan de sus temas habituales contigo, creo que te expondrás cuando hables, ya que no será más que cosas de otaku.", "Kyousuke"),
    10: ("Si ese es el caso, entonces no lo haré.", "Kirino"),
    11: ("...Entiendo. Haré seguimiento en los puntos peligrosos, así que por ahora solo siéntate.", "Kyousuke"),
    14: ("Bueno entonces, por el momento, rompe el hielo mencionando naturalmente cosas como sus opiniones sobre los recuerdos de Kioto que repartí.", "Kyousuke"),
    15: ("Tch... eres tan engreído.", "Kirino"),
}

a70_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo No Ayude A Mi Hermanita",
    10: "La que tengo ante mis ojos también es una persona así.",
    21: "¿Qué tal hablar del torneo de juegos reciente?",
    24: "Las dos son buenas chicas por dentro, así que lo que sea que Kirino escriba, lo seguirán de alguna manera.",
    25: "Solo me relajaré y vigilaré el chat entre Kirino y las otras dos...",
    28: "¡¡Hay un límite para no poder leer el ambiente!!",
    37: "Acabas de escribir calmadamente algo que haría que tu yo habitual se enfureciera si lo leyera.",
    38: "Aaah, esas chicas probablemente están mirando con la boca abierta la pantalla de sus computadoras ahora mismo.",
    39: "Maldición, tendré que hacer algo al respecto después...",
    43: "Después de todo, la otra parte incluye a la muy considerada Saori.",
    44: "Incluso si un tema es sacado a la fuerza, definitivamente se asegurará de que la conversación se desarrolle agradablemente.",
    50: "Por cierto, Tentacle Little Sister es el apodo del personaje, Madouin Reika, que aparece en Siscaly, pero...",
    51: "Poniendo a la Tentacle Little Sister en el baño... ¿por qué hizo una elección así?",
    55: "¡M-Mierda!",
    63: "Esto es malo. Kirino no puede seguir el ritmo de la conversación otaku con estas dos, y su enojo está llegando a su límite.",
    64: "Aunque esperaba que alguna terapia de shock funcionara, según cómo se ven las cosas ahora mismo, no sirve...",
    93: "La enfermedad incurable conocida como ser una Chuunibyou.",
    94: "....Pero en serio, Kuroneko es tan perspicaz como siempre.",
    102: "Esto es malo... su pérdida de memoria va a ser expuesta a este paso.",
    103: "Guh... esa Kirino, ¿a dónde se fue en un momento así?",
    104: "¿Qué debería hacer, qué debería hacer...?",
    105: "Y-Ya que se ha llegado a esto, solo puedo tratar de engañarlas.",
    108: "C-Como era de esperar de Saori...",
    109: "Es una mujer que puede leer espléndidamente el ambiente a pesar de su apariencia exterior.",
    115: "Con palabras que transmitían una sensación de desconcierto, Saori empezó a explicar sobre lo que pasó durante su último chat, el 14 de julio.",
}
a70_s = {
    1: ("Buen día, err, ¿están todas bien?", "Kiririn"),
    2: ("Ah, ¡Kiririn-san, cuánto tiempo! Estaba preocupada ya que no te has conectado desde hace bastante tiempo.", "Saori"),
    3: ("Normalmente te conectas para chatear con nosotras casi a diario.", "Saori"),
    4: ("Perdón, estuve un poco ocupada con el trabajo.", "Kiririn"),
    5: ("Je, pensé que seguramente habías vuelto a tu tierra natal, el planeta de los esclavos de la moda.", "Kuroneko"),
    6: ("...¿Qué pasa con la repentina grosería de esta persona?", "Kirino"),
    7: ("Bueno, para decirlo de una manera que puedas entender, está diciendo «Estaba sola. Podrías al menos haberte contactado conmigo».", "Kyousuke"),
    8: ("¿Huh? ¿Cómo puedes siquiera interpretar esa oración molesta de esa manera?", "Kirino"),
    9: ("No hay forma de que exista una persona tan perversa.", "Kirino"),
    11: ("Dejando eso a un lado, habla primero de los recuerdos de Kioto, ¿de acuerdo?", "Kyousuke"),
    12: ("...Tch, lo sé.", "Kirino"),
    13: ("Err, el chico con ojos de pez muerto me hizo decirles que le gustaría entregarles los recuerdos que trajo de Kioto.", "Kirino"),
    14: ("¿P-Pez muerto...?", "Kyousuke"),
    15: ("Oh cielos, ¿el hermano mayor Kyousuke quiere darnos algo? ¿Qué clase de recuerdos son?", "Saori"),
    16: ("Si consideráramos los gustos de Senpai, es mejor para nosotras no tener altas expectativas de los recuerdos.", "Kuroneko"),
    17: ("...Nadie me apoya.", "Kyousuke"),
    18: ("¿Qué estás murmurando? Entonces, ¿qué debería decir después?", "Kirino"),
    19: ("Guh...", "Kyousuke"),
    20: ("Err, l-lo siguiente...", "Kyousuke"),
    22: ("Bueno, solo seguir el flujo de la conversación naturalmente bastará, supongo.", "Kyousuke"),
    23: ("¿Huh? ¿Así que está bien? Entonces...", "Kirino"),
    26: ("Err... Ha estado hablando de nada más que juegos y anime por un tiempo y está siendo seriamente molesto, ¿sabes? Enviar.", "Kirino"),
    27: ("...¡Espera, ¿qué demonios estás escribiendo?!", "Kyousuke"),
    29: ("Ki-Kiririn-san, ¿pasó algo hoy? Pareces estar actuando diferente a lo habitual...", "Saori"),
    30: ("Sí, normalmente eres 16 veces más desagradable.", "Kuroneko"),
    31: ("Espero que tu alma manchada de negro caiga en las profundidades del purgatorio.", "Kuroneko"),
    32: ("¿Huh? No entiendo nada de lo que estás diciendo.", "Kiririn"),
    33: ("Te lo devuelvo. Estabas hablando alegremente sobre ese juego y anime el otro día.", "Kuroneko"),
    34: ("No, normalmente, los temas discutidos por las chicas de nuestra edad son sobre maquillaje o moda, ¿verdad? Ustedes son las raras...", "Kiririn"),
    35: ("Te dije que pares. No hay necesidad de que digas tanto.", "Kyousuke"),
    36: ("Para resolver este tipo de malentendido, tienes que decirle a la otra persona directamente.", "Kirino"),
    40: ("Kirino, habla de los premios que ganamos del torneo de juegos el otro día.", "Kyousuke"),
    41: ("¿Huh? No sé nada sobre eso. Hablar de ello normalmente es imposible.", "Kirino"),
    42: ("No importa lo que digas. Puedes preguntar qué está haciendo cada una con sus premios, por ejemplo. De todos modos, solo saca el tema.", "Kyousuke"),
    45: ("...Lo entiendo.", "Kirino"),
    46: ("Ahora que lo pienso, sobre los premios que ganamos del torneo de juegos el otro día. ¿Qué hizo cada una con los suyos?", "Kiririn"),
    47: ("Impermeabilicé mi póster de Tentacle Little Sister y lo convertí en una cortina de baño. Puedo pasar mi tiempo de baño feliz gracias a eso.", "Saori"),
    48: ("Oye... ¿qué están diciendo estas personas? Más bien, ¿qué quiere decir con tentáculos?", "Kirino"),
    49: ("...Es mejor que no lo pienses demasiado.", "Kyousuke"),
    52: ("Si recuerdo correctamente, la parte de Kiririn-san era la tablilla de autógrafos firmada por un seiyuu.", "Saori"),
    53: ("Incluso dijiste que nos enviarías una foto de ella exhibida en tu habitación, pero ¿qué pasó después?", "Saori"),
    54: ("¿Eh...", "Kiririn"),
    56: ("Espera, ¿qué está pasando?", "Kirino"),
    57: ("E-Es esta tablilla de autógrafos. Rápidamente toma una foto de ella con tu teléfono celular y envíalasela.", "Kyousuke"),
    58: ("¿Q-Qué es esto...? No solo no tengo idea de quién es ese autógrafo, la ilustración en ella apesta a otaku.", "Kirino"),
    59: ("Más bien, este es mi límite. ¿Por qué tengo que unirme a esta conversación llena 100% de otaku?", "Kirino"),
    60: ("C-Cálmate, estas personas no tienen malas intenciones.", "Kyousuke"),
    61: ("Cállate. Incluso si no hay malas intenciones, lo que me enoja simplemente me enoja.", "Kirino"),
    62: ("Aaah, ¡Dios! ¡Podemos hablar de eso después! Por ahora, di que se la enviarás después y engáñalas adecuadamente.", "Kyousuke"),
    65: ("Perdón, lo olvidé. Enviaré la foto en otra ocasión.", "Kiririn"),
    66: ("No, por favor no te preocupes por ello.", "Saori"),
    67: ("Ufufu, hablando de fotos, nos tomamos una foto de las tres durante una de las muchas veces que nos reunimos en una reunión fuera de línea.", "Saori"),
    68: ("¿F-Foto? ¿Existía tal cosa?", "Kiririn"),
    69: ("¿Oh cielos? ¿No se la envié a Kiririn-san? Perdón, debe haberse deslizado descuidadamente de mi mente.", "Saori"),
    70: ("Entonces, se la enviaré ahora.", "Saori"),
    71: ("...¿Eh...?", "Kirino"),
    72: ("¿Qué es... esto.... soy yo?", "Kirino"),
    73: ("Sí, la del atuendo gótico lolita es Kuroneko, y la grande con anteojos espiralados es Saori.", "Kyousuke"),
    74: ("Pero... no recuerdo haberme tomado esta foto antes.", "Kirino"),
    75: ("...Te ves muy feliz en esta foto.", "Kyousuke"),
    76: ("...Entiendes, ¿verdad? Estas personas de verdad son tus amigas.", "Kyousuke"),
    77: ("... Cómo... es eso...", "Kirino"),
    78: ("Oye, Kirino, ¿a dónde vas?", "Kyousuke"),
    79: (".........", "Kirino"),
    80: ("Lo sé, intenta hablar sobre el torneo del juego Siscaly después.", "Kyousuke"),
    81: ("¡¿Huh?! ¡No sé nada sobre eso!", "Kirino"),
    82: ("Incluso si no sabes sobre ello, ciertamente participaste. Así que tu cuerpo debe recordarlo. Lo recordarás mientras hables de ello.", "Kyousuke"),
    83: ("Tsk, lees demasiado manga.", "Kirino"),
    84: ("Err... Por cierto, sobre el torneo de Siscaly...", "Kiririn"),
    85: ("Eso realmente fue una lástima.", "Saori"),
    86: ("La incompetencia de tu hermano superó mis expectativas con creces.", "Kuroneko"),
    87: ("¿Qué significa versión arcade?", "Kiririn"),
    88: ("Je, ¿tu clan olvidó hasta eso? Como era de esperar de una escritora activa en la secundaria, los Circuitos Mágicos en tu cerebro son deficientes.", "Kuroneko"),
    89: ("...", "Kiririn"),
    90: ("...También, desde hace rato, has estado preguntando repetidamente sobre nada más que cosas que ya deberías saber.", "Kuroneko"),
    91: ("Esta chica... de verdad quiero matarla...", "Kirino"),
    92: ("B-Bueno, aguanta. Sufre de una enfermedad incurable, así que a veces dice cosas extrañas.", "Kyousuke"),
    95: ("Tch...", "Kirino"),
    96: ("O-Oye, ¿a dónde crees que vas?", "Kyousuke"),
    97: (".........", "Kirino"),
    98: ("...Incluso si puedes engañar a los mortales, no puedes engañarme a mí, la señora favorecida por la oscuridad.", "Kuroneko"),
    99: ("Hay 【algo extraño】 en ti hoy.", "Kuroneko"),
    100: ("Sí, para ser honesta, también me lo estoy preguntando.", "Saori"),
    101: ("¿Qué exactamente estás escondiendo?", "Kuroneko"),
    106: ("¡N-No hay nada malo en absoluto!", "Kiririn"),
    107: ("...¿Es ese el caso? Bueno, dejaremos de preguntar si es difícil hablar de ello.", "Saori"),
    110: ("Estás diciendo que soy rara... ¿Parezco así?", "Kiririn"),
    111: ("Sí, es obvio que estás actuando raro.", "Kuroneko"),
    112: ("Como pensé, ¿algo pasó durante nuestro último chat?", "Saori"),
    113: ("...Bueno, no puedo recordarlo bien... ¿qué pasó exactamente?", "Kiririn"),
    114: ("Hmm, si no puedes recordar, puedo contarte sobre ello, pero...", "Saori"),
    116: ("¡Más bien, cómo pudo haberse ido al viaje escolar sin jugar 【Sis×Sis】!", "Kiririn"),
    117: ("Bueno bueno, así como tú tienes tu propia vida escolar, Kiririn-san, creo que el hermano mayor Kyousuke también tiene su propia vida.", "Saori"),
    118: ("Hmph. Para empezar, la razón por la que estás enojada no es realmente porque él no jugó el juego, ¿verdad?", "Kuroneko"),
    119: ("¡¿Q-Qué estás diciendo?!", "Kiririn"),
    120: ("¿Estás tan molesta porque tu amado hermano ha sido arrebatado por Belfegor? Tu kung fu no fue suficiente.", "Kuroneko"),
    121: ("¿Huh? Estoy bien incluso sin él aquí.", "Kiririn"),
    122: ("Bueno... Es mejor tenerlo aquí que no tenerlo. Solo un poco.", "Kiririn"),
    123: ("Bueno, tengo a Rinko-rin de 【Sis×Sis】 conmigo.", "Kiririn"),
    124: ("...Una siscon al extremo, eh. Ese fetiche pervertido de hermanita tuyo está más allá de la ayuda.", "Kuroneko"),
    125: ("¡Tú también entenderás completamente la maravilla de una hermanita si escuchas ese diálogo divino en la ruta de Rinko-rin!", "Kiririn"),
    126: ("...【Siempre te he amado, siempre te he amado】, ¿verdad?", "Kuroneko"),
    127: ("¡Sí, sí, sí. Deja una impresión tan fuerte!", "Kiririn"),
    128: ("...Acabo de ver tu final. Perdiendo de vista los límites entre 2D y 3D, encontrarás un final miserable retorciéndote en la desesperación.", "Kuroneko"),
    129: ("Aaaahyouqawsedrftgyhujikol.", "Kiririn"),
    130: ("Y después de eso, Kiririn-san no respondió más por un tiempo.", "Saori"),
    131: ("No hubo otras entradas después de eso... Estaba realmente preocupada.", "Saori"),
    132: ("...", "Kiririn"),
    133: ("...¿Podría ser que algo pasó después de eso, Kiririn-san?", "Saori"),
    134: ("He terminado de absorber el conocimiento de esa enciclopedia en mi mundo interior. Ya no tengo ningún interés en ese artículo cuya forma solo puede ser", "Kuroneko"),
    135: ("llamada un libro.", "Kuroneko"),
    136: ("Bueno bueno, el hermano mayor Kyousuke casi no tenía experiencia con la versión arcade, así que es irrazonable desear que sea mejor que eso", "Saori"),
    137: ("en el poco tiempo que tuvo.", "Saori"),
}

a71_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo No Ayude A Mi Hermanita",
    5: "Te ves muy feliz aquí, pero...",
    6: "La tú actual ha olvidado todos estos recuerdos felices...",
}
a71_s = {
    1: ("Ahh, cierto, cierto. ¿No nos tomamos también una foto de la cabina de stickers fotográficos durante la reunión fuera de línea en la que se tomó esa foto del celular?", "Saori"),
    2: ("Descargué los datos de la imagen en mi computadora después, así que aprovecharé esta oportunidad para enviársela a las dos también.", "Saori"),
    3: ("¿E-Esto es...?", "Kyousuke"),
    4: ("Kirino...", "Kyousuke"),
    7: ("Maldición... Definitivamente haré que lo recuerdes...", "Kyousuke"),
    8: ("¿Cómo está? ¿Te gusta?", "Saori"),
    9: ("S-Sí. Gracias por enviármela.", "Kiririn"),
    10: ("Esa fue la primera vez que te vi retozando de manera bastante desagradable.", "Kuroneko"),
    11: ("¿Oh cielos? ¿No estaba Kuroneko-san también no tan insatisfecha como trataba de parecer en ese entonces?", "Saori"),
    12: ("¿C-Cómo es eso posible?", "Kuroneko"),
    13: ("No, tanto Kiririn-san como Kuroneko-san estaban tan animadas en ese momento. Pero, ¿qué le pasa a... la Kiririn-san actual?", "Saori"),
}

data = {
    "000scriptBKIR_0060A.obj": build(a60_n, a60_s),
    "000scriptBKIR_0063T.obj": build(a63_n, a63_s),
    "000scriptBKIR_0065A.obj": build(a65_n, a65_s),
    "000scriptBKIR_0070A.obj": build(a70_n, a70_s),
    "000scriptBKIR_0071G.obj": build(a71_n, a71_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))