import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0150_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko 2",
    1: "Unos días han pasado en un abrir y cerrar de ojos desde que empecé mi trabajo como asistente.",
    2: "Durante ese tiempo, he notado todo tipo de cosas.",
    3: "Los amigos tienen lados más sorprendentes de lo que pensaba inicialmente.",
    4: "La capacidad de concentración de Kuroneko es realmente buena. ¿Cuántas horas puede dibujar continuamente?",
    5: "Si fuera yo, definitivamente sería imposible concentrarme así... es lo que solía pensar en el pasado...",
    6: "He estado trabajando junto con Kuroneko, ¿verdad? Estoy siendo inspirado por ella.",
    13: "Debería ser un buen hijo de vez en cuando.",
    16: "Muy bien, entonces terminaré esto rápidamente.",
    23: "Sin embargo, bueno... si este pequeño acto la hace tan feliz, supongo que no está tan mal después de todo.",
    27: "Guh... bueno, aunque soy consciente de eso también...",
    28: "Sin embargo, no creo que sea bueno contarle esto a mi propia madre. Se siente un poco embarazoso... o mejor dicho, ¿definitivamente me tomaría el pelo?",
    29: "Mamá y Papá son diferentes, seguramente se esparcirá sin control una vez que se lo cuente, y no puedo imaginar los resultados...",
    30: "Contra una madre, no es como si le fuera a dar material para que se burle de mí.",
    48: "Se siente un poco embarazoso cuando ella lo pone así...",
    54: "Ya lo noté un poco cuando ayudé en la creación de ese juego la última vez... Pero esta vez, estuve más involucrado en el proceso...? En comparación con la última vez, yo",
    55: "realmente pude sentirlo esta vez.",
}
a0150_s = {
    7: ("¿Kyousuke～, podrías ayudarme a lavar los platos?", "Yoshino"),
    8: ("...Mamá, voy al lugar de siempre, ¿sabes?", "Kyousuke"),
    9: ("¿No puedes ayudarme solo un poco? No tomará más de cinco minutos.", "Yoshino"),
    10: ("Si no toma tanto tiempo, deberías hacerlo tú misma...", "Kyousuke"),
    11: ("Pero, parece que tienes mucho tiempo libre en tus manos.", "Yoshino"),
    12: ("Tch, supongo que no hay otra opción...", "Kyousuke"),
    14: ("Solo lavarlos será suficiente, ¿verdad?", "Kyousuke"),
    15: ("Sí, cuento contigo.", "Yoshino"),
    17: ("Oh, ¿incluso secaste todos los platos? ¡Gracias!", "Yoshino"),
    18: ("Hmm, bueno, si es solo esto...", "Kyousuke"),
    19: ("Hmm-hmm, Mamá está realmente feliz de que te hayas vuelto tan amable.", "Yoshino"),
    20: ("Uh... bueno, es solo esto poquito...", "Kyousuke"),
    21: ("Bien bien. Entonces cuento contigo la próxima vez también.", "Yoshino"),
    22: ("¡Oye...!", "Kyousuke"),
    24: ("...Supongo que está bien de vez en cuando.", "Kyousuke"),
    25: ("Ya veo. Gracias, Kyousuke.", "Yoshino"),
    26: ("Hablando de eso, ¿no has estado actuando un poco raro últimamente?", "Yoshino"),
    31: ("No seguiré ayudándote si sigues tratando de halagarme.", "Kyousuke"),
    32: ("Vaya, vaya, no estoy haciendo esas cosas.", "Yoshino"),
    33: ("Ya es hora de todos modos, ¡tengo que irme ya!", "Kyousuke"),
    34: ("...En serio. Bueno bueno, cuídate. Saluda a tu novia de mi parte～", "Yoshino"),
    35: ("Como dije, no es mi novia...", "Kyousuke"),
    36: ("Parece que tengo una kohai muy trabajadora.", "Kyousuke"),
    37: ("Ajá.", "Yoshino"),
    38: ("Pensé en ayudarla. Por eso sentí que necesitaba ser trabajador también.", "Kyousuke"),
    39: ("Hmm～", "Yoshino"),
    40: ("Esa fue una respuesta bastante escasa...", "Kyousuke"),
    41: ("Así que, estaba pensando «Ya que no tengo nada que hacer, ¿qué puedo hacer?».", "Kyousuke"),
    42: ("Ah, ¿en serio?", "Yoshino"),
    43: ("¿Por qué estás tan sorprendida?", "Kyousuke"),
    44: ("Es porque siento que Kyousuke ya está haciendo 【las cosas que deben hacerse】.", "Yoshino"),
    45: ("...¿Eh?", "Kyousuke"),
    46: ("Parece que has estado bastante feliz últimamente, ¿no? Se ve como si te estuvieras moviendo hacia una meta.", "Yoshino"),
    47: ("¿E-Es así?", "Kyousuke"),
    49: ("Esa niña, no creo que sea solo una kohai para ti, ¿verdad?", "Yoshino"),
    50: ("¿Q-Qué estás diciendo de repente...?", "Kyousuke"),
    51: ("No subestimes los ojos de tu madre, ¿de acuerdo? Puedo ver a través de todo lo tuyo.", "Yoshino"),
    52: ("Guh... ¡M-Me estoy haciendo tarde! ¡Me voy!", "Kyousuke"),
    53: ("Vaya, vaya, huyó...", "Yoshino"),
}

a0160_n = {
    0: "Ruta de Kuroneko · La Asistente De Kuroneko 2",
    1: "...Esto es algo que ocurrió durante el trabajo.",
    17: "Esta es una responsabilidad bastante pesada...",
}
a0160_s = {
    2: ("...Ah.", "Kuroneko"),
    3: ("¿Hmm? ¿Qué pasa?", "Kyousuke"),
    4: ("No es nada. Solo pensé en algo que tenía que hacer.", "Kuroneko"),
    5: ("¿En serio? En ese caso, ¿qué tal si paramos aquí por hoy?", "Kyousuke"),
    6: ("No, se terminará rápido. Por favor continúa con tu trabajo.", "Kuroneko"),
    7: ("¿Eh, está bien para ti?", "Kyousuke"),
    8: ("¿Por qué? ¿No es muy ineficiente si solo esperas aquí?", "Kuroneko"),
    9: ("No, pero... ¿no sería terrible si cometiera un error mientras no estás...", "Kyousuke"),
    10: ("Ah, así que ese es el problema...", "Kuroneko"),
    11: ("A partir de ahora, ciertamente no eres digno de ser llamado un asistente capaz...", "Kuroneko"),
    12: ("No estás aquí solo para cometer errores, ¿verdad?", "Kuroneko"),
    13: ("¡S-Sí! ¿No es obvio?", "Kyousuke"),
    14: ("Si ese es el caso, entonces haz tu trabajo con confianza. Eso es todo lo que puedo decir.", "Kuroneko"),
    15: ("Cuento contigo por el momento.", "Kuroneko"),
    16: ("...Entendido. Déjamelo a mí.", "Kyousuke"),
}

a0165_n = {
    0: "Ruta de Kuroneko · Relajándome En Su Habitación",
    1: "¿Cuándo volverá Kuroneko...?",
    2: "Después de eso, ella sí regresó una vez---",
    5: "Aunque fue lo que dijo...",
    7: "¿Qué está haciendo? No creo que haya salido de la casa...",
}
a0165_s = {
    3: ("Uf... Sudé un poco.", "Kuroneko"),
    4: ("Lo siento, tendré que irme de nuevo. No debería tomar mucho tiempo esta vez.", "Kuroneko"),
    6: ("Dijo que no tomaría mucho tiempo esta vez, pero seguro que ha pasado un buen rato...", "Kyousuke"),
    8: ("¿Oye～ Kuroneko～? ¿Dónde estás～?", "Kyousuke"),
    9: ("Sin respuesta...", "Kyousuke"),
    10: ("¿Kuroneko～?", "Kyousuke"),
    11: ("¿Eh...?", "Kyousuke"),
    12: ("...¿En la ducha...?", "Kyousuke"),
    13: ("*tragar saliva*", "Kyousuke"),
    14: ("Ah...", "Kyousuke"),
    15: ("¿Eh...?", "Kuroneko"),
    16: ("¿P-Por qué estás aquí...?", "Kuroneko"),
    17: ("N-No... Bueno...", "Kyousuke"),
    18: ("¿P-Para qué estás aquí...?", "Kuroneko"),
    19: ("Ah... Bueno～...", "Kyousuke"),
    20: ("¿P-P-Podría... ser, que...", "Kuroneko"),
    21: ("¿C-Cómo podría...? ¡No haría algo así como espiar...!", "Kyousuke"),
    22: ("...¿E-Espiar...?", "Kuroneko"),
    23: ("...Eres lo peor. Te desprecio.", "Kuroneko"),
    24: ("Ah, sobre esto... ¿Kuroneko-san?", "Kyousuke"),
    25: ("¿Qué? Bajo tales circunstancias, si tienes algo que decir para que te perdone, más vale que lo digas.", "Kuroneko"),
    26: ("Tampoco deseo entregar a alguien que conozco a la policía...", "Kuroneko"),
    27: ("¡No, no estaba espiando! ¡Tampoco soy un criminal atrapado en el acto! ¡Solo pasé por aquí!", "Kyousuke"),
    28: ("¿Y solo empezaste a escuchar aquí...?", "Kuroneko"),
    29: ("N-No... Aunque es como dices al final...", "Kyousuke"),
    30: ("...Ya veo. No me extraña que una vez te llamaran «el senpai del acoso sexual».", "Kuroneko"),
    31: ("G-Guh...", "Kyousuke"),
    32: ("...Ahora me voy a cambiar de ropa.", "Kuroneko"),
    33: ("S-Sí...", "Kyousuke"),
    34: ("Por favor, regresa y continúa tu trabajo.", "Kuroneko"),
    35: ("L-Lo entiendo.", "Kyousuke"),
    36: ("Al mismo tiempo, olvida todo lo que acabas de ver.", "Kuroneko"),
    37: ("Ah, ¿eh? E-Eso es un poco difícil...", "Kyousuke"),
    38: ("Puedo ayudarte a olvidar todo si no puedes hacerlo tú mismo.", "Kuroneko"),
    39: ("Por suerte, aquí mismo hay algo convenientemente usado como herramienta de tortura llamado «agua».", "Kuroneko"),
    40: ("¡L-Lo entiendo, lo olvidaré! ¡Puedo olvidarlo! ¡Al menos no se lo contaré a nadie!", "Kyousuke"),
    41: ("Si se lo contaras a alguien...", "Kuroneko"),
    42: ("¡¿D-Dije que no lo haré, no?!", "Kyousuke"),
    43: ("Las llamas del infierno te quemarán. Además, las cenizas quemadas serán dispersadas. Por último, tu alma que no tiene a dónde regresar será purificada...", "Kuroneko"),
    44: ("...Creo que volveré a hacer mi trabajo con cuidado ahora.", "Kyousuke"),
}

a0168_n = {
    0: "Ruta de Kuroneko · Un Breve Periodo De Respiro",
    1: "Y con eso, me concentré en continuar mi trabajo.",
    4: "Eh, ¿alguien llegó a casa?",
    13: "...Parece una niña muy enérgica y linda, igual que una versión mini de Kuroneko. Debería estar todavía en el jardín de infantes, creo.",
    15: "Esta niña vivaz debería estar todavía en la primaria... ¿verdad? Se ve muy sorprendida.",
    45: "¡Qué linda! Es completamente diferente de mi propia hermana.",
    46: "No debo traer a Kirino a esta casa, porque algo malo pasará...",
    51: "...Esta niña se está volviendo demasiado familiar.",
    69: "E-Esta niña---",
    90: "¡Increíble! ¡Esto es echarle leña al fuego!",
    98: "Una hermana Kuroneko enojada es realmente aterradora.",
}
a0168_s = {
    2: ("¡Llegamos～!", "???"),
    3: ("¿Eh?", "Kyousuke"),
    5: ("Hermana, ¿no es un par de zapatos que nunca hemos visto?", "???"),
    6: ("Ah, tienes razón.", "???"),
    7: ("¿Ruri-nee～, vino alguien～?", "???"),
    8: ("¿Podría ser... que son las hermanas de Kuroneko!?", "Kyousuke"),
    9: ("Ah.", "???"),
    10: ("Ah...", "Kyousuke"),
    11: ("...Perdonen la intrusión.", "Kyousuke"),
    12: ("Sí, nos alegra tenerte.", "???"),
    14: ("...¡Woah!", "???"),
    16: ("...¿B-B-Ba...", "Older sis"),
    17: ("¿?", "Kyousuke"),
    18: ("¡¡El novio de Ruri-nee-----------!!", "Older sis"),
    19: ("¡¿Ehh!?", "Kyousuke"),
    20: ("¡¡Guau---! ¡Realmente consiguió novio!!", "Older sis"),
    21: ("¿Q-Q-Qué...", "Kyousuke"),
    22: ("¡He estado pensando que algo anda mal últimamente!", "Older sis"),
    23: ("Diciendo «salgan a jugar hoy», «tres horas... salir de la habitación te evitará ser maldecida por el Rey Demonio para convertirte en la cena de esta noche»... cosas", "Older sis"),
    24: ("así!", "Older sis"),
    25: ("Furtivo furtivo, furtivo furtivo～", "Older sis"),
    26: ("Así que eso es lo que estaba pasando... Ejeje～", "Older sis"),
    27: ("¿Eh～～～～?", "Little sis"),
    28: ("¡N-No es así! ¡Ambas están equivocadas!", "Kyousuke"),
    29: ("¡No soy su novio!", "Kyousuke"),
    30: ("¿Eh? ¿En serio?", "Older sis"),
    31: ("Sí, soy Kousaka Kyousuke. Umm, estoy en el mismo club que tu hermana, mucho gusto.", "Kyousuke"),
    32: ("¡Woah! ¡He escuchado ese nombre antes!", "Older sis"),
    33: ("¿Eh?", "Kyousuke"),
    34: ("¡¿Entonces eres el hermano de esa 'perra' que siempre se pelea con Ruri-nee por teléfono, verdad!?", "Older sis"),
    35: ("Sí, soy yo, sin duda.", "Kyousuke"),
    36: ("...Kirino. Te están recordando de una manera muy notable por las hermanas de Kuroneko, ¿sabes?", "Kyousuke"),
    37: ("Bueno... ¿puedo llamarte el hermano de la perra?", "Older sis"),
    38: ("¡Para nada! ...Llámame de otra manera.", "Kyousuke"),
    39: ("¿Ehh～? Bueno entonces...", "Older sis"),
    40: ("Hermano mayor.", "Little sis"),
    41: ("¿Eh?", "Kyousuke"),
    42: ("Hermano mayor～", "Little sis"),
    43: ("A-Ahh...", "Kyousuke"),
    44: ("Ejeje.", "Little sis"),
    47: ("Solo te llamaré Kousaka-kun por ahora.", "Older sis"),
    48: ("Sí, está bien.", "Kyousuke"),
    49: ("Oye, oye, Kousaka-kun.", "Older sis"),
    50: ("¿Hmm? ¿Qué pasa?", "Kyousuke"),
    52: ("¿Te casarás con Ruri-nee?", "Older sis"),
    53: ("*atragantarse*", "Kyousuke"),
    54: ("¡¿C-Cómo es posible! Ya dije que no soy su novio, ¿no?", "Kyousuke"),
    55: ("¿Eh～? Pero...", "Older sis"),
    56: ("Ruri-nee lo mencionó antes, creo que dijo que deberías ser tú, Kousaka-kun, ¿verdad?", "Older sis"),
    57: ("¿C-Cómo lo dijo?", "Kyousuke"),
    58: ("«...Hmph... no me tomes por tonta. Yo también tengo a un chico... que ha formado un 'contrato' conmigo.»", "Older sis"),
    59: ("«Su nombre en este mundo es 'Kyousuke'. Mientras yo era todavía la Bestia Negra en el pasado, él es una bestia feroz que una vez se emparejó conmigo...»", "Older sis"),
    60: ("¿Qué le contó esa tonta a sus propias hermanas...?", "Kyousuke"),
    61: ("Inicialmente asumí que ese novio en su mente era 2D...", "Older sis"),
    62: ("Eres realmente demasiado cruel.", "Kyousuke"),
    63: ("¡No pensé que realmente existirías! ¡Realmente me tomó por sorpresa! ¡A-Así que entonces! ¿Qué era ese 'contrato'...? ¿De qué se trataba? ¡Hyah～①", "Older sis"),
    64: ("No sé qué estás imaginando, ¡pero es todo un malentendido!", "Kyousuke"),
    65: ("Entonces, ¿de qué se trataba ese 'contrato'?", "Older sis"),
    66: ("...N-No sé.", "Kyousuke"),
    67: ("Es un beso, ¿verdad?", "Little sis"),
    68: ("¡?!?!", "Kyousuke"),
    70: ("¿Q-Qué era todo ese alboroto... u-ustedes---dos...", "Kuroneko"),
    71: ("Ah, se petrificó.", "Older sis"),
    72: ("E-Esto... ¿cuál es el significado de esto?", "Kuroneko"),
    73: ("...Es como ves.", "Kyousuke"),
    74: ("...!! Kuh...", "Kuroneko"),
    75: ("Hu... Kukuku... Ustedes dos... Les dije que les permitía jugar afuera hasta el atardecer, ¿no? ¿Por qué están aquí?", "Kuroneko"),
    76: ("Pero hace calor afuera, ¿no～?", "Older sis"),
    77: ("¿Verdad que sí～?", "Little sis"),
    78: ("Hmm... ¿eso es todo lo que... tienen que decir?", "Kuroneko"),
    79: ("¡Oh no! Ruri-nee está realmente enojada... ¡Por favor sálvanos, Kousaka-kun!", "Older sis"),
    80: ("¡Por favor sálvanos～ Hermano mayor～", "Little sis"),
    81: ("¡N-No me usen como escudo!", "Kyousuke"),
    82: ("Vaya.. Parece que te llevas bastante bien con ellas.", "Kuroneko"),
    83: ("...Por favor piensa en algo para calmarla, es tu hermana mayor, ¿verdad?", "Kyousuke"),
    84: ("¡Muy bien, déjamelo a mí!", "Older sis"),
    85: ("¡Tengo una pregunta para Ruri-nee!", "Older sis"),
    86: ("...¿Qué?", "Kuroneko"),
    87: ("¿Ruri-nee se bañó con la intención de formar un 'contrato' con Kousaka-kun?", "Older sis"),
    88: ("Qué...", "Kuroneko"),
    89: ("Ejeje, la molestamos sin saberlo--- ¡y por eso estás enojada!", "Older sis"),
    91: ("............", "Kuroneko"),
    92: ("...Hmph.", "Kuroneko"),
    93: ("¿Ku-Kuroneko...?", "Kyousuke"),
    94: ("Lo siento por esto, senpai. Parece que tendré que disculparme de nuevo.", "Kuroneko"),
    95: ("No tengo más remedio que darle una lección a mi hermana ahora mismo.", "Kuroneko"),
    96: ("...A-Adelante.", "Kyousuke"),
    97: ("¡Noooooooo～～!", "Older sis"),
}

a0170_n = {
    0: "Ruta de Kuroneko · La Prueba De Dios",
    1: "Y así, el trabajo progresó sin problemas.",
    2: "Si nos apegamos al horario, estaremos bastante ocupados. Pero deberíamos lograrlo si mantenemos este ritmo.",
    3: "Pero los accidentes de verdad probablemente empezarán a ocurrir en momentos como estos...",
    11: "Pen tab -- abreviación de Pen Tablet.",
    12: "Para aclarar, es una herramienta indispensable usada para dibujar en la computadora sin el mouse pero con un lápiz óptico. La forma se parece a un lápiz real.",
    24: "Participar en el evento e imprimir materiales parece ser costoso también.",
    26: "Eso es, no queda suficiente tiempo...",
    27: "Bajo tales circunstancias, la mejor solución es...",
    39: "Maldición, ¿qué está haciendo...? Haciendo lo que le plazca, solo está hablando consigo misma ahí...",
    63: "Esa mirada está diciendo, no se permiten mentiras...",
    68: "Yo... nunca consideré esto...",
    69: "No, NO podía considerarlo.",
    70: "Poner mi relación con Kuroneko en palabras... Nunca pude expresarla correctamente, siempre posponiéndolo...",
    71: "Y ahora tengo que responderle...",
    72: "Yo... ¿Puedo encontrar una buena respuesta?",
    73: "No sirve...",
    74: "No puedo encontrarla...",
    75: "Pero Kuroneko todavía está esperando...",
    76: "Todavía es muy temprano para rendirse...",
    77: "Déjame calmarme y pensar en ello de nuevo...",
    78: "¿Estoy seguro de que existe?",
    79: "No hay manera de que no exista, ¿verdad? Algo que describa mi relación con Kuroneko...",
    80: "Eso es...",
    81: "Esta respuesta, al menos no será un error.",
    86: "Se siente como si estuviera cometiendo un error... o soy yo quien está en negación...",
    87: "Sin embargo, siento que esta es la mejor respuesta que podría dar.",
    91: "Creo que esta es la mejor manera de ponerlo... de lo que puedo pensar...",
    98: "Huh... Pensé que ella respondería con una risa fría de inmediato como antes...",
    107: "¿Kuroneko me abofeteó...?",
    108: "Espera Kuroneko, no tenía esa intención...",
    109: "El dolor en mi mejilla, realmente no tiene ningún sentimiento...",
    110: "En comparación con eso, mi corazón duele aún más.",
    111: "Kuroneko está llorando. Y yo pasé a ver esto. No solo eso...",
    112: "La persona que la hizo llorar... fui yo.",
    113: "Pensé en hacer un chiste aburrido y no esperaba que la lastimara, es todo culpa mía...",
    115: "...Kuroneko se fue...",
    116: "Pero yo... no tengo el derecho de ir tras ella.",
    117: "Porque, el que la hizo llorar, fui yo.",
    118: "Esa es una pregunta que no se puede responder mal, y aun así lo hice...",
    120: "...Maldición...",
    121: "Parece que, yo... pisé una mina terrestre...",
    123: "A esa pregunta, no soy capaz de dar una respuesta...",
}
a0170_s = {
    4: ("No puede ser...", "Kuroneko"),
    5: ("¿Qué? ¿Qué pasa, Kuroneko?", "Kyousuke"),
    6: ("En este momento... Cómo... podría ser...", "Kuroneko"),
    7: ("O-Oye... ¿Kuroneko? ¿Qué pasó exactamente?", "Kyousuke"),
    8: ("...Parece que a Dios le encanta ponerme a prueba.", "Kuroneko"),
    9: ("La tableta gráfica murió.", "Kuroneko"),
    10: ("...¿Huh?", "Kyousuke"),
    13: ("Por eso, no hay manera de continuar dibujando el manuscrito así.", "Kuroneko"),
    14: ("¿Estás... hablando en serio?", "Kyousuke"),
    15: ("¿N-No tienes repuestos? Dijiste que tenías maneras de lidiar con los problemas, ¿verdad?", "Kyousuke"),
    16: ("Incluso esto es demasiado inesperado. Además, comprar una tableta gráfica de repuesto para esto era demasiado costoso...", "Kuroneko"),
    17: ("En ese caso, ¿qué tal si pedimos prestada...? Eso es, Saori debería tener una, ¿verdad?", "Kyousuke"),
    18: ("Imposible. Aunque tiene una tableta gráfica, la dejó tal cual cuando se descompuso.", "Kuroneko"),
    19: ("Cuando fuimos a Akihabara el otro día a comprar cosas, Saori fue específicamente a mirar vitrinas por una nueva.", "Kuroneko"),
    20: ("¡¿Qué tal el salón del club!?", "Kyousuke"),
    21: ("Imposible. Un miembro del club obsesionado con el BL la ha tomado prestada.", "Kuroneko"),
    22: ("Entonces, ¿qué tal comprar una nueva---", "Kyousuke"),
    23: ("Entonces volvemos a la casilla uno, no tengo el dinero. El boleto de tren de ese día ya estaba apretado.", "Kuroneko"),
    25: ("Si tomamos un trabajo de medio tiempo... Espera, es imposible en este momento...", "Kyousuke"),
    28: ("En ese caso, ayudaré con el dinero. Deberíamos poder empezar a trabajar de esa manera, ¿verdad?", "Kyousuke"),
    29: ("Aunque no me sorprende que digas eso... Es un no.", "Kuroneko"),
    30: ("¿Por qué? ¿No es esta la mejor solución al problema? ¿A menos que haya otras maneras?", "Kyousuke"),
    31: ("¿Quién sabe? No puedo pensar en ninguna ahora mismo. Sin embargo, no deseo usar esta solución.", "Kuroneko"),
    32: ("Como dije, ¿por qué?", "Kyousuke"),
    33: ("Lo he dicho antes. Este es 'mi' trabajo. Por esa razón, no puedo usar el dinero de alguien más, mi orgullo no lo permitirá.", "Kuroneko"),
    34: ("¡¿Sigues diciendo esto cuando ya hemos llegado tan lejos!?", "Kyousuke"),
    35: ("Por supuesto que debo hacerlo. ¿No lo entiendes? Esta actividad es puramente un pasatiempo. Por esta razón, si es algo que no puedo aceptar, entonces no tiene significado.", "Kuroneko"),
    36: ("¡¿Qué...!", "Kyousuke"),
    37: ("Por eso no tomaré prestado tu dinero.", "Kuroneko"),
    38: ("Si todo lo demás falla, venderé cosas para reunir el dinero. Ese es el valor de este manuscrito para mí.", "Kuroneko"),
    40: ("...Eso es...", "Kyousuke"),
    41: ("¿Eh?", "Kuroneko"),
    42: ("...¡Eso es lo mismo para mí también!", "Kyousuke"),
    43: ("...¿Qué? ¿A qué te refieres?", "Kuroneko"),
    44: ("Estoy diciendo que este pedazo de manuscrito tiene el mismo valor para mí también.", "Kyousuke"),
    45: ("...¿Qué estás diciendo? Este manuscrito es mío.", "Kuroneko"),
    46: ("Es verdad que es tuyo. Es algo que dibujaste, por lo tanto es tu propio manuscrito.", "Kyousuke"),
    47: ("Sin embargo, ya no es 'solo' tuyo.", "Kyousuke"),
    48: ("¿Qué? ¿Estás tratando de decir que ya que ayudaste, se ha vuelto tuyo también?", "Kuroneko"),
    49: ("Qué impactante... Por favor conoce tu lugar.", "Kuroneko"),
    50: ("Es verdad que lo que he hecho es meramente poco. Y es algo simple que cualquiera podría hacer.", "Kyousuke"),
    51: ("No es nada comparado con lo que tú has hecho. Bajo tales circunstancias, no diré cosas como «también es mío».", "Kyousuke"),
    52: ("Sin embargo, ¡no perderé contra ti en querer completar este manuscrito!", "Kyousuke"),
    53: (".........", "Kuroneko"),
    54: ("......Jeh.", "Kuroneko"),
    55: ("Por Dios, gente como tú... Entonces planeas imponer tu voluntad otra vez?", "Kuroneko"),
    56: ("Eso es todo lo que puedo hacer...", "Kyousuke"),
    57: ("Ciertamente, estoy de acuerdo... Eso es todo lo que tienes. Desafortunadamente, no tengo intención de cambiar de opinión.", "Kuroneko"),
    58: ("Aunque... Sí. Si pudieras responder esta pregunta mía, podría considerarlo.", "Kuroneko"),
    59: ("¡¿E-En serio!?", "Kyousuke"),
    60: ("Sí. Siempre que puedas responderla, por supuesto.", "Kuroneko"),
    61: ("...Sin importar qué sea, te daré una respuesta.", "Kyousuke"),
    62: ("¿Lo dudas?", "Kuroneko"),
    64: ("¿Por qué estás... llegando tan lejos?", "Kuroneko"),
    65: ("¿No te estás preparando para los exámenes? ¿Se supone que debes estar aquí haciendo esto? ¿Entiendes tu propia situación?", "Kuroneko"),
    66: ("Y aun así, ¿por qué... llegas tan lejos por mí?", "Kuroneko"),
    67: ("¿Qué soy... para ti?", "Kuroneko"),
    82: ("Una amiga importante.", "Kyousuke"),
    83: ("No solo Kirino... para mí también, eres una amiga importante que es irremplazable.", "Kyousuke"),
    84: ("¿En serio, una amiga...", "Kuroneko"),
    85: ("Así que somos amigos... eso es. Supongo que tenemos ese tipo de relación...", "Kuroneko"),
    88: ("...¿Como una hermanita, supongo?", "Kyousuke"),
    89: ("*suspiro*", "Kuroneko"),
    90: ("¿Cuánto más quieres insultarme?", "Kuroneko"),
    92: ("Eres mi kohai.", "Kyousuke"),
    93: ("Como tu senpai, tengo que cuidarte, ¿sabes?", "Kyousuke"),
    94: ("Tú...", "Kuroneko"),
    95: ("¿Te estás aferrando a mí basándote en ese nivel de relación?", "Kuroneko"),
    96: ("Para una gata indómita, debe haber un amo para ella, ¿verdad?", "Kyousuke"),
    97: ("Guh...", "Kuroneko"),
    99: ("...¿Kuroneko?", "Kyousuke"),
    100: ("Ya veo...", "Kuroneko"),
    101: ("...No te preguntaré, por qué elegirías decir eso.", "Kuroneko"),
    102: ("Pero ya has arruinado mi humor... ¿lo entiendes?", "Kuroneko"),
    103: ("Pensé que serías una persona capaz de tomar una decisión... por más estúpido que fueras... qué decepcionante.", "Kuroneko"),
    104: ("Manteniendo las apariencias con tus palabras, sin significado en ellas... No, a veces se convertirán en una espada que te destruirá a ti mismo, recuerda esto", "Kuroneko"),
    105: ("con tu cuerpo...", "Kuroneko"),
    106: (".........!", "Kyousuke"),
    114: ("...No te atrevas a volver a mostrarme tu cara---", "Kuroneko"),
    119: ("................................", "Kuroneko"),
    122: (".........", "Kyousuke"),
}

data = {
    "000scriptCKUR_0150A.obj": build(a0150_n, a0150_s),
    "000scriptCKUR_0160A.obj": build(a0160_n, a0160_s),
    "000scriptCKUR_0165G.obj": build(a0165_n, a0165_s),
    "000scriptCKUR_0168A.obj": build(a0168_n, a0168_s),
    "000scriptCKUR_0170A.obj": build(a0170_n, a0170_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
