import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a0073_n = {
    0: "Ruta de Saori · La Resolución Es Esencial",
    3: "Mierda... solo está echando leña al fuego...",
    4: "¡Tengo que hacer algo para sacar a Kirino de su mal humor...!",
    5: "Pero, si lo arruino, ella se enojará conmigo en su lugar.",
    6: "Solo tendré que callarme y ver cómo se desarrolla esto.",
    12: "Después de sus duras palabras, Kirino giró la cabeza hacia Saori.",
    18: "Esa risa seca sonaba como si se estuviera sofocando...",
}
a0073_s = {
    1: ("*suspiro*...", "Kirino"),
    2: ("Todos son tan molestos...", "Kirino"),
    7: ("Kirino, yo...", "Kyousuke"),
    8: ("Tú mantén la boca cerrada. Este es el problema de Saori, ¿verdad?", "Kirino"),
    9: ("Bueno sí, eso es verdad, pero...", "Kyousuke"),
    10: ("Kyousuke-shi, no tienes que cubrirme.", "Saori"),
    11: ("Después de todo, yo soy la que está en falta.", "Saori"),
    13: ("Oye...", "Kirino"),
    14: ("Tienes que aceptar el hecho de que 【amas los hobbies otaku】.", "Kirino"),
    15: ("¿Alguien gana algo con que te mientas a ti misma?", "Kirino"),
    16: ("Kiririn-shi...", "Saori"),
    17: ("Pero, ya he decidido... ahaha...", "Saori"),
    19: (".........Ya veo.", "Kirino"),
    20: ("Bueno, entonces he terminado.", "Kirino"),
    21: ("Oye, espera Kirino.", "Kyousuke"),
    22: ("...¿Qué?", "Kirino"),
    23: ("No te limites a decir «Ya veo». ¿Acaso Saori no sigue siendo tu amiga?", "Kyousuke"),
    24: ("......", "Kirino"),
    25: ("Bueno, esa «amiga» no escucha, así que no hay nada que pueda hacer.", "Kirino"),
    26: ("Por eso he terminado.", "Kirino"),
    27: ("Kirino...", "Kyousuke"),
    28: ("Kyousuke-shi...", "Saori"),
}

a0075_n = {
    0: "Ruta de Saori · La Resolución Es Esencial",
}
a0075_s = {
    1: ("Te estoy en deuda, Kyousuke-shi...", "Saori"),
    2: ("Me has dado una gran ayuda, y aun así, todo se convertirá en nada...", "Saori"),
    3: ("¡Pero todavía no se ha convertido en nada!", "Kyousuke"),
    4: ("Así de fuerte es tu voluntad.", "Saori"),
    5: ("Solo el hecho de que pienses así me hace sentir bendecida.", "Saori"),
    6: ("No solo lo pienso. Tengo la intención de hacer algo.", "Kyousuke"),
    7: ("Esas son palabras muy prometedoras.", "Saori"),
    8: ("Aunque, mi espíritu es como una llama agonizante en el viento ahora...", "Saori"),
    9: ("Es lo mismo incluso si tienes resultados. No hay nada que se pueda hacer.", "Saori"),
    10: ("Jaja... Es verdaderamente un esfuerzo vano.", "Saori"),
    11: ("Creo que no importa cuánto me disculpe, tengo que quitarme el sombrero ante ti.", "Saori"),
    12: ("Pero, realmente no he hecho nada...", "Kyousuke"),
    13: ("Aun así, el hecho de que intentaste ayudarme permanece.", "Saori"),
    14: ("Termina hoy. Oficialmente eres un hombre libre.", "Saori"),
    15: ("¿Saori...?", "Kyousuke"),
    16: ("...Después de la boda... te enviaré una carta...", "Saori"),
    17: ("Una carta mostrando cuán... feliz soy con él.", "Saori"),
    18: ("¡Entonces la haré pedazos y me la comeré antes de siquiera leerla!", "Kyousuke"),
    19: ("Kyousuke-shi, eso es lo que hacen las cabras blancas y las cabras negras.", "Saori"),
    20: ("¿Exactamente cuándo se ha convertido mi amigo en una cabra?", "Saori"),
    21: ("Si todavía piensas en mí como un amigo, entonces deja de hacer bromas de las que no puedo reírme.", "Kyousuke"),
    22: ("¿Dónde encuentras diversión en engañar a tu amigo y hacer que se preocupe?", "Kyousuke"),
    23: ("No te estoy engañando... Estoy tratando de mostrarte mi sinceridad.", "Saori"),
    24: ("¿Estás diciendo que tienes la resolución para casarte?", "Kyousuke"),
    25: ("Si no tengo resolución, entonces no puedo progresar como un samurái.", "Saori"),
    26: ("Espera, eres una otaku, no una samurái.", "Kyousuke"),
    27: ("Eso también termina hoy. De ahora en adelante, soy una novia.", "Saori"),
    28: ("Una novia muy feliz...", "Saori"),
    29: ("¡No necesito tu falsa sinceridad!", "Kyousuke"),
    30: ("La sinceridad es pensar en cómo se siente la otra persona, ¿verdad?", "Kyousuke"),
    31: ("Si dejas de ser otaku, y dejas de ser nuestra amiga...", "Kyousuke"),
    32: ("¿De verdad crees que lo estás haciendo por nuestro bien?", "Kyousuke"),
    33: ("...Mis disculpas.", "Saori"),
    34: ("¡Estoy harto de escucharte disculparte!", "Kyousuke"),
    35: ("Intenta decir algo diferente de vez en cuando.", "Kyousuke"),
    36: ("¡Dime «¡Cuento contigo!» o «¡Dame una mano!» o algo así!", "Kyousuke"),
    37: ("...", "Saori"),
    38: ("¡Por favor no te rindas! ¡Si te rindes, entonces todo habrá terminado!", "Kyousuke"),
    39: ("...he escuchado...", "Saori"),
    40: ("¿Saori?", "Kyousuke"),
    41: ("¿Cuántas veces he escuchado que digas, «No te rindas»?", "Saori"),
    42: ("...Aunque, es extraño. No me he cansado de escucharlo.", "Saori"),
    43: ("...No te disculpes. No has hecho nada malo.", "Kyousuke"),
    44: ("Tampoco he hecho nada bien.", "Saori"),
    45: ("No te auto-desprecies tanto. Estás haciendo lo mejor que puedes.", "Kyousuke"),
    46: ("Fufu... Siempre eres así.", "Saori"),
    47: ("Ja... ¡Jajaja!", "Saori"),
    48: ("¿Q-Qué pasa? Riendo de repente así...", "Kyousuke"),
    49: ("Bueno, cuando uno lo considera, ¡es matrimonio! El sueño máximo de toda chica.", "Saori"),
    50: ("¡En el momento en que me convierta en novia, seré más feliz que nadie!", "Saori"),
    51: ("Más feliz... que nadie...", "Saori"),
    52: ("Saori...", "Kyousuke"),
    53: ("...Realmente lo siento.", "Saori"),
    54: ("¿Por qué te disculpas...? Aún no has hecho nada malo...", "Kyousuke"),
    55: ("Has llegado tan lejos conmigo, no con nadie más, sino conmigo...", "Saori"),
    56: ("Si lo pienso, solo he estado dependiendo de ti.", "Saori"),
    57: ("Creo que es hora de pagar mi deuda.", "Saori"),
}

a0078_n = {
    0: "Ruta de Saori · Penetrado Hasta El Corazón",
    2: "Saori parece estar en su límite...",
    3: "¿Debería decir algo inteligente?",
    8: "Es Saori quien lo dice ahora. Supongo que debería prestarle un oído.",
    24: "Saori... ¿De verdad quiere deshacerse de sus artículos?",
    25: "Pero si no me equivoco, los artículos otaku de Saori...",
    36: "Me quedé atrás, mirando la espalda de la figura de Saori haciéndose cada vez más pequeña.",
    37: "He dicho lo que pude.",
    38: "Incluso las palabras usadas por grandes personas a lo largo de la historia no llegarán a ella ahora.",
    39: "Estaba tan decidida. Era lo suficientemente seria como para hacer que cualquiera pensara eso.",
    41: "No puedo simplemente aceptar esto, ¿verdad?",
    42: "Decir «Está bien, adiós», justo después de fallar tres veces, ¡no puedo aceptar este escenario miserable!",
}
a0078_s = {
    1: ("*suspiro*...", "Saori"),
    4: ("Oye, Saori...", "Kyousuke"),
    5: ("Kyousuke-shi... lo siento...", "Saori"),
    6: ("¿Podrías escuchar lo que tengo que decir?", "Saori"),
    7: ("Ah, claro...", "Kyousuke"),
    9: ("No te esfuerces demasiado, Saori.", "Kyousuke"),
    10: ("¿Kyousuke-shi?", "Saori"),
    11: ("También es doloroso para mí, verte así.", "Kyousuke"),
    12: ("...Fufu. Como era de esperarse, siempre eres tan amable.", "Saori"),
    13: ("Pero, ¿podrías escucharme ahora?", "Saori"),
    14: ("Ah, sí.", "Kyousuke"),
    15: ("Hace una semana, cuando nos encontramos en Akihabara, me dijiste esto.", "Saori"),
    16: ("Dijiste, «Pase lo que pase, nuestra amistad se mantendrá fuerte...»", "Saori"),
    17: ("Tu sinceridad ha llegado a lo profundo de mis órganos internos.", "Saori"),
    18: ("¿Qué es esto, de repente...", "Kyousuke"),
    19: ("Siendo la persona amable que eres, incluso si yo dijera que ya no éramos amigas, probablemente seguirías pensando en mí como una.", "Saori"),
    20: ("Esos sentimientos tuyos son suficientes.", "Saori"),
    21: ("Saori...", "Kyousuke"),
    22: ("Lamento mucho no haber podido aceptar el recuerdo de tu viaje escolar!", "Saori"),
    23: ("Por favor cuídalo bien junto con todos los otros artículos que te di.", "Saori"),
    26: ("Oye, esos artículos otaku no son solo tuyos, ¿verdad?", "Kyousuke"),
    27: ("Sí... entre ellos había cosas de mi hermana mayor y sus amigas.", "Saori"),
    28: ("Incluso para él, no creo que quiera tirar las cosas de otras personas, pero...", "Saori"),
    29: ("Si está bien para ti, me gustaría que guardaras esos...", "Saori"),
    30: ("...Si es de forma temporal, claro. Pero no puedo guardarlos para siempre.", "Kyousuke"),
    31: ("Esa respuesta es suficiente.", "Saori"),
    32: ("...Gracias por todo lo que has hecho.", "Saori"),
    33: ("Los días que he pasado con todos son tesoros que atesoraré toda mi vida. Incluso cuando pierda mis artículos, todavía tendré eso.", "Saori"),
    34: ("Y así...", "Saori"),
    35: ("...Adiós.", "Saori"),
    40: ("Pero...", "Kyousuke"),
    43: ("¡Saori!!", "Kyousuke"),
}

a0080_n = {
    0: "Ruta de Saori · Penetrado Hasta El Corazón",
    17: "Definitivamente puedo decir con solo mirar a Saori que está agotada. Puede romperse si se excede...",
    18: "Pero, si sigue así, definitivamente se romperá algún día...!",
    26: "En otras palabras, no cambiará de opinión... ¡Maldición!",
    40: "Piensa, Kyousuke. Tengo que tener un plan.",
}
a0080_s = {
    1: ("Kyousuke-shi...", "Saori"),
    2: ("No permitiré que te limites a decir «Adiós».", "Kyousuke"),
    3: ("Pero, no hay nada más que decir.", "Saori"),
    4: ("¡Yo todavía tengo, incluso si tú no!", "Kyousuke"),
    5: ("Esa parte tan empeñosa es lo bueno de ti.", "Saori"),
    6: ("Eres bondadoso, entrometido, y serás directo con cualquiera...", "Saori"),
    7: ("Si tan solo pudiera actuar tan imprudentemente...", "Saori"),
    8: ("¡Si eres tú, es posible!", "Kyousuke"),
    9: ("Impo...sible.", "Saori"),
    10: ("...Mis piernas ya se han detenido, y ya no puedo moverme.", "Saori"),
    11: ("¡Si no puedes moverte, tienes que forzarte a moverte!", "Kyousuke"),
    12: ("Si afirmas tus piernas y pones fuerza en tus rodillas, puedes llegar a cualquier parte.", "Kyousuke"),
    13: ("Jajaja, si hiciera eso, me rompería.", "Saori"),
    14: ("...", "Kyousuke"),
    15: ("Estás considerando mis sentimientos y te quedas en silencio...", "Saori"),
    16: ("Realmente eres una persona amable.", "Saori"),
    19: ("¿Hm? ¿Pasa algo, Kyousuke-shi?", "Saori"),
    20: ("Si nos detenemos ahora, tarde o temprano, terminará de la misma manera, ¿verdad?", "Kyousuke"),
    21: ("...", "Saori"),
    22: ("Oye, no entenderé nada si te quedas en silencio.", "Kyousuke"),
    23: ("Lo siento, Kyousuke-shi...", "Saori"),
    24: ("Ah, quiero decir... No tienes que disculparte...", "Kyousuke"),
    25: ("No, entiendo que no puedes simplemente regalar estos sentimientos...", "Saori"),
    27: ("...No puedes pensar en nada que decir, huh. Lo entiendo.", "Kyousuke"),
    28: ("Yo tampoco sé qué decirte.", "Kyousuke"),
    29: ("¿Hoho? ¿También hay momentos en los que te quedas sin palabras?", "Saori"),
    30: ("¿No es obvio?", "Kyousuke"),
    31: ("Más bien, creo que soy peor hablando que tú.", "Kyousuke"),
    32: ("¿Que yo? ...¡Por supuesto que no!", "Saori"),
    33: ("No, no, no, eres increíble con las palabras.", "Kyousuke"),
    34: ("Me explicaste cosas de otaku a mí, un tipo que no sabía nada de eso, de una manera fácil de entender...", "Kyousuke"),
    35: ("Y puedes resolver los conflictos entre Kirino y Kuroneko cuando empiezan a discutir justo al verse, ¿verdad?", "Kyousuke"),
    36: ("¡Kyousuke-shi! ¡Me estás dando demasiados elogios...!", "Saori"),
    37: ("No es solo eso. No puedo contar cuántas veces nos has ayudado.", "Kyousuke"),
    38: ("Eso no es...", "Saori"),
    39: ("Es verdad. Nos salvaste.", "Kyousuke"),
    41: ("Si no tienes nada que decir, me iré ahora.", "Saori"),
    42: ("¡Tengo que hacer los preparativos para convertirme en novia!", "Saori"),
    43: ("¡Espera, no te conviertas en novia, Saori!", "Kyousuke"),
    44: ("¿No has escuchado que el matrimonio es la tumba de la vida? No sabes lo que pasará.", "Kyousuke"),
    45: ("Si es él, entonces ciertamente me traerá felicidad.", "Saori"),
    46: ("¿Un hombre que niega los hobbies de su prometida?", "Kyousuke"),
    47: ("......", "Saori"),
    48: ("...No puedes pensar en nada que decir, huh. Lo entiendo.", "Kyousuke"),
    49: ("Yo tampoco sé qué decirte.", "Kyousuke"),
    50: ("¿Hoho? ¿También hay momentos en los que te quedas sin palabras?", "Saori"),
    51: ("¿No es obvio?", "Kyousuke"),
    52: ("Más bien, creo que soy peor hablando que tú.", "Kyousuke"),
    53: ("¿Que yo? ...¡Por supuesto que no!", "Saori"),
    54: ("No, no, no, eres increíble con las palabras.", "Kyousuke"),
    55: ("Me explicaste cosas de otaku a mí, un tipo que no sabía nada de eso, de una manera fácil de entender...", "Kyousuke"),
    56: ("Y puedes resolver los conflictos entre Kirino y Kuroneko cuando empiezan a discutir justo al verse, ¿verdad?", "Kyousuke"),
    57: ("¡Kyousuke-shi! ¡Me estás dando demasiados elogios...!", "Saori"),
    58: ("No es solo eso. No puedo contar cuántas veces nos has ayudado.", "Kyousuke"),
    59: ("Eso no es...", "Saori"),
    60: ("Es verdad. Nos salvaste.", "Kyousuke"),
    61: ("Es inútil. No puedo salvar a nadie...", "Kyousuke"),
    62: ("No quiero que digas cosas así.", "Saori"),
    63: ("Incluso si me dices que no...", "Kyousuke"),
    64: ("En una entrevista de matrimonio, ambos lados necesitan estar de acuerdo.", "Saori"),
    65: ("Kiririn-shi me odia ahora, y no sé qué dirá Kuroneko-shi...", "Saori"),
    66: ("Al menos... quiero que me felicites...", "Saori"),
    67: ("No puedo simplemente hacer eso...", "Kyousuke"),
    68: ("¿Por qué?", "Saori"),
    69: ("Porque he visto tu rostro de dolor.", "Kyousuke"),
    70: ("...Pero, ya he llegado a la conclusión.", "Saori"),
    71: ("Parece que mi ruta otaku ha llegado a su fin.", "Saori"),
    72: ("¡Entonces hazlo de nuevo!", "Kyousuke"),
    73: ("¡Recarga los datos! ¡Incluso puedes resetear o reiniciar!", "Kyousuke"),
    74: ("No digas cosas tan absurdas, Kyousuke-shi.", "Saori"),
    75: ("La realidad y los juegos son diferentes.", "Saori"),
    76: ("Tienes razón. La realidad y los juegos son diferentes.", "Kyousuke"),
    77: ("Si lo sabes, ¿entonces por qué dijiste eso?", "Saori"),
    78: ("Solo porque no puedas reiniciar no significa que debas rendirte tan fácilmente.", "Kyousuke"),
    79: ("¿Puedes incluso disfrutar de una vida con la que ni siquiera estás de acuerdo?", "Kyousuke"),
    80: ("¿Estás segura de que estás bien con eso?", "Kyousuke"),
    81: ("Ya te lo he dicho muchas veces.", "Saori"),
    82: ("No hay nada más que hacer...", "Saori"),
    83: ("¿¡Por qué!? ¡Te estás acorralando!", "Kyousuke"),
    84: ("Entonces, déjame preguntarte.", "Saori"),
    85: ("¿Me estás diciendo que sea egoísta?", "Saori"),
    86: ("¿Traicionar a mis padres y a mi prometido por mí misma? ¿No hacer nada sobre las restricciones al anime, los juegos y el manga? ¿Causar problemas a mis amadas amigas?", "Saori"),
    87: ("¿Es esto lo que quieres decir?", "Saori"),
    88: ("...", "Kyousuke"),
    89: ("Sí, eso es.", "Kyousuke"),
    90: ("Mis padres, mi prometido, y mis amados anime, juegos, y manga, además de-", "Saori"),
    91: ("No puedo causar más problemas a mis preciosas amigas.", "Saori"),
    92: ("¡Eso es lo que quiero decir! ¡Deja de pensar así!", "Kyousuke"),
    93: ("Está bien, es hora de que yo...", "Saori"),
    94: ("¡Espera espera espera espera!", "Kyousuke"),
    95: ("¡Oye! ¡No me detengas! ¡Si no voy, seré una vergüenza de mujer!!", "Saori"),
    96: ("¡Si vas, serás una vergüenza de otaku! ¡No te rindas tan fácilmente con la vida!", "Kyousuke"),
    97: ("Pero, parece que el escenario de mi ruta otaku ha llegado a su fin.", "Saori"),
    98: ("¿El escenario de tu ruta otaku...?", "Kyousuke"),
    99: ("¡También estoy terminando la ruta de la princesa, la ruta del escape amoroso, y todo tipo de otras rutas!", "Saori"),
    100: ("¡¡Deja de hacer tonterías!!", "Kyousuke"),
    101: ("...¿Kyousuke-shi?", "Saori"),
    102: ("¡No conviertas tu vida en un juego!", "Kyousuke"),
    103: ("Somos humanos porque no tenemos una segunda oportunidad, ¿verdad? En nuestra única vida, tenemos una oportunidad de disfrutarla al máximo.", "Kyousuke"),
    104: ("Y sin embargo, ¿por qué estás tirándolo todo tan fácilmente...?", "Kyousuke"),
    105: ("P-Pero, si hago eso...", "Saori"),
    106: ("Todas mis relaciones podrían cortarse.", "Saori"),
    107: ("E-Es posible... P-Podría terminar sola...", "Saori"),
    108: ("No lo harás, ¡idiota! ¡Date cuenta de esto ya!", "Kyousuke"),
    109: ("No importa quién se convierta en tu enemigo, siempre estaré contigo.", "Kyousuke"),
    110: ("¡¿Kyo-Kyousuke-shi...?!", "Saori"),
    111: ("Puede que pienses que está bien así, pero sin ti, nuestras relaciones cambiarían.", "Kyousuke"),
    112: ("...", "Saori"),
    113: ("No creo que pensar primero en los demás sea algo malo.", "Kyousuke"),
    114: ("Sin embargo, ¡no podrás obtener felicidad para ti misma de esa manera!", "Kyousuke"),
    115: ("Fufu... Solo bromeaba...", "Saori"),
    116: ("Si lo piensas, ya estoy mayormente sola...", "Saori"),
    117: ("Pero, esto es algo ya decidido por mis padres y yo.", "Saori"),
    118: ("...No, no solo con mis padres.", "Saori"),
    119: ("Involucra a mi prometido también, y a ustedes también. Me estoy acercando a mi decisión.", "Saori"),
    120: ("En lugar de imponer mi propio camino, las cosas podrían resolverse quitando a una persona... a mí...", "Saori"),
    121: ("Estoy bien estando sola.", "Saori"),
    122: ("¡No estás sola! Estoy aquí, ¿verdad?", "Kyousuke"),
    123: ("Y, ser olvidada justo frente a mis ojos... Estoy realmente triste por eso.", "Kyousuke"),
    124: ("E-Espera... no lo quise decir así...", "Saori"),
    125: ("Entiendo que valores tus relaciones humanas.", "Kyousuke"),
    126: ("Pero, sin ti, ¿qué pasa con nuestra relación?", "Kyousuke"),
    127: ("U-Umm...", "Saori"),
    128: ("Más que eso, no puedes proteger tu felicidad.", "Kyousuke"),
    129: ("Mi felicidad...", "Saori"),
    130: ("Sí, tu felicidad.", "Kyousuke"),
    131: ("P-Pero, si yo soy feliz, otras personas no lo serán...", "Saori"),
    132: ("Esa no es una razón suficiente para que te rindas.", "Kyousuke"),
    133: ("No se trata de otras personas, se trata de lo que quieres hacer...¿verdad?", "Kyousuke"),
    134: ("Y-Yo...", "Saori"),
    135: ("No quiero vivir una vida con la vergüenza de causar problemas a los demás...", "Saori"),
    136: ("Por eso dejaré mi vida otaku y comenzaré mi vida de casada.", "Saori"),
    137: ("¡No te dejaré terminar aquí!", "Kyousuke"),
    138: ("¡¿Kyo-Kyousuke-shi!? ¡Estás demasiado ruidoso!", "Saori"),
    139: ("¡Cállate! ¿Eso tiene algo que ver con esto?!", "Kyousuke"),
    140: ("¿El ruidoso eres tú, no?!", "Saori"),
    141: ("Hmmm...", "Kyousuke"),
    142: ("¿Qué pasa con esa mirada seria...", "Saori"),
    143: ("...Justo ahora, me contestaste por primera vez, ¿verdad?", "Kyousuke"),
    144: ("...¿Y?", "Saori"),
    145: ("Así que puedes expresar tu opinión después de todo.", "Kyousuke"),
    146: ("Solo dile a tu prometido tus verdaderos sentimientos así. Ve a por ello.", "Kyousuke"),
    147: ("Kyousuke-shi...", "Saori"),
    148: ("Bueno entonces, parece que esta conversación ha terminado-", "Saori"),
    149: ("Espera, no ha terminado todavía.", "Kyousuke"),
    150: ("...¿Todavía? ¿qué?", "Saori"),
    151: ("¿Vas a decir que estás sola, incluso cuando estoy frente a ti...?", "Kyousuke"),
    152: ("Ah... n-no...", "Saori"),
    153: ("De ninguna manera estoy tratándote como aire.", "Saori"),
    154: ("Si lo hicieras, lloraría. Me retorcería y me quejaría con mocos en toda la cara.", "Kyousuke"),
    155: ("¡N-No hagas eso aquí!", "Saori"),
    156: ("Entonces, ¿no lo pensarás una vez más?", "Kyousuke"),
    157: ("Si te vas, cambiará el mundo de Kirino y el mío.", "Kyousuke"),
    158: ("Pero...", "Saori"),
    159: ("¿Es realmente inútil ahora?", "Kyousuke"),
    160: ("¿Te estás rindiendo porque piensas que es inútil?", "Kyousuke"),
    161: ("...Sí.", "Saori"),
    162: ("Esto es un callejón sin salida. Podrías decir que es game over.", "Saori"),
    163: ("No lo creo. Tu historia no termina aquí.", "Kyousuke"),
    164: ("Solo... detente. Un final es un final.", "Saori"),
    165: ("¿Estás tratando de hacer que te odie esta vez? Para intentar dejarme fuera de esto...", "Kyousuke"),
    166: ("...", "Saori"),
    167: ("Oye, ¿no escucharás al menos... solo un poco más?", "Kyousuke"),
}

a0087_n = {
    0: "Ruta de Saori · El Sermón De Kyousuke-shi",
    3: "He llegado tan lejos... ¡¿crees que me rendiré ahora...!",
    4: "Tengo que hacer algo para que me escuche...",
    26: "Incluso después de decir todo eso, la resolución de Saori todavía no ha vacilado...",
    27: "Lo que significa, su voluntad es fuerte.",
    28: "¡Pero, hay una cosa decisivamente equivocada en lo que está diciendo!",
    47: "...Parece que está tratando de decir algo.",
    48: "Pero por la forma en que se queda en silencio...",
    49: "Es como si las palabras estuvieran tratando de escapar de su garganta, pero simplemente no pueden salir... huh?",
    55: "Sé cómo se siente Saori. Lo sé, ¡pero...!",
    56: "Pero la forma en que niega todo no resolverá nada...",
    57: "¿Por qué no puede simplemente entender eso...",
    66: "¿N-No puede ser... oye...",
    67: "Es la primera vez que veo llorar a Saori...",
    74: "Saori sollozó en silencio, su voz temblando.",
    75: "Sin poder encontrar las palabras para arreglar esto, me quedé parado hasta que se detuvo...",
    100: "Incluso yo me sentí un poco avergonzado después de decir eso.",
    101: "Pero era como me sentía, así que no podía mentir al respecto.",
    103: "Unos meses después...",
    104: "Recibí una carta y una fotografía de Saori.",
    105: "La carta era sobre su compromiso en su cumpleaños.",
    106: "La recepción era solo para familiares, así que Kirino, Kuroneko, y yo no pudimos ir.",
    107: "Y la foto era-",
    108: "Una foto de Saori con un vestido de novia blanco puro.",
    109: "...Estaba hermosa.",
    110: "Tenía una sonrisa reservada en su rostro, pero tenía el aire de una princesa.",
    111: "No sería una exageración llamar a Saori una belleza.",
    112: "Pero, ¿qué es esto?",
    113: "Cuando miro el rostro sonriente de Saori, mi pecho duele.",
    114: "Es vergonzoso decirlo pero, estoy tan solo, mi pecho siente que se va a romper.",
    115: "Esto debe ser lo que se siente cuando un padre envía a su hija como novia.",
    118: "Saori sonrió con una expresión solitaria en la foto...",
    124: "...Puede que tenga razón.",
    125: "Pero, eso no es lo que estoy tratando de decirle a Saori.",
    126: "Saori debería vivir la vida más libremente.",
    127: "Sin prestar atención a las obligaciones, viviendo como le plazca.",
    128: "Incluso si es una dama reservada, su vida no necesita ser reservada también.",
    129: "Lo único que tiene que ser reservado son las figuras en pre-pedido.",
    133: "Saori declaró en un tono distintivo.",
    137: "Saori tenía una expresión gentil, mientras sus palabras fluían de su boca...",
    138: "Mientras intentaba decir algo, pensé en la inquebrantable determinación de Saori.",
    139: "Espera... el matrimonio es algo con lo que ambas partes están de acuerdo, ¿verdad?",
    140: "Si ese es el caso, si ella tuviera a alguien que ya «hizo una promesa a...»",
    162: "Incluso yo me sentí un poco avergonzado después de decir eso.",
    163: "Pero era como me sentía, así que no puedo mentir sobre mis sentimientos.",
    165: "Unos meses después...",
    166: "Recibí una carta y una fotografía de Saori.",
    167: "La carta era sobre su compromiso en su cumpleaños.",
    168: "La recepción era solo para familiares, así que Kirino, Kuroneko, y yo no pudimos ir.",
    169: "Y la foto era-",
    170: "Una foto de Saori con un vestido de novia blanco puro.",
    171: "...Estaba hermosa.",
    172: "Tenía una sonrisa reservada en su rostro, pero tenía el aire de una princesa.",
    173: "No sería una exageración llamar a Saori una belleza.",
    174: "Pero, ¿qué es esto?",
    175: "Cuando miro el rostro sonriente de Saori, mi pecho duele.",
    176: "Es vergonzoso decirlo pero, estoy tan solo, mi pecho siente que se va a romper.",
    177: "Esto debe ser lo que se siente cuando un padre envía a su hija como novia.",
    180: "Saori sonrió con una expresión solitaria en la foto...",
    189: "Kirino, Kuroneko y Saori son sin duda tres piezas de mi mundo que no puedo quitar.",
    190: "Lo mismo va para mis amigos de la infancia, Manami y Ayase, mis amigos irremplazables.",
    191: "Pero incluso si entiendo cuán importantes son, si pasamos suficiente tiempo juntos, lo daría por sentado.",
    192: "Sin embargo, tan pronto como no pude contactar a Saori, me volví realmente solitario.",
    193: "Ahí fue cuando lo supe.",
    194: "Lo obvio no es tan obvio a veces. Puede ser fácilmente pasado por alto.",
    202: "No sé qué pasa pero, parece que está bien... ¿verdad?",
    215: "Oh sí, mi padre dijo algo como...",
    216: "«La miseria de un hijo es responsabilidad de los padres.»",
    217: "Los padres de Saori podrían sentirse mal por decidir la vida de su hija por sí mismos.",
}
a0087_s = {
    1: ("...Estoy realmente contenta de que sientas eso.", "Saori"),
    2: ("Pero ahora mismo, tus palabras son demasiado pesadas...", "Saori"),
    5: ("Si mis palabras son demasiado pesadas para ti, entonces cargaré la mitad por ti.", "Kyousuke"),
    6: ("Por eso... por eso, por favor... ¿no escucharás al menos lo que tengo que decir?", "Kyousuke"),
    7: ("...Kyousuke-shi...", "Saori"),
    8: ("¿Por qué estás yendo tan lejos por mí...", "Saori"),
    9: ("Sé por qué te importan tanto tus relaciones.", "Kyousuke"),
    10: ("Eres una persona gentil e increíblemente amable.", "Kyousuke"),
    11: ("No importa cuánto te destaques, te acercaste a mi hermana cuando estaba siendo rechazada y te preocupaste por esa chica delirante.", "Kyousuke"),
    12: ("Cuando tus amigas están en problemas, intentas ayudarlas sin importar qué... Eso es mucho más impresionante de lo que piensas.", "Kyousuke"),
    13: ("Kyousuke-shi, me estás alabando demasiado... Solo estaba haciendo lo obvio.", "Saori"),
    14: ("¡Como digo, el hecho de que pienses que es obvio cuando no lo es! ¡Es increíble!", "Kyousuke"),
    15: ("Definitivamente no podría dirigir una comunidad. Tampoco podría mediar entre Kirino y Kuroneko solo.", "Kyousuke"),
    16: ("¿Ves lo que quiero decir?", "Kyousuke"),
    17: ("Te necesitamos. Eres irremplazable.", "Kyousuke"),
    18: ("...Pero, eso ha sido hasta ahora.", "Saori"),
    19: ("Justo antes, Kiririn-shi obviamente me odiaba.", "Saori"),
    20: ("Kirino no quiso decir lo que dijo. Puedo decirlo... Soy su hermano, después de todo.", "Kyousuke"),
    21: ("Por eso tú, que te preocupas por los sentimientos de los demás, puedes hacerlo-", "Kyousuke"),
    22: ("...Si ese es el caso, con más razón debo irme.", "Saori"),
    23: ("¿¡Por qué! Esto no tiene ningún sentido!", "Kyousuke"),
    24: ("Por favor entiende, Kyousuke-shi. No quiero ser un problema para mis amigas.", "Saori"),
    25: ("Siempre he querido ser una persona cuyas amigas me consideren una amiga.", "Saori"),
    29: ("Entiendo que piensas en nosotros como preciosos.", "Kyousuke"),
    30: ("...Pero, ¿es eso lo que es una amiga?", "Kyousuke"),
    31: ("¿Huh...?", "Saori"),
    32: ("Una amiga no es solo alguien con quien sales, compras y te diviertes, ¿verdad?", "Kyousuke"),
    33: ("Como Kirino y Kuroneko, también pelean, hablan mal, y se preocupan cuando alguien se enferma.", "Kyousuke"),
    34: ("Las cosas buenas y malas, las divertidas y las terribles, todo eso combinado es de lo que se tratan las amigas, ¿verdad?", "Kyousuke"),
    35: ("¿Causar problemas a tus amigas? ¡Como si me importara! ¡Sería extraño si no las hubiera!", "Kyousuke"),
    36: ("Pero, esto es diferente a solo causar problemas...", "Saori"),
    37: ("Cuando tus amigas vinieron a pedirte consejo, ¿pensaste que era una molestia? Por supuesto que no, ¿verdad?", "Kyousuke"),
    38: ("Como mínimo, yo seré feliz. ¿Que vengas a pedirme consejo significa que se puede contar conmigo, verdad?", "Kyousuke"),
    39: ("Seré muy feliz cuando piense en el hecho de que se puede contar conmigo... Esto no pasa mucho, así que ten paciencia conmigo.", "Kyousuke"),
    40: ("Por eso, cuando viniste a mí sobre tu entrevista de matrimonio, fui realmente feliz.", "Kyousuke"),
    41: ("Ya que siempre contamos contigo, estuvo bien que tú también contaras con nosotros.", "Kyousuke"),
    42: ("Pero... yo no he...", "Saori"),
    43: ("Lo hiciste, Saori. Kirino, Kuroneko, y yo, todos nosotros inconscientemente contamos contigo.", "Kyousuke"),
    44: ("Te hemos causado muchos «problemas». No solo una o dos veces, sino todo el tiempo.", "Kyousuke"),
    45: ("¡Así que no pienses que es una molestia! ¡Dime... tus verdaderos sentimientos!", "Kyousuke"),
    46: ("Y-Yo...", "Saori"),
    50: ("...Kyousuke-shi...", "Saori"),
    51: ("Saori, por favor.", "Kyousuke"),
    52: ("Quiero escuchar lo que tienes que decir.", "Kyousuke"),
    53: ("Pero, pero...", "Saori"),
    54: ("¡Ya no sé qué hacer más...!", "Saori"),
    58: ("...¿Planeas huir?", "Kyousuke"),
    59: ("Embotellando tus sentimientos, queriendo proteger algo precioso como excusa...", "Kyousuke"),
    60: ("Al final, todo lo que estás haciendo es huir.", "Kyousuke"),
    61: ("Haciendo exactamente lo que tus padres dicen, yendo con tu prometido, todo es demasiado doloroso y por eso huyes!", "Kyousuke"),
    62: ("¿Has hablado con tus padres? ¡¿Le has dicho a tu prometido cómo te sientes realmente?!", "Kyousuke"),
    63: ("...Si dijera eso...!", "Saori"),
    64: ("S-Saori...?", "Kyousuke"),
    65: ("Uuuu, *hip*...", "Saori"),
    68: ("Saori... um, lo siento...", "Kyousuke"),
    69: ("Yo... dije demasiado... ¿verdad?", "Kyousuke"),
    70: ("No... yo también lo siento, llorar así de repente...", "Saori"),
    71: ("Pero, así es como soy...", "Saori"),
    72: ("La verdadera yo es débil, pequeña, y una chica cobarde...", "Saori"),
    73: ("Nada se puede hacer... No puedo hacer nada más...", "Saori"),
    76: ("Te gusta ser una otaku, ¿verdad?", "Kyousuke"),
    77: ("Amas tus figuras, juegos, y manga tanto que no puedes evitarlo, ¿verdad?", "Kyousuke"),
    78: ("Eso es... verdad...", "Saori"),
    79: ("Mentir sobre algo que te gusta, no me hagas reír hablando del compromiso!", "Kyousuke"),
    80: ("Incluso si él es tu prometido, todavía no merece llamarte su esposa.", "Kyousuke"),
    81: ("¡Esa no puede ser tu razón para rendirte en lo que te gusta!!", "Kyousuke"),
    82: ("...", "Saori"),
    83: ("...Siempre eres así, Saori.", "Kyousuke"),
    84: ("Tratas de mantener todo junto diciendo cosas lindas, y haces felices a todos mientras te encierras...", "Kyousuke"),
    85: ("Eres una flor de preparatoria. Deberías hacer más cosas que quieras.", "Kyousuke"),
    86: ("...Ya he hecho suficientes de esas ahora.", "Saori"),
    87: ("Estoy diciendo palabras egoístas incluso ahora, causándote muchos problemas...", "Saori"),
    88: ("¿¡Cómo es eso suficiente!?", "Kyousuke"),
    89: ("De hecho, ¡nunca es suficiente! ¡Hazlo un 20% más!!", "Kyousuke"),
    90: ("¡En realidad, necesitas mucho más que suficiente! ¡Muéstrame un 200% suficiente!!", "Kyousuke"),
    91: ("Bueno, entonces haz lo que quieras.", "Kyousuke"),
    92: ("¿Eh...?", "Saori"),
    93: ("No soy tú, así que no puedo entenderte completamente.", "Kyousuke"),
    94: ("Si lo que he dicho hasta ahora todavía no puede sacudir tu determinación, entonces quizás esta sea la mejor opción para ti?", "Kyousuke"),
    95: ("...Si ese es el caso, no diré nada más.", "Kyousuke"),
    96: ("Kyousuke-shi...", "Saori"),
    97: ("...Es mi honor haber recibido tu comprensión.", "Saori"),
    98: ("Todavía no puedo aceptarlo, aunque...", "Kyousuke"),
    99: ("Pero, incluso si parecemos no ser amigos más, ¡seguimos siendo amigos para siempre!", "Kyousuke"),
    102: ("Bueno entonces... cuídate.", "Saori"),
    116: ("...Oye, Saori.", "Kyousuke"),
    117: ("¿Esto... estaba realmente bien?", "Kyousuke"),
    119: ("Mi cuerpo no podrá sostener todo eso...", "Saori"),
    120: ("Si es esa cantidad, ¡puedes hacerlo! ¿Verdad?", "Kyousuke"),
    121: ("Jaja... Ni siquiera lo sé.", "Saori"),
    122: ("Es justo como dices, si hago lo que me plazca, puede que sea feliz.", "Saori"),
    123: ("Pero, ¿no es eso diferente de ser una niña egoísta?", "Saori"),
    130: ("Realmente he hecho grandes amigas.", "Saori"),
    131: ("Kyousuke-shi, Kiririn-shi, Kuroneko-shi... Mis amigas irremplazables, pude hacer tantos recuerdos.", "Saori"),
    132: ("Por eso, estoy satisfecha.", "Saori"),
    134: ("...¿Estás bien así?", "Kyousuke"),
    135: ("¿Estás realmente, realmente bien?", "Kyousuke"),
    136: ("Sí. Está bien así como está.", "Saori"),
    141: ("¡Está bien, ya sé! ¡Me casaré contigo!", "Kyousuke"),
    142: ("Wahhh...!!", "Saori"),
    143: ("¡K-K-K-K-Kyousuke-shi!? ¡¿Qué estás diciendo!?", "Saori"),
    144: ("¡Por el bien de descartar el compromiso!", "Kyousuke"),
    145: ("Reducirá las posibilidades de que consigas otro prometido, ¿verdad?", "Kyousuke"),
    146: ("P-Pero e-e-e-e-esto es... umm, uhhh...", "Saori"),
    147: ("...Después de decir tanto, ¿todavía no lo entiendes?", "Kyousuke"),
    148: ("Como externo, ¡ya estoy así de emocionado! ¡Por el bien de mi importante amiga, por el bien de ti!", "Kyousuke"),
    149: ("¡Ahora muéstrame tu fuerza de voluntad!", "Kyousuke"),
    150: ("...", "Saori"),
    151: ("Fu... Entiendo.", "Saori"),
    152: ("Si lo dices así, puedo prepararme para lo peor.", "Saori"),
    153: ("Bueno, entonces haz lo que quieras.", "Kyousuke"),
    154: ("¿Huh...?", "Saori"),
    155: ("No soy tú, así que no puedo entenderte completamente.", "Kyousuke"),
    156: ("Si lo que he dicho hasta ahora todavía no puede sacudir tu determinación, entonces quizás esta sea la mejor opción para ti?", "Kyousuke"),
    157: ("...Si ese es el caso, no diré nada más.", "Kyousuke"),
    158: ("Kyousuke-shi...", "Saori"),
    159: ("...Es mi honor haber recibido tu comprensión.", "Saori"),
    160: ("Todavía no puedo aceptarlo, aunque...", "Kyousuke"),
    161: ("Pero, incluso si parecemos no ser amigos más, ¡seguimos siendo amigos para siempre!", "Kyousuke"),
    164: ("Bueno entonces... cuídate.", "Saori"),
    178: ("...Oye, Saori.", "Kyousuke"),
    179: ("¿Esto... estaba realmente bien?", "Kyousuke"),
    181: ("Bueno...?", "Kyousuke"),
    182: ("...Sí, he ganado la determinación de declinar el compromiso.", "Saori"),
    183: ("Soy una otaku. Una otaku que no siente vergüenza por serlo.", "Saori"),
    184: ("Dejaré de mentirme a mí misma. Amo las cosas a las que me he apegado. Nada más, nada menos.", "Saori"),
    185: ("Una cosa tan obvia e importante... ¿por qué no la he notado todo este tiempo?", "Saori"),
    186: ("Es difícil darse cuenta porque es obvio... probablemente.", "Kyousuke"),
    187: ("Porque siempre está ahí, olvidas que es precioso... un poco como el aire.", "Kyousuke"),
    188: ("Los hobbies y la familia... cosas así, ¿verdad?", "Kyousuke"),
    195: ("En serio, tu pasión es admirable.", "Saori"),
    196: ("Ser capaz de darle la vuelta a la determinación de toda mi vida.", "Saori"),
    197: ("¿Toda tu vida? Puede que haya hecho algo malo.", "Kyousuke"),
    198: ("Fufu, no te preocupes por eso.", "Saori"),
    199: ("Pronto, creo que encontraré otra determinación de otra vida.", "Saori"),
    200: ("¿Qué quieres decir?", "Kyousuke"),
    201: ("...Es un secreto por ahora.", "Saori"),
    203: ("Por ahora, ¿qué harás?", "Kyousuke"),
    204: ("Primero, creo que tendré una conversación con mis padres.", "Saori"),
    205: ("Bueno, eso es probablemente lo mejor que se puede hacer.", "Kyousuke"),
    206: ("Incluso mientras digo eso, pueden ir en cualquier dirección sobre aceptarlo...", "Saori"),
    207: ("Incluso si no funciona, no me rendiré.", "Saori"),
    208: ("Si una vez no es suficiente, lo haré dos veces, o tres veces. Si tres veces no es suficiente, lo haré cualquier número de veces.", "Saori"),
    209: ("...De esa manera mi «amor» les llegará, ¿verdad?", "Saori"),
    210: ("Sí, justo así.", "Kyousuke"),
    211: ("Fufufufu...", "Saori"),
    212: ("Gracias, Kyousuke-shi. Estoy agradecida por todo...", "Saori"),
    213: ("Si me vas a agradecer, entonces hazlo después. Estoy esperando las buenas noticias.", "Kyousuke"),
    214: ("...¡Está bien!", "Saori"),
    218: ("Por supuesto que sí...", "Kyousuke"),
    219: ("Probablemente se sentirán aliviados de que ella les haya hablado al respecto.", "Kyousuke"),
    220: ("Por eso tienes que ir y contarles todo lo que has estado guardando.", "Kyousuke"),
    221: ("Kyousuke-shi...", "Saori"),
    222: ("¿No solo estás cuidando de mí, sino también de mi familia?", "Saori"),
    223: ("¿Por supuesto?", "Kyousuke"),
    224: ("Si es tu familia, entonces están relacionados con tu problema.", "Kyousuke"),
}

data = {
    "000scriptDSAO_0073A.obj": build(a0073_n, a0073_s),
    "000scriptDSAO_0075T.obj": build(a0075_n, a0075_s),
    "000scriptDSAO_0078A.obj": build(a0078_n, a0078_s),
    "000scriptDSAO_0080T.obj": build(a0080_n, a0080_s),
    "000scriptDSAO_0087A.obj": build(a0087_n, a0087_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
