import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration: dict, speech: dict) -> dict:
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a66_n = {
    0: "El Fin Del Torneo",
    1: "El día después del torneo.",
    3: "Esta zona suele ser vista como una «Guarida de Otakus», pero en realidad, es bastante sofisticada.",
    4: "La plaza pública frente a la estación está bastante limpia; hace que el lugar sea espacioso y relajante.",
    5: "Saori y Kuroneko ya han llegado y están sentadas en un banco de la plaza pública.",
    6: "Ah, cierto, la primera vez que conocí a Saori y Kuroneko fue también en Akihabara...",
    10: "No habría ambiente si celebráramos de inmediato. Esto podría ser bueno para aumentar la emoción.",
    18: "Y así Saori reflexionó por un rato.",
    19: "Probablemente está buscando en el interminable «Akiba-data» dentro de su cabeza.",
    22: "...*tragar*",
    23: "Parece bastante simple, pero en realidad, la respuesta puede ser de crucial importancia.",
    24: "Si eligiera un lugar que no les importa, estoy seguro de que se convertiría en otra pelea.",
    25: "Hmm... ¿A dónde deberíamos ir?",
    26: "Además, no debería elegir un lugar agotador...",
    34: "...*suspiro*.",
    35: "Me estoy volviendo bastante familiarizado con esos temas.",
    36: "El contenido es... el de un juego bishoujo.",
    37: "Porque la historia trata de tener una relación de triángulo amoroso con tus hermanitas «Rinko» y «Miyabi», me duele la cabeza.",
    38: "Según Kirino, es un «juego divino» que «arranca lágrimas». Pero francamente no lo entiendo.",
    39: "Sin embargo, sí sé cómo hacer llorar a mi propia hermanita...",
    47: "Esta chica, prácticamente gastó todo su salario ganado como modelo, en «Sis×Sis»...",
    55: "Bueno, se ve toda feliz y todo... Oh bueno.",
    58: "Saori formó su boca como la de un gato y echó la cabeza hacia atrás.",
    63: "No solo Kirino, sino incluso la normalmente inexpresiva Kuroneko reaccionó... Esta persona debe ser realmente algo.",
    64: "Recientemente, me he vuelto cada vez más familiarizado con «ese género de temas», pero sigo siendo un aficionado después de todo.",
    65: "Solo escuchar el nombre no es suficiente para que lo reconozca.",
    75: "Uwah... Esa es una reacción tan clásica...",
    77: "Diciendo eso, Saori me extendió sus manos. Entonces...",
    79: "Extendí mi mano derecha...",
    80: "¡¡Cuidado ahora!!",
    81: "Extendí mi mano izquierda y estreché la mano de Saori...",
    87: "...Yo no.",
    95: "Me agoto cada vez que recorro Akiba con estas chicas.",
    99: "Ignorando la mirada persistente de Kirino, nos dirigimos a un Maid Cafe.",
}
a66_s = {
    2: ("Akihabara está tan bulliciosa como siempre.", "Kyousuke"),
    7: ("Entonces, ¡para celebrar el fin del torneo, vinimos a la tierra sagrada!", "Saori"),
    8: ("Vamos de compras ya que estamos aquí, ¿de acuerdo?", "Saori"),
    9: ("¿Compras...", "Kyousuke"),
    11: ("Sí, de acuerdo. ¿Están de acuerdo ustedes?", "Kyousuke"),
    12: ("Por mí está bien.", "Kirino"),
    13: ("No me importa; hagan lo que quieran.", "Kuroneko"),
    14: ("Las escuchaste, Saori.", "Kyousuke"),
    15: ("¡Entendido! Entonces, ¿a dónde deberíamos ir primero?", "Saori"),
    16: ("¿Hay algún lugar que recomiendes?", "Kyousuke"),
    17: ("Cada lugar en Akihabara es recomendable... Hmm...", "Saori"),
    20: ("¿Qué tal si vamos a 【Radio Kaikan】 o 【AniMate】?", "Saori"),
    21: ("Kyousuke-shi, ¿tienes algún lugar que quieras visitar?", "Saori"),
    27: ("¿Qué hacemos en realidad en Radio Kaikan?", "Kyousuke"),
    28: ("¡¡¡Ah～～～～～～～～～!!!", "Kirino"),
    29: ("¿Q-Qué pasa? ¿Q-Q-Q-Qué es?", "Kyousuke"),
    30: ("¡Radio Kaikan! ¡Quiero ir a Radio Kaikan!", "Kirino"),
    31: ("¿Qué tiene Radio Kaikan?", "Kyousuke"),
    32: ("¡Porque Radio Kaikan tiene una tienda de figuras y hay un puesto especial de 【Sis×Sis】 que empezó a vender artículos de edición limitada!", "Kirino"),
    33: ("¿Sis×Sis - Sister Sister: Historia de Amor Siscon?", "Kyousuke"),
    40: ("¡Deja de dar vueltas! ¡Se agotarán si no nos apuramos!", "Kirino"),
    41: ("No se agotarán tan rápido. Cálmate un poco. Te lastimarás si entras en pánico.", "Kyousuke"),
    42: ("¡Sis×Sis es un «juego divino»!", "Kirino"),
    43: ("¡Ah, oye! ¡No corras!", "Kyousuke"),
    44: ("¡Maldición! ¡Quiero esto! ¡Esto también! ¡Y eso también!", "Kirino"),
    45: ("¿N-No estás comprando demasiado?", "Kyousuke"),
    46: ("¡Cállate! ¡Cómo gasto mi propio dinero es cosa mía!", "Kirino"),
    48: ("¡Qué gran botín! ¡Estoy tan feliz!", "Kirino"),
    49: ("Qué bueno, Kiririn-shi.", "Saori"),
    50: ("No está tan mal observar a los humanos comportándose así de vez en cuando.", "Kuroneko"),
    51: ("Sigues hablando así～ Puedo prestartelos si te interesa.", "Kirino"),
    52: ("¿Qu-...? ¿Quién dijo algo así...", "Kuroneko"),
    53: ("Mira, mira. Tú también quieres probarlos, ¿no?", "Kirino"),
    54: ("¡Jajaja! ¡Profundizando lazos mutuos a través de los juegos! ¡Ah, qué maravilloso!", "Saori"),
    56: ("¿Qué se hace en AniMate?", "Kyousuke"),
    57: ("¡Ohh! ¡Como era de esperar de Kyousuke-shi, buena elección!", "Saori"),
    59: ("¡Parece que hoy, Morimura Kaede-dono está haciendo una sesión de autógrafos en AniMate!", "Saori"),
    60: ("¡¿En serio?!", "Kirino"),
    61: ("¿Esto es verdad?", "Kuroneko"),
    62: ("¿Quién es esa?", "Kyousuke"),
    66: ("¡Dios santo! ¡Tenemos que apurarnos! ¡DASH!", "Kirino"),
    67: ("¡Ah, oye! ¡No corras!", "Kyousuke"),
    68: ("Oh vaya... No puedo dejar de temblar.", "Kirino"),
    69: ("No puedo creer que pude darle la mano a Morimura Kaede-san... Esto no es un sueño, ¿cierto?", "Kirino"),
    70: ("Incluso para una veterana de Akihabara como yo, ha pasado mucho tiempo desde que me emocioné tanto...", "Saori"),
    71: ("Fue bastante impresionante...", "Kuroneko"),
    72: ("¿Viste? ¡Kaede-san sostuvo mi mano suavemente y me guiñó el ojo!", "Kirino"),
    73: ("¿La tuya no fue solo un parpadeo normal? La que me dio a mí fue un guiño.", "Kuroneko"),
    74: ("¡Lo he decidido! ¡Nunca me lavaré las manos!", "Kirino"),
    76: ("Kyousuke-shi, muchas gracias por considerar mis sentimientos.", "Saori"),
    78: ("...Ah, bueno. No es como crees...", "Kyousuke"),
    82: ("...Por cierto, ¿qué tipo de persona es Morimura Kaede?", "Kyousuke"),
    83: ("¡Kaede-shi no solo es escritora, sino también cantante, modelo y estrella; realmente una persona multi-talentosa!", "Saori"),
    84: ("Se rumorea que participará en un musical de Broadway después...", "Saori"),
    85: ("¡Eso es increíble, ¿no?! ¡La admiro por completo!", "Kirino"),
    86: ("Oh, ya veo.", "Kyousuke"),
    88: ("No me importa a dónde vayamos....", "Kyousuke"),
    89: ("Ya veo... Qué lástima.", "Saori"),
    90: ("¿Eeeh? Ya vinimos a Akiba, ¡así que quiero ir a algún lugar al menos!", "Kirino"),
    91: ("Es cierto, ahora los cuatro estamos juntos. Perder nuestro tiempo en vano va contra las reglas de mi alma.", "Kuroneko"),
    92: ("Quieres decir que quieres divertirte, ¿cierto? Eres demasiado críptica.", "Kirino"),
    93: ("¿Podrías dejar de resumir los discursos de otras personas...?", "Kuroneko"),
    94: ("Jajaja, ustedes dos ciertamente se llevan bien.", "Saori"),
    96: ("¿Entonces qué tal relajarnos en un Maid Cafe?", "Saori"),
    97: ("¡Oh! ¡Esa es una buena idea!", "Kyousuke"),
    98: ("¿Huh...?", "Kirino"),
}

a68_n = {
    0: "Menú Extraño",
    2: "*suspiro* Todavía no me acostumbro a esto.",
    3: "Mientras pensaba, el trío otaku camina a mi lado como si fuera natural.",
    4: "Pedí una Poción de Recuperación de Frijol Negro después de sentarme, que es básicamente, café helado.",
    5: "Kirino pidió un Espíritu de Saiyan. Kuroneko pidió un Agua de Dios Superior, Saori consiguió una Esencia de Árbol Sagrado.",
    6: "¿Por qué no usan nombres normales para el menú de este café?",
    13: "¡El café helado penetró mi cuerpo cansado...!",
    28: "Esto está llevando una broma demasiado lejos.",
    29: "Además, esto significa que planea seguir siendo amiga de Kuroneko en los años venideros.",
    36: "Sí.",
    37: "Esos son recuerdos importantes hechos en Akihabara para los cuatro.",
    38: "Todos hicimos muchos recuerdos en esta parte de la ciudad.",
    39: "Buenas o malas, muchas cosas pasaron.",
    40: "Recuerdos acumulados, del tipo que no olvidarás, atesorándolos a lo largo de tu vida.",
    41: "Espero que ellas sientan lo mismo.",
    43: "Kirino sacó rápidamente un reproductor de música.",
    48: "¡Whoa...! ¡¿Q-Qué está pasando, esta 【canción denpa】?!",
    49: "No estoy completamente seguro de si esto fue grabado correctamente o no.",
    50: "Hay sonidos electrónicos que aparecen a mitad de camino.",
    51: "También hay cambios repentinos de melodía.",
    52: "Es similar a la canción de Meruru que conozco.",
}
a68_s = {
    1: ("¡Bienvenidos, Amo, Ama!", "Maid"),
    7: ("Entonces, para celebrar la gloriosa victoria---", "Saori"),
    8: ("¡Salud!", "Kirino"),
    9: ("Salud.", "Kuroneko"),
    10: ("¡Salud es!", "Saori"),
    11: ("Salud.", "Kyousuke"),
    12: ("Haaa.", "Kyousuke"),
    14: ("Ahora que lo pienso, ustedes tres usaron trajes de maid antes.", "Kyousuke"),
    15: ("Ah, es verdad que hubo algo así. Fue probablemente en invierno.", "Saori"),
    16: ("Es cierto.", "Kyousuke"),
    17: ("Reservamos una sala de alquiler donde Kiririn-shi, Kuroneko-shi y yo consolamos a Kyousuke-shi.", "Saori"),
    18: ("¡Pfft!", "Kyousuke"),
    19: ("¡Tú! ¿Por qué dices esas cosas en público? ¡¿Y si se malinterpreta?!", "Kyousuke"),
    20: ("Huhuhu, perdón por eso. Pero bueno, realmente lo extrañaba.", "Saori"),
    21: ("Todavía recuerdo que los trajes de maid les quedaron muy bien a Kiririn-shi y Kuroneko-shi - absolutamente lindas.", "Saori"),
    22: ("...P-Por favor, olvida esa época.", "Kuroneko"),
    23: ("Je, ¿de qué te avergüenzas tanto? ¡Fue lindo, tu maid con orejas de gato!", "Kirino"),
    24: ("¿Qu-...", "Kuroneko"),
    25: ("Todavía tengo una foto en mi teléfono, ¿quieres verla?", "Kirino"),
    26: ("¡B-Borra eso!", "Kuroneko"),
    27: ("No. ¡Planeo mostrarlas a tus hijos años después!", "Kirino"),
    30: ("A-Ahora que lo pienso, le diste a tu hermano mayor un regalo escandaloso.", "Kuroneko"),
    31: ("¡¿Qu-...! ¿E-Eso no tiene nada que ver con esto?", "Kirino"),
    32: ("Fue algo como «Por favor, atesóralo como me atesoras a mí», ¿cierto? Algo que dirían los amantes.", "Kuroneko"),
    33: ("¡Ahhhhhhhh! ¡Cállate cállate cállate! ¡Olvida eso!", "Kirino"),
    34: ("Jeje.", "Saori"),
    35: ("Je.", "Kyousuke"),
    42: ("¡Ah! ¡Eso me recuerda algo!", "Kirino"),
    44: ("Oye tú, escucha esto.", "Kirino"),
    45: ("¿Eh?", "Kyousuke"),
    46: ("¡Date prisa!", "Kirino"),
    47: ("Okay, okay.", "Kyousuke"),
    53: ("¡¿Hmm?! ¡¿Hmm?! ¡¿Esta canción es increíble, no?!", "Kirino"),
    54: ("¡Mis oídos están por caerse!", "Kyousuke"),
    55: ("¡¿Eh? ¡¿Qué estás diciendo?! ¿No ves los méritos de esta canción?", "Kirino"),
    56: ("¡¿Quién es! La persona que escribió una canción tan sin sentido!", "Kyousuke"),
    57: ("...¿Eh? ¿Qué estás diciendo?", "Kirino"),
    58: ("...Uh, no me digas...", "Kyousuke"),
    59: ("¡La persona que hizo esta canción es... YO!", "Kirino"),
    60: ("¡¿Whoa...! ¿Tan aura asesina...?!", "Kyousuke"),
}

a70_n = {
    0: "Un Menú Extraño",
    9: "Tengo demasiadas objeciones.",
    10: "¿Por qué tengo que escuchar una canción denpa tan terrible?",
    19: "Ni siquiera tengo energía para replicar...",
    21: "Grrr... Atacándome por estar en silencio...",
    26: "Es una causa perdida... Es inútil decirle algo más...",
    27: "Solo soy un pedazo de roca... Un pedazo de roca sin emociones e inútil...",
    35: "*suspiro*... Estamos hablando de Kirino; seguramente tiene algo bajo la manga...",
}
a70_s = {
    1: ("Espera... ¿Qué querías decir hace un momento?", "Kirino"),
    2: ("P-Pero... esta música es solo una den-", "Kyousuke"),
    3: ("¡Guh!", "Kyousuke"),
    4: ("¿Qué pasa? ¿Tienes algo en contra de mi creación?", "Kirino"),
    5: ("Como dije, esta música es una den-", "Kyousuke"),
    6: ("Ah, entonces es eso. ¡Ya veo!", "Kirino"),
    7: ("¡¿De qué te estás convenciendo?!", "Kyousuke"),
    8: ("¡Estás celoso, cierto?! ¡Después de todo, soy la única con todos los talentos!", "Kirino"),
    11: ("Te quedaste sin palabras después de escucharla, ¿cierto?", "Kirino"),
    12: ("En ese caso, ¿podrías no añadir comentarios innecesarios?", "Kirino"),
    13: ("Bueno, soy tanto inteligente como hermosa. Puedo entender tus celos por la impecable yo-", "Kirino"),
    14: ("¿Impecable, de verdad estás diciendo eso?", "Kyousuke"),
    15: ("Creo que una persona llena de defectos nunca podrá entender.", "Kirino"),
    16: ("¡Yo tampoco quiero entender!", "Kyousuke"),
    17: ("Bueno, te elogiaré por hacer el papel del tsukkomi.", "Kirino"),
    18: ("Creo que lo hiciste bastante bien ahí.", "Kirino"),
    20: ("¿Qué? Si tienes algo que decir, dilo.", "Kirino"),
    22: ("¿Sí? ¿Qué? ¿Vamos? Date prisa.", "Kirino"),
    23: ("Vamos, alábame, la genio con todos los talentos. ¡Date prisa, date prisa, date prisa!", "Kirino"),
    24: ("¡Eres demasiado ruidosa! ¡¿Qué es esta velocidad para hablar?!", "Kyousuke"),
    25: ("¡Como dije! ¡La envidia es fea!", "Kirino"),
    28: ("Además, has estado quejándote sin parar. ¡Es realmente irritante!", "Kirino"),
    29: ("No está bien si esto es suficiente para preocuparte～", "Kirino"),
    30: ("¿H-Hay más?", "Kyousuke"),
    31: ("No te lo diré. Además, lo sabrás para entonces.", "Kirino"),
    32: ("¡¿Qué es eso?!", "Kyousuke"),
    33: ("¡Es obvio que solo quieres decirlo!", "Kyousuke"),
    34: ("Escucharás el coro de esta canción divina pronto. ¡Tenlo en cuenta!", "Kirino"),
    36: ("Entonces, si no tienes quejas, dime 3 puntos buenos de esta canción divina.", "Kirino"),
    37: ("¡De cualquiera - forma! ¡Conquistaré el mundo entero con esto!", "Kirino"),
    38: ("¡¿Qué es eso?! ¡¿De qué mundo hablas?!", "Kyousuke"),
    39: ("Eres ruidoso.", "Kirino"),
    40: ("¡No hay mundo que puedas conquistar con esta canción!", "Kyousuke"),
    41: ("Pronto escucharás el coro de esta canción divina. Tenlo en cuenta.", "Kirino"),
    42: ("Solo haz lo que quieras...", "Kyousuke"),
    43: ("Entonces, si no tienes quejas, dime 3 puntos buenos de esta canción divina.", "Kirino"),
}

a72_n = {
    0: "Pero Es Una Canción Denpa",
    7: "Diablos, esa canción no tiene sentido. ¿Y yo soy el raro?",
    8: "¿O quizás es una pieza de música divina para los que les gusta ese tipo de cosas?",
    9: "...No funciona, no lo entiendo en absoluto.",
    20: "¡El mundo me ha dejado atrás y ha seguido moviéndose!",
    27: "No creo que haya una oportunidad de que esta canción denpa sea seleccionada...",
    28: "Pero ¿de dónde sale esa vitalidad?",
    29: "Hay que admirar su entusiasmo cuando se trata de las cosas que le gustan.",
    31: "Ah, esa Kuroneko...",
    32: "Esa sonrisa condescendiente... ¿Será que...",
    42: "*suspiro* ¿No se cansan alguna vez de esto?",
    48: "Kuroneko se puso los audífonos.",
}
a72_s = {
    1: ("No, por eso dije que esto no es más que una denp-", "Kyousuke"),
    2: ("¡No digas denpa...!", "Kirino"),
    3: ("¡--Guu?!", "Kyousuke"),
    4: ("Realmente no te perdonaré si dices denpa una segunda vez.", "Kirino"),
    5: ("D-Deberías decir eso solo si me hubieras perdonado al menos una vez antes...", "Kyousuke"),
    6: ("Hmph, el hecho de que seas un tonto tan sin sentido es la razón por la que esto es un dolor.", "Kirino"),
    10: ("Pero ¿por qué compusiste esta pieza de repente?", "Kyousuke"),
    11: ("¡Eso es porque esta canción que compuse muy bien podría ser el tema principal de este Comiket de Verano!", "Kirino"),
    12: ("¿Eh? ¿Por qué tu canción se convertiría en el tema principal de un evento tan grande?", "Kyousuke"),
    13: ("¿Podría ser eso lo que Nico Nico Douga estaba anunciando?", "Kuroneko"),
    14: ("¡Exacto!", "Kirino"),
    15: ("Nico Nico Douga... ¿Ese sitio web que aloja todo tipo de videos?", "Kyousuke"),
    16: ("¿Por qué también está solicitando canciones?", "Kyousuke"),
    17: ("Debido a la influencia de los Vocaloids, toneladas de canciones de calidad han sido compuestas por los usuarios.", "Kuroneko"),
    18: ("Es probablemente debido a eso.", "Kuroneko"),
    19: ("A-Así que es así...", "Kyousuke"),
    21: ("Jeje～", "Kirino"),
    22: ("La verdad es... ¡ya he enviado mi solicitud!", "Kirino"),
    23: ("Oh. Sin embargo, solo enviaste tu solicitud, ¿cierto? No es que hayas sido seleccionada-", "Kyousuke"),
    24: ("¡No hay forma de que esta divina pieza de música no sea seleccionada!", "Kirino"),
    25: ("...Huh.", "Kyousuke"),
    26: ("¡¿No es genial?! ¡¿No es incluso estupendo?!", "Kirino"),
    30: ("...Jeje.", "Kuroneko"),
    33: ("¿Eh? Oye, ¿de qué te ríes?", "Kirino"),
    34: ("No, nada realmente.", "Kuroneko"),
    35: ("Estabas pensando que no hay forma de que mi canción sea seleccionada, ¿cierto?", "Kirino"),
    36: ("¿Oh? ¿Será que tú también piensas así ya que lo dijiste tú misma?", "Kuroneko"),
    37: ("Obviamente no. ¿Estás celosa de mis múltiples talentos?", "Kirino"),
    38: ("...Incluso si tienes talento, tu futuro será nada si continúas regodeándote en la autosatisfacción.", "Kuroneko"),
    39: ("¿Eh? ¿Qué estás diciendo?", "Kirino"),
    40: ("Bueno, cálmense, ambas.", "Kyousuke"),
    41: ("Cállate, deberías ayudarme a decir algo.", "Kirino"),
    43: ("Kuroneko, ¿podrías intentar escucharla solo una vez primero?", "Kyousuke"),
    44: ("¿Por qué debo llegar a ese extremo?", "Kuroneko"),
    45: ("¿Hazlo por mí, por favor?", "Kyousuke"),
    46: ("......Supongo que no hay de otra, solo un poco entonces.", "Kuroneko"),
    47: ("¡Jeje～! ¡Escucha mi canción divina!", "Kirino"),
    49: ("¿Cómo está, cómo está? ¡La canción que hice! ¡Es la mejor, no?!", "Kirino"),
    50: (".........", "Kuroneko"),
    51: ("¿No está buena? ¿Muy buena? ¿Extraordinaria?", "Kirino"),
    52: ("¡La canción divina ha aparecido! ¡Quizás la pondré como sonido del sistema de mi 【laptop】 cuando llegue a casa!", "Kirino"),
    53: ("...¿Qué es esta canción?", "Kuroneko"),
    54: ("¡¿Hah?! ¿Tienes problemas con tus oídos?", "Kirino"),
    55: ("¡Oye oye oye! No empiecen a pelear aquí, ¿está bien?", "Kyousuke"),
    56: ("Cuando interfieres la conversación se vuelve complicada, así que cállate.", "Kirino"),
    57: ("...¿Dije algo mal?", "Kyousuke"),
    58: ("Kiririn-shi y Kuroneko-shi están teniendo algo similar a una pelea de enamorados. Es mejor quedarse en silencio y observar hasta que todo se asiente.", "Saori"),
    59: ("...Supongo que sí. *suspiro*...", "Kyousuke"),
}

data = {
    "000scriptAKYO_0066A.obj": build(a66_n, a66_s),
    "000scriptAKYO_0068A.obj": build(a68_n, a68_s),
    "000scriptAKYO_0070T.obj": build(a70_n, a70_s),
    "000scriptAKYO_0072A.obj": build(a72_n, a72_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))