import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

n = {
    203: ("¡Que mi hermana y yo estemos juntos por toda la vida--!", "Akagi"),
    204: ("¡¿Qué?!", "Kyousuke"),
    205: ("¡Whoa! ¡Es demasiado brillante...!!!", "Akagi"),
    206: "¡¿Qué-!? ¿Q-Q-Qué demonios!?",
    207: "¡Podía sentir la luz atravesando mis párpados y entrar en mis ojos!",
    208: "¡¿Qué está pasando en el mundo?!",
    209: ("...", "Kyousuke"),
    210: ("...E-Oye, Kousaka...", "Akagi"),
    211: ("...U-Urgh, ¿Akagi...?", "Kyousuke"),
    212: ("¿Hm? ¿No más «pupupupu»?", "Kyousuke"),
    213: "¿Qué es esto... Estábamos en el lugar subterráneo sospechoso hasta este momento...",
    214: "Pero esto es... un escenario familiar...",
    215: ("...Estábamos en el viaje escolar, ¿verdad?", "Akagi"),
    216: ("S-Sí.", "Kyousuke"),
    217: ("¿Por qué estamos... parados frente a la escuela?", "Akagi"),
    218: ("No me preguntes...", "Kyousuke"),
    219: "Por alguna razón, cuando volvimos en sí, Akagi y yo estábamos parados frente a la escuela.",
    220: "Pero ciertamente estábamos frente al pequeño santuario del Fushimi Inari Subterráneo hace un momento.",
    221: "¿Qué diablos nos pasó...?",
    222: ("¡Onii-chan～!", "???"),
    223: ("¡¿Qué?!", "Kyousuke"),
    224: ("¡Onii-chan～!", "Kirino"),
    225: ("¿Onii-chan? Oye, ¿esa niña es quizás tu hermanita?", "Akagi"),
    226: ("......", "Kyousuke"),
    227: ("Es bastante linda. ¡Pero definitivamente pierde contra mi hermana!", "Akagi"),
    228: "Ciertamente, la persona sin aliento que viene corriendo es Kirino.",
    229: "Pero... ¿Por qué me llamaría «Onii-chan»?",
    230: "Mi cuerpo se llenó de una extraña sensación incómoda.",
    231: ("Onii-chan, ¿qué pasa? ¿No estabas en tu viaje escolar?", "Kirino"),
    232: ("¿K-Kirino...?", "Kyousuke"),
    233: ("Sip, soy yo. Entonces, ¿qué hay con eso?", "Kirino"),
    234: "La Kirino que apareció frente a mí me llamó «Onii-chan», y encima de eso, una gran y brillante sonrisa flotaba en su rostro.",
    235: ("¿Q-Qué te pasa...?", "Kyousuke"),
    236: ("¿Qué quieres decir?", "Kirino"),
    237: ("B-Bueno, uh...", "Kyousuke"),
    238: ("¿Será que... te sentiste solo porque no pudiste verme, así que volviste antes que los demás?", "Kirino"),
    239: ("E-Eso es imposib-", "Kyousuke"),
    240: ("Si ese es el caso, estoy feliz. ¡Yo también me siento sola cuando Onii-chan no está aquí!", "Kirino"),
    241: ("...¿Eh?", "Kyousuke"),
    242: "¿Qué? ¡¿Qué clase de trampa es esta!? En realidad, ¡¿con quién estoy hablando?!",
    243: "Kirino es más como, bang, wham, gyah! ¡Algo así!",
    244: ("...Es el efecto del Fushimi Inari Subterráneo.", "Akagi"),
    245: ("¿Qué?", "Kyousuke"),
    246: ("¡Nuestro deseo llegó al Fushimi Inari Subterráneo! ¿¡Esto significa, que mi hermana también!?", "Akagi"),
    247: "Por tu lógica, lo que estás diciendo es que tu deseo también me afectó a mí, ¿y esto cambió la personalidad de Kirino?",
    248: "¡Su personalidad es un giro de 180 grados completo! ¡Es completamente diferente!?",
    249: "¡¿Qué demonios es esto!? ¡En primer lugar, yo no deseé nada!!",
    250: ("Oye, Akagi...", "Kyousuke"),
    251: ("¡¡Oooohhh!! ¡¿Dónde está mi hermana-!!", "Akagi"),
    252: ("¿Oye～?", "Kyousuke"),
    253: "Sin escuchar ni una palabra de lo que dije, Akagi salió disparado.",
    254: "¿La hermana de Akagi realmente se volvió así también?",
    255: "Ni siquiera puedo imaginarlo...",
    256: ("......", "Kirino"),
    257: ("¿Kirino? ¿Algo mal?", "Kyousuke"),
    258: ("Onii-chan, ¿estuviste con ese tipo durante todo el viaje?", "Kirino"),
    259: ("Ese tipo... Te refieres a Akagi? Bueno, así es.", "Kyousuke"),
    260: ("¿Por qué?", "Kirino"),
    261: ("¿Por qué... porque somos amigos... más o menos.", "Kyousuke"),
    262: ("No puede ser. No vuelvas a hacer ese tipo de cosas.", "Kirino"),
    263: ("¿Huh?", "Kyousuke"),
    264: ("Estaría bien si Onii-chan solo está conmigo.", "Kirino"),
    265: ("¿Qué te pasa?", "Kyousuke"),
    266: ("¡Onii-chan solo necesita estar solo conmigo!", "Kirino"),
    267: ("Oye, Kirino...", "Kyousuke"),
    268: ("Y, ¡esa persona! ¡Esa chica!!", "Kirino"),
    269: ("¿Quién es esa chica?", "Kyousuke"),
    270: ("¡Esa persona! ¡¡La Chica Común!!!", "Kirino"),
    271: ("¿Chica común...? ¿Qué pasa con Manami?", "Kyousuke"),
    272: ("¡No digas su nombre! ¡No dejes que nada de ella toque tus labios!", "Kirino"),
    273: ("E-Oye...", "Kyousuke"),
    274: ("Por favor, mira solo a mí, pronuncia solo mi nombre.", "Kirino"),
    275: ("Dices eso, pero ella es una amiga de la infancia.", "Kyousuke"),
    276: ("¡No me importa! ¡Soy tu hermanita! ¡Estoy más cerca de ti! ¡Estoy más cerca de ti de lo que esa persona jamás estará!", "Kirino"),
    277: "El momento en que mencioné el nombre de Manami, la expresión de Kirino cambió completamente.",
    278: "Es como si estuviera celosa sin medida... Espera, ¿celosa?",
    279: "¿Por qué está celosa de Manami?",
    280: ("Así es... no solo la Chica Común. Kuroneko, y Saori, y Ayase...", "Kirino"),
    281: ("¿Kirino?", "Kyousuke"),
    282: ("Cada una de ellas está apuntando a Onii-chan. ¿Por qué no me di cuenta hasta ahora?", "Kirino"),
    283: ("¿Q-Qué estás diciendo...", "Kyousuke"),
    284: ("No hay problema. No dejaré que nadie te ponga un dedo encima, y solo yo tengo permitido hacer eso.", "Kirino"),
    285: ("Oye, Kirino...", "Kyousuke"),
    286: ("No te dejaré acercarte a esas gatas hembras.", "Kirino"),
    287: ("¡¿Cómo puedes decir eso de tus amigas?!", "Kyousuke"),
    288: ("¡No necesito amigas que estén apuntando a Onii-chan!", "Kirino"),
    289: ("¡Kirino! ¡Cálmate!", "Kyousuke"),
    290: ("¡Estoy muy calmada! Solo amo mucho a Onii-chan.", "Kirino"),
    291: ("E-Espera un momento, oye...", "Kyousuke"),
    292: "¡¿De qué diablos está hablando?!",
    293: "¡¿Me ama? ¡Eso es extraño!",
    294: "¡No necesito este desarrollo de la trama en mi vida!",
    295: ("Honestamente, ¿qué te pasa?", "Kyousuke"),
    296: ("Onii-chan es muy amable. Pero esta amabilidad engañará a otros, así que es mejor que te detengas.", "Kirino"),
    297: ("No, no estoy tratando de engañar a nadie.", "Kyousuke"),
    298: ("Afectándolos subconscientemente, eh...", "Kirino"),
    299: ("Oye, ¿siquiera estás escuchando?", "Kyousuke"),
    300: ("Si se hace subconscientemente, entonces no hay remedio...", "Kirino"),
    301: ("Kirino. Oyeééé.", "Kyousuke"),
    302: ("Ya veo. Si Onii-chan no puede salir solo, entonces todo estará bien.", "Kirino"),
    303: ("...¿Eh?", "Kyousuke"),
    304: ("Está bien, Onii-chan. Estaré siem～pre a tu lado.", "Kirino"),
    305: ("No, no. Está bien. Está bien solo por mí mismo.", "Kyousuke"),
    306: ("¡Eso no servirá!", "Kirino"),
    307: ("¡Hiee!!!", "Kyousuke"),
    308: "Tengo la corazonada de que debería escapar o si no...",
    309: "Cuando estaba a punto de mover mi cuerpo, Kirino agarró mi brazo.",
    310: ("Está bien...", "Kirino"),
    311: ("K-Kirino, suelta.", "Kyousuke"),
    312: ("¿Por qué?", "Kirino"),
    313: ("Mi brazo, duele...", "Kyousuke"),
    314: ("Solo lo estoy sosteniendo ligeramente.", "Kirino"),
    315: "Sin soltar su sonrisa, Kirino sostuvo mi brazo fuertemente con sus manos.",
    316: "En este momento, escuché un ruido de rechinido.",
    317: "¡¿Qué clase de fuerza es esta...!",
    318: ("¡Ou-¡Auch! ¡Realmente duele!", "Kyousuke"),
    319: ("Es solo por un momento corto.", "Kirino"),
    320: ("¡E-Oye! ¡Kirino!", "Kyousuke"),
    321: ("Brazos, piernas... y luego, dedos también...", "Kirino"),
    322: ("¡Kirino! ¡¡Kirino!!", "Kyousuke"),
    323: ("Está bien, Onii-chan. Esto es por el bien de que estemos juntos para siempre.", "Kirino"),
    324: "Lo que Akagi deseó en el santuario hace un momento vino a mi mente.",
    325: "«Que mi hermana y yo estemos juntos por toda la vida»",
    326: "No... ¡Esto no es lo que significaba!",
    327: "¡Definitivamente no!",
    328: ("Llevémonos bien de ahora en adelante.", "Kirino"),
    329: "Mientras miro a Kirino diciendo eso con una dulce sonrisa, mi cuerpo se enfrió hasta los huesos.",
    330: "Si no escapo, pasará algo impensable.",
    331: "Es lo único que pude deducir de toda la situación.",
    332: ("Mi Onii-chan～ Solo para mí～", "Kirino"),
    333: "Kirino dijo eso con una sonrisa y una voz adorable.",
    334: "En un instante, mi brazo fue doblado a la fuerza en la dirección opuesta.",
    335: ("Onii-chan, estaremos juntos para siempre!", "Kirino"),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
e = current["000scriptHKYM_0000E.obj"]
for k, v in n.items():
    k = str(k)
    e[k] = v if isinstance(v, str) else "「" + v[0] + "」"
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated 000scriptHKYM_0000E.obj (part 2)")