import json

PATH = "/mnt/c/Users/christ-gm/Desktop/code/oreimo/work/disc1/Data/Translation.json"

def build(narration, speech):
    out = {}
    for i, t in narration.items():
        out[str(i)] = t
    for i, t in speech.items():
        out[str(i)] = "「" + t[0] + "」"
    return out

a140_n = {
    0: "Ruta de Kirino · Es Imposible Que El Caso Con Mi Hermanita Esté Cerrado",
    7: "Mientras rodeaban a este impotente, Saori, Kuroneko y Kirino se rieron.",
    8: "En fin, ya ha pasado bastante tiempo desde la última vez que los cuatro nos reunimos así. Porque las agendas diarias de nosotros cuatro no coinciden muy bien.",
    9: "Y hoy es el primer día del Comiket.",
    10: "No podemos darnos el lujo de perder este día, así que todos hicieron todo lo posible por reorganizar sus planes solo para reunirse.",
    11: "Si es así, no puedo estar deprimido todo el tiempo. ¡Tengo que animarme por primera vez en mucho tiempo!",
    21: "Eso es genial. Kirino. Volviste a venir a jugar con todos una vez más.",
    26: "Escuchamos una canción denpa amateur en cuanto pisamos el salón de convenciones. Pero realmente era una melodía bastante misteriosa, que aterradoramente",
    27: "se quedaba en tus oídos y de alguna manera hacía que tu corazón latiera emocionado cuanto más la escuchabas.",
    29: "No mientas, mocosa.",
    30: "Saltaste de alegría en la casa en cuanto supiste que la iban a usar, e incluso presumiste ante mí todos los días.",
    42: "Aunque eso dije, lentamente coloqué mis manos sobre mis oídos.",
    48: "...Al final, incluso después de que terminara el asunto de su pérdida de memoria, la relación entre Kirino y yo no ha cambiado mucho de antes.",
    49: "Sin embargo, creo que eso está bien por ahora.",
    50: "Si nuestra relación fuera a cambiar tan fácilmente debido a los recuerdos de Kirino, quiero mantener esta cómoda distancia por un poco más de tiempo.",
    51: "...Sí, bueno... está bien pensar de esa manera, ¿verdad?",
}
a140_s = {
    1: ("¡Yupi, el caso de la pérdida de memoria de Kiririn-shi ha llegado a su fin! ¡El mundo está en paz otra vez!", "Saori"),
    2: ("No cierres las cortinas tan dramáticamente así. En esa frase final, no incluiste cuánto esfuerzo puse y el sufrimiento que pasé hasta", "Kyousuke"),
    3: ("ahora, ¿sabes?", "Kyousuke"),
    4: ("Quien siembra vientos recoge tempestades. Aunque nadie te pidió ayuda, Senpai simplemente se entrometió, ¿no?", "Kuroneko"),
    5: ("Sí, sí. No hay nada más molesto que eso.", "Kirino"),
    6: ("Y-Yo sé que ustedes... ¿podrían ser un poco más amables conmigo...?", "Kyousuke"),
    12: ("Y aquí pensé que estabas deprimido, ¿por qué de repente empezaste a sonreír?", "Kirino"),
    13: ("Y-Yo... ¿cómo puedes decirle eso a tu hermano mayor que acaba de recomponerse?", "Kyousuke"),
    14: ("Jeje... Mírate quién habla, tus labios se han estado ensanchando desde hace rato. Tu cara se ve incluso más redonda que antes.", "Kuroneko"),
    15: ("¡¿Q-Qué?! ¡¿Cómo podría ser eso?!", "Kirino"),
    16: ("Si quieres pelea, te complaceré, maldita gata.", "Kirino"),
    17: ("Mero humano. Te reduciré a cenizas.", "Kuroneko"),
    18: ("Ahh, una obra escenificada ha vuelto a empezar.", "Kyousuke"),
    19: ("Jajaja, las dos están igual que siempre.", "Saori"),
    20: ("Sí, es verdad.", "Kyousuke"),
    22: ("Sin embargo, estamos por llegar a la entrada, así que ya es hora de... detenerse...", "Saori"),
    23: ("¿Eh? ¡¿Esto es?! ¡Kiririn-shi, Kuroneko-shi, guarden silencio por un momento!", "Saori"),
    24: ("¿Eh...?", "Kuroneko"),
    25: ("...Ah, esta es mi canción...", "Kirino"),
    28: ("Ah, ahora que lo pienso, recibí una notificación el otro día diciendo que la iban a usar. Lo había olvidado por completo.", "Kirino"),
    31: ("Bueno, es una canción que hice yo, así que es natural.", "Kirino"),
    32: ("Sí, como se espera de Kiririn-shi. Ya eres una chica polifacética del mundo femenino otaku.", "Saori"),
    33: ("¡¿Verdad, verdad?! Bueno, cualquier cosa que haga será de nivel profesional.", "Kirino"),
    34: ("Hmph, esto es más conocido como el que mucho abarca, poco aprieta.", "Kuroneko"),
    35: ("Fufu, ¿me tienes celos?", "Kirino"),
    36: ("...En realidad te estoy alabando.", "Kuroneko"),
    37: ("Sin embargo... estaremos aquí todo el día, ¿no? Será realmente insoportable si tenemos que escuchar esta canción denpa por horas.", "Kyousuke"),
    38: ("¿No está bien? Deléitate por completo con mi talento.", "Kirino"),
    39: ("Oye, Saori. ¿Hay algún lugar aquí que venda tapones para los oídos?", "Kyousuke"),
    40: ("Fufufu, Kyousuke-shi, deberías escucharla como un hermano mayor.", "Saori"),
    41: ("Tch... Sí, sí. Lo entiendo.", "Kyousuke"),
    43: ("¡O-Oye, ¿por qué estás tratando de taparte los oídos?!", "Kirino"),
    44: ("¡Eso es obvio! ¡Si escucho este tipo de denpa por horas, mi cerebro se derretirá o se convertirá en gelatina!", "Kyousuke"),
    45: ("¡¿Qué dijiste...!", "Kirino"),
    46: ("¡Escucha! ¡Escúchala! ¡Escucha mi canción!!", "Kirino"),
    47: ("¡Guwa!", "Kyousuke"),
}

a150_n = {
    0: "Ruta de Kirino · Es Imposible Que Yo Me Mantenga Cuerdo Mientras Escucho La Canción De Mi Hermanita",
    1: "Hoy es el día del Comiket.",
    2: "Cuando los cuatro nos reunimos por primera vez en mucho tiempo, nos encontramos con una escena increíble en el salón de convenciones.",
    8: "Pero, ahora es verano.",
    9: "En fin, pensar que esta canción denpa hiperactiva sería seleccionada, realmente parece que hay algo mal con el mundo en el que vivo.",
    13: "E-Estas dos son aterradoramente las mismas de siempre.",
    14: "Al final, todos mis duros esfuerzos fueron en vano, y los recuerdos otaku de Kirino no volvieron.",
    15: "Estaba preocupado por lo que pasaría con su relación con Kuroneko y Saori... pero parece que no tenía por qué estarlo.",
    16: "Ser exactamente como solían ser... ya no es posible, pero ambas parecen querer recuperar el pasado perdido, y así no hacen nada más que",
    17: "pelear repetidamente cada vez que se ven.",
    18: "Bueno, en su caso, seguramente está bien así.",
    24: "O-Oye, espero que no vayas a decir algo como que es asqueroso de repente y que quieras irte a casa.",
    27: "¡¿Hasta dónde vas a malinterpretarme?!",
    29: "Eso es un malentendido de su parte. Eras una hermanita horrible en aquel entonces que ni siquiera me saludaba cuando nos veíamos.",
    36: "Recientemente, Kirino ha vuelto a jugar juegos de hermanitas. Parece que está tratando de recuperar aunque sea un poco de sus recuerdos.",
    37: "Aunque es digno de elogio tener esa actitud proactiva... ahora es una existencia aún más peligrosa con su conocimiento otaku",
    38: "incompleto de lo que lo era la Kirino anterior.",
    39: "Se dice comúnmente que es más peligroso darles armas de fuego a los aficionados que a los profesionales.",
    49: "Al final, los recuerdos de Kirino no volvieron.",
    50: "Sin embargo, no estamos tan desanimados por eso. Si me preguntas por qué, es porque mi hermanita es una chica presumida, super estudiante de secundaria que",
    51: "cumple sus propias palabras.",
    52: "Incluso si nos rindiéramos, sus recuerdos están destinados a volverle algún día.",
}
a150_s = {
    3: ("¡Sí, todavía siento que es una buena canción sin importar cuántas veces la escuche!", "Kirino"),
    4: ("¡El organizador de este evento tiene muy buen gusto por haber elegido mi canción!", "Kirino"),
    5: ("...No, ¿no dijiste el otro día que era asquerosa y detestable?", "Kyousuke"),
    6: ("Jajaja, los pensamientos de una doncella cambian como el cielo de otoño, Kyousuke-shi.", "Saori"),
    7: ("*suspiro*...", "Kyousuke"),
    10: ("Has estado ruidoso como una persona ignorante del mundo real desde antes. Conoce tu lugar, mis oídos han estado sufriendo desde que entré aquí.", "Kuroneko"),
    11: ("¿Huh? ¿No podrías no desquitarte conmigo solo porque tu círculo no pudo participar?", "Kirino"),
    12: ("Esta vez estoy ocupada haciendo un juego... Así que no tuve tiempo de crear un libro.", "Kuroneko"),
    19: ("¡Espera, ¿cuándo caminaste a mi lado?! ¡Además, por qué tus labios están tan cerca de mi oreja?!", "Kyousuke"),
    20: ("¡Shh! Hay algo que he querido escuchar de ti.", "Kirino"),
    21: ("...¿Querer escuchar?", "Kyousuke"),
    22: ("D-Dime...", "Kirino"),
    23: ("¿Q-Qué es?", "Kyousuke"),
    25: ("Nosotros... no hicimos nada extraño... antes de que perdiera mis recuerdos, ¿verdad?", "Kirino"),
    26: ("¡No hicimos---!", "Kyousuke"),
    28: ("E-Eso es porque... cuando pregunté, ambas dijeron que éramos muy cercanos.", "Kirino"),
    30: ("A-Además...", "Kirino"),
    31: ("...Me ha desaparecido algo de mi ropa interior... ¿podría ser que tú fuiste el que las robó?", "Kirino"),
    32: ("¡No! ¡Definitivamente no! ¡¿En qué parte de este mundo existe un hermano mayor que se excite robando la ropa interior de su hermanita?!", "Kyousuke"),
    33: ("Debes haber tomado mi ropa interior para olerlas, ¿me equivoco?", "Kirino"),
    34: ("¡Eso es lo que les haces a las hermanitas 2D de tus juegos! No lo mezcles con el 3D.", "Kyousuke"),
    35: ("¿Q-Qué? ¡«Onii-pan» es una obra maestra!", "Kirino"),
    40: ("En fin, no sé dónde han ido a parar tus panties.", "Kyousuke"),
    41: ("...¿Cómo supiste... que las que faltan son las «panties»?", "Kirino"),
    42: ("¿¿Podría ser...?!", "Kirino"),
    43: ("D-Detente... F-Fue cuando se lo estabas contando a Mamá, yo solo... solo lo escuché por accidente.", "Kyousuke"),
    44: ("Hmph...", "Kirino"),
    45: ("Jajaja. Los hermanos Kousaka se están llevando bien hoy también, incluso sin que sus recuerdos hayan vuelto aún.", "Saori"),
    46: ("Jeh... qué par de casos perdidos de siscon y brocon.", "Kuroneko"),
    47: ("¡Dejen de hablar y sálvenmeeeeeeeeee～!", "Kyousuke"),
    48: ("¡Tú... siscon pervertido------!!", "Kirino"),
    53: ("¡Solo espera! ¡Voy a arreglar esos recuerdos míos definitivamente por cualquier medio posible!", "Kirino"),
}

a160_n = {
    0: "Ruta de Kirino · Mi Hermanita No Puede Ser Tan Linda",
    1: "En el día del Comiket.",
    2: "Kirino y yo nos reunimos con Kuroneko y Saori antes de entrar al salón de convenciones.",
    3: "Básicamente pasé toda la mañana tratando de evitar que Kirino y Kuroneko pelearan y siendo golpeado por Kirino después de que descubriera el doujinshi de una",
    4: "doncella con gafas, pero bueno, fue divertido, supongo.",
    5: "Y en la tarde, se supone que nos reuniríamos frente al puesto para participar en el evento especial que Saori recomendó.",
    6: "...es como debería haber sido, pero...",
    21: "¿Amor, amor por quién? ¿Amor por las hermanitas 2D?",
    22: "Ahh... Me duele la cabeza solo de pensar en esas cosas extrañas...",
    23: "Maldición, esa Saori... Haciendo esa cara de :3 otra vez... ¡Definitivamente se está divirtiendo con esto!",
    31: "Mierda... ¿Nos separamos en la multitud?",
    32: "... Hay demasiada gente, parece que será muy difícil encontrarla.",
    33: "Bueno, están en algún lugar de este salón de todos modos. Se siente solitario, pero solo miraré por mi cuenta.",
    34: "...Pero en fin, es un evento realmente grandioso.",
    35: "El escenario es excesivamente extravagante... El escenario instalado especialmente hasta tiene chicas que parecen ídolos.",
    36: "Además, esas chicas se ven de muy alto nivel. ¿Podrían ser ídolos realmente populares?",
    40: "¡¿Por qué Kirino y Kuroneko están ambas en este escenario rodeadas de vítores, y además cuándo subió también Saori hasta allí?!",
    45: "Oye, oye, ¿está bien? Parece que le está costando bastante, lo cual es inusual en ella.",
    46: "¿Hmm? Parece que hay algunos susurros saliendo de los altavoces...",
    58: "Oye, ustedes, podemos escuchar perfectamente todo lo que dicen...",
    59: "Y Kuroneko, deja de ponerme como ejemplo...",
    60: "¡Oh! Pero parece que los nervios de Kirino se han calmado ahora.",
    62: "Jeh, como se esperaba de mi hermanita... Hasta ese discurso de apertura lo dijo bien...",
    63: "Sin embargo, parece que está echando un vistazo en mi dirección de vez en cuando...",
    64: "Bueno, probablemente es mi imaginación.",
    66: "...¿Qué?",
    67: "¿Un Onii-chan irreemplazable? ¡¿Kirino tiene otro hermano mayor?!",
    68: "Espera, eso es imposible...",
    69: "...Entonces, esas palabras de hace un momento... ¿Podría ser...",
    71: "Tan pronto como la canción comenzó, la atmósfera alrededor del escenario alcanzó su punto máximo.",
    72: "En medio del salón, mientras una extraña emoción y entusiasmo giraba a mi alrededor, logré verlo a través de la multitud de otakus.",
    73: "La brillante sonrisa que mi hermana me dio mientras me guiñaba el ojo, una sonrisa que sentía como si estuviera poniendo todo su ser de esta vida... no, incluso de su",
    74: "vida anterior y de la próxima en ella.",
    99: "...Entiendo ahora. Lo que más temía de que Kirino perdiera sus recuerdos.",
    100: "Era el miedo de que nuestra relación de hermanos volviera a ser como era antes.",
    101: "No quería que perdiera solo los recuerdos de este último año en el que nuestra relación de hermanos mejoró un poquito.",
    102: "Viendo a Kirino sonriendo con sus amigas, con su cara sonrojada por alguna razón, con sus recuerdos recuperados...",
    103: "...De repente, esto vino a mi mente:",
    104: "【Mi Hermanita No Puede Ser Tan Linda.】",
}
a160_s = {
    7: ("Dios, ¿a dónde fueron las dos?", "Kyousuke"),
    8: ("Ya, ya, contrólate, Kyousuke-shi. Las dos probablemente tenían productos que cada una quería comprar esta tarde.", "Saori"),
    9: ("Pero, dejando de lado a Kuroneko, Kirino acaba de recuperar sus recuerdos, así que ¿qué haremos si vuelve a golpearse la cabeza en un lugar así?", "Kyousuke"),
    10: ("Jajaja, Kyousuke-shi realmente se preocupa por su hermanita.", "Saori"),
    11: ("Oye, ¿tienes idea de los problemas que pasé durante todo este incidente? Si tuviera que vivirlo otra vez, probablemente moriría de agotamiento.", "Kyousuke"),
    12: ("No hay necesidad de preocuparse, golpearse la cabeza no resulta en pérdida de memoria así.", "Saori"),
    13: ("Le pregunté a un conocido en un hospital sobre eso, y supe que la mayoría de las causas de la pérdida de memoria son lesiones externas o emocionales.", "Saori"),
    14: ("En el caso de Kiririn-shi, la causa real probablemente fue el estrés.", "Saori"),
    15: ("Estrés... Huh. Ese es un concepto completamente ajeno a ella.", "Kyousuke"),
    16: ("Con todo respeto, sí tengo una idea de cuál podría ser la causa del estrés de Kiririn-shi.", "Saori"),
    17: ("Qué, dímelo sin darle tanto aire de importancia.", "Kyousuke"),
    18: ("Huhu, Kiririn-shi probablemente está hambrienta de amor.", "Saori"),
    19: ("...¿Huh?", "Kyousuke"),
    20: ("¿Qué fue eso? ¿Esa palabra, que es la que menos le queda a Kirino de todas las palabras del mundo entero?", "Kyousuke"),
    24: ("Bueno entonces, el evento está por empezar, así que vamos.", "Saori"),
    25: ("¿Eh? E-Espera. ¡¿No deberíamos esperar a Kirino y Kuroneko?!", "Kyousuke"),
    26: ("Las dos ya fueron allí delante de nosotros. ¡Ven, vamos a reunirnos con ellas en el área de cosplay!", "Saori"),
    27: ("¡O-Oye! ¡No me empujes!", "Kyousuke"),
    28: ("¡Woah! ¡¿Qué es este entusiasmo?!", "Kyousuke"),
    29: ("¿No parece que todos los que asistieron al Comiket hoy están reunidos aquí? Dime, Saori...", "Kyousuke"),
    30: ("...¡¿No está aquí?!", "Kyousuke"),
    37: ("Ahora que lo pienso, siento que las he visto antes...", "Kyousuke"),
    38: ("Eh...", "Kyousuke"),
    39: ("¡¿Eh... Eeeeeeeeh!?", "Kyousuke"),
    41: ("Todos, gracias por esperar. El evento de presentación de la canción principal está por comenzar.", "Announcer"),
    42: ("El discurso de apertura será de Kiririn-san, quien proporcionó la canción principal para el Comic Circle Market de este verano.", "Announcer"),
    43: ("...Hola a todos, soy Kiririn.", "Kirino"),
    44: ("Gracias por permitirme asistir al evento de presentación de este año. Umm... E-Esta... Esta...canción...", "Kirino"),
    47: ("Hmph, poniéndose nerviosa por una cosa tan trivial. Por eso los plebeyos no son más que dolores de cabeza.", "Kuroneko"),
    48: ("¡C-Cállate! Tengo sentido de la vergüenza, a diferencia de ti.", "Kirino"),
    49: ("Tiene razón, Kuroneko-shi. Cualquiera también se pondría nervioso al confesarse con la persona que le gusta.", "Saori"),
    50: ("Esto y eso son dos cosas completamente diferentes.", "Kirino"),
    51: ("¿Oh? Estaba segura de que estabas aquí para una confesión a un hermano mayor...", "Kuroneko"),
    52: ("¿Huh? ¿Quién se confesaría con ese tipo...!", "Kirino"),
    53: ("¿Ese tipo? Aunque dije un hermano mayor, no dije que fuera TU hermano mayor.", "Kuroneko"),
    54: ("¡Q-Q-Q-Qué...!", "Kirino"),
    55: ("Ya, ya... ambas, por favor deténganse aquí.", "Saori"),
    56: ("...Tch.", "Kirino"),
    57: ("Hmph...", "Kuroneko"),
    61: ("E-Esta canción fue creada por el bien de un Onii-chan presente aquí.", "Kirino"),
    65: ("Para el único e irreemplazable Onii-chan...", "Kirino"),
    70: ("...Ahora comenzaré a cantar. Por favor escuchen con atención... Aniki①", "Kirino"),
    75: ("Buen trabajo. Lo hiciste inesperadamente bien allí.", "Kyousuke"),
    76: ("E-Eso es obvio. Después de todo, yo soy la que cantaba.", "Kirino"),
    77: ("Sí, sí. Tienes razón. Ah, por cierto...", "Kyousuke"),
    78: ("Al final, Kirino, ¿por qué perdiste tus recuerdos?", "Kyousuke"),
    79: ("¿Eh? ¿Por qué preguntas eso ahora?", "Kirino"),
    80: ("No hay una razón en especial, solo lo pensé de repente. Entonces, ¿cuál fue la razón?", "Kyousuke"),
    81: ("Y-Yo recuerdo que en ese momento... estaba charlando con las otras dos y luego de repente me emocioné!", "Kirino"),
    82: ("Hmm, ¿de qué era? ......¡Ah!", "Kirino"),
    83: ("¡Probablemente me emocioné demasiado y me resbalé de las escaleras mientras iba a buscar un jugo de frutas, sí!", "Kirino"),
    84: ("...¿Qué fue lo que te emocionó tanto como para que cayeras de las escaleras?", "Kyousuke"),
    85: ("E-Eso fue... umm, ¡eso es! ¡Me emocioné mucho discutiendo sobre un juego nuevo～! ¡Ah-ajajaja!", "Kirino"),
    86: ("Eres realmente un caso perdido...", "Kyousuke"),
    87: ("...Hmph. ¿De verdad estábamos discutiendo eso?", "Kuroneko"),
    88: ("Ahh, ¡así que era sobre eso!", "Saori"),
    89: ("¿Eh? ¿De qué están hablando?", "Kyousuke"),
    90: ("...! ¡Ustedes dos, deténganse ahora mismo! ¡No digan nada innecesario!!", "Kirino"),
    91: ("En ese momento... estabas parloteando alegremente sobre que Senpai volviera a casa al día siguiente.", "Kuroneko"),
    92: ("¡¿Qué-! Y-Yo nunca dije esas cosas!", "Kirino"),
    93: ("¿Oh, en serio? ¿Entonces la manera en que hablabas alegremente de esperar el recuerdo de su viaje fue una alucinación?", "Kuroneko"),
    94: ("¡¡Guhhhh!! ¡¿Qué te pasa?! ¡Ya dije que nunca dije esas cosas!!", "Kirino"),
    95: ("¡¿Auch?! ¡¿Por qué me pateaste?!", "Kyousuke"),
    96: ("¡Cállate!! No he recuperado esa parte de mi memoria, ¡así que no sé nada!", "Kirino"),
    97: ("¡¡No sé-!!!!!", "Kirino"),
    98: ("¡¡Nada en absoluto, ¿de acuerdo?!!!!!", "Kirino"),
}

data = {
    "000scriptBKIR_0140E.obj": build(a140_n, a140_s),
    "000scriptBKIR_0150E.obj": build(a150_n, a150_s),
    "000scriptBKIR_0160E.obj": build(a160_n, a160_s),
}

with open(PATH, "r", encoding="utf-8") as f:
    current = json.load(f)
for file, entry in data.items():
    if file not in current:
        current[file] = entry
    else:
        current[file].update(entry)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(current, f, ensure_ascii=False)
print("updated:", list(data.keys()))
